### PR TITLE
Upgrade to bundler 2

### LINKED ISSUE #5193: Upgrade to bundler v2
### What we should change and why (this is tech debt)
We should upgrade to latest bundler 2.

I cant see why we cant upgrade after we have moved to ruby 2.3. I may be missing something.

### Impact and timeline
I am not really sure.

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5193

I just run
bundle update --bundler

I wonder if that's all it takes.
No reference to bundler v1 in ofn-install as far as I can see.

#### What should we test?

green build and green deploy.

#### Release notes

Changelog Category: Technical changes
Upgrade bundler.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
It'll definitely need some corresponding changes in ofn-install (and testing the transition scenario during a deployment) :+1:

**Review by Matt-Yorkley — APPROVED** [review]
Nice :rocket:

**Review by andrewpbrett — APPROVED** [review]
@Matt-Yorkley you did a test deploy then? I think we can merge if so.

**Comment by Matt-Yorkley** [comment]
Not yet, I'll give it a go today :+1:

**Comment by Matt-Yorkley** [comment]
Looks good for deployment :tada:

**Pull request merged**
