### PR TITLE
fix the pending invoice print spec

### LINKED ISSUE #7983: Tax amounts from Adjustments on regular invoice not displayed correctly
## Description

Follow-up issue on point 6), see [testing notes here](https://github.com/openfoodfoundation/openfoodnetwork/pull/7805#issuecomment-886766743).

Relates to #7933.

There are some inconsistencies introduced by PR #7805 in what concerns the displaying of Tax amounts on the regular invoice, for both inclusive and added-tax instances, which can be confusing to users:

(UPDATED to reflect the improvements introduced on #7989)

- `Line items` do not display any value on `Sales Tax`~~/`GST`~~
~~- `Shipping` displays 0.00 despite having an associated tax value~~
- Added-tax instances: an `added adjustment` displays the correct tax value
- Inclusive-tax instances: an `added adjustment` displays the correct tax value but additionally displays the wording `(included)`; this entry is not centered on the column.

## Expected Behavior

**Added-tax instances**

The regular invoice should display the `Sales Tax` correctly for all line items, shipping and added adjustments correctly or (instead) this should be omitted for all of these.

**Inclusive-tax instances**

The regular invoice should display the `GST` correctly for all line items, shipping and added adjustments correctly:
- the wording `(included)` appears next to the GST value; this entry is not centered

## Actual Behaviour

Information is displayed inconsistently on the regular invoice (see pics).

## Steps to Reproduce

1. Place orders where tax is applied for both added- and inclusive-tax instances.
2. Check the regular invoice, for the respective instances, namely:
3. Added-tax -> the `Sales Tax` column; Inclusive-tax -> the `GST` column
4. Notice the inconsistencies (pics below)

## Animated Gif/Screenshot

- Added-tax -> the `Sales Tax` column

- Inclusive-tax -> the `GST` column

## Workaround

A bit confusing.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.8.7
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #7983

1. Fix the pending tests on `spec/system/admin/invoice_print_spec.rb`
2. Display added taxes 
3. Show 0.00$ when there is no taxes or tax amount = 0

#### What should we test?

My focus was on line item taxes on Order printing as PDF when
1. added taxes are in use
2. included taxes are in use
3. no taxes

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by abdellani** [comment]
Hi @filipefurtad0 

I have some questions related to the pending tests. Some expected results are confusing me.

1. Do we show added taxes? or only included taxes?
2. Do we show $0.00 when there're no taxes? when the amount is equal to 0?

image

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

Sorry for the confusion, my bad - pending test case ii) is already working and can be removed. I guess I forgot to update the spec. You can find it a couple of lines below: the correct included amount is already displayed for the enterprise fee ($15.65).

>  Do we show added taxes? or only included taxes?

For the regular invoice: the current behavior already displays included taxes - this is ok and should not be changed.

The change/improvement should be to display the **added** taxes, for this invoice type. This corresponds to the pending test cases iii) iv) and v).

>    Do we show $0.00 when there're no taxes? when the amount is equal to 0?

This is perhaps the only change which concerns included taxes: I think in yes, it would be a nice to have, to see $0.00 when no tax is associated. This corresponds to the pending test case i).

**Comment by abdellani** [comment]
Looks like the expected value of `display_checkout_tax_total` is not checked.
 https://github.com/openfoodfoundation/openfoodnetwork/blob/895fc94a75032ca7c3616b95f7a75fdfd34fd690/spec/views/spree/admin/orders/invoice.html.haml_spec.rb#L24-L27

**Review by mkllnk — APPROVED** [review]
Looking good.

**Review by filipefurtad0 — APPROVED** [review]
Nice!! :+1:

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

An order with **added** taxes:

(left - no enterprise fee; right enterprise fee is set)

## **Before this PR**

image

## **After this PR**

image

We can see that all the taxes are displayed correctly :tada: 
Also, line items with zero tax also display 0.0% now :+1: 


An order with **no taxes**:

### **Before this PR**

image

### **After this PR**

image

This example shows that the header is not displayed, when no taxes are applied to the order - this is minor inconsistency, as the `$0.00` introduced in this PR now has no header. A header was not necessary as the default was not to display zeroes.

I would created an issue to add the header on invoices where taxes are not applied, but would request a quick feedback from @openfoodfoundation/train-drivers-product-owners .

In any case: Merging! Thanks Mohamed.

**Comment by RachL** [comment]
@filipefurtad0 coffee is not kicking in yet for me 😁 Just to be sure, what's a header here?

**Comment by filipefurtad0** [comment]
Hey @RachL ,
I meant the header of the table - sorry I was not clear:

image

Should I create a PR to add this?

**Comment by RachL** [comment]
@filipefurtad0 aaah yes why not. I think it can be a `good first issue` :+1:

**Pull request merged**
