### PR TITLE
Fixes invert columns logic on reports spec

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

This reports spec  was failing locally - again the build was not finding this fail :biohazard: Not sure why... Needs investigation.

This spec was failing locally with:

```
Failures:
  1) 
    As an administrator
    I want numbers, all the numbers!
 behaves like sales tax report generate Tax Rates report
     Failure/Error:
       expect(page).to have_table_row [order1.number, "1446.7", "16.76", "0", "270.08", "286.84",
                                       "1733.54"]
     
       expected to find table row ["R728084366", "1446.7", "16.76", "0", "270.08", "286.84", "1733.54"], got #<Capybara::Session:0x00007f687045cd30>
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_numbers_all_the_numbers_behaves_like_sales_tax_report_generate_tax_rates_report_379.png
     
     Shared Example Group: "sales tax report" called from ./spec/system/admin/reports_spec.rb:296
     # ./spec/system/admin/reports_spec.rb:291:in `block (3 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'
Finished in 18.73 seconds (files took 10.96 seconds to load)
2 examples, 1 failure
```

Open questions:
- Why are we getting the error `got #<Capybara::Session:0x00007f687045cd30>` (sometimes)
- Why is the build not finding this failure previously
- Why does the spec only pass locally with independent `if` statement; and fails with a `if` / `else` statements.

One approach to improve this could be to split this `it` block on `line 279` in different `context` blocks for `inverse_columns_logic` enabled/disabled.

#### What should we test?

Green build.

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
Another open question:
 - why the `inverse_columns_logic` feature toggle inverse those two columns?

**Comment by filipefurtad0** [comment]
> why the inverse_columns_logic feature toggle inverse those two columns?

Agree - I found this very strange as well.

> (i still could not run this spec locally, it seems to last forever)

It could be related to this `got #<Capybara::Session:0x00007f687045cd30>`

I'm not sure the app is behaving correctly, once this feature is toggled... Maybe it needs more testing.

**Comment by jibees** [comment]
> * Why is the build not finding this failure previously



> > why the inverse_columns_logic feature toggle inverse those two columns?
> 
> Agree - I found this very strange as well.

It should not impact the column order as I know (and as I developed this _feature_)

**Comment by jibees** [comment]
Ok, now I know why it failed for my PR: 

Capture d’écran 2022-09-28 à 15 25 07

those two columns aren't selected although they should be. 
Will fix it.

**Review by mkllnk — APPROVED** [review]

**Pull request merged**
