### PR TITLE
[Adjustments] Add index on spree_adjustments.order_id

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

We've added this column recently, and we're starting to use it a lot. This index is added later in Spree. It's a foreign key with high cardinality, so it's a good index candidate. It's also one of our busiest tables.

#### What should we test?

No test?

#### Release notes

Added index on spree_adjustments.order_id

Changelog Category: Technical changes

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
> No test?

Not worth manual testing but we do need a PostgreSQL query plan before and after to see whether or not it'll have an impact.

**Comment by filipefurtad0** [comment]
> PostgreSQL query plan before and after to see whether or not it'll have an impact

I've come across this issue before. Would it make sense for us to set up a performance test tool, on our staging servers, and compare load response/performance before after deploy?

I don't think I can set this up in short notice (so maybe this is out of scope for this PR) but I was considering JMeter for this task.

**Comment by sauloperez** [comment]
I'm very reluctant to go down that path because that would miss half the equation: the production's DB load + concurrent usage + other specifics related to the environment while still having to pay the maintenance cost. I'd rather get our attention on the data we already have in Datadog plus things like https://github.com/openfoodfoundation/openfoodnetwork/pull/7001.

The query plan IMO is proof that this indeed improves the query.

**Comment by sauloperez** [comment]
Merging this so we can include it in the release.

**Pull request merged**
