### PR TITLE
Fix SCA regression

### LINKED ISSUE #6755: SCA-paiyments marked as uncaptured (from orders places in the shopfront)
## Description

After PR #6534, orders placed through the shopfront, and paid with an SCA-card always requiring authentication are marked as uncaptured, both on the Stripe dashboard and in the backoffice of the managing hub (see pics in thread).

The payment state is correctly reflected on Stripe. Order confirmation emails arrive as usual and the customer balance is reflecting the state of the order correctly.

## Expected Behavior

Orders placed through the shopfront and paid with an SCA card requiring authentication should have "Payment State" marked as "Paid", with no need of manually capturing the payment in the BO.

## Actual Behaviour

Orders placed through the shopfront and paid with an SCA card requiring authentication have "Payment State" marked as "Pending" and require manually capturing the payment in the BO.

## Steps to Reproduce

As a customer
1. Place an order in the shopfront and pay it with valid a 3D-auth card
2. Validate the payment

As an admin
3. Go to orders, and check the payment state for that order -> "pending"
4. Edit the order and go to the payments tab -> payment is pending 

## Workaround

Manually capture the payment.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.5
* Browser name and version: Firefox 84
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

### PR DESCRIPTION
**Pull request by andrewpbrett**
This reverts commit bba9e550062c69672111945445796e8b633d19e8.

#### What? Why?

Closes #6755 

#### What should we test?

See #6755 

#### Release notes

Fixed a regression where payments were marked as uncaptured

Changelog Category: User facing changes

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,
In addition to reverting the commit, and considering all the recent work around customer balance:
maybe it would be good to add a spec, to assure that `customer balance = 0`, for all Stripe-SCA payments processed through the shopfront. What do you think?

**Comment by Matt-Yorkley** [comment]
There aren't any tests that failed..?

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by Matt-Yorkley** [comment]
Just to understand a bit more: at this point where the payment has been placed but hasn't been authorized yet, has the money left the customer's account or not?

**Comment by andrewpbrett** [comment]
@Matt-Yorkley it has not left the customer's account until it's captured. Indeed, there aren't any tests that failed, and that's the problem ;-)

**Comment by andrewpbrett** [comment]
Because this involves going to Stripe in order to authorize, it's a little tricky to do a feature spec since real HTTP requests have to be stubbed out in the test suite. I could write a trivial unit test instead, (e.g. check for the case where `cvv_response_message` is present and make sure that we process the payment anyway), but I don't think that's a very good test to write and I think the actual solution should change that behavior anyway. 

I did do a manual test (actually a few manual tests) locally and confirmed that by reverting that commit, the payment no longer shows up as Pending but instead is captured. 

I think this is a high priority to include in the next release, if not before, so I've moved it to the top of Test Ready.

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

Ok, looks like this is reverted correctly - all as before:

- stripe SCA-payments made with valid cards and authentication are captured automatically - no action needed in the BO :+1: 

A quick notice though:
- it seems that in the previous state - i.e., before this fix - orders were being confirmed, even when customers used invalid cards in the shopfront. For example, cards with insufficient funds generated orders which appeared in the BO and "could" be captured, despite the invalid payment. Attempting to capture these generated this error:

https://app.bugsnag.com/open-food-france/coopcircuits/errors/6012d4bdc3f2b90017fea272?event_id=6012d4bd0069a529245a0000&i=sk&m=nw

So, we might be getting notices on this type of error, from orders which were created with invalid cards, since last deployment.

Such orders will not be created any more, after this PR.

Ready to go.

**Pull request merged**
