### PR TITLE
Pi/inventories

### LINKED ISSUE #3116: Unable to import Inventory
## Description
On Australian production the CSV inventory template looks like this:
image
Is this template up to date? Should this template also include On Demand and Category?

I have attempted to import the following csv with the Inventories upload option:
image

I don't fully understand how the Inventory upload tool should operate, so I tested the functionality which I guessed it would have:
**1) In the shop's Inventory, this product was already on the shop's inventory list. It was set to inherit all details from the product list. I wanted to import this csv to override the price from $30 to $20 and stock from 0 to 100 On Hand**
- When I uploaded the csv, I got the following error... despite the fact that this product does exist.
image

image

**2) In the shop's Inventory, this product was in the shop's HIDDEN list. I was testing whether uploading the CSV would move the product into the INVENTORY list**
- I got the same error as above

**3) In the shop's Inventory, this product was in the shop's NEW list. I was testing whether uploading the CSV would move the product into the INVENTORY list**
- First i got an error 'category can't be blank' - this is confusing because the template doesn't include Category
- I added Category (oil and spreads) and then I got the same error as in 1) above.

image

* note screenshots above have inconsistencies with capital letters, but this wasn't the issue
## Expected Behavior
Please tell me how the Inventory upload tool should work?
- Should it be used to move a product from the NEW list to the INVENTORY list?
- Should it be used to only update overrides on a product which is already on the INVENTORY list?
- Should it be used to move a product from the HIDDEN list to the INVENTORY list (and vice versa)?

## Actual Behavior
See description

## Steps to Reproduce
Here's the CSV - https://docs.google.com/spreadsheets/d/1Qby6YOjGuUz0ybz75HrKQwxmQDiYY7gowPYs-d5rQs8/edit#gid=0 
You can try to upload it on Aus production for Producer of Peanuts and Demo Hub

## Severity
s3 - not urgent yet, as the feature isn't launched.

## Your Environment
Aus production 
PC, Chrome

### LINKED ISSUE #3160: update inventory upload template
## Description
Some fields are still missing in the inventory  upload template (product  import feature)
- variant_unit_name (to be confirmed)
- sku
- on_demand

@Matt-Yorkley can you confirm variant_unit_name I have some doubts about the first one, is variant_unit_name needed if I want to update a price or stock for a product that is set up as "item" ? Or is it enough to have the unit type in the inventory template to identify the product ? I wrote in the comment in the template issue that I thought it was needed but you didn't answer.

## Expected Behavior
User can download accurate info to prepare inventory import.

## Actual Behavior
They can't.

## Steps to Reproduce
Go to https://www.openfoodfrance.org/admin/product_import an download inventory upload template, you will see those fields are not it, but you can update sku and on_demand, so they should be in the template.

## Severity
S3

## Context
Spotted by Sally https://github.com/openfoodfoundation/openfoodnetwork/issues/3116

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3116 
Closes #3160

Updated the specs and CSV template for importing into inventories.

#### What should we test?

Product Import: importing into inventory. Check import to inventory works correctly, and existing inventory items set to hidden should be set to visible when updated via import.

#### Release notes

Updated inventory CSV template for Product Import.

Changelog Category: Changed

#### Documentation updates

The template has changed for inventory CSV.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Note: if importing inventory for an existing variant of a product with multiple variants, the `display_name` field has to match.

**Comment by myriamboure** [comment]
Ping @sstead @RachL  something to clearly say in the user guide probably ! awesome @Matt-Yorkley thank you, PI is on the final run !

**Comment by RachL** [comment]
@myriamboure would you be available to test this one? I'm not sure I know all features of inventory well enough. With your testing notes I would then update the user guide, which I think is not describing all the potential of this feature (at least in french).

**Comment by myriamboure** [comment]
Ok I will find time to test this, hopefully today.

**Comment by myriamboure** [comment]
Ok so here are my testing notes: https://docs.google.com/document/d/1QBV4CUplM6GSJl1GQ5sxfLsCwwa4Pe1uRmTfxcwLi9c/edit?usp=sharing

@Matt-Yorkley @kristinalim there is a problem with the new variant override thing. It is not possible to import anything in inventory, it should be possible to change the info in inventory when it is set to "use producer stock info" but it is not, the system blocks and says "count on hand must be blank". Even more annoying is that even after I change in inventory to not use producer stock info, I still get the same error message.

Also it is impossible to import in inventory "items" type products.

So back to in dev, I tried lots of things to come to those conclusions so please check my notes. I linked also the test files I used. @Matt-Yorkley if any question we can plan a 10 min sync touchpoint so we can move that forward.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley am assuming this will be your first priority to get to done when you're back onboard for the year, will hold off moving it back to Dev Ready for now 😈

**Comment by myriamboure** [comment]
@kristinalim isn't it linked to the issue @Matt-Yorkley was talking about that we discussed on Slack ? Anyway I think there is something to change in the way the inventory variant override work has been done so it doesn't block inventory upload. If you have some clue on what to do @kristinalim to share with @Matt-Yorkley please do ;-)

**Comment by Matt-Yorkley** [comment]
@myriamboure The failures you saw were down to the new logic for on_demand validations when using inventories, introduced in #3198 and #3104. I've added a spec here to make sure it's working with product import. I think we just need to update the user guide for this. The new logic is as follows:

- `on_demand` can be set to "true", "false", or blank 
- If it's set to "true", `on_hand` must be blank.
- If it's set to "false", `on_hand` must be filled in. 
- If it's left blank, `on_hand` must be blank.

**Comment by myriamboure** [comment]
I don't understand what you talk about @Matt-Yorkley when you talk about true, false or blank, now the logic is that in inventory you have either:
- "use producer stock info" so then "on-hand" must be blank
- "yes" then "on hand" must be blank
- "no" then "on hand" must have a value.

The problem was that on the work @kristinalim did we said if you want to write on the "on hand" field a value in inventory page you need first to make sure in the "on demand" colum the value is "no". 
So the logic you should follow is:
- if an entry in the inventory import file modify the on hand quantity of a product that has "user producer stock info" or "no" in the on demand column, change the on demand column on "yes" and put the new value.
Do you agree @kristinalim ?

Is that clear @Matt-Yorkley ? I'm pretty confused by what you wrote, if we gain time by talking directly I'm on Slack all the afternoon so ping me and we can talk quickly if unclear.

**Comment by myriamboure** [comment]
Oh or maybe you were talking about the PI user guide @Matt-Yorkley ? Today we put 1 or 0 in on_demand column, does that change ? Now they need to write "true" or "false", that's it ?
Maybe that's just what you meant and what I said above is no point ;-) Just make sure you understood the same as me and what I described is cover and if yeas we can delete my comment ;-)

**Comment by kristinalim** [comment]
I also investigated the specifics.

Agreeing what @Matt-Yorkley said. For the "on_demand" column:

1. If blank - Read as "Use producer stock settings", so "on_hand" should be blank.
2. If "true", "TRUE", or "1" - Read as on demand of "Yes", so "on_hand" should be blank.
3. If "false", "FALSE", or "0" - Read as on demand of "No", so "on_hand" is required.

BUT if you use any unsupported string, it will be considered as on demand of "No" (Scenario 3). So, if you use the text "no", it still works _but only by accident_. If you use "yes" which is also unsupported, the result is not what you would expect: it will ask for an "on_hand" value even if you wanted to set unlimited stock. This can indeed be confusing for users, we use "Yes" and "No" in the inventory page... @myriamboure Did you happen to use these values at some point when testing?

Also noting another detail: If there is an "on_hand" value, on demand is set to "No" automatically if there is no "on_demand" column. However, if there is an "on_demand" column, the column has to be set to "false"/"FALSE"/"0" to be valid.

**Comment by kristinalim** [comment]
There seem to be two separate issues with the failures in your testing notes, @myriamboure.

The later failures are because "on_demand" should be "0"/"FALSE"/"false".

For the first one, @Matt-Yorkley it seems I can replicate this with a product that has "weight" unit (1g) initially but I changed it to "items" (1 item). I get the error whether with "g", "unit", or blank as unit type in the import spreadsheet.

**Comment by myriamboure** [comment]
1- I see one problem then with your last comments @kristinalim, when I import a file into inventory, I might need the on-demand column for some products, but let's say for one product I want to setup a on-hand value, the column is here, but the on-demand column is blank, and that blocks saving...
So:
- if on-demand is blank and there is a on hand quantity, on demand should be switched to false when doing the import.
- if on-demand is blank and there is no on hand quantity, then on demand should be switched to "use producer stock info"

Don't you think ? Or am I missing something ?

So 

> "If there is an "on_hand" value, on demand is set to "No" automatically if there is no "on_demand" column. However, if there is an "on_demand" column, the column has to be set to "false"/"FALSE"/"0" to be valid."
is a problem in term of UX IMO. Let's see if what I said just above is possible :-)

2- Regarding the unvalid values, if anything else than the value expected (FALSE or 0, I think we should decide and only give one option to users to avoid confusion and write it in the user guide) is filled in, the upload should fail and an error message saying "on-demand value is unrecognized, must be TRUE, FALSE or BLANK".

Do you agree @Matt-Yorkley ? @kristinalim I used 0 and 1 in my tests.

3- About the later case about a product that were in weight and moved to item, it seems like a remaining thing to fix @Matt-Yorkley.

**Comment by Matt-Yorkley** [comment]
Okay, it looks like the matching `variant_unit_name` of the variant has to be supplied when using the items unit type when using inventory import, so maybe we should add it to the template, @myriamboure ?

**Comment by myriamboure** [comment]
Sure @Matt-Yorkley can you update the inventory template file then ? And @sstead and @RachL we can update the user guide !

**Comment by myriamboure** [comment]
Maybe we should open a new issue and separate PR for that @Matt-Yorkley I let you decide but it seems like a separate issue to fix.

**Comment by Matt-Yorkley** [comment]
I've added it to the CSV template.

**Comment by sigmundpetersen** [comment]
So is this ready for another review? Or straight to Test Ready again maybe?
@Matt-Yorkley @myriamboure

**Comment by myriamboure** [comment]
@Matt-Yorkley is it ready for a new review ? @kristinalim had requested changes, are they done ? Cheers !

**Comment by myriamboure** [comment]
Oups sorry I had not seen your comment @sigmundpetersen cool you are doing train driving as well ! ;-)

**Comment by Matt-Yorkley** [comment]
Yes, the requested changes are done. It should be ok to re-test.

**Comment by myriamboure** [comment]
I put it to code review first @Matt-Yorkley so your changes can be reviewed, especially @kristinalim requested changes.

**Comment by RachL** [comment]
Deploying on UK staging

**Comment by RachL** [comment]
@Matt-Yorkley @kristinalim I need a new eye because it must seems that I'm doing something wrong with the file as my producer column is not "detected". Does any of you see where I did a mistake in the file?
Here are the files I've used:
https://drive.google.com/drive/u/0/folders/1gAnupX_EStkndyUt8lHpYu7FN0y8lAgt
And I've updated the testing notes: 
https://docs.google.com/document/d/1QBV4CUplM6GSJl1GQ5sxfLsCwwa4Pe1uRmTfxcwLi9c/edit#

**Comment by kristinalim** [comment]
@RachL What spreadsheet application do you use? Is it Excel?

I get the same error when using your files. Finding out only now, it turns out Excel sometimes inserts a "Byte Order Mark" (BOM) UTF-8 character to the CSV. This is the `<U+FEFF>` when looking at the files with `less` (command):

20190207031411-test2-bom

We either need to (1) support CSV files with BOM, or (2) provide enough instructions to make sure users don't upload files with BOM. I read just now that the first option is easy, but I haven't checked if our version of the CSV parser supports this. We can address parseability of CSV with BOM in a separate issue.

For you to be able to proceed with testing, @RachL, I am researching how to save the file without BOM - I'll get back to you. (I don't have access to Excel.)

**Comment by kristinalim** [comment]
@RachL A way to save the CSV file without BOM is by opening the files in Google Sheets, and saving the files locally again through File > Download as > Comma-separated values. Let me know if this still doesn't work.

**Comment by kristinalim** [comment]
I created an issue to support the BOM: #3448

**Comment by mkllnk** [comment]
Great research Kristina. I've heard people in another project saying they were putting spreadsheets through Google Docs, because that avoids errors when importing into other systems. Now I have an idea why. :+1:

**Comment by mkllnk** [comment]
Staged on https://staging.katuma.org/.

**Comment by RachL** [comment]
Alright, so with LibreOffice, it has worked very well :)

I've updated the testing notes here: https://docs.google.com/document/d/1QBV4CUplM6GSJl1GQ5sxfLsCwwa4Pe1uRmTfxcwLi9c/edit#

**Comment by sigmundpetersen** [comment]
Yay, go open source! 😄

**Comment by luisramos0** [comment]
This PR broke master:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/472

```
 1) Product Import when importing products from uploaded file handles on_demand and on_hand validations with inventory
     Failure/Error: import_data
     
     NameError:
       undefined local variable or method `import_data' for #<RSpec::ExampleGroups::ProductImport::WhenImportingProductsFromUploadedFile:0x0055fa01117870>
     # ./spec/features/admin/product_import_spec.rb:310:in `block (3 levels) in <top (required)>'
```

I pulled master and it's failing on my local as well. Where is "import_data" coming from?

**Comment by sauloperez** [comment]
I'll take a look tomorrow morning if no one has done it yet.

**Comment by Matt-Yorkley** [comment]
It looks like the `import_data` helper method in this spec was renamed to `proceed_to_validation` in a different PR that got merged before this one.

**Comment by sauloperez** [comment]
Thanks @Matt-Yorkley!

**Pull request merged**
