### PR TITLE
3544 Add date format to moment date conversion

### LINKED ISSUE #3544: [Subscriptions] Proxy orders show OC is closed when it isn't
## Description

When viewing a subscription's proxy_order, it shows the order cycle as **closed** when it's actually **open**. It also shows an error message relating to the close time:

screenshot-2019-02-25-13-49 39

I'm not sure if this also affects the placement of orders via proxy_orders, but I suspect it might.

## Expected Behavior

It should list the order's OC as open when it is open. 

## Actual Behaviour

It incorrectly shows the OC is closed.

## Steps to Reproduce

1. Create a subscription
2. View the order in the subscription
3. It displays: "closed Invalid date"

## Context

Testing subs.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: master
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Debian 10

## Possible Fix

Greping for the "Invalid date" error message shows it originates in the the js datepicker component...

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #3544 
See issue for details: https://github.com/openfoodfoundation/openfoodnetwork/issues/3544#issuecomment-510838979

#### What should we test?
See issue. Very isolated change, nothing else needs testing.

#### Release notes
Changelog Category: Fixed
Fix date conversion issue in subscriptions that was showing incorrect data on the subscriptions list page.

### CODE REVIEW

**Comment by RachL** [comment]
Despite a gigantic grammar mistake :grinning:  (I couldn't fin  the text in Transifex - @luisramos0 what's the translation key for this?) this is now working on Firefox :tada: 

image

I've tested with the following browsers:

- Firefox 68
- Firefox 69
- Firefox 67
- Firefox 66
- Chrome 75
- IE 11
- Edge 18

**Comment by luisramos0** [comment]
here: https://www.transifex.com/open-food-foundation/open-food-network/translate/#fr/enyml/135961995?q=key%3A%22js.subscriptions.closes%22

**Comment by luisramos0** [comment]
if you want to learn to look up these things: you just need to search this file: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/fr.yml

**Comment by RachL** [comment]
@luisramos0 thx, exactly what I was looking for :) In my previous job I used to edit the yml file directly because we didn't have something like transifex. Will look at the file now that I know where it is :ok_hand:

**Pull request merged**
