### PR TITLE
Dotenv

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Twinned with https://github.com/openfoodfoundation/ofn-install/pull/751

Introduces **Dotenv** for ENV var management on a per-environment basis. 

This means:
- instead of having all environment variables defined in `application.yml`, we can have them in separate files
- devs can also add local overrides that are gitignored, so for example you can load some French data in your dev database, and apply alternate locale/country settings without it affecting the test suite (which often expects the default country to be Australia, or the currency to be AUD, for example)
- the current manual step in dev environment setup where we need to copy `config/application.example.yml` to `config/application.yml` is removed

#### What should we test?

Build should be green. Environment variables should all be the same after deployment. Can also be tested locally in dev via booting the app or the console, or running tests.

#### Release notes

Added Dotenv for better ENV var management

Changelog Category: Technical changes

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
> you can load some French data in your dev database, and apply alternate locale/country settings without it affecting the test suite

Brillant idea! Loving it. Thanks for that. 🙏

**Review by jibees — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
Nice!

The community seems to agree that dotenv is the new way to go: https://www.ruby-toolbox.com/categories/Configuration_Management

**Comment by Matt-Yorkley** [comment]
I pushed two extra commit here that make Redis and Sidekiq nicer to use in dev by default.

**Comment by jibees** [comment]
There is conflicts into the Gemfile.

**Comment by Matt-Yorkley** [comment]
Rebased +1:

**Comment by jibees** [comment]
I tested locally. 
I created the `.env.development.local` with content:
```
LOCALE="fr"
```
And the interface was in French.

I deleted the file, and the interface was in English, as specified in the `.env.development` file, and then all was translated to English.

I'd say: **Ready to go**! 🎉

**Pull request merged**
