### PR TITLE
Updates syntax to remove depracation warnings

### LINKED ISSUE #10046: [Deprecation warning] Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated.
### What we should change and why (this is tech debt)

```
Deprecation Warnings:

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/runner/work/openfoodnetwork/openfoodnetwork/spec/models/spree/payment_spec.rb:91:in `block (4 levels) in <top (required)>'.
```

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

- Closes #10046

Replaces `.stub` with `allow()` or `expect()`.

#### What should we test?

Green build.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @binarygit ,

As discussed in delivery circle today: I've now updated this PR, the syntax in the specs above has been updated and the build is green.

I think the only other spec which is triggering these types of deprecation errors is `spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb`.

I guess we would need to replace `instance.stub(params)`, but doing so with `allow(instance).to receive([params])` throws out:

```
Failure/Error: expect { authorizer.authorize! }.not_to raise_error
     
       expected no Exception, got #<NoMethodError: undefined method `to_sym' for [{:id=>"1"}]:Array
       Did you mean?  to_s
                      to_set> with backtrace:
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:174:in `block in stub_model'
         # <internal:kernel>:90:in `tap'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:172:in `stub_model'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:167:in `block in stub_model_collection'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:166:in `map'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:166:in `stub_model_collection'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:18:in `block (4 levels) in <module:EnterpriseFeeSummary>'
         # ./lib/reporting/reports/enterprise_fee_summary/authorizer.rb:16:in `authorize_by_distribution!'
         # ./lib/reporting/reports/enterprise_fee_summary/authorizer.rb:8:in `authorize!'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:26:in `block (5 levels) in <module:EnterpriseFeeSummary>'
         # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:26:in `block (4 levels) in <module:EnterpriseFeeSummary>'
     # ./spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb:26:in `block (4 levels) in <module:EnterpriseFeeSummary>'

```

Any idea how to proceed? Thank you for your help! :pray:

**Comment by binarygit** [comment]
Hey @filipefurtad0 use this `allow(instance).to receive_messages(params)` instead of `allow(instance).to receive([params])` :smile:

**Comment by filipefurtad0** [comment]
Thanks @binarygit :raised_hands: 

> Actually I went ahead and committed sweat_smile

I could not find your commit on this PR so I've added this change to this branch now.

I think this should cover for all the missing deprecation warnings. I'll run the build locally to double check. Thanks again!

**Comment by binarygit** [comment]
no worries. Maybe I commited on a different local branch or smt :shrug:

**Comment by filipefurtad0** [comment]
Thanks @jibees - that info was missing in the description, now edited :pray: 

It only changes the specs, so I think we'd be good to merge?

**Comment by jibees** [comment]
> It only changes the specs, so I think we'd be good to merge?

giphy-1

**Pull request merged**
