### PR TITLE
Missing translations inventory page

### LINKED ISSUE #4105: Missing translations on inventory page
## Description

The button "save changes" at the bottom of the page is not translated on inventory page + the support text "default stock" is also not translated in the default stock column.

URL of the page: `/admin/inventory`

Capture du 2019-07-31 16-13-35

## Context

Noticed when updating french user guide and retesting stuff.

## Severity
S3

## Your Environment

* OFN Platform instance where you discovered the bug, and which version of the software they are using : French 2.2.1

### PR DESCRIPTION
**Pull request by andrewjprice**
#### What? Why?

Closes #4105 

Uses save_changes translation for the Save Changes button on the admin/inventory page.

Adds a default_stock placeholder translation to be also used on the admin/inventory page.

#### What should we test?

Add products on the admin/inventory page to be saved. Test translations are displaying correctly.

#### Release notes

Add missing translations.

Changelog Category: Added | Changed 

#### Screenshots

Before
Screen Shot 2019-10-19 at 4 45 33 PM

After
Screen Shot 2019-10-19 at 4 36 59 PM

### CODE REVIEW

**Comment by luisramos0** [comment]
Welcome Andrew, thanks for your PR!

**Comment by andrewjprice** [comment]
@luisramos0 Thanks for pointing this out. 

So I was playing around with this last night and could not get the placeholder translations to display. I added a key to `es.yml`, ensured the path was correct (at least 5 times! 😆 ), and nothing.

**Comment by luisramos0** [comment]
yeah, I gave it a try.
in JS (you are inside {{}} here so you are in angular context) you need to use the t filter, not the t function.
docs: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)#javascript-translations-prefer-angular-filter-over-global-t-function

I added a commit, it's working now :+1:

**Comment by andrewjprice** [comment]
@luisramos0 Ah, I was using `| translate` instead of `| t`. Thank you!

**Comment by RachL** [comment]
Looking good :)

image

**Pull request merged**
