### PR TITLE
Revert "Pluralize admin products search result [OFN-12532]"

### PR DESCRIPTION
**Pull request by filipefurtad0**
Closes openfoodfoundation/openfoodnetwork#12731.
Reverts openfoodfoundation/openfoodnetwork#12665.

### CODE REVIEW

**Comment by wandji20** [comment]
Hi @filipefurtad0

I just pulled the latest master branch and noticed a weird translation with `en_FR` which certainly causes a server error
Can you please confirm what local you did assign before getting this new error?

**Comment by filipefurtad0** [comment]
Hey @wandji20, thanks for looking into this!

The locale assigned to staging-FR is `fr.yml`: 
image

I've pulled the latest translations into master. Maybe I should re-stage master after this...

> noticed a weird translation with en_FR which certainly causes a server erro

Which translation do you mean?

**Comment by wandji20** [comment]
> Which translation do you mean?

image
The variable name should be `count` and not `total`

**Review by rioug — APPROVED** [review]
Looks good :+1: . It's a pretty safe change so I am going to merge it now to not block the release

**Comment by filipefurtad0** [comment]
Thanks @rioug for reverting the PR.

> The variable name should be count and not total

In any case, I agree with @wandji20, [this does not seem](https://github.com/openfoodfoundation/openfoodnetwork/pull/12730#issuecomment-2265601421) right.

Now we've gone down the path of reverting this PR, so I think we'd need to revert the latest translations from master too, 0afbdf157e91bb5425862a91795b515cf460669f. Right?

**Comment by rioug** [comment]
I am not sure to be honest. I think if this fix the problematic translations we should be good as it is. @openfoodfoundation/core-devs any input ?

**Comment by dacook** [comment]
Thanks for spotting this Wandji. Indeed, `en_FR` is wrong, this may be due to user mistake (I can see that `fr` was also updated):
https://github.com/openfoodfoundation/openfoodnetwork/commit/0afbdf157e91bb5425862a91795b515cf460669f#diff-afc33b29ea937814856ce867d17a71bf7dae5c8eec30212046e5e538275217fcL813-R817

All other changes in that commit look valid. But it's interesting that a lot of valid translations were also removed, for example: https://github.com/openfoodfoundation/openfoodnetwork/commit/0afbdf157e91bb5425862a91795b515cf460669f#diff-e76a11e9b4a84e1653a37d620ec4ce380841d3763e51f37e5a415a5a7d21a028L758

So I agree with Filipe that commit also contributes to the problem and can be reverted. I'll discuss in Slack and make sure that's done before we test the release again.

Going forward, I think we could fix this up by manually fixing the dodgy translation changes. As far as I understand, it's appropriate in this case to manually edit the translation files. @wandji20, would you be interested to try that, or should I?

**Comment by mkllnk** [comment]
> manually edit the translation files

I think that any manual edits would get overridden through Transifex again. Manual updates have to happen in Transifex.

Next time we should rename the translation key if we change the parameter variable names. It may just be that translations were not updated yet and still using the old variable which then results in a server error.

**Comment by wandji20** [comment]
> rename the translation key

I have opened a [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12740) with this change.

**Pull request merged**
