### PR TITLE
change colour of "complete order"

### LINKED ISSUE #12716: [Checkout] Change colour of 'complete order' button to match rest of the UI
## Description

We have reports of users globally who arrive to collect orders or are awaiting deliveries of orders they haven't actually placed. Investigations have shown that each time this happens, the user has arrived at the 'checkout' screen, but has failed to click the button to complete their order. Transifex changes have been made to the text as some users indicated the 'complete order' text suggested their order was already completed, however another sticking point is likely that the colour of the 'complete order' button is green. From a UX perspective, green is associated with 'completed' or 'done' and is indeed used on completed stages of the checkout process:
Screenshot 2024-07-30 at 10 31 56
This conflict between all other actionable buttons on the platform using OFN orange/#F26F52, together with the association of green=done (reinforced by previous completed stages of the checkout marked in green) is therefore likely contributing to incomplete checkouts.

## Expected Behavior

Actionable buttons/the complete order button should be visually consistent with others across the platform, i.e. using #F26F52

## Actual Behaviour

The complete order button is shown in 'completed green'/#0B8C61 

## Possible Fix

Amend colour of button to OFN orange/#F26F52 in line with rest of the UI and other 'incomplete' elements

Screenshot 2024-07-30 at 10 36 55

### PR DESCRIPTION
**Pull request by EdwardLi-coder**
#### What? Why?

- Closes #12716

#### What should we test?

As described in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by chahmedejaz — APPROVED** [review]
Looks good to me. Thanks, @EdwardLi-coder.
Please add the testing steps in the PR's description. If they are exactly what the expected behavior of the issue's description then simply "As described in the issue" would be enough. Thanks.

**Comment by EdwardLi-coder** [comment]
> Looks good to me. Thanks, @EdwardLi-coder. Please add the testing steps in the PR's description. If they are exactly what the expected behavior of the issue's description then simply "As described in the issue" would be enough. Thanks.

Ok,Thanks.I've already updated it.

**Review by dacook — COMMENTED** [review]
I notice that the general rule for `.button.primary` is a slightly different colour:

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/css/darkswarm/ui.scss#L69
```scss
  background: $orange-450;
```

Can you check if that one works best? Maybe you can remove this line and let it use the default.

**Comment by EdwardLi-coder** [comment]
> I notice that the general rule for `.button.primary` is a slightly different colour:
> 
> https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/css/darkswarm/ui.scss#L69
> 
> ```css-scss
>   background: $orange-450;
> ```
> 
> Can you check if that one works best? Maybe you can remove this line and let it use the default.

Ok,I will check it.

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]

**Review by chahmedejaz — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @EdwardLi-coder,
Thank you for improving our code!

I have tested your pull request on our staging server. 

Here is a screenshot before staging:
image

And here after:
image

Great! The button is now using the default orange!

I'll go ahead and merge! :rocket:
Thanks again! :tada:

**Comment by EdwardLi-coder** [comment]
> Hi @EdwardLi-coder,
> 
> Thank you for improving our code!
> 
> 
> 
> I have tested your pull request on our staging server. 
> 
> 
> 
> Here is a screenshot before staging:
> 
> image
> 
> 
> 
> And here after:
> 
> image
> 
> 
> 
> Great! The button is now using the default orange!
> 
> 
> 
> I'll go ahead and merge! :rocket:
> 
> Thanks again! :tada: 

Thank you for your recognition and support. I'll continue to work hard to contribute to our project.

**Pull request merged**
