### PR TITLE
Remove unused partial paypal

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

This PR just removes an unused partial for the paypal refund button that was recently removed in #7749.

#### Release notes
- Removed unused partial

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Could you drop the first commit and force-push? It's already included in #7759

Hot tip: you can use an [interactive rebase](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d) with the `HEAD~2` option.

**Comment by apricot12** [comment]
Just did it :ok_hand:

**Review by Matt-Yorkley — APPROVED** [review]
Great. I'm 99% sure this is a leftover from importing the Spree paypal gem code.

:fire:

**Review by andrewpbrett — APPROVED** [review]
Build is green (minus the Codecov thing). This might be worth double checking manually since I don't know how well our test suite covers the full Paypal flow? If we're pretty sure it's not used though I'm fine merging as is.

**Comment by filipefurtad0** [comment]
Hey @apricot12 and @andrewpbrett ,

Thanks for the heads-up on this one. In this case I did only a quick sanity check by checking out with Paypal through the shopfront: it worked as usual.

I think we're good to merge.

**Pull request merged**
