### PR TITLE
Ensure the hero image doesn't pixelate on hamburger menu open

### LINKED ISSUE #1253: [mobile ux] When I expand the hamburger menu on mobile, background image zoom in and overly pixelated
## In a feature branch or master?
This can be merged directly to master 🎉 

## Description
On mobile/tablet, when expand hamburger menu, the background image zoom in excessively giving a pixelated look.

## Current behavior
Pixelated view, background image zoomed
46837804-66844100-ce02-11e8-84ed-b2b68e34221d

## Expected behavior
No zoom in the image
46837891-a0554780-ce02-11e8-9437-387910acfaee

### PR DESCRIPTION
**Pull request by mbudm**
#### What? Why?

Closes #1253 

This ensures the hero image doesn't attempt to use the full height of all page content:
Screen Shot 2020-07-08 at 9 12 40 pm

Not sure exactly why this happens, but when the mobile nav is opened the hero image at #tagline:before uses the height of the full window - often around 4000px. Adding max-height of 100% to the nearest safe parent prevents this behaviour, without pulling apart the nav css to figure out exactly what's happening.

#### What should we test?
Toggle open the hamburger menu
The hero image should stay the same size

Highly recommend we test this on multiple browsers... (I've tried chrome and safari on mac)

#### Release notes
Fixed hero image pixelating

Changelog Category: Fixed

### CODE REVIEW

**Comment by mbudm** [comment]
Hi @luisramos0 - here is the example without the change - you can see that the `max-height:100%;` property is disabled, and the image is enlarged greatly because the height of `.inner-wrap` is almost 4000px (the `#tagline:before` element that contains the background image inherits it's height from `.inner-wrap`).
Screen Shot 2020-07-14 at 12 49 35 pm

When that css property is re-enabled, the image decreases back to the expected height ~ 800px in this case:
Screen Shot 2020-07-14 at 12 48 58 pm

If you aren't seeing this the this is either:
- a cache issue, try clearing cache
- a browser issue, I've tested this on chrome and safari on osx. I could make a static version and go the browsertesting route if that seems to be the issue

**Comment by mbudm** [comment]
Grrr Firefox... Investigating

**Comment by mbudm** [comment]
I stripped back the generated html and got a rudimentary static version, which I've [hosted here](https://mbudm.github.io/scratchpad/index.html). This is pretty broken - but importantly the bit that does work is the tagline layout.

You can check this by toggling the properties I've added - which make up this fix, the image will pixelate again:
Screen Shot 2020-07-14 at 7 28 10 pm

I then used this static mock to test on a random variety of browsers/os:

Opera on windows
Screen Shot 2020-07-14 at 7 21 06 pm

IE11 on windows
Screen Shot 2020-07-14 at 7 19 58 pm

A Galaxy device
Screen Shot 2020-07-14 at 7 19 10 pm

Edge on windows
Screen Shot 2020-07-14 at 7 17 56 pm

**Comment by luisramos0** [comment]
ah, yeah, I forgot to mention, I am on firefiox.
Firefox is 5/6% on most instances but 15% in France. Definitely a major browser. Also because it's the main open source browser.

I am ok with having two height entries, we just need a short code comment to explain that they work for different browsers.

**Comment by filipefurtad0** [comment]
Hi @mbudm ,

I verified issue #1253 and, after staging this PR, went through several environment combinations on Browserstack.

Manually:
- iPhone 11, iPhone 8 - Chrome, Safari
- Samsung Galaxy S20, Samsung Galaxy S9 - Chrome, Firefox

With a small ruby script (click - wait - take screenshot) - woohoo, it worked! :tada: (except for IE)
- Windows 10, Windows 8 - Chrome, Firefox, Edge, IE
- OS X Catalina, OS X High Sierra - Chrome, Firefox, Safari, Edge

You may find all the pics on the google doc:
https://docs.google.com/document/d/1W384cjrdC8AGQYG4GRtYFppgTQLIXekennxWK0BlRUg/edit#

Do you have a Gmail account/access to this folder Steve? If not, do drop me a line so I can add you.

While testing, I've observed the known issue #5721.

This looks great! Ready to go :-)

**Pull request merged**
