### PR TITLE
Edit tooltip text to make it readable

### LINKED ISSUE #1848: One tooltip is off the page on OC edit page
Updated by Myriam 21.05.2018

## Description
One tooltip on order cycle edit page / "advance settings" can't be seen

## Expected Behavior
Tooltip can be read properly

## Actual Behavior
Tooltip can't be seen (Myriam just retested in 13inch screen for instance, so "regular" screen)
image

## Steps to Reproduce
1. You need to have one order cycle created already, then click on "edit" 
2. Click on "advance settings" button below the main menu
3. On this advance setting zone there is a tooltip below "choose products from", this tooltip is on one line only an can't be read properly.

## Context
Retesting to clean and specify old issues.

## Severity
S5

## Your Environment
PC, Aus production (+ French production), Chrome

## Possible Fix
Display tooltip on two lines?

### PR DESCRIPTION
**Pull request by jonleighton**
#### What? Why?

Fixes #1848 by rebasing the fix proposed in
https://github.com/Ecksi/openfoodnetwork/pull/1 (which was confusingly merged
to a forked repo) onto the current master.

#### Release notes

Fix display of tooltip in order cycle advanced settings so that the text
doesn't run off screen.

Changelog Category: Fixed

### CODE REVIEW

**Comment by jonleighton** [comment]
Thanks for the explanation -- I've updated the PR.

**Comment by RachL** [comment]
hhmmmm what is the definition of "off the screen" applied here? Because to me it still feels that the tooltip is off the screen:

image

On a smaller screen it is then truncated.

The text of the tooltip should be appearing like this when the screen is smaller:

You can opt
to restrict all
available products
(both incoming and
outgoing to only those in OFN Demo hub's inventory)

What do you think@luisramos0 @Matt-Yorkley ?

**Comment by luisramos0** [comment]
this PR only makes the message smaller, so it definitely improves the situation. And the message can be further reduced in transifex by translators. But maybe it will still be off the screen for other screen sizes... the PR should be merged. The question is if we close the issue or not.

**Comment by RachL** [comment]
thank you @luisramos0 I understand better. This is not the only tooltip displaying badly, so I would be in favor of working maybe on a issue that would set up a responsive tooltip style that would work in many cases? In the meantime, moving to ready to go.

**Comment by luisramos0** [comment]
yes, agree!

**Pull request merged**
