### PR TITLE
Fix Voucher Code Field Focus Issue

### LINKED ISSUE #12632: Voucher code field at checkout only allows one character
## Description
At checkout when entering a voucher code the user can only type one character at a time. After each character they need to re-click in the space to type another character, and repeat until the code is completely entered. This will no doubt be a nuisance to customers.

## Expected Behavior
Voucher code field should accept the full voucher code without needing to reclick into the field.

## Actual Behaviour
Voucher field requires the user to reclick into the field after each character. 

## Steps to Reproduce
1.  Go to checkout with a cart of items
2.  Attempt to enter a voucher code

## Workaround
Some users can use discounts via enterprise fees however this does not work for all use cases of vouchers

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
Chrome Version 126.0.6478.127 on laptop

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12632
- Currently, we are using the generic `toggle_control_controller` to enable the **Apply** button if the voucher code is present.
- This controller focuses the `control` after performing some toggle action on it i.e. after enabling etc.
- In this case, the control is a `submit` button (**Apply**), and when user enters the voucher code, and after that the controller **_enables_** the **Apply** button and **_focuses_** it. Hence, the focus is lost from the Voucher Code input field.
- I assume the _focus_ functionality was intended for text-related fields, so this PR adds the check such that if the `control` is a button, then it won't be focused. Hence, the currently focused field will remain focused.

#### What should we test?
- On the checkout page, when entering the voucher code, the field should remain focused and let you fill in the entire code without re-clicking it to focus after each character.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

**Review by rioug — CHANGES_REQUESTED** [review]
Good one, could you update the related test as well ? thanks !

**Comment by chahmedejaz** [comment]
> Good one, could you update the related test as well ? thanks !

Ah, sorry about that. I missed the Jest specs. Let me update that and get back to you. Thanks.

**Comment by chahmedejaz** [comment]
Hi @rioug - Specs are updated here: https://github.com/openfoodfoundation/openfoodnetwork/pull/12634/commits/ced3408aaa38bb1ffb94f9e15588cec98d61e6a1. Please review and let me know if anything is missing. Thanks.

**Review by dacook — APPROVED** [review]
Great work, and thanks for updating the existing spec to cover this also 👍

**Review by rioug — APPROVED** [review]
Awesome, It looks good now thanks !

**Comment by RachL** [comment]
I didn't manage to successfully stage this one :(

**Comment by sigmundpetersen** [comment]
This is how Filipe did it earlier https://github.com/openfoodfoundation/openfoodnetwork/issues/12485#issuecomment-2112884888

**Comment by RachL** [comment]
@sigmundpetersen ah good to know, thanks! but Filipe has ssh access, I don't :(

**Comment by sigmundpetersen** [comment]
Yes, same error on au-staging.
So either out of memory there as well, or there is another error

**Comment by drummer83** [comment]
Hi @chahmedejaz,
Thank you for fixing this s2. :muscle: 

I was able to reproduce the bug BEFORE this PR. After staging your solution, I couldn't see it anymore.

So I can confirms that the bug is fixed. That's great! Thank you!! :pray: 

[Kazam_screencast_00004.webm](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/cfd53c15-dbdd-440b-8b0c-32c0556fa822)

Ready to go! :rocket: :partying_face:

**Pull request merged**
