### PR TITLE
Stripe 3DS issues

### LINKED ISSUE #7753: Can't place orders using Stripe 3D cards (shopfront and backoffice)
## Description

Checking out through the shopfront with [3D-auth cards](https://stripe.com/docs/testing#regulatory-cards) like:

- 4000000000003220
- 4000002760003184

display the error:

`
There was a problem with your payment information: Received unexpected 3DS authentication response. Use the execute_threed option to initiate a proper 3DS flow. 
`

Placing BO orders with 3D cards leads to an invalid payment.

First observed on staging-FR as reported by @Matt-Yorkley; reproduced on other servers, namely staging-AU: staging master [build #2649](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/345) led to this bug.

## Expected Behavior

Checkout should be possible with 3D-auth. cards.

## Actual Behaviour

Checking out with 3D-auth. cards is not possible.

## Steps to Reproduce

Shofront
1. Attempt to place an order through the shopfront, selecting Stripe SCA as a payment method
2. Add a 3D-secure card
3. See the error

Backoffice
1. Attempt to place an order through the backoffice, selecting Stripe SCA as a payment method
2. Add the card details
3. See the payment marked as "Failed"

## Animated Gif/Screenshot

**Shopfront**

**Backoffice**

## Workaround

Using a different payment method. 

## Severity

Blocker for the release v3.8.0 - it is not in production.
Not observed after deploying v3.7.3.

## Your Environment

* Version used: observed on master branch [build #2649](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/345)

## Possible Fix

@Matt-Yorkley investigated further: Reverting a recent PR (#7752) didn't fix it... Rails 6.0 upgrade could be related to this - although this scenario was tested before merging with master...

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #7753 

Fixes errors thrown when trying to use Stripe with a card that requires authorization at checkout.

Also removes a decorator for an ActiveMerchant Stripe class that we no longer need.

#### What should we test?

Both regular and 3DS Stripe SCA payments work. We should probably test other Stripe SCA functionality as well, like connecting an account, creating an order via admin, stripe payments via subs, etc...

#### Release notes

Updated ActiveMerchant decorators

Changelog Category: Technical changes

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]
:clap:

**Comment by Matt-Yorkley** [comment]
I just found an alternate solution to this that doesn't involve adding any more mess to the decorator, so I've updated it (and force-pushed).

**Review by luisramos0 — APPROVED** [review]
nice :+1:

**Review by jibees — APPROVED** [review]
Good catch @Matt-Yorkley ! 👌

**Comment by sigmundpetersen** [comment]
Yes, s1/s2 bugs always go to the top of each column 👍

**Comment by Matt-Yorkley** [comment]
Alright, lets merge and I'll prep a hotfix release that we can hopefully deploy today (to get Rails 6 in production)

**Pull request merged**
