### PR TITLE
Make bullet activation optional

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

This might speed up CI, and still makes it easy to activate when needed. Also I sometimes seem to get weird problems in dev that are fixed when I disable bullet. No idea why. :shrug:

#### What should we test?

No test.

#### Release notes

Made bullet profiling optional

Changelog Category: Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
What do you think, @sauloperez ?

**Review by sauloperez — APPROVED** [review]
Not prob. I'll set up that env var on my machine

**Review by andrewpbrett — APPROVED** [review]

**Comment by andrewpbrett** [comment]
I'll merge since it technically has the two reviews necessary. But if @mkllnk or @jibees feel strongly that this should be defaulted to on, we can keep it that way. I'm not strongly opinionated.

**Comment by sauloperez** [comment]
:pray: turn it on sometimes, guys, or I'm afraid we won't raise awareness of the N+1s

**Pull request merged**
