### PR TITLE
Add Customer balance to customer list

### LINKED ISSUE #5171: Shop can easily see Customer account totals on Customers page
## Description

- As a Shop or Hub
- On page: admin/customers
- I want to be able to see the total amount owed from or owing to my shop for each Customer
- This column could be present by default, or hidden by default in the columns drop down (shown below)
- It should be clear whether the amount is owing to the Shop, or the Customer has a credit (red for owing to the shop?)
 
This information is currently visible to the Customer in their [account transactions page](https://openfoodnetwork.org.au/account#/transactions) - I think the page just adds up the total credits and debits at each shop and displays it on this page

If the Shop manager could also see this amount easily it saves them pulling the Payments report anytime they are trying to work out the state of a customers account balance

(slight enhancement to ease our workaround account credits process :)
  
## Acceptance Criteria & Tests

1. View Customers list, see customer with account credit = $0
2. Create an order for that Customer with multiple items in a shop
3. Edit the order to remove an item, so now the Customer is owed money (they have an account credit)
4. Refresh Customers page - should now show a customer account credit amount 
5. Go to the Customer's order and add payment, -$XX to indicate processign a refund
6. Refresh Customer page - should now show new amount reflecting the refund

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5171
Display customer balance in the customer list.

#### What should we test?
Green build.
Verify the customer balance is displayed in the customer list.

#### Release notes
Changelog Category: Added
Added the customer balance for a specific shop in the customer list page.

### CODE REVIEW

**Comment by luisramos0** [comment]
For some reason this PR didnt get a build in semaphore. I decided to push the branch upstream to get a build for this code. I am surprised to see github picks that up and links this PR to the build of the branch in upstream :-O

**Review by Matt-Yorkley — APPROVED** [review]
Any screenshots..?

**Comment by luisramos0** [comment]
ah, yes, in the issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/5171#issuecomment-708326799

**Review by sauloperez — CHANGES_REQUESTED** [review]
I'm missing some specs but it looks good

**Comment by luisramos0** [comment]
yeah, I agree. I am not sure why I simply skiped specs here :see_no_evil: 
Done now.

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @luisramos0 ,

I didn't find the link to deploy above, so I went looking it on semaphore and found the branch `customer_total `. Used the link there to deploy this PR, but this seems to have failed:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/fr-staging/deploys/411

Adding the feedback label here. Thank you!

**Comment by luisramos0** [comment]
yeah, it's that states problem. I rebased the branch now and staged to FR. It should be fine now. We need to verify the build and deploy job are green in a few minutes.

**Comment by luisramos0** [comment]
build had a flaky fail but deploy is goood. ready for testing in fr staging :+1:

**Comment by filipefurtad0** [comment]
Hey @luisramos0 ,

I checked this PR before staging:
image

And after staging:
image

I logged in into these three accounts, and made sure each of these has the corresponding account totals:

- account 1:
image

- account 2:
image

- account 3:
image

All good.



The tests and acceptance criteria on issue #5171 were checked as well:
- showing by default works as well as hiding by default: these settings take effect after logout, and are retained til new log in, in a different session/browser.
- setting all balances to zero appears with no color marking:
image
- changes made in orders are reflected in /admin/customers correctly

From the description of the issue, the 5th item states: 
> It should be clear whether the amount is owing to the Shop, or the Customer has a credit (red for owing to the shop?)

Maybe this point would still need to be addressed, but I think it can be done on a separate issue. Also, this will influence probably the state of orders as well, as currently both are shown in orange. Shall I go ahead and open an issue for this one?

Other than this, it looks great and I'd say it's good to go.

**Comment by luisramos0** [comment]
>>> It should be clear whether the amount is owing to the Shop, or the Customer has a credit

We have added the labels "balance due" and "credit owed" to address this point.
Maybe I have missed the point but this makes it very obvious if it's credit or not:
image

**Comment by filipefurtad0** [comment]
I agree, the point is indeed addressed. Thanks for stressing that point Luis :+1: 

> (red for owing to the shop?)

Thinking of it, this part of the description sounds rather as a suggestion, so I guess it was not really a requirement for this issue. 
Removing the label - ready to go.

**Comment by luisramos0** [comment]
ok :+1:

**Pull request merged**
