### PR TITLE
Design suggestions to authorization links table

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Extends #6919 to bring some design consistency.

:warning: it needs to be rebased onto master when #6919 gets merged.

#### :camera_flash: screenshots

*Before*

Screenshot from 2021-02-22 12-08-29
Screenshot from 2021-02-22 12-08-16

*After*

Screenshot from 2021-02-22 12-05-49
Screenshot from 2021-02-22 12-05-40

#### What should we test?

There are no behavior changes but things need to look fine both on desktop and mobile; no obvious spacing issues or odd sizes.

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]
This looks awesome, thanks! I'll rebase and merge once the parent PR is merged.

**Review by mkllnk — APPROVED** [review]
Nice!

**Comment by mkllnk** [comment]
@andrewpbrett I think you could pick these commits into your branch and then they are included in the testing.

**Comment by andrewpbrett** [comment]
I'll close this one since I brought these commits into https://github.com/openfoodfoundation/openfoodnetwork/pull/6919 (I **think** it worked - I had to reorder some commits and resolve some conflicts, but it looks like the commits are still the same).

**Pull request closed without merging**
