### PR TITLE
Sort products alphabetically in OC edit page

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

This makes the list of products in the OC page sorted alphabetically.

#### What should we test?
Verify the order of the products is alphabetical.

#### Release notes
Changelog Category: Changed
The lists of products in the OC create/edit pages are sorted alphabetically.

### CODE REVIEW

**Comment by sauloperez** [comment]
In this case, I wonder if it's worth adding or tweaking an existing test to ensure the ordering :thinking:

**Comment by luisramos0** [comment]
rebased to resolve conflicts.

**Comment by mkllnk** [comment]
I restarted the build. If it passes, it can go to test ready.

**Comment by RachL** [comment]
@jenRSmith I'm sorry I will test this one as well because it's kind of a package with the new OC page.

**Comment by RachL** [comment]
@luisramos0 do you know why the product "LA TENDA" is on top (AU staging - DorV Online OC)? :

image

**Comment by RachL** [comment]
@luisramos0 funfact : this product i son top but only in outgoing, not in incoming :) This is a screenshot of incoming:

image

**Comment by luisramos0** [comment]
hey @RachL
there's a trailing space in that product name:
Screenshot 2019-11-26 at 17 13 05

Removing the space will move the product to its place in the list.
In the incoming exchanges page, that space gets trimmed in some way. I dont understand why it's not at the top of the list on the incoming exchanges...
When I try to replicate this with a product with a trailing space in the name, I get the product at the top of the list in both incoming and outgoing...
I think we can ignore this. Removing the trailing space will move the product to its place in the list.


Additionally but I think unrelated:
Investigating this I just realized before this PR the products were already sorted alphabetically on the outgoing exchanges (done on the browser).
This PR is sorting all products on the server so I added a new commit to remove the existing, and now unnecessary, sorting done on the browser.

**Comment by RachL** [comment]
ALright I've restaged this and indeed, couldn't reproduce! This is ready to go.

**Comment by RachL** [comment]
This isn't working anymore 😢 
@luisramos0 do you know if the latest changes have something to do with it? I will prepare an issue

**Comment by luisramos0** [comment]
I am sorry to hear that.
I dont see how the new changes could break this. The ordering is still there.
Please create an issue, I'll have a look.

**Comment by RachL** [comment]
@luisramos0 I did one here: https://github.com/openfoodfoundation/openfoodnetwork/issues/4845 is it something we can tag good first issue?

**Pull request merged**
