### PR TITLE
Rails 5 upgrade with dualboot

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

This starts with https://github.com/openfoodfoundation/openfoodnetwork/issues/6346 and closes https://github.com/openfoodfoundation/openfoodnetwork/issues/4800

All credit for making the gemfile dependencies work in rails 5 is for @Matt-Yorkley (I coudlnt make it work!) :clap: :clap:
https://github.com/Matt-Yorkley/openfoodnetwork/commits/rails-5-0
 
All I did was to make it dual bootable. The beauty is that this PR **can be merged to master** and you can run BOTH green:
bundle install      (rails 4.2)
and 
DEPENDENCIES_NEXT=1 bundle install       (rails 5)

NOTE: I think we can make the Gemfile simpler than this, I dont think we need so many gems inside the first if ENV['DEPENDENCIES_NEXT'], we can move some to the shared space.

#### What should we test?
I am not sure we even need a sanity check on the app running on rails 4.2...
We can then start looking at the rails 5 build and fix problems **in master**!!!

#### Release notes
Changelog Category: Technical changes
Setup dual boot for rails 5 upgrade.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
How well would dependabot handle these conditionals and two separate Gemfile.lock files..?

**Comment by luisramos0** [comment]
yeah, good question. I dont know.
I can't think of other approach than merging this and see how dependabot handles it... if not good, we can revert.
I think we can wait until the avalanche is over to test this :+1:  Also because the avalanche will make this PR simpler as mentioned above.

**Comment by luisramos0** [comment]
ok, the avalanche of upgrades was smaller that I thought. It's already over, with some pending PRs.
This PR will remain very similar to this anyway so I think this is ready for review. I recommend we code review, verify the app still works in staging, merge and then see if dependabot doesnt get too confused and keeps helping us.

**Comment by sauloperez** [comment]
The gem avalanche is mostly over so we can revisit this hopefully in a few days.

**Comment by luisramos0** [comment]
rails 4.2 and ruby 2.4.4 upgrades are over. Can we move forward with this?

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
I gave a try at this with docker and dual boot seems to be working but I found:

```
worker_1  | Unsupported rails environment for compass                                                                           
web_1     | Unsupported rails environment for compass                                                                           
worker_1  | rake aborted!                                                                                                       
worker_1  | TypeError: superclass mismatch for class Request                                                                    
worker_1  | /usr/src/app/lib/action_dispatch/request.rb:31:in `<module:ActionDispatch>'                                                                                                                                                                         
worker_1  | /usr/src/app/lib/action_dispatch/request.rb:30:in `<top (required)>'    
```

did someone else find this?

**Comment by luisramos0** [comment]
yes, nice, welcome to rails 5. That's the error you get while running rails s in rails 5.

It's an easy fix, just comment out what's in config/initializers/action_dispatch_request_deep_munge_patch.rb (credit to Matt in #6635).
Anyway, I think any fix for rails 5 should come after this PR is merged, and those fixes will go into master!!!

In this case, if this is needed in rails 4.2, the code in master will looks like this:
image

**Comment by luisramos0** [comment]
if anyone is worried about the clean up after the upgrade to rails 5, I think it's quite easy to search for ENV['DEPENDENCIES_NEXT'] in the code and delete all the parts related to rails 4.2 like this require example above.

**Comment by sauloperez** [comment]
ok, cool. Wasn't sure what to expect and whether or not this was normal. Then, this is ready to go IMO.

**Review by mkllnk — APPROVED** [review]
:champagne:

**Comment by sauloperez** [comment]
if there's an issue we'll see it in the release testing IMO. I managed to boot it locally and use the app normally.

**Comment by sigmundpetersen** [comment]
I see the repo url of the CI project is git@github.com:openfoodfoundation/spree_i18n.git
That can't be right, we should review the project settings and see if everything is setup correctly.

**Pull request merged**
