### PR TITLE
[README] Updated build status badge

### LINKED ISSUE #2822: Update CI's badge
## Description
We didn't update the README's CI badge when switched to Semaphore CI and so it still points to the last CI run we did in Travis. That is 3 months ago.

## Expected Behavior
The README's CI badge needs to point to the latest CI execution on `master` so that we can know the status of our test suite.

### PR DESCRIPTION
**Pull request by 73VW**
#### What? Why?

Closes #2822

#### What should we test?
Nothing.

#### Release notes

Changelog Category: Fixed

### CODE REVIEW

**Comment by sauloperez** [comment]
Hi @73VW! Welcome!
Very happy to have your help with it.

If you have any questions setting up the dev env, with Github, etc. feel free to ask on the dev channel of [our Slack team](https://openfoodnetwork.org/slack-invite).

**Comment by luisramos0** [comment]
changing the README, no tests are necessary.

**Comment by luisramos0** [comment]
Hey @73VW , yes, "ready to go" means that someone can just merge it. I'm not currently merging PRs into master myself. Someone else will do it soon.

**Comment by 73VW** [comment]
@luisramos0 I didn't know this, thanks!

**Comment by Matt-Yorkley** [comment]
Third time today I've seen this test giving a flaky failure: 

screenshot from 2018-10-05 12-08-02

**Comment by sauloperez** [comment]
Can we skip it and then tackle it in an issue? We've done this before.

**Pull request merged**
