### PR TITLE
Format money amounts in report spreadsheets as numbers

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Australian enterprises rely on reports with totals which can also be used for calculations. But the Order Cycle Customer Totals report formatted some price columns as string with a currency symbol (unlike other reports) which means that they are not numbers in office applications to continue calculations.

This was due to a general autoformatting rule which I removed now. But the packing reports and Bulk Coop Supplier report still have currency formats defined.

An alternative solution would be to add total rows to the CSV format.

#### What should we test?

Are there any reports which absolutely need a currency format?

- Check the formatting of all reports with prices?

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
👌

**Comment by jibees** [comment]
Should probably be placed on the top of the `Test Ready` column then

**Comment by RachL** [comment]
AH no conflict have arisen, moving back to in dev ping @mkllnk

**Comment by drummer83** [comment]
Not sure who did this, but now all tests have passed... :+1:

**Comment by sigmundpetersen** [comment]
Hey @drummer83 I just re-ran the build 👍 
Sometimes it's just a hangup in GH Actions or some other thing

**Comment by mkllnk** [comment]
@RachL 

> AH no conflict have arisen, moving back to in dev

I read this sentence probably 42 times because my brain always read: "Ah, no conflict arisen, moving back to in dev". Then I thought it may have been a typo, maybe you wanted to write: "Ah, one conflict arisen". But that doesn't make much sense either. Much later I finally realised: "Ah no, conflict arisen". :facepalm: Sometimes my brain is going in the wrong direction...

**Comment by RachL** [comment]
@mkllnk I couldn't read myself either. Sorry, sometimes I think I write in French while typing in English... :face_with_head_bandage:

**Comment by drummer83** [comment]
Thanks for this PR, @mkllnk!

I have checked our reports on screen and in the xlsx files. Here is an overview of all reports which contain some 'money' columns. 
grafik

We can see that all 'text with currency' (formatted as string and can't be used for calculations) have been transformed into 'numbers' (which can be used for calculations). There are exceptions but these have been highlighted by Maikel already in the opening post:

> But the packing reports and Bulk Coop Supplier report still have currency formats defined.

So this is according to my expectation and I think we are **ready to go** here! :partying_face: 

Some notes and asking @RachL and @mkllnk for their expertise:
- Money columns in Enterprise fees report are formatted as text (without currency) in xlsx. No calculations possible. --> Intentional or create an issue to fix this? Impact on integrations?
- We still have the 4 mentioned reports using 'text with currency'. --> Why is that? Create an issue? Impact on integrations?
- For those columns without currency symbol within the data itself the currency should be displayed in the header (as it does for other reports). --> Create issue? Impact on integrations?
- Incorrect header in Enterprise fees report can be fixed in Transifex --> no issue
- Incorrect header of column 4 in Tax type report can be fixed in Transifex --> no issue

**Comment by drummer83** [comment]
Yes, @mkllnk! Will do.

**Comment by drummer83** [comment]
Here is the follow-up issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/9384.

**Pull request merged**
