### PR TITLE
Rails 4.2 upgrade

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### ActiveJob

`ActiveJob` is now a core part of Rails, essentially it's a wrapper for the interfaces of various job-processing services, like `DelayedJob`, `Sidekiq`, or `Resque`. Instead of passing a job directly to the service, it's now passed to `ActiveJob`, which passes it to the specified backend. This means the backend can be seamlessly switched out for a different one with one line of code, or in testing it can be substituted for a mock backend that is easier to work with.

`ActionMailer` has also had various changes which are aimed at integrating it with `ActiveJob`.

#### Responders

A large amount of functionality related to how controllers respond to requests has been extracted out from Rails core to the `responders` gem. This includes lots of methods like `#responds_to` and `#respond_with`. This move comes with a lot of associated changes and refactoring behind the scenes in base classes like `ActionController::Base`.

#### StateMachine -> StateMachines

The `state_machine` gem was abandoned by it's maintainers and is incompatible with Rails 4.2. It was forked and now has a fixed and maintained alternative called `state_machines`.

#### Paranoia

The `paranoia` gem that handles soft-deleting has some problems with Rspec transactions in Rails 4.2, creating lots of broken specs around soft-deletion. This bug is patched in the `rails-4` branch in their repo, but that branch is totally out of date and not available in any releases. :see_no_evil: I've applied their patch manually in an initializer and it's working as intended.

### CODE REVIEW

**Comment by jhsu802701** [comment]
What's the reason for skipping Rails 4.1?  Isn't upgrading from 4.0 to 4.2 too much to do all at once?  What am I missing?

**Comment by Matt-Yorkley** [comment]
@jhsu802701 there's already a Rails 4.1 upgrade branch that's almost ready for merge here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6297. It's been held back slightly, waiting for some other _very large_ changes to be merged from another branch: https://github.com/openfoodfoundation/openfoodnetwork/issues/5978

**Comment by luisramos0** [comment]
I see, you are going for the home run!!! 3 specs broken :tada: :tada: :tada: :clap: :clap: :clap:

**Comment by Matt-Yorkley** [comment]
> I see, you are going for the home run

And there it is! There's probably a few bits that we need to look at, but **build 85 is green**.

home-run

**Comment by luisramos0** [comment]
This needs to be broken in a few PRs before review, right? I have looked at the code already and there's nothing controversial :tada: 
It's important we get as much as possible into master, for example, all strong params changes can go to master already, even before rails-4-1 is merged.

**Comment by Matt-Yorkley** [comment]
> all strong params changes can go to master

Some of these changes are tied in to `ActionController::Base` changes in 4.2, but I'll see how much I can pull out :+1:

**Comment by Matt-Yorkley** [comment]
Hmmm not all of the changes are compatible. I've shifted the compatible changes (~80%) into this PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/6343. Basically there were two groups of strong params issues, one relating to API controllers and one relating to collections. The API changes can go to master, the others will have to stay in this branch.

**Review by luisramos0 — COMMENTED** [review]
This PR is 100% uncontroversial. I only have questions about things extracted to https://github.com/openfoodfoundation/openfoodnetwork/pull/6343 :+1: 

I think we will need some more detailed testing notes with the actual features being touched:  PDF generation, order state machine (some tests around orders workflow between address, payment and complete), something related to responders, etc

**Comment by luisramos0** [comment]
this branch is going to be used instead: https://github.com/openfoodfoundation/openfoodnetwork/pull/6354

**Pull request closed without merging**
