### PR TITLE
Move sets out of app/models to app/services/sets

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

These classes are not model classes. I think they fit perfectly well in app/services/sets and help make messy (and core) app/models simpler.

#### What should we test?
I think we can run a simple test checking that catalog, inventory, enterprise fees and order cycles list pages are working correctly.

#### Release notes
Changelog Category: Technical changes
Improve code organization.

### CODE REVIEW

**Comment by luisramos0** [comment]
the code climate issues are listed in rubocop_manual_todo as before

**Review by mkllnk — COMMENTED** [review]
The code looks good to me but I'm not sure if I agree with the approach.

The assumption here seems to be that only descendents of `ActiveRecord::Base` are models. And I think that there are two sides to this:

* Rails models are usually persisted ActiveRecord models. The `app/models` directory is a Rails convention and we should only put Rails stuff in there. Everything else should be separate.
* A model in the MVC pattern is a data structure. It doesn't matter if it's persisted or not and it doesn't matter from which class it inherits. Since a set is a data structure, it belongs to the model directory.

In this case, the ModelSet is very closely interacting with models and shares the same interface by using ActiveModel modules. You can say that it's a model itself.

I do think that the code can simplified though. The callbacks are used only in one place each. And is the main benefit just to easily pass on params, save and have a combined error field? The params should probably be checked with strong parameters. Calling `save` is easy on a collection and why not display the errors for each entry? Sorry, this is off-topic.

I'm not sure how to proceed here. I'm not approving but if others think that this is a good idea, okay, no big harm.

**Comment by luisramos0** [comment]
Hi Maikel, thanks for the feedback.
I recommend this change because it helps simplifying the models area of the
app whichis unnecessarily compllicated in ofn.
Model is a very generic term. Id call these classes service objects. I
mean, the service layer does have data objects (models). I think these
qualify as that.
For the future and in any MVC odebase
I recommend you take as much code of the MVC into a well organized service
layer that includes data objects like the ones in this pr.

**Comment by mkllnk** [comment]
I understand that perspective as well. What do others think?

**Comment by luisramos0** [comment]
There are some conflicts here. I will wait for approval. I can fix the conflicts after this approach is approve.

**Comment by andrewpbrett** [comment]
This one's getting a bit stale. I don't have a strong preference either way, but it makes sense to me that the sets would be outside of the models directory, so if @luisramos0 doesn't mind rebasing/resolving conflicts that would be my vote.

**Comment by luisramos0** [comment]
:+1: rebased

**Review by andrewpbrett — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Comment by mkllnk** [comment]
More conflicts...

**Comment by filipefurtad0** [comment]
Hey @luisramos0 ,

Had a quick look at the pages you mention, and tested basic functionality:

- product catalogue
- inventory
- enterprise fees
- order cycles

Everything looks and works as before. Ready to go.

**Pull request merged**
