### PR TITLE
Replace setup_intents class from active merchant v1.98 with a decorator that will change the current v1.119

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Raised in https://github.com/openfoodfoundation/openfoodnetwork/pull/7272
We can use the code in active merchant and use a decorator to customize some parts.

Here I am keeping the code that was changed as is. We could reduce this decorator even more but that would probably require more testing. All the changes to the original code were done to make it work so they will need some form of adaptation or fix before being removed. 

Also removed the stripe_decorator, that code is now available in v1.119.

#### What should we test?
We need to test stripe SCA payments.

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Review by Matt-Yorkley — CHANGES_REQUESTED** [review]
There's various relevant errors in the build...

**Comment by luisramos0** [comment]
new trial.

**Review by andrewpbrett — APPROVED** [review]
This looks good, thank you @luisramos0! Will definitely need some careful testing - @filipefurtad0 and I could team up on this. Once it gets a second approval let's move it to dev ready and I'll do some checks before Filipe picks it up.

**Comment by Matt-Yorkley** [comment]
Okay, so just to understand the context; we had an old version of active_merchant (< v1.98), then we added some decorators to bring in some changes from v1.98, then we bumped active_merchant a few times (> v1.98) which meant the decorators were outdated?

And now we're removing two decorators and replacing them with a smaller one?

It feels like we should document this a bit (maybe in a tech-debt issue?) and have a plan to move towards removing this last decorator, if possible?

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by andrewpbrett** [comment]
@Matt-Yorkley sort of, yes. The stripe_decorator is no longer necessary at all now that we're on ActiveMerchant > 1.98.0, so this PR removes it. The payment_intents_decorator is new and @luisramos0 wrote it so that it only overrides methods that we've changed in the PaymentIntentsGateway class. So now rather than having to bring it a whole file that's different from the gem, we just bring in the decorator.

**Comment by filipefurtad0** [comment]
Hey @luisramos0 !

It looks like this PR is breaking 3D-authentication, for previously set enterprises. I tried different staging servers, and also re-connecting the hub with Stripe. All looks fine in the payment settings:

image

However, placing orders with 3D cards (like x-3155, x-3184) triggers this error:

- frontoffice

image


Triggers this bugsnag error, with more details:
https://app.bugsnag.com/katuma/katuma/errors/6062beab8d382c000784abea?event_id=606ef2b900770e502a940000&i=sk&m=nw

- backoffice

image

For some reason, this payment attempt did not introduce any new bugsnag alerts.

Payments are successful with non-3D auth cards (like 424242....) 

This one needs a second look, moving back to In dev :+1:

**Comment by Matt-Yorkley** [comment]
I think this probably just needs a rebase and we can retest it. I'll do it now :ok_hand:

**Comment by filipefurtad0** [comment]
Hey @luisramos0 and @Matt-Yorkley ,

Tested StripeSCA payments, in the previously failing scenarios:
- shopfront and backoffice orders paid with cards x-3155 and x-3184 (valid SCA cards) - all good
- tested some error messages like the insufficient funds (card x-3178) - OK
- saving a card on checkout - OK

All good, ready to go :+1:

**Pull request merged**
