### PR TITLE
Fix schema version

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Previous schema version was commited after manually resolving a merge conflict. See https://github.com/openfoodfoundation/openfoodnetwork/pull/7259#discussion_r614050742

Note: needs to go in the release.

#### What should we test?

Running `db:reset` or `db:migrate` should work okay.

#### Release notes

Updated schema version

Changelog Category: Technical changes

### CODE REVIEW

**Review by jibees — APPROVED** [review]

**Comment by Matt-Yorkley** [comment]
Every Rails dev has done this at least once, so welcome to the club! :smile:

If you're manually resolving a merge conflict in `schema.rb`, the version needs to be set to whichever is the most recent timestamp :+1:

**Comment by jibees** [comment]
> Every Rails dev has done this at least once, so welcome to the club! 😄

Proud to be part of the club. Is there any welcome gift? ;)

> If you're manually resolving a merge conflict in `schema.rb`, the version needs to be set to whichever is the most recent timestamp 👍

I've resolved by keeping the same value as the previous diff. Anyway, thanks for the tip!

**Comment by Matt-Yorkley** [comment]
> I've resolved by keeping the same value as the previous diff

Yeah, it's really counter-intuitive if the PRs get merged in the reverse order to the order in which the migrations were created. When you get to resolving the merge conflict it _feels like_ you should keep the one from the previous diff. But in this case, the higher is number is always the right one :+1:

**Comment by andrewpbrett** [comment]
Whoops, I merged another schema change and didn't realize this was open - I think it just needs a rebase.

**Comment by andrewpbrett** [comment]
Oh, or, apparently it's not needed at all any more. I'd never seen a force push automatically close a PR like that.

**Comment by mkllnk** [comment]
Haha, I included the same resolution in another wip pr yesterday. :smile:

**Pull request closed without merging**
