### PR TITLE
Emails/validation

### LINKED ISSUE #2840: When user changes their mail from "my account", no confirmation is sent + disturbing UX
## Description

As a user I try to change my email address...
1- the UX is bad, when I click on "proceed" I am redirected violently to login modal
2- When I login again I see a message saying the new email will apply when it is validated, but I never receive any validation email on the new mailbox... **UPDATE: I receive the email but not on the new email, on the old one!!! So I can't validate the new email obviously.**

## Expected Behavior
1- when i click on "proceed" I get a success message saying a validation email was sent to the new address, and that I'll be able to connect with this new address once validated.
2- I should receive a validation message on that new address.

## Steps to Reproduce
1. With any user, go to "my account" and "account info" (last tab)
2. Change the email, type your password, and validate.
3. Check the new malbox: nothing
4. Check the old mailbox: you see validation email

## Animated Gif/Screenshot

https://www.useloom.com/share/fdda1736be3e47cfbdecdf24c6edc3fc

## Context

I was trying to do support to a user who wanted to change their email.

## Severity
bug-s3: a feature is broken but there is a workaround = keep using the old email...

## Your Environment

* Version used: v1.18
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu 18

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2840

Confirmation emails for users who are changing their password were being sent to `user.email` instead of `user.unconfirmed_email`, which is where the new pending email gets set on a user that is already confirmed.

#### What should we test?

Confirmation emails when changing email should now be delivered to the correct email. Confirmation emails for new users should also be sent to the correct email.

#### Release notes

Fixed confirmation emails being sent to the old address when changing to a new email address.

Changelog Category: Fixed

### CODE REVIEW

**Comment by mkllnk** [comment]
Staged on https://staging.openfoodnetwork.org.au/.

**Comment by RachL** [comment]
@myriamboure @Matt-Yorkley it is working well except I don't see a message when I update my email (as you were asking in your issue Myriam), I'm directly logged out.

Still I think that this PR covers the most urgent case so I would propose to merge this and create a new issue in order to improve the UX on the log out part. Are you both ok with this?

My testing notes:
https://docs.google.com/document/d/1aCqXCZNzJ8Ts9P6jyRD9IGe56guyTP0SuTEz-cvBp6Q/edit#

**Comment by myriamboure** [comment]
@RachL @Matt-Yorkley already did https://github.com/openfoodfoundation/openfoodnetwork/issues/2848

**Comment by RachL** [comment]
Awesome ! Ready to roll then

**Pull request merged**
