### PR TITLE
[Enterprise Fee Summary] Merge "Enterprise Fee Summary" report to master

### LINKED ISSUE #2616: Build Enterprise Fee Summary Report
https://docs.google.com/spreadsheets/u/1/d/1pnJwHgBo2sokdcwNoLquYlVh8ICUcx6X4J2ZAMnRyio/edit?usp=sharing
Sheet "THIS By Customer"

Fee Type | Enterprise Owner | Fee Name | Customer | Fee Placement | Fee calc on trans through | Tax Category | $$ SUM
-- | -- | -- | -- | -- | -- | -- | --
Admin | Coord 1 |   | Customer A | Coordinator | All |   | 2.3
Admin | Coord 1 |   | Customer B | Coordinator | All |   | 4.7
Admin | Hub 2 |   | Customer A | Outgoing | Hub 2 |   |  
Admin | Hub 2 |   | Customer B | Outgoing | Hub 2 |   |  
Mgmt | Coord 1 |   | Customer A | Incoming | Supplier 2 |   |  
Mgmt | Coord 1 |   | Customer B | Incoming | Supplier 2 |   |  
Packing | Supplier 1 |   | Customer A | Incoming | Supplier 1 |   |  
Packing | Supplier 1 |   | Customer B | Incoming | Supplier 1 |   |  
Transport | Coord 1 |   | Customer A | Incoming | Supplier 2 |   |  
Transport | Coord 1 |   | Customer B | Incoming | Supplier 2 |   |  
Transport | Hub 3 |   | Customer A | Outgoing | Hub 3 |   |  
Transport | Hub 3 |   | Customer B | Outgoing | Hub 3 |   |  
Transport | Supplier 1 |   | Customer A | Incoming | Supplier 1 |   | etc
Transport | Supplier 1 |   | Customer B | Incoming | Supplier 1 |   | etc

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

* Closes #2616
* Relates to #2656
* Relates to #2672

This would merge the transitional branch for the Enterprise Fee Summary to master.

#### What should we test?

1. Do a general test of whether this breaks the layout and that checkout is not broken.
2. Do a smoke test of report generation:
    a. Link in the admin Reports page
    b. Filters are working
    c. CSV report is working
    d. HTML report (below filters) is working

#### Release notes

* Add "Enterprise Fee Summary" report available only to superadmin users.

Changelog Category: Added

#### Discourse thread

* https://community.openfoodnetwork.org/t/report-that-isolates-various-enterprise-fees/1361

#### Dependencies

* #3337

### CODE REVIEW

**Comment by kristinalim** [comment]
@kirstenalarsen Were you able to test #3115 with the recommendations I made in the issue description before? I was the one who merged that PR in the transitional branch, so I included an updated version of that (I added Items 2 and 5) here for a more thorough round of testing by a non-dev, before everything is merged to master.

**Comment by kristinalim** [comment]
I moved this PR straight to "Test Ready" because these changes have already been approved in code review.

**Comment by kirstenalarsen** [comment]
@kristinalim I cannot stage this because the Semaphore build has failed . .

**Comment by kristinalim** [comment]
@mkllnk I was surprised too, actually - I expected a lot of lines but not this much.

Although it makes sense:

1. The code is split quite well into responsibilities (e.g. permissions, rendering, mapping DB result columns to report columns), for better readability and testability.
2. We also have well formatted SQL left joins in `Scope` with lots of code whitespace. That class owns more than 10% of this PR in terms of added lines. (Preferred SQL left joins over eager/lazy -loading for better performance.) There is a pending issue #3214 for seeing if `ActiveRecord` associations can be reused here.
3. Great test coverage, IMO. :+1: 

Looking at the line count, almost half of these are for new test files:

```sh
$ wc -l $(find . -path "./spec/validators/*" -or -path "./engines/order_management/spec/*" -or -path ./spec/features/admin/reports/enterprise_fee_summaries_spec.rb -or -path spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb)
[...]
   1491 total
```

**Comment by kirstenalarsen** [comment]
sooo. I am going to say that this is ok to merge to master as it is restricted to superadmin and it passes the tests above and doesn't break anything 

I have found a few issues where I'm not sure what it's doing - BUT I think we are going to be so much better off to look at this with real data . . so let's get it through!
https://docs.google.com/document/d/1IxYHgzITDn0QcV-Po9sm1310cNiCdHTDx2kOGGlLrfY/edit

**Comment by kirstenalarsen** [comment]
Merge to master as passes tests above and is restricted to superadmin

There are some confusions, that I think need testing with real data
https://docs.google.com/document/d/1IxYHgzITDn0QcV-Po9sm1310cNiCdHTDx2kOGGlLrfY/edit

**Comment by sauloperez** [comment]
`./spec/features/admin/product_import_spec.rb:131` failed so I retried it. Meanwhile, I'll check if it is a flaky one. I'll merge as soon as it gets :green_apple:

**Comment by sauloperez** [comment]
Bad luck. `spec/features/admin/product_import_spec.rb:131` is still failing (alongside other flaky ones this time) so might be related to this PR.

**Comment by luisramos0** [comment]
maybe rebase to get latest "flaky fixes"?

**Comment by kristinalim** [comment]
The product import spec failure is also an "intermittent" failure, which has been fixed here: #3430. "Intermittent" because it will pass in less than 24 hours, when it's February 10 in Melbourne time.

The other two are related to spec failures that still have [open issues](https://github.com/openfoodfoundation/openfoodnetwork/issues?q=is%3Aissue+is%3Aopen+%22flaky+spec%22), but yes, better luck with a rebase.

I don't have Github permissions to modify this upstream branch though. Asking on Slack for anyone (any of you) to do this, or give me enough Github permissions. :slightly_smiling_face: Thanks!

**Comment by kristinalim** [comment]
Yes! :grin: A green build. Thanks for rebasing, @luisramos0!

**Comment by kirstenalarsen** [comment]
So this is ready to merge I think. Yay

**Comment by sauloperez** [comment]
Putting the merge on hold until we get https://github.com/openfoodfoundation/openfoodnetwork/pull/3337's conflicts fixed.

**Comment by luisramos0** [comment]
are we merging #3337 into this one and merging this one into master without staging/testing this and 3337 together?

**Comment by kristinalim** [comment]
@luisramos0 That confused me too, because the base branch and separation of PRs is highly dependent on the timeline...

How about we merge this tested PR into master first. Then for #3337, I will change the PR base branch of #3337 to `master` and rebase it, and then it can also be merged without testing again? Considering that we often rebase PRs upon `master` even after testing.

**Comment by luisramos0** [comment]
@kristinalim you will know what's the best approach :-)
I just wanted to raise the concern so that you aware.

**Comment by kristinalim** [comment]
If that doesn't horrify the merger, that's the approach that I think is efficient and is still safe. :slightly_smiling_face: :+1: I will update the other PR as soon as this is merged.

**Pull request merged**
