### PR TITLE
4243 Restore old pagination API for inventory products

### LINKED ISSUE #4243: Inventory is limitted to the first 100 products
## Description

The inventory page shows 10 products to start with. There is a button to display more. But it's showing only up to 100 products. An inventory with more than 100 products can't be managed.

## Expected Behavior

Then inventory shows 10 products and a button to load x more. x is the total number of products in the inventory minus the 10 products already shown. For example, the button will says "Show All (149 more)" more and after clicking on it, the total 159 products are shown and the buttons disappear.

Please note: the previous behaviour did show "Show All (90 more)" for a short time during page load. But more products were loaded in the background and that number increased to the full amount.

## Actual Behaviour

The inventory shows 10 products and a button to load 90 more. After clicking the button, 100 products are shown.

## Steps to Reproduce

1. Create or use an enterprise with inventory, for example a farm shop.
2. Add more than 100 products to the inventory.
3. Load the inventory page: `/admin/inventory`
4. Observe the button at the bottom.

## Animated Gif/Screenshot

Shown first and currently it doesn't change:
Screenshot from 2019-09-08 16-27-14

Shown in v1.3.1 when all products were loaded:
Screenshot from 2019-09-08 16-26-22

## Context

The Australian farmer New Life Farm reported this issue. They use the inventory every week and this week they saw the issue. I verified that the last release introduced this bug.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround

I'm not sure if the inventory is a critical feature. But for people using it, they may not be able to manage their stock to successfully open an order cycle. Not being able to sell produce, seems to be an s1.

A possible workaround is to not use the inventory. But this may need a lot of effort and I don't know how well it works and how to best transition.

## Your Environment

* Version used: v1.4.1 au-prod

## Possible Fix

I changed the number of products loaded in one go from 100 to 200 to help our farmer straight away. app/assets/javascripts/admin/variant_overrides/controllers/variant_overrides_controller.js.coffee

But that doesn't really solve the problem. I guess, we have to apply the new Bulk Products Edit pagination logic to the inventory as well.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #4243.

I'm re-adding an attribute to the products API because it's still used by the inventory page. This is an easy fix that I can deploy without risk. A rewrite of the inventory pagination should follow.

#### What should we test?

1. Create or use an enterprise with inventory, for example a farm shop.
2. Add more than 100 products to the inventory.
3. Load the inventory page: `/admin/inventory`
4. Check the numbers on the load-all button at the bottom.
5. Click the button to load all products and check that they all appear.
6. Go to the Bulk Products Edit page: `/admin/products`
7. Check that you can see all products going through the pages.

#### Release notes

Fixed: The inventory can display more than 100 products again.

Changelog Category: Fixed

### CODE REVIEW

**Comment by mkllnk** [comment]
Okay, cool. I didn't see the other spec because the naming is so different. There is the VariantOverridesController and the InventoryItemsController.

It's also not great that this spec needs 30s to run. The bulk of that is creating products. If you have an idea how to speed that up... but then I think we need to rewrite it anyway. Once we implement the fetching properly, we can define to load 15 products at a time and don't need to create as many products.

**Comment by mkllnk** [comment]
I moved the spec to the existing file. Back to you, @luisramos0.

**Comment by lin-d-hop** [comment]
I just tested this on UK production with the user that reported the issue.

All products are showing again in Inventory as expected. They also appear in Products (BEP) correctly, tested as per notes above.

This has been deployed to all production servers already so I feel pretty confident to move to Ready To Go for a dev to close.

As a side note - It took a LONG time for all of the products to load in Inventory (about 6 minutes. While I was waiting I created a custom emoji and added it to slack. We can argue the merits of this another time).

**Comment by sauloperez** [comment]
> (about 6 minutes. While I was waiting I created a custom emoji and added it to slack. We can argue the merits of this another time).

LOOOOL

**Pull request merged**
