### PR TITLE
3417,2962,3358 [Flaky Spec] Address some race conditions for bulk order management specs

### LINKED ISSUE #2962: [Flaky Spec] Fix unreliable bulk_order_management_spec.rb feature spec
## Description

I found this error while passing CI on https://github.com/openfoodfoundation/openfoodnetwork/pull/2958. You can check the CI build on https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-2958/builds/2

It's totally unrelated to that PR's change so it's likely an unreliable test that needs to be fixed.
 
```
1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using action buttons using edit buttons shows an edit button for line_items, which takes the user to the standard edit page for the order
     Got 1 failure and 1 other error:

     1.1) Failure/Error: expect(URI.parse(current_url).path).to eq "/admin/orders/#{o1.number}/edit"
          
            expected: "/admin/orders/R722674705/edit"
                 got: "/admin/orders//edit"
          
            (compared using ==)
          # ./spec/features/admin/bulk_order_management_spec.rb:625:in `block (5 levels) in <top (required)>'

     1.2) Failure/Error: @app.call(env)
          
          ActiveRecord::RecordNotFound:
            Couldn't find Spree::Order with number = edit
          # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
          # ------------------
          # --- Caused by: ---
          # Capybara::CapybaraError:
          #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
          #   ./spec/spec_helper.rb:92:in `block (2 levels) in <top (required)>'

Finished in 18 minutes 29 seconds (files took 36.69 seconds to load)
855 examples, 1 failure, 5 pending

Failed examples:

rspec ./spec/features/admin/bulk_order_management_spec.rb:605 # 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using action buttons using edit buttons shows an edit button for line_items, which takes the user to the standard edit page for the order
```

## Expected Behavior

This test should always pass.

## Actual Behavior

I don't have data to claim it failed before, but I bet it did.

### LINKED ISSUE #3358: [Flaky Spec] spec/features/admin/bulk_order_management_spec.rb:322,436
## Description
This spec seems be unreliable: https://github.com/openfoodfoundation/openfoodnetwork/pull/3354#issuecomment-455585480

## Context
Our automated test fail regularly due to unreliable specs. If you encounter this in your build then comment on this issue or add :+1: 

Error:

```
Failures:

  1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using drop down seletors distributor filter displays all line items when 'All' is selected from distributor filter
     Failure/Error: expect(page).to have_no_selector "tr#li_#{li2.id}"
       expected #has_no_selector?("tr#li_34") to return true, got false
     # ./spec/features/admin/bulk_order_management_spec.rb:322:in `block (5 levels) in <top (required)>'
```

### LINKED ISSUE #3417: [Flaky Spec] spec/features/admin/bulk_order_management_spec.rb:488
## Description

This spec is unreliable: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3416/builds/1

## Context

Our Semaphore builds fail regularly because of these unreliable tests. If you encounter this in your build, please comment on this issue or add :+1: 

Error:

```
  1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using date restriction controls displays only line items whose orders meet the date restriction criteria, when changed
     Failure/Error: expect(page).to have_selector "tr#li_#{li1.id}"
       expected to find visible css "tr#li_57" but there were no matches
     # ./spec/features/admin/bulk_order_management_spec.rb:488:in `block (4 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

* Closes #3417 
* Closes #2962 
* Closes #3358 (two separate issues)

Specs in affected examples are intermittently failing.

#### What should we test?

Please do a general test that the bulk order management page is still functioning.

Semaphore build should be green.

In the long term, these specs should also not fail.

#### Release notes

* Address intermittently failing feature tests

Changelog Category: Fixed

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
Semaphore fail @kristinalim  😞

**Comment by kristinalim** [comment]
@daniellemoorhead Yes, I'm working on the other failing tests in other PRs. :slightly_smiling_face: 

@luisramos0 I only forgot to mark this `pr-no-test`, but just now realized this needs a test in staging. FYI, I added this to testing instructions:

> Please do a general test that the bulk order management page is still functioning.

**Comment by RachL** [comment]
Bulk order management page looks fine 👍 
https://docs.google.com/document/d/1hla_5DoI6r8FiRgzbgRXdYpaS3JiVgC1nYfMkLKh7HA/edit#

**Comment by sauloperez** [comment]
Would you mind fixing those conflicts @kristinalim ? also, the build is not green. Anything to do with this change?

**Comment by kristinalim** [comment]
@sauloperez I rebased this branch just now.

The failing specs are not related:

1. `spec/features/admin/product_import_spec.rb:131` - Addressed in #3420
2. `spec/features/admin/enterprise_roles_spec.rb:131` - Pending issue #3426

:crossed_fingers: Hopefully no failing specs this time.

**Comment by luisramos0** [comment]
build is green, merging.

**Comment by sigmundpetersen** [comment]
./spec/features/admin/bulk_order_management_spec.rb:317 (#3358) failed again after merge https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/463

**Comment by kristinalim** [comment]
Thanks, @sigmundpetersen! @luisramos0 reopened #3358.

**Pull request merged**
