### PR TITLE
added alert to producer product page

### LINKED ISSUE #3362: Add 'would you like to save changes?' alert to Product page
## Description
On the Bulk Edit Products page (or Inventory page), if I makes some changes and don't click save, then I navigate away from the page, my changes are lost. Can we please add a dialogue box in this case asking the user whether they want to Save Changes?

## Expected Behavior
If I make some changes but don't click save, then i navigate away,  I would like to be asked 'are you sure you want to discard those changes' or 'would you like to save your changes'. This helps the user to avoid making mistakes.

## Actual Behavior
I accidentally navigate away without saving my changes and now I've lost all the edits I just did.

## Steps to Reproduce
1. Go to a Products page
2. Edit something about a product and then navigate to another tab in the backed.
3. You'll see that you are not asked 'would you like to save changes' and your edits are lost.

1. Go to Inventory page
2. Edit something about a product and then navigate to another tab in the backed.
3. You'll see that you are not asked 'would you like to save changes' and your edits are lost.

## Context
One example from an Aus user - I'm trying to prepare my stock availability. I think I've saved everything correctly but when I go to the shop I find the some of my edits haven't saved - I must have forgotten to click save. I wish there was an easier way to prevent these little mistakes - they are hard to rectify if I have a customer accidentally order something I don't have, or I lose sales because something I have on hand isn't showing in the shop.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
Aus production, Desktop, Chrome

### PR DESCRIPTION
**Pull request by Chrisyee22**
Add 'would you like to save changes?' alert to Product page

Closes #3362

#### What should we test?
Test that the alert pops up prior to leaving the page.

#### Release notes

Changelog Category: Added 

#### Dependencies
None that I am aware of.

### CODE REVIEW

**Comment by luisramos0** [comment]
hey @Chrisyee22 welcome to OFN, it's great to have your contribution!

**Comment by sauloperez** [comment]
Thanks a lot for your contribution @Chrisyee22 ! Please, don't forget to add a short sentence beyond the category of the change under *Release notes*. That's what we use to compile the whole release notes.

**Comment by luisramos0** [comment]
moving to "in dev" until feedback is included.

**Comment by daniellemoorhead** [comment]
Hey @Chrisyee22, looks like this is back with you to make a couple of changes as per @luisramos0 and @sauloperez feedback. Doesn't look too onerous though, so hopefully they're quick changes and you can get it back for review soon!

**Comment by Chrisyee22** [comment]
@luisramos0 I just wanted to clarify from the question I asked in the slack channel. I wasn't placing my code in the .haml file but in the location which you posted here; app/assets/javascripts/admin/bulk_product_update.js.coffee. I wasn't sure if the .haml file needed to be adjusted because my change didn't seem to be working and I am not sure what is missing. `$scope.$on('$routeChangeStart', function (event, next, current) {
       if(confirm("Are you sure you want to leave without saving?")){
             event.preventDefault();
       }
    });`
This should bring up a window asking the user to confirm the route change but it's not. Just wondering what I am missing?

**Comment by daniellemoorhead** [comment]
@luisramos0 there's an outstanding question directed at you from @Chrisyee22 from 9 days ago. Would be great if you could get back to him so we can get this moving again 😃

**Comment by luisramos0** [comment]
hey @Chrisyee22, I dont know why it's not working, maybe you are binding it to the controllers scope and that scope is not broad enough to be picked up on page navigation?

**Comment by sigmundpetersen** [comment]
Closing this PR and moving the connected issue to the backlog. Please reopen and move it forward if you start working on it again @Chrisyee22

**Pull request closed without merging**
