### PR TITLE
Fixes some errors due to Product refactor

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

Due to failing check for #12641 , I found that #12594 raised some errors.
It is in relation with the Product refactor.
Following the advice from @sigmundpetersen , this is a Fix. I do not know if it is complete but I hope it can help the core devs team.

I basically replaced product with variant.
There is a pending I added in spec, because there are some data that are still retrieved from product from line_item.
In the `lib/reporting/reports/orders_and_distributors/base.rb` file:
https://github.com/openfoodfoundation/openfoodnetwork/blob/2c41d065df27cfdad1d3028def28359c10d3dedc/lib/reporting/reports/orders_and_distributors/base.rb#L15-L17

So I guess there would be some remaining tidying up to do.

I let this PR in open status, even if it is intended to be completed.

#### What should we test?
Nothing, the tests should all pass.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [X] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by cyrillefr** [comment]
Hello @sigmundpetersen , would it be possible to relaunch the checks ?
The 2 failing ones are ok locally ...

**Comment by sigmundpetersen** [comment]
I'm afraid the failure is consistent on the CI @cyrillefr

**Review by mkllnk — COMMENTED** [review]
Thank you for starting this. I'll have a look at the pending work now.

**Comment by mkllnk** [comment]
I continued your work in a different pull request:

* https://github.com/openfoodfoundation/openfoodnetwork/pull/12644

Your commit had some changes that I didn't want to include. So I started new commits inspired by your work. Thank you.

**Pull request closed without merging**
