### PR TITLE
Feature into system specs

### LINKED ISSUE #7929: Replace "feature specs" for "system tests"
### What we should change and why (this is tech debt)

**Project steps**
~~- Create OFN's first "system test" under a new directory (/spec/system, I guess), with a simple browser-based test that passes.~~ - done
~~- Add the Ferrum-Cuprite driver to the stack. Configure all tests of the "system test" type to run on Ferrum-Cuprite instead of Selenium (but leave the old feature spec setup as it is, with Selenium).~~ - done
- slowly transition towards Ferrum-Cuprite, replacing old feature specs (Selenium) 

**Guidelines**

https://ofn-user-guide.gitbook.io/ofn-testing-handbook/automated-testing-handbook/system-specs

**Background**
https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing#modern-system-tests-with-cuprite
https://guides.rubyonrails.org/testing.html#system-testing

### Context

This came up here:
https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1626093858077600?thread_ts=1626075838.077100&cid=C02TZ6X00

### Impact and timeline

This impacts all feature specs, build performance and its reliability.

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #7929.
A second go at this, after messing up #8029 :see_no_evil: 

This PR changes feature specs into system specs.

The idea is to:
- first, to make a copy of all existing feature specs (in `spec/features`) into the `spec/system` directory
- then, step-wise, make each spec pass locally, making separate commits for these changes
- finally, deleting the spec/features directory

#### What should we test?

Green build.

#### Release notes

Changes feature specs into system specs

Changelog Category: Technical changes

#### Documentation updates

Updating the Testing Guide and the Wiki.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
I realize now, that as these files are copies from the feature specs, they don't really retain history... This means, that during the life on this branch, the changes made on feature specs could be lost. I'm not sure how to solve this :thinking: 

Also, it would be great to just run all system specs on our CI, and check that the fixed specs actually work :-) Something to chat about. I'll move to code review; grateful for feedback :pray:

**Comment by andrewpbrett** [comment]
> This means, that during the life on this branch, the changes made on feature specs could be lost.

For review purposes, we can still see the changes that were made by looking at individual commits after the first big one that moves the files - is that what you mean? 

It also looks like there's a few specs failing because they use the `background` keyword.

**Review by mkllnk — COMMENTED** [review]
Wow! :heart_eyes: 

This is great work. You could probably structure the pull request a bit differently. My approach would have been:

1. Apply backwards compatible changes like renaming `feature` to `describe` and `scenario` to `it`. That work can be done on the feature specs and that could be merged straight away. The feature branch is smaller then.
2. If you move the specs instead of copying them then Git should be clever enough to track the history. It also makes your intent clearer that those specs are replaced, not duplicated.
3. I would have moved specs in chunks instead of all in one go. That helps to get some easy work done and maybe merged before solving the hard bits. But doing it all in one go is good, too. Especially since you did the work already.

Is there a reason why you haven't deleted the feature specs yet? Is this still work in progress?

**Comment by filipefurtad0** [comment]
That's really very useful feedback, thanks @mkllnk .

I'm tempted to start over yet again and follow those steps, because even if this PR would be all greens - it isn't, there are still a few places to work on as @andrewpbrett mentions - because a copy was made (instead of moving) the most recent changes and add-ons on the `/features` spec directory  will not be included on the `/system` directory... This was kind of concernign me, as specs are constantly updated...

Before starting off again: if I delete the `/features` directory maybe git will pick it up as a `move` and not `copy`? I'll give it a quick try.

**Comment by mkllnk** [comment]
> there are still a few places to work on

Okay, so it would be a good strategy to extract little changes that can be merged before the rest is done. That will avoid merge conflicts as well.

> because a copy was made (instead of moving) the most recent changes and add-ons on the /features spec directory will not be included on the /system directory...

If you delete a feature spec on your branch and it's changed in master then Git will alert you to a merge conflict.

> if I delete the /features directory maybe git will pick it up as a move and not copy?

Yes, Git picked it up as move instead of copy. But you see that only if you look at all changes at once. To prevent any confusion, you can do it in the same commit. But as discussed earlier, it may be worth selecting chunks of feature specs, move them, fix and then open a pull request with just that work when all tests pass. Merging to master often prevents a lot of extra work due to conflicts. And it may also be clearer which spec files need certain changes to the helpers and so on. So if I wonder one day why there is a certain line in the system spec helper, I can go through the Git history and find the commit which migrated the spec that needed that line. Just as an example. I regular do this kind of research to understand the code to estimate the impact of my changes.

**Comment by filipefurtad0** [comment]
Yet another try but I think this one should work: I'll close this PR and branch here and move the discussion into #8179.

Many thanks again @mkllnk for the precious feedback!

**Pull request closed without merging**
