### PR TITLE
Admin, Reports,  Order Cycle Customer Totals: Remove paid?, order cycle and payment method columns from summary row

### LINKED ISSUE #9319: Order Cycle Customer Totals report: Summary row populated when it shouldn't be
## Description

During testing of #9246 it was discovered that also in the Order Cycle Customer Totals report there are some columns populated in the summary row, where it doesn't make sense. The following columns should not be populated:
- Hub
- Customer
- Paid?
- Order cycle
- Payment method
- Order number
- Date

## Expected Behavior

The listed columns should be blank in the summary row.

## Actual Behaviour

The listed columns are populated in the summary row.

## Steps to Reproduce

1. Make sure you have placed at least one order
2. Run the Order Cycle Customer Totals report

## Animated Gif/Screenshot

image

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [ec338bca9cd17673c6db9a74a3265d6c9dc0ed4e](https://github.com/openfoodfoundation/openfoodnetwork/commit/ec338bca9cd17673c6db9a74a3265d6c9dc0ed4e)
* Browser name and version: 101.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

## Possible Fix

See #9246 as a reference.

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9319
Capture d’écran 2022-07-11 à 15 22 37

#### What should we test?

- As an admin, on `Order Cycle Customer Totals` report, check that `paid?`, `order cycle` and `payment method` columns are empty for the summary row

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by RachL** [comment]
I'm sorry guys but I'm really unsure we don't want to populate the total line with info. Let's say I want to see total lines for a particular order cycle on a spreadsheet, with this PR I would be able to sort the column anymore. Same for the paid column?

I would actually be in favor of having values in the total lines as much as we can?

@lin-d-hop what do you think?

**Comment by lin-d-hop** [comment]
I agree with you @RachL. People use these reports in all kinds of ways in automations and having all the information in the totals rows is really helpful.
Besides, we can't make more changes to report downloads at the moment. Little changes cause BIG problems to so many people's integrations and support teams are still in recovery from the big reports release.

I'm unclear on a few things:

1. Which export types would this report impact? From the PR I can see CSVs should be impacted as the spec was updated. Probably worth noting that we can't just make changes to reports downloads. These can result in some of the angriest support emails you'll find as hub's entire processes break on release.

2. @drummer83 is there a specific reason you created the issue that maybe I did not see? Or a slack discussion in which it was discussed that I've missed? It would be helpful to know what inspired this proposal, if I missed something :)

**Comment by lin-d-hop** [comment]
Note #9246 was removing false information (as the summary row could not include all the shipping methods used it included the wrong one). In this case the information is correct information.

**Comment by drummer83** [comment]
> Note #9246 was removing false information (as the summary row could not include all the shipping methods used it included the wrong one). In this case the information is correct information.

I don't agree 100 %, @lin-d-hop. In the original issue #9228 you can see that the provided screenshot of the 'actual behaviour' has the same shipping method everywhere. And the summary row also shows that shipping method. This was indicated as being wrong by the author and was fixed by #9246. Since #9246 the shipping method in the summary row will ALWAYS be empty. Here is the image again:
grafik

During testing I saw that the Order Cycle Customer Totals is the only Order Cycle report populating the summary row in that way. So it seemed like an error to me. I mentioned this in this [comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/9319#issuecomment-1158825024).
> @RachL Oooops, sorry about your integrations! 😃 No, I didn't check. I just thought "calculating" totals of dates and order numbers doesn't make any sense. And I saw that in the other Order Cycle reports we only have totals where it actually does make sense. But no problem, feel free to close! 👍

**Comment by lin-d-hop** [comment]
Isn't this related to the type of report?
- Report by Supplier cannot have a shipping/payment details because when a report is by supplier the information is split across multiple orders (and hence multiple shipping/payment methods unless the hub only has one)
- Report by Customer should have a shipping/payment details because this will be grouping over a single order which will have those details.

**Comment by drummer83** [comment]
Not sure I understand what you mean. The Order Cycle Distributor Totals **by Supplier** also has shipping method listed: 
grafik

**Review by mkllnk — COMMENTED** [review]
Hm, this is in code review. Technically I would approve this but product seems to have a different idea. Should this be closed or put In Dev?

**Comment by jibees** [comment]
Not sure to understand here on how to handle this one. 
Should we close this PR? 

help @openfoodfoundation/train-drivers-product-owners :p

**Comment by RachL** [comment]
Yes let's close the PR and move the issue to wishlist so we can write it properly. Ok for everyone?

**Pull request closed without merging**
