### PR TITLE
Rails/LexicallyScopedActionFilter

### LINKED ISSUE #11482: Fix Rubocop Rails issues

### PR DESCRIPTION
**Pull request by Nwabor**
#### What? Why?

- Part of #11482 

#### What should we test?
Test is not required

- Visit ... page.
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] Technical changes only

The title of the pull request will be included in the release notes.

#### Dependencies
Does not depend on other PR

#### Documentation updates
No documentation needed

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
Hey @Nwabor 👋 There are some conflicts that need to be resolved.
Can you have a look?

**Comment by sigmundpetersen** [comment]
Hi @Nwabor , how are you 👋 
Would you like to continue on this one?
Don't hesitate to ask if you have any questions or blockers 👍

**Comment by Nwabor** [comment]
> Hi @Nwabor , how are you 👋 Would you like to continue on this one? Don't hesitate to ask if you have any questions or blockers 👍

Hi sigmundpetersen, I am good what about you? some tests are failing I have tried to resolve them, but I have not been successful.

**Comment by sigmundpetersen** [comment]
That's fine @Nwabor , we can ask some devs for help.
@chahmedejaz @dacook or anyone else, any advice here?

**Comment by Nwabor** [comment]
> That's fine @Nwabor , we can ask some devs for help. @chahmedejaz @dacook or anyone else, any advice here?

Thank you. That will be helpful.

**Comment by chahmedejaz** [comment]
Hi @Nwabor - Can you please rebase your branch with the latest master and force push? Hopefully, most of them will get fixed; if some remain, we can look into those, no worries. 👍

**Comment by Nwabor** [comment]
> Hi @Nwabor - Can you please rebase your branch with the latest master and force push? Hopefully, most of them will get fixed; if some remain, we can look into those, no worries. 👍

Thank you @chahmedejaz - I will do just that.

**Comment by dacook** [comment]
I'm afraid there are conflicts still. 
I guess a lot is changing at the moment, so perhaps it would be worth splitting into smaller PRs to minimise conflicts.
You could submit the PR with only the files that have no conflicts first, then you can open a second PR with the remaining fixes.

**Pull request closed without merging**
