### PR TITLE
Fix:- Order cycle creation: Needless warning and lost data when leaving and saving

### LINKED ISSUE #9874: Order cycle creation: Needless warning and lost data when leaving and saving
## Description

During complex order cycle creation there are warnings when leaving the page without saving the data. However this isn't applied on all steps and sometimes the warning is shown even when no data was changed. Also the 'save' buttons should only be active when data was changed and needs to be saved.

- Leaving step 3 of complex order cycle asks to confirm to leave the page even when no data was changed.
- Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).
- The buttons ‘save’ and ‘save and back to list’ should only be active when data was changed.

## Expected Behavior

- Leaving any step of order cycle creation should NOT warn the user if NO data has been changed.
- Leaving any step of order cycle creation SHOULD warn the user IF data has been changed.
- The buttons ‘save’ and ‘save and back to list’ should only be active if data was changed.

## Actual Behaviour

- Leaving step 3 of complex order cycle asks to confirm to leave the page even when no data was changed.
- Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).
- The buttons ‘save’ and ‘save and back to list’ are always active on step 3 and 4.

## Steps to Reproduce

1. Create an order cycle for a hub (sells = any)
2. Proceed through all steps and save
3. Edit the order cycle
4. Proceed to step 3, don't change anything and the click on step 1, 2 or 4 --> the warning will be shown
5. Proceed to step 4, change data and then click on step 1, 2 or 3 or any other page --> there will be no warning, data will be lost
6. Observe the buttons 'save' and 'save and back to list' while editing an order cycle

## Animated Gif/Screenshot

Peek 2022-10-25 15-45

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by krishnasingh001**
#### What? Why?

Closes #9874 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by krishnasingh001** [comment]
Hi @drummer83 While working on issue #9874, I am able to fix the first issue related to `Leaving step 3`. But need some help from you to fix the 2nd issue.
> Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).

In the order cycle, we have 4 steps. For the first 3, the logic or code is written in **Angular**.  But the code related to the **4. CHECKOUT OPTIONS** is written by using Stimulus. Since we already have the code in the angular to fix the issue. Please refer to [select_all_controller.js](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/webpacker/controllers/select_all_controller.js).

Can you help me to solve point 2 issue?

**Comment by drummer83** [comment]
Hi @krishnasingh001,
Thanks for working on this!

I am not a developer myself, so I can't really help you with coding.

What do you think about the following?
- Create a pull request with your solution for the issue around step 3.
- Prepare a second pull request for the issues around step 4. I will help you to get some feedback from our developers there.

Does that sound good for you?

**Comment by krishnasingh001** [comment]
> Hi @krishnasingh001, Thanks for working on this!
> 
> I am not a developer myself, so I can't really help you with coding.
> 
> What do you think about the following?
> 
> * Create a pull request with your solution for the issue around step 3.
> * Prepare a second pull request for the issues around step 4. I will help you to get some feedback from our developers there.
> 
> Does that sound good for you?
Yes @drummer83 Sounds good. Thanks

**Comment by RachL** [comment]
HI @krishnasingh001 Hope this message finds you well. I'm just checking in: are you still working or planning to work on that PR? Thanks :)

**Comment by krishnasingh001** [comment]
Hi @RachL I tried to reproduce this issue locally. But looks like this is working fine. I think the issue is resolved now. Closing this PR. Thanks

**Pull request closed without merging**
