### PR TITLE
Allow negative stock levels for on-demand products

### PR DESCRIPTION
**Pull request by mkllnk**
:information_source: **Funded Feature. Please track ALL ASSOCIATED WORK under the associated tracking code https://github.com/openfoodfoundation/openfoodnetwork/issues/11678 DFC Orders**

#### What? Why?

- Part of #11678

We want to place backorders on a wholesaler's platform when we run out of stock in our local OFN store. This complicates the stock logic though. To allow customers to order more than we have in stock, we set the products to on demand. And we change the logic to still count stock, allowing it to go negative, so that we know how much stock we need to order from the wholesaler.

This PR just prepares the change in OFN stock logic without adding the backordering logic. While it seems to be a fairly easy change, there's potential for subtle bugs around products going out of stock. We may have assumptions in our code that I'm not aware of.

#### What should we test?

- Test the checkout of stock controlled items and on-demand items.
- Test the order creation as admin of those items.
- Test with producer products and with inventory products (using variant overrides).
- When a stock controlled product goes out of stock during checkout, we still need to raise an error.
- When an on-demand product goes out of stock, we should still be able to check out and it should not be marked as out of stock.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good

**Review by dacook — APPROVED** [review]
Nice, good idea to do this in a separate PR first.

**Comment by filipefurtad0** [comment]
Hey again @mkllnk ,

Tested the indicated scenarios:

- checkout of stock controlled items and on-demand items - OK. Editing the order (as a customer) by removing on-hand items returned these to the initial on-hand value. 
- order creation as admin of those items. - OK
- with producer products and with inventory products (using variant overrides). - OK


image


Verified that:

- When a stock controlled product goes out of stock during checkout, we still need to raise an error.

image

- When an on-demand product goes out of stock, we should still be able to check out and it should not be marked as out of stock.

I'm a bit unsure about this one, I'm probably misunderstanding this. How do we get an on-demand product out of stock? I did checkout on-demand variants, with no change of behavior, so I think we should be good. Please let me know if there is anything else you feel I should cover, on this specific scenario. 

Other than that, this looks good to me. Found nothing unusual. Please feel free to merge.

**Comment by mkllnk** [comment]
Great, that's all good. It's a bit confusing but on-demand products still have a stock level. It's ignored during checkout and the shop doesn't show any stock levels, of course. But your screenshots look like you had a product with 0 stock that was set to on demand. That's what I meant with "out of stock" even though it's on demand. And the checkout still worked. :+1:

**Pull request merged**
