### PR TITLE
Redirect to shopfront when OC closes during checkout

### LINKED ISSUE #9583: (silent?) Checkout error 404 when order cycle closes during checkout
## Description

If the OC closes during checkout the user will see an generic error (see Animated Gif/Screenshot section).

I believe we're not getting notified from these errors, as 404s don't trigger the Bugsnag notification flow.

We do get a warning though, each time the OC closes on checkout:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61f91350e0348e00089f160f?filters[event.since]=30d&filters[error.status]=open

## Expected Behavior

If the OC closes during checkout, then:
The customer should be redirected to the (closed) shopfront and the appropriate message should be displayed:

image

## Actual Behaviour

If the OC closes during checkout, then:
The customer is not getting redirected to the shopfront page but rather seeing generic flash messages.

## Steps to Reproduce

As a customer
1. Visit the shopfront, add some items to the cart and proceed to checkout

As admin
2. Close the order cycle

As the customer
3. Click Checkout
4. See the generic error

## Animated Gif/Screenshot

**Cash**
image

**Stripe**
image

## Workaround

Navigate back to the cart and or shopfront page.

## Severity

~~I think this would be an S3; surely a regression.~~
Upgrading to S2 - likely to impact customer support. Feel free to downgrade if disagreed.

## Your Environment

* Version used: observed on v4.2.9 and before (checked for v4.2.8). 
* Browser name and version: Firefox 103
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by binarygit**
#### What? Why?

Closes #9583 

#### What should we test?

- Login as user
- Create an order in an order cycle
- Get to the checkout screen
- As the enterprise owner, close the order cycle
- As the user, click on checkout
- Ascertain that you are redirected to the shop front
- Ascertain that there's a flash message informing you that the OC just closed

ezgif com-gif-maker(2)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by binarygit** [comment]
The test is passing locally:
passing

**Comment by sigmundpetersen** [comment]
I think it's flaky.
I'll try re-running the build.

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]
👌 
Thanks!

**Comment by drummer83** [comment]
Hi @binarygit,
Thanks for yet another pull request. I have tested this scenario for **different payment methods** (because different behavior was observed for Stripe in the original issue #9583) and with **different amount of order cycles open** (from 0 to 2 open ones remaining after closing the one of interest). I have also checked **Legacy Checkout** as well as **Split Checkout**.

## Results for **Legacy Checkout**:

| Situation | Before staging the PR | After staging the PR |
|---|---|---|
| **Cash**: Closing and **no** order cycle open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to closed shopfront; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Cash**: Closing and **one** order cycle open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to shopfront with remaining order cycle; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Cash**: Closing and **two** order cycles open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to shopfront with remaining order cycles; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Paypal**: Closing and **no** order cycle open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to closed shopfront; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Paypal**: Closing and **one** order cycle open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to shopfront with remaining order cycle; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Paypal**: Closing and **two** order cycles open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to shopfront with remaining order cycles; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Stripe**: Closing and **no** order cycle open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to closed shopfront; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Stripe**: Closing and **one** order cycle open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to shopfront with remaining order cycle; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |
| **Stripe**: Closing and **two** order cycles open | No redirection; Error: The checkout failed. Please let us know so that we can process your order. | Redirecting to shopfront with remaining order cycles; Warning: The order cycle you've selected has just closed. Please try again! :heavy_check_mark: |

**Before staging:**
image

**After staging (example of closed shopfront):**
image

## Results for **Split Checkout**:
| Situation | Reaction after staging |
|---|---|
| Order cycle closes while on page '1 - Your details' | First click: nothing happens (HTTP 303) :x: <br> Second click: Redirection to closed shopfront :heavy_check_mark: |
| Order cycle closes while on page '2 - Payment method' | First click: nothing happens (HTTP 303) :x: <br> Second click: Redirection to closed shopfront :heavy_check_mark: |
| Order cycle closes while on page '3 - Order summary' | First click: nothing happens (HTTP 303) :x: <br> Second click: Redirection to closed shopfront :heavy_check_mark: |

This looks like a regression to me because I did not see this before staging.

## Summary
As you can see:
- for Legacy Checkout we are fine.
- for Split Checkout we have a regression.

I will leave for @openfoodfoundation/train-drivers-product-owners to decide if we move forward and create a separate issue for Split Checkout or if we fix this first.

I have the feeling that this PR is trying to fix something on Legacy Checkout only, because the redirection seems to work fine on Split Checkout before this PR already. Since we don't want to fix issues on Legacy Checkout anymore we might just want to close the original issue without fixing and without investing more time:question: If we decide to do so, we should test the redirections on Split Checkout without this PR deeper - I did this very quickly only.

Thanks! Adding feedback-needed label.

**Comment by RachL** [comment]
Let's move forward with this PR and open another issue for split checkout :+1:

**Pull request merged**
