### PR TITLE
Update things related to some package manager influencing setup process

### LINKED ISSUE #7521: Setup script fails for new devs
## Description

A couple of potential contributors have hit errors when running the setup script under `script/setup` (as directed to in the wiki). the script checks for a really outdated version of Node (5.12.0). We actually use 14.x.x in production and in CI, so this check is a bit ridiculous. The setup script fails if that exact version is not present.

We use yarn now, which should work fine with any modern version of Node.

We should just do a basic check that node is installed, and continue if it is. Also the wiki might need an update.

## Expected Behavior

New devs can run the setup script as per the wiki.

## Actual Behaviour

Setup script fails.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by psychoslave**
#### What? Why?

Fixes #7521

The version specified in the `.node-version` file is no longer supported, and trying to install it through `nodenv` or the like will not allow to run the project on a bright new system. 

This patch:
- set node version to the last LST 14.16.1
- follows the recommendations of  @Matt-Yorkley to remove the node test in `./script/setup`. 
- replaces npm with yarn
- remove everything related to newrelic

#### What should we test?

Anything that allows to make sure no dependencies require a version

#### Release notes

Fix hindrances on new setup related to Node version

Changelog Category: Technical changes

#### Documentation updates

Already done:
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup:-Ubuntu

Possibly might also require some edits:
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Debian
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Fedora
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-OS-X

### CODE REVIEW

**Comment by psychoslave** [comment]
Github specific shortcut syntax to issues still seem to be a mystery for me :laughing:

**Comment by viktorsmari** [comment]
@psychoslave are you using `nodenv` or another tool like `nvm`?
I was thinking if https://github.com/nvm-sh/nvm has become the standard with its `.nvmrc` file.

Last update to the `nodenv` repo was July 2020 and it has 1.5k stars
Last update to the `nvm` repo 5 days ago and it has 48k stars

We might also be able to symlink these files, but I thought the `.nvmrc` file was the 'unofficial' winner :smile_cat:

**Comment by psychoslave** [comment]
Hello @viktorsmari 

I did installed `nodenv` as it was recommended in the documentation for dealing with dependencies on Ubuntu. That said @Matt-Yorkley reported that using the official Ubuntu Node package is enough.

The project currently doesn't have a `.nvmrc`, but it can be added, this is all up to the community. For a matter of simplicity, I would recommend to avoid to add multiple concurrent solution in the repository. Maybe `nodenv` was retained because its sub-commands are aligned with `rbenv` which is also highlighted in the documentation. 

If some consensus arise in OFN community that it would be great to move to `nvm` as a recommanded tool, then I would suggest to remove references to `nodenv` in the main path of the documentation and push that instead.

In any case, it's always possible to add specific documentation in a peripheral wiki page/section explaining how to set up a symlink that won't be tracked by git so no one is bothered with all possible preferences.

Anyway, as interesting as the topic might be, I think it should be treated in its own issue and pull request. This one doesn't intend to address something that it is not directly pertaining to the #7578.

**Comment by viktorsmari** [comment]
I agree,  fewer files are better and symlinking might be an overcomplication :smile: 

Since this PR is removing the only reference to `nodenv` in the repo, maybe the `.node-version` file is not needed at all, what does @jibees say, do you use any particular Node version manager?

This could be part of another PR / discussion, I just thought it was related.

We could also remove references to `nodenv` in the wiki, I found them in 2 places:
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Ubuntu#step-4-installing-node
- https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Fedora#install-node-using-nodenv

Maybe detailing in the wiki how each version manager is installed on multiple operating systems should not be the responsibility of OFN? These things change and every time I install `rbenv` I personally would follow the official documentation of `rbenv`.

**Review by Matt-Yorkley — APPROVED** [review]
Thanks!

**Comment by andrewpbrett** [comment]
> Github specific shortcut syntax to issues still seem to be a mystery for me 😆

I fixed that, I think the problem was you had the extra `[` and `]` around the issue number. You just need #1234, for example.

**Review by andrewpbrett — APPROVED** [review]

**Pull request merged**
