### PR TITLE
Fix Rbenv and ruby-build installation to get Ruby 2.5.9

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

This newer Ruby version can't be found on that ruby-build's branch that we were installing. The `docker-compose build` command works again.

:warning: we need https://github.com/openfoodfoundation/openfoodnetwork/pull/7698 first.

#### What should we test?

Nothing.

#### Release notes

Fix Ruby 2.5.9 installation in docker container.
Changelog Category: Technical changes

### CODE REVIEW

**Comment by sauloperez** [comment]
:see_no_evil: this now fails with:

```
❯ docker-compose run --rm web bundle exec rake db:setup
Starting openfoodnetwork_db_1 ... done
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
rake aborted!
LoadError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /bundles/gems/eventmachine-1.2.7/lib/rubyeventmachine.so
/bundles/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/bundles/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/bundles/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/bundles/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/bundles/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
/usr/src/app/config/application.rb:11:in `<top (required)>'
/usr/src/app/Rakefile:7:in `require_relative'
/usr/src/app/Rakefile:7:in `<top (required)>'
/bundles/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/src/rbenv/versions/2.5.9/bin/bundle:23:in `load'
/usr/local/src/rbenv/versions/2.5.9/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by sauloperez** [comment]
it seems that fixed it. @Matt-Yorkley chances are that this is happening in production as well.

**Comment by sauloperez** [comment]
The last commit solved all the issues. I can `db:setup`, `db:test:prepare`, `bundle exec rspec` and `docker-compose up` :sparkles:

**Comment by sauloperez** [comment]
After #7698 libssl is not needed by eventmachine but it turns out Ruby still needs it :shrug: Adding it back fixes

```
Step 12/19 : RUN git clone --depth 1 https://github.com/rbenv/rbenv.git ${RBENV_ROOT} &&     git clone --depth 1 https://github.com/rbenv/ruby-build.git ${RBENV_ROOT}/plugins/ruby-build &&     echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh &&     RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install $(cat .ruby-version) &&     rbenv global $(cat .ruby-version) &&     gem install bundler --version=1.17.3
 ---> Running in b509f158cb03Cloning into '/usr/local/src/rbenv'...Cloning into '/usr/local/src/rbenv/plugins/ruby-build'...
Downloading ruby-2.5.9.tar.bz2...-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.9.tar.bz2Installing ruby-2.5.9...
WARNING: ruby-2.5.9 is past its end of life and is now unsupported.It no longer receives bug fixes or critical security updates.
BUILD FAILED (Ubuntu 20.04 using ruby-build 20210526)
Inspect or clean up the working tree at /tmp/ruby-build.20210527160920.42.bZNqvyResults logged to /tmp/ruby-build.20210527160920.42.log
Last 10 log lines:ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libssl-dev` to fetch missing dependencies.Configure options used:
  --prefix=/usr/local/src/rbenv/versions/2.5.9  --enable-shared  --disable-install-doc
  --with-jemalloc  LDFLAGS=-L/usr/local/src/rbenv/versions/2.5.9/lib   CPPFLAGS=-I/usr/local/src/rbenv/versions/2.5.9/include 
```

**Review by Matt-Yorkley — APPROVED** [review]

**Review by andrewpbrett — APPROVED** [review]

**Pull request merged**
