### PR TITLE
Reduce unnecessary avalanches of Redis queries

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Related to issue https://github.com/openfoodfoundation/openfoodnetwork/issues/11752, comment: https://github.com/openfoodfoundation/openfoodnetwork/issues/11752#issuecomment-2015529956

Wraps commonly-repeated calls to `Spree::Config` in a `CurrentAttributes` object to reduce unnecessary cache reads. Docs: https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

These config values are relatively static but in some cases they can be called hundreds or even thousands of times in the same request (like rendering a report or a large list of line_items in BOM). These config values will now only get fetched from Redis/Postgres _once at most_ per request/job and be memoized per request cycle (but the values can still change between requests).

Background: `Spree::Config` inherits form `Spree::Preferences` which is kind of a hybrid data store that simultaneously uses the cache (Redis)  and the database (Postgres) for writes, but for reads it tries the cache first and only hits the database as a fallback. It's an interesting mechanism that's quite useful in some cases (combining the long-term storage of the database with the fast reads of the cache), but there's a few places where it can cause issues, namely; if it's used in places where a value can be called for each row in a query and the number of queried objects are large. In that scenario it causes a kind of **N+1 query** problem but against Redis instead of Postgres, which can be problematic in extreme cases (reports). The result is an avalanche of requests that are all fetching the same value repeatedly.

#### What should we test?
Update an instance config variable (Admin > Configuration > General Settings) and check that the updates apply correctly. Any of:
* Currency Settings
* Number Localization Settings
* Available Units

Also, see if you can replicate this before/after:
* https://github.com/openfoodfoundation/openfoodnetwork/issues/11752

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — COMMENTED** [review]
Great find, and thanks for building a solution for this!
This doesn't seem to cover [all Spree config variables](/Users/dcook/projects/openfoodnetwork/app/models/spree/app_configuration.rb), although I guess these are the main offenders.
I assume it would be a logical progression to include them all as a next step?

I've re-run the failing spec, and it succeeds. Hopefully that was a rare flaky result, but I'll re-run one more time just in case.

I don't quite follow the CurrentAttributes implementation, but am satisfied that it works :)

Is there anything else that's needed before we should progress this PR?

**Comment by dacook** [comment]
(added some testing notes)

**Comment by dacook** [comment]
We tested this on au_staging, loading a page of 100 products (and a lot of variants). 
You can see the first two humps, before deploying this PR. At one point it reaches nearly 60 commands per second.

After deploying the PR, doing the same action, it barely registers on the graph.

Screenshot 2024-03-25 at 11 20 37 am

**Comment by rioug** [comment]
I am wondering if we should be fixing the underlying `Spree::Config` , it does seem to be a sharp knife ( to use rails parlance :D). But from what I can see it might not be that easy, it seems to rely on a bunch of meta programming.

**Review by rioug — APPROVED** [review]
Looks good :+1:  TIL about `ActiveSupport::CurrentAttributes`

**Review by dacook — APPROVED** [review]

**Comment by dacook** [comment]
FYI @mkllnk

**Review by mkllnk — APPROVED** [review]
Nice, thank you!

This is a great little workaround to boost performance.

I also think that we should look at the current Spree Config and if we can leverage something there. Basically, our source of truth is the database but we also cache in Redis for a while and now in memory as well. It would be good to make that more explicit.

Before we apply this to everything, we have to check a couple of things:

* This implementation assumes that all stored values are not `nil`. If we want to handle all values, we need to remember which variables are cached. It's not in the public API but we can simply access the `@attributes` hash of the singleton class.
* Do we have values that change during a request? Admin pages that edit the config, may need to call reset on this.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Thanks. I've tested:
| --- | - before staging (ms) | - after staging (ms)|
| ---- |----|----|
| BOM page |1067|956|
| products page (BUU) |423|390|
| customer packing report |1020|166|

The figures are a bit hard to reproduce, but these seem to represent the tendency. Also, I've rebased the PR before testing - somehow, staging was not completing - which makes hard to differentiate between the effect of this PR and #12307.

Also, and as you've suggested, I've tested whether the config changes took effect correctly:


- Currency Settings :heavy_check_mark: 
- Number Localization Settings (never too sure what this setting does...)
- Available Units :heavy_check_mark: 

This looks good to go and be tested in production.

Merging. Thanks!

**Comment by dacook** [comment]
I forgot to test before deployment 🤦 
After, on `au_prod`:

| --- | - details | page size | - load time (seconds) |
| ---- |----|----|----|
| BOM page |`GET /admin/orders` | default 15 per page|26|
| products page (BUU) | `Products#fetch` | 100 per page, page 1|7|
|  || 100 per page, page 3 (many variants)|7,34,76|
| customer packing report | `GET /admin/reports/packing/customer `||10, 3|
| | `POST /admin/reports/packing` / `ReportJob` |2024-02-27 - 2024-03-28 (435 PDF pages) | 74|

So not exactly super fantastic! 

But I found out why for the BUU products page at least; Rails is often downloading the image for each product:

```
I, [2024-03-26 23:28:40 #13860]  INFO -- :   S3 Storage (11715.9ms) Downloaded file from key: public/images/spree/products/8602/original/TamarindTree-Front_BBQ_Afghan_Spice.jpg
I, [2024-03-26 23:28:41 #13860]  INFO -- :   S3 Storage (452.6ms) Uploaded file to key: 7jj4vsk9f6bm5nrvscwr2dh9lqkq (checksum: FF7OPcmcyf1DEIj2nTZdtA==)
I, [2024-03-26 23:28:41 #13860]  INFO -- : [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 56ddfe48-f0f5-4a68-acb2-f5c6de9f3af9) to Sidekiq(default) with arguments: #<GlobalID:0x00007efe5bebe898 @uri=#<URI::GID gid://openfoodnet
work/ActiveStorage::Blob/82494>>
I, [2024-03-26 23:28:41 #13862]  INFO -- : [ActiveJob] [ActiveStorage::AnalyzeJob] [56ddfe48-f0f5-4a68-acb2-f5c6de9f3af9] Performing ActiveStorage::AnalyzeJob (Job ID: 56ddfe48-f0f5-4a68-acb2-f5c6de9f3af9) from Sidekiq(default) enqueued
 at 2024-03-26T23:28:41Z with arguments: #<GlobalID:0x00007f93b58cb8b0 @uri=#<URI::GID gid://openfoodnetwork/ActiveStorage::Blob/82494>>
I, [2024-03-26 23:28:41 #13860]  INFO -- : [2f1b85a7] 1/1 ProductsReflex#fetch -> document via Nothing Morph (dispatch_event)
```

**Comment by dacook** [comment]
# Prod test: fr_prod

Conveniently, fr_prod got disconnected and didn't get deployed yet. Logged in as super admin. 

DRAFT: waiting for deployment...

| --- | - details | page size | - before (seconds) | - after (seconds) |
| ---- |----|----|----|----|
| BOM page |`GET /admin/orders` | default 15 per page|51| |
| products page (BUU) | `Products#fetch` | 100 per page, page 1 (barely any images loaded)|12| |
| customer packing report | `GET /admin/reports/packing/customer `|initial load|29 | |
| | `POST /admin/reports/packing` / `ReportJob` | Boutiques: Au Local, 2024-02-27 - 2024-03-28 (243 PDF pages) |47| |


Interesting, the images don't work on the BUU products screen for this instance, probably due to different storage configuration (hence it loads quicker).

**Pull request merged**
