### PR TITLE
Remove unused js dependencies (jquery-migrate-1.0.0 and timeago) and bring some legacy browsers support dependencies from spree_backend

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Starts #4595

- We drop jquery-migrate-1.0.0 because we already have jquery-migrate-min through gemfile jquery-migrate-rails.
- We drop unused timeago (this was replaced by moment).
- We bring modernizr from spree_backend to keep compatibility with old browsers
- We bring from spree_backend the dependency css_browser_selector_dev that comes with some browser specific "hacks' as well as browswer specific css selectors that we use.

I thought of making modernizr a gem file dependency with modernizr-rails but this is all very old code and we could introduce problems with the versioning... copy pasting it from spree is far from ideal but much easier and safer.

#### What should we test?
This are all generic javascript dependencies already in the code through spree_backend, we just bringing the code.
Some are particularly related to old browsers and different browsers, so it's a very goood candidate to put through browserstack.
Otherwise we need to make a overall verification that the website looks good and works. 

#### Release notes
Changelog Category: Changed
Delete some unused dependencies and bring some dependencies from spree_backend that support older browsers.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hi @luisramos0,

Dropping a line to report that I had troubles staging this PR in Katuma, despite all checks passed. Any idea on the reason?

Cheers :-)

**Comment by luisramos0** [comment]
thanks @filipefurtad0 

in the deploy job:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/katuma-staging/deploys/209
you can open the red log tab and look for error messages. That's how we can see what's broken.

This is the error we have there:
`fatal: [staging.katuma.org]: FAILED! => {"changed": true, "cmd": ["bash", "-lc", "bundle exec rake assets:clean assets:precompile:primary RAILS_GROUPS=assets RAILS_ENV=staging"], "delta": "0:03:37.404438", "end": "2020-01-15 21:57:12.775623", "msg": "non-zero return code", "rc": 1, "start": "2020-01-15 21:53:35.371185", "stderr": "rm -rf /home/openfoodnetwork/apps/openfoodnetwork/current/public/assets\nrake aborted!\nSass::SyntaxError: **Undefined variable: \"$color-1**\".\n  (in /home/openfoodnetwork/apps/openfoodnetwork/current/app/assets/stylesheets/admin/hacks/ie.scss)\n/home/openfoodnetwork/apps/openfoodnetwork/current/app/assets/stylesheets/admin/hacks/ie.scss:50\`

It's a CSS bug, probably just an issue with the order the files are being loaded.
I'll have a look tomorrow :+1:

**Comment by filipefurtad0** [comment]
Good morning @Luisramos0,
Thanks! It's good to know that it's all in there. I'll keep my eye open for that box during depolyments :-)

**Comment by RachL** [comment]
@luisramos0 does this still belong to the testing column?

**Comment by filipefurtad0** [comment]
Hey @rachel,
Yes it does :-) Sorry for the delay. I'll pick it up now.

**Comment by sigmundpetersen** [comment]
Yes that's the correct procedure Filipe, thank you.

**Comment by luisramos0** [comment]
ok, I fixed the file path on the new import statements. it's looking good now 👍 
ready for testing

**Comment by luisramos0** [comment]
Hi @sigmundpetersen please do not remove the staging label even if you see something else is there. The label is marking that the staging server is taken.

**Comment by luisramos0** [comment]
I redeployed, ready for testing.

**Comment by filipefurtad0** [comment]
Thank you @luisramos0 !

One note though:
I won't be able to pick this up today so - from my side - the staging server can be used by someone else. I'll be back at testing tomorrow.

Cheers :-)

**Comment by luisramos0** [comment]
ok @filipefurtad0
someone else = me :-)

**Comment by filipefurtad0** [comment]
Hi @luisramos0 ,

Tested the behavihour of the website in Browserstack for the following combinations:

- WinXP, Firefox 43
- Windows 7, Chrome 72
- Chrome on iPhone 5S
- Windows 10, Firefox 68

And on my Ubuntu system the latest versions of Chrome and Firefox

Found no issues, so moving to ready to go!

>>>> Unrelated to this PR:
Tooltip does not appear under in the OC page, for the Edit Clone Delete OC butons. Verified in staging ES, FR and UK
https://staging.katuma.org/admin/order_cycles

**Comment by luisramos0** [comment]
all right, Filipe, thanks!

"tooltip does not appear under" ... I dont see what tooltip is missing.

**Comment by filipefurtad0** [comment]
Hey,

Sorry, I forgot to paste this.

In Order Cycles it looks like this:
image

Whereas under Products:
image

I am not sure, but should't it appear in OCs, like for all other menus?

**Comment by luisramos0** [comment]
:+1: that's a new issue. it's a good-first-issue.

**Comment by filipefurtad0** [comment]
Cool! I'll open one then :-)
Thank you!

**Pull request merged**
