### PR TITLE
Make orders not capturable if they have a payment pending authorization

### LINKED ISSUE #6909: Orders with payments requiring authorization are able to be captured
## Description

In the course of reviewing https://github.com/openfoodfoundation/openfoodnetwork/pull/6808, @filipefurtad0 noticed that it was possible for an admin to capture an order if there was a payment that required authorization from the customer. Trying to capture the payment while it's pending authorization causes the payment to fail. 

## Expected Behavior

An order that has a payment pending authorization should not be able to be captured.

## Actual Behaviour

The capture button appears and the shop owner can click it, resulting in a failed payment. 

## Steps to Reproduce

See https://github.com/openfoodfoundation/openfoodnetwork/pull/6808#issuecomment-780717414
1.
2.
3.
4.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

On the way ;-)

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6909

#### What should we test?

See issue

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by andrewpbrett** [comment]
@sauloperez this last commit queries specifically for the payments requiring auth; I'm not actually sure it's an improvement, since we still have to run the `pending_payments` query, and now have a separate query on top of it. What do you think?

**Comment by sauloperez** [comment]
Hey @andrewpbrett I found it easier to show what I meant in code. I hope you don't mind. Feel free to reorder the commits or squash them as you see fit.

I wanted to optimize even further by loading only the payments requiring authentication if any but that became a bit tricky as it was breaking other use cases and required more effort. Nevertheless the biggest perf. improvement is the eager loading.

**Comment by andrewpbrett** [comment]
This is great, thanks @sauloperez!

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

I guess we're good here, after triggering Bugsnag on the first run:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6036a8c2eaff73001706eed0?event_id=6036a8c20072e8010b750000&i=sk&m=nw

I decided to stage this in another staging server. After that:
1) placing an order in the BO
2) choosing stripe and inserting a 3d-auth card
3) with the order number, one can check back on how the order looks like and verify that the option to manually capture it is gone :+1: 

image

I tried this once again, and seemed to work, so looked like a one off error. No idea what happened before Andy. Can you get something out of that error?

This looks ready to go, unless you feel otherwise?

**Comment by andrewpbrett** [comment]
Thanks @filipefurtad0 ! The bugsnag is saying that the payment was already marked as failed somehow... I'm not sure how that would have happened though, other than what you were saying about there being a separate issue with redirects. I think it's good to go if it worked on FR.

**Pull request merged**
