### PR TITLE
Fix searching issue with full name on bulk order management

### LINKED ISSUE #10570: [BOM] User cannot use both `first-` AND `lastname` to filter orders
## Description

After #10460 the user cannot use both `first-` AND `lastname` together to search for orders; it can only search for `firstname` OR `lastname`.

(in a way, this is a regression, because before #10460 the user could search before for both names - however, only on the results shown per page)

## Expected Behavior

User should be able to search for both `first-` AND `lastname`

## Actual Behaviour

User cannot use both `first-` AND `lastname` together to search for orders

## Steps to Reproduce

1. Log in as admin of a hub with some complete orders and visit `/admin/orders/bulk_management`
2. On the search field, type the first and last name
3. Click "Filter Results"
4. Notice no results are found.

## Animated Gif/Screenshot

Using first name only - OK

image

Using first and lastname - No results:

image

## Workaround

Type in only first OR lastname.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: Should be in v4.2.39
* Browser name and version: Firefox 110.0.1
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by saunmanoj888**
#### What? Why?

- Closes #10570

As we  are using ransack gem for search functionality. Used advanced functionality `ransacker` to search with fullname

#### What should we test?
 - Log in as admin of a hub with some complete orders and visit /admin/orders/bulk_management
 - On the search field, type the first and last name
 - Click "Filter Results"
 - Proper results should appear.

#### Release notes

Changelog Category: User facing changes

#### Dependencies
None

### CODE REVIEW

**Comment by saunmanoj888** [comment]
hii @mkllnk @jibees

Could you please review this PR once you have the bandwidth.

Thanks!

**Review by mkllnk — APPROVED** [review]
Great solution, thank you!

**Review by jibees — APPROVED** [review]
👌 
Nice solution with a great PR and its associated description: thanks a lot!

Moving to `Test Ready`

**Comment by saunmanoj888** [comment]
I missed adding the `full_name` to the search query in `app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee` , I have modified my commit and also locally verified al the changes.
Thanks

**Comment by jibees** [comment]
> I missed adding the full_name to the search query in app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee , I have modified my commit and also locally verified all the changes.

Should we then add a system spec?

https://github.com/openfoodfoundation/openfoodnetwork/blob/cfb9bee084e6fd074d9dc88012b62d0d526976ec/spec/system/admin/orders_spec.rb#L156

**Review by mkllnk — APPROVED** [review]

**Pull request merged**
