### PR TITLE
Bug fixes to Order Cycle Reports

### PR DESCRIPTION
**Pull request by lin-d-hop**
Lots of stupid bugs found in here.... and now lots of little fixes.

Could we queue this up for a production merge please?

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
Hey @mkllnk can you have a look at this please :)

**Comment by oeoeaio** [comment]
Hi @lin-d-hop: Travis is reporting a few spec failures: three for the report and three for the calculator - could you resolve and ping me when you've got a green build in Travis?

**Comment by lin-d-hop** [comment]
Hi @oeoeaio 
Thanks for your continued patience. Note to self - slow down and think :-)

Checks are passing. Could you take another look at merging this one?

**Comment by daniellemoorhead** [comment]
@oeoeaio can you put this into the v1.6 milestone once you've pushed it to production, so that Sally knows to include it in the release notes. Ta :)

**Comment by oeoeaio** [comment]
Thanks @lin-d-hop!

This all looks pretty good - this stuff just came onto my radar in the last couple of weeks as we started doing deliveries at Baw Baw and I wanted to fix the bugs you've just fixed so that I could use the OCM report. :)

See my pull request #867 for some suggested changes - let me know what you think.

**Comment by oeoeaio** [comment]
Merged via `report_fixes_rebased`

**Pull request closed without merging**
