### PR TITLE
[BUU] Remove StimulusReflex from Image Edit

### LINKED ISSUE #12399: [BUU] Remove StimulusReflex from Image edit
We've decided to avoid using StimulusReflex, because it's not reliable. 
Probably the best alternative is to utilise Turbo, but please discuss with the team in [#backoffice-ui-uplift](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6) before starting.

### PR DESCRIPTION
**Pull request by dacook**
### What? Why?

Because I have had _quite enough_ of StimulusReflex.

- Closes #12399 

Although I have to admit I'm not entirely impressed by Turbo either.

#### 2. Also dynamically reload the image thumbnail after update, without a page reload
This was tricky, but I've now figured it out, yay! A couple of notes:
* Turbo Frame: It would require a bit of a weird setup with a few partials and I think it will be a bit hard for a newcomer to understand (defeating the purpose of using frames I think).
* Turbo Streams: I chose this method and managed to do most of what I needed. But would like to have a generic hook for showing loading indicator.

FYI for reviewers, there's already a [system spec](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/system/admin/products_v3/products_spec.rb#L927-L967), and it continues to Just Work :D

### What should we test?
`/admin/products` with `admin_Style_v3` enabled

For each of:
- product with an image. 
- product with the default image (ofn logo).
- With any url params like `?page=2` (note that you  might have to add these manually, due to https://github.com/openfoodfoundation/openfoodnetwork/issues/11640)

1. Click on the image, view the modal. Close the modal.
2. Click on the image again, upload a new one
3. Image should be updated, with success message. The page shouldn't reload or move, and the thumbnail updates quickly.

### CODE REVIEW

**Review by chahmedejaz — COMMENTED** [review]
Nicely done! 💪🏻

Just shared my thoughts on the Turbo stream thing here:
https://github.com/dacook/openfoodnetwork/commit/c6daf9546fa7375a60b0f26470a26169bc9facf7#r142268681

Please let me know what do you think about it. Thanks

**Review by mkllnk — APPROVED** [review]

**Comment by dacook** [comment]
Thanks to your prompt @chahmedejaz , I managed to get the dynamic update working! 🎉 

So I've added it to this PR and requesting re-review.

**Review by mkllnk — APPROVED** [review]
Yay!

**Review by chahmedejaz — APPROVED** [review]
Looks great! 🎉

**Comment by filipefurtad0** [comment]
Hey @dacook ,

Congrats for your work on this, it's looking great:

Took your tests:
- Click on the image, view the modal. Close the modal - OK
- Click on the image again, upload a new one - OK
- Image should be updated, with success message. The page shouldn't reload or move, and the thumbnail updates quickly. - OK

All good. These work perfectly.

Added this one as well:

- uploading a corrupt image. In this case we get a console error:

image

From a user perspective, this is a silent error. Basically, an update attempt does not work. I guess ideally, we'd get some sort of warning. I'll open an issue for this one.

Repeated the tests above, with the same results, when some params are given in the URL. For this, I've used `?category_id=&page=1&per_page=15&producer_id=&search_term=basket`, all good:

image

This is looking good. I'll merge now :tada:

**Pull request merged**
