### PR TITLE
Make split checkout buttons sticky on step 3

### LINKED ISSUE #8630: [Split checkout] Make the bottom buttons sticky
## Description
**- As a:** shopper
**- On page:** last checkout page step
**- I want to be able to do:** always see the bottom checkout button, no matter the device used

## Acceptance Criteria & Tests

Tests have to be performed both on mobile & desktop

_Scenario 1 as a guest checkout_

1. Add product to the cart
2. Proceed to checkout
3. When reaching the last step, no matter where I scroll on the page I see the checkout button at the bottom, overlapping the page content

_Scenario 2 as a loggedin user_

repeat scenario 1 but this time with a known shopper

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8630

#### What should we test?
The button should be sticked on step 3 (only) for both desktop and mobile view.

#### Release notes
Split Checkout: Make submit buttons on step 3 always visible

Changelog Category: User facing changes

### CODE REVIEW

**Comment by jibees** [comment]
Since #8631 is merged, rebased this one onto master.

**Comment by filipefurtad0** [comment]
I'll re-stage it then :+1:

**Comment by Matt-Yorkley** [comment]
Needs a rebase :+1:

What do you think about making the sticky part full-width on desktop / large devices?

**Comment by jibees** [comment]
> What do you think about making the sticky part full-width on desktop / large devices?

I've tested, without any success. It was awful. But maybe I didn't have a good inspiration!

**Review by mkllnk — APPROVED** [review]
This is beautiful! :sparkles:

**Comment by jibees** [comment]
> Hey @jibees , Some conflicts appeared here in the meantime 👍

rebased 👌

**Comment by filipefurtad0** [comment]
This failing spec seems relevant?
```

  1) As a consumer, I want to checkout my order as a logged in user summary step completing the checkout keeps the distributor selected for the current user after completion
     Failure/Error: click_on "Complete order"
     
     Capybara::ElementNotFound:
       Unable to find link or button "Complete order"

```
I'll re-trigger the build.

**Comment by jibees** [comment]
Yes it is, I'm on it, trying to resolve

**Comment by jibees** [comment]
Finally back in Code Review ! 
(after two rebase and conflicts ...)

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

The `complete order` sectrion now sticks to the final/confirmation screen:

Desktop Firefox
Peek 2022-01-31 19-04

Android Samsung 12/Chrome
Peek 2022-01-31 19-12

iPhone 12 / Safari
Peek 2022-01-31 19-18

I think this respects the acceptance criteria.

I had a look also on my device - in which the screen is not so big and also to check usability. I think it's ok, probably most people have larger screens - not sure. It looks more or less like this:

image

I'm moving to ready to go, but maybe @openfoodfoundation/train-drivers-product-owners would like to have a go at this one, before merging?

**Comment by RachL** [comment]
@filipefurtad0 we will have a look at the whole split checkout once we are ready to fully test it :+1: thanks for the ping thought.

**Pull request merged**
