### PR TITLE
Avoid opening tabs when navigating away from page

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Fixes a long-standing mini bug that creates little Javascript console errors. Also stops pointless requests being sent to the server.

Relevant Bugsnag: https://app.bugsnag.com/yaycode/open-food-network-js-australia/errors/6107571122c69d0007a7246c?event_id=61075711007f8a053b6d0000&i=sk&m=nw

#### What should we test?

On the shops page and producers page; the pull-down tabs for enterprises should work as before when clicking in the space in the tab, but when the link with the enterprise's name is clicked, the tab doesn't toggle open/closed at the same time as navigating away from the page.

#### Release notes

Improved toggling of tabs on shops and producers pages

Changelog Category: Technical changes

### CODE REVIEW

**Review by apricot12 — APPROVED** [review]
👍

**Review by jibees — APPROVED** [review]
Finally! 🎉

**Comment by RachL** [comment]
This is beautiful 😍 

I've tested both desktop and mobile and it really improves the experience!! (even if on mobile fat-fingering the name of the enterprise can sometimes do nothing - but that's a known problem).

I've spent too much time to find a new and decent gif recorder... Sorry team I can't add my before / after videos easily. You will have to trust me on this one.

Any tips on tools to do gifs easily is welcomed (my previous one is no longer supported :( ).

**Comment by apricot12** [comment]
> Any tips on tools to do gifs easily is welcomed (my previous one is no longer supported :( ).
If you're on linux, you can use Peek. It's simple and easy.

**Comment by RachL** [comment]
> I personally use gifox, limited to 10 seconds in free plan.

Thanks, I will search a bit more, but it does not seem to run on ubuntu :'(

**Comment by apricot12** [comment]
> > I personally use gifox, limited to 10 seconds in free plan.
> 
> Thanks, I will search a bit more, but it does not seem to run on ubuntu :'(

https://github.com/phw/peek

**Comment by RachL** [comment]
haha yes sorry @apricot12 it seems we are posting too fast for github :D I was answering to @jibees comment!

I will check out peek :)

**Comment by Matt-Yorkley** [comment]
+1 for Peek on Linux.

This is ready to merge, right?

**Comment by lin-d-hop** [comment]
+1 for peek. I use it on Ubuntu

**Pull request merged**
