### PR TITLE
changed string into translation key & add 'infinity' key

### LINKED ISSUE #3687: Missing translation : on demand
## Description
When you edit a product using the "variant" submenu. You can see that "on demand" is shown as an "infinity" stock. "infinity" is not translated yet.

## Steps to Reproduce
1. Log in as a producer or super admin or hub
2. Go on "products"
3. Click on the edit icon of one product
4. Click on the variant submenu
5. Here you can see the "infinity" stock

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v1.29
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Windows 10
* OFN Platform instance where you discovered the bug, and which version of the software they are using : French platform

### PR DESCRIPTION
**Pull request by kkoomin**
#### What? Why?

Closes #3687

Changed string "Infinity" into translation key and add 'infinity' key to get a translated string.

#### What should we test?

1. Log in as a producer or super admin or hub
2. Go on "products"
3. Click on the edit icon of one product
4. Click on the variant submenu
5. Click on the edit icon of the product
6. Check the string "infinity" translated (in "es" local page)

#### Release notes

Fixed translation on variants page

Changelog Category: Fixed

### CODE REVIEW

**Comment by CathyPearce** [comment]
The variant screen looks ok and this is good to merge
image

**Comment by sauloperez** [comment]
Congratulations @kkoomin :tada: ! This will make it to OFN v2.1.0 :muscle: !

**Comment by luisramos0** [comment]
@sauloperez we are merging these PRs to master, do you mean we should prepare v2.0.0 based on the last commit before the devhack?

**Comment by sauloperez** [comment]
Yeah, I just realized before merging and did it already :sunglasses: . I pointed the draft release to the 2-0-stable-master merge commit. Thanks for the heads-up!

**Comment by luisramos0** [comment]
great, thanks!!!

**Pull request merged**
