### PR TITLE
Add acts_as_taggable to Variant decorator

### PR DESCRIPTION
**Pull request by jeronimo**
PR to #1571

### CODE REVIEW

**Comment by oeoeaio** [comment]
My only problem with this is that it is fixing the symptom, not the cause. We don't actually want or need to tag variants...

**Comment by lin-d-hop** [comment]
@oeoeaio @jeronimo should we close this? 
Agree not worth just masking a symptom and currently its just not a priority to dig deeper (sorry @jeronimo, you could volunteer your time if you really wanted to suss out the root cause).

**Comment by jeronimo** [comment]
Sure, I am volunteering to jump into it the next time it will appear for me. Can we keeps this PR as a reminder for it?

**Comment by lin-d-hop** [comment]
CLosing as we haven't heard from @jeronimo recently. If you reappear mate then please do reopen :-D

**Pull request closed without merging**
