### PR TITLE
Adding i18n keys on Admin side (Rails views)

### PR DESCRIPTION
**Pull request by pacodelaluna**
I couldn't run the tests locally yet, but I have tested the views and it is working good.
French translations are not completed yet but I have really focus on i18n keys here.
Please tell me if any issue.

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/1095

### CODE REVIEW

**Comment by mkllnk** [comment]
Did you notice that the tests are failing? I guess the change accidentally broke something.

**Comment by pacodelaluna** [comment]
@mkllnk Yes, I have seen it, it didn't 'break' anything but Selenium is not working good with missing translation issues, it was difficult to understand the issues initially but I figured out yesterday.
I have updated the PR, it should be better now, fingers crossed ...

**Comment by pacodelaluna** [comment]
@mkllnk The tests are ok now, please tell me if you see any other issues. Once this PR is merged, I can work on translations on JS templates and on email templates also.

**Comment by sstead** [comment]
image

image

image

**Pull request closed without merging**
