### PR TITLE
Closes translation bug for enterprise fee settings

### LINKED ISSUE #3722: Missing translation keys in enterprise fee menu
## Description
When using the enterprise fee menu the tax dropdown "Inherit from product" is not translated.

The whole dropdown for the column showing the type of fee isn't as well.

Same for the "search" placeholder.

## Steps to Reproduce
1. As an enterprise admin got to admin/enterprise_fees
2. Clic on "manage fees"
3. See the screen captured below

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v1.29
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Ubuntu 18.10
* OFN Platform instance where you discovered the bug: French production

### PR DESCRIPTION
**Pull request by amers185**
#### What? Why?
The enterprise fee management menu has two missing keys. Namely, the search text in search bar and the inherit from product option in tax category. Closed previous PR because of squashing issues. Created new PR instead. 

Closes #3722
I have generated keys for both and put them in the en.yml file. After reviewing, both cases work.

What should we test?

Check if the correct keys are accessed.
Release notes

Transifex will do its magic once everything is merged

FIxed

### CODE REVIEW

**Comment by amers185** [comment]
@luisramos0 does this suffice? Thank you for all the help.

**Comment by amers185** [comment]
I will do that in future instances, thank you!

**Comment by luisramos0** [comment]
I have master into this branch and staged it in staging UK.

**Comment by RachL** [comment]
hey @amers185 ! Thank you so much for this PR this will really help our non-english speakers! 
The original issue was however covering 3 spots, the third being the dropdown list of type of fees (but I apologies, it was badly described):
But don't worry we can merge your PR. FYI if you interested to work on it I've created another issue for the dropdown here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3781


image

**Pull request merged**
