### PR TITLE
Fix product import Metrics/ClassLength

### PR DESCRIPTION
**Pull request by macanudo527**
#### What? Why?

- Helps #6055 

This helps to slim down controllers, making them more for routing than data processing.

#### What should we test?

- Visit Admin Dashboard
- Visit Products Tab
- Click Import
- Choose CSV
- Click Upload
- Click Import
- Verify no errors
- Click Save

[Screencast from 2023年07月12日 16時30分48秒.webm](https://github.com/openfoodfoundation/openfoodnetwork/assets/17987707/5d1fa310-a36e-4934-b2c6-cf88ee1ad057)

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by dacook — COMMENTED** [review]
Hmm, this fixes the linter rule, thanks. But I'm wondering if it brings any benefit.

This simply moves the code to a new place, which I'm not sure makes it any more readable. It moves some `redirect_to` and `render` calls out of the controller which is probably best to avoid.
The new concern is very specific to the one controller and would never be shared.
It's not DRYing up the code by abstracting general methods out (eg I think some file methods could be more general). 

So I'd probably try to refactor the code more.. but honestly I don't think 150 lines was that bad, so I'll discuss with the team about increasing the rule.

**Review by mkllnk — COMMENTED** [review]
I agree that a simple copy and paste is not improving code quality. I'm starting to wonder if the Metrics cops should only be considered when writing new code.

Maybe "Fix all rubocop issues" was not the best idea to trigger work for the sake of it. There are some style violations which cause confusion and are "harmful" the longer they are present but I don't think that metrics cause any harm besides being difficult to read. So if you need to work on some code that's difficult then it's good to refactor it to suit your coming changes but otherwise we may as well leave it. Any changes can cause bugs, merge conflicts and pollute the Git history.

Thank you for pulling our attention in this direction. My opinion is that we should moderate the issue and give you more guidance on what we would find useful to work on.

**Comment by macanudo527** [comment]
Ok, some guidance would be helpful. I've just been using this for learning how to refactor code and write specs, so it hasn't been wasted time for me. My new freelance job is going to be doing this kind of stuff for 2 days a week, so I'm eager to learn and see what another mature project is doing.

**Comment by mkllnk** [comment]
> some guidance would be helpful

I totally understand and I'm sorry that we haven't had capacity to guide you more. David and I are in the process of updating the main issue. It's now called:

* https://github.com/openfoodfoundation/openfoodnetwork/issues/6055

I proposed a priority list of cop categories to work on. But definitely check before doing big changes if it's worth it.

**Comment by macanudo527** [comment]
@mklink should I just abandon this for now? I can't really see anything that is worth extracting. There are a lot of little pieces that don't add up to something worth extracting.

**Comment by mkllnk** [comment]
Hm, yes. I'll close it. Sorry for that.

**Pull request closed without merging**
