### PR TITLE
Rails 5-2 - View spec in rails5

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Resolves rails 5-2 view spec issues:
```

59) Order Management viewing a completed order when checking out as an anonymous guest allows the user to see the details
      Failure/Error: super
      
      ActionView::Template::Error:
        undefined method `display_checkout_subtotal' for #<#<Class:0x00007f8527cbc560>:0x00007f8527cba670>
      # ./app/helpers/application_helper.rb:20:in `method_missing'
      # ./app/views/spree/orders/_summary.html.haml:36:in `_app_views_spree_orders__summary_html_haml__1127751263167468036_70104935160560'
      # ./app/views/spree/shared/_order_details.html.haml:48:in `block in _app_views_spree_shared__order_details_html_haml___2449339065797419772_70104937116180'
      # ./app/views/spree/shared/_order_details.html.haml:44:in `_app_views_spree_shared__order_details_html_haml___2449339065797419772_70104937116180'
      # ./app/views/spree/orders/show.html.haml:28:in `_app_views_spree_orders_show_html_haml___4306387082297664791_70104937523260'
      # ./lib/open_food_network/rack_request_
``` 

#### What should we test?
Green build is enough.

#### Release notes

Changelog Category: Technical changes
Adapts code to rails 5.2

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice!

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
watch out, the build is failing on spec/features/admin/order_print_ticket_spec.rb

**Comment by luisramos0** [comment]
yes, I'll have a look.

**Comment by luisramos0** [comment]
ok, it should be green now. It was the wrong helper name in one spec.

**Comment by luisramos0** [comment]
is a green build in GH enough these days? semaphore is very unstable isnt it? i rerun the build in semaphore to check.

**Comment by andrewpbrett** [comment]
@luisramos0 I just updated the build config in Semaphore to only run js tests, see https://github.com/openfoodfoundation/openfoodnetwork/issues/6752 for more. But yes, I think we're now (back to) a point where if it's not green it shouldn't be merged.

**Comment by luisramos0** [comment]
ah, nice, thanks for the info!
well done btw!

**Review by andrewpbrett — APPROVED** [review]

**Pull request merged**
