### PR TITLE
Revert "Merge pull request #2893 from luisramos0/deleted_products_bre…

### PR DESCRIPTION
**Pull request by sauloperez**
…ak_inventory"

#### What? Why?

This reverts commit 8a3f621b42dfa1248d6b647bcf53befe83790c28, reversing
changes made to 7cac4637fe566c32e17402ed3cf0b5ad7a19443d.

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@sauloperez #assignyourself #please 🙏

**Comment by mkllnk** [comment]
@luisramos0 I just read through the thread at https://github.com/openfoodfoundation/openfoodnetwork/pull/2893 and there are still two open questions:

1. Why are permissions in place if the user sells their own enterprise? Is this scenario still valid?
2. Does reverting fix anything? If the data changed because of the migration, this pull request doesn't change anything about it. The migration didn't have a `down` method and there is no way for a rollback via migration. The user already fixed the stock levels herself. So maybe no further code change is needed for Australia.

**Comment by luisramos0** [comment]
Maikel, good questions:
1- both the code and the migration will revoke inventory items even if override hub_id = produdct supplier_id. we need to fix this in both code and migration.
2- In AUS now, everytime users create permissions, the data will be corrupted again. We should run quick fix (see below) to fix AUS data and revert the change. the more you keep the system as is the more inventories will be messed up.

See here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/2960#issuecomment-434627038

**Comment by luisramos0** [comment]
Actually, changing my mind.
@mkllnk is right on point 2. This code is only revoking permissions on delete (user needs to delete permissions) and will only affect the overrides of that permission (specific relation between 1 producer and 1 hub), no own overrides involved. Also, the code will review overrides when new permission is created but again it will not affect own overrides.

So, the bug is only in the migration. We need to fix it and run it again.

**Comment by luisramos0** [comment]
And, correcting what I say above about point 1.
1- Only the migration will revoke inventory items even if override hub_id = product supplier_id.
The code will only revoke permissions that are part of the permission being created or deleted.

So, actually there is a problem in the code when a permission to manage own inventory is added and then removed (it's a edge case, but will break the inventory). the fix is to re-add the permission. I think we can ignore this case but I'll put this on 2893 for reference.

**Pull request closed without merging**
