### PR TITLE
Removes matomo JS tracking code

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/9650.
Replaces #9665.

As per recent feedback from Matomo Customer Support, the `tag manager integration code` can replace the `general js tracking integration code`; This PR removes the latter.

Some references:

https://matomo.org/faq/tag-manager/manage-tags-in-matomo-tag-manager/
https://matomo.org/faq/tag-manager/create-a-container-in-matomo-tag-manager/
https://matomo.org/faq/tag-manager/install-a-tag-manager-container-on-your-site/
https://matomo.org/blog/2021/12/tag-manager-benefits

#### What should we test?

We should assure standard features from tag and tracking are not changed. Ideally, we'd test Matomo functionalities like:

- goals and funnels
- tags and triggers

...before and after this PR, on pages using the "darkswarm" template, like legacy and split checkout, for example.
 
#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
One note: from what I could gather, there is really no down-side on using the tag manager functionality, in detriment of the js tracking code; Which makes me wonder why is the latter still supported. Maybe a transition phase. 

That said, I see this as a critical change (in the context of analytics), so it would be great to assure this is not changing/breaking already implemented tracking on production. Adding the `prod-test` here too.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Staged this PR in staging-FR, tested in Chome (enabling tracking cookies/behavior) and verified the following:

1. JS tracking code is gone from all pages using `darkswarm` template:
image

2. Trigger / Tag code still works (preview mode):

image

3. Checked the Dashboard section

This _could_ be me, while testing...
image

I've checked out on split-checkout, visiting all three checkout steps, and order confirmation. However we should only have this result tomorrow... I'll check again later again.

This looks good, although point 3. is still to be fully verified. I'd move this to ready to go or merge, later on. What do you think @openfoodfoundation/testers ?

**Comment by filipefurtad0** [comment]
I could get goals/funnels to work after this PR in staging - this might be a regression for production too. Probably relevant for https://github.com/openfoodfoundation/openfoodnetwork/issues/9724

**Comment by drummer83** [comment]
Do you mean 'could not'?
Or did I not understand what you mean?

**Comment by filipefurtad0** [comment]
Yes, I've edited in the meantime.

**Comment by BethanOFN** [comment]
@filipefurtad0 did you manage to get goals/funnels working? Struggling on the UK instance

**Pull request merged**
