### PR TITLE
#1291 Fix dropdown font-size not to zoom in iOS

### PR DESCRIPTION
**Pull request by jeronimo**
#1291

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@lin-d-hop is there someone in the UK team that can check this or is it ready to come into Aus Review land?

**Comment by mkllnk** [comment]
@jeronimo It would be great if you could rebase the branch on the current master.

**Comment by jeronimo** [comment]
@mkllnk not sure what you meant by rebase the branch on the current master? Merge updated master branch into this (I've done it). Or you wanted rebase master into this branch and push force into github?

Btw. Also for (@Matt-Yorkley) OSX Xcode does have iOS emulator which I tested this issue with. In iOS Safari it has different style of dropdown which looks like https://i.stack.imgur.com/uZ0QF.png and it can't be emulated by desktop Safari.

**Comment by mkllnk** [comment]
Yes, rebase on the current master and force push. We just try to keep the Git history a bit cleaner.

**Comment by jeronimo** [comment]
Done!

**Comment by sstead** [comment]
just tested, looks fine to me

**Pull request merged**
