### PR TITLE
#10408/Fixes flaky admin/orders_spec:330

### LINKED ISSUE #10408: [Flaky] spec/system/admin/orders_spec.rb
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage orders
 with a complete order logging as superadmin and visiting the orders page ordering orders with different billing addresses orders by last name
     Failure/Error: find("a", text: 'NAME').click # sets ascending ordering
     
     Capybara::ElementNotFound:
       Unable to find visible css "a" with text "NAME"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_logging_as_superadmin_and_visiting_the_orders_page_ordering_orders_with_different_billing_addresses_orders_by_la_64.png

     
     # ./spec/system/admin/orders_spec.rb:330:in `block (6 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:44:in `block (2 levels) in <top (required)>'
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4139474229/jobs/7157078713

### PR DESCRIPTION
**Pull request by anshu1992**
#### What? Why?
Changes `spec/system/admin/orders_spec.rb` to ensure user is logged in.

- Closes #10408 

#### Why?

It wasn't able to login sometimes and so the test failed. Screenshot attached:

Screenshot 2023-02-15 at 3 38 22 PM

I added a check to ensure that user is logged in. Ran spec around 10 times to see if failed. Before this check it failed on every 2-3rd run. Screenshot attached:

Screenshot 2023-02-15 at 3 44 37 PM

#### What should we test?
Run this spec `rspec spec/system/admin/orders_spec.rb`.

- Visit /admin/orders.
- You should see a table with header `NAME` which is can be clicked in order to sort records based on name column.

#### Release notes
Fixes flaky admin orders spec.

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

#### Dependencies
None

#### Documentation updates
Note required.

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
`login_as_admin_and_visit` is widely used, and I've seen similar issues around that (but cant' find anymore).

My proposition is to add `expect_logged_in` at the end of the method `login_as_admin_and_visit` to solves similar cases as well.

What do you think?

_Moving to `In Dev` then_

**Comment by anshu1992** [comment]
Hey @jibees, made the change as requested.

**Comment by jibees** [comment]
I've squashed your two commits, and added another one since `login_as_admin_and_visit` is used in PDF context, and we cannot expect user is logged in, since we are in a pdf.

**Comment by jibees** [comment]
I've moved into code review, waiting for another reviewer then!

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Review by mkllnk — COMMENTED** [review]
I'm not sure this is solving anything.

> It wasn't able to login sometimes and so the test failed. Screenshot attached:

So expecting to be logged in would then fail as well, right? Maybe we would see the error earlier but we still have a flaky spec.

And adding that parameter adds code complexity. I don't think it's worth it.

I guess that there's another reason for this spec to fail. Maybe the Javascript responsible for sorting needs time to initialise? It seems to be handled by AngularJS. We could add the `ng-transclude` attribute to hide page contents until AngularJS is completely initialised. Maybe that would solve the flakiness.

I ran it 50 times locally but it didn't fail. So it's hard to measure what's effective.

**Comment by anshu1992** [comment]
I can try with ng-transclude to see if that solves the issue.

**Comment by sigmundpetersen** [comment]
Hi @anshu1992 hope you are well.
Did you want to continue on this one?
If so, I think it needs a rebase first as I think something has changed around e.g. `login_as_admin_and_visit`

**Comment by sigmundpetersen** [comment]
@jibees @mkllnk any of you want to move this forward?
Or should we close?

**Comment by jibees** [comment]
No news since march, will close it. 
But feel free to reopen if needed!

**Pull request closed without merging**
