### PR TITLE
When resetting stock to 0 on absent products in product import also reset the on demand setting

### LINKED ISSUE #6064: On import - products not in the product list remain 'on demand'
## Description

When I import a file,  products in my product list but not on the import file remain 'on demand',  even when I select the option that these products should be set to '0' on hand

It messes up  product management significantly!   I cannot simply update my current products -  I have to set all products that I am not currently selling to '0'  manually in my import file.  In the hub I'm currently working with,  this is 2500 products.    I just sold a bunch of products I don't have -  because the message when I imported my file said that the products not on the file were set to '0' on hand successfully. But they weren't.

## Expected Behavior

As the option suggests -  if you check the box when importing,  all the products not in the file should be set to '0'.  This should allow the user to just import and work with a partial product list of current products,  knowing that the others will be set to '0' on hand.

## Actual Behaviour

The import does not set products not in the file to '0'.  Worse,   the message to the user says that it has done so.  (Which is why I only found this after selling a bunch of products I don't have.  They were not re-set to on-demand.) 

## Steps to Reproduce

1. create an import file with 2 products set to 'on demand'
2.remove one of the products from the import file and re-import,   selecting the box to select products not included in the import file to 0 on hand
3.see the confirmation message that this has been done
4. look at your product list and see it has NOT been done -  the product is still set to 'on demand'  

## Animated Gif/Screenshot

Here is the product in my product list
product on product list
I removed it from my import file and re-imported,   see the box is selected
product import screenshot
here is my confirmation that it is done
product import message
here is my post-import product list -   see the product is still listed as 'on demand'
after import product list

## Workaround
Manage all products online  or on the file I guess.  But -  right now,  users might not even realize that their product list,  and hence order cycles -  have products listed that are not available.  (I didn't)

Maybe a minimum step for now would be to remove the check box,  or remove the confirmation message -- so we aren't confirming something happened that didn't?

## Your Environment

* Version used:
* Browser name and version: Chrome - latest
* Operating System and version (desktop or mobile): desktop

## Possible Fix

Further to this -   I think this was introduced at the same time it became impossible to delete products in orders.  May be related?  I think this because the user who reported to me that they couldn't delete products,  also said that the "check box on the product import screen wasn't working".   I misunderstood them,  and tested product import and got no errors - so I didn't do an issue then.  Now I realize  this is what they were reporting  in addition to not being able to delete products.

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

Before when you imported products and clicked the 'Set stock to zero for all existing products not present in the file' option it would set the on hand stock to 0 but if the variant was also set to be on demand the product would still be available for sale. This change makes sure the on demand setting is turned off too.

Closes #6064.

#### What should we test?

1. Set up a product variant to be 'on demand'.
2. Run a product import with the 'Set stock to zero for all existing products not present in the file' option but don't include the above product.
3. Check the product variant is no longer set to be on demand.

#### Release notes

When resetting stock to 0 on absent products during a product import also turn off the on demand setting.

Changelog Category: Fixed

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]
Nice one! Thanks!

I wonder if there is a way to tell rubocop to alow specs to go let's say up to 300 lines. I think that would be good. Specs with 100 lines is not realistic...

**Comment by cillian** [comment]
@luisramos0 Yes 100 lines is very short. One way to allow 300 lines in specs could be to use a per directory `.rubocop.yml` config file e.g.

A `.rubocop_specs.yml` file in the root directory containing...

```
Metrics/ModuleLength:
  Max: 300
```

Then a config file in each spec directory e.g. `spec/.rubocop.yml`, `engines/catalog/spec/.rubocop.yml`, etc. Each of those would contain...

```
inherit_from:
  - ../../../.rubocop_specs.yml
```

**Review by sauloperez — APPROVED** [review]

**Comment by luisramos0** [comment]
Thanks @cillian it works. I went for it here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6256

**Comment by filipefurtad0** [comment]
Hi @cillian,

Thanks for introducing this improvement.

I've verified the bug - indeed the on_demand settings do not change, even though this is set upon product import. Before this PR:

- with these product settings:
image

- importing a new product ("eggs" not shown on that list) and ticking the option to reset stock only has an effect on variants with limited stock:

image

image

After staging this PR and resetting stock levels for some variants:

image

and uploading the same file - making sure the option to reset stock levels is ticked - now makes all products not available on that file unavailable. It sets the stock to zero and removes the "on_demand" setting:

image

I checked as well if for the variant included on the product-import file, the:
- setting of a given stock value works as before - OK
- setting of that variant "on_demand" works - OK


All good here!

Ready to go.

**PS (not introduced and outside the scope of this PR):**
I had a look at what happens to the inventory import. It seems we have the same issue there i.e., ticking the option to set stock values to zero importing variants to the inventory does not reset inventory products on demand.

For example, for this inventory list:

image

Uploading "eggs", on demand, with the option to set other the stock of variants to zero ticked:

image

image

Leads to this result:
image

I think this might need an issue - what do you think @tschumilas ? Have you ever came across this issue?

**Comment by cillian** [comment]
Cheers @filipefurtad0 ...good catch on the inventory import :+1:

**Pull request merged**
