### PR TITLE
Fix: Missing translation in error messages issue#9559

### PR DESCRIPTION
**Pull request by Laurel16**
#### What? Why?

Closes #  9559. 

This PR is adding missing translation to for name & price in spree/product in config/locales/{lang}.yml.
This fixs the missing error message describe in the issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/9559

#### What should we test?
Similar to the Steps to Reproduce in the issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/9559

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
Hi @Laurel16 👋 

Actually, we use Transifex to manage our i18n. Therefore, we only update the `en.yml` file and then when new keys appears (ie. when PR is merged), instance managers are aware of those key and can translate those new keys inside Transifex. After that, we pull the each file from Transifex.

That's why here, you only need to modify `en.yml` file ;) Sorry about that! That's maybe not clear enough.

Source: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

**Comment by Laurel16** [comment]
> Hi @Laurel16 👋
> 
> Actually, we use Transifex to manage our i18n. Therefore, we only update the `en.yml` file and then when new keys appears (ie. when PR is merged), instance managers are aware of those key and can translate those new keys inside Transifex. After that, we pull the each file from Transifex.
> 
> That's why here, you only need to modify `en.yml` file ;) Sorry about that! That's maybe not clear enough.
> 
> Source: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

**Comment by Laurel16** [comment]
> > Hi @Laurel16 👋
> > Actually, we use Transifex to manage our i18n. Therefore, we only update the `en.yml` file and then when new keys appears (ie. when PR is merged), instance managers are aware of those key and can translate those new keys inside Transifex. After that, we pull the each file from Transifex.
> > That's why here, you only need to modify `en.yml` file ;) Sorry about that! That's maybe not clear enough.
> > Source: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

Hi @jibees 👋 Thank your for your comment.  Too bad for me but now I know how to say Product in Turkish :-) 
If I understand well, just adding the new keys in spree/product in en.yml file would have been sufficient ?

**Comment by jibees** [comment]
>If I understand well, just adding the new keys in spree/product in en.yml file would have been sufficient ?

Yep, only keys (and associated values) are enough.

**Comment by Laurel16** [comment]
> > If I understand well, just adding the new keys in spree/product in en.yml file would have been sufficient ?
> 
> Yep, only keys (and associated values) are enough.

@jibees shall I make a new PR with only this change?

**Comment by jibees** [comment]
You can update this PR by force pushing the branch

**Pull request closed without merging**
