### PR TITLE
Admin, on page `/admin/enterprise_fees` when selecting a calculator, update its settings automatically (without reloading the page)

### LINKED ISSUE #9485: Enterprise fee calculator: Allow to enter calculator settings immediately (without saving/reloading the page first)

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
This needed the migration `/admin/enterprise_fees` from AngularJS to StimulusReflex: main part of the issue.

- Closes #9485 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
This work is not ended as I'm blocked on the way I can 'customize' parameter name in the calculator settings sub-form (the one that is updated when selecting another calculator_type).

I'm facing an issue around rails form, and therefore I need help from @openfoodfoundation/core-devs 🙏 

##### What we have on `master`: a form
The page `/admin/enterprise_fees` is a big form, posted on `/admin/enterprise_fees/bulk_update`

The part 'Calculator Values' depends on 'Calculator' selection:
Capture d’écran 2023-02-02 à 14 49 42

Currently (ie. on `master`) and if we take this screenshot as an example, the `<input />` _Per Unit_ has the following name: `sets_enterprise_fee_set[collection_attributes][0][calculator_attributes][preferred_per_unit]` which is long but actually correct. When submitted, rails controller knows how to iterate over EnterpriseFees and then assign values to that field. 

##### What I've done: a `form`, but some input have bad name
What I've done is basically replacing all AngularJS code to rails+stimulusreflex one. Doing that, it appears that the _same_ input has the following name: `calculator_weight[preferred_per_unit]`. We miss `sets_enterprise_fee_set[collection_attributes][0]` part and therefor, when submitting value is not updated as it does not follow the right structure.

##### Why the name isn't correct?
Because of the way we build the form on `app/views/admin/enterprise_fees/_calculator_form.html.haml`:
```haml
= form_for(calculator, url: "", method: nil, authenticity_token: false) do |calculator_form|
```
The partial is imported in two ways:
 - **WAY_1**: Either it's done through the view (`app/views/admin/enterprise_fees/index.html.haml`) directly via:
```haml
= render partial: "calculator_form", locals: { calculator: f.object.calculator }
```
 - **WAY_2**: Or it's done trough the reflex  (`app/reflexes/enterprise_fees_reflex.rb`)
```ruby
morph "#calculator-settings-#{id}",
          with_locale {
            render(partial: "admin/enterprise_fees/calculator_form",
                   locals: { calculator: calculator, I18n: I18n })
          }
```

The form is build from the `calculator` object directly and not _inside_ the global form on object `@enterprise_fee_set`

##### Where I'm actually blocked?
I tried to change the way the form is build, and actually, it's pretty simple if we change the **way_1**. It simply consist to pass the form to the partial and change the partial a bit:
`app/views/admin/enterprise_fees/index.html.haml`
```haml
= render partial: "calculator_form", locals: { f: f, calculator: f.object.calculator }
```
`app/views/admin/enterprise_fees/_calculator_form.html.haml`
```haml
= f.fields_for :calculator, calculator do |calculator_form|
```

and then the `<input />` has the right name: `sets_enterprise_fee_set[collection_attributes][0][calculator_attributes][preferred_per_unit]` and therefor could be handled when submitted. 
But this solution is not that compatible with `app/reflexes/enterprise_fees_reflex.rb`: we need to build and pass the form to the partial. I tried to build the form object for a _fake_ `enterprise_fee_set` that contains only the current `enterprise_fee` (this does not handle the creation case...):
```ruby
enterprise_fee_set = Sets::ModelSet.new(EnterpriseFee, EnterpriseFee.where(id: id))
form = ActionView::Helpers::FormBuilder.new(:enterprise_fee_set, enterprise_fee_set, self, {})
```
But I didn't manage to go further because of: 

```
ERROR: undefined method `fields_for' for #<EnterpriseFeesReflex:0x00007fe462b79208 
```

(and probably more errors I can't remind at the time I write this message)

##### Solution?
Previously, it seems that we used to use a crappy (?) solution:

https://github.com/openfoodfoundation/openfoodnetwork/blob/1e3f754f96a21f0ca2b701d1e58d0e9bf8a7f619/app/serializers/api/admin/enterprise_fee_serializer.rb#L28

that maybe hack the input name ....

**Comment by RachL** [comment]
Just a note that this work in not prioritized and we have 18 PRs in code review. Maybe we should park this one for a while @jibees ?

**Comment by jibees** [comment]
Yep. I wanted to tackle this one as it was marked as papercut (which I probably plead guilty) and I had few minutes left during my day. And then I was stuck in a spiral. I'll be back on code review. 

But, to be honest, I think it's also important to try to learn more and more about replacing AngularJS with rails+stimulusReflex, and this case is a good case study.

**Comment by RachL** [comment]
>  try to learn more and more about replacing AngularJS with rails+stimulusReflex, and this case is a good case study.

I know - but we have the PR column and backoffice UI uplift for this as well. So in terms of priority, BUU and the column PR should be shipped first. Not to mention all PRs that have been started by Avi. I'm not saying we shouldn't work at all on this, just that it's dangerous to do the review now as it seems it can be a rabbit hole for someone else as well.... :/

**Comment by dacook** [comment]
@jibees you've documented the issue really well here, thanks. As Rachel suggests I'll try not to get involved yet..

I think this issue is partly why I'm still a bit unsure about StimulusReflex. Here we're opening up two code paths that do the same thing (building the calculator form fields), and if they don't behave exactly the same we will have some problems..
But anyway I will move on to other code review!

**Comment by mkllnk** [comment]
Thanks for describing the issue so well. I won't look at the code now but it reminds me of a discussion I had with @dacook on his webhooks work.

A lot of our current pages have huge forms because that used to be more efficient in the past. Network requests were slow and we wanted to submit all data in one go. And with AngularJS we did a lot of transformation and filtering on the page. It was more convenient to hold all the data in the browser to enable AngularJS to see it all.

But HTTP2 changed the trade-off between network requests and processing time on the server. These big bulk operations don't bring much performance gain any more. Instead, they make everything more complicated like the structure of the nested parameters.

StimulusReflex is going back to simple Rails / REST actions and reflexes can be used to update only a small part. But our current architecture is not open to this simplicity. We need to refactor the forms first. In another PR I suggested to split up the form and have one form for each row in the table instead of having one big form.

But while we still have these big forms, can we still apply StimulusJS without the reflexes? My understanding was that reflexes can speed things up by doing only a little work when we don't need to do everything. But why don't we submit the whole form for now, use the existing controller action and re-render the page? It can still replace only the changed DOM elements, right? We need to find an easy transition path which may be a bit slower for the user until we have all our new and shiny toys and can optimise.

**Comment by RachL** [comment]
As per discusisn in delivery circle, this is not a papercut. Closing and moving to wishlist again.

**Pull request closed without merging**
