### PR TITLE
Update fees after changing a line item

### LINKED ISSUE #7296: Changing line item quantity does not update fees
## Description

In the back office, changing the quantity of a line item does not update the fees for an order.

## Expected Behavior

Changing the quantity of an item should also update any fees that are associated with the item. 

## Actual Behaviour

The order total is unchanged until clicking "Update and Recalculate Fees"

## Steps to Reproduce

1. Create an order with line item fees
2. Change the quantity of one of the line items
3. Note the order total and fee for the line item
4. Click Update and Recalculate Fees
5. Note that the order total and fees change

## Animated Gif/Screenshot
MjmDUHapAC

## Workaround

Knowledgeable users will click the Update + Recalculate button, but this will appear broken to a lot of people. 

## Severity

On its own, probably an S3, but the fix will also involve fixing https://github.com/openfoodfoundation/openfoodnetwork/issues/6806, which was originally an S2.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #7296; addresses https://github.com/openfoodfoundation/openfoodnetwork/issues/6806

This fixes the issue, but maybe not in the most performant way possible. @Matt-Yorkley I tried a bunch of different variations of just calling `update_line_item_fees!` and reloading the order and line items, but this (falling back on `recreate_all_fees!`) was the only thing that worked...

I'd also like to write a better test. The most lightweight approach would be to spec the #add method in the controller to say that calling it should always call `recreate_all_fees!` (or whatever we end up going with). But that feels like a silly test to write, and it's also difficult (maybe not possible?) to get Rspec to expect a message on a database object. 

#### What should we test?

See #7296 

#### Release notes

Changing the quantity of line items for an order in the backoffice now automatically updates the appropriate fees. 

Changelog Category: User facing changes

### CODE REVIEW

**Comment by sauloperez** [comment]
> will increase coverage by 0.00%

the singularity :joy:

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by sauloperez** [comment]
> This fixes the issue, but maybe not in the most performant way possible. @Matt-Yorkley I tried a bunch of different variations of just calling update_line_item_fees! and reloading the order and line items, but this (falling back on recreate_all_fees!) was the only thing that worked...

We can't neglect performance, it's too costly :sweat: 

Why don't we make `OrderFeesHandler` deal with a single line_item? It's supposed to do it already in `#create_line_item_fees!` so it wouldn't be too hard to move the block to a new public method that accepts a line_item as an argument. 

> But that feels like a silly test to write, and it's also difficult (maybe not possible?) to get Rspec to expect a message on a database object.

It may be silly but we must guarantee that the method is called for the action to work :shrug: . And we can test that very easily but stubbing `find_by!(number:)` to return the test order and then asserting the method call against that order object.

**Comment by Matt-Yorkley** [comment]
> it wouldn't be too hard to move the block to a new public method that accepts a line_item as an argument.

I'm planning on doing that soon and taking a second pass at improving all the places we currently call `#recreate_all_fees!`, but it ties in to adjustments code that is still changing frequently, and there's a couple more bits that need to change before we can get the most benefit there.

**Comment by sauloperez** [comment]
Can't we help you on that? Ideally, if we design a proper abstraction we should be able to decouple from those adjustements details that still need to change.

**Review by sauloperez — CHANGES_REQUESTED** [review]
I think we do need a test. Fees are too delicate.

**Comment by andrewpbrett** [comment]
I definitely think it needs a test, I think I was just getting frustrated the other night (the approach of stubbing `find_by(:number)` also wasn't working!) and wanted to get someone else's eyes on the problem I was facing :)

On performance: my thinking was that until we can do the fast thing we need to do the correct thing... I tried using `update_line_item_fees(item)` but it wasn't working as I expected it to. So similarly, I felt like I was hitting a roadblock there and wanted to see what Matt thought. 

I'll give the test another shot in the meantime.

**Comment by andrewpbrett** [comment]
@sauloperez let me know what you think of this approach: https://github.com/openfoodfoundation/openfoodnetwork/pull/7299/commits/5bfd6fd2ba8833967526a8d90a616f24db186002 - I ended up having to reach into the controller and stub out a lot. And if/when we change the method that's called, we'll need to update the test. But it's hopefully better than nothing? 😁

**Comment by Matt-Yorkley** [comment]
> until we can do the fast thing we need to do the correct thing

Yeah, I think we can go with this for now and come back to it later. It's on my todo list :+1:

**Comment by sauloperez** [comment]
It's definitely not your fault but the design's @andrewpbrett

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

I checked the scenario described in #7296 and #5567:
- making changes to line item quantities
- adding/removing line items

Does not require clicking "Update and Recalculate Fees" :+1

Also checked the scenario which might have led to #6806:
- removing a line item from an order
- printing the invoice

The info (line items, fees, taxes and order total) is now correctly displayed on the invoice, as the order now updates, without the need to click "Update and Recalculate Fees" :+1: 

Awesome :tada: 

Sounds to me as if this PR actually makes this button obsolete? Performance issues aside - yeah, I guess we need to consider them - but updating fees is not really optional. So maybe we can remove this from the UI? This needs a bit more thought, but I think this goes in that direction.

Good to go!

**Comment by filipefurtad0** [comment]
One additional note:

I could not really reproduce the scenario described on #6806 . Comparing the invoices before and after removing a line item from an order (without clicking Update and Recalculate fees) correctly showed the order's contents, i.e., the deleted line item did not appear on the invoice. So I'm not entirely sure it closes this issue - but I guess it should (maybe I'm not quite reproducing this scenario correctly)

Also tested changes introduced by customers on editable orders: the invoices appeared correctly.

But I guess we can close the issue, and reopen - if we do have more occurrences.

**Comment by andrewpbrett** [comment]
Thanks for the always-thorough testing @filipefurtad0! I agree about #6806. It seems likely that with this new change, that scenario won't occur again, and if it does, we can reopen the issue.

**Pull request merged**
