### PR TITLE
Bump to ruby 2.4.4

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #https://github.com/openfoodfoundation/openfoodnetwork/issues/6115
Last upgrade was ruby 2.3.7 https://github.com/openfoodfoundation/openfoodnetwork/pull/4518 

This PR goes with https://github.com/openfoodfoundation/ofn-install/pull/677 that installs 2.4.4.

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by luisramos0** [comment]
I changed semaphore settings to ruby 2.4.4 and run this build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-6441/builds/2

**Comment by luisramos0** [comment]
In the build we can see a few issues with BigDecimal, some code needs to be adapted I guess.

**Comment by Matt-Yorkley** [comment]
I wonder if we could skip `2.4.x` and bump straight to `2.5.x`? I think it might actually have less issues...

Hot tip: `2.5.7` is an excellent vintage :champagne: :wink:

**Comment by luisramos0** [comment]
we can try, this is what I read: https://stackoverflow.com/questions/53213498/has-ruby-2-5-been-tested-with-rails-4-2

**Comment by luisramos0** [comment]
Main issue here is BigDecimal behaviour: https://stackoverflow.com/questions/59022857/ruby-2-4-and-bigdecimal-error-invalid-value

I fixed it in preferable and voilá, the build is good, only the flaky tag_rules spec!!!

I am moving this to Code Review :heart:

**Review by andrewpbrett — APPROVED** [review]
This seems... way too easy? But the build is green (minus that flaky spec)! Let's do it.

**Comment by Matt-Yorkley** [comment]
Nice! I'm wondering if we have any gems that could pass an empty value to `BigDecimal` at some point?

I just had a quick look, and `2.5.7` seems to work as well (with this fix added).

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by Matt-Yorkley** [comment]
I've tried provisioning Ruby `2.4.4` and deploying this PR, and it looks good to me. Do we want to do some other testing, or just included it in the next release?

**Comment by andrewpbrett** [comment]
Since the build is green, I'd say it's fine to include in the next release. Do we need to alert people that they'll need to reprovision servers before updating?

**Comment by Matt-Yorkley** [comment]
Yeah, I think it might be good to leave this unmerged for now and discuss the plan a bit. I've provisioned the staging servers so they now have Ruby `2.4.4`, but I haven't done production servers yet. We'll have to tell non-core instances they need to provision with the latest `ofn-install`. And I think we'll need a very thorough release test.

**Comment by luisramos0** [comment]
Shall we do a staging server test first with this PR? I'd move this to test
ready.

**Comment by Matt-Yorkley** [comment]
I did a `dev-test`. Provisioned Ruby `2.4.4` and staged this PR. Everything seemed fine :+1:

The question is: do we want to do some more manual testing of this specific PR in staging (and if so, what would we test?), or shall we just assume that the release test will cover it reasonably enough?

**Comment by luisramos0** [comment]
Yeah. Maybe easier to merge and get all staging servers with 2.4.4. With
that you can test a few other PRs with it and then finally validate it in
the release testing.

**Comment by Matt-Yorkley** [comment]
Ok, staging servers all have Ruby 2.4.4, so I'll mere this and update Semaphore...

:rocket:

**Comment by luisramos0** [comment]
:clap:

**Pull request merged**
