### PR TITLE
Make StripeSCA void action work

### LINKED ISSUE #5258: Make voiding a payment work with StripeSCA payments
## Description
With the new StripeSCA, users cant make total refunds in backoffice.
I think partial refunds are working although I didnt manage to test.

The action void (cancel) in stripe does work in the Payment Intents API. It doesnt let us cancel payment intents that have been confirmed: https://stripe.com/docs/api/payment_intents/cancel
In the payment intents api we need to issue a refund: https://stripe.com/docs/refunds

If the credit action works (needs to tested), this change is very small, on the void user action we need to issue a refund (which is what is already happening on a partial refund).

Refunds user guide for reference:
https://guide.openfoodnetwork.org/basic-features/orders/refund-payments#how-to-refund-a-payment

## Acceptance Criteria & Tests
Make stripeSCA payment and void it in the backoffice. Verify there's some positive feedback to the user. Verify the Stripe dashboard to see the **total** refund.
Make stripeSCA payment, remove an item from the order so there's some credit owned. Then, void the payment in the backoffice. Verify there's some positive feedback to the user. Verify the Stripe dashboard to see the **partial** refund.

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5258

StripeSCA does not support voiding confirmed payment intents so we need to make a refund of the full amount instead.

#### What should we test?
The code changes is really only in the void action in StripeSCA so we dont need to do major stripeSCA tests. Maybe just a sanity checks and then validate the total and partial refunds are working correctly.

#### Release notes
Changelog Category: Changed
StripeSCA payment method now supports full refunds.

### CODE REVIEW

**Comment by luisramos0** [comment]
Some problem with the order of execution of the spec, I dont understand it.
I decided to delete the specs verifying filtering of master variants in the repport, they are not used in the report: https://github.com/openfoodfoundation/openfoodnetwork/blob/a91c81059f34335d12a43a024f636996b925d553/lib/open_food_network/products_and_inventory_report_base.rb#L27

**Comment by luisramos0** [comment]
rebased to fix conflicts in a spec.

**Comment by luisramos0** [comment]
I have just tested and it looks the same from a user perspective on stripe dashboard.
This is a voided payment in StripeConnect:
image

And this is voided payment in stripeSCA:
image

**Comment by luisramos0** [comment]
rebased to resolve conflicts. @Matt-Yorkley can you please review this? Thanks!

**Comment by luisramos0** [comment]
rebased to fix problem in the build.

**Comment by filipefurtad0** [comment]
Hi @luisramos0,

To test this PR, I placed Stripe-SCA orders with a regular and a 3D secure card, as a basic sanity check - all good.

Then, i) voided one of the orders and ii) issued a partial refund on another. I monitored these changes in the:
- status of the order (admin)
- stripe dashboard
- payment totals report (admin)
- status of the order (customer)



i) Voiding the payment in order R406080336 now works :tada: 

image

The Stripe fee was refunded as well, as shown in the Stripe Dashboard:
image

The Payment Totals Report for this day shows this due payment:
image

The status of the order changes from "Paid" in the order confirmation email to "Not paid". This can be checked in the customers own orders:

image

Ready to go!


ii) Issuing a partial refund on R406080336:
image


It is shown in the Stripe Dashboard (partial Stripe-fee refund):
image


The Payment Totals report shows the partially refunded order correctly:
image
(it shows twice the value because I placed two orders with that amount - all good)

For the customer, the value of the order changes, the paid status remains:
image

**Comment by filipefurtad0** [comment]
I forgot to mention: please note @luisramos0 that this PR was staged with these two failing specs, which I assumed were flaky specs:

- rspec ./spec/models/variant_override_spec.rb:36 # VariantOverride scopes fetching variant overrides indexed by variant does not include overrides for soft-deleted variants

- rspec ./spec/features/admin/bulk_product_update_spec.rb:246 # As an Administrator I want to be able to manage products in bulk updating product attributes

I'm happy to rerun the tests, should you find these failing specs of relevance.

**Comment by luisramos0** [comment]
awesome all good! Except for the flakiness of our build right now.

**Pull request merged**
