### PR TITLE
Add cities and countries to DFC affiliate sales data endpoint

### LINKED ISSUE #12890: Add cities and countries to DFC affiliate sales data endpoint
Funded feature code is https://github.com/openfoodfoundation/openfoodnetwork/issues/12543 [DFC] Anonymized orders endpoint

## Description

**- As a:** Affiliate sales data API user
**- On page:** API only, URL is `/api/dfc/affiliate_sales_data?endDate=2024-12-31&startDate=2024-01-01`
**- I want to be able to do:** I want to be able to see cities and countries **for both suppliers and distributors**

We should use `hasCountry` and `hasCity` (part of Address)

## Acceptance Criteria & Tests

1. Turn on feature toggle `affiliate_sales_data`
2.  Use an enterprise that allows the endpoint
3. Check cities and countries are available **for both suppliers and distributors**

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12890
- This PR adds country and city data in the affiliate sales data endpoint for supplier and distributor

#### What should we test?

- As mentioned in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [x] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Nice one :+1:

**Review by dacook — APPROVED** [review]
Looks good, nice and straightforward. Sorry for the delay in review.

**Comment by RachL** [comment]
@chahmedejaz just checking is this URL correct? https://staging.coopcircuits.fr/api/dfc/affiliate_sales_data?endDate=2024-12-31&startDate=2024-01-01

**Comment by chahmedejaz** [comment]
> @chahmedejaz just checking is this URL correct? https://staging.coopcircuits.fr/api/dfc/affiliate_sales_data?endDate=2024-12-31&startDate=2024-01-01

Yes, @RachL - I believe it should be this. Plus please make sure you are login to the staging server. Thanks.

**Review by mkllnk — APPROVED** [review]
Great. I updated the docs as well which demonstrate example data.

**Comment by chahmedejaz** [comment]
@RachL - To validate this, please follow these steps:
- Enable the following feature flags:
  - affiliate_sales_data
  - connected_apps
- Login as an enterprise owner/manager and make sure that this Enterprise has distributed some orders within the start and end date range
- Please "Allow Data Sharing" for the above enterprise by navigating to the Connected Apps panel on the enterprise edit page

After following the above steps please try the API endpoint again.

**Comment by RachL** [comment]
Thanks @chahmedejaz with the fact that the staging data has changed since my first tests I completely forgot my setup was incomplete, sorry for the waste of time 🤦‍♀️ 

However I now get an error 500 when reaching the URL. I'm using enterprise ID 5714 on staging FR, let me know if you want super admin access and I can upgrade your account.

**Comment by chahmedejaz** [comment]
No worries, @RachL 
Please create my account in staging fr and I'll check it.
I'd need admin and enterprise owner accounts. Sharing my email with you in person, please let me know if you need anything. Thanks

**Comment by filipefurtad0** [comment]
> Thanks @chahmedejaz with the fact that the staging data has changed since my first tests I completely forgot my setup was incomplete, sorry for the waste of time 🤦‍♀️

Apologies... This was me trying to make another PR work. I've restored the test data to a previous point. I guess this interefered with your testing @RachL , sorry for that :-/

I guess restoring the DB needs to be used with care, to prevent such situations :warning:

**Comment by filipefurtad0** [comment]
I've just noticed the staging-FR label was on this PR. I thought it was not, because of this notice:

image

The "removed" comes last, so I assumed the server was available. I hope I did not interfere (yet again!) with your testing @RachL . I've re-added the label.

**Comment by RachL** [comment]
@filipefurtad0 no don't worry I've left it for Ahmed to look at it.

**Comment by chahmedejaz** [comment]
@RachL - The issue is that your range is long and has a lot of data. This takes time and our server timeout.
Please shorten the range, like try the data for 1 or 2 months or so ? I tried with 
https://staging.coopcircuits.fr/api/dfc/affiliate_sales_data?startDate=2024-10-01&endDate=2024-12-31
And it works fine. Thanks

image

**Comment by RachL** [comment]
I knew the problem was simple!! thanks @chahmedejaz merging :)

**Comment by RachL** [comment]
@chahmedejaz there is one failling test, do you confirm it's ok to merge?

**Comment by chahmedejaz** [comment]
That's strange @RachL , this failing spec is passed in the master as well as in this branch on local.
Moreover it's not even related to the changes.
This was passed in the PR before as well. 😅
 
Will look into it a bit more in a while if I can find something. 

Just a tip for the future, unless we have conflict or latest-master-dependant failing spec, we don't need to rebase or force push the branch. 🙂

**Comment by sigmundpetersen** [comment]
Have re-run the spec quite a few times. The failure seems consistent, or at least very flaky.
So i think it would need to be looked at either way.

The failure is also in ./spec/system/admin/reports/pay_your_suppliers_spec.rb so seems relevant :)

**Comment by sigmundpetersen** [comment]
Have re-run the spec quite a few times. The failure seems consistent or at least very flaky.
Since the failure is unrelated to the PR we could choose to merge and monitor if the failure continues in master.

If it fails with the same frequency in master we would have to look into it immediately though.

**Comment by chahmedejaz** [comment]
> > Just a tip for the future, unless we have conflict or latest-master-dependant failing spec, we don't need to rebase or force push the branch. 
> 
> thanks! I could be wrong, but I think I've done the rebase otherwise I wouldn't have the merge button (the message said the branch was not up-to-date with the base branch anymore or something like that).

Ah, you did the rebase from GitHub. Sorry for my misunderstanding, I thought you did it by terminal for something 😅

**Comment by chahmedejaz** [comment]
> Have re-run the spec quite a few times. The failure seems consistent or at least very flaky.
> Since the failure is unrelated to the PR we could choose to merge and monitor if the failure continues in master.
> 
> If it fails with the same frequency in master we would have to look into it immediately though.

Let me do some more digging on it and get back to you before we merge

**Comment by chahmedejaz** [comment]
I tried validating this by pushing only my changes before rebasing, build got green.
When I rebased and pushed, it's still failing the same spec. 

I looked into it more closely, the failing spec, I think I've found a way to fix this. But still it's strange that the changes are not related to that spec and it's still changing its behavior 😅

Anyhow, I'll fix this spec here and push the fix as soon as possible.

**Comment by chahmedejaz** [comment]
@sigmundpetersen @RachL - The specs are fixed now, there was some specs data issue. Data has been fixed and specs got fixed now.

The PR functionality has not changed, nor was it related to the previous failure. Please see, if we are good to merge this as PR has been passed the validation.
Otherwise, we could move it to the next step for review and re-validation. Thanks.

**Comment by sigmundpetersen** [comment]
Let's get a short review from a dev on the last commit, after that it's good to merge I think 👍

**Comment by RachL** [comment]
@chahmedejaz before this get reviewed again I apologies but I need to ask you to remove the city. I've received an email from the researchers and apparently there is a legal issue about the city name 👀 Sorry about this, I'm really surprise to hear about this so late in the project. Please do put all your hours in clokify / CoopCircuits will pay for that extra work anyway.

**Review by mkllnk — APPROVED** [review]

**Comment by RachL** [comment]
All good here many thanks @chahmedejaz ! Merging :tada:

**Pull request merged**
