### PR TITLE
3782 Fix missing translation in subscription update modal

### LINKED ISSUE #3782: Missing translation when subscription update would not cascade to order in open OC
Missing translation when subscription update would not cascade to order in open OC.

## Description

See image:

20190503231500-subscription_changes_not_cascaded_to_orders_closes_translation

## Expected Behavior

The translation should use word "closes" or similar.

## Actual Behaviour

The translation is missing.

## Steps to Reproduce

1. Create a subscription with no end date for an open OC. Set pickup as the shipping method.
2. Edit the subscription order.
3. Change the billing name for the order.
4. Edit the subscription.
5. Change the billing name for the subscription. The modal with the missing translation would appear.

## Animated Gif/Screenshot

20190503233800-subscription_changes_not_cascaded_to_orders_closes_translation

## Context

This came up in #3589.

## Severity

bug-s4: it's annoying, but you can use it

### PR DESCRIPTION
**Pull request by kristinalim**
Fix missing translation in subscription update modal.

:warning: This includes changes in #3589 and needs to be rebased after that PR is merged. Only the last commit here is really for this PR.

#### What? Why?

Closes #3782 

See issue for details.

#### What should we test?

1. Create a subscription with no end date for an open OC. Set pickup as the shipping method.
2. Edit the subscription order.
3. Change the billing name for the order.
4. Edit the subscription.
5. Change the billing name for the subscription.
6. In the modal that opens, there should be no missing translation.

#### Release notes

This is for 2-0-stable.

#### Dependencies

This includes changes in #3589.

### CODE REVIEW

**Comment by kristinalim** [comment]
I rebased this branch upon `master`.

**Comment by RachL** [comment]
@kristinalim on staging FR I don't see any modal anymore. Did you simply removed it?

**Comment by kristinalim** [comment]
@RachL No, I did not remove the modal. Just a moment, I will try the steps again, maybe I made another mistake...

**Comment by kristinalim** [comment]
@RachL I am able to have the subscription update modal open fine - kindly see the screen recording below:

20190516175700-subscription_details_modal

I'm not sure what the problem is. In Step 2 above, maybe I was confusing when I said "subscription order" (which I meant was, order for the subscription)?

**Comment by RachL** [comment]
@kristinalim thank you, I think I know what went wrong the first time: I've put the same character than the one I used editing the order when editing the sub. Sorry about that. 🤦‍♂  This is ready to go

image

**Pull request merged**
