### PR TITLE
Merge Headless Chrome to master

### LINKED ISSUE #2469: Replace PhantomJS with headless Chrome
We see a lot of test failures on our Continuous Integration servers. Some of them could be related to PhantomJS not being very consistent and reliable.

## Description

Rob has been working on using headless Chrome instead of PhantomJS for our feature tests. I thought that was a really good idea, but it is actually a lot of work to change our tests to work with Chrome. I'm also wondering if Chrome is what we want. In an ideal world, our tests would run with all browsers, but at the moment the tests don't pass in all browsers (different test behaviour) and we don't have enough CI power.

So assuming that we will test with only one browser, here is a little breakdown:

For PhantomJS:
- It's like an old Safari. We test compatibility with older browsers.
- It's made for testing and can raise Javascript errors as Ruby errors.
- We are used to it and we don't have to change tests.

For Chrome:
- PhantomJS is not maintained any more: https://github.com/ariya/phantomjs/issues/15344
- Chrome is more reliable.
- It behaves like a real browser, not something emulating a browser.
- Chrome has a global market share of ~50%. https://en.wikipedia.org/wiki/Usage_share_of_web_browsers
- A simple option changed on a developer's machine can activate real browsing to see what's going on (not headless).

I tend to switch to Chrome, but I wanted to double check with you if you have any concerns.

## Expected Behavior

Tests always pass.

## Actual Behavior

Tests sometimes pass.

## Steps to Reproduce

Open a pull request to trigger a test run.

## Context

When developing, our test servers often have different results to my own machine. And I can't really see what PhantomJS is doing apart from `save_and_create_screenshot`.

## Severity

s4 tech debt

## Possible Fix

Use headless Chrome or Firefox. Rob started that work and I added a little bit. Now we are managing a branch as a team, creating pull requests to fix the broken tests: https://github.com/openfoodfoundation/openfoodnetwork/compare/headless-chrome?expand=1

**7** Broken tests:
```
rspec ./spec/features/admin/variant_overrides_spec.rb:289 -> #3326

rspec ./spec/features/admin/bulk_order_management_spec.rb:485 -> #3325
rspec ./spec/features/admin/shipping_methods_spec.rb:79
rspec ./spec/features/admin/product_import_spec.rb:130

rspec ./spec/features/admin/customers_spec.rb:24
rspec ./spec/features/admin/enterprises/images_spec.rb:29
rspec ./spec/features/admin/enterprises/images_spec.rb:66
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2469

We can simply merge to master as all tests are passing with headless chrome!

#### What should we test?
The build should be green. It's a lot of changes under /spec and a change in an icon in app/views/admin/enterprises/form/_primary_details.html.haml. Maybe we should do a sanity check of the app.
 
#### Release notes
Changelog Category: Added
Major improvement of our test suite from PhantomJS to HeadlessChrome. This makes the tests more reliable and more real as the browser the tests are executed now is a lot more similar to modern browsers.

#### Documentation updates
I'll update https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-and-Rspec-Tips when this PR is merged.

#### Credits
Great dev team work!!! With @oeoeaio making the majority of the initial work and them everyone contributing a little to close this one.

### CODE REVIEW

**Comment by luisramos0** [comment]
Build took 40mins ❤️ 
I think we can leave codeclimate issues for after merging (I can fix it in a PR with regenarating the knapsack report).

**Comment by sauloperez** [comment]
screenshot from 2019-01-17 12-53-57

We can as well disable this rule.

**Comment by luisramos0** [comment]
I  resolved the conflict using GH. nice.

**Pull request merged**
