### PR TITLE
Move properties and product properties from spree_backend to OFN 

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Part of #4050

This moves properties and product properties from spree_backend to OFN. No change in functionality.

#### What should we test?
Make sure the following pages work correctly: general properties list in the product menu, product properties in product submenu and also validate enterprise properties can still be inherited from enterprise properties..

#### Release notes
Changelog Category: Changed
Imported views related to properties and product properties management from spree_backend to make OFN more independent of Spree.

### CODE REVIEW

**Comment by luisramos0** [comment]
yes, the first little step!!!!

**Comment by daniellemoorhead** [comment]
@JenRSmith is gonna test this on friday @RachL and @filipefurtad0 so leave it here for her 😄

**Comment by JenRSmith** [comment]
All tests passed. Testing notes here - https://docs.google.com/document/d/1zDT_JZZf-aAY2w_AByJ2zNe8t7ImD7Fi_HheZAfG8YY/edit#

**Comment by luisramos0** [comment]
great, thank you @JenRSmith 🎉

**Pull request merged**
