### PR TITLE
Fix Style/HashSyntax 12/13

### PR DESCRIPTION
**Pull request by macanudo527**
#### What? Why?

- Part of #11253 

This is a minor style change that was introduced with Rails 3.1. [More information here.](https://dev.to/baweaver/ruby-3-1-shorthand-hash-syntax-first-impressions-19op) 

This is a bundle of 30 files. 28 files remain.

#### What should we test?

This is just a simple style change, so shouldn't require extra testing.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1 or DFC)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Thanks for improving our code base !

**Comment by mkllnk** [comment]
Just to let you know, I have been holding off reviewing this because of:

- [x] #11479
- [ ] #11588

I'm assuming potential conflicts and it's easier to re-run the auto-correction than resolving merge conflicts.

**Review by mkllnk — APPROVED** [review]
Thank you!

I checked for a potential conflict with another open PR but it's all good. You may want to wait with your next PR though.

**Comment by macanudo527** [comment]
@mkllnk Thanks for the heads up. I'm a little bogged down trying to remove the Bogus/BogusSimple Gateways at the moment, so I'll busy myself with that.

**Pull request merged**
