### PR TITLE
Remove unused dependency

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #[the issue number this PR is related to]

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Nice, I was wondering about this the other day. There's some nasty monkey-patching of the built-in `Json` class that happens behind the scenes with the `oj` gem...

**Comment by luisramos0** [comment]
Theres just the concurrent checkout spec broken. So it looks like we can
remove this?

**Comment by Matt-Yorkley** [comment]
In theory the `oj` gem improves performance of rendering JSON (in some cases, and if it's configured correctly). We should switch to `fast_jsonapi` soon.

**Comment by luisramos0** [comment]
I dont understand how this could be used without any reference to it.
I'd vote remove as it looks like dead code.
What do you vote Matt? Remove or keep?

**Comment by Matt-Yorkley** [comment]
I have a feeling that just adding it in the gemfile means it silently monkey-patches the JSON module, but yeah I reckon we should remove it for now :+1:

**Review by Matt-Yorkley — APPROVED** [review]

**Review by andrewpbrett — APPROVED** [review]

**Comment by andrewpbrett** [comment]
Thanks @luisramos0!

**Pull request merged**
