### PR TITLE
Add missing indexes to spree_orders and spree_products

### LINKED ISSUE #4424: Add supplier_id index to spree_products table
### What we should change and why (this is tech debt)

We're missing a `supplier_id` index on the `spree_products` table. This index is commonly used and will result in sequential scans. It's a foreign key, and has high cardinality.

### Context

Looking into potential useful indexes for performance.

Example traces:

https://app.datadoghq.com/apm/resource/rails-postgres/postgres.query/3e58832d71271611?end=1572733957676&env=production&index=apm-search&paused=false&start=1570141957676
https://app.datadoghq.com/apm/resource/rails-postgres/postgres.query/79a87739d97ae77f?end=1572729769909&env=production&index=apm-search&paused=false&start=1570137769909
https://app.datadoghq.com/apm/resource/rails-postgres/postgres.query/8478cbff71034945?end=1572729762684&env=production&index=apm-search&paused=false&start=1570137762684

### LINKED ISSUE #5137: Add database index on `spree_orders.user_id`
### What we should change and why (this is tech debt)

It's very common to load orders of a user. But without an index on that column, that can be slow. Just counting the user_ids of orders landed in the top 10 of time consuming queries.

Query 9:
Screenshot from 2020-04-03 09-02-31

### Context

This came up reviewing #5133. We do have a foreign key from orders to users and that automatically indexes the `spree_users.id` but Postgres has no requirement on indexing the source of the foreign key: `spree_orders.user_id`

https://github.com/openfoodfoundation/openfoodnetwork/blob/445eb9f2870a867e0cd9f415404fa07cb3181be8/db/schema.rb#L573-L577

https://github.com/openfoodfoundation/openfoodnetwork/blob/445eb9f2870a867e0cd9f415404fa07cb3181be8/db/schema.rb#L1290

https://www.cybertec-postgresql.com/en/index-your-foreign-key/

### Impact and timeline

This should improve the performance in many queries and is very easy to fix. We should do it as soon as possible. There are probably more foreign keys that would benefit from indexing. There is a general issue for this: #3819

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #5137 
Closes #4424

Adds previously identified missing indexes to spree_orders and spree_products.

#### What should we test?

Improved query plans.

#### Release notes

Added database indexes on products and orders

Changelog Category: Added

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I also had a go with an automated missing indexes scan, using the [lol_dba](https://github.com/plentz/lol_dba) gem, and it recommended this (on top of the two indexes added here):

```ruby
class AddMissingIndexes < ActiveRecord::Migration
    def change
        add_index :column_preferences, :user_id
        add_index :coordinator_fees, [:enterprise_fee_id, :order_cycle_id]
        add_index :customers, :enterprise_id
        add_index :distributors_payment_methods, [:distributor_id, :payment_method_id]
        add_index :enterprise_groups_enterprises, [:enterprise_group_id, :enterprise_id]
        add_index :enterprise_groups_enterprises, [:enterprise_id, :group_id]
        add_index :exchanges, [:enterprise_id, :order_cycle_id]
        add_index :inventory_items, :enterprise_id
        add_index :inventory_items, :variant_id
        add_index :order_cycle_schedules, [:order_cycle_id, :schedule_id]
        add_index :order_cycles, :coordinator_id
        add_index :proxy_orders, :order_cycle_id
        add_index :spree_activators, [:id, :type]
        add_index :spree_addresses, :country_id
        add_index :spree_addresses, :state_id
        add_index :spree_adjustments, :originator_id
        add_index :spree_adjustments, [:adjustable_id, :adjustable_type]
        add_index :spree_adjustments, [:originator_id, :originator_type]
        add_index :spree_adjustments, [:source_id, :source_type]
        add_index :spree_assets, [:id, :type]
        add_index :spree_assets, [:viewable_id, :viewable_type]
        add_index :spree_calculators, [:calculable_id, :calculable_type]
        add_index :spree_calculators, [:id, :type]
        add_index :spree_inventory_units, :return_authorization_id
        add_index :spree_line_items, :tax_category_id
        add_index :spree_log_entries, [:source_id, :source_type]
        add_index :spree_option_values, :option_type_id
        add_index :spree_option_values_line_items, [:option_value_id, :spree/line_item_id]
        add_index :spree_option_values_variants, [:option_value_id, :spree/variant_id]
        add_index :spree_option_values_variants, [:spree/option_value_id, :variant_id]
        add_index :spree_orders, :bill_address_id
        add_index :spree_orders, :created_by_id
        add_index :spree_orders, :ship_address_id
        add_index :spree_payment_methods, :provider_id
        add_index :spree_payment_methods, [:id, :type]
        add_index :spree_payments, :payment_method_id
        add_index :spree_payments, [:source_id, :source_type]
        add_index :spree_product_option_types, :option_type_id
        add_index :spree_product_option_types, :product_id
        add_index :spree_product_properties, :property_id
        add_index :spree_products, :shipping_category_id
        add_index :spree_products, :tax_category_id
        add_index :spree_products_promotion_rules, [:product_id, :promotion_rule_id]
        add_index :spree_products_promotion_rules, [:promotion_rule_id, :spree/product_id]
        add_index :spree_promotion_action_line_items, :promotion_action_id
        add_index :spree_promotion_action_line_items, :variant_id
        add_index :spree_promotion_actions, :activator_id
        add_index :spree_promotion_actions, [:id, :type]
        add_index :spree_promotion_rules, :activator_id
        add_index :spree_promotion_rules, [:id, :type]
        add_index :spree_promotion_rules_users, [:promotion_rule_id, :user_id]
        add_index :spree_return_authorizations, :order_id
        add_index :spree_roles_users, [:spree/role_id, :user_id]
        add_index :spree_roles_users, [:spree_role_id, :user_id]
        add_index :spree_shipments, :address_id
        add_index :spree_shipments, :stock_location_id
        add_index :spree_shipping_methods_zones, [:shipping_method_id, :zone_id]
        add_index :spree_shipping_rates, :shipment_id
        add_index :spree_shipping_rates, :shipping_method_id
        add_index :spree_state_changes, :user_id
        add_index :spree_state_changes, [:stateful_id, :stateful_type]
        add_index :spree_states, :country_id
        add_index :spree_stock_locations, :country_id
        add_index :spree_stock_locations, :state_id
        add_index :spree_stock_movements, [:originator_id, :originator_type]
        add_index :spree_tax_rates, :tax_category_id
        add_index :spree_tax_rates, :zone_id
        add_index :spree_users, :bill_address_id
        add_index :spree_users, :ship_address_id
        add_index :spree_variants, [:spree/image_id, :spree/product_id]
        add_index :spree_zone_members, :zone_id
        add_index :spree_zone_members, [:zoneable_id, :zoneable_type]
        add_index :tag_rules, :enterprise_id
        add_index :tag_rules, [:id, :type]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :customer_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :exchange_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/billing_integration_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/bogu_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/bogus_simple_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/mig_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/pay_pal_express_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/pin_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/stripe_connect_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway/stripe_sca_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/gateway_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/payment_method/check_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/payment_method_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :spree/shipping_method_id]
        add_index :taggings, [:acts_as_taggable_on/tag_id, :variant_override_id]
        add_index :variant_overrides, :hub_id
        add_index :variant_overrides, :variant_id
    end
end
```

**Comment by luisramos0** [comment]
:-O
Adding indexes is not always the best approach, right?
Indexes take space (they are basically simplified tables maintained in parallel to the actual table. They make inserts slower.
Having said this I am sure some of these would be very beneficial! How do we choose?

**Comment by mkllnk** [comment]
Looking good. :+1: 

I tested on UK staging because there is a lot of data. I'm not very experienced in analysing database performance. So I hope this makes sense and proofs that this PR is an improvement.

Before deploying:
```
puts Spree::Order.where(user_id: 207078).explain
  Spree::Order Load (8.6ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = 207078
  EXPLAIN (0.7ms)  EXPLAIN SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = 207078
EXPLAIN for: SELECT "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."user_id" = 207078
                                                               QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using spree_orders_completed_at_user_id_created_by_id_created_at_idx on spree_orders  (cost=0.42..7661.20 rows=21 width=209)
   Index Cond: (user_id = 207078)
(2 rows)


puts Spree::Product.where(supplier_id: 1).explain
  Spree::Product Load (4.8ms)  SELECT "spree_products".* FROM "spree_products" WHERE "spree_products"."supplier_id" = 1 AND ("spree_products".deleted_at IS NULL)
  EXPLAIN (0.6ms)  EXPLAIN SELECT "spree_products".* FROM "spree_products" WHERE "spree_products"."supplier_id" = 1 AND ("spree_products".deleted_at IS NULL)
EXPLAIN for: SELECT "spree_products".* FROM "spree_products"  WHERE "spree_products"."supplier_id" = 1 AND ("spree_products".deleted_at IS NULL)
                            QUERY PLAN
------------------------------------------------------------------
 Seq Scan on spree_products  (cost=0.00..762.89 rows=5 width=290)
   Filter: ((deleted_at IS NULL) AND (supplier_id = 1))
(2 rows)
```

After the deploy:
```
puts Spree::Order.where(user_id: 207078).explain
  Spree::Order Load (2.4ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = 207078
  EXPLAIN (1.1ms)  EXPLAIN SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = 207078
EXPLAIN for: SELECT "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."user_id" = 207078
                                              QUERY PLAN
------------------------------------------------------------------------------------------------------
 Index Scan using index_spree_orders_on_user_id on spree_orders  (cost=0.42..64.03 rows=21 width=209)
   Index Cond: (user_id = 207078)
(2 rows)


puts Spree::Product.where(supplier_id: 1).explain
  Spree::Product Load (1.3ms)  SELECT "spree_products".* FROM "spree_products" WHERE "spree_products"."supplier_id" = 1 AND ("spree_products".deleted_at IS NULL)
  EXPLAIN (0.6ms)  EXPLAIN SELECT "spree_products".* FROM "spree_products" WHERE "spree_products"."supplier_id" = 1 AND ("spree_products".deleted_at IS NULL)
EXPLAIN for: SELECT "spree_products".* FROM "spree_products"  WHERE "spree_products"."supplier_id" = 1 AND ("spree_products".deleted_at IS NULL)
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on spree_products  (cost=4.34..30.10 rows=5 width=290)
   Recheck Cond: (supplier_id = 1)
   Filter: (deleted_at IS NULL)
   ->  Bitmap Index Scan on index_spree_products_on_supplier_id  (cost=0.00..4.34 rows=7 width=0)
         Index Cond: (supplier_id = 1)
(5 rows)
```

The key numbers:


Order | time | cost | index
-- | -- | -- | --
before | 8.6ms | 0.42..7661.20 | spree_orders_completed_at_user_id_created_by_id_created_at_idx
after | 2.4ms | 0.42..64.03 | index_spree_orders_on_user_id on spree_orders
  |   |   |  
Product | time | cost | index
before | 4.8ms | 0.00..762.89 | Seq Scan on spree_products
after | 1.3ms | 4.34..30.10 | index_spree_products_on_supplier_id

**Comment by luisramos0** [comment]
nice one Maikel, thanks!

**Pull request merged**
