### PR TITLE
Fix minor ordercyle selector layout regression

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Smallest PR ever; fixes a little regression that popped up recently in the shop page.

#### What should we test?

ordercycle selector doesn't have a weird gap at the bottom on the shop page.

#### Release notes

Fixed vertical positioning regression on ordercycle selector

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
**Before:**

Screenshot from 2020-10-21 17-04-39

**After:**

Screenshot from 2020-10-21 17-04-30

**Review by luisramos0 — APPROVED** [review]
Thanks Matt!

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley 
Let's add your quick-fix as well :+1: 

before staging:

image


after staging:
image

Looks good!

**Comment by Matt-Yorkley** [comment]
Its moved again! :see_no_evil:

**Comment by filipefurtad0** [comment]
There is still a bit missing... yeah.
I'll stage it again after your commit :+1:

**Comment by Matt-Yorkley** [comment]
Okay, it's corrected.

**Comment by filipefurtad0** [comment]
Humm, flaky spec? This PR doesn't relate to `tag_rules_spec.rb:14` in any way, so should be safe to stage, right?

**Review by luisramos0 — APPROVED** [review]

**Comment by luisramos0** [comment]
yes, tag_rules is super flaky right now...

**Comment by filipefurtad0** [comment]
Alright, now it looks perfect @Matt-Yorkley ,

Before:
image

After this PR:
image

Thumbs up :+1:

**Pull request merged**
