### PR TITLE
Double checkout

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Deletes `Spree::CheckoutController` :fire:  

#### What should we test?

Checkout with Paypal. Is there a way to test for Paypal where the payment fails?

#### Release notes

Removed duplicate Spree checkout controller.

Changelog Category: Technical changes

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]
yes, we can try this.
we need to test paypal and maybe try paypal error scenarios, at least that's what the code comment says.

**Comment by sauloperez** [comment]
> we need to test paypal and maybe try paypal error scenarios, at least that's what the code comment says.

yes, testing what the comment says is still true should suffice.

**Comment by Matt-Yorkley** [comment]
I added some more tests for the redirect behaviors. They're heavily mocked as we're not testing the provider methods :+1:

**Review by sauloperez — APPROVED** [review]
awesome! :metal:

**Comment by sauloperez** [comment]
pr-no-test?

**Comment by luisramos0** [comment]
I'd test paypal manually specifically some error scenarios.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

I'm not entirely sure if it is possible to test Paypal errors through the UI.

**i) It is possible to trigger an authentication error**, by incorrectly setting incorrect API credentials, when creating the payment method (in the section Provider Settings)

Attempting to checkout leads to

image

Which is expected, and allows the customer to choose another payment method.

**ii) It is possible to trigger an authorization error** - there is a "Refund" option for successful Paypal payments in the backoffice:

image

Clicking "Refund":

image


**iii) Paypal** does seem to provide an array of options for **negative testing**:


I've created two payment methods in **staging-AU**:
/admin/payment_methods/434/edit -> negative testing is enabled
/admin/payment_methods/435/edit -> negative testing is disabled

From the link above, I think it might be possible to test for specific responses via cURL / API requests. I have to admin I tried this for a while but seem not to manage to get the response we're after (I'm guessing I was just using the wrong syntax). I could not find a way to do this via the UI.

**iv) Setting-up and Checking-out** (regression tests)

All good and as usual here.

**v) For a given Sandbox user-account**: updated the balance for that customer, setting to a small value: 

image

Then, placed an order on OFN, authenticating as that user. It did not trigger any sort of payment error; order confirmation was issued, and the order appears in the "paid" state:

image
 

**Summary**
I found no regressions. Looks good to merge but before that, maybe we'd want to test some error messages, i.e., further exploring point iii)
Also, it seems that point ii) is a bug; I'm wondering if customers see this button as well - should we create an issue for this, and enable refunds on Paypal?

**Comment by Matt-Yorkley** [comment]
Thanks @filipefurtad0 !

I did some extra dev-tests here that involved manually changing the code to ensure we hit these error redirects, and they are working as expected. I think it's okay with the additional test coverage that's added here.

That _refunds not working nicely via Paypal_ issue (ii) is pre-existing right? Or not?

**Comment by sigmundpetersen** [comment]
There is #4416 on partial Paypal refunds. 
It's a prioritized papercut

**Comment by filipefurtad0** [comment]
Thanks for pointing this our @sigmundpetersen - it's pre-existing and documented :+1: no need for a new issue here. 

> I did some extra dev-tests here that involved manually changing the code to ensure we hit these error redirects, and they are working as expected

Great, so I guess we're all good here @Matt-Yorkley - let's move this forward.

**Pull request merged**
