### PR TITLE
Spree2 fix test line items

### LINKED ISSUE #2577: [Spree Upgrade] Fix tests with error "undefined method `stock_location' for nil:NilClass" by defining a shipment in test line_items
Follow up from #2573 by fixing all occurrences of:
undefined method `stock_location' for nil:NilClass
by providing a target_shipment in the test line_items created.

This error is found in several specs:

- [x]  ... orders_and_fulfillments_report_spec
- [x] ... bulk_order_management_spec

- [x] spec/features/admin/reports_spec.rb
- [x] spec/controllers/spree/admin/orders_controller_spec.rb
- [x] spec/lib/open_food_network/packing_report_spec.rb
- [x] spec/controllers/spree/admin/line_items_controller_spec.rb
- [x] spec/jobs/update_billable_periods_spec.rb
- [x] spec/lib/open_food_network/bulk_coop_report_spec.rb
- [x] spec/controllers/spree/api/line_items_controller_spec.rb
- [x] spec/lib/open_food_network/order_and_distributor_report_spec.rb

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2577 

See issue for details.

#### What should we test?
More passing specs in ofn2 branch.

#### Release notes
No release notes.

#### How is this related to the Spree upgrade?
This is part of the spree upgrade. Adapting test specs to spree2.

### CODE REVIEW

**Comment by luisramos0** [comment]
Note to help the review: all the changes in this PR are the same as the change in #2574

**Comment by mkllnk** [comment]
If that is the most common pattern, wouldn't it make sense to change the factory to create a shipment by default?

**Comment by luisramos0** [comment]
As discussed, I have implemented a new factory on the ofn side called line_item_with_shipment.
Looks much better, thanks for the suggestion!

Commit with the factory here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/2578/commits/8a6103b52033b48f49b4d23298451ad66d6d4a82

**Comment by luisramos0** [comment]
I am happy to squash these commits into 1 before merging.

**Comment by luisramos0** [comment]
ok, thanks @mkllnk . I've squashed all commits except the removal of the monkeypatchs :-)

**Comment by luisramos0** [comment]
I just rebased this PR to resolve conflicts.

**Comment by luisramos0** [comment]
ah, yes, thanks for the link @sauloperez !
This is ready to be merged I believe.

**Comment by sigmundpetersen** [comment]
Okay, thanks for the update @mkllnk . Yeah we could put the `no-test` label on SpreeUpgrade PRs

**Pull request merged**
