### PR TITLE
content_spec.rb improvement

### LINKED ISSUE #4118: Add tests for "Footer and External Links" dynamic content
### What we should change and why (this is tech debt)

Automate the tests mentioned in https://github.com/openfoodfoundation/openfoodnetwork/pull/3389#issuecomment-457794935 as feature specs or view specs so that next time @RachL does waste precious time doing something that a computer would do faster and more reliably.  

### Context

This came up in https://github.com/openfoodfoundation/openfoodnetwork/pull/4093#issuecomment-516369849

### Impact and timeline

It should be pretty straightforward to add and it'd improve our confidence when updating Redcarpet.

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #4118.

Moves content_spec.rb into /configuration and adds an href string, increasing Redcarpet test coverage

Inserting a string with special characters and an assertion to check whether the conversion from backoffice to the homepage works correctly, thus replicating the manual tests proposed [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/3389#issuecomment-457794935), to check a Redcarpet upgrade.

#### What should we test?

Green build.

#### Release notes

The following changes are proposed:

- moving the file to spec/features/admin/configuration/content_spec.rb
- adding a string and the respective assertion to make sure Redcarpet makes the conversion of special characters correctly
- some minor refactoring: replacing ' for ", where appropriate; replaced feature -> describe and scenario -> it - according to previous comments
- removed a Rubocop offense concerning the attach_file method, #{Rails.root} -> Rails.root.join
 

Changelog Category: Added

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]
Filipe, well done on what I think will be your first successful PR :tada:  It's really great you are taking the time to learn how to do this :muscle: 

Just one comment: this PR is quite impossible to review on github
If you look here: 
https://github.com/openfoodfoundation/openfoodnetwork/pull/6110/files
There's no way to tell what have you changed (I had to copy the file to my local envinronment and compare to the file I have there). The pattern you should watch for is the word "and" on your commit message, if there is an "and" you should probably split the commit in two commits.
To avoid this problem we recommend you make incremental commits, in this case the ideal commit history would be:
- commit 1 - move file to /configuration - commit message "Move file..."
- commit 2 - replace ' with " - commit message "Replace..."
- commit 3 - add special character string - commit message "Increase redcarpet test coverage...

**Comment by luisramos0** [comment]
The spec that is breaking the build is breaking master branch so it's not a problem with this PR :+1: 
I am adding the pr-no-test as this is only changing code in /spec :+1:

**Comment by filipefurtad0** [comment]
Thanks so much for the support words @luisramos0 :pray: 

I get your point... I saw this on the good practices (in wiki), splitting PRs in smaller commits, but I was not sure where to apply it...  Now I see it greatly affects the review process, thanks. Is it best that I close this PR and submit a fresh one, following those steps? 

The spec `order_checkout_restart_spec.rb` is failing both in my local system and in master. I thought of trying to investigate what is failing manually but I'm not sure it's the right approach. When a spec repeatedly fails, should an issue be opened on that regard?

**Comment by luisramos0** [comment]
>>> Is it best that I close this PR and submit a fresh one, following those steps?

I dont think you need to worry this time! I think I am just going to merge this PR now with one review (we have doing that for simple PRs like this one).

when the master build is broken like now we need to stop everything and fix it (I will do that tomorrow first thing). It's a big thing in agile software development. You can read about it in many many places: https://dzone.com/articles/fix-broken-builds-immediately

**Comment by luisramos0** [comment]
Hi @filipefurtad0 fyi the release notes is a one liner that lands here: https://github.com/openfoodfoundation/openfoodnetwork/releases
In this case, what you have written in release notes is more appropriate for the What/Why section.
This are the release notes I am adding for this PR:
"Improve spec and test coverage in the backoffice content settings page."

**Comment by luisramos0** [comment]
I am suggesting we improve the notes so we get better release notes from new contributors:
https://github.com/openfoodfoundation/openfoodnetwork/pull/6150

**Comment by filipefurtad0** [comment]
Hey Luis ,
That makes sense. I'll be sure to follow those guidelines :+1:
Thank you!

**Pull request merged**
