### PR TITLE
Fix #6090 (Inventory import fails for products with units other than "g")

### LINKED ISSUE #6090: Inventory import fails for products with units other than "g"
## Description

Importing existing products directly to the inventory is failing with the error "Product not found in the database". This does not occur if the product has weight units `g` but fails, for example, for `kg`, and as well to with the newly introduced `lb` and `oz` units.

This was spotted during a regression test to PR #6043, but it was not introduced by this PR.

## Expected Behavior

It should be possible to import products to the inventory with other units other than `g`.

## Actual Behaviour

Product import for other units such as (`kg`, `oz`, `lb`) should be possible. Attempting to do so shows the error "Product not found on the database".  

## Steps to Reproduce

1.a) Create a product with weight units g (manually or through product import)
2.a) Create a file to import the newly created product to the inventory. Use it on the product import section. 

or

login as Superadmin in staging-uk:

1.b) copy the content below to a .csv file and use it to import a product to the product list

Product Import file
```
producer,sku,name,display_name,category,description,units,unit_type,variant_unit_name,price,on_hand,available_on,on_demand,shipping_category,tax_category
Kurkuma Farm,1,import_prod,import,Products,,1,g,,1,,,1,Default,Zero rated
```
2.b) copy the content below to a .csv file and use it to import a product to the inventory

Inventory Import file
```
producer,distributor,name,display_name,variant_unit_name,sku,units,unit_type,price,on_hand,on_demand
Kurkuma Farm,Kurkuma Farm,import_prod,import,,1,1,g,1,,1
```

3. This should work fine.
4. Delete the newly created product
4. Now repeat the procedures above after replace the `g` by `kg` in the files above. You should observe the bug in point 3 (see pic below).  

## Workaround

Manually adding/updating products to/in the inventory.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: Firefox 80
* Browser name and version: Desktop Ubuntu 20.04
* Operating System and version (desktop or mobile): v.3.2.8

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6090 

The entry_validator was interpreting the entry's `unit_value` as a string, e.g. `"1"`, so if the existing variant's `unit_scale` was anything other than 1 (e.g. 1000 for a product in kg), we did `"1" * 1000` and got `"11111111111111....."` :)

#### What should we test?
See issue for test procedure (thanks @filipefurtad0! 😁). We could also test one in lbs while we're at it. 

#### Release notes
Bug fix: inventory import failed for units other than "g" but now works for all valid units.

Changelog Category: Fixed

#### Documentation updates

### CODE REVIEW

**Comment by andrewpbrett** [comment]
I don't see any existing tests for this sort of case. Am I maybe not looking in the right place, or do we rely on manual testing for inventory import?

**Review by luisramos0 — COMMENTED** [review]
The tests are at
spec/features/admin/product_import_spec.rb
and
spec/models/product_import

Could you please add a simple test (unit or feature, whatever is easier for you) to validate this case?
Actually maybe we should start the spec/models/product_import/entry_validator_spec.rb and add a unit test for this case.

BTW, there's some work going on in PI, I have moved one service to engines/catalog/app/services/catalog/product_import/products_reset_strategy.rb
Thee plan is to move all the services (these are not models) in app/models/product_import to engines/catalog/app/services/catalog/product_import/

**Comment by andrewpbrett** [comment]
Adding a feature spec was faster for me; I can add the unit test as well. Or maybe we could wait to add the unit test until we migrate them to services if the feature spec is sufficient for now.

**Review by luisramos0 — APPROVED** [review]
ok, that's good, thanks!

FYI we have very good test coverage in OFN but our test pyramid is severely inverted: a lot of feature tests, quite a lot of controller tests and not so many unit tests. We should work in the direction of more unit tests verifying all sorts of behavior and then have simple mostly happy path feature tests. This way we can have shorter builds. Not a 25 minutes build as we have.

**Comment by andrewpbrett** [comment]
Ah right, thanks @luisramos0 - @sauloperez mentioned this to me about the inverted pyramid shape of the test. When I wrote the feature spec I did the easier thing and wasn't thinking of the build time. 

I wrote a unit test now too. I was unsure of a few OFN conventions around doubles and stubbing out unrelated methods. If people think it's sufficient to just have that unit test I can revert the feature spec commit since it will just make the build take longer.

**Review by sauloperez — APPROVED** [review]
I think is fine having both kinds of tests for this particular case.

**Comment by sigmundpetersen** [comment]
Build is failing though https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-6094/builds/3
So I don't think this is Test Ready yet.

Semaphore report doesn't show on GH issue, I don't know why, sometimes it doesn't.

**Comment by andrewpbrett** [comment]
I think that's because I did a force push. Could someone rerun the build with the latest code? That spec is passing locally for be so I think it should be fixed.

**Comment by luisramos0** [comment]
Green build, Test Ready :+1: 

Andy, could be related to force pushes yes, but not all force pushes, I use it all the time and generally the build is triggered.

**Comment by sigmundpetersen** [comment]
I'm sorry but where did you see a green build @luisramos0 ? 🙂

**Comment by luisramos0** [comment]
:face_with_head_bandage: I was fooled by the green PR:
image

Build 5 did even start for some reason, I rerunning it now here:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-6094/builds/6

**Comment by luisramos0** [comment]
For some reason semaphore didnt pick up the force push so it is still looking at previous commit history:
image

Andy, I think you will need to force push again with some small change so that semaphore picks it up.

**Comment by luisramos0** [comment]
I am moving to In Dev until we fix this problem.

**Comment by andrewpbrett** [comment]
Sorry about all the confusion! I squashed and pushed a trivial change and now it looks like Semaphore picked up the change (even though I did a force again). I've seen force pushes picked up before as well. I think the issue this time may have been that I did the force push while the prior build was still running (but that's just a guess). I'll move it back to test ready if the build turns back to green.

**Comment by filipefurtad0** [comment]
Awesome @andrewpbrett !

Thanks for addressing this one so quickly :raised_hands: 

I tried the import tool for products and inventory, with the units:
- g
- kg
- lb
- oz

Using the templates described in the issue I was able to populate the product list with these products:

image

And after that, the inventory list - which shows the issue is correctly addressed:

image

Awesome, thanks!
Ready to go.

**Pull request merged**
