### PR TITLE
Add tooltips in products bulk edit page

### LINKED ISSUE #1804: Add "tooltips" on main bulk edit product page
To improve the ux, after some users suggested it (after I explained them how to proceed as they didn't find alone), I propose to add some "tooltips" ("infobulles" in french, not sure about the translation) as it is done here on the "order" page to edit order or capture payments:
illustration

on the bulk edit page here:
illustration3

and of course the tooltip text needs to be translatable but that's obvious now ;-)

### PR DESCRIPTION
**Pull request by ltrls**
Fixes #1804 
If someone knows a way to translate [this tooltip that has an Angular interpolation in it](https://github.com/ltrls/openfoodnetwork/blob/9b2d9303f29f0fad26ca43de9b8faf18b64e3805/app/views/spree/admin/products/bulk_edit/_products_variant.html.haml#L28) please let me know!

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@oeoeaio ☝️

**Comment by ltrls** [comment]
> If someone knows a way to translate this tooltip that has an Angular interpolation in it please let me know!
found it! the key I used is pretty long though but I'd be happy to follow suggestions for something else.

**Comment by sstead** [comment]
Testing notes:

These tooltips are correct:
image

The Inventory override tooltip is missing translations:
image

One tooltip requested in 1804 hasn't been done:
image

**Comment by ltrls** [comment]
The missing translation is weird as it works well in my development environmnent. Could it be that you need to recompile the assets so the new translation key is injected in the javascript file?

**Comment by ltrls** [comment]
And I don't get why there's a failing test, it has nothing to do with changes in this PR oO

**Comment by oeoeaio** [comment]
Definitely something weird going on. It works fine on my local environment too, but on staging2 the javascript translations look wrong (they don't include `variant_has_n_translations` at all). Maybe we're not generating the js translations properly on our staging server?

**Comment by myriamboure** [comment]
Testing the new tooltip : working find
tooltip

We still have the issue with the missing translation, but it seems it's not connected with this PR. Can we move this one forward and maybe open another issue if there is some issue with JS & staging ?

**Comment by daniellemoorhead** [comment]
>We still have the issue with the missing translation, but it seems it's not connected with this PR. Can we move this one forward and maybe open another issue if there is some issue with JS & staging ?

Sorry @myriamboure I'm not sure what you mean by this. Did you want us to stage it in Australia again and have Sally have another round of testing? What did you mean by JS & staging?

**Comment by myriamboure** [comment]
@daniellemoorhead I don't think it needs more testing, I just tested the missing tooltip on french staging so I guess it's enough ? About JS & staging see Rob's comment just above, it seems the missing translation is connected to the way js translations are generated on our staging servers, not connected to that PR, so it seems to me we can merge and open a new issue for that if needs be ?

**Comment by daniellemoorhead** [comment]
Will leave it to you for merging @oeoeaio :-)

**Comment by daniellemoorhead** [comment]
@myriamboure unfortunately this can't be merged until the i18n-js issue is fixed (affecting #1820 as well). Hopefully @oeoeaio and @mkllnk can figure out what's wrong and fix it so that these can both go through in the next release (which includes the Stripe feature). Cheers!

**Comment by daniellemoorhead** [comment]
@oeoeaio has the i18n-js issue blocking this PR been resolved? Can we get this one through once the conflict has been resolved?

**Comment by myriamboure** [comment]
@daniellemoorhead @oeoeaio @ltrls  do we need to solve the conflict on our side ? Or is it linked to something else that you are dealing with in Aus ? Thanks !

**Comment by daniellemoorhead** [comment]
>@daniellemoorhead @oeoeaio @ltrls do we need to solve the conflict on our side ? Or is it linked to something else that you are dealing with in Aus ? Thanks !

It would be worth checking on your end if the conflict can be resolved now, given it's been a while since it was last checked. I'm sitting next to @oeoeaio but I don't want to bug him because he's 1 hour away from having subscriptions ready to be staged and tested by Sally. So it would be great if you can check it again on your end and see if the conflict can be removed. Once subs is done Rob will have much more time to focus on this stuff (and split payments solution design too).

**Comment by myriamboure** [comment]
@ltrls can you have a quick look at the conflict please ?

**Comment by ltrls** [comment]
There it is

**Comment by myriamboure** [comment]
Conflict resolved on our side @daniellemoorhead ;-) Ready for @oeoeaio to merge if no more blocking !

**Comment by daniellemoorhead** [comment]
Given @oeoeaio has approved this @myriamboure I assume it's ready for testing? Or have you tested it already? There are no testing notes so I can't tell, and I see that @sigmundpetersen moved the PR from Code Review to Ready to Go, but it didn't seem to go through the testing steps. 

If it has been tested can you please confirm this? 

If it hasn't been tested did you want Sally to test it next Wednesday or can you test it in France before then?

**Comment by oeoeaio** [comment]
Working fine for me on staging... 👍 

New Variant:
screen shot 2017-11-23 at 12 08 00 pm

n Overrides:
screen shot 2017-11-23 at 12 07 35 pm

Action Labels:
screen shot 2017-11-23 at 12 08 40 pm

**Comment by oeoeaio** [comment]
Working in production too:
screen shot 2017-11-23 at 12 17 53 pm

**Pull request merged**
