### PR TITLE
Translate ResetPasswordConfirmation mail

### PR DESCRIPTION
**Pull request by pacodelaluna**

### CODE REVIEW

**Comment by myriamboure** [comment]
@daniellemoorhead ping you here, no emergency to be merged for Friday (great if it can of course!), @pacodelaluna made the "reset password" message translatable ;-) Thanks for that François!

**Comment by daniellemoorhead** [comment]
Hey there, assuming this also isn't linked to an issue? We've got a lot to get through for 1.8.9 so going to put this into 1.8.10 which should be out in the next couple of weeks. Cheers!

**Comment by myriamboure** [comment]
It is linked to that issue @daniellemoorhead : https://github.com/openfoodfoundation/openfoodnetwork/issues/1039

**Comment by daniellemoorhead** [comment]
> It is linked to that issue @daniellemoorhead : #1039

Hey @myriamboure do you see the section above this comment box that shows which issue the issue the PR is linked to with a Disconnect button on the right? I'm not sure that this shows up for you, but it's where you link the issues so that they display together in Zenhub 😄

**Comment by myriamboure** [comment]
Interesting @daniellemoorhead ! I don't see it on Firefox (which I already use) but it shows up in Chrome ! I guess that also because Zenhub only works in Chrome... I guess I'll have to use Chrome for Github related work ;-) I link it now!

**Comment by daniellemoorhead** [comment]
> I guess I'll have to use Chrome for Github related work ;-)

So interesting, what works and what doesn't in each browser! I really wish all the zenhub features were part of github to make it easier for everyone 😄

**Comment by mkllnk** [comment]
I implemented my feedback in #1548. But since our user tester is not working today, I won't merge it. Are you happy with my changes? If yes, I schedule it for next Wednesday. Thank you.

**Comment by mkllnk** [comment]
Merged in #1548.

**Pull request closed without merging**
