### PR TITLE
Update from address in notification emails

### PR DESCRIPTION
**Pull request by lin-d-hop**
Quick update to the 'from' email in producer order summary emails: change to from enterprise instead of from instance.

### CODE REVIEW

**Comment by lin-d-hop** [comment]
@oeoeaio Would you merge if happy?

**Comment by daniellemoorhead** [comment]
@lin-d-hop going to get @mkllnk to look at this rather than @oeoeaio who is busy up to eyeballs with other UK stuff :)

**Comment by mkllnk** [comment]
Is the coordinator triggering that email?

If yes, do we still need the reply-to field?

**Comment by lin-d-hop** [comment]
Good thinking @mkllnk :-)

**Comment by sstead** [comment]
Hi @lin-d-hop 
I couldn't see the desired changes when I tested this today. In my inbox, the 'notify producers' email was still from 'admin@ofw..' instead of from the enterprise (see below)...

image

If I clicked reply to the older email, it would be addresed to the hub's coordinator. If I clicked reply in staging, it was now being addressed to admin@ofw.

Maikel said it could be something at our end that's preventing your change from showing. Or perhaps I don't understand what should be changed?

**Comment by lin-d-hop** [comment]
Hi @sstead 
Totally confused as to how that change hasn't worked.
You understand the change correctly.
Shall I test on our staging server and see what happens on our end?

**Comment by mkllnk** [comment]
@lin-d-hop This confused me a lot as well. But I have two ideas what it might be.

1. Our mail method has a from address. The spree interface says, "Send all mails as from the following address." It could be that spree overrides the from address. But I couldn't find that in the code.

2. We are using Gmail to send our emails. That is like a personal email account. It might be that Gmail is changing the from address to the logged in user to prevent fraud.

If it's Spree overriding the address, that can be an important feature, because some email gateways accept only certain pre-defined email addresses. An email from a random coordinator would be rejected. If this pull request would work, it could actually break sending emails if you use authsmtp.com with restricted sender addresses.

If we want to support sending those emails from user email addresses, we need that as an optional feature that can be turned off. Sorry, I didn't think of all that when I first looked at your pull request. But now I think we can't merge it in the current form.

**Comment by lin-d-hop** [comment]
@mkllnk 
I deployed this to UK staging to test whether there was an unknown place in Spree this is overwritten or if it is gmail.

I know that to use gmail as an smtp server you have to overwrite the from address so suspected this was likely the cause.
Testing on UK staging (we use sendgrid) the email came through fine and dandy with the from address updated.

So I think we go with making this an optional change in the Mail Methods panel, with a note that this might be overriden by some SMTP servers. Will update now in #1025

**Comment by mkllnk** [comment]
Sounds good. Ping me once that's done.

**Comment by daniellemoorhead** [comment]
Removing the Aus Review label on this till you're ready for us to look at it again @lin-d-hop :)

**Comment by daniellemoorhead** [comment]
---Doing a PR Cleanup---

@lin-d-hop thoughts on what to do with this PR? Was it replaced by #1203 as a fix for #1025 and so can be closed?

**Comment by lin-d-hop** [comment]
Closing this PR as this is far too simple an implementation for what we actually need

**Pull request closed without merging**
