### PR TITLE
Rails 5.2 add T&Cs helper

### LINKED ISSUE #7091: [Rails 5.2] Undefined helper methods
There's quite a few like this:
```
Check out with Stripe using Stripe SCA with a logged in user saving a card and re-using it allows saving a card and re-using it
       Failure/Error: super
       
       ActionView::Template::Error:
         undefined method `terms_and_conditions_activated?' for #<#<Class:0x00007f192b29c278>:0x00007f1920b0d390>
       # ./app/helpers/application_helper.rb:20:in `method_missing'
       # ./app/views/checkout/_terms_and_conditions.html.haml:1:in `_app_views_checkout__terms_and_conditions_html_haml___3882455399943719169_69872954490380'
       # ./app/views/checkout/_form.html.haml:18:in `block in _app_views_checkout__form_html_haml__1664303948059702347_69872956121000'
       # ./app/views/checkout/_form.html.haml:6:in `_app_views_checkout__form_html_haml__1664303948059702347_69872956121000'
       # ./app/views/checkout/edit.html.haml:32:in `_app_views_checkout_edit_html_haml__2217575113360240181_69872949687160'
       # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
       # ------------------
       # --- Caused by: ---
       # NoMethodError:
       #   undefined method `terms_and_conditions_activated?' for #<#<Class:0x00007f192b29c278>:0x00007f1920b0d390>
       #   ./app/helpers/application_helper.rb:20:in `method_missing'
```

Rails 5.2 has changed the way helpers are auto-loaded. I made a rough start on addressing this in [this commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/d64ae9584ae5013d0ab252a71593f1f072cead76) which fixed the majority of the related errors, but not all of them.

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Continues #7091

Adding checkout helper to checkout controller also fixes lots of specs related to undefined method `display_checkout_subtotal'

#### What should we test?
Green build.

#### Release notes

Changelog Category: Technical changes
Adapt code to rails 5.2

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by luisramos0** [comment]
rebased :+1:

**Comment by luisramos0** [comment]
I have moved this to master, I think this should work in master.

**Review by mkllnk — APPROVED** [review]
Looking good.

**Comment by andrewpbrett** [comment]
The semaphore build just has the embedded shopfront spec failing, this should be good to go.

**Pull request merged**
