### PR TITLE
Fix browser caching of updated icon font

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Simple fix for the updated OFN icon font not showing the new icon due to browser caching. Renamed the font files with "v2" appended, and updated the CSS font import rules.

#### What should we test?

The icon font looks ok.

### CODE REVIEW

**Comment by myriamboure** [comment]
@Matt-Yorkley is there an issue open for that? Couldn't find it. Else please can you open one or explain me in non-tech terms what you did so that I can create the issue? Thanks ;-)

**Comment by daniellemoorhead** [comment]
All good @myriamboure, I don't think this needs an issue. It's just a `tech debt` thing and doesn't deserve the energy needed to create the issue.

@Matt-Yorkley can you please add before and after screenshots so that we know what to look for when testing pls? #apicturepaintsathousandwords

**Comment by Matt-Yorkley** [comment]
The globe icon should show up without display issues, especially in browsers that cached the previous version of the icon font. It's also an example of what to do next time the icon font is updated, in order to not run in to the same issue.

screenshot from 2018-03-02 19-09-38

**Comment by daniellemoorhead** [comment]
@enricostano @sauloperez @mkllnk @oeoeaio @KeirOsborn @HugsDaniel could we get a review on this please? Been sitting in Code Review for two weeks...

giphy

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley do you need front end testing for this PR or would you be able to do it? If you want Myriam or Sally to look at it can you add screenshots so they know what to look for?

**Comment by Matt-Yorkley** [comment]
There's not much to test @daniellemoorhead

**Comment by myriamboure** [comment]
Ok so I put as ready to go, please mergers check if you agree that it can be merged without test, sounds logical to me given previous discussions.

**Pull request merged**
