### PR TITLE
Try out removing RSpec retry

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

WIP. I want to check CI's report.

Let's see if it makes any difference or if it simply slows down our test
suite a lot.

My hypothesis? chances are that what failed once will also fail three times so don't waste time.

### CODE REVIEW

**Comment by sauloperez** [comment]
In the first attempt only a spec failed due to https://github.com/openfoodfoundation/openfoodnetwork/blob/d88be202a6248c6b93e8330a26081f79854f3498/spec/support/delayed_job_helper.rb#L63

Check https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3272/builds/1

**Comment by sauloperez** [comment]
Nice! second attempt and still the same failure due to a non-initialized var! Check https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3272/builds/2

**Comment by sauloperez** [comment]
Weird. I tried commenting out the code that enqueues the job as the test was passing but then I don't see the failure above. Just the right error message.

**Comment by luisramos0** [comment]
that checkout_spec is failing very regularly in the 2-0 build...

**Comment by sauloperez** [comment]
With the exact same failure? If so, we can take a closer look

**Comment by sauloperez** [comment]
I've seen it fail again in https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/386

**Comment by sigmundpetersen** [comment]
Same test failing often against master also. 3 of 4 builds failing here https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3302/builds/4

We should prioritize this

**Comment by sauloperez** [comment]
Yep, I'll fix this test here but I'd like to finish #3254, which is nearly done.

**Comment by daniellemoorhead** [comment]
#3254 is merged @sauloperez - do you now want to sort this issue out, or move it back to `Dev Ready` till you have time to focus on it again?

#toottoot

**Comment by sauloperez** [comment]
I'll close it until I manage to have some room for it.

**Pull request closed without merging**
