### PR TITLE
Upgrade test dependencies

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

This PR upgrades a bunch of test gems that are out of date (some of them quite a lot). Our Gemfile is suffering from serious abandonment and upgrading these gems is the easiest thing we can do, which will already bring benefits such as performance.

#### What should we test?

The test suite should keep green.

#### Release notes

Upgraded gems used in testing

#### Full list of gems

- [x] Rspec rails
- [x] Rspec retry
- [x] Timecop
- [ ] Webmock
- [x] Letter opener
- [x] knapsack
- [x] Shoulda matchers
- [x] Capybara
- [ ] Poltergeist
- [x] Json spec
- [ ] DatabaseCleaner

### CODE REVIEW

**Comment by sauloperez** [comment]
Looks like `DatabaseCleaner` will require some care.

**Comment by enricostano** [comment]
> Looks like DatabaseCleaner will require need some care.

Should we move DatabaseCleaner to another issue/PR? Or it's not that bad?

**Comment by sauloperez** [comment]
I don't how bad it is, but it definitely looks like we need to spend time digging in the documentation. I'll skip so that we can merge this as soon as it gets :green_apple: .

**Comment by sauloperez** [comment]
:scream: 

From the CI job:
```
WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST https://api.stripe.com/v1/charges
```

**Comment by sauloperez** [comment]
So finally I left webmock and poltergeist out of the upgrade as they require us to fix some specs. I'll create two new issues so this can be done by anyone later on. As it is now is already a win.

**Comment by sauloperez** [comment]
👉 https://github.com/openfoodfoundation/openfoodnetwork/issues/2144, https://github.com/openfoodfoundation/openfoodnetwork/issues/2145, https://github.com/openfoodfoundation/openfoodnetwork/issues/2146

**Pull request merged**
