### PR TITLE
Modify English tool tip text in yml file

### LINKED ISSUE #1848: One tooltip is off the page on OC edit page
Updated by Myriam 21.05.2018

## Description
One tooltip on order cycle edit page / "advance settings" can't be seen

## Expected Behavior
Tooltip can be read properly

## Actual Behavior
Tooltip can't be seen (Myriam just retested in 13inch screen for instance, so "regular" screen)
image

## Steps to Reproduce
1. You need to have one order cycle created already, then click on "edit" 
2. Click on "advance settings" button below the main menu
3. On this advance setting zone there is a tooltip below "choose products from", this tooltip is on one line only an can't be read properly.

## Context
Retesting to clean and specify old issues.

## Severity
S5

## Your Environment
PC, Aus production (+ French production), Chrome

## Possible Fix
Display tooltip on two lines?

### PR DESCRIPTION
**Pull request by Ecksi**
#### What? Why?

Closes #1848

Before:
before img

After:
after img

Attempted to edit the styling properties of PowerTip but current value used for positioning is `smartPlacement: true` which is supposed to keep the tooltip within the viewport. We believe the text of the tooltip being a long continual string is causing the issue. We decided to shorten the verbiage of the tooltip to allow PowerTip to better handle the placement. Styling still isn't ideal but we believe this is a decent fix without rework of the PowerTip implementation.

As our only available language in our group is English we only applied the shortened tooltip text to the English yml files. We did not want to provide incorrect translations, but we recommend the other language tooltips be changed as well.

#### What should we test?

These changes only modify display text, the test suite we ran had no broken tests.

### CODE REVIEW

**Comment by sauloperez** [comment]
Thanks for tackling the issue but there's something that needs to be changed to merge it. As described in [config/locales/en.yml](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml#L1-L54), all locales except the default one, `en`, are meant to be changed through [Transifex](https://www.transifex.com/), where non-devs keep the copies up to date. Check out that first file for more details.

The [i18n](https://github.com/openfoodfoundation/openfoodnetwork/wiki/i18n) wiki page will also be of help and don't hesitate to ask anything.

@sigmundpetersen @mkllnk do we know who's in charge of the English translations? I have no idea. I have enough with Spanish and Catalan :trollface:

**Comment by mkllnk** [comment]
No, I don't know either. A while ago I started a list in the community forum: https://community.openfoodnetwork.org/t/localisation-ofn-in-your-language/397 But we should probably move that to the wiki. What do you think?

We should also update the documentation in the source file: https://github.com/openfoodfoundation/openfoodnetwork/blob/deb04c3075e35a1d839b58206a5363dd99e1403d/config/locales/en.yml#L1-L54

**Comment by sauloperez** [comment]
@kristinalim your recently acquired knowledge might be useful here. You just went through this, right?

**Comment by kristinalim** [comment]
To be honest, I completely missed the documentation in `en.yml`. I think I've developed a habit of ignoring the comments there, because it's usually just the default instructions from Rails app setup. Also, new contributors who aim to update translations for other locales might not see these notes.

As for the wiki, I read some pages there, but I treated `CONTRIBUTING.md`, and pages linked, as a _sufficient_ guide to get started.

In addition to #2447, I think these would help:

* In `CONTRIBUTING.md`, mention that translations other than "en" are managed on Transifex and provide a link to the wiki page.
* In the wiki, move the "i18n" from "Specific features" to "Contributing".
* In the wiki, change the sidebar link to the "i18n" page to "Internationalization (i18n)".

**Comment by sauloperez** [comment]
Thanks a lot for the feedback @kristinalim ! that sounds great!

**Comment by kristinalim** [comment]
@mkllnk Got it! I submitted #2466, which adds a new "Internationalisation (i18n)" section in `CONTRIBUTING.md`. This has already been merged. Thanks!

**Comment by myriamboure** [comment]
Ok so I guess now that you get the process it's back to you @kristinalim ?

**Comment by mkllnk** [comment]
We haven't heard from @Ecksi since opening the pull request. It may have been a one-shot contribution. Does somebody else want to pick it up or should we close it and wait for another contributor?

**Comment by myriamboure** [comment]
Oh sorry I didn't read carefully I thought @kristinalim was working on it ;-) Sorry for the confusion! @Ecksi if you want to move forward with this PR that would be awesome! I close it for now as we try not to have standing PR's with no activity, so please reopen it and finish it if you feel like you can and want to do it :-) Just a small suggestion: it would be great if the tooltip was not hiding the text, could remain on the same line but just more on the righ so that it doesn't go out of the screen. Cheers!

**Pull request closed without merging**
