### PR TITLE
Sort correctly in Bulk Order Managment

### LINKED ISSUE #9661: [Bulk Order Management] Incorrect sorting by date: months sorted alphabetically instead of chronologically
## Description

When sorting the orders on bulk order management page by 'completed at' date, the months are sorted alphabetically and not chronologically as you would expect. 

## Expected Behavior

Sorting ascending by date you would expect: July --> August --> September

## Actual Behaviour

It is sorted alphabetically: August --> July --> September

## Steps to Reproduce

1. Go to /admin/orders/bulk_management
2. Select date range covering three or more months
3. Sort by date (click on 'completed at' in the table header)
4. Observe the sorting

## Animated Gif/Screenshot

image

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [5a4b38e](https://github.com/openfoodfoundation/openfoodnetwork/commit/5a4b38ec55ad0a56fd00f49fbf4899c91912fa72) (master)
* Browser name and version: Firefox 104.0 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

- Closes #9661 

Inaccurate sorting @ /admin/orders/bulk_management
Even though so some numeric representation of a Date could be used at first thought, the advantage here is also to get a utc date first then to format it to an ISO8601. No locale in a numeric representation.

Avdi Grimm has a post on it: https://avdi.codes/iso8601-dates-in-ruby/

#### What should we test?
The same procedure as stated in #9661
- Go to /admin/orders/bulk_management
- Select date range covering three or more months
- Sort by date (click on 'completed at' in the table header)

I would personally use  July, September and August

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Great documentation, clean PR, thanks!

Wondering if this worth a spec. @filipefurtad0 what to you think?

**Comment by filipefurtad0** [comment]
> Wondering if this worth a spec.

Agree @jibees , wondering as well - something like we already to for the [orders page](https://github.com/openfoodfoundation/openfoodnetwork/blob/4e4a392a8c4fcb157885066136e4c802b5c478bb/spec/system/admin/orders_spec.rb#L226).

I'd suggest we'd make this check on the file `spec/system/admin/bulk_order_management_spec.rb`, within the block `describe "sorting of line items" do`.

Would you be available to add a test to this PR @cyrillefr?

**Comment by cyrillefr** [comment]
Hello @filipefurtad0.
Just added the spec.

**Review by filipefurtad0 — APPROVED** [review]
LGTM, in what the spec concerns. Thanks @cyrillefr !

Seems like a minor code change - should we move it to test ready @jibees ?

**Comment by jibees** [comment]
Yes!

**Comment by filipefurtad0** [comment]
Hey @cyrillefr ,

I've staged the PR and repeated the automated test, on the server with "real" data.

Before the PR:

image

After this PR - with the data for this enterprise, I somehow cannot observer the correct ordering:

After clicking once on "Completed at", I get:

image

After clicking a second time:

image

This seems to work in some cases, but not always. Could there be another factor interfering in the ordering, on this page?

**Comment by cyrillefr** [comment]
@filipefurtad0 , it should work now.
I had forgotten to put the serializer ....
Strangely, my combination of months names worked ... 
So I have taken the same months as your example both in local and and test, and it is ok after(ko before this change)

**Comment by sigmundpetersen** [comment]
Thanks @cyrillefr . 
We should get a short review of the latest changes before moving back to testing 👍

**Review by mkllnk — APPROVED** [review]
Great work!

**Comment by drummer83** [comment]
Hi @cyrillefr,
Thanks for following up on this. I have tested your updated PR and it looks good now.

**Before your PR - clicking 'Completed at' ONCE**
Sorted alphabetically, ascending:
image

**Before your PR - clicking 'Completed at' TWICE**
Sorted alphabetically, descending:
image

**After your PR - clicking 'Completed at' ONCE**
Sorted chronologically, ascending:
image

**After your PR - clicking 'Completed at' TWICE**
Sorted chronologically, descending:
image

### Conclusion
This is great improvement, thanks a lot! It's ready to be merged! :rocket: 

### Note
I find it strange that the columns are sorted per page only (and not all results of the query). So on other pages there may be older or newer line items, even if the table is sorted by date. On page /orders the behavior is different and more intuitive, I think. But we can see that each sorting process requires a new database query there - maybe there was a technical reason to implement the BOM page like this. I will do some digging and see if we want to improve this even more. Also the little indicator arrow for ascending and descending might be helpful sometimes.
All of this is clearly out of scope of this issue and your PR. Just noting my observation.
Thanks again! :muscle:

**Pull request merged**
