### PR TITLE
rename 'new invoice' button to 'create or update invoice'

### LINKED ISSUE #11338: [invoices] Don't generate a new invoice if adjustments label changes
## Description

Editing an adjustment label generates a new invoice when it shouldn't: last invoice should just be updated see https://docs.google.com/spreadsheets/d/1hOM6UL4mWeRCFLcDQ3fTkbhbUQ2WvIUCCA1IerDBtUA/edit#gid=831959393 

## Steps to Reproduce

1. Activate invoice toggle
2. Go to an order with manual adjustment and generate an invoice
3. Edit the label of that manual adjustment
4. See the last invoice is not updated and the new invoice button is available

## Workaround
Generate a new invoice

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #11338

#### What should we test?

- Described on #11338

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Easy.

**Comment by RachL** [comment]
Working good! Got me thinking about other improvements, I will run them by Mario :+1: Merging!

**Comment by RachL** [comment]
@abdellani some conflits to resolve first

**Review by mkllnk — APPROVED** [review]
Conflict resolved. Merging after tests passed.

**Pull request merged**
