### PR TITLE
Use https on all links in emails in production

### LINKED ISSUE #2895: Email Confirm Links not working for some users
For a long time the UK has had an issue with some users not being able to confirm their email addresses.

Asking around other instances, I've not heard this happening in other places, so figured it was a UK config issue. After much (soul) searching it seems that the problem is actually with the way the spree configures URLs

## Expected Behavior

Links in OFN emails break for some users

## Actual Behavior

Links in all OFN emails will work

## Steps to Reproduce

We have not been able to reproduce this issue with consistency.

## Context

UK gets at least one user per week that has not been able to confirm their account or reset their password.

The workaround is them forwarding the email to UK support team as none of us experience the same problem.

We have not found a pattern in browser but haven't tracked mail clients or virus software.

## Severity

bug-s3: a feature is broken but there is a workaround

## Possible fix
Links in emails are always written with http rather than https. My hunch is that some specific virus protection or mail client in the UK is blocking these links as the http in the email does not match the https of the UK website.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2895

Links created by devise in emails were being built with http instead of https. Aside form this not being good practice in general, it seemed to be causing some issues on UK prod where certain user's browsers were complaining, and causing support issues to pile up.

#### What should we test?

Links in emails should now use https on staging and production.

- sign up
- sign up confirmation
- password reset
- order confirmation
- new enterprise
- enterprise manager invitation
- order cycle report for producer
- subscription emails: (testing one of the following should be enough)
  - confirmation
  - empty order
  - placement
  - failed payment
  - placement summary
  - confirmation summary

#### Release notes

Ensure links in emails use https. #2896 

Changelog Category: Changed

### CODE REVIEW

**Comment by mkllnk** [comment]
Staged on https://staging.openfoodnetwork.org.au/.

**Comment by RachL** [comment]
@Matt-Yorkley @mkllnk I've tested the following email:

- registration (producer and buyer)
- order
- password reset

Did I've missed some emails? All working good except password reset where I've got the https twice:
test

but maybe it's just staging related?

**Comment by mkllnk** [comment]
I moved it back to In Dev, because we need to investigate that duplicate https thing. Sounds like a bug.

**Comment by mkllnk** [comment]
@RachL I had a look at all the emails the system is sending and included a list in the PR description.

**Comment by RachL** [comment]
awesome thx @mkllnk !

**Comment by Matt-Yorkley** [comment]
I made a quick tweak to the config and it seems to be working now. 

Staged on https://staging.openfoodnetwork.org.uk

**Comment by RachL** [comment]
Yay it's working beautifully, I don't even have to change the start of the URL anymore ⭐️ 

Thank you @mkllnk for the list of all mails send. My testing notes: https://docs.google.com/document/d/1-GCX2y3FvmJBopWZIGgzkmYlYI6j-B0RWwmNRZf5ePY/edit#

**Comment by mkllnk** [comment]
@Matt-Yorkley This has been deployed to the Australian production server, but we still have http links. I just signed up for accounts on UK staging and production and get http links. For example:

```
http://openfoodnetwork.org.uk/user/spree_user/confirmation?confirmation_token=obynsTgwiewdq3mY3hkr
```

I looked into this, because our staging server had broken URLs. In the Spree configuration we had https//staging.openfoodnetwork.org.au/ as SITE_URL which resulted in confirmation links like this
```
http://https//staging.openfoodnetwork.org.au//user/spree_user/confirmation?confirmation_token=6HcugUqp6GNWnUQLGIfW
```

Changing the url to a domain (staging.openfoodnetwork.org.au) generates a working URL, but with http.

**Pull request merged**
