### PR TITLE
Uk/ie11 quantity fix

### PR DESCRIPTION
**Pull request by stveep**
…n incompatibility of IE11 and Angular.

Fix for #1417

### CODE REVIEW

**Comment by stveep** [comment]
Doing some tidying up - did this slip through the PR review net?

**Comment by daniellemoorhead** [comment]
Sure did @stveep !

Would actually be great if you could get this staged and tested by @OliverUK? @lin-d-hop does that sound like the best next step given @sstead is climbing a mountain somewhere and isn't back until Sept 14?

**Comment by OliverUK** [comment]
I'm afraid I don't have / don't use IE.

**Comment by NickWeir63** [comment]
Hi @OliverUK I have IE set up as an alternative browser and am happy to test if you can tell me what to test and on which server

**Comment by OliverUK** [comment]
@NickWeir63  I believe this is the related issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/1417
However I don't think there is a build to stage yet. If @stveep could make this appear on buildkite for UK dev, we could stage it and you could test it in IE11.

**Comment by daniellemoorhead** [comment]
@sstead has IE @NickWeir63 @OliverUK so we can test it over here if it's easier?

**Comment by sstead** [comment]
Testing notes:
The 0 is disappearing in IE now when you start typing :+1:

**Comment by oeoeaio** [comment]
So @sstead says the functionality it right, but looking at this I am a little bit concerned about performance. We're adding an awful lot of event listeners to the shop page, which is already not the fastest. Any thoughts @stveep? Do you guys have a way of testing this against production data?

**Comment by sauloperez** [comment]
Do we have any analytics data to base our decision on? If the IE11 user base in most of the instances is not significant is not worth optimizing the performance IMHO.

**Comment by oeoeaio** [comment]
@sauloperez as it stands, any performance hit caused by this fix would be experienced by all users. It would not be restricted to only IE users, even though it is solving a UX issue only for them only. So it is a choice between a) ensuring that performance is not affected by this change (which it may not be) or b) not implementing the fix.

**Comment by sauloperez** [comment]
Oops, I didn't notice that this applies to all users. Thanks for the heads-up. Totally agree with you.

**Comment by daniellemoorhead** [comment]
Hey all, it's been a while since this was active. Given the solution will impact on performance and we have big performance issues it feels like we need to go back to the drawing board.

@stveep for the sake of kicking off the new year and trying to get our delivery pipe cleaned up I'm going to close this PR and put the issue back into the backlog. Feel free to reopen and continue work on it if you get the time. And also, happy new year to you and yours :-)

Ping @lin-d-hop for info

#githubcull2018

**Pull request closed without merging**
