### PR TITLE
[Bye bye Spree] Bring models product, variant, price from spree_core

### PR DESCRIPTION
**Pull request by luisramos0**
See comment below first: https://github.com/openfoodfoundation/openfoodnetwork/pull/5885#issuecomment-676647764

#### What? Why?
Also included in this PR models: option_value, option_type, product_property and product_option_type

Continues #4826
Here we move the following files to OFN:

- core/app/models/spree/variant.rb MERGE WITH DECORATOR
- spec/models/spree/variant_spec.rb MERGE WITH OFN VERSION
- core/app/models/spree/price.rb MERGE WITH DECORATOR
- core/app/models/spree/option_type.rb MERGE WITH DECORATOR
- core/app/models/spree/option_value.rb COPY
- core/app/models/spree/product_option_type.rb MERGE WITH DECORATOR
- spec/models/spree/product_option_type_spec.rb COPY
- core/app/models/spree/product_property.rb MERGE WITH DECORATOR
- spec/models/spree/product_property_spec.rb COPY
- core/app/models/spree/product.rb MERGE WITH DECORATOR
- spec/models/spree/product_spec.rb MERGE WITH OFN VERSION
- core/app/models/spree/prototype.rb - NO COPY remove references

No code changes were made, here we only move the code from spree, adapt the specs if needed and improve the code a little with rubocop and transpec.

#### What should we test?
We need to verify if everything related to products and variants (yes, everything basically) in OFN is working well.
This is a little heart surgery to OFN. We do need to trust the build here and do some good verifications:
- catalog management - create edit delete products and variants and all their properties.
- add these to OCs
- verify we can buy these products and variants and that they display correctly in the shopfront
- verify reports and make sure products and variants are displaying correctly
- there quite a few more things we could check...

#### Release notes
Changelog Category: Changed
Brought code needed in OFN from Spree so that we can make OFN independent of Spree.

### CODE REVIEW

**Comment by luisramos0** [comment]
Some problem with the product duplicator. I will wait for 5733 and see if it fixes this broken spec.
The spec is green locally...

**Comment by luisramos0** [comment]
Still broken after 5733, any thoughts about what could be causing such issues?
I think I have seen this in the past but I cant remember what it was....
image

**Comment by Matt-Yorkley** [comment]
So the naming here is handled by `ProductDuplicator` (Spree lib which has been imported here), which is called from `Spree::Product#duplicate`. I can't see why it's not working though. The `Spree::Product` class does not explicitly load that lib file, and the initialization is implicitly done with no namespace, maybe that's a clue.

**Comment by luisramos0** [comment]
Hmm, I tried this but it didnt help:
image

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by jhsu802701** [comment]
At the moment, the issues are CodeClimate only (which overlap with RuboCop).

**Comment by luisramos0** [comment]
As discused with @Matt-Yorkley and @filipefurtad0 this PR should wait until #5870, #5980, #5928 and #6089 are tested and merted. After that we can test this as part of the final bye bye spree PR #5978.

When the 4 minor PRs are merged, I will base #5978 on this PR only and we can test both PRs there :+1:

**Comment by Matt-Yorkley** [comment]
All merged, time for whatever branch juggling is planned here before testing :+1:

**Comment by luisramos0** [comment]
ok, the plan is done: rebase this one and push to upstream. Then rebase #5978 on it and make this branch the base of #5978 
Test both PRs in #5978 
@Matt-Yorkley do you want to have a final look at the code and move #5978 to Test Ready.
Then @filipefurtad0 can pick #5978 for testing (I'll keep this one blocked as this is not supposed to be staged).

**Pull request merged**
