### PR TITLE
Add Bullet logging to test suite

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

WIP: quick test of the Bullet gem with Semaphore.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Ok... it looks like there's maybe a conflict with one of the Bullet dependencies and some of our code, so lots of specs are failing. On the other hand the N+1 reports are working, and there are LOTS of entries in the logs.

**Comment by luisramos0** [comment]
😲 this is awesome, it even tells you what to do!
"Add to your finder: :includes => [:bill_address]"

**Comment by luisramos0** [comment]
and then the performance nirvana:
Bullet.raise = true  # raise error if n+1 query found

**Comment by luisramos0** [comment]
you can do "gem 'bullet', group: 'development'" to start with.

**Comment by luisramos0** [comment]
there are 782 alerts! a lot are repeated, for example:
/home/runner/openfoodnetwork/app/serializers/api/admin/order_serializer.rb:12:in `full_name'

appears in 32 alerts.

I think we should follow this up! maybe we should create an epic specifically for this #exciting

**Comment by Matt-Yorkley** [comment]
There's tons of errors related to variant option naming. There's a PR going through soon that changes it, I'll rebase this once it's merged and have another look...

**Comment by Matt-Yorkley** [comment]
Also from looking at the github issues for this gem, it looks like there could be some false-positive and false-negative problems. I'll play with it again next week and see how we can extract some value from it.

**Comment by Matt-Yorkley** [comment]
> /home/runner/openfoodnetwork/app/serializers/api/admin/order_serializer.rb:12:in `full_name' appears in 32 alerts

That should be fixed in the open PR for variant naming. :+1:

**Comment by Matt-Yorkley** [comment]
The build is green now (apart from a single flaky spec), so the question is: how do we want to use the output from this gem?

It seems like a valuable resource. We could do a quick blast through the list and try to add eager-loading in all the suggested places? Whether we want to merge this PR and permanently include Bullet reports in our CI is a different question.

**Comment by luisramos0** [comment]
ah, I dont think we should forget about this.
I will re-open this PR temporarily now, capture the output of bullet in the CI build and create an tech debt issue for this based on the current output.

**Comment by luisramos0** [comment]
ok, I have created https://github.com/openfoodfoundation/openfoodnetwork/issues/4673

**Pull request closed without merging**
