### PR TITLE
Move variables

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

I discovered that we have an unnecessary extra file, so to cleanup and assist future changes, I moved the variables where they belong.

https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1687252447504379

I started doing this on master, but realised it's inter-related with BUU. Hmm we need to do some PRs!!

#### What should we test?
- The only colour change is a very slight change of red on the modal close button (eg upload product photo on the bulk edit screen).
- Everything else should look the same when feature toggle is turned on or off. 
#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Nice clean up, thanks! 🙏

**Comment by jibees** [comment]
I'm wondering what the next steps are. 

- I've slightly tested this one (both on legacy and v3), and I'm tempted to merge as soon as possible. 
- Also, I agree that we probably should prepare the PR to merge our WIP work in master. What do you think?

**Comment by RachL** [comment]
@dacook hello is this one something you are still working on?

**Comment by dacook** [comment]
Thanks Rachel, yes there's some work here that is not yet merged.
It's quite timely – I was just thinking yesterday, "I'm sure I did this already". So thanks for the prompt! I've created a new PR so will close this one.

**Pull request closed without merging**
