### PR TITLE
Add CSS optimization

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Addressing #1628.

#### What should we test?

Size of CSS files in production and staging. Duplication of CSS rules.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Doesn't seem to be working on staging...

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley where's this at? Does it need testing by Oliver? Let us know when you want the AU team to get involved via the aus review label :)

**Comment by myriamboure** [comment]
@Matt-Yorkley @lin-d-hop what should we do about that ? It seems Matt you pushed another commit on 23rd september, but it has not been reviewed and tested, is it ready for it?

**Comment by lin-d-hop** [comment]
Closing as @Matt-Yorkley didn't follow up on the comments after it didn't seem to slove the problem out-of-the-box.
#gitcull2017

**Pull request closed without merging**
