### PR TITLE
Convert Admin Order Cancellation Workflow to Stimulus #9447

### LINKED ISSUE #9447: Convert Admin Order Cancellation Workflow to Stimulus
### What we should change and why (this is tech debt)

As OFN is transitioning to use StimulusJs in the frontend, remove all Jquery/Angular code that handles admin orders cancellation to Stimulus. The existing jquery/angular code resides in: `app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb`

### PR DESCRIPTION
**Pull request by cyrillefr**
- removes Angular Controller
  - replaces it with Stimulus Controller
  - add XSRF protection that used to be native with Angular
  - replaces use of jQuery `ofnCancelOrderAlert` with `ModalCancelController`

#### What? Why?

- Closes #9447 

#### What should we test?

- Visit /admin/orders
Select one or many orders, click on `Actions` then `Cancel Orders` : it should work exactly as before.
- Unit T: `rspec spec/system/admin/bulk_order_cancellation_spec.rb` should raise no failures.

##### Before
call to Angular Controller
`app/assets/javascripts/admin/orders/controllers/bulk_cancel_controller.js.coffee` that calls `ofnCancelOrderAlert` (jQuery in `variant_autocomplete.js.erb)`

`ofnCancelOrderAlert` in `variant_autocomplete.js.erb` is now `this.showModal(this.callback);` in `ModalCancelController`

##### After
`app/views/spree/admin/orders/index.html.ham`  call to new StimulusJS controller `admin/bulk_cancel_controller.js`

It extends `ModalCancelController`
`ModalCancelController` takes care of what `ofnCancelOrderAlert` handles
  - binding/unbinding OK & Cancel buttons
  - visible/hide toggling of modal
  - setting content message

`bulk_cancel_controller.js` replace Angular Controller
Diffs are:
  - getting order ids from the controller directly and not from the Angular object
  - Angular use XSRF protection natively, so we must now add it natively

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
Hi! 👋

Thank you very much for your contribution. I think we should have been more explicit when writing the issue and specially the acceptance criteria in terms of development. 

As we are currently moving towards using reflexes via [StimulusReflex] (https://docs.stimulusreflex.com/), I don't think it is a good idea to implement a solution via `fetch` and _classical_ requests. You couldn't have known that, of course, so I apologise for that. 

You can find an example of PR using StimulusReflex (still in code review) [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9804).

I'm also wondering what's the opinion of @mkllnk on it. Thanks! 🙏 

Anyway, feel free to ask any question if needed. 

Thanks a lot! 🙏

**Review by mkllnk — APPROVED** [review]
Excellent work. We could accept this solution because it solves the part of replacing AngularJS but ideally we would use StimulusReflex. Would that be a fun challenge for you?

**Comment by cyrillefr** [comment]
Hello @jibees and @mkllnk , thank you for the words.
Yes, I 'd like to redo it with StimulusReflex.
I 'd like to play with this new way of reactive ruby (like hotwire).
Which means I have therefore written waaay too much JavaScript ....

I will need a few days to get to know a bit better StimulusReflex.
I guess also none of the code I have written is any useful, the best thing would be to close this PR and for me to create another one.
I will do that before creating another one PR.

**Comment by jibees** [comment]
Awesome @cyrillefr ! Can't wait to see your next PR!!

**Comment by cyrillefr** [comment]
I just created a new PR at #10297

**Comment by sigmundpetersen** [comment]
Should we close this one then?

**Comment by filipefurtad0** [comment]
> Should we close this one then?

I think so, seems #10297 replaces it - Thanks for pointing it out @sigmundpetersen :-)

**Pull request closed without merging**
