### PR TITLE
Uk/1025 from address

### PR DESCRIPTION
**Pull request by stveep**
See #1025 and previous PR #1044 from @lin-d-hop. This adds a toggle for the 'send confirmation from the enterprise email' behaviour. It's off by default (perhaps should be on?) and can be set in the super admin mail settings.

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@oeoeaio is this ok to be tested by @sstead and then make part of the 1.8.5 or 1.8.6 release?

**Comment by lin-d-hop** [comment]
Hi @daniellemoorhead @oeoeaio Just wondering if there was any update on this one. I see it didn't make it into v1.8.5 release. Thanks!

**Comment by daniellemoorhead** [comment]
Hi @lin-d-hop realised we'd missed this one from the 1.8.5 backlog. Have included it in 1.8.6 and will let @oeoeaio tell you where he's at with it (looks like it's going through testing with @sstead).

**Comment by daniellemoorhead** [comment]
@oeoeaio the UK team are going to get @MagsHall to test this one on their end in an attempt to speed up the process. Once you're back online can you let them know where you're at with it and if you were planning for @sstead to take a look? Ta!

**Comment by oeoeaio** [comment]
Hey @stveep and @lin-d-hop,

The commit history in this PR looks like it has a weird merge or rebase that shouldn't be there. It makes it a bit hard to actually review what is going on - I am assuming all of those commits from Rohan have already been merged into master with a different hash. Might I suggest creating a new branch from the current master and then pulling across the commits that are relevant to this branch using `git cherry-pick`?

**Comment by stveep** [comment]
New PR: #1203

**Pull request closed without merging**
