### PR TITLE
Moves/Updates admin into system (cont. III)

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Continues #8440

Updates/moves several admin/enterprise feature specs into system. 

Aside from the required updates https://github.com/openfoodfoundation/openfoodnetwork/pull/8450/commits/182ef9eb3ee1ce62db54d6b626c874784ab4e4e8 and https://github.com/openfoodfoundation/openfoodnetwork/pull/8450/commits/a946b93fb92cc10cd135aa916909b68f44ad917c, an example was removed in https://github.com/openfoodfoundation/openfoodnetwork/pull/8450/commits/a946b93fb92cc10cd135aa916909b68f44ad917c as it concerned hard-deletion of a shipping method. This cannot be achieved from the UI - it is only possible to soft delete items using the trash-bin icon.

Enterprises_spec.rb was updated 6a33ad4 as it seemed to fail before. 

#### What should we test?

Green build.

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Comment by mkllnk** [comment]
There are still failing specs, so moving back to dev. Or did you move it here as a request for help?

**Comment by filipefurtad0** [comment]
Sorry, my mistake - all was passing locally so I thought I'd be good to go. I'll have a second look at it :+1:

**Review by mkllnk — APPROVED** [review]
Great!

When I suggested to split this work into several PRs, I was worried that I was just causing more work for no real benefit. But seeing all the little bumps you are smoothing out along the way I'm now glad that we went this way. Thank your for embracing this strategy. :hugs:

**Review by Matt-Yorkley — APPROVED** [review]
:+1:

**Pull request merged**
