### PR TITLE
Fix error when creating new product on Admin panel

### LINKED ISSUE #6117: Invalid unit_value on product creation returns 500 instead of 422
## Description
Entering a non-number for `unit_value` (appears as the "Value" text field) during product creation returns a 500 error instead of a more informative error message. We do have placeholder text in the field but this can often be missed or misinterpreted.

## Expected Behavior
Error message stating "Value must be a number" and a 422 server response.

## Actual Behaviour
Entering a non-number for unit_value during product creation returns a 500 error.

## Steps to Reproduce

1. https://openfoodnetwork.net/admin/products
2. Click on New Product
3. Enter valid product information except for the Value text field
4. Click Create
5. Death by slug

## Animated Gif/Screenshot
Screen Shot 2020-10-01 at 1 53 41 PM

## Workaround
Reading the placeholder text, or just guessing at what went wrong. 

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Safari

### PR DESCRIPTION
**Pull request by tsara27**
#### What? Why?
Closes #6117

I am adding conditional to check variants first before updating the stock items when creating a product.

#### What should we test?
Test the new product creation on admin panel.

How to do:

Login as an admin.
Go to products.
Create a new product.
Fill other required details, leave the unit value empty.

Changelog Category: Fixed

### CODE REVIEW

**Comment by andrewpbrett** [comment]
Hi @tsara27, thanks for submitting this. It looks like some tests now fail as a result, so we'll need those to pass before we can consider merging this. 

The `on_hand` and `on_demand` fields probably don't need to be changed to fix this, since those have to do with variant stock. I think the fix will be somewhere in the product model or controller.

**Comment by tsara27** [comment]
Hello @andrewpbrett,

I have checked the specs. It seems work on my dev machine. Is there any possibility that the spec only failed on Semaphore?

**Comment by andrewpbrett** [comment]
Hi @tsara27 - this is looking better now! It looks like some specs are still failing because the factory creates a product without specifying a unit_value and so the object fails validation. You could take a look at the product factory and feel free to update it to provide a unit_value and I think that would take care of a few of them. 

I did checkout this branch locally and confirm that the tests fail locally for me and not just on Semaphore.

**Comment by tsara27** [comment]
> Hi @tsara27 - this is looking better now! It looks like some specs are still failing because the factory creates a product without specifying a unit_value and so the object fails validation. You could take a look at the product factory and feel free to update it to provide a unit_value and I think that would take care of a few of them.
> 
> I did checkout this branch locally and confirm that the tests fail locally for me and not just on Semaphore.

Thank you Andrew! I am fixing all specs now.

**Comment by luisramos0** [comment]
hello! fyi app/models/spree/product_decorator.rb is now app/models/spree/productrb

**Comment by andrewpbrett** [comment]
Hi @tsara27 - I tried to rebase this branch to resolve the conflicts from removing spree and I'm afraid I made a big mess of it. I think it happened because I merged master in instead of replaying these changes on top of the latest... and now I'm not able to undo the merge. I made a fresh PR instead. Sorry about that! I'm going to close this issue so we can use the new one instead.

**Comment by tsara27** [comment]
Hello @andrewpbrett,

No problem. Thank you for helping me recreating a fresh PR. :slightly_smiling_face: 

I did not have time for few weeks to work on this project because I got project from my full time work to finish everything before the holiday. :cry:

**Pull request closed without merging**
