### PR TITLE
Remove atomic gem

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Bundler says this when installing gems:
```
Post-install message from atomic:
This gem has been deprecated and merged into Concurrent Ruby (http://concurrent-ruby.com).
```
It looks like we're using the atomic gem for an old workaround that modifies the middleware in the test environment. I tried removing it, and everything seems to work fine without it...? Maybe capybara/chromedriver handle this issue now without intervention?

#### What should we test?

Dev-test? Running feature specs with JS is potentially affected..?

#### Release notes

Removed atomic gem and RackRequestBlocker middleware.

Changelog Category: Technical changes

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]
Let's try it. We can always revert it.

**Review by mkllnk — COMMENTED** [review]
The RackRequestBlocker was really important to stabilise our build. Without it, we have to make sure that all AJAX requests are finished before the end of a test block. Otherwise we get random failures because the database cleaner is already cleaning stuff up while the server tries answer a request.

While I would prefer to have really clean specs, we found that it's too hard, especially with community contributions, to keep track of all possible AJAX requests that may happen in each feature spec. It's also easily overlooked because specs fail only sometimes.

I wonder though if this problem has been solved differently within Rails now. We would need to run the specs many times to know if this has an impact or not.

**Comment by mkllnk** [comment]
> Let's try it. We can always revert it.

Yes we can. But wouldn't it be annoying if specs become flaky and we may not know why? I prefer to test things before. A test setup for this would be:

* feature spec visits a page like showing a shopfront
* the page contains JS doing a request
* the request contains a sleep of a second
* the spec ensures that the request is in progress (loading sign) and then finishes
* the server tries to load something from the database that was referenced in the request :bomb: :question: 

In this scenario, the request blocker would wait for the server to finish the request before cleaning up after the spec.

**Review by mkllnk — APPROVED** [review]
Okay, I had a good go at trying to make this fail. I changed the shop spec to finish while the products were still loading. And in the controller action I added a sleep and deleted a random product. All went fine and the log showed me that the database cleaner ran last, after the request finished. So it looks like Rails solved this problem and made the RackRequestBlocker obsolete. :+1:

I'm very hopeful that this won't cause any more flaky specs. Merging... :smile:

**Comment by Matt-Yorkley** [comment]
I was recently debugging some errors with XHR requests failing due to a bug, and I noticed that removing `RackRequestBlocker` made the test output show the error more clearly, which made it easier to figure out the problem. So I think this is a good move!

If everything starts blowing up we can shove it back in again :sweat_smile:

**Pull request merged**
