### PR TITLE
Add total to producer emails

### PR DESCRIPTION
**Pull request by stveep**
Quick fix to add a total to the emails, re. https://github.com/openfoodfoundation/openfoodnetwork/issues/927

### CODE REVIEW

**Comment by NickWeir63** [comment]
Thanks very much @stveep

**Comment by mkllnk** [comment]
Sally tested this and we get the following error:

```
NoMethodError · app/mailers/producer_mailer.rb:55
undefined method `+' for #<Spree::Money:0x007f174be670a8>

Stacktrace summary
app/mailers/producer_mailer.rb:55 · each
app/mailers/producer_mailer.rb:55 · reduce
app/mailers/producer_mailer.rb:55 · total_from_line_items
app/mailers/producer_mailer.rb:9 · order_cycle_report
app/jobs/order_cycle_notification_job.rb:4 · block in perform
```

Does Spree::Money have a `+` method? Do we need to add that one?

**Comment by stveep** [comment]
OK think that should fix it. Somehow my test case was adding up correctly though so please check it again - it's hard for me to check this manually so I am relying on the spec. Or let me know how to do it - I guess I need an OC set up with items + orders, then click notify...? There is no + method for Spree::Money - we could implement one though, might be useful elsewhere.

**Comment by daniellemoorhead** [comment]
Hey @mkllnk can you please try and get this through for the UK as part of release 1.7.1.

**Comment by OliverUK** [comment]
Thanks very much of taking care of this so promptly, everyone!

**Comment by stveep** [comment]
This has been merged as part of the other improvements

**Pull request closed without merging**
