### PR TITLE
Remove StockLocation from ReturnAuthorization

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

We have only one default location and don't need it associated to anything.

#### What should we test?

- A return authorization can be created as before.
- A return can be processed as before.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — APPROVED** [review]
👍

**Review by rioug — APPROVED** [review]
Nice :+1:

**Comment by mkllnk** [comment]
Thanks for the quick merge, but there were testing steps on here! Well, I guess that return authorizations are so rarely used that we can probably live with the risk.

**Comment by rioug** [comment]
Sorry, I missed that !

**Pull request merged**
