### PR TITLE
Increase limit on database columns that involve prices

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Increases the maximum number of digits (on the _left_ side of the decimal place) that the columns can hold, to allow larger values. 

Note: `precision: 10, scale: 2` means "10 digits in total, 2 of them are decimals".

These changes are introduced in various places in Spree 2.2 (eg [here](https://github.com/spree/spree/blob/fd0131aea17c3a25972cf5079288bec7bd6870bc/core/db/migrate/20130319062004_change_orders_total_precision.rb))  and become the default setting for fields dealing with prices.

#### Relevance

It's useful in cases with either large order values, or certain currencies that have large values as standard. For example, 100 UK Pounds is roughly 4000 Thai Baht. So whilst 1 million pounds is unlikely to ever be needed as a value, 1 million Baht is not so unlikely...

I believe the guys in West Africa have already hit this issue and found errors thrown by the database when trying to save values that were larger than the current constraints?

Anyway, it's a small change and won't really have any effect on core instances.

#### What should we test?

- Sanity check existing prices are unchanged.
- When saving things with prices, values such as `10,000,000.00` can now be saved without error.

#### Release notes

Increased limit on size of numbers that can be saved on price fields.

Changelog Category: Technical changes

### CODE REVIEW

**Comment by sauloperez** [comment]
IMO, although is fine to manually test this, we can't rely on manual testing for this low-level change. That's what I think it's worth adding a test to ensure

> When saving things with prices, values such as 10,000,000.00 can now be saved without error.

That will provide us with the necessary confidence to merge this.

**Comment by sauloperez** [comment]
I move this to In Dev while we add that unit test.

**Comment by Matt-Yorkley** [comment]
@sauloperez I added a quick test which verified an error was thrown before the change, and updated it to show the test passes without throwing an error after the migration is run :+1:

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley 

I'm wondering; ideally we would not have to consider "cost_price" at the DB level, after this PR #6822, right? I opened a tech-debt #6898 to address this (in case removing it is indeed a good idea).

I'll drop you a line on slack later tomorrow, this PR seems to have conflicts.

**Comment by Matt-Yorkley** [comment]
thanks @filipefurtad0 I've created a PR to remove that `cost_price` code :+1:

I think we can still test and merge this one as-is, even if we're separately deleting that column.

**Comment by filipefurtad0** [comment]
Cool, thanks @Matt-Yorkley ,

This is working as expected. I've triggered the respective error, before staging:
- [A field with precision 10, scale 2 must round to an absolute value less than 10^6](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/602d087d59985300178a8246?event_id=602d087d0069a1c657460000&i=sk&m=nw)

I checked that the same error is only triggered after exceeding the condition no
- [A field with precision 10, scale 2 must round to an absolute value less than 10^8](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/602d087d59985300178a8246?&event_id=602d14850069aa66aa1b0000)

So, after this it accepts numbers like this one:

image

However, we might to improve our UI to accommodate these larger numbers:

image

I'll open an issue on this one :+1: 

Good to go!

**Pull request merged**
