### PR TITLE
Edits to .ruby-version for Docker setup in Windows

### LINKED ISSUE #6034: Docker-Compose Build command error-ing out with ruby-build
## Description
I was trying to set up the app by following the Docker guide. I ran into an issue on step 9/15 of the docker file, what I believe to be the line that runs ruby-build's install.sh file.  The build stops as it returns a "ruby-build: definition not found: 2.3.7" error.

## Steps to Reproduce
What I did was:

1. Fork the repo
2. run docker-compose build

## Animated Gif/Screenshot
issue1
issue

## Severity
I'm not too sure what to rate it, maybe s3 or s4?

## Your Environment
I am on Windows 10 Pro.

## Possible Fix
I was thinking maybe something need to be modified within the Dockerfile.

### PR DESCRIPTION
**Pull request by abdiclear**
Closes #6034 

Having attempted to setup OpenFoodNetwork via Docker, there was an issue with ruby-build not finding a definition for ruby 2.3.7. This happened on a Windows 10 Pro device. There was whitespace at the end of the ruby-version file, specifically a newline (CR+LF), and removing that allowed for the Docker setup to proceed and complete sucessfully.

#### What should we test?

Similar Windows 10 devices may run into this issue if there is space after the version number, a press of the Enter key.

Changelog Category: Changed

### CODE REVIEW

**Comment by luisramos0** [comment]
Hello @abdiclear this is weird, are you sure this really fixes the problem? Can you replicate the problem if you re-add the line break?

There is no whitespace there, only a new line.

I am now thinking this is could be related to how your git setup is done and how line breaks are converted. You know, windows and linux have different ways of representing line breaks...

**Comment by abdiclear** [comment]
So to clear up any misconceptions I have caused, I do regard line breaks as whitespace, apologies for that. Here is the .ruby-version file pulled straight from the main repo:
linebreak

When I run docker-compose build, I get the error I reported:
test1 0

Now, when I remove the line break, this is what happens:
nolinebreak

test2 0

Toggling the core.autocrlf setting doesn't seem to cause any changes. I think the line break was being read with the version number, and the line break is CRLF on GitHub.

**Comment by luisramos0** [comment]
line breaks and whitespaces are totally different things.
the problem we are looking at here is related to line breaks being represented differently in Linux and Windows. You can look up the internet for that.

from what you post, I am pretty sure that it is a problem with your git setup on windows. That CRLF is just the way Linux writes line breaks. I think there must be something you can do on your windows/git setup to get that file without that crlf.
I think we can merge this PR and this problem is solved, but I am saying this because I think you will have further problems down the line when you write and commit code.... I recommend you have a further look.

Looking at how github repesents your change, we can see it doesnt look very goof with the red sign indicating there's a missing empty line at the end of the file:
image

**Comment by abdiclear** [comment]
To my understanding, Linux should end lines with just LF yeah? I know Windows ends files with CRLF, and after some sniffing around, it seems Git for Windows came with core.autocrlf set to true. Looking at my configurations:
clash

It would explain why toggling core.autocrlf didn't seem to do anything. It was recommended that repositories have a .gitattributes file in the root directory in which we can insist on line endings to be LF, which I believe would stop Git for Windows on devices like mine to switch line endings to CRLF by default. What do you think?

**Comment by abdiclear** [comment]
On my local repo of OFN, I added a .gitattributes file that looks like this:

gitattributes

For testing purposes, I cloned my local repo onto my device, and had a look at .ruby-version. Here are the results:
LFending

betterresult

I think this is a more elegant solution than just simply removing any line breaks from .ruby-version. Let me know what you think and how you want to proceed! 👍

**Comment by Matt-Yorkley** [comment]
Give this a try: https://stackoverflow.com/a/33424884

**Comment by abdiclear** [comment]
I gave your suggestion a try Matt, and it worked out for me when I tested it out. Should there be a section in the Getting Started documentation telling Git for Windows users about this? Or should the .gitattributes route be taken?

**Comment by Matt-Yorkley** [comment]
I think we can just add a note in the Wiki :+1:

**Comment by sauloperez** [comment]
then the problem is solved and we can close this, right @abdiclear ?

**Comment by abdiclear** [comment]
Yeah we can close this as long as the wiki is updated accordingly.

**Comment by luisramos0** [comment]
:+1: 
here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6148/files

**Pull request closed without merging**
