### PR TITLE
Upload enterprise image (logo and promo): force content type to "text/plain"

### LINKED ISSUE #7534: Endless spinner when uploading logo and promo images
## Description

When creating an enterprise, the user has the possibility do add a logo and promo images. These appear not to work: an endless spinner is displayed instead.

## Expected Behavior

The spinner should only be displayed till the image is fully uploaded.

## Actual Behaviour

The spinner does not disappear.

## Steps to Reproduce

1. Log in; click Register here on the homepage.
2. Fill in the details necessary to get to the step in which you are allowed to upload logo and promo images.
3. Select a file and click Upload.
4. See the spinner spinning.

## Workaround

The images seem to actually be uploaded. So the workaround is to just move along to the next registration step.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.6.10
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Closes #7534

`render plain:` does render text. Force the content type to be `text/plain` (instead of `application/json`) for the image upload response.

#### Discussion:
I don't know which one of the solution is the best, between: 
```ruby
render html: @enterprise.logo.url(:medium), status: :ok
```

and
```ruby
render plain: @enterprise.logo.url(:medium), status: :ok, content_type: 'text/plain'
```

The main issue could be that `render plain:` send response with `Content-Type: application/json` but I guess it could be something bigger, and maybe we should open another issue to handle properly this case?

#### What should we test?

1. Log in; click Register here on the homepage.
2. Fill in the details necessary to get to the step in which you are allowed to upload logo and promo images.
3. Select a file and click Upload.
4. See the image upload ending, and display the image in the preview instead the spinner

#### Release notes
Upload image during enterprise registration 

Changelog Category: User facing changes

### CODE REVIEW

**Review by sauloperez — CHANGES_REQUESTED** [review]
I think `render html` is the way to go. Our controllers either do `render json` or `render html` so it makes sense.

This looks good to me but adding a couple of controller tests seems reasonable because we changed its behaviour.

**Comment by Matt-Yorkley** [comment]
A couple of notes:
- we can add tests on that controller output very easily as well (which is totally missing), and check `response.body ` and `response.content_type`
- an integration test might be good as well? It feels like this bug is about how the client is parsing the response
- the output and behavior in building that image URL will be slightly different in staging and prod due to compiling and asset timestamps (which won't be the same in dev or test) :warning:

**Comment by jibees** [comment]
- I will change to `render html`
 - I will create some controller test
 - I will create an integration test

Thanks !

**Review by Matt-Yorkley — APPROVED** [review]
:+1:

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Awesome @jibees ,

After staging:

Peek 2021-05-27 10-23

- The the spinner appears only during file upload
- The image preview appears reviews
- After completing the registration we can verify that the image upload is persistent and can be seen under the `Images` tab:

image

Thanks for adding tests for this as well :muscle: 
Ready to go!

**Pull request merged**
