### PR TITLE
Add password confirmation, token and expired keys

### LINKED ISSUE #2905: Untranslated error message in reset password process
## Description

When asking new password, one string is untranslated (second field) and the error message if token expired is untranslated as well.

capture du 2018-10-22 16-41-47

## Severity

This is front end so more annoying... priority S3 I would say ;-)

### PR DESCRIPTION
**Pull request by HugsDaniel**
#### What? Why?

Closes #2905 

Add password confirmation, token and expired keys for devise i18n.

#### What should we test?

Translations are made with devise i18n keys.

Changelog Category: Added

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
Stage on FR @luisramos0 ?

**Comment by luisramos0** [comment]
stage https://staging.openfoodfrance.org/

**Comment by myriamboure** [comment]
It might not be super easy to reproduce @RachL to see the key, I have no idea what is the duration of the password reset expiration token? Maybe some dev can tell us? @Matt-Yorkley ? @mkllnk ? So we can plan the test to get it and see if the text is still ok.

**Comment by RachL** [comment]
Don't worry that's why I've started it a Friday night @myriamboure so that the link would be expired on Monday ;)

"Password confirmation" is not translated. Is it just not translated in the french file but the string is there @HugsDaniel ?

image

**Comment by mkllnk** [comment]
I also found a few untranslated text pieces with an automated test: https://github.com/openfoodfoundation/openfoodnetwork/issues/2626#issuecomment-433291504
I think it would be really good to get all these untranslated strings done quickly so that we can check for them in automated tests. That should avoid most of these issues.

**Comment by HugsDaniel** [comment]
@RachL the key for `password_confirmation` is there (see `en.yml`) so the translation must be missing for french and other languages.

I can take care of the other missing translations in this PR, @mkllnk what do you think ? Or in a new PR ?

**Comment by RachL** [comment]
@HugsDaniel ok then I propose we move this one forward. Please do another PR for the other missing translations :) it will be easier to follow.

**Comment by mkllnk** [comment]
All good! My comment was about more work to be done in other PRs. :+1:

**Pull request merged**
