### PR TITLE
Remove unnecessary SSL code

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Once upon a time, SSL over HTTP (HTTPS) was new and not supported by default. We still got some leftover code from those times which can be removed now.

#### What should we test?

- Open a private window to not use any HSTS settings.
- Visit http://staging.../ and make sure that you are redirected to https://staging.../.
- Then log in as super admin and go to the general settings.
- The two "security" options should be gone and the layout should not be compromised.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
👌 
Thanks for cleaning the code! 🧼

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

Thanks for the detailed steps on how to check this:

- Opened a private window to not use any HSTS settings.
- Visited `http://staging.../` -> redirection to `https://staging.../.` occurred :+1: 
- Logged in as super admin and visited the general settings
- The two "security" options are gone now :+1: 
- The layout looks good :+1: 

All good here! Merging.

**Comment by filipefurtad0** [comment]
Hey @mkllnk,

I've noticed this error, on #devops-notifications:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1675275022293559
```

Unhandled error
NoMethodError: undefined method `disable_starttls_auto' for #<Net::SMTP smtp.sendgrid.net:587 started=false>
Did you mean?  disable_starttls
              enable_starttls_auto
Location
gems/mail-2.8.0.1/lib/mail/network/delivery_methods/smtp.rb:138 - block in build_smtp_session
```

Emails seem not to be arriving for staging-UK - strangely, they seem to be arriving for staging-AU

**Comment by filipefurtad0** [comment]
Emails are broken on staging-FR too; this was probably introduced on this PR - opening an [issue](https://github.com/openfoodfoundation/openfoodnetwork/pull/10339).

**Pull request merged**
