### PR TITLE
Remove feature toggle around unit_price

### LINKED ISSUE #7499: Remove feature toggle on Unit prices
### What we should change and why (this is tech debt)
We should remove all the conditional testing about unit prices feature once it has been released, tested and accepted by all instances.

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
And, as a consequence, enable it.
Closes #7499 

This idea is to enable it by default on all instance.

#### What should we test?
You should basically test everywhere when a unit price should be present, that it is really present.

###### As a customer
 - On a shop front
 - On a sidebar cart
 - On the cart page
 - On the confirm order page

###### As an admin
 - When creating a new product
 - When editing an existing variant
 - When creating a new variant

#### Release notes
Unit price feature is ready, and is therefore enabled.
Changelog Category: User facing changes

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]

**Comment by jaycmb** [comment]
@sauloperez We agreed that this can be released independent from #7602

**Comment by sauloperez** [comment]
ah ok, then I forgot/misunderstood.

**Comment by filipefurtad0** [comment]
Hey @jibees ,
Some merge conflicts arose, I think this needs rebasing  :+1: 
Adding the feedback needed label.

**Comment by jibees** [comment]
Hey @filipefurtad0 
Indeed ;) Rebase done! ✅

**Comment by filipefurtad0** [comment]
Hey @jibees,

After:
- staging this PR
- disabling the `unit_price` feature on `flipper` (browser session 1, pic below - left)
- opening an admin tab  (browser session 2, pic below - right)
- opening a customer tab (browser session 3, pic below - middle)

image

We can see unit-price is still active, so I proceeded to verify this on the places you mentioned (thanks!) throughout the app:

- As a customer

    On a shop front - OK
    On a sidebar cart - OK
    On the cart page - OK
    On the confirm order page - OK

- As an admin

    When creating a new product - OK
    When editing an existing variant - OK
    When creating a new variant - OK

Good to go! :tada:

**Pull request merged**
