### PR TITLE
Fix Layout/LineLength - Bundle 3

### PR DESCRIPTION
**Pull request by macanudo527**
#### Third Bundle of Layout/LineLength Rubocop Offense Fixes

- Helps #6055 
- This is a bundle of fixes that were originally attached to #10714 

This makes code easier to read on smaller screens by reducing the line length. These fixes are bundled in groups of 60 to make it easier to review.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by macanudo527** [comment]
This should be good to go as well when someone is free.

**Review by rioug — APPROVED** [review]
Nice one !

**Comment by macanudo527** [comment]
@dacook I was wondering if you are free, could you look at this?

**Review by dacook — APPROVED** [review]
👍 Thank you!

**Comment by macanudo527** [comment]
> +1 Thank you!

Thanks for the quick turnaround!

**Pull request merged**
