### PR TITLE
Add more fields to revenue report as used by Aus

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Follow up to #9521.

We currently maintain our own [CSV generation script](https://gist.github.com/mkllnk/9be5e677bffb65141998d9ff9925ecc1) which could be replaced if we got all this information here.

#### What should we test?

- As a super admin, visit page `/admin/reports`
- Select the revenue report
- New columns should appear
- Some columns may be empty if the enterprise didn't store that information

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Looks good to me!

**Comment by drummer83** [comment]
Hi @mkllnk,
Thanks for this PR!
I have first compared the columns of your script to the columns in the report. These seem to match.
Also have I pulled the report before staging and after staging to compare the results. 

- content is identical before and after staging :heavy_check_mark: 
- columns have been added :heavy_check_mark: 

image

We do have BOTH email addresses in the report now, while we had **hub owner email** in the previous report only and the **public email** in your script. Should we leave this as is:question: 

I am moving to ready to go, to include it in the next release and we can always remove one of the two emails later, if desired.

**Comment by RachL** [comment]
Hub owner email is important at least in FR, otherwise we don't know how to regroup the shops. If AU needs public email, then let's keep both I guess :)

**Comment by drummer83** [comment]
> What's the address btw? the one in business details?

Yes. Let me double check...

**Comment by drummer83** [comment]
@RachL Only the hub's legal name is taken from the business details. The rest is the information from 'address' and 'contact' tabs.

**Comment by RachL** [comment]
Ah thanks Konrad! :) fyi @kirstenalarsen I wonder if you have these cases. In FR the hub address is often a pickup location whereas the business address is where we need to invoice. I don't know how we could easily improve this. Like take the hub address if no business details is mentioned... but perhaps too complex.

**Pull request merged**
