### PR TITLE
Ordercyclemanagementreports3

### PR DESCRIPTION
**Pull request by lin-d-hop**
Ok it took three attempts (not sure why the second failed)... but I've cleaned up the PR from the merge commits.

Also flushed away bad code smells by stripping out the long method as requested.

Fun times had by all :-)

### CODE REVIEW

**Comment by lin-d-hop** [comment]
Ok so a few things on this...
1) I stupidly updated when exploring matts changes... so I'm going to cherry pick all of these commits over to OrderCycleManagementReports4... d'oh!
2) I've added a method to the delivery report to suss whether an order has any chilled or frozen items. Heres the method in a gist: https://gist.github.com/lin-d-hop/11c60592e6f0d7984dd2
I feel like this might be a pretty useful method to have available elsewhere moving forward. @oeoeaio Can you suggest a better place to put this method so that it is more publicly accessible? In the line_items controller perhaps?
3) The new method still needs a spec so I'll add that once it's comfortably housed.

Thanks!!

**Comment by RohanM** [comment]
About the updates thing, there are a couple of tools that might be helpful:

- git up adds an alternative to git fetch/pull that rebases by default: https://github.com/aanand/git-up
- This bash alias provides a pretty git log that makes it easy to see merges vs rebases etc.: `alias gl='git log --graph --pretty="format:%C(yellow)%h%Cblue%d%Creset %s %C(white) %an, %ar%Creset"'`

**Comment by RohanM** [comment]
I've commented on that gist: https://gist.github.com/lin-d-hop/11c60592e6f0d7984dd2

**Comment by lin-d-hop** [comment]
@RohanM @oeoeaio Hi both.
I'm having trouble getting my head around how to implement @RohanMs suggestions in the gist above:
"The simplest way I can think of to work around that would be to add a flag to ShippingCategory, like needs_refrigeration. There could be a checkbox in the admin interface to set that."
So, my interpretation of this is:
1) Add to the Configuration -> Shipping Categories two shipping categories that can be included with just a check box; needs_refrigeration and frozen. 
2) Update the ShippingCategoryDecorator so that product.shipping_category.needs_refrigeration return the value as appropriate.

It would be good to discuss this a little more to check I understand what I'm actually doing.... maybe via skype?

**Comment by RohanM** [comment]
Hi @lin-d-hop . The idea I had in mind was a bit different:

1. To the ShippingCategory model, add a new field `needs_refrigeration:boolean`.
2. To the admin interface for managing shipping categories (Admin -> Configuration -> Shipping Categories -> New/Edit), add a checkbox to control this field.
3. Set up some shipping categories. There could be several that need refrigeration, such as Dairy and Frozen Foods.

Now we can do the following in the report:

```ruby
def has_chilled_or_frozen_items?(order)
  order.line_items.any? { |line_item| line_item.product.shipping_category.needs_refrigeration? }
end
```

Which is another way of saying, "Does this order have any items that need refrigeration?"

What are your thoughts on that one? Happy to tee up a skype if it's not clear.

**Comment by lin-d-hop** [comment]
Closed, replaced by #399 purely because of the merge commits messing up the PR.

**Pull request closed without merging**
