### PR TITLE
select2: improve style

### PR DESCRIPTION
**Pull request by seballot**
#### Before

image

#### After

image

## Improve the style of select2 "light" version

Make it look the same than normal select

#### Before

image

#### After

image

#### What should we test?

Pages which use such select box
Also make sure others select box are still working as before

### CODE REVIEW

**Review by jibees — APPROVED** [review]
I'm not that happy when I see `!important`, but I'm sure you've tested without ;)

**Review by mkllnk — APPROVED** [review]

**Comment by seballot** [comment]
@jibees @mkllnk thanks for the review, FYI I have pushed another commit and updated the PR

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @seballot, 
Thanks for another pull request! I love looking at the details, so I love improving them as well. :-)

I did a test of your changes in Chromium and in Firefox, both on Ubuntu. Here is what I found!
## Improve the style of select2 input with multiple choices
This was found on 
- /admin/enterprises/enterprise_name/edit#!/primary_details --> Groups
- /admin/enterprise_groups/group_name/edit#!/primary_details --> Enterprises
- /admin/order_cycles/#nubmer/edit --> Schedules
- probably many more...

### Chromium
**Left:** before staging the PR (production); **Right:** the PR staged
image
:ok_hand: The multiple choices are nicely aligned in the center vertically.

### Firefox
**Left:** before staging the PR (production); **Right:** the PR staged
image
:warning:  The changes don't seem to have the same effect on the display in Firefox.

## Improve the style of select2 "light" version
I have difficulties finding instances of this select2 version. Can you provide any advice on how/where to find these so I can spot the difference? Thanks!

# Summary
- Please provide advice on how/where to find the improved select2 drop down
- Changes of multi-select are only improving in Chromium, but not breaking anything in Firefox, so this would be an overall improvement and could be merged.

**Comment by seballot** [comment]
Thanks for testing @drummer83 !

For the "light selec2", it seems almost not used in the code expect in some files called "tag_rules", but I cannot understand where there are used (without spending too much time)

If you know how to do it, you can just add the class `light` to any select2

image

image

re multiple select2, in firefox, there is still an improvement, the close icon is now vertically centered and a bit bigger :P

**Comment by mkllnk** [comment]
I had a quick search and I think the light input is used when editing tag rules.

**Comment by drummer83** [comment]
Thanks for both your support. It's still tricky for me. Forgive me, if I am totally wrong...

Reading the scss file, which was changed in this PR, I understand that the changes made to 'light' only apply when the class 'select2-container' is applied at the same time. `.select2-container` plus `&.light` some lines below leads to `.select2-container.light`, correct?
But searching for `select2\-container[^\-]` (regular expression to avoid finding 'select2-container-multi' etc.) leads to results only in scss files. Doesn't that mean that 'select2-container' is not used in the code and the changes to 'light' will never be applied? Or are there other ways to apply that class to an element without writing it in the code?

Here are the search results:
```
Search "select2\-container[^\-]" (24 hits in 6 files of 3189 searched)
  Z:\home\konrad\openfoodnetwork\app\webpacker\css\admin\hacks\ie.scss (2 hits)
	Line 15:   .select2-container:hover .select2-choice,
	Line 16:   .select2-container.select2-container-active .select2-choice {
  Z:\home\konrad\openfoodnetwork\app\webpacker\css\admin\plugins\select2.scss (3 hits)
	Line 1: .select2-container {
	Line 80: .select2-container .select2-choice .select2-arrow {
	Line 177: label .select2-container {
  Z:\home\konrad\openfoodnetwork\app\webpacker\css\admin\sections\orders.scss (1 hit)
	Line 7:   .select2-container {
  Z:\home\konrad\openfoodnetwork\app\webpacker\css\admin\sections\products.scss (1 hit)
	Line 5:   input, select, textarea, .select2-container {
  Z:\home\konrad\openfoodnetwork\app\webpacker\css\admin\select2.scss (1 hit)
	Line 1: .select2-container {
  Z:\home\konrad\openfoodnetwork\vendor\assets\stylesheets\select2.css.scss (16 hits)
	Line 4: .select2-container {
	Line 14: .select2-container,
	Line 29: .select2-container .select2-choice {
	Line 60: .select2-container.select2-drop-above .select2-choice {
	Line 72: .select2-container.select2-allowclear .select2-choice .select2-chosen {
	Line 76: .select2-container .select2-choice > .select2-chosen {
	Line 86: .select2-container .select2-choice abbr {
	Line 103: .select2-container.select2-allowclear .select2-choice abbr {
	Line 107: .select2-container .select2-choice abbr:hover {
	Line 177: .select2-container .select2-choice .select2-arrow {
	Line 198: .select2-container .select2-choice .select2-arrow b {
	Line 406: .select2-container.select2-container-disabled .select2-choice {
	Line 413: .select2-container.select2-container-disabled .select2-choice .select2-arrow {
	Line 419: .select2-container.select2-container-disabled .select2-choice abbr {
	Line 607:   .select2-search input, .select2-search-choice-close, .select2-container .select2-choice abbr, .select2-container .select2-choice .select2-arrow b {
	Line 607:   .select2-search input, .select2-search-choice-close, .select2-container .select2-choice abbr, .select2-container .select2-choice .select2-arrow b {
```
Searching for 'light' I have also come across the 'tag_rule' pages but there is no combination with 'select2-container' as well.

Looking forward to your comments and probably learning from you, @seballot.

**Comment by seballot** [comment]
Hi @drummer83, the `select2-container` class is added by select2 with javascript, and select2 take all initial select class (such as `light` and add it to the `select2-container` newly created by javascript.

So in the code we just use `select2` class (that tell selct2 to convert this select tag into a select2 input), along with `light` or other classes when necessary

**Comment by drummer83** [comment]
Ok, thanks! You see, now I've learned! :smiley: 
I have no idea how to find and test it then.
@filipefurtad0 What is your opinion? Should we leave that part untested or would you like to have a look and let me know how you did it?
Learning, learning, learning... :wink:

**Comment by mkllnk** [comment]
Also note that #8814 is replacing select2 in some places.

**Comment by mkllnk** [comment]
This is a really small change and since @drummer83 didn't find any regressions, I'm declaring it as *tested*. :smile: Merging.

**Comment by filipefurtad0** [comment]
Hey, thanks @seballot for input and @drummer83 for testing. 

Just for the record:

>  light input is used when editing tag rules

Indeed we can see in (Firefox/Ubuntu), that `light` version is rendering/working as expected, tags page as @mkllnk pointed out:

image

I've made this search to find it in the code:

image

Thanks for all the tips on this one! :pray:

**Comment by drummer83** [comment]
Damn it! 
I WAS SO CLOSE!!! :sob: 
:laughing:

**Pull request merged**
