### PR TITLE
en-US

### PR DESCRIPTION
**Pull request by MikeiLL**
This looks like a pretty messy PR. The only thing I'm trying to PR is the `en-US` file so apologies for the mess. Since we (stubbornly) insist on using Pounds and Inches instead of the Metric system here, I added one string: `weight_measurement_unit: "Weight (per lb)"` which I was hoping we can use instead of a hard coded string in `models/open_food_network/calculator/weight.rb`. I experimented briefly, but unsuccessfully.

### CODE REVIEW

**Comment by pmackay** [comment]
This cannot be merged in its current state. Is there an issue related to the weights problem? Would it be worth discussing there first the best solution? If it is to have an `en-US` locale, I'd suggest a PR that just has that change. Its not correct to include file mode changes, log files, hardcoded paths for `ofn_america`, removing database.yml and so on.

**Comment by MikeiLL** [comment]
I understand that, which I thought I had made clear in my comment. Will try to send a new PR with only the `en-US` file. Just not sure what that will entail yet. Was hoping you could merge only that new file in.

**Comment by MikeiLL** [comment]
OK. Apologies for the mess. This should do the trick.

**Comment by MikeiLL** [comment]
And yes - there is an issue with weight, because Americans are used to buying produce by the pound. Like everything else international, the metric system scares us. I imagine that the string in `models/open_food_network/calculator/weight.rb` should be i18n anyway rather than hard coded with the word "weight".

**Comment by daniellemoorhead** [comment]
Hiya @MikeiLL we've added time next week in our schedule for @mkllnk to review this, @sstead test it, and then to put it into the dot point release that'll go live by the end of the week. Cheers!

**Comment by mkllnk** [comment]
Hi @MikeiLL!

I can merge the current pull request with just the locale. But I would like to mention that whenever you update to a newer version of OFN, you will need to update the locale as well and translate new strings. Most people use Transifex for that. So if you are happy to maintain the en-US locale, that would be great. You are also very welcome to open a pull request translating strings that are currently hard-coded. The people in France and Norway would be very happy about that as well.

**Comment by myriamboure** [comment]
Ping @pacodelaluna for info

**Comment by daniellemoorhead** [comment]
@mkllnk @MikeiLL can this be closed given Maikel merged the commit to master last year? Or is there more in it that hasn't been finished off yet?

**Comment by mkllnk** [comment]
@daniellemoorhead This is closed. But people can comment on closed pull requests. I don't think any further action is required.

**Pull request merged**
