### PR TITLE
Confirmation popup on shop change in admin section.

### LINKED ISSUE #8441: Cart deleted without warning when choosing different hub on producer's page
## Description

The following behaviour was observed and discussed in this [slack conversation](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1611105113010100):
**Scenario 1**
- Put items into your cart
- On the map, select a different hub
- Click on the hub below "change shop to ..."
- A warning pops up that you will lose your items in your cart

This is considered to be a feature.

**Scenario 2**
- Put items into your cart
- On the map, select a producer, that sells at a different hub
- Click on the hub below "shop for ... products at"
- No warning will show, but your cart will be deleted.

This is condisered to be a bug.

## Expected Behavior
Before deleting the cart in scenario 2 a warning should be displayed (as in other cases).

## Actual Behaviour
The cart is deleted without warning.

## Steps to Reproduce
See description of scenario 2 above.

## Animated Gif/Screenshot
This is the warning which should be displayed, but is not.
grafik

## Workaround
Don't use the above workflow of scenario 2.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v4.1.5
* Browser name and version: Firefox 93.0
* Operating System and version (desktop or mobile): Windows 10, Desktop

## Possible Fix
Include the warning.

### PR DESCRIPTION
**Pull request by seballot**
#### What? Why?

Closes #8441

#### What should we test?
Scenario 2 described in #8441

### CODE REVIEW

**Review by jibees — APPROVED** [review]
I've updated the PR title, to be more clear in the release notes section.
Adding a screenshot is also most welcome in a PR. Thanks for that @seballot ! 🙏

**Review by mkllnk — APPROVED** [review]
Thanks! You are on :fire:

**Comment by filipefurtad0** [comment]
Hey @seballot !

I've checked the mentioned scenarios, before staging:

Scenario 1 - not relevant for this issue, but good to check:

image

Scenario 2

Peek 2021-12-02 12-23

After staging, and looking at scenario 2 one can gets the same result, i.e., no pop-up or warning when choosing a hub associated with a given producer, from the map:

Peek 2021-12-02 12-54

So, I think this might need a second look?
Moving to In Dev for now.

**Comment by seballot** [comment]
sorry @filipefurtad0 I had been lazy and did not took time to get the map working on local machine (needed google api key), so I made a fix on the producer list, hoping it was the same template used

But it was not ah ah :)

So this time I made the map working and fixed it propery (hopefully!!)

**Comment by seballot** [comment]
Hi @jibees 
my first attempt did only change `producers/_fat.haml`, now it change also `producer_details.haml`

Yes the map is now working with evil google :)

**Comment by jibees** [comment]
Nice @seballot thanks!

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @seballot ,
This is now working:

Peek 2021-12-17 10-54

Thanks!
Merging.

**Pull request merged**
