### PR TITLE
Jobs cleanup

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Removes Job classes who's only purpose is to send a single email asynchronously. `ActionMailer` is better integrated with `ActiveJob` since Rails 4.2, so this is not needed. Calling `#deliver_later` directly on a Mailer will have the same effect, without the need for wrapping the whole thing in an extra Job class.

#### What should we test?

Emails for User signup, Manager invitation, and Enterprise registration should all work as before.

#### Release notes

Changelog Category: Technical changes

Removed some unnecessary code and simplified use of Jobs and Mailers.

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]

**Review by sauloperez — APPROVED** [review]
:tada:

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Tested:

- User signup - 1 email arrives: Signup confirmation. Somehow it got labelled as junk, by my Thunderbird, which is unusual. Is this to be correlated with the change in the code? I repeated registration, but couldn't reproduce this. So I think we're good here.
 
- Manager invitation (unregistered user) - 2 emails arrive: Signup confirmation + Invitation to Manage Hub.

- Enterprise registration - 1 email arrives: Enterprise registration.

Looks good, ready to go.

Emails arrived as usual - ready to go :+1:

**Comment by sauloperez** [comment]
> Signup confirmation. Somehow it got labelled as junk, by my Thunderbird, which is unusual. Is this to be correlated with the change in the code?

That's normally related to the DNS configuration of the domain.

**Comment by filipefurtad0** [comment]
Maybe a good idea to re-check this in production. I'll open a place-holder issue, as a reminder for an after-deploy check.

**Pull request merged**
