### PR TITLE
Make shops index page usable on mobile

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Adds some quick adjustments for the shops index page on mobile to make it usable. It's not a full-blown redesign, just some minor changes that mean the user can actually see the list of shops and click them.

#### What should we test?

Shops index page, producers index page, and hubs and producers tabs on group pages are usable on small devices.

#### Release notes

Improved shops, producers, and group pages for mobile devices.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
### Video:

SHOPS

**Comment by lin-d-hop** [comment]
@Matt-Yorkley you are my hero :heart_eyes:

**Comment by RachL** [comment]
this is awesome! thanks @Matt-Yorkley Weird question: is the angle the only way to have the dropdown opening? Like what happens if I fatfinger the carret? :D How can I visit the shop? I just click on the name?

**Comment by Matt-Yorkley** [comment]
> is the angle the only way to have the dropdown opening?

If you click anywhere in the whole area that's not the name/;ink for the shop, it toggles.

**Review by luisramos0 — APPROVED** [review]
This PR is pure @Matt-Yorkley :ok_hand:

**Comment by Matt-Yorkley** [comment]
Ah, there's a few similar changes that can be done to fix the /producers and /groups pages. I'll add them now.

**Review by sauloperez — APPROVED** [review]
Thank you @Matt-Yorkley and pretty good CSS!

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

I had a look how did this behave on mobile (Browserstack, Iphone 11 - Chrome), **before staging**:

/shop
image

/producers
image


/groups
image

And after staging :tada: 

/shop
image

/producers
image

/groups
image

Shop and Producers looks awesome!! But I can't make out any difference on /groups. Also, I see in your commits that `darkswarm/groups.scss` remains unchanged. Is/was this the file to be changed? I'm just assuming here :-D Should an issue be opened here, as a reminder?

Anyway, this looks great!! :heart:

**Comment by Matt-Yorkley** [comment]
You have to choose a group, then look in the tabs on the group page :+1:

**Comment by filipefurtad0** [comment]
No problem at all - my bad actually: I'm still not very familiar with Groups pages/feature, I should have explored here a bit more. Thanks Matt :-)

**Pull request merged**
