### PR TITLE
`/shops`: fix list overlapping and overflowing texts on mobile

### LINKED ISSUE #9782: [Shops list] Overlapping and overflowing texts on mobile
## Description
In the shops page (shops#/) 

- Shop city: can overlap with the shop "status" (closing in..)
- Shop title: sometimes overflow, sometimes there's "..." and the arrow (>>), sometimes there's "..." and no arrow

## Overlap
Screen Shot 2022-10-13 at 16 27 51

## Overflow
Screen Shot 2022-10-13 at 16 33 04

## Severity
bug-s4: it's annoying, but you can use it

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #9782 

It's not easy to make great PRs when refactoting/improving CSS. When language is not that structured, it's a mess. Maybe I should delete all and rewrite all...

**FROM**:
Capture d’écran 2023-04-14 à 15 23 16
Capture d’écran 2023-04-14 à 15 32 50

**TO**:
Capture d’écran 2023-04-14 à 15 23 50
Capture d’écran 2023-04-14 à 15 33 27

#### What should we test?

- Visit `/shops` and check that for each size of screen, it's better (or at least not worst) than previously ...
- 

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Review by dacook — CHANGES_REQUESTED** [review]
Noting that this means the columns for each shop are no longer aligned. I can see how this makes better use of the space, unique for each shop. 
But I'm not sure how it will look with production data. For example if there are lots of towns/suburbs in the same state, the same state name will appear in different positions (depending on the town name).

Otherwise, I have a suggestion about class naming.

**Comment by jibees** [comment]
> But I'm not sure how it will look with production data. For example if there are lots of towns/suburbs in the same state, the same state name will appear in different positions (depending on the town name).

You're right. Maybe I should test with more data. Will deploy this PR on staging (has a lot of data), and see how it goes. Back `In Dev` then.

**Comment by filipefurtad0** [comment]
> Will deploy this PR on staging (has a lot of data), and see how it goes.

@jibees Let me know if you need help testing this :+1:

**Comment by jibees** [comment]
#### Before the PR




#### After the PR
Capture d’écran 2023-04-18 à 15 33 09
Capture d’écran 2023-04-18 à 15 33 22



#### My conclusion

To me, it's not obvious that this PR does improve the global UX experience (yes, we do not have overlapping anymore but now some alignment issues to be clean). I think I should work more on it.

**Comment by jibees** [comment]
This PR is not the right solution to avoid overlapping text, as it introduce others issues. I can think of two solutions:

 - Find a way to solve the issue in a very simple tiny fix ; 
 - either re-write all DOM/CSS and use a table display (both flexible and aligned between rows)

**Pull request closed without merging**
