### PR TITLE
Update Bugsnag error data

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Changes the way we pass extra data to Bugsnag. It should be displayed more nicely now in the UI.

#### What should we test?

Try triggering one of the errors in staging and see if there's an extra tab with more info added.

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — CHANGES_REQUESTED** [review]
Nice! Thank you!

There's one related spec fail. So I'll move it back to in-dev.

Just an idea: What do you think about creating a new module that uses the syntax we thought works and translates it into the Bugsnag's interface. 

```rb
def report_issue(error, metadata)
  Bugsnag.notify(error) do |payload|
    metdata.each...
  end
end
```

And we could have a method on the ApplicationController which adds the order automatically.

**Comment by Matt-Yorkley** [comment]
> And we could have a method on the ApplicationController which adds the order automatically.

Hmmm... I'm not sure how much we'd gain there. Firstly there's plenty of places where we need to call Bugsnag outside of the controller context (models, jobs, etc) so a method in `ApplicationController` wouldn't be much use. Secondly adding the order automatically doesn't make sense in all cases either, it's not always present and it's not always the main focus of a Bugsnag call. So then I think we'd just end up creating an interface that looks more or less identical to the one that's already provided by `Bugsnag.notify`...? :man_shrugging:

**Comment by mkllnk** [comment]
> There's plenty of places where we need to call Bugsnag outside of the controller context (models, jobs, etc) so a method in ApplicationController wouldn't be much use. Adding the order automatically doesn't make sense in all cases either,

That are very good points. I agree to not add a method to the ApplicationController. Adding a method that takes a hash instead of a block could still simplify the code. I'm not fussed. :shrug: Your current version annoys the cops though...

**Review by mkllnk — APPROVED** [review]
I rebased this PR to get the relaxed Rubocop rules. All good now.

**Review by jibees — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @Matt-Yorkley,
I have tested this PR on UK staging server. However I couldn't spot a difference. Could you please provide more information where to look for the extra tab?

Here is what I found before staging:
grafik

And here the same after staging and triggering the same error again:
grafik

I am leaving this in Test Ready because I might just be looking at the wrong thing...

**Comment by mkllnk** [comment]
I reckon that the error you triggered is not one that is adding a tab. Not all errors do. One scenario that should add an Order tab is the case that an order cycle expires during checkout. I can't remember properly but I think that you can go through the checkout with Paypal, stop at the confirmation page in Paypal (before being redirected back) and close the order cycle in a different tab.

**Comment by drummer83** [comment]
Thanks for the hint @mkllnk!

I have tried the following things:
- close the order cycle during checkout with paypal
- do a check out with all shipping methods set to 'backoffice only'

Both is triggering an error in Bugsnag but with no additional tab:
grafik

grafik

I would need more advice or @filipefurtad0 needs to do his magic! Nevertheless I have learned a lot! :-)

**Comment by filipefurtad0** [comment]
Hey @drummer83, @Matt-Yorkley, @mkllnk 
I've noticed there were some changes around subscriptions in this PR, so I've ran some subscription jobs with cards doomed to fail like the "always block" card 4100000000000019 `pm_card_radarBlock` or with an `invalid_cvc`, but still no luck on observing the new tab on Bugsnag.

Then, I've tried checking out with such cards, observed [this bug](https://github.com/openfoodfoundation/openfoodnetwork/issues/8952);

Then, I've disabled split-checkout, and placed some orders with bad cards, on legacy checkout. 

Peek 2022-03-24 13-28

Should the toggled split-checkout play a role here? Adding the feedback-needed label.

**Comment by mkllnk** [comment]
I don't know why it's not working. I'm moving it back to in-dev.

**Review by jibees — APPROVED** [review]
I agree @mkllnk : let's merge it!

**Pull request merged**
