### PR TITLE
Direct beginners to Rails tutorials

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

We want to support beginners better and collected some resources for learning Rails.

### CODE REVIEW

**Review by jibees — APPROVED** [review]

**Comment by achauve** [comment]
The PR looks good but I don't know where we can discuss the content of the wiki page (PR are not available for that I think? unless using a second repository... :D ).

For the content:
- I couldn't find the "5$" reference on the website you linked. For a full access to the ebook (and download) it seems to be 39$ now.
- The book "Agile Web Development with Rails 6" seems to have great reviews too (https://pragprog.com/titles/rails6/agile-web-development-with-rails-6/).
- Maybe we could add a section on general ruby books (still love programming books): "The Well-Grounded Rubyist" and "Eloquent ruby" (tell me if you think it's a good idea, I could add it to the wiki).
- Maybe add a word on rails + angularjs, coffeescript, other techs used in the repo? (same I can do it, don't hesitate to ask / point me to good ressources you'd know of).

**Comment by Matt-Yorkley** [comment]
I'd recommend [this book](https://www.poodr.com/) by Sandi Metz, for learning Ruby and learning how to approach software development in general.

**Comment by mkllnk** [comment]
> I don't know where we can discuss the content of the wiki page (PR are not available for that I think? unless using a second repository... :D ).

Github wikis are actually Git repositories as well. You can clone https://github.com/openfoodfoundation/openfoodnetwork.wiki.git but it doesn't have a pull request functionality, as far as I know. So we can discuss it here.

> I couldn't find the "5$" reference on the website you linked.

https://www.learnenough.com/pricing
Screenshot from 2021-11-23 09-01-45

I think that "the tutorial" includes access to the courses, not just the book.

> I'd recommend this book

Great! We can have a whole section of books there. But we also need to be careful not to overwhelm people. The purpose is not to tell people all the options out there. They can search themselves. We want to make it easy for people to decide which way to go by giving our recommendations that we can vouch for and that are aligned with our code style.

That said, whatever you found helpful is probably worth mentioning on the wiki page.

> Maybe we could add a section on general ruby books

Yes, very happy to go beyond Rails and include JS and databases as well.

Go for it! :rocket:

**Comment by achauve** [comment]
Thanks @mkllnk but going back to LEarn enough website, I think the "5$" download is for other tutorials on the site (command line, ruby, etc. ?) but not for "the rails tutorial". In any case I couldn't add the rails tutorial in the cart at that price ;-). If you click on "the rails tutorial" in the upper menu, the pricing on the page is "39$".

Completely agree with you that people should not overwhelmed. The links you added seem totally fine as a start and we can later add a section of other books or ressources recommended by the team, if indeed we personnaly vouch for it.

**Review by achauve — APPROVED** [review]

**Comment by mkllnk** [comment]
Ah, thanks for clarifying that @achauve. I removed the $5 for the wiki page now. Pricing can change anyway. People just have to look it up and decide for themselves.

**Pull request merged**
