### PR TITLE
Reduce controller size

### LINKED ISSUE #8942: Rubocop: app/controllers/split_checkout_controller.rb has too many lines
### What we should change and why (this is tech debt)
Rubocop warning about the length of the class `split_checkout_contoller.rb`

### Context
This came up in PR https://github.com/openfoodfoundation/openfoodnetwork/pull/8893#issuecomment-1048313464

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #8942

Trims down the split checkout controller size to a more manageable level. 

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
👌 

We lose some information about the error messages, but I think that's fine. 
Is it worth testing manually? What do you think?

**Review by mkllnk — APPROVED** [review]
Nice work! Still so much complexity. Ten years ago I never imagined ecommerce to be that complicated. :wink:

**Comment by mkllnk** [comment]
Testing instructions:

- Checkout
- Trying to find edge cases in error handling and going between checkout steps.

**Comment by filipefurtad0** [comment]
Hey team,
Conflicts arose here :point_down:

**Comment by mkllnk** [comment]
I resolved the conflict.

**Review by rioug — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @Matt-Yorkley,
Thanks for another PR!

I have tested:
- checkout,
- moving between checkout steps,
- creating error messages (e.g. missing information),
- race conditions during checkout (order cycle closing or last item sold during checkout).

I couldn't find any problems. Looking good!

Merging! :tada: 
Thanks again! :rocket:

**Pull request merged**
