### PR TITLE
[BUU] Style and behaviour updates

### PR DESCRIPTION
**Pull request by dacook**
## What? Why?
Just some little updates that have popped up. Plus I added a few more..

1. **Addresses [padding comments in Slack](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1705370180125479?thread_ts=1705367237.342049&cid=C01CXQNJ1J6)**
    - Product rows ("relaxed") are a total of 56px
    - Variant rows ("condensed") are a total of 40px
    Screenshot 2024-01-25 at 3 01 20 pm
3. **Validation to prevent invalid negative values ([per comments](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1706663539310959))**
    Screenshot 2024-01-31 at 4 55 07 pm
4. **Allow direct entry of a number if On Hand field is selected with the keyboard**
5. **Fix styling when on hand has a blank value** (it's not valid, but can happen, which makes it hard to click on again)
    Now, it just appears blank. We'll probably adjust minimum widths later as part of a broader change.
    Screenshot 2024-02-01 at 11 39 09 am
6. **Fix to prevent "on demand" covering up the next column**
    Screenshot 2024-02-01 at 11 57 19 am
7. **Fix column heading alignment**
    Columns with inputs should now line up. Well.. almost. The On Hand popout has reduced padding which messes it up a bit, but I won't dwell on that right now.
    Screenshot 2024-02-01 at 12 05 24 pm

## What should we test?
As above.

### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by dacook** [comment]
FYI @mariocarabotta I've created these fixes, can you please let me know if you see any problems?

**Comment by mariocarabotta** [comment]
good stuff David!

**Review by mkllnk — APPROVED** [review]
Easy to follow. :+1:

**Review by rioug — APPROVED** [review]
Nicely done !

**Pull request merged**
