### PR TITLE
Redirect to shopfront when Order cycle closes during split checkout 

### LINKED ISSUE #9733: [Split Checkout] Message 303 when order cycle closes during checkout
## Description

Follow up of #9688.

In #9688 the redirections and error messages when the order cycle closed during checkout were fixed for our legacy checkout. For Split Checkout the situation got worse, see below.

## Expected Behavior

- When clicking 'Next' on any of the three Split Checkout pages, the user should be redirected immediately
  - if shop has no order cycles open -> redirect to shop homepage (closed shopfront)
  - if shop has 1 order cycle open -> redirect to /shop; automatically select that order cycle
  - if shop has 2 order cycles open -> redirect /shop; do not select an order cycle
- in all the above cases, display the correct error message (from en.yml -> order_cycle_closed)
- 404 should not occur
- 303 should not occur

## Actual Behaviour

- the first click on 'Next' doesn't do anything (Message 303 in the browser) :x: 
- only the second click works as expected ✔️ 
- redirections are ok ✔️ 
- error messages are ok ✔️ 

## Steps to Reproduce

The following should be tested for 
- legacy checkout and split checkout
- all steps on split checkout (1 - Your details, 2 - Payment method, 3 - Order summary)
- cash, paypal and stripe payments
- zero, one and two or more remaining open order cycles after closing the current one

1. Login as user
2. Create an order in an order cycle
3. Get to the checkout screen (/checkout)
4. As the enterprise owner, close the order cycle
5. As the user, click on 'Next' or 'Order now' on the checkout step of interest
6. Ascertain that you are redirected to the shop front according to the 'expected behavior' above
7. Ascertain that there's a flash message informing you that the OC just closed

## Animated Gif/Screenshot

image

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by binarygit**
#### What? Why?

- Closes #9733 

#### What should we test?

Please follow the steps outlined under `Steps to Reproduce` [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9733#issue-1396232792) in order to test this. 

Thanks to @drummer83 for the detailed steps above. 

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
I'm not sure to understand this. First question then: the lines you've added are 
only used when split checkout is activated right? What happens if split checkout is not activated for user? This kind of response is handled without error? or ignored?

Thanks! 🙏

**Comment by binarygit** [comment]
In legacy checkout we request a `json` response from the server, so this code runs and is sent back to the client.
```ruby
      format.json { render json: { path: main_app.shop_path }, status: :see_other }
```

and in split checkout, we request a `cable_ready` response from the server, so this code runs and is sent back to the client.
```ruby
      format.cable_ready {
        render status: :see_other, operations: cable_car.redirect_to(url: main_app.shop_path)
      }
  ```
  
 We are good in both cases, either legacy or split, because we are requesting different responses from the server and have tailored responses for each of them.

**Review by jibees — APPROVED** [review]
Thanks

**Comment by filipefurtad0** [comment]
Hey @binarygit ,

I've tested the scenarios of a closing order cycle on the `/details`, `/payment` and `/summary` pages. In all cases redirection occurs to the shopfront, and so the behavior is verified, as described in the issue:

>    When clicking 'Next' on any of the three Split Checkout pages, the user should be redirected immediately
        if shop has no order cycles open -> redirect to shop homepage (closed shopfront)
        if shop has 1 order cycle open -> redirect to /shop; automatically select that order cycle
        if shop has 2 order cycles open -> redirect /shop; do not select an order cycle
    in all the above cases, display the correct error message (from en.yml -> order_cycle_closed)
    404 should not occur
    303 should not occur

This looks great now :+1: 

All cases above were verified, as an example:

>  if shop has no order cycles open -> redirect to shop homepage (closed shopfront)

image

Bugsnag is triggered as we get a warning for closed OC:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1671721087734389

Thank you!

Merging.

**Pull request merged**
