### PR TITLE
Upgrade to ruby 2.7.3

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

In rails 6.0 we can use ruby 2.7 now.
Pairs with https://github.com/openfoodfoundation/ofn-install/pull/749

#### Release notes

Changelog Category:  Technical changes
Upgraded to ruby 2.7

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Looks like we'll need to bump the `json` gem?

**Comment by Matt-Yorkley** [comment]
There's a [monkey-patch we could potentially use](https://github.com/flori/json/issues/399), otherwise we'll need to disentangle whatever dependencies are tying us to `json < 2.0`, which currently seems to be primarily the `aws-sdk` gem...

**Comment by luisramos0** [comment]
aws-sdk-v1 1.67 is the last version, so it's not an upgrade.  I think it's a switch to aws-sdk-s3 https://rubygems.org/gems/aws-sdk-s3/versions
I tried using the patch (still in the branch) and it doesnt fix the warning.

**Comment by luisramos0** [comment]
Actually the patch does work! I am leaving it in this PR :-)

**Comment by luisramos0** [comment]
There are only 4 broken specs here, will work on this now.

**Comment by andrewpbrett** [comment]
Nice, that last spec is just flaky. Thanks @luisramos0! 🐒🐒🐒

**Review by andrewpbrett — APPROVED** [review]

**Comment by Matt-Yorkley** [comment]
Amazing! :heart_eyes: 

FYI; I think any app that's compatible with Ruby 2.7.x is technically compatible with Ruby **3.0.x**, but let's leave that for another day...

**Comment by luisramos0** [comment]
yes, but it looks like we need rails 6.1 first and then we can try ruby 3.

**Review by sauloperez — APPROVED** [review]

**Pull request merged**
