### PR TITLE
Fix supplier loading on Product & inventory report

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

I came across this when fixing #12768 
Not all supplier are loaded in the "Product & inventory" report  it's missing the suppliers of products distributed by the distributors the current user manages. As far as I could tell it wasn't covered by spec. 

#### What should we test?

Set up an enterprise user that can manage another enterprise, and create an order cycle including the managed enterprise products. Place an order including at least one of the managed enterprise products.

As an admin
- Visit Report page and choose Product & Inventory -> "All product"
- Check the managed enterprise is included in the supplier dorpdown

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice cleanup. I hope that nobody will be confused by additional data in the report. This may need running past the product team. Kirsten had doubts about the use of this report, didn't she?

Anyway, it seems a good change.

**Comment by RachL** [comment]
@mkllnk @rioug Kirsten was speaking about the bulk coop report.

Here I guess if no one has reported it, that the report is rarely used, but maybe this bug also prevented the use of it? If I understand clearly, a distributor with no product, but managing it's suppliers would never see data on it.

It makes sense to me that we show the data the user has access to. Otherwise we should hide the report from them. So I'm ok with moving forward with that PR :+1:

**Review by dacook — APPROVED** [review]
Great, I can see this is fixed thanks to the spec 💪 

From what I understand, it is now meant to be more accurate, and will now show only suppliers that I have distributed products for? Instead of all suppliers that I have access to? 
I don't see this new feature covered in the spec, but I don't know enough to judge how important it is...

**Comment by rioug** [comment]
The part that I fixed only affect the supplier dropdown, it should not display additional data in the report. It means that before a user was not able to filter by supplier from a product distributed by the distributor. 
It looks like it's not used much, no one has complained about it.

**Comment by filipefurtad0** [comment]
> It looks like it's not used much,

Opened an issue to track this [here](https://github.com/openfoodfoundation/Analytics/issues/14).

**Comment by drummer83** [comment]
# Work in Progress

| Managing | Permissions | Distributor dropdown | Supplier dropdown | Results with no filter |
| - | - | - | - | - |
| Producer 1 AU | | Producer 1 AU | Producer 1 AU | Products of ...
| Producer 1 AU + Producer 3 AU | No Permissions | Producer 1 AU + Producer 3 AU | Supplier 1 AU | 
| Producer 1 AU + Producer 3 AU | Permission to add to Order Cycles | Producer 1 AU + Producer 3 AU | Producer 1 AU + Producer 3 AU |

## Before
- User: producer@ko...
- Managing only 1 enterprise (Producer 1 AU)
  - Distributor dropdown: only Producer 1 AU available
  - Supplier dropdown: only Producer 1 AU available
  - Results with no filter:
    - Products of Producer 1 AU are shown
    - Products of Konrad Producer 5 AU are shown (through enterprise permissions)
  - Results with supplier filter for Producer 1 AU
    - Products of Producer 1 AU are shown
- Managing a 2nd enterprise (Producer 1 AU + Producer 3 AU) with permission to add to order cycle
  - Distributor dropdown: Producer 1 AU + Producer 3 AU available
  - Supplier dropdown: Producer 1 AU + Producer 3 AU available
  - Results with no filter:
    - Products of Producer 1 AU are shown
    - Products of Konrad Producer 5 AU are shown (through enterprise permissions)
    - Products of Producer 3 AU are shown (through enterprise managing)
- Managing a 2nd enterprise (Producer 1 AU + Producer 3 AU) WITHOUT permission to add to order cycle
  - Distributor dropdown: Producer 1 AU + Producer 3 AU available
  - Supplier dropdown: Producer 1 AU available
  - Results with no filter:
    - Products of Producer 1 AU are shown
    - Products of Konrad Producer 5 AU are shown (through enterprise permissions)
    - Products of Producer 3 AU are shown (through enterprise managing)

Check that enterprise is removed from supplier dropdown when set to non-producer.

**Comment by drummer83** [comment]
# Work in Progress

## After

| Managing | Permissions for Producer 3 AU | Distributor dropdown | Supplier dropdown | Results with no filter |
| - | - | - | - | - |
| Producer 1 AU | | Producer 1 AU | Producer 1 AU | Products of Producer 1 AU + Products of Konrad Producer 5 AU (through enterprise permissions) |
| Producer 1 AU + Producer 3 AU | No Permissions | Producer 1 AU + Producer 3 AU | Producer 1 AU | Products of Producer 1 AU + Products of Konrad Producer 5 AU (through enterprise permissions) + Products of Producer 3 AU (through enterprise managing) |
| Producer 1 AU + Producer 3 AU | Permission to add to Order Cycles | Producer 1 AU + Producer 3 AU | Producer 1 AU :exclamation: | Products of Producer 1 AU + Products of Konrad Producer 5 AU (through enterprise permissions) + Products of Producer 3 AU (through enterprise managing) * |

* If Producer 2 allows Producer 3 to add to order cycle, then products of producer 2 are listed as well.


- Check that enterprise is removed from supplier dropdown when set to non-producer :question:

**Comment by filipefurtad0** [comment]
Hey @rioug and @drummer83 ,

If I understand correctly, the last point to check is to:

> Check that enterprise is removed from supplier dropdown when set to non-producer ❓

I've verified that before and after this PR, a supplier which has:
- granted all rights to a hub
- is set to non-producer

Still appears on the dropdown of the report, as per pic below. Also, the pic shows a minor glitch, which is, if a producer is selected from the dropdown, but no distributor is selected, the report is not generated. I think this is a bug, but not a regression introduced by this PR:

image

Given all the work in the PR and the thorough tests from @drummer83 , I'd say this is good to merge. Moving it to ready to go for now, please let me know if you feel otherwise.

Thanks!

**Pull request merged**
