### PR TITLE
fix Missing products in Bulk co-op Packing Sheets report  

### LINKED ISSUE #9844: [Admin][Reports] Missing products in Bulk co-op Packing Sheets report
## Description
Some bulk products that have been ordered are not displayed in the Bulk co-op Packing Sheets report. 
And the "sum total" displayed is incorrect.

## Expected Behavior
There must be a line for each product, with the "sum total" for each product.

## Steps to Reproduce
1. Create 2 bulk products (products with the "group by option" set to yes)
2. Pass an order with these 2 products
3. Go to admin/reports/bulk_coop, choose "Bulk co-op Packing Sheets" report and see

You can also use shop 2735 on https://staging.coopcircuits.fr/

## Client1 ordered 1kg cacahuetes AND 1kg almonds
Screen Shot 2022-10-23 at 12 59 16

## Only almonds appear in the Bulk co-op Packing Sheets report 
Screen Shot 2022-10-23 at 12 58 42

## Severity
bug-s4: it's annoying, but you can use it

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #9844

#### What should we test?

- Described on: #9844

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Review by jibees — APPROVED** [review]
This is the solution we already discussed, so I'm probably not the right person to review it ;)

**Review by dacook — APPROVED** [review]
The code looks good to me :)

I didn't review the requirements in depth, but I can see that you and JB have. 
It would be good to have a test to specify exactly how this should be behaving, but I think fine to proceed without this time.

**Comment by drummer83** [comment]
## Things to test

- one customer (K2) buys different variants (V1 = 1, V2 = 2) of same product (KPS1-P1)
Before: :x: 
image
After: :heavy_check_mark: 
image

- one customer (K2) buys different variants (V1 KPS1-P1 = 4, KPS1-P2 = 8) of different products (KPS1-P1, KPS1-P2) 
Before: :x: 
image
After: :heavy_check_mark: 
image

- one customer (K2) buys one variant (V1 = 16) of one product (KPS1-P3)
Before: :heavy_check_mark: 
image
After: :heavy_check_mark: 
image

- one customer (K2) buys one variant (V1 KPS1-P1 = 32, V1 KPS1-P3 = 64) of different products (KPS-P1, KPS1-P3)
Before: :x: 
image
After: :heavy_check_mark: 
image

- more customers (K2, K3) buy different variants (V1 = 128, V2 = 256) of same product (KPS1-P1)
Before: :heavy_check_mark: 
image
After: :heavy_check_mark: 
image

- more customers (K2, K3) buy the same variant (V3) of same product (KPS1-P3 = 512, 1024)
Before: :heavy_check_mark: 
image
After: :heavy_check_mark: 
image

- more customers (K2, K3) buy different variants (V2 KPS1-P1 = 2048, V4 KPS1-P3 = 4096) of different products (KPS1-P1, KPS1-P3)
Before: :heavy_check_mark: 
image
After: :heavy_check_mark: 
image

- more customers (K2, K3) buy one variant (V1 KPS1-P1 = 8192, V1 KPS1-P3 = 16384) of different products (KPS1-P1, KPS1-P3)
Before: :heavy_check_mark: 
image
After: :heavy_check_mark: 
image

Overall summary:
Before: :x:
image

After: :heavy_check_mark: 
image

## Results
Wow, this is an awesome improvement and as far as I can tell, it's working perfectly! :+1: 
Thanks so much! 

## Notes
I observed one strange thing, but looking at your code changes I don't think this can be related:
After staging the PR the order edit page showed just amount '1' instead of 64 (as indicated in the confirmation email and according to the price calculation). It stayed like this after refreshing the page as well. Editing the amount from '1' to '2' brought back the '65' (so original amount of '64' increased by '1'). 
Peek 2022-12-02 17-00

**Comment by drummer83** [comment]
I found no way to reproduce the strange issue. So not investigating further.

**Pull request merged**
