### PR TITLE
Fix snail issue for all shipping method fees

### LINKED ISSUE #8249: Snail when editing non-numeric characters on shipping method fees
## Description

In all things similar to #6942, but concerning shipping method fees.

Updating a shipping method can cause a server error when entering invalid values.

## Expected Behavior

Invalid values should not be allowed or there should be a proper error message.

## Actual Behaviour

It shows the snail.

## Steps to Reproduce

1. Edit a shipping method.
2. Select the "per item" calculator.
2. Enter `'20.0'` with the single quotes as fee amount.
3. Click Update.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

* Version used: v4.1.2
* Browser name and version: Firefox 92
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

The only figures that should be allowed are:
- numbers 0123456789
- decimal point .
- negative sign -

The error message should read:
Invalid input. Please use only numbers. For example: 10, 5.5, -20

See [PR which introduces a fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/8204) for a similar issue, regarding transaction fees.

### PR DESCRIPTION
**Pull request by vsmay98**
#### What? Why?

Closes #8249 

#### What should we test?

flat percent --> snail
flat rate (per order) --> OK
flexible rate --> snail
flat rate (per item) --> OK
price sack --> snail
weight (per kg or lb) --> probably snail

As an Admin:

- edit a shipping method
- on the calculator section choose one of the calculators marked with "snail" above
- click update
- type in an invalid value (e.g. some text or numbers with comma as separator)
- click update --> snail

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by vsmay98** [comment]
This PR is ready for review.

**Comment by vsmay98** [comment]
Hello @drummer83 
Could you please get this PR review?

**Review by mkllnk — CHANGES_REQUESTED** [review]
This looks like a good solution. Can you fix the remaining Rubocop warning?

**Comment by vsmay98** [comment]
Done @mkllnk Please re-review

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]
Thanks!

I'd squashed all of those 3 commits to avoid _fix rubocop warning_ commit.

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @vsmay98,
Thanks for this pull request!

I have first made sure that I can still reproduce the issue on our staging server. 
**Before** your PR the situation was like this:
- flat percent --> snail
- flat rate (per order) --> OK
- flexible rate --> snail
- flat rate (per item) --> OK
- price sack --> snail
- weight (per kg or lb) --> snail

**After** your PR I tested again:
Peek 2022-10-20 12-10

In the screen capture I always used the string 'invalid' as input but I have also tested:
- numbers with comma separator :heavy_check_mark: 
- numbers with two '-' signs :heavy_check_mark: 
- numbers with leading spaces, trailing spaces or spaces in between :heavy_check_mark: 
- quotes ' and " :heavy_check_mark: 

For the different calculators we now have:
- flat percent --> OK
- flat rate (per order) --> OK
- flexible rate --> OK
- flat rate (per item) --> OK
- price sack --> OK
- weight (per kg or lb) --> OK

Worth mentioning:
- For 'Flexible rate' the amount value is not validated as other fields, but it is set to '0' for invalid input while for 'Price sack' the amount values are validated as other fields - the error message is displayed for invalid input. Flexible rate should do the same.
- Invalid input field(s) should be highlighted (red border of input field) and all other updated information should be kept (including description, tags, display, ...)
- Flat rate (per order), Flexible rate, Flat rate (per item), Price sack: remove currency setting (the amount is considered the instance's currency anyway)

This is looking really great and it's removing quite a few snails at one shot. :boom: 

We are ready to go here and I will create a follow-up issue for the topics of 'worth mentioning' (probably later today). Maybe you would like to continue you great work on this!

Thanks again! :partying_face:

**Pull request merged**
