### PR TITLE
Split checkout design changes part 1

### LINKED ISSUE #10146: Split checkout design changes part 1
## Description
**- As a:** shopper with split checkout activated
**- On page:** checkout process
**- I want to be able to do:** 

- [x] Stop underlining the step title before the step occurred: if there is no link, there shouldn't be any underlining

- [x] Stop underlining bold title:

- [x]  Use two columns for fields. 
Capture d’écran 2022-12-13 à 12 22 08

- [x]  for all filelds, remove title and keep only placeholder

- [x] Instead of "your details", a contact details start the process (first name and name are moved to "billing address"): 

Apart from this billing address remains unchanged

- [x] When selecting a **shipping or payment** method, let's put the description _under_ the radio button that is selected and not _under_ the full list of shipping method

- [x] Grey button can be interpreted as disabled, let's move them to white background with red text and border

- [x] Price of shipping method and payment method are harmonized: italic+bold+bracket

## Acceptance Criteria & Tests

1. Enable split checkout
2. Check the items above have changed

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10146
Capture d’écran 2022-12-15 à 15 13 24

screencapture-localhost-3000-checkout-details-2022-12-15-15_13_33

#### What should we test?

- As a shopper, with feature toggle activated, check that new design is well implemented regarding the linked issue.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by abdellani** [comment]
I like the idea of moving the label to the top : )
This branch needs a rebase.
I have one question: 
https://github.com/openfoodfoundation/openfoodnetwork/issues/10146
>  Stop underlining the step title before the step occurred: if there is no link, there shouldn't be any underlining

I don't see the different before and after the PR. Are we talking about the gray/green underline?
image

**Comment by jibees** [comment]
> > Stop underlining the step title before the step occurred: if there is no link, there shouldn't be any underlining
> 
> I don't see the different before and after the PR. Are we talking about the gray/green underline?

We are talking about that white underlying:
Capture d’écran 2022-12-27 à 10 32 34

But you're right, I cannot see any underlying for the previous step.


@abdellani when code reviewing, we usually don't do extensive testing (and see if it fit the acceptance criteria) ; we _only_ read the diff, the commit messages, and see if it fits our rules, see if no regression... 


Will do the rebase, thanks!

**Comment by jibees** [comment]
Rebased!

**Review by abdellani — APPROVED** [review]

**Comment by abdellani** [comment]
>  when code reviewing, we usually don't do extensive testing (and see if it fit the acceptance criteria) ; we only read the diff, the commit messages, and see if it fits our rules, see if no regression...

Ok, this will make things much easier :)

**Comment by RachL** [comment]
@jibees one thing is not working as it should: 

Payment method description is appearing correctly just after the radio button, but for shipping method, the first time they didn't appear at all. Then I went back to details and this showed up: 

image

And if I select Home delivery, the position of the description remains the same: 

image

I think it's correct because both don't have description. But I guess we forgot we are displaying the "ready for" field in this box. So we need to apply the behavior of the description to the ready for field as well. Can we also fix the size of the grey box (fit to text with margins?).

Also - but this might be something I have forgotten when writing the issue: when selecting Stripe as payment method, the stripe boxes appear at the end of the form. Can we make them appear after the Stripe radio button? 

image

Finally, regarding underlying, I think in this case: 

image

We can underline "Your details" because there is a link on it. But we can fix this in a future PR as well.

**Comment by jibees** [comment]
@RachL Done!

Capture d’écran 2022-12-28 à 15 37 11

Capture d’écran 2022-12-28 à 15 37 39

**Comment by RachL** [comment]
Marvelous!

Now only waiting for the design on the order confirmation page to create issue for part 2 and then we are ready to re-roll-out Split checkout :exploding_head:

**Pull request merged**
