### PR TITLE
Add support for enterprise time zones

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

See https://community.openfoodnetwork.org/t/allow-enterprises-to-set-their-own-time-zone/2058

and

https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1600561652011600

This is the minimum viable feature version of a solution to the problem. We could consider going further by:

- Noting when a user's browser is using a different time zone than the enterprise(s) they are managing and directing them to the settings page to change it
- Improving the Order Cycle datetime picker to make it more obvious that the open/close times are in a specific timezone at all (I've created dozens of order cycles and never noticed the timezone offset at the end of that string, even though it's very obvious now)
- Add support to other object (besides Order Cycle) that rely on times: `Order.completed_at, Product.available_on, Shipment.shipped_at, Subscription.begins_at, Subscription.ends_at, Subscription.canceled_at, Subscription.paused_at`

#### What should we test?
- Existing order cycles should still have the correct time zone after this code is merged
- An enterprise's order cycles should remain at the same absolute time if the enterprise changes its timezone. For example, if an existing order cycle closes at midnight (GMT -7), and the enterprise changes its timezone to one that's GMT -4, the order cycle should close at 3 am in the new time zone. 

#### Release notes
Added support for enterprises to set their own time zone and set the open/close times of their order cycles in that time zone. 

Changelog Category: Added

#### Discourse thread
https://community.openfoodnetwork.org/t/allow-enterprises-to-set-their-own-time-zone/2058

#### Documentation updates
Yes - the order cycle page could be updated to alert people to double check the time zone when setting up order cycles.

### CODE REVIEW

**Review by luisramos0 — COMMENTED** [review]
wow, nice one!

Can you please create an issue on GH for this one? I think it's better to discuss the request there and not here. We need to investigate potential problems this may cause, off the top of my head I can think of three:
- order_cycle dates will impact subscriptions
- order dates will impact reports
- order_cycle dates will have to be read by the shopfront with timezone so that the shop closes at the correct time, right?

**Comment by RachL** [comment]
@andrewpbrett I would like to move the issue to the inception-pipe repo so we don't forget we need to come back to this at some point. I was about to transfer the issue when I realize
Would it be ok for you if I:
- create an issue
- Close this PR and link it inside the new issue?

**Comment by andrewpbrett** [comment]
Yes please and thank you @RachL!

**Comment by RachL** [comment]
Issue created here: https://app.zenhub.com/workspaces/product--inception-pipe-5f82e534db531f000f8c09ff/issues/openfoodfoundation/inception-pipe/31

**Pull request closed without merging**
