### PR TITLE
Oeoeaio/uk/1031 insufficient stock in cart

### PR DESCRIPTION
**Pull request by jeronimo**
#### What? Why?

This is extension to PR https://github.com/openfoodfoundation/openfoodnetwork/pull/1583 as issue has appeared:

1. a variant is in the user's cart
2. the user logs out
3. the variant is removed completely from the order cycle (not just stock reduced)
4. the user logs back in

Approach:
Validation method inside order model seemed more appropriate way but there were so many tests failing and fixing that looked like very time consuming thing so this approach has been chosen.

P.S. was not sure about naming on methods so please give better ones if you have any in mind.

#### What should we test?

Checkout process when incoming/outgoing products get unselected in admin order_cycles edit page.

#### How is this related to the Spree upgrade?

Hopefully it is not related unless later Spree versions has Orders implemented already with double check of this functionality.

#### Dependencies

Extension of https://github.com/openfoodfoundation/openfoodnetwork/pull/1583
And follow up of https://github.com/openfoodfoundation/openfoodnetwork/pull/1477

### CODE REVIEW

**Comment by sauloperez** [comment]
> Validation method inside order model seemed more appropriate way but there were so many tests failing and fixing that looked like very time consuming thing so this approach has been chosen.

How did validation looked like? To me the validation does seem like the way to go rather than having to pollute the application controller. What about ensuring there are no orders still to be completed  that have that variant in their line items when removing it from the order cycle? I'd then tell the admin through a flash error message.

**Comment by jeronimo** [comment]
Cool! @sauloperez, @enricostano, may I assume that you will take this issue out of me, will analyse all requirements and whole situation again and will do it properly?

**Comment by enricostano** [comment]
@jeronimo maybe we can discuss about it quickly on mumble, what do you think? Just to be on the same page and better understand the context. Is that OK for you?

**Comment by Matt-Yorkley** [comment]
For reference, this is the latest PR for #1031.

**Comment by daniellemoorhead** [comment]
>For reference, this is the latest PR for #1031.

@Matt-Yorkley should this PR be closed then?

**Comment by daniellemoorhead** [comment]
Moved to September dot point release.

**Comment by lin-d-hop** [comment]
Hi @enricostano 
Could you just leave a wee update on the latest?
Maybe we could have a chat and we can respec the issue to assign to someone new?
Cheers,
Lynne

**Comment by oeoeaio** [comment]
For my own reference, potentially related to [this](https://github.com/oeoeaio/openfoodnetwork/commit/4443229066983f8ff07c6c0dd3b5cbd21859e237)

**Comment by enricostano** [comment]
@sauloperez can we work on prioritizing this? Maybe we can help in some way.

**Comment by myriamboure** [comment]
@enricostano @lin-d-hop what shall we do with that PR ? Shall we just#1031 into an icebox item, so that it gets specced properly when we prioritize it ? And for the bug #1491 shall we wait for it to be prioritized before we work back on this?

**Comment by myriamboure** [comment]
Do I understand well: this one is blocked by #1767 so we can't review and merge before we have moved forward the other one which is in dev, right?

**Comment by myriamboure** [comment]
Will reopen when #1491 is priorized, incepted and solve, and then we can work on #1031. So closing for now.

**Pull request closed without merging**
