### PR TITLE
Improve readability of shop's code

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

While investigating how a shop is rendered I found a number of things that ought to be cleaned up and be a bit more readable.

Also, you will see I removed a Bugsnag notification. In the related commit message you will find the reason why.

### CODE REVIEW

**Comment by sauloperez** [comment]
No need for testing here. What label should I add then?

**Comment by oeoeaio** [comment]
Thanks @sauloperez. Seeing as there has been a change to a functional part of the code I would like to test this if that is ok?

I tend to agree with your assertion that error tracking should not be used for monitoring cache misses, but I am reluctant to just burn our existing approach until we have a replacement solution in place.

**Comment by sauloperez** [comment]
> Seeing as there has been a change to a functional part of the code I would like to test this if that is ok?

As you wish, I just see that the change is fully covered by lots of tests.

> but I am reluctant to just burn our existing approach until we have a replacement solution in place.

We need to understand whether you guys actually use that information and how

**Comment by sauloperez** [comment]
I opened an issue to address the cache monitoring https://github.com/openfoodfoundation/openfoodnetwork/issues/1949 so that we reach a consensus here.

**Comment by daniellemoorhead** [comment]
>We need to understand whether you guys actually use that information and how

We get notifications from Bugsnag, and there are also GitHub issues created for some of them (not sure what triggers that because it's not for every event, @mkllnk or @oeoeaio would know). Each time we get a message we are sad because we don't have the time to focus on solving them.

**Comment by sauloperez** [comment]
@oeoeaio do you still want to test this? IMO being the injection helper we would have noticed in the integration tests if it was broken, but otherwise we can take a look ourselves.

**Comment by sauloperez** [comment]
Tested and working. The refactored method is used in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/helpers/injection_helper.rb#L68 which renders the orders successfully as you see below.

injector

**Comment by daniellemoorhead** [comment]
@oeoeaio this has been tested so ready to merge if you're happy to approve code review.

**Comment by sauloperez** [comment]
cc @oeoeaio

**Pull request merged**
