### PR TITLE
When searching for shop products check the variant :display_name and :display_as fields too

### LINKED ISSUE #5757: The shopfront search doesn't find display names of variants
## Description

When a variant has a unique display name and you search for it in the shopfront, no products are shown.

## Expected Behavior

Products are found by a variant's display name

## Actual Behaviour

Display names are ignored by the search.

## Steps to Reproduce

1. Create a variant with a display name "Marmelade" but don't call anything else in the product like that.
2. Go to the shopfront and type "Marm"
3. No product is shown even though the product with "Marmelade" should show.

## Animated Gif/Screenshot

Search

## Workaround

Use the browser's search function.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.1.0

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

Closes #5757

#### What should we test?

See _Steps to Reproduce_ in #5757

#### Release notes

Fix shop product search so it finds products by their variant names too.

Changelog Category: Fixed

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]
:ok_hand: thanks @cillian

**Review by Matt-Yorkley — APPROVED** [review]
:muscle:

**Comment by filipefurtad0** [comment]
Hey @cillian ,

I had a look this before and after the PR.

Before staging:

cant_find_variant_nme


After staging:
CAN_find_variant_name

Did a brief sanity check on the search field on openstreet maps as well - these search fields are related in the app, right? - all good here as well.

Thank you for this fix! Ready to go.

PS: I was unaware of the "Pending" status one can attribute to certain test cases. Interesting!

**Comment by cillian** [comment]
Hey @filipefurtad0 the OSM search map shouldn't be affected from this change but thanks for checking anyway :+1:

**Pull request merged**
