### PR TITLE
Admin, Orders list: new actions dropdown for bulk invoice printing

### LINKED ISSUE #9316: Implement new action dropdown for (bulk) invoice printing
## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/orders`
**- I want to be able to do:** see the new action dropdown on the list of orders. 

The scope here is just to introduce the new design. It means the dropdown will only have one action : **Print invoice**. After that, other issues will cover other actions.

Design is located here : https://www.figma.com/proto/PBNUA4ygpTiI1PUg51K9Yl/44-Select-Multiple-Orders?page-id=2%3A3&node-id=2%3A28&viewport=326%2C48%2C0.33&scaling=min-zoom&starting-point-node-id=2%3A28

**Current design shows a confirmation modal. This modal is not needed for invoice printing and the current modal should stay in place.**

## Acceptance Criteria & Tests

1. Log in as enterprise
2. Go to `/admin/orders`
3. Select orders: see the count is correct
4. Actions => Print invoice
5. See modal (same behavior than in production)
6. PDF open in new tab with only invoice selected
7. Filters work as usual, same for number of result per page.

Repeat as superadmin.

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9316
Capture d’écran 2022-06-28 à 18 12 54

Capture d’écran 2022-06-28 à 18 13 00

#### What should we test?

- As an admin, visit `/admin/orders` page
- See that Actions dropdown is grey, unusable
- Select one a many order(s)
- See that Actions dropdown is now usable, and you can print invoices

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
> If you have any idea...

I'll try to understand what's happening. Thanks for reaching out :pray:

**Comment by jibees** [comment]
Ok, this fails on my setup, but not on CI. Maybe a resources compilation error ?

**Comment by filipefurtad0** [comment]
Here's what I did to check this spec:
- pulled this branch and its latest commit
- on `cuprite_setup.rb` set `headless: false`, to actually "see" what's going on
- added a `byebug` between each of the four tests (lines 113, 117, 121, 125)

Everything looks :ok_hand:  

Then,
- reset to the latest commit as well with `git reset --hard 8ba59079b3603a9ec0e41f01734f1856115917a1`
- and ran the spec 10 times, to check flakyness with:
```
for i in `seq 10` ; do bundle exec rspec spec/system/admin/orders_spec.rb:111; [[ ! $? = 0 ]] && break ; done
```

Got only greens :green_apple: 
I think were good!

**Review by mkllnk — APPROVED** [review]
Nice.

**Comment by jibees** [comment]
> Got only greens 🍏
> I think were good!

Thanks @filipefurtad0 ! 🙏

**Comment by jibees** [comment]
>  should we still be able to print cancelled orders?

Regarding the behavior you described, it seems to me like an incoherence, for sure ;)

**Comment by RachL** [comment]
@filipefurtad0 this actually echos another wishlist item we've just received this week in FR. I will work on a combined wishlist for our next papercut meeting :+1:

**Comment by RachL** [comment]
I've made a proposal here: https://github.com/openfoodfoundation/wishlist/issues/261

**Pull request merged**
