### PR TITLE
Error messages that are prompted when altering account settings are now fully translated

### LINKED ISSUE #7182: Missing translation in user account
## Description

When changing email or password, and not typing correctly the password twice, the error message shown is only partially translated

## Steps to Reproduce

1. Login as a shopper, manager, whatever!
2. Go to Profile > Account > Setting
3. Change the email address and hit save
4. See the error message

## Workaround
Learn english

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.6
* Browser name and version: All
* Operating System and version (desktop or mobile): both

### PR DESCRIPTION
**Pull request by KyleGericke**
#### What? Why?
Currently, if a user is altering their account settings and either type a password confirmation that doesn't match their password or type a password that is shorter than 6 characters (the minimum length) they are shown the following text. The issue is that non English languages have a partial translation (as shown below). This should now be fixed.

Screen Shot 2021-04-21 at 12 12 23 AM

Closes #7182

This change is needed to ensure a full translation when users receive errors when altering their account settings. We solved this by substituting the correct translations into the error message strings when creating the bulleted list (As shown below)

Screen Shot 2021-04-21 at 10 55 59 PM

#### What should we test?

- All languages have a fully translated error message when "Password confirmation doesn't match Password"
- All languages have a fully translated error message when "Password is too short (minimum is 6 characters)"

#### Release notes
Error messages that are prompted when altering account settings are now fully translated

Changelog Category: User facing changes

### CODE REVIEW

**Review by Matt-Yorkley — CHANGES_REQUESTED** [review]
Ah, so there's a couple of things here with how our translations work that are not immediately obvious.

Firstly, we manage translations with an external service called Transifex. Long story short, when we're adding a new translation in the code, we only add it to `en.yml`, and then the others are populated later via the service. So no manual changes are committed in the other translation files.

Secondly, I don't think we can use this `gsub` implementation to switch out the strings, it should be handled by the I18n module. I think the issue here is that we need to define a translation key for the `password` attribute of the `Spree::User` model, which looks a bit like this: https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

**Comment by KyleGericke** [comment]
Hi, sorry about all the problems I'm having, I'm very new to ROR. I've been looking at the en.yml file for a while to see how it is used to render the account settings page and I have a few questions if you have some time. 

First, if a key doesn't exist in the YAML file, how is that field generated? For example, in the snippet below "password_confirmation" does not exist in en.yml, so how is this rendered? 
Screen Shot 2021-04-22 at 1 37 21 PM

Second, when adding the error messages to the bulleted list we loop through target.errors.full_messages (where target is spree_user). Similarly to the question above, I am unable to find these messages in the en.yml file so I'm a little confused where these strings are coming from. (Here's the code for reference)
Screen Shot 2021-04-22 at 1 40 05 PM

Sorry for all the questions! If this is something that should be discussed on Slack instead I can send a message on there.

**Comment by Matt-Yorkley** [comment]
> I'm very new to ROR

No problem :ok_hand: 

> in the snippet below "password_confirmation" does not exist in en.yml

It's in there, check line 339 :wink:

> we loop through target.errors.full_messages ...

So the issue here is that those errors are actually being created somewhat automatically in the _backend_, and when the object is passed to the view the errors have already been created and added to the object. So there's not an obvious place where those error messages can be manipulated from within the view.

If you look at lines 20-30 you'll see this:
```yaml
en:
  # Overridden here due to a bug in spree i18n (Issue #870, and issue #1800)
  language_name: "English" # Localised name of this language
  activerecord:
    attributes:
      enterprise_fee:
        fee_type: Fee Type
      spree/order:
        payment_state: Payment State
        shipment_state: Shipment State
```
I think if we add a `spree/user:` node and define those attributes like `password: "Password"` under it, then ActiveRecord will pick up the translation keys when it's assigning errors on those attribute for the `Spree::User` model. Eg:
```yaml
   ...
   activerecord:
     attributes:
       spree/user:
         password: "Password"
         password_confirmation: "Password confirmation"
```

**Review by Matt-Yorkley — APPROVED** [review]
Great :+1:

For bonus points you could squash the 5 commits into 1 commit

**Comment by KyleGericke** [comment]
I tried to squash the commits via "git rebase" but it didn't work, it just added more commits to this pull request. Sorry about that! I can try again but I don't want to keep adding unnecessary commits.

**Comment by andrewpbrett** [comment]
Hi @KyleGericke - thanks for this contribution! I noticed that one of the seven commits just added the keys, so I cherry-picked it onto a separate branch and made a new PR for it https://github.com/openfoodfoundation/openfoodnetwork/pull/7693 - hope you don't mind :) I'm going to close this PR in favor of that one but you still show up as the author of that commit.

**Pull request closed without merging**
