### PR TITLE
Increase space for buttons in savebar layout

### LINKED ISSUE #4503: New OC bottom page buttons do not fit well with long text
## Description

When translating the button in French for example, the text is longer, leaving the buttons to display like this:

French:

Spanish:

Instead of:

## Steps to Reproduce

Make sure to check a non English instance.

1. Go to `/admin/order_cycles/`
2. Create or edit an OC
3. See bottom buttons

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v2.6.4
* Browser name and version: Firefox 70
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #4503 

Increases space for buttons on the right hand side of the admin savebar to accommodate for different sizes due to translations.

#### What should we test?

Save bar buttons on the OC edit page are rendering ok in different languages.

#### Release notes

Fixed layout issue with save bar buttons in different languages

Changelog Category: Fixed

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Ah, it works in Spanish, but not French. Do we need all these buttons crammed into this space? The savebar was designed to have two buttons, and now it has five.

I tried adding some padding and keeping them on multiple lines but it doesn't look good...

**Comment by luisramos0** [comment]
yeah, do you have a suggestion @Matt-Yorkley ? I think the "previous" button is the least useful. we could drop it now that the steps are clickable above...
could you paste a screenshot with the 5 buttons in French spanning 2 lines with padding?

@RachL could we have shorter French translations? Maybe just "retour" on the last one?

**Comment by Matt-Yorkley** [comment]
Lets drop the "previous" button for now. I think that's the best option here. :+1:

**Comment by RachL** [comment]
FR:

image

IT:
image

I didn't tested in Spanish or Portuguese because it is actually not translated yet. Ping @sauloperez @luisramos0 maybe you will want to have a look some time on Transifex.

Looking good in FR and IT. Moving to ready to go! Let's see how user react to the previous button being gone.

**Pull request merged**
