### PR TITLE
Enterprise Terms of Service

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Addressing issue #1211.

Added config options for Enterprise Terms of Service, defaulting to disabled (not required).

Reworked frontend registration form to:

- Show terms of service message and checkbox if Spree::Config[:enterprises_require_tos] is enabled.
- Hide if not.
- Disable "Lets get started" button if Spree::Config[:enterprises_require_tos] is enabled and accept checkbox is not checked. Re-enables when checked.

Added translation entries in en.yml and en-GB.yml.

### CODE REVIEW

**Comment by oeoeaio** [comment]
Hey mate, just so I know that you know: you can just keep pushing commits into an existing PR branch in your repository and they will update here automatically. Not sure if that is the reason you resubmitted this one or not, but there you have it. Took me ages to work that out myself. I find it quite cool because by then I can submit changes as a new PR against the PR source branch on your fork (ie. `Matt-Yorkley:enterprise_tos`), and you can just approve the merge in GitHub if you're happy and they come straight through to here. :) Sorry if that was explaining something you already had down...

**Comment by lin-d-hop** [comment]
@oeoeaio Likely it was because we triggered builds on buildkite for PRs on branches matching uk/* 
I set this up and then asked people to recreate some branches that didn't match the pattern.

**Comment by oeoeaio** [comment]
Ah, sorry. My bad.

**Comment by Matt-Yorkley** [comment]
@oeoeaio is there any more reviewing to be done for this one? I've just added a final UX tweak from testing feedback. I think it's all finished... :)

**Comment by oeoeaio** [comment]
@Matt-Yorkley yep, I think so. @sstead is this on your radar?

**Comment by oeoeaio** [comment]
@Matt-Yorkley note that I've just rebased this onto the current version of master, so you'll need to pull this down again as a fresh branch if we need to make any changes.

Just as a matter of process, would you prefer that I not rebase your PR branches? Would it have been better for you if I had just created a new PR, closed this one and and mentioned here that this one has been superseded?

**Comment by Matt-Yorkley** [comment]
@rob Yeah, that's fine. I'm not sure what's the best process, I guess the superseding option is less likely to cause accidental branch-overwriting problems?

**Pull request merged**
