### PR TITLE
Fix- chore(deps): bump debounced from 0.0.5 to 1.0.2

### PR DESCRIPTION
**Pull request by wandji20**
Bumps [debounced](https://github.com/hopsoft/debounced) from 0.0.5 to 1.0.2.
- [Release notes](https://github.com/hopsoft/debounced/releases)
- [Commits](https://github.com/hopsoft/debounced/commits/v1.0.2)

---
updated-dependencies:
- dependency-name: debounced dependency-type: direct:production update-type: version-update:semver-major ...

#### What? Why?

- Closes #12281 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] Technical changes only

The title of the pull request will be included in the release notes.

#### Dependencies
N/A

#### Documentation updates
N/A

### CODE REVIEW

**Review by dacook — APPROVED** [review]
Thank you!

**Review by dacook — CHANGES_REQUESTED** [review]
Actually, I'm not sure if we're even using this plugin. According to the [readme](https://github.com/hopsoft/debounced), it emits new events with names prefixed by `debounced:`. 
We don't have this word in our code anywhere, and I don't see it mentioned in `yarn.lock` as a dependency. 

... I just checked commit history: it was added for search_input_component, which was later removed (3b68674896bc5ebedfb0314ce3e685e46c4a3e4b)

So we can actually remove it! Would you be willing to try that instead?

**Comment by wandji20** [comment]
Thanks for bringing this point up @dacook

If I understand correctly, calling `debounced.initialize({ input: { wait: 300 } });` should only delay firing `input` event listeners on every keystroke. So I doubt we should expect to see some `debounced:input` in the code.

Also, I tried looking around to see if we had some kind of search input field for making a network request but found none on the admin screens.

However, we already have `_debounce` provided by the `loadash` library so we can make use of it just in case

**Comment by dacook** [comment]
Thank you!

> If I understand correctly, calling `debounced.initialize({ input: { wait: 300 } });` should only delay firing `input` event listeners on every keystroke. So I doubt we should expect to see some `debounced:input` in the code.

I also thought this at first; that the plugin could be intercepting the native events and affecting all inputs. But then I found this commit which proves that it fires _additional_ events, which you need specific event handlers for: 122677bc7a8

After seeing that, and `SearchInputComponent` later removed again, I was confident we can remove this.

**Review by dacook — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
Great outcome! :tada:

**Pull request merged**
