### PR TITLE
Add some require statements to specs

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

These requires are needed in the 3-0-stable build.

#### What should we test?
no tests needed apart from a green build.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
This is totally blocking the current 3-0 build, right?

**Comment by luisramos0** [comment]
yes, it breaks it badly.
to avoid these errors, you can use the 3-0-latest branch to work on the upgrade:
https://github.com/openfoodfoundation/openfoodnetwork/pull/4825

**Comment by Matt-Yorkley** [comment]
When I was looking at this before I ended up doing the exact same thing; having multiple branches and a big "all the changes together" branch, but it was a bit of a mess...

**Comment by Matt-Yorkley** [comment]
Is there some underlying reason why these files are no longer being loaded as expected..?

**Comment by luisramos0** [comment]
"having multiple branches and a big "all the changes together" branch, but it was a bit of a mess..."
that's how I worked most of the time in the last upgrade. I kept a little map of branches and what was already in the "latest" or not. It'ss quite important because we need code review and at the same time you want to be looking at the edge.

re this PR, I dont know why this is a problem in 3-0-stable...

**Comment by sauloperez** [comment]
The way we decorate Spree classes in OFN and the fact that we brought Spree code recently, this change doesn't surprise me. I wouldn't even bother finding the root cause, tbh :man_shrugging:

**Comment by luisramos0** [comment]
awesome, I'll merge master into 3-0-stable now :tada: New PR coming in a minute.

**Comment by sauloperez** [comment]
weird. I couln't merge it myself even with three attempts :thinking:

**Comment by luisramos0** [comment]
github is a bit unstable these days...

the merge PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/4861

**Pull request merged**
