### PR TITLE
Add OIDC authentication for Les Communs

### LINKED ISSUE #8922: As a user with an OFN account, I want to be able to login with my LesCommuns account
Merging https://github.com/openfoodfoundation/openfoodnetwork/issues/5220 and https://github.com/openfoodfoundation/openfoodnetwork/issues/5221

## Description
**- As a:** enterprise who has an account on both OFN and les communs account
**- On page:** `/#/login`
**- I want to be able to do:** I want to be able to login with lescommuns. **User creation is out of scope here.**

A small demo on how it is working on another platform: https://www.loom.com/share/1a61cd8972fa4e3eb1566da4b2fc679c

## Acceptance Criteria & Tests

As tester we want to be able to see the following if the feature toggle in #8195 is turned on:

1. When visiting `/#/login` on a staging server where you would have created an account with the email testdfc@protonmail.com (FR staging is set up) I should see: 

image

**Except the text should not be red it should be grey to not attract user attention too much.** OFN grey is `#555555`

2. When clicking on the link, I should be redirected to this page (URL looks like https://login.lescommuns.org/auth/realms/data-food-consortium/protocol/openid-connect/auth?scope=openid+profile+email&response_type=code&redirect_uri=https%3A%2F%2Fsecure.socleo.org%2Fauth%2Fauthorize%2Flescommuns&code_challenge_method=S256&prompt=consent&client_id=socleo&code_challenge=6-D8UCbxW8--C279y6SrFilIJJZzItGEwU6sIi0Omd8 )

image

3. When login in with test DFC user (credentials in bitwarden) I should be redirected back to OFN home page, but logged in this time (as I would if I had used OFN to login).
4. If there is another staging server that has this same account, when visiting that staging server on the same browser I should be logged in automatically.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Part of:
* #8922

#### What should we test?

- You'll need an account with Les Communs set up in advance
- Currently you should be able to test on French Staging
- Log in as an enterprise/admin user and go to `/admin/oidc_settings`
- Confirm your login in the Les Communs portal
- Your user account should be connected

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by RachL** [comment]
@Matt-Yorkley https://staging.coopcircuits.fr/admin/oidc_settings works for me when I'm loggedin with superadmin credentials:

image

But if I login with testdfc[at]protonmail.com I get an unauthorized message (even when I login first on oidc). Credentials for this account on fr staging are the same than for oidc.

image

**Review by mkllnk — APPROVED** [review]
I think that this part is ready now.

**Review by jibees — APPROVED** [review]
💪

**Comment by RachL** [comment]
@mkllnk here are the tests I did:

1. Login to staging FR with testdfc[at]protonmail.com (login in bitwarden) => account is correctly linked (was linked in previous tests) :tada:

2. Then I used my email for release testing rachel.arnould+release on protonmail, I created a new account on les communs and I could link the two accounts :tada:

3. So here I was confident this is working, I then started recording a video for the rest of the testing team using a new producer hub email started from scrach (rachel.arnould+newhub)

But then when I'm trying to link, i get an error 422.... do you know why?

Link to video: https://www.loom.com/share/07f4c02973474d7abc1ac1199d1a9b19?t=120

**Comment by jibees** [comment]
I suppose this is your stacktrace: 
https://app.bugsnag.com/open-food-france/coopcircuits/errors/634fd389f606d800099f3d43?event_id=634fd389009a613ba50a0000&i=sk&m=nw

Is the hour corresponding? (around 12h38)

**Comment by RachL** [comment]
@jibees yes the time looks correct

**Comment by mkllnk** [comment]
The error says that the UID is already in use. That's the email address which we enforce to be unique. Each account can be linked only once. On OFN you used `+newhub` but did you log into the same account with Lescommunes?

Two options:

* Provide a better error message and enforce that each account is used only once.
* Drop that constraint and allow linking to several OFN accounts. I'm just not sure if that can be a problem later. If you log into Lescommunes and then navigate to OFN to say "login with Lescommunes" then it can't log you in straight away. It would need to ask you which account you want to log in with.

**Comment by RachL** [comment]
thanks @mkllnk it's indeed possible I didn't logged out properly after all my tests.

The clean error message is not urgent, let's leave it for later.

FYI also for @lin-d-hop @RaggedStaff what didn't made me thing to test the log out is that for other competitors, the implementation of OIDC acts like a real SSO within the same browser: if I login on Les communs, I'm instantly login on their platform and reverse.

During our chat on Wednesday I'll be briefly interested to understand more about where these differences can come from.

**Comment by mkllnk** [comment]
> the implementation of OIDC acts like a real SSO within the same browser: if I login on Les communs, I'm instantly login on their platform and reverse.

We could do that as a next step to automatically log in. Well, if you are not logged into OFN then you need to click the "log in with Les Communes" button and it would do that. I'm not sure about the reverse though. It may be handled by the library we use. I'm not sure.

**Pull request merged**
