### PR TITLE
Adding packing reports as required by the UK contingent

### PR DESCRIPTION
**Pull request by lin-d-hop**
Hiya @RohanM @kirstenalarsen @oeoeaio 

Would y'all mind finding time to have a look over this one.

I've used the search options of the Orders and Fulfilments reports. At the moment it is essentially a cut and paste. I wanted to get this working before undertaking the next step:
-> Refactoring this with the order cycle management reports and orders and fulfilments to separate out the repeated code.
After this I'd like to do a bit of refactoring of the Reports Controller Decorator to:
-> Strip out some of the clunkiness of the reports that use the order grouper and put them into their own lib/report classes

If you guys are happy with that I'll create myself some issues. Basically I'm telling you all that here as I expect feedback on these changes to comment on the repeated code. So I wanted to let you know how I intend to break up that chunk of work :-)

Thanks guys! Hope it's all going well before the launch.... should I ask? xx

### CODE REVIEW

**Comment by RohanM** [comment]
Hi Lynne,

This is looking good! Looks like there's a solid pattern to follow. Is it coming along smoothly?

As a side note, it seems like there's a lot of boilerplate involved with writing any report, and I'd like to made it cleaner. I think a major refactor of the whole reports system is due when we find the time for it.

**Comment by lin-d-hop** [comment]
Hi @RohanM 
I agree it would be great to refactor the whole of the reports section. I'd be interested in exploring things we can do to make the reports more navigable and possibly more flexible for users as well. Perhaps a broad discussion might point the direction for more refactorings?

In the mean time, I've extracted a lot of the code from Reports_controller_decorator out into lib/open_food_network/reports classes. This has made the r_c_d much more readable and reduced the length by about 500 lines.... which was much needed. There isn't anything radical in these changes, just some code moved about. 

I've done my own testing but it might be worthwhile for @kirstenalarsen to take a peak at the results as she has more familiarity with any idiosyncrasies in these reports.

Other than that looking forward to feedback and hopefully a merge. I know UK people would like to use the new packing reports soon.

Thanks heaps. Hope you are all shiny :-)

**Comment by kirstenalarsen** [comment]
I am not really testing stuff that's specifically uk-led, particularly things like reports that are designed by you for you, so not really sure there's much extra for me to test? or would the changes you have made be affecting all reports? and if so, would be useful to give me a much clearer idea what you want me to look for?

**Comment by NickWeir63** [comment]
Thank you!  We will fully test the reports we have requested.  I guess we need to check with @lin-d-hop as to whether other reports will be affected

**Comment by lin-d-hop** [comment]
Hi @kirstenalarsen 
The non-UK reports affected by this change are:
- orders and fulfillments
- bulk coop
- payments
The changes were really just shuffling code about and I've tested they work to my expectations. However I know yours are more detailed, so if you can it would be good to have a look as well.
Sorry to give you more work :-)

**Comment by kirstenalarsen** [comment]
I'm sorry I just can't test all the reports for 'something' - what might have changed? what would I be looking for?

**Comment by lin-d-hop** [comment]
@kirstenalarsen Haha yeah fair. Nothing should have changed, but that doesn't help you much. I'll do what you suggest in your email and do a diff on reports before and after the change, with a range of params, choosing specific dates in the past to avoid current testing changing the reports.

@NickWeir63 is coming to Bristol on Monday for a OFN training session. We could look at it then. So if you guys put this on staging on your Monday daytime is that ok? Myself or Nick will copy the reports our sunday night and we'll go through this on our Monday.

Does that sound ok?

**Comment by kirstenalarsen** [comment]
Hi @lin-d-hop and @NickWeir63 - Monday is a public holiday here and @RohanM won't be working till weds so I don't think we can get it on staging. If you take a bunch of reports off while you're working on Monday though, we can let you know when to check against the updated ones later in the week. More likely to be thursday or friday (do you have a preference?)

**Comment by lin-d-hop** [comment]
Thanks @kirstenalarsen 
All good. Just let us know when it's been pushed and we'll crack on from there.

**Comment by NickWeir63** [comment]
I am doing the first run of reports today.  I will have a bit of time on Thursday to do the second batch for comparison if you can get the update done by about 11am BST Thursday.  Otherwise I might find some time on Saturday.  If not then @lin-d-hop will do the second batch next week.

**Comment by NickWeir63** [comment]
OK - the first report run is done.  I will email the reports to @lin-d-hop and @kirstenalarsen

**Comment by RohanM** [comment]
Hi @lin-d-hop,

Thanks for your work, especially cleaning up the reports controller. It's looking so much better :)

Before I build this branch, I ran the minimal specs directly related to this PR, and found a number of failures. It looks like the change to filtering in OrderCycleManagementReport introduced some issues, and having a look at those recent commits there's some clear differences (ie. the `distributed_by_user(@user)` scope has been dropped). The specs I ran were `spec/features/admin/reports_spec.rb` and `spec/lib/open_food_network/*report*`.

When doing that kind of refactoring, I'd generally rely heavily on the existing specs to make sure I haven't broken anything - I feel really nervous making big changes without that feedback. 

Would you be able to fix those issues, and in future do a quick spot check of the relevant specs before submitting a branch for review/merge?

**Comment by lin-d-hop** [comment]
Oh d'oh. You're right. What a school girl error. I'll get on sorting this today and hopefully won't have to wait to long to get it onto staging :-/

**Comment by lin-d-hop** [comment]
@RohanM @kirstenalarsen 
Apologies for this. It's taken me longer than expected to sort out the tests on the refactorring here. A couple of bugs picked up which is great, but also some tweaks needed to make them work with the new code.

As the UK team is getting ready for launch and really needs to move on with testing, I was hoping it would be possible to merge 3 commits that just add the functionality for the UK packing reports. There commits are:
20433ce
c68e56f
1df5499

I'm away for a week now for Glasto, then a conference (on democratising agricultural research, I'm sure you guys will be interested in outcomes :-)). I plan to commit most of my time to OFN when I'm back so looking forward to getting into the angularising the order index page then.

xx

**Comment by lin-d-hop** [comment]
Closing as opened another to remove merge commits. #629

**Pull request closed without merging**
