### PR TITLE
Fix admin taxonomies interface

### LINKED ISSUE #9031: "Rename" function broken (taxonomies)
## Description

There are different ways one can rename taxonomies. By visiting `/admin/taxonomies/<taxon_id>/edit`, one can:
i) edit the Name field
ii) right click on the taxon; select Edit
iii) right click on the taxon; select Rename

This issue is about option iii): it currently takes no effect whatsoever.

## Expected Behavior

Editing a taxon name by right clicking on the taxon and selecting Rename should change its name.

## Actual Behaviour

Right clicking on the taxon and selecting Rename takes no effect.

## Steps to Reproduce

As superadmin:
1. Visit `/admin/taxonomies/<taxon_id>/edit`
2. Right click on the taxon
3. Select Rename and change the name
4. Click Update, or on the "Back to Taxonomies list"
5. Check whether the change took effect -> see that it didn't

## Animated Gif/Screenshot

image

## Workaround

You can still change the taxonomy name by using steps i) and ii) (see Description section, above)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.1.22
* Browser name and version: Firefox 96
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

Maybe related to:
https://github.com/openfoodfoundation/openfoodnetwork/pull/8678

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9031, #9113

The interface was broken, this PR is here to restore, move, delete and rename functionnalities.

Solution for the rename of the first/root taxon is to update the main input field as well:
Capture d’écran 2022-06-02 à 16 10 56
Capture d’écran 2022-06-02 à 16 11 05
Capture d’écran 2022-06-02 à 16 11 09

#### What should we test?

see the Steps to reproduce section in the linked issue: #9113

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Cool.

**Comment by drummer83** [comment]
Things tested:
- Renaming the header taxon
  - using right click rename --> OK
  - using right click edit --> **not ok**
  - using the input field above the taxons --> OK
- Renaming taxons
  - using right click rename --> OK
  - using right click edit --> OK
- Moving taxons
  - move a taxon inside another taxon --> OK
  - move a taxon outside another taxon --> OK
  - change the order of taxons --> **not OK**
- Deleting taxons
  - deleting one of at least two taxons using right click remove --> OK
  - deleting the last taxon using right click remove --> **not OK**
  - deleting the header taxon using right click remove --> **not OK**

**Before staging your PR**
Peek 2022-06-17 14-44
Peek 2022-06-17 14-47

**After staging your PR**

Renaming the header taxon:
Peek 2022-06-17 15-03

Renaming taxons:
Peek 2022-06-17 15-07

Moving taxons:
Peek 2022-06-17 15-13

Deleting taxons (header and normal):
Peek 2022-06-17 15-16

Deleting the last taxon:
Peek 2022-06-17 15-18

## Summary
Open points:
- Renaming the header taxon is not working when right clicking and selecting 'edit'
  - **should be fixed**
- Changing the order of taxons is not working - but I am not aware where this is being used at all. I does not affect the order of the filter buttons in the shop and also not the order of the products. Any idea @filipefurtad0 @RachL?
  - maybe no need to fix
- Deleting the last taxon using right click 'remove' does not work
  - if it's easy to do: maybe remove the 'remove' option otherwise no fix for now
- Deleting the header taxon using right click 'remove' does not work
  - if it's easy to do: maybe remove the 'remove' option otherwise no fix for now

We do have great improvement here with at least one little glitch. I will leave to you @jibees to decide if you want to merge this or move back to 'In Dev' first.

Thanks again!

**Comment by RachL** [comment]
cool this is being improved and nice testing @drummer83 ! :tada:

> Changing the order of taxons is not working - but I am not aware where this is being used at all. I does not affect the order of the filter buttons in the shop and also not the order of the products. 

The product order in the shopfront is either alphabetical or defined by the shop manager in Enterprise > Settings > Shopfront preferences. For the filter...do I have a sun burn or the order does not make sense? 👀 could it be by ID? I see in prod all filters have the same weird ordering. 🤕 

I don't think shoppers can understand the reasoning behind this order. Maybe if one day we have a different shopfront UX with categories first, maybe shop managers will want to re-order categories. But I think that filters should stay in alphabetical order.

That being said, I'm diverging here, the question was for super admin: IMO changing the order is useful if we have actually 2 dropdowns ( one for main categories and the other one for sub categories). But that's maybe a project of it's own, going beyond the scope of this PR?
With a single dropdown, I feel an alphabetical order is the simplest solution?

**Comment by jibees** [comment]
- Rename the taxon by using "Right click, Edit" and the interface at `/admin/taxonomies/1/taxons/1/edit`

Nice catch. Also broken in `master`

 - Changing the order of taxons

Right. Also not functional in `master`

 - Removing the last taxon

Not functional in `master`

- Removing the header taxon

Also in `master`



All those issues are also in `master`, so I would say: no regression but improvements (yes, not complete), so merge it and create new issues for each case (or an epic? Or a draft issue in order to have a discussion about removing, or moving...)

**Comment by mkllnk** [comment]
Yes, that interface was completely broken for many years now. It's rarely used and the one use case of ordering did work.

**Pull request merged**
