### PR TITLE
[Spree 2.1] Fix enterprise package selection submit button

### LINKED ISSUE #5360: [Spree 2.1] Snail upon finishing enterprise registry
## Description

The the enterprise registry finishes with a welcome menu (see pic below). Here, after selecting the desired option, pressing Select and Continue button results in a 404 Snail (/register page is missing)

## Expected Behaviour

One should be able to choose a package in the Welcome menu to finish the registry.

## Actual Behaviour

After selecting the desired option, pressing Select and Continue button results in a 404 Snail.

## Steps to Reproduce

This can be reproduced either:

1. By creating a new user and completing the registry an enterprise.
2. In the welcome menu, choose an option and press the Select and Continue.
3. This leads to the page: https://staging.openfoodnetwork.org.uk/admin/enterprises/_enterprisename_/register which does not exist.

or

1. or attempting to change package, for an already registered enterprise under
2. https://staging.openfoodnetwork.org.uk/admin
3. Selecting and Change Package and Change Now

## Workaround

No workaround.

## Severity

bug-s1: a critical feature is broken

## Your Environment

* Version used: 
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04 64

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5360

The target route needs to be patch in rails 4, put wont work. I extended the registration process spec to cover this step.

#### What should we test?
Verify the issue is solved.

#### Release notes
Changelog Category: Fixed
Fixed enterprise package selection submit button

### CODE REVIEW

**Comment by luisramos0** [comment]
rebased to get latest 3-0-stable before testing.

**Comment by filipefurtad0** [comment]
Hi @luisramos0  - happy to test this one, when it's staged. Thank you :-)

**Comment by luisramos0** [comment]
done, staged :+1:

**Comment by filipefurtad0** [comment]
@luisramos0 this looks good as well,
Choosing package after login is now possible and works as expected.
Thanks.

**Pull request merged**
