### PR TITLE
Upgrade node version

### PR DESCRIPTION
**Pull request by jibees**
Thanks to @dacook it's pretty easy to upgrade node version (using nodenv that is used in local, CI and once deployed)

#### What? Why?

- Reference https://github.com/openfoodfoundation/ofn-install/issues/838

#### What should we test?
I think it's great to simply check:
 - green build
 - deployment on staging
 - launch the app and request on page

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

#### Post-merge actions
We should raise a tech-debt issue about removing the `--openssl-legacy-provider` option when possible
--openssl-legacy-provider

### CODE REVIEW

**Comment by jibees** [comment]
When upgrading to the next node version (ie. `17.0.0`):

```
➜  openfoodnetwork git:(upgrade-node-version) ✗ ./bin/webpack-dev-server 
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /Users/jibees/dev/openfoodnetwork/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
/Users/jibees/dev/openfoodnetwork/node_modules/loader-runner/lib/LoaderRunner.js:106
                        throw new Error("callback(): The callback was already called.");
                              ^

Error: callback(): The callback was already called.
    at context.callback (/Users/jibees/dev/openfoodnetwork/node_modules/loader-runner/lib/LoaderRunner.js:106:10)
    at /Users/jibees/dev/openfoodnetwork/node_modules/css-loader/dist/index.js:141:5

Node.js v17.0.0
```

**Comment by dacook** [comment]
At first, I wasn't sure about the `--openssl-legacy-provider` option. **The issue is that we have a package using an insecure method** which is no longer allowed (as pointed out by one of the answers in the SO topic: https://stackoverflow.com/a/73027407/421243).
It would be better to update that package. But the package is probably being held back by our old Webpack version. We want to upgrade that but can't do it quickly.

So.. this is a reasonable interim solution. But we should remove this flag as soon as we can (hopefully once Webpack is upgraded). So after merging this, we should probably raise a new tech debt issue about this flag.

**Review by dacook — COMMENTED** [review]
@jibees if we're updating the Node version here, I think we need to have a plan to [also upgrade on the servers](https://github.com/openfoodfoundation/ofn-install/issues/838). 

So actually I personally don't think we should merge this yet sorry. I will comment on the other issue.

**Review by dacook — APPROVED** [review]
I think this is good to go now, yay!

I'd like to request a second review though in case anyone has any further concerns about `openssl-legacy-provider`

**Comment by dacook** [comment]
Successful deploys:
Screen Shot 2023-03-17 at 2 48 07 pm

**Review by mkllnk — APPROVED** [review]
Cool. Works on my machine as well.

**Pull request merged**
