### PR TITLE
Bump Ruby version from 2.1.5 to 2.1.9

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Minor Ruby version bump from 2.1.5 to 2.1.9. We gain a _vast_ number of updates and fixes:

- 2.1.6 Changelog: https://svn.ruby-lang.org/repos/ruby/tags/v2_1_6/ChangeLog
- 2.1.7 Changelog: https://svn.ruby-lang.org/repos/ruby/tags/v2_1_7/ChangeLog
- 2.1.8 Changelog: https://svn.ruby-lang.org/repos/ruby/tags/v2_1_8/ChangeLog
- 2.1.9 Changelog: https://svn.ruby-lang.org/repos/ruby/tags/v2_1_9/ChangeLog

#### What should we test?

Needs some dev input:

- Provision a staging server with https://github.com/openfoodfoundation/ofn-install/pull/514
- Deploy this PR
- Test everything looks ok

#### Release notes

Bumped Ruby from 2.1.5 to 2.1.9

Changelog Category: Changed

### CODE REVIEW

**Comment by luisramos0** [comment]
❤️ 
build broken complaining about semaphore ruby version being 2.1.5, I temporarily changed it to 2.1.9 in project settings and re triggered this build

**Comment by Matt-Yorkley** [comment]
> can we just go forward?

I just put this up so I can deploy it easily with Ansible. We need to add some corresponding updates in `ofn-install` first and test a few things to make sure it's all ok. This will be a nice trial run for upgrading to `2.2.x` though.

**Comment by Matt-Yorkley** [comment]
Initial testing on Vagrant looks good on the Ops side of things. I think we can test this PR on a staging server with: https://github.com/openfoodfoundation/ofn-install/pull/514

**Comment by Matt-Yorkley** [comment]
### Dev testing notes:

- [ ] Provisioning https://github.com/openfoodfoundation/ofn-install/pull/514 in Staging works without error, and keeps both versions of Ruby available
- [ ] Deploying https://github.com/openfoodfoundation/openfoodnetwork/pull/4250 afterwards works without error and the app runs with `2.1.9`
- [ ] Deploying other branches (that still use `2.1.5`) afterwards can be done without error

**Comment by sauloperez** [comment]
> It looks like the Ruby version gets set for the openfoodnetwork user during provisioning, so to deploy a pre-2.1.9 PR afterwards, the Ruby version would have to be reset via rbenv before it will work.

I haven't put too much thinking on all this but this means that we won't have rollbacks if we need it in production (to me manual rollback is out of the question). We can temporally add the reset command for rbenv in the rollback playbook, right?

**Comment by Matt-Yorkley** [comment]
Another option is that we can set the Ruby version in the deploy playbook. I think that will resolve the issue. so we check the `.ruby-version` file in the build, and set the server to that version.

So the current status of this is that we get a green build, and the app loads and seems ok, but we havn't done more testing. It seems good to go, but I'm a bit nervous.

**Comment by RachL** [comment]
I've tested very simple cases (checkout , order page etc). Everything is looking good. Let's see in release testing how the rest goes!

**Comment by luisramos0** [comment]
👏

**Pull request merged**
