### PR TITLE
Validate user's email address

### LINKED ISSUE #10808: Missing validation of user email address
## Error in OpenFoodNetwork Aus

**Net::SMTPFatalError** in **ActionMailer::MailDeliveryJob@default**
555 5.5.2 Syntax error. a80-20020a0dd853000000b0054c0dd7b376sm21641ywe.9 - gsmtp

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64544e2308cebe0009e0c732?event_id=645461da00bcd98a12030000&i=gh&m=ci)

## Stacktrace

    gems/net-smtp-0.3.3/lib/net/smtp.rb:1076 - check_response

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64544e2308cebe0009e0c732?event_id=645461da00bcd98a12030000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #10808 

We didn't really validate email addresses, only presence, uniqueness and that it contains an `@`. Now we validate the syntax and even the validity of the domain.

#### What should we test?

- Creating a user with an invalid email address shouldn't be possible. You should see an error instead.
- Sign up as user with a domain which doesn't exist, like me@example.com.
- Invite an enterprise manager and add backslashes `\\` at the end of the address.
- Create a user as admin with an invalid address.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Thanks for that! With this, we'll improve our user email validation, and I think it's always a good idea!

I'd add something to the "How to test?" section, in order to check the validation for the _old_ users: 
###### Before staging the PR
 - Create a user with an invalid-with-this-PR-but-valid-with-current-master email 
###### After staging the PR
 - Check you can still login with this email

**Comment by mkllnk** [comment]
> Create a user with an invalid-with-this-PR-but-valid-with-current-master email

I thought of that but I couldn't work out how to create a valid account which is able to log in. If the email address is not valid then you don't get the link to activate the account and you can't log in...

**Comment by drummer83** [comment]
Just yesterday Nick has uploaded a video to YouTube showing an interesting use case for invalid dummy email addresses. It's about taking phone orders for people without internet access.

https://youtu.be/JTIB0fpn21o?t=341

So the question is: Will the email validation of this PR also check the email address of guest checkouts?
If it does, then this use case will not work anymore.

**Comment by mkllnk** [comment]
> Will the email validation of this PR also check the email address of guest checkouts?

No, guest checkouts don't create a user record. They create a customer record only. A customer record uses the same library to validate email addresses but it doesn't check the validity of the domain. You can still make up syntactically correct addresses as before for guest checkout.

But even if we validated the domain, I would suggest to make dummy addresses like `guest.nick.example@openfoodnetwork.org.uk`. The domain is valid and would be recognised by strict validation. It also means that we don't try to send an email to a random account. If you make something up like `aaa@abc.com` then that's actually a valid address that may get delivered to someone.

I run an email provider and I get random flight booking confirmations (legit, not spam) to `contact.@.email.org.au`, for example (without the dots). It's probably just annoying for someone else but it could also be abused.

@NickWeir63 The above may interest you.

**Review by abdellani — APPROVED** [review]
Side note: all of the following characters can be used on the email address (local part and not the domain part)
```
      ! # $ % & ' * + - / = ?  ^ _ ` . { | } ~
```

[RFC 3696](https://datatracker.ietf.org/doc/html/rfc3696#section-3)

**Comment by drummer83** [comment]
Hi @mkllnk,

Just to clarify before diving into this. How are the first two scenarios different? What do you mean by 'create a user' vs. 'sign up as a user'? Regular users can only sign up through the Login button in the shopfront, right? I understand that admins can 'create' users (case three below).

> * Creating a user with an invalid email address shouldn't be possible. You should see an error instead.
> 
> * Sign up as user with a domain which doesn't exist, like [me@example.com](mailto:me@example.com).
> 
> * Create a user as admin with an invalid address.

**Comment by drummer83** [comment]
Hi @mkllnk,
Thanks for this improvement. It's a long test documentation with many screen shots. You can find a summary at the end (and skip the rest).

### Test cases
* Creating a user with an invalid email address shouldn't be possible. You should see an error instead.
  * ❓ Question from previous post pending ❓ 
* Sign up as user with a domain which doesn't exist, like [me@example.com](mailto:me@example.com).
  * Before: No error message, but the user will never receive the email to activate his/her account.
image
  * After: Unchanged ❓ 
image
* Sign up as user with an invalid email address (like '\\' added).
  * Before: No error, but no user is created when clicking 'Create'. Instead the cursor jumps into the email field.
  * After: Unchanged. ✔️ 
* Create a user as super admin with an invalid email address (invalid domain).
  * Before: The user is created and listed, but will never receive the email to activate his/her account.
image
image
image
  * After: Unchanged ❓ 
image
image
* Create a user as super admin with an invalid address (invalid characters like '\\' or SPACE).
  * Before: No error, but no user is created when clicking 'Create'. Instead the cursor jumps into the email field.
  * After: Unchanged. ✔️ 
* Create a customer as admin with an invalid email address (invalid domain).
  * Before: No error, customer will be listed as guest.
image
image
  * After: Unchanged ✔️ (customer emails are out of scope here)
image
image
* Create a customer as admin with an invalid email address (invalid characters like '\\' or SPACE).
  * Before: Error message, customer can't be created.
image
  * After: Unchanged. ✔️ 
image
* Invite an enterprise manager with invalid email address (invalid domain).
  * Before: No error, but nobody will receive the invitation.
image
image
image
  *After: Unchanged. ❓  
image
* Invite an enterprise manager with invalid email address (added `\\`).
  * Before: No error, but the email won't be delivered.
image
image
image
  * After: Error message: Email is invalid! ✔️ ✔️ ✔️ 
image
image
* Invite an enterprise manager with invalid email address (email contains SPACE).
  * Before: Error message.
image
image
  * After: Error message: Email is invalid and email is invalid. ❓ 
image
image
* Try guest checkout with invalid email address (invalid domain).
  * Before: Order is placed.
image
image
  * After: Unchanged. ✔️ 
image
image
* Try guest checkout with invalid email address (invalid characters like '\\' or SPACE).
  * Before: Error message.
image
  * After: Unchanged. ✔️ 
image
* Edit email as customer to an invalid address (invalid domain).
  * Before: Email is accepted but account won't be updated because the required confirmation email will not be received.
image
image
  * After: Unchanged. ✔️ 
image
* Edit email as customer to an invalid address (invalid characters like '\\' or SPACE).
  * Before: No error, but no update when clicking 'Update'. Instead the cursor jumps into the email field.
  * After: Unchanged. ✔️ 
* Edit user email as super admin to an invalid address (invalid domain).
  * Before: Email is accepted but account won't be updated because the required confirmation email will not be received.
image
image
  * After: Unchanged ❓ 
* Edit user email as super admin to an invalid address (invalid characters like '\\' or SPACE).
  * Before: No error, but no update when clicking 'Update'. Instead the cursor jumps into the email field.
  * After: Unchanged. ✔️ 
* Group owners, enterprise managers and enterprise owners
  * Before: It's possible to use users with invalid email address for these roles.
  * After: Unchanged. ✔️ 

## Summary
- Users can still sign up with email addresses from invalid domains like abc@example.com ❓ However the confirmation email will not be received and so it can't become a user account's email address.
- Super admins can still create users with email addresses from invalid domains like abc@example.com. ❓ However the confirmation email will not be received and so it can't become a user account's email address.
- Invitations to managers can still be sent to emails with invalid domains like abc@example.com. ❓ However it will not be received and so it can't become a user account's email address.
- Invitations to managers can't anymore contain invalid characters like '\\' or SPACE. This is a great improvement! ✔️✔️✔️
- The error message for a SPACE in the email address to invite a manager leads to a repeated error message: Email is invalid and Email is invalid ❌ 
- Super admins can still edit a user's email address to use an invalid domain like abc@example.com. ❓ However the confirmation email will not be received and so it can't become a user account's email address.

## Result
We have one minor and edge-case regression regarding the repeated error message. But we do have a great improvement regarding the added '\\' when inviting a manager - and this had been reported in production. Additionally there are a few cases where I would have expected for the new email validation to kick in and avoid those cases but none of them is critical because a user confirmation is required - which is impossible if the email can't be delivered.

So, I think we can merge this. But I will leave it for you to decide.

Thanks for working on this! 🙏

**Comment by mkllnk** [comment]
Thank you for testing this thoroughly. I gave you bad test data for the domain validation. When I run `host example.com` on my machine, I get "Host example.com not found: 3(NXDOMAIN)" but if I do it on staging, it finds the domain. So it seems to be an existing domain which is filtered by my internet provider. You need to find another domain which does not exist to test this. Maybe this one?
```
$ host k8k4n48snasdfl8does-not-exist.com
Host k8k4n48snasdfl8does-not-exist.com not found: 3(NXDOMAIN)
```

But we can also skip the testing here. I'll merge this because it's an improvement, as you said. The domain validation was a nice extra and I expect it to work (except for example.com :wink:).

**Pull request merged**
