### PR TITLE
Removing 'required' tag for 'Latitude / Longitude' for Enterprises

### LINKED ISSUE #10008: [Admin][Enterprise] Latitude and longitude fields are indicated as required but aren't required
## Description
When you create an enterprise in the admin dashboard (admin/enterprises/new), as well as in an enterprise paramaters address (admin/enterprises/from-admin/edit#!#address_panel), latitude and longitude fields are indicated as required fields but aren't actually required. You can save without filling in these fields.

## Expected Behavior
If a field is not required, there should not be the red asterisk above it.

## Actual Behaviour
The latitude and longitude fields are indicated as required with the red asterisks, but aren't really required.

## Steps to Reproduce
1. Click "New enterprise" button in the dashboard (admin/enterprises/new)
2. Don't fill in the latitude and longitude fields
3. See that you can proceed
4. Go to Enterprise tab > Settings > Address
5. See that the fields are not filled

## Animated Gif/Screenshot
Screen Shot 2022-11-16 at 20 21 42

## Workaround
If you think lat and long required and don't want to type them manually, you can check the "Calculate latitude and longitude automatically from address?" box 

## Severity
bug-s4: it's annoying, but you can use it

### PR DESCRIPTION
**Pull request by vviekk**
#### What? Why?

- Closes #10008

#### Removed required(`*`) tag for `Latitude / Longitude` form fields under Enterprises. 
1. The form accepts empty value.
2. DB schema accepts empty values.
3. All the look up check for the respective availability before processing.
4. No change in functionality. Simple UI change.

**The expected change** 
- Before - Asterisk(*) next to label  `Latitude / Longitude` on forms on 
  1. New Enterprise creation (admin/enterprises/new), and 
  2. address setting for an enterprise(Enterprise tab > Settings > Address).
  - image

- After - NO Asterisk(*) next to  `Latitude / Longitude` label on the above forms.
  - image

#### What should we test?
Functionality checks 
1. No change in data entered in DB for new enterprises. (comparing control (prod) and treatment(dev))
  1. With Latitude and Longitude data
  2. without Latitude and Longitude 
1. No change in map rendering for enterprises with coordinates data.

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by vviekk** [comment]
Hi,
This is my first time with Ruby.
Please let me know if I have missed something.

Cheers.

**Review by jibees — APPROVED** [review]
Thanks! It looks good to me, not much to add.
Let's go to `Test Ready` state!

**Comment by vviekk** [comment]
Thank you @jibees!
How do I mark this as test ready? I can't find status board under the project section of the repo.
Also is testing done by another person or am I responsible for it?

**Comment by RachL** [comment]
@vviekk it's done by our testing team. JB already moved your PR on our board so you don't have anything to do ;)

**Comment by sigmundpetersen** [comment]
Hey @vviekk , also you can get the [Zenhub browser extension](https://www.zenhub.com/extension) to view our Kanban board 👍

**Comment by vviekk** [comment]
Thank you for the update @RachL!
Thanks @sigmundpetersen, I'll check it out!

**Comment by drummer83** [comment]
Hi @vviekk,
Thanks for this fix! I have tested this on one of our staging servers.
I can confirm that the 'required' tag is not shown anymore on the address tab as well when creating a new enterprise and functionality is still ok.

Before your PR:
image

After your PR:
image

Thank you so much! This one is ready for merging! :partying_face:

**Pull request merged**
