### PR TITLE
Use Google's map tiles with Google Maps

### LINKED ISSUE #6884: Spike: cleaning our google set-up vs switching completely to OSM
## Description

The purpose of this spike is to assess how long does it take to:

A. Display gmaps our main map layer and reversing #6882

B. Switch our system to completely and only support Open Street Map

Option B will need to take into account:

- Previous Epic summarizing the technical work left here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5542
- Maybe this is interesting? https://github.com/openfoodfoundation/openfoodnetwork/issues/5078
- OSM can work with several geocoders
- Farms are often located on roads that do not exist yet on OSM, so the journey/experience for the user might be different on OSM vs the current one on Gmaps. An estimate of the time and tasks required is therefore needed by the design team.

## Acceptance Criteria & Tests

We should be able to take a decision base on the result of the spike. => To be details a bit more this is too vague

### PR DESCRIPTION
**Pull request by mkllnk**
We started to move to Open Street Maps (OSM) and one simple change was
to show OSM tiles on top of the current Google Maps functionality. This
hybrid use violates Google's terms and conditions though and I'm
reverting it here (basically reverting daa5b00a2).

Another branch of work was already started to use OSM without Google
functionality and it's available behind a feature toggle. We can
continue that work in our own time without a license violation. This
change is only changing the tiles, the look of the map and doesn't touch
any functionality which was always provided by Google Maps.

#### What? Why?

Closes #6884

#### What should we test?

- The map at `/map`.
- Enterprises should display, you can zoom etc.
- You can search for locations with the search bar.
- There is no reference to Open Street Maps.
- Repeat the same on a group's map.

#### Release notes

Changelog Category: User facing changes

The default map is showing Google Maps images instead of Open Street Maps images again to comply with Google's terms and conditions. Open Street Maps is still available as alternative in beta mode via a feature toggle under Admin/Settings/Content.

#### Dependencies

No.

#### Documentation updates

No.

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]

**Review by jibees — APPROVED** [review]

**Comment by sigmundpetersen** [comment]
So this can go to Test ready with 2 approvals, right?

**Comment by andrewpbrett** [comment]
Yes! That might be a good pointer for @jibees - if you give the second approval, please move the issue to Test Ready or Dev Test Ready in Zenhub 🙂

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

This appears to have taken effect

Main map - Before this PR:
image

Main map - After this PR:
image

Icons are appearing correctly, all as before. Geocoding is working as well:
image

Group maps are also displayed in the same fashion, but only "+1" icons are appearing - this is bug #6829 
image


I'm wondering about the strange coloring though. Maybe we should try to display the same colors as before, like blue for water, etc. What do you think Maikel? Should I create an issue for this?

**Comment by mkllnk** [comment]
> I'm wondering about the strange coloring though. Maybe we should try to display the same colors as before, like blue for water, etc. What do you think Maikel? Should I create an issue for this?

That would be nice but I don't know how to do that. The general options are "roadmap" (current), "satellite" (too colourful) and "terrain" (shows mountains, still grey). If there is someone with Google Maps experience who knows how to do that in 5 minutes, great. Otherwise I wouldn't bother.

**Pull request merged**
