### PR TITLE
Remove N+1 query loading tags for each order cycle exchange

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

- For https://github.com/openfoodfoundation/openfoodnetwork/issues/5213 

When an order cycle is loaded in the admin area a separate query is made to fetch the tags for each and every exchange that belongs to the order cycle. This changes things so tags are fetched for every order cycle exchange in a single query.

#### What should we test?

1. Find an order cycle which has multiple exchanges with tags, the more the easier it might be notice a difference, there should be less queries in any case.
2. Compare the before and after performance of `/admin/order_cycles/:id.json`. This URL is loaded via AJAX on the edit order cycle page.

#### Release notes

Remove N+1 query loading tags for each order cycle exchange

Changelog Category: Technical changes

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
Thanks a lot for this one @cillian !
On small comment: shouldn't we rename this file `spec/support/query_counter.rb` to `spec/support/query_counter_spec.rb`

Otherwise I'm good! 💪

**Comment by cillian** [comment]
Thanks for the review @jibees I think `spec/support/query_counter.rb` might be ok in this case because it's more of a helper class like `spec/support/test_summarizer.rb`

**Comment by jibees** [comment]
You're absolutely right @cillian . Moving to Test Ready then!

**Review by jibees — APPROVED** [review]
👌

**Comment by drummer83** [comment]
Hi @cillian,
Thanks for this one! I am not sure I am trying to test the right thing here.

## What I did
1. Using this psql query I tried to find an order cycle with a lot of exchanges: `SELECT order_cycle_id, COUNT (order_cycle_id) FROM exchanges GROUP BY order_cycle_id ORDER BY count DESC;`
2. From the results I identified order cycle ID 3327 with 140 exchanges. 
image
3. I opened `https://staging.openfoodnetwork.org.uk/admin/order_cycles/3327/edit` and `.../3327/incoming`, took screenshots and had a look at the number of requests and the loading time.

## Results
### Before
/edit: 12 requests, 53 seconds
/incoming: 150 requests, 57 seconds
### After
/edit: 12 requests, 56 seconds
/incoming: 151 requests, 59 seconds

- No reduction of loading time observed.
- No reduction of queries observed.
- The exchange queries are only sent on the /incoming page.

## Screenshots
### Before
/edit: 12 requests, 53 seconds
image

/incoming: 150 requests, 57 seconds
image

### After
/edit: 12 requests, 56 seconds
image

/incoming: 151 requests, 59 seconds
image

## (Stupid) Questions
1. Am I looking at the right thing?
2. What exactly does an "exchange" mean?
3. When we talk about "tags" in this context, do we still mean the tags for showing/hiding order cycles, payment methods and so on to tagged customers?
4. How do "exchanges" and "tags" play together?

Thanks for providing some insight here!

**Comment by cillian** [comment]
Hi @drummer83 Thanks for testing this. It's the request to `/admin/order_cycles/3327.json` specifically that _should_ be improved by this PR. The exchanges are the incoming products coming in from the grower(s)/supplier(s) and the outgoing products from the distributor(s). Each _outgoing_ exchange can have tags like below...

exchange-tags

The problem is that for _each and every_ outgoing exchange a database query is made to find which tags, if any, belong to that exchange. So if the order cycle has 7 outgoing exchanges for example (like in this [test](https://github.com/openfoodfoundation/openfoodnetwork/pull/9983/files#diff-4b05dd9f13b267021ea1adf1cc5f92150707a8bbb0573f18bdff24680d2af103R141)) there will be 7 database queries to lookup the tags. This PR changes things so it fetches the tags for all 7 outgoing exchanges in [a single query](https://github.com/openfoodfoundation/openfoodnetwork/pull/9983/files#diff-4b05dd9f13b267021ea1adf1cc5f92150707a8bbb0573f18bdff24680d2af103R147). I see the after time in your test was a bit slower at `54160ms` then the before time `52420ms`. I'm not sure why it's a bit slower yet, but it is good to investigate this further to check things are actually working faster, does that order cycle have any tags attached like in the screenshot above?

I tested it by loading the `/admin/order_cycles/3327.json` page directly in a browser rather than loading the `/edit` page and there seemed to be an improvement. I pulled these timings from the logs.

**Before:**

```
Completed 200 OK in 234ms (Views: 142.7ms | ActiveRecord: 81.2ms | Allocations: 93162)
Completed 200 OK in 243ms (Views: 150.7ms | ActiveRecord: 83.1ms | Allocations: 93161)
Completed 200 OK in 259ms (Views: 152.7ms | ActiveRecord: 92.1ms | Allocations: 93161)
Completed 200 OK in 226ms (Views: 137.2ms | ActiveRecord: 78.0ms | Allocations: 93161)
Completed 200 OK in 254ms (Views: 150.4ms | ActiveRecord: 88.8ms | Allocations: 93162)
Completed 200 OK in 290ms (Views: 173.5ms | ActiveRecord: 96.9ms | Allocations: 93164)
Completed 200 OK in 241ms (Views: 142.7ms | ActiveRecord: 87.0ms | Allocations: 93164)
Completed 200 OK in 234ms (Views: 141.9ms | ActiveRecord: 80.6ms | Allocations: 93161)
Completed 200 OK in 250ms (Views: 155.1ms | ActiveRecord: 84.8ms | Allocations: 93161)
Completed 200 OK in 266ms (Views: 160.9ms | ActiveRecord: 90.3ms | Allocations: 93161)
Average: 249.7ms
```

**After:**

```
Completed 200 OK in 206ms (Views: 128.2ms | ActiveRecord: 69.3ms | Allocations: 86780)
Completed 200 OK in 219ms (Views: 132.3ms | ActiveRecord: 75.8ms | Allocations: 86780)
Completed 200 OK in 213ms (Views: 131.5ms | ActiveRecord: 71.2ms | Allocations: 86782)
Completed 200 OK in 222ms (Views: 137.0ms | ActiveRecord: 74.8ms | Allocations: 86785)
Completed 200 OK in 216ms (Views: 135.2ms | ActiveRecord: 70.7ms | Allocations: 86780)
Completed 200 OK in 227ms (Views: 144.2ms | ActiveRecord: 75.7ms | Allocations: 86781)
Completed 200 OK in 211ms (Views: 129.2ms | ActiveRecord: 72.5ms | Allocations: 86780)
Completed 200 OK in 208ms (Views: 128.0ms | ActiveRecord: 71.7ms | Allocations: 86780)
Completed 200 OK in 261ms (Views: 153.1ms | ActiveRecord: 92.6ms | Allocations: 86780)
Completed 200 OK in 216ms (Views: 133.8ms | ActiveRecord: 73.5ms | Allocations: 86783)
Average: 219.9ms
```

**Comment by drummer83** [comment]
Hi @cillian,
Thanks for your explanations. I didn't use tags during my last test.

The strange thing is: On current master the loading time has suddenly dropped to only ~10 seconds (compared to > 50 seconds during my last test session). This is the same with and without a tag applied on the outgoing page and also after staging your PR. I am using the same order cycle as last time.
image

Are we expecting to reduce the number of requests (13 in the example above - see bottom left corner) or are we expecting the request to be faster because within the request we have fewer database queries?

I have learned now that an exchange correlates to an enterprise and not to a product. :+1: 

Now I need to go to bed. I will try again. If you have any ideas or comments in meantime, it's much appreciated.
Thanks! And I'm sorry that I have difficulties testing this...

**Comment by drummer83** [comment]
Hi @filipefurtad0,

Sorry, I am totally stuck on this one. I still don't really understand the concept of exchanges and I don't know where to see the number of queries.

Could you maybe have a go at this one and document - as you always do - so I can learn for the next time?

I think it would be great to have it in this week's release, so I officially resign from this task. 😉

**Comment by filipefurtad0** [comment]
Hey @cillian @drummer83 ,

Thanks for all the testing and discussion. It's indeed not always easy to catch performance improvements in staging.

I understand an exchange each of the 4 lines (incoming) below:

image

For the outcoming section we have 3 exchanges:

image

So if we check the DB for this OC we have 7 exchanges (with tags):

```

openfoodnetwork=> select count(*) from exchanges where order_cycle_id = 3653;
 count 
-------
     7
(1 row)
```

Following the suggestion from @cillian (thanks!!), tracking the log of the staging server with:

`openfoodnetwork@staging:~/apps/openfoodnetwork/current$ tail -f log/staging.log | grep 'Completed 200 OK'`

And re-loading the page 10x we get:

**before this PR**

```

I, [2022-12-07 17:19:12#17778]  INFO -- : Completed 200 OK in 375ms (Views: 252.3ms | ActiveRecord: 107.3ms | Allocations: 94754)
I, [2022-12-07 17:19:14#17778]  INFO -- : Completed 200 OK in 363ms (Views: 244.6ms | ActiveRecord: 100.1ms | Allocations: 94756)
I, [2022-12-07 17:19:16#17472]  INFO -- : Completed 200 OK in 367ms (Views: 235.3ms | ActiveRecord: 117.0ms | Allocations: 94752)
I, [2022-12-07 17:19:17#17472]  INFO -- : Completed 200 OK in 361ms (Views: 238.4ms | ActiveRecord: 107.9ms | Allocations: 94758)
I, [2022-12-07 17:19:19#17472]  INFO -- : Completed 200 OK in 386ms (Views: 253.2ms | ActiveRecord: 117.4ms | Allocations: 94758)
I, [2022-12-07 17:19:21#17778]  INFO -- : Completed 200 OK in 416ms (Views: 273.5ms | ActiveRecord: 123.9ms | Allocations: 94752)
I, [2022-12-07 17:19:23#17778]  INFO -- : Completed 200 OK in 380ms (Views: 240.1ms | ActiveRecord: 118.1ms | Allocations: 94776)
I, [2022-12-07 17:19:25#17778]  INFO -- : Completed 200 OK in 396ms (Views: 256.8ms | ActiveRecord: 120.9ms | Allocations: 94753)
I, [2022-12-07 17:19:27#17778]  INFO -- : Completed 200 OK in 404ms (Views: 264.3ms | ActiveRecord: 122.2ms | Allocations: 94760)
I, [2022-12-07 17:19:29#17778]  INFO -- : Completed 200 OK in 430ms (Views: 281.6ms | ActiveRecord: 131.3ms | Allocations: 95575)
```

Average: 387.8 ms

**after this PR**

```
I, [2022-12-07 17:03:36#12537]  INFO -- : Completed 200 OK in 346ms (Views: 227.4ms | ActiveRecord: 102.4ms | Allocations: 90118)
I, [2022-12-07 17:03:38#12262]  INFO -- : Completed 200 OK in 339ms (Views: 222.4ms | ActiveRecord: 100.6ms | Allocations: 90117)
I, [2022-12-07 17:06:12#12262]  INFO -- : Completed 200 OK in 341ms (Views: 231.5ms | ActiveRecord: 93.6ms | Allocations: 90125)
I, [2022-12-07 17:06:15#12537]  INFO -- : Completed 200 OK in 327ms (Views: 213.0ms | ActiveRecord: 96.0ms | Allocations: 90128)
I, [2022-12-07 17:06:17#12262]  INFO -- : Completed 200 OK in 359ms (Views: 230.4ms | ActiveRecord: 111.1ms | Allocations: 90507)
I, [2022-12-07 17:06:19#12262]  INFO -- : Completed 200 OK in 340ms (Views: 222.6ms | ActiveRecord: 99.1ms | Allocations: 90117)
I, [2022-12-07 17:06:21#12537]  INFO -- : Completed 200 OK in 309ms (Views: 196.7ms | ActiveRecord: 96.5ms | Allocations: 90117)
I, [2022-12-07 17:06:23#12537]  INFO -- : Completed 200 OK in 350ms (Views: 239.4ms | ActiveRecord: 95.4ms | Allocations: 90124)
I, [2022-12-07 17:06:26#12537]  INFO -- : Completed 200 OK in 353ms (Views: 232.8ms | ActiveRecord: 104.1ms | Allocations: 90118)
I, [2022-12-07 17:06:30#12537]  INFO -- : Completed 200 OK in 343ms (Views: 229.1ms | ActiveRecord: 98.2ms | Allocations: 90123)
```

Average: 340.7 ms

So the improvement is indeed noticeable and reproducible in staging :+1: 

Also tested basic tag functionality: hiding an OC by default - OK!

Merging :tada:

**Comment by drummer83** [comment]
Thanks @filipefurtad0 for your support!

**Comment by cillian** [comment]
@drummer83 @filipefurtad0 thanks both :+1:, yes I wasn't sure the easiest way to test this.

**Pull request merged**
