### PR TITLE
Order class tidyup

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

A little refactor pushing back slightly against the `Order` class drifting towards being a [God Object](https://en.wikipedia.org/wiki/God_object).

Trims down the public interface of the `Order` class a bit and reduces the class's overall size. Removes some superfluous methods, moves some out into other modules, and makes some methods private that don't need to be public.

There's probably a bit more we could do in this direction to put this class on a diet and remove some responsibilities, maybe extracting some of it's methods into services (`process_payments!`, `process_payments_offline!` and `process_each_payment` all feel like they could go to a service, `create_proposed_shipments` feels like it's not the `Order`'s job either, and `create_tax_charge!` and `clear_legacy_taxes!` feel like they could be extracted to a service). Anyway, this seems like a good step (and relatively small in scope). 

#### What should we test?

Green build should be enough.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Crystal clear! Thanks for making thing cleaner! 🧼 


_one rubocop complain_

**Review by mkllnk — APPROVED** [review]
Great work. :muscle:

**Comment by Matt-Yorkley** [comment]
I don't think there's any manual testing that makes sense for this PR and it's not changing any behaviour, so I'm just gonna slap the the merge button :+1:

**Comment by jibees** [comment]
> I don't think there's any manual testing that makes sense for this PR and it's not changing any behaviour, so I'm just gonna slap the the merge button 👍

Therefore, this one will be tested with all the PRs that will be included in the next release ;)

**Pull request merged**
