### PR TITLE
Enable (optional) APM with Datadog

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Part one of https://github.com/openfoodfoundation/ofn-install/issues/496

Closes https://github.com/openfoodfoundation/ofn-install/issues/318

Add option for using Rails APM with Datadog. Disabled by default.

#### What should we test?

I'll have to test this myself. Datadog APM should work.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Added `DelayedJob` APM and re-tested. :heavy_check_mark:

**Comment by sauloperez** [comment]
Can't wait to see this in production :tada: !

**Comment by sauloperez** [comment]
This is pure :heart: 

screencapture-app-datadoghq-apm-service-delayed-job-delayed-job-2019-08-14-19_46_37

screencapture-app-datadoghq-apm-service-rails-rack-request-2019-08-14-19_58_42

**Comment by sauloperez** [comment]
OMG

screencapture-app-datadoghq-apm-resource-rails-postgres-postgres-query-175688c64ced44a0-2019-08-14-20_06_53

**Pull request merged**
