### PR TITLE
Add HoundCI config

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Adds config for HoundCI automated code reviews: https://github.com/marketplace/hound

#### What should we test?

No test.

#### Release notes

Changelog Category: Technical changes

Added automated code review helper.

### CODE REVIEW

**Comment by luisramos0** [comment]
I like it, it comments in line. But it's not following our rules I think. We need to make it follow our rules.

**Comment by luisramos0** [comment]
not following our rules: https://github.com/openfoodfoundation/openfoodnetwork/pull/6186#discussion_r518473536
Thank god we dont prefer single quotes :-)

**Comment by Matt-Yorkley** [comment]
Maybe it's not picking up our settings on other branches because the config file in this PR isn't merged yet?

I'll take a look. What do you think in general though? Shall we go ahead and use it? I really like it.

**Comment by Matt-Yorkley** [comment]
Yeah, I think we need to merge this for it to pick up our rules on other branches.

**Comment by luisramos0** [comment]
I think this is quite annoying in the PRs, I am not sure everyone will agree with this, specially if the current Exclude lists are not used.
Following our rules is a hard requriement. Let's merge this and see? We can revert if it doesnt follow the rules or if we find it too annoying.

**Comment by luisramos0** [comment]
It's still incorrect Matt, maybe it's picking the default setting but not what's on manual_todo: lineLength 100
https://github.com/openfoodfoundation/openfoodnetwork/pull/6324#discussion_r518695066

**Comment by luisramos0** [comment]
Thsi lineLength thing is a blocker as we would be seeing a comment for every line over 80 chars...

**Pull request merged**
