### PR TITLE
Remove unused angular directives

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

This partially address https://github.com/openfoodfoundation/openfoodnetwork/issues/8700 and removes three unused angular directives.

* The `showMore` directive was introduced here but it looks like it was never used, see [a](https://github.com/openfoodfoundation/openfoodnetwork/commit/564c1a36503c9eb7cb90905035918c07137ddf35#diff-9760af8f4566400549860007fd0ce6ab6c142d0ec6a854af6b8bc93e3bda1b3aR1), [b](https://github.com/openfoodfoundation/openfoodnetwork/commit/564c1a36503c9eb7cb90905035918c07137ddf35#diff-ae689bfd287387619006ac1672cf0240adc13e76f692318d9a0bdfc0b150903bR71), [c](https://github.com/openfoodfoundation/openfoodnetwork/commit/564c1a36503c9eb7cb90905035918c07137ddf35#diff-b138ce97cdab2d374ea052f69b26ced5a666d36756b3ac13ac1d82479abc73e0R8).
* The `fillVertical` directive was introduced [here](https://github.com/openfoodfoundation/openfoodnetwork/commit/b1b80a1e39ddb54a6bdfcadcd4a5ceac8e9bd208) but was no longer used after https://github.com/openfoodfoundation/openfoodnetwork/commit/a3660dfe377d9577706970dee6817d23582eef2e
* The `singleLineSelectors` was no longer used after https://github.com/openfoodfoundation/openfoodnetwork/commit/532e27b7e18ebc7573c04e9af3aa9f4b2fb46417

#### What should we test?

Check the directives are not called anywhere here...

https://github.com/openfoodfoundation/openfoodnetwork/search?q=fill-vertical
https://github.com/openfoodfoundation/openfoodnetwork/search?q=show-more
https://github.com/openfoodfoundation/openfoodnetwork/search?q=single-line-selectors

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Comment by jibees** [comment]
```ruby
# For now, this component is not being used.
```

7 years ago. 

Thanks! 🙏 ☺️

**Review by jibees — COMMENTED** [review]
Thanks!

I saw that:

https://github.com/openfoodfoundation/openfoodnetwork/blob/1ca305ab7cb701d79b0014972e27cf2201a3490c/app/webpacker/css/darkswarm/_shop-filters.scss#L164

What do you think?

**Comment by cillian** [comment]
Thanks @jibees what about this instead? https://github.com/openfoodfoundation/openfoodnetwork/pull/10169/commits/c000010d0b28ef214747cb7d1a98c3fcae46a9c7 

We might be able to get rid of the CSS .filter-row class entirely, it's used [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/producers/_filters.html.haml#L6) and [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/shops/_filters.html.haml#L7) but I'm not 100% sure.

**Comment by jibees** [comment]
I removed that class and tested:

Capture d’écran 2022-12-19 à 10 43 01
Capture d’écran 2022-12-19 à 10 44 39

I've tested, and I can't see any difference...

So i've commit/pushed. Tell me what do you think about it!

c000010d0b28ef214747cb7d1a98c3fcae46a9c7

**Comment by cillian** [comment]
Looks good to me, it doesn't seem to be used anywhere :heavy_check_mark:

**Review by jibees — APPROVED** [review]
LGTM! Thanks @cillian !

**Comment by filipefurtad0** [comment]
Hey @cillian @jibees ,

I'm not sure what else would be needed from the testing side of things. I've had a quick smoke test around:

- This [commit](https://github.com/openfoodfoundation/openfoodnetwork/pull/10169/commits/d90d352a86f5a1d51e5a526656d934ff8c0c0269) seems to relate to` /customers` page: I've spotted no change in rendering or behavior
- As pointed [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10169#issuecomment-1357375753), I've had a look at the shop front and different filter selections (shop and product categories)

I'd say this is good to go? I'll more to ready to go, feel free to drop a line if anything else is needed on this one!

**Comment by jibees** [comment]
Thanks @filipefurtad0 !
Since those directives were unused, it's rather difficult to know how to test ;)

I'd say `Ready to go` then!!

**Pull request merged**
