### PR TITLE
references to payment_enterprise_id removed, new migration created

### PR DESCRIPTION
**Pull request by hughbric**
1. we ran `git grep payment_enterprise` and removed all the references (Exchange model, Spec files)
2. we created a new migration, removing payment_enterprise_id 
3. we ran the migration

### CODE REVIEW

**Comment by luisramos0** [comment]
is there an issue? why are you doing this? is it dead code?

**Comment by sauloperez** [comment]
Nice @hughbric ! don't forget to fill up the `.github/PULL_REQUEST_TEMPLATE.md`. it has the necessary information for the team to review such as a link the issue your closing, the note to include in the release, etc.

**Comment by m-budryte** [comment]
What? Why?
Closes #3789

What should we test?
Exchanges table (should not have enterprise_payment_id column)
Exchanges model (should not have references to the enterprise_payment) 

Changelog Category:  Removed

How is this related to the Spree upgrade?
Dependencies

**Comment by CathyPearce** [comment]
Checked Order cycle creation and order process still runs ok.  Checked payment_enterprise_id didn't appear in the debug information presented on the OC create screen.  No problems found.
https://docs.google.com/document/d/1aAKo-xpLv0xDO_t6CkNtixD-FEb0yASX0JghbBvH7ts/

**Pull request merged**
