### PR TITLE
Uk/filter producers for map

### PR DESCRIPTION
**Pull request by stveep**
Fix for:
https://github.com/openfoodfoundation/openfoodnetwork/issues/303

This should work until OFN Ghana opens and starts selling fish!

### CODE REVIEW

**Comment by NickWeir63** [comment]
thanks Steve

**Comment by daniellemoorhead** [comment]
Hey @mkllnk can you push this through for @stveep please :)

**Comment by mkllnk** [comment]
Could we actually distinguish between latitude `0` and latitude not set? Could it be `null`? Just for the people in Ghana and because it would be a good practice anyway.

**Comment by stveep** [comment]
You're right - think that should do it.

**Comment by daniellemoorhead** [comment]
@stveep we'll have @sstead do a quick test of this on Friday and then get it merged in.

**Pull request merged**
