### PR TITLE
Navigation css

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

- Updates the colour of the bottom border on the navigation bar (was much darker than in Zeplin)
- Adds a bit of transparency on the light grey so it looks nicer when scrolling past a section with a darker background 
- Adds bottom border to the navigation bar in mobile view (was missing)
- Updates position of the cart dropdown to be in line with the recent changes (was outdated)

#### What should we test?

Visual display of navigation bar in desktop and mobile, positioning of cart dropdown in desktop.

#### Release notes

Updated CSS on navigation bar and cart dropdown

Changelog Category: Changed

### Screenshots

**Border colour before:**
light-3

**Border colour after:**
light-2

**Border on dark background without transparency:**
dark-1

**Border on dark background with some transparency:**
dark-2

**Missing border added on mobile view:**
light-mobile

**Cart dropdown before:**
cert-drop-2

**Cart dropdown after:**
cart-drop

### CODE REVIEW

**Comment by RachL** [comment]
@Matt-Yorkley thank you! I've linked this PR to the issue I've made :)

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley I tried to stage and test this on france and Katuma and both times it failed. So I can't test it #sadface



Can you sort it out for me plesase? kthxbai

**Comment by Matt-Yorkley** [comment]
Should be fixed now :+1:

**Comment by sigmundpetersen** [comment]
Staged OK on FR

**Comment by daniellemoorhead** [comment]
**Testing notes (not worthy of a Google doc for such a small test)**

Tested on:
- Mac / Chrome + Firefox + Safari
- Browserstack: Galaxy 10, iPhone 8 + XS.

✅Border is the correct lighter colour on desktop
✅Border is transparent on darker background on desktop
✅Cart dropdown is in correct position on desktop
✅Border displays on mobile version

This is good to go!

**Pull request merged**
