### PR TITLE
Add roo gem

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Adding roo gem for #1430

### CODE REVIEW

**Comment by pmackay** [comment]
Despite this being literally one line, I have a couple of questions:

* Does the version need to be set? Most gems dont have a version and that means they will update if `bundle update` is run. 
* Might it be appropriate to use `require: false` here, and load the gem explicitly if needed? Perhaps the import process might happen separately and could load the gem independently? This import feature is not likely to be used often (compared with daily commerce use).

**Comment by Matt-Yorkley** [comment]
@pmackay I guess setting a version means you don't get unforeseen bugs arising from gem updates. 

I'm not up on dynamically loading gems... how about you take this on and I'll take that basket UI issue you were stuck on? Sound like a good trade? :)

**Comment by pmackay** [comment]
I guess gem updates should get "better" over time, including new security fixes. But any process of running `bundle update` would need careful checking and testing. 

The dynamic loading thing really depends on how the whole feature would get built :-O I'm sure you'll have it whipped up in no time ;-)

**Comment by enricostano** [comment]
Regarding the gem versioning I would even go for fixed version like `gem 'roo', '2.7.0'` since in my experience I've found much more useful to know the exact version I'm using.

I think it's our duty to keep an eye on security updates in used gems. There are even tools to raise an alert and tell developers that there is a new version covering security issues.

Running `bundle update` against a specific gem has always brougth problems in the projects where I've been working on. Running it against the whole `Gemfile` leads to disasters of course.

For me is a 👍 for `gem 'roo', '2.7.0'` or at least `gem 'roo', '~> 2.7.0'`

Sorry for jumping in like this but I just wanted to share my opinion/experience 😀

**Comment by Matt-Yorkley** [comment]
I think having the ability to update it at a scheduled time is probably preferable to having unannounced changes to the codebase whenever the maintainer releases an update?

**Comment by Matt-Yorkley** [comment]
@pmackay It looks like conditionally loaded gems stay loaded until the server is restarted anyway?

"Once a gem is loaded it's loaded until the server is stopped. By [including the gem conditionally], the first time this method is called it would load the gem, [leaving the app] in the same situation as if you were to load it normally. "

https://stackoverflow.com/questions/6086865/how-do-ruby-gems-load-in-rails#comment7058565_6087906

**Comment by pmackay** [comment]
Sure, so it would only benefit if there is a way to run an import as a separate short-lived process. I'm not sure if there is good practice around that. Probably getting too detailed on this anyway....

**Comment by Matt-Yorkley** [comment]
Closing to include this in main feature branch instead

**Pull request closed without merging**
