### PR TITLE
Fix Payments with non-3D cards need to be manually captured in the BO (Split checkout)

### LINKED ISSUE #8952: [Split Checkout] Payments with non-3D cards need to be manually captured in the BO
## Description

Payments with non-3D cards need to be manually captured in the BO.
~~Despite manually capturing them they still appear as not-captured on the Stripe Dashboard.~~

## Expected Behavior

- Payments with non-3D cards should be automatically captured (provided the card is valid), both on the UI and on Stripe.
- The button to manually capture credit card payments is displayed (when editing the order)

## Actual Behaviour

- Payments with non-3D cards are not automatically captured (provided the card is valid) in the UI, and remain uncaptured on Stripe
- The button to manually capture credit card payments is displayed (when editing the order)

## Steps to Reproduce

1. Place an order with Stripe using a simple non-3D card, like the 4242424242... 
2. Notice the payment is not taken (seen on order confirmation and order edit)

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #8952

#### What should we test?

- Described on: #8952

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

Thanks for taking this one :muscle:

On delivery circle meeting today, we've agreed on an early-feedback testing round, let's go :rocket: 

After staging the PR:

i) checking out with a regular **valid** card x-4242

We can verify that the payment does not require any additional capturing. The order confirmation screen is displayed (left, customer), the order appears as complete with a status Paid (middle, admin) and the payment appears as captured (Stripe dashboard, right):

image

This is great. I guess the introduced change in the PR processes the payment when transitioning to the confirmation screen - I did not check the DB or logs, so I'm assuming.

ii) first, attempting to check out with a regular **invalid** card x-9995; then with the valid card x-4242.

If the payment method has a transaction fee, then it will be charged for a failed payment as well, when attempting to checkout. In fact, the customer cannot even proceed to the `confirmation` step, if this card is introduced in the `payment` step: the card validity is now checked on the `payment` step - I guess this is a good thing :+1: 

However, this does lead to double (or triple, i.e., `x`) transaction fees, depending on the number of attempts the customer makes. After a successful checkout, we can see that the customer has now an order total which accounts for two transaction fees:

image

So, while this is a step in the right direction, it might introduce some overhead to customer support. I'm not sure we should move on to the next round.

What do you think @abdellani @jibees @RachL ?

**Comment by RachL** [comment]
we can merge as this is behind a feature toggl, but we will need to remove the additional transaction fee before processing with beta testers further :+1:

**Comment by abdellani** [comment]
@filipefurtad0, @RachL 

I spotted the problem.

As this part of the system is new to me, I'll share what I understood, and please correct me if I missed anything.

Every time the user updates his order, a new adjustment is created and associated with the order.
From the name, I guess those objects serve to track the changes performed on the order.
So far, I have seen two types of adjustment: 'Shipping' and 'Transaction fee'. In our context, we're interested in the 'Transaction fee'.

In the split checkout controller, we recalculate the fees after every order update
https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/app/controllers/split_checkout_controller.rb#L88-L90

The total amount is calculated using the item_total + the adjustment_total
https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/engines/order_management/app/services/order_management/order/updater.rb#L81-L83

the adjustment_total is the sum of the `additional` and `eligible` adjustments
https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/engines/order_management/app/services/order_management/order/updater.rb#L75-L79

Later, I noticed this callback on the `Payment model`
https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/app/models/spree/payment.rb#L33

https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/app/models/spree/payment.rb#L214-L224

This method goes through the previous `incompleted` payment and marks them as `invalid`, then it call `ensure_correct_adjustment`

https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/app/models/spree/payment.rb#L142-L154
`ensure_correct_adjustment` revoke the eligibility from a payment that is in one of the following stats ['failed', 'invalid', 'void']




When I reproduced the scenario of @filipefurtad0

1. I typed an invalid card and submit the order.
2. after that, I selected another payment method and moved to checkout (but without submitting the order)
Using the `rails console`, I checked `order.payments`, and here what I found
```ruby
[#<Spree::Payment:0x0000564bec0f3d48                
  id: 94,
  amount: 0.2e2,
  order_id: 54,
  created_at: Thu, 08 Dec 2022 22:16:12.838814000 AEDT +11:00,
  updated_at: Thu, 08 Dec 2022 22:16:29.065988000 AEDT +11:00,
  source_id: 23,
  source_type: "Spree::CreditCard",
  payment_method_id: 12,
  state: "failed",
  response_code: nil,
  avs_response: nil,
  identifier: "C8ESHWJS",
  cvv_response_code: nil,
  cvv_response_message: nil,
  captured_at: nil>,
 #<Spree::Payment:0x0000564bec0f3898
  id: 95,
  amount: 0.25e2,
  order_id: 54,
  created_at: Thu, 08 Dec 2022 22:16:41.761060000 AEDT +11:00,
  updated_at: Thu, 08 Dec 2022 22:16:41.761060000 AEDT +11:00,
  source_id: nil,
  source_type: nil,
  payment_method_id: 9,
  state: "checkout",
  response_code: nil,
  avs_response: nil,
  identifier: "ZVLS2223",
  cvv_response_code: nil,
  cvv_response_message: nil,
  captured_at: nil>] 
```
You'll notice that the first payment method was not removed from the order while, **I think**, it's supposed to be removed using the `after_create`callback `invalidate_old_payments`.
The reason  is that the scope used on `invalidate_old_payments`, `Payment::incompleted` doesn't cover payment with `state='failed'`
https://github.com/openfoodfoundation/openfoodnetwork/blob/e11d644a95f1a50aaece85efe7735569ca4bdd4d/app/models/spree/payment.rb#L49


I fixed the problem by invoking `ensure_correct_adjustment` on all the payments connected to the `@order` after an update.
I tested the solution and it worked.

Maybe a better solution will be to update `invalidate_old_payments` to also cover the failed payments, but I'm not sure if this will not create other problems.

**Comment by filipefurtad0** [comment]
Awesome @abdellani ,

Thank you so much for explaining your approach :clap: :clap: :clap: 
Even though I don't follow every step, I find it really useful.

This looks good now:

After repeating the failing test case, on split-checkout:
- attempting a payment with an invalid non-3D auth. card
- re-attempting a payment with a valid non-3D auth. card

We can verify that:
- the unsuccessful payment attempt left no transaction fee on the order
- the successful payment completes the order and does not require manual capturing

Screenshots to support these findings:

Customer > Order confirmation
image

Admin > Edit order > Payments tab
image

Stripe Dashboard
image

--

Regression testing:
- cash payments - OK
- successful and failed payment attempts using 3D-auth. cards - OK

This looks great, from a testing perspective :muscle: 

Over to you @jibees for code-review :pray:

**Review by jibees — APPROVED** [review]
The solution is very clear. LGTM ;) 👍 

I'm wondering if it's possible to add automatic tests on that particular case? What do you think? 
I'm wondering what is the @filipefurtad0 point of view

**Comment by filipefurtad0** [comment]
> I'm wondering if it's possible to add automatic tests on that particular case? What do you think?

It would be great to, of course.

@abdellani Do you think this is feasible on this PR still  or, instead, should we move on / merge, and open an issue to add tests later to cover this issue later?

**Comment by abdellani** [comment]
@filipefurtad0 
I prefer the second option : )

**Comment by RachL** [comment]
@jibees I guess this one is test ready?

**Comment by jibees** [comment]
> @jibees I guess this one is test ready?

Right. 
Created #10177

Moving this one to `Test Ready`

**Comment by filipefurtad0** [comment]
> Created https://github.com/openfoodfoundation/openfoodnetwork/issues/10177

Thank you for creating the issue @jibees :pray: I'll try to work on it - Perhaps at some point good to have a chat about this with @abdellani as well.

I see no code changes since it was last tested, so I'd say this is good to go - [testing notes here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10089#issuecomment-1348641956), for reference.

Merging - Thanks!

**Pull request merged**
