### PR TITLE
Sanitize HTML in custom tab content [read only]

### PR DESCRIPTION
**Pull request by anansilva**
#### What? Why?

- Part of #12448

Sanitises the HTML of custom tab content before reaching the database.

#### What should we test?

1. [Editor] Visit Admin, Enterprise settings, [white label setting](http://localhost:3000/admin/enterprises/freddy-s-farm-shop/edit#/white_label_panel). Make sure you can save the text with all the editing options provided by the editor.

2. [Store] Visit Store, Select a store and look for the previously created custom tab. The content of the tab should show up as it was edited in step 1.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Nice one, Thanks !

**Review by mkllnk — APPROVED** [review]
Great!

**Review by dacook — APPROVED** [review]

**Comment by filipefurtad0** [comment]
I'm having troubles testing this one, due to a [bug](https://github.com/openfoodfoundation/openfoodnetwork/issues/12566) which is unrelated to this PR. Adding the blocked label.

**Comment by drummer83** [comment]
Hi @filipefurtad0,
I can see you're offline currently, so I hope you're ok with me having a look at this one. :pray:

**Comment by drummer83** [comment]
Hi @anansilva,
Thank you for working on this one! I have tested it on our staging server.

## Results
- Existing content is still displayed the same. :heavy_check_mark: 
image

- New content is displayed correctly. :heavy_check_mark: 
image

- I do not see a difference in the html source code, which I think is expected, because we sanitized the code on display - if I understood correctly. :question: 
- Dangerous tags like <script> remain displayed as text. :question: 
image

- I did not test any response of the API. If that's needed, please provide some hints how to do that.

## Conclusion

I think this is working as expected. No problems with existing or new content could be found.
If you agree that I've covered everything and the :question: above is okay, feel free to merge (or let me know).

Thanks again for your work on this one! :pray:

**Comment by mkllnk** [comment]
Great. I think that the specs cover the technical part of the sanitation. So if it's still working, we can merge. :tada:

**Comment by anansilva** [comment]
Thank you both!

**Pull request merged**
