### PR TITLE
Raise error on missing translation keys

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

First part of https://github.com/openfoodfoundation/openfoodnetwork/issues/2626.

This enables our automated test to pick up most missing translations.

#### What should we test?

Not required.

#### Release notes

Added: Automated checks for missing translations.

Changelog Category: Added

#### Dependencies

The automated test will fail unless we fix all untranslated strings. So this will be blocked for a while and then needs rebasing.

### CODE REVIEW

**Comment by sauloperez** [comment]
Any reason why this is in the Blocked list? I'd :heart: to merge it

**Comment by mkllnk** [comment]
@sauloperez The PR descriptions says under dependencies:
> The automated test will fail unless we fix all untranslated strings. So this will be blocked for a while and then needs rebasing.

It's blocked, because Semaphore is still failing. We need to fix translations first.

**Comment by sauloperez** [comment]
ok, so AFAIK @luisramos0 you fixed the missing translation, right?

**Comment by luisramos0** [comment]
yep, this will be green after #3946 is merged.

**Comment by mkllnk** [comment]
This is passing now. It has been reviewed already and doesn't need tests. I'm merging it.

**Comment by luisramos0** [comment]
awesome!

**Pull request merged**
