### PR TITLE
[Headless Chrome] - Travis config WIP

### PR DESCRIPTION
**Pull request by luisramos0**
Extracted travis wip commits from the headless chrome branch.
What do we do with these @mkllnk ?

### CODE REVIEW

**Comment by mkllnk** [comment]
All this is not needed for Semaphore? I would still merge it in case we ever switch back to Travis. You never know, it's a moving market and it doesn't hurt to have these changes in the code.

**Comment by sauloperez** [comment]
but if we move back to travis chances are that the config changed and we might keeping useless code. I'd say this is just YAGNI.

**Comment by mkllnk** [comment]
I didn't want to give up Travis, because it's much easier to set up for other contributors. But if you think it's YAGNI, we should delete .travis.yml alltogether. It's broken now anyway.

**Comment by mkllnk** [comment]
And this pull request will be here in case we want to know how to use headless chrome on Travis with the OFN. Closing it.

**Comment by luisramos0** [comment]
:+1:

**Pull request closed without merging**
