### PR TITLE
[OFN-9834-PT2] Fix new product form error label styling

### LINKED ISSUE #9834: Product creation: Further improvements of errors and mandatory information
## What is the need / problem?
This is a follow-up of #9776.

Each of the following issues can be solved individually. There may be easy ones and hard ones. :wink: 

During product creation (page `/admin/products/new`) there are still some things that could be improved.
- [ ] If 'item' is selected as unit size and a value is entered in 'unit name', these values are not kept if product creation fails due to some other missing information (e.g. product name). This was missed in issue [#9067](https://github.com/openfoodfoundation/openfoodnetwork/issues/9067) and its pull request [#9177](https://github.com/openfoodfoundation/openfoodnetwork/pull/9177). Look at those for inspiration.
Peek 2022-10-20 11-22

- [ ] Add red highlighting of the input field's title (compare to field 'product name') for 'unit size' and 'product category'.
image

- [ ] Add red highlighting of the input field box and its title (compare to field 'producer name') for ''value' and 'unit name' (when 'item' is selected as 'unit size').
image

- [ ] Add a placeholder for 'supplier' instead of selecting the first option and make the field mandatory again (red star and highlighting if not selected): "Please choose a supplier" (or similar). See https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1158647656 for the discussion.
image

- [ ] Improve the 'tax category' dropdown, see https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1158664475. Details are to be agreed upon before implementation!

- [ ] Make price mandatory and evaluate input: don't set it to 0.0 if invalid input but show error message instead. There might be a reason and a previous discussion about this (see https://github.com/openfoodfoundation/openfoodnetwork/pull/9177#issuecomment-1132635366).

- [ ] Keep the uploaded image, if product creation fails, see [#9297](https://github.com/openfoodfoundation/openfoodnetwork/issues/9297).

## Which type of users does this problem affect (and how many, if known)?
- Hub Managers (MCFEs)
- Producers
- Instance Managers

### PR DESCRIPTION
**Pull request by ijdershem**
#### What? Why?

- [Closes] #9834, Part 2 & 3: 
> 1. "Add red highlighting of the input field's title (compare to field 'product name') for 'unit size' and 'product category'."
> 2. "Add red highlighting of the input field box and its title (compare to field 'producer name') for ''value' and 'unit name' (when 'item' is selected as 'unit size')."

This ensures consistent error styling between required form fields on the new product form. The 'Unit', '(Unit) Value', and 'Product Category' field labels do not currently have a red font color when an error is present on each respective field. This aims to establish styles across required fields that are currently present on the 'Product Name' field.

#### What should we test?

- Visit the new product page 
> - Submit a new product form with no value selected for 'Unit' and ensure the 'Unit' label turns red with the sub-label 'can't be blank'
> - Select a value for 'Unit' but don't input a value for the 'Value' field. Submit the form an ensure the label for the 'Value' field turns red with the sub-label 'can't be blank'
> - Submit a form with no value for 'Product Category' selected. Ensure the label for the 'Product Category' field turns red with a sub-label 'can't be blank'
- After all styling is ensured, regression test to ensure that form submission and preservation of values still functions as expected

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Thanks! 🙏 

I think that both commit 99840f4c1f623b868dc23b5a2cf81cb81e4bd460 and 5534462db4cc1c5da96acce9c65fc0e4e76c1fdf should be squashed together to have a cleaner git history ; what do you think?

**Comment by ijdershem** [comment]
> Thanks! 🙏
> 
> I think that both commit [99840f4](https://github.com/openfoodfoundation/openfoodnetwork/commit/99840f4c1f623b868dc23b5a2cf81cb81e4bd460) and [5534462](https://github.com/openfoodfoundation/openfoodnetwork/commit/5534462db4cc1c5da96acce9c65fc0e4e76c1fdf) should be squashed together to have a cleaner git history ; what do you think?

Got it!

**Review by jibees — APPROVED** [review]
LGTM! 
Thanks! 👍

**Comment by filipefurtad0** [comment]
Hi again @ijdershem ,

Thanks for another improvement here.

**Before this PR**

1) 

> Submit a new product form with no value selected for 'Unit' and ensure the 'Unit' label turns red with the sub-label 'can't be blank'

image

2)

> Select a value for 'Unit' but don't input a value for the 'Value' field. Submit the form an ensure the label for the 'Value' field turns red with the sub-label 'can't be blank'

image

3)

> Submit a form with no value for 'Product Category' selected. Ensure the label for the 'Product Category' field turns red with a sub-label 'can't be blank'

image


**After this PR**

Following the detailed instructions:

1)

-> this is verified on the pick below :heavy_check_mark: 

image

2)

-> this is not verified on the pick below :x: 
- the label for the 'Value' field does not turn red -> compare with "Before this PR" section above
- the sub-label 'can't be blank' is now appearing blue -> minor regression: was appearing red, compare with "Before this PR" section above

image

3)

-> this is verified on the pick below :heavy_check_mark: 

image


**Summary**

The PR meets the several of the requirements :muscle: but introduces a (minor) regression on point 2).

Would you be available to address this point @ijdershem ? That would be great! I'll move this back to In Dev for now.

**Comment by ijdershem** [comment]
> Hi again @ijdershem ,
> 
> Thanks for another improvement here.
> 
> **Before this PR**
> 
> 
> > Submit a new product form with no value selected for 'Unit' and ensure the 'Unit' label turns red with the sub-label 'can't be blank'
> 
> image
> 
> 
> > Select a value for 'Unit' but don't input a value for the 'Value' field. Submit the form an ensure the label for the 'Value' field turns red with the sub-label 'can't be blank'
> 
> image
> 
> 
> > Submit a form with no value for 'Product Category' selected. Ensure the label for the 'Product Category' field turns red with a sub-label 'can't be blank'
> 
> image
> 
> **After this PR**
> 
> Following the detailed instructions:
> 
> 
> -> this is verified on the pick below ✔️
> 
> image
> 
> 
> -> this is not verified on the pick below ❌
> 
> * the label for the 'Value' field does not turn red -> compare with "Before this PR" section above
> * the sub-label 'can't be blank' is now appearing blue -> minor regression: was appearing red, compare with "Before this PR" section above
> 
> image
> 
> 
> -> this is verified on the pick below ✔️
> 
> image
> 
> **Summary**
> 
> The PR meets the several of the requirements 💪 but introduces a (minor) regression on point 2).
> 
> Would you be available to address this point @ijdershem ? That would be great! I'll move this back to In Dev for now.

@filipefurtad0 Good catch, thank you for testing! I will pull this back into dev.

**Comment by ijdershem** [comment]
@jibees @filipefurtad0 We should be good to go again on this branch! Thanks again for the catch on that regression 🙂

**Review by jibees — APPROVED** [review]
Looks good to me!

Hope this is ok now. 

Thanks @ijdershem and @filipefurtad0 !

**Comment by filipefurtad0** [comment]
Hi @ijdershem and @jibees ,
Thanks! 
This looks good now :tada: 




        Submit a new product form with no value selected for 'Unit' and ensure the 'Unit' label turns red with the sub-label 'can't be blank'

image


        Select a value for 'Unit' but don't input a value for the 'Value' field. Submit the form an ensure the label for the 'Value' field turns red with the sub-label 'can't be blank'



image

        Submit a form with no value for 'Product Category' selected. Ensure the label for the 'Product Category' field turns red with a sub-label 'can't be blank'

image

Merging!

**Pull request merged**
