### PR TITLE
[Split Checkout] Update terms of service handling

### LINKED ISSUE #8765: [Split Checkout] Terms and Conditions
Showing the links to terms and conditions files and accepting them (for the instance and the hub) in the summary step of the split checkout needs some more work and improvements in the test coverage.

There's quite a lot of different combinations of scenarios, [outlined here](https://github.com/openfoodfoundation/openfoodnetwork/pull/8653#issuecomment-1016423660) by @filipefurtad0

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #8765

#### What should we test?

Tests outlined here: https://github.com/openfoodfoundation/openfoodnetwork/pull/8653#issuecomment-1016423660

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]
Will be in conflict with #8640

**Comment by filipefurtad0** [comment]
Thanks for mentioning that @jibees, I'll perhaps test/merge #8640 first (also as you'll be offline today). Hope that's ok @Matt-Yorkley ?

**Comment by jibees** [comment]
#8640 is still not ready, I've a test that fail, trying to understand why (but yes, relevant).

**Comment by filipefurtad0** [comment]
1)
**Settings**
- T&Cs: none
- ToS: none (No terms of services have been uploaded yet. This site is currently linking to your old Terms of service.)

**Result UI**
- Split Checkout -> "I agree to the platform Terms of service"  -> clicking on it displays the default ToS - OK :+1: 

**Behavior**
- Split Checkout -> ToSs need to be accepted every time - OK :+1: 

2)
**Settings**
- T&Cs: none
- ToS: custom/uploaded PDF

**Result UI**
- Split Checkout -> clicking on it displays the uploaded ToS - OK :+1: 

**Behavior**
- Split Checkout -> ToS file previously accepted? If Yes -> no need to accept again. OK :+1: 

3)
**Settings**
- T&Cs: custom/uploaded PDF
- ToS: none

**Result UI**
- Split Checkout ->  displays "I agree to the seller's Terms and Conditions and the platform Terms of service." -> clicking on the links displays the uploaded ToS and T&Cs - OK :+1: 

**Behavior**
- Split Checkout -> the default ToS and custom T&Cs need to be accepted every time - OK :+1: 

4)
**Settings**
- T&Cs: custom/uploaded PDF
- ToS: custom/uploaded PDF

**Result UI**

- Split Checkout ->  it displays "I agree to the seller's Terms and Conditions and the platform Terms of service"  -> clicking on the links displays the uploaded ToS and T&Cs - OK :+1: 

**Behavior**
- Split Checkout: the custom ToS and T&Cs only need to be accepted once - OK :+1: 

All greens! This looks great :tada:

**Pull request merged**
