### PR TITLE
removed assets related to spree store: dead code

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I found this in the context of deleting dead code here #2539 
Deleting dead UI code. The OFN frontoffice should not depend on any Spree JS code any longer.

#### What should we test?
The frontoffice (OFN shop) should work and look the same way.

#### Release notes
Removed unused Spree UI code.

Changelog Category: Removed

### CODE REVIEW

**Comment by mkllnk** [comment]
Why not in `vendor/assets`? Seems to be the Rails convention: https://guides.rubyonrails.org/asset_pipeline.html#asset-organization

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley could you take a look at this and approve pls? That way we can try and merge it and get it out of the way :)

**Comment by daniellemoorhead** [comment]
@luisramos0 can I assume this one doesn't need to be tested by Myriam or Rachel or Sally?

**Comment by mkllnk** [comment]
It should still be tested. We think that we are removing unused code, but sometimes we make mistakes.

**Comment by luisramos0** [comment]
yes, needs to be tested. we need to validate the checkout process.

**Comment by Matt-Yorkley** [comment]
Looks good, I hope we can get rid of the `split2` file without any problems.

**Comment by luisramos0** [comment]
all right, I moved it to test ready. needs staging.

**Comment by daniellemoorhead** [comment]
I think we really need the french staging server so we have 3 european options going at the same time. There are so many things to test, it will help with that. @luisramos0 if you can try and figure out why it's not working (ping @myriamboure FYI) and get access to it I think this will be a great help in clearing out the testing backlog.

**Comment by luisramos0** [comment]
ok, stagingF is working now. I'll learn how to stage and stage this one there today or tomorrow.

**Comment by mkllnk** [comment]
Staged on https://staging1.openfood.com.au/.

**Comment by mkllnk** [comment]
After deploying this, we got the following exception on staging:
```
 ActionView::Template::Error · darkswarm/all_split2.css isn't precompiled

gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:142:in `digest_for': darkswarm/all_split2.css isn't precompiled (ActionView::Template::Error)
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:151:in `rewrite_asset_path'
    from gems/actionpack-3.2.22.5/lib/action_view/asset_paths.rb:27:in `compute_public_path'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:56:in `asset_path'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:49:in `block in stylesheet_link_tag'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:43:in `collect'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:43:in `stylesheet_link_tag'
    from gems/css_splitter-0.4.5/app/helpers/css_splitter/application_helper.rb:18:in `block in split_stylesheet_link_tag'
    from gems/css_splitter-0.4.5/app/helpers/css_splitter/application_helper.rb:7:in `map'
    from gems/css_splitter-0.4.5/app/helpers/css_splitter/application_helper.rb:7:in `split_stylesheet_link_tag'
    from app/views/layouts/darkswarm.html.haml:20:in `_ab5644e7ce6d8a4a7df3eb77aaf8a69f'
    from gems/actionpack-3.2.22.5/lib/action_view/template.rb:145:in `block in render'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications.rb:161:in `instrument'
    from gems/actionpack-3.2.22.5/lib/action_view/template.rb:143:in `render'
    from bundler/gems/deface-1110a1336252/lib/deface/action_view_extensions.rb:41:in `render'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/template_renderer.rb:60:in `render_with_layout'
    from gems/skylight-1.6.1/lib/skylight/probes/action_view.rb:30:in `block in render_with_layout'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications.rb:159:in `block in instrument'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications/instrumenter.rb:20:in `instrument'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications.rb:159:in `instrument'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
    from gems/skylight-1.6.1/lib/skylight/probes/action_view.rb:29:in `render_with_layout'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/template_renderer.rb:46:in `render_template'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/template_renderer.rb:18:in `render'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/renderer.rb:43:in `render_template'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/renderer.rb:24:in `render'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb:111:in `_render_template'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/streaming.rb:225:in `_render_template'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb:104:in `render_to_body'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb:89:in `render'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/rendering.rb:16:in `render'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
    from gems/activesupport-3.2.22.5/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
    from /home/openfoodweb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
    from gems/activesupport-3.2.22.5/lib/active_support/core_ext/benchmark.rb:5:in `ms'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'

Caused by: gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:142:in `digest_for': darkswarm/all_split2.css isn't precompiled (Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError)
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:151:in `rewrite_asset_path'
    from gems/actionpack-3.2.22.5/lib/action_view/asset_paths.rb:27:in `compute_public_path'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:56:in `asset_path'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:49:in `block in stylesheet_link_tag'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:43:in `collect'
    from gems/actionpack-3.2.22.5/lib/sprockets/helpers/rails_helper.rb:43:in `stylesheet_link_tag'
    from gems/css_splitter-0.4.5/app/helpers/css_splitter/application_helper.rb:18:in `block in split_stylesheet_link_tag'
    from gems/css_splitter-0.4.5/app/helpers/css_splitter/application_helper.rb:7:in `map'
    from gems/css_splitter-0.4.5/app/helpers/css_splitter/application_helper.rb:7:in `split_stylesheet_link_tag'
    from app/views/layouts/darkswarm.html.haml:20:in `_ab5644e7ce6d8a4a7df3eb77aaf8a69f'
    from gems/actionpack-3.2.22.5/lib/action_view/template.rb:145:in `block in render'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications.rb:161:in `instrument'
    from gems/actionpack-3.2.22.5/lib/action_view/template.rb:143:in `render'
    from bundler/gems/deface-1110a1336252/lib/deface/action_view_extensions.rb:41:in `render'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/template_renderer.rb:60:in `render_with_layout'
    from gems/skylight-1.6.1/lib/skylight/probes/action_view.rb:30:in `block in render_with_layout'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications.rb:159:in `block in instrument'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications/instrumenter.rb:20:in `instrument'
    from gems/skylight-1.6.1/lib/skylight/vendor/active_support/notifications.rb:159:in `instrument'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
    from gems/skylight-1.6.1/lib/skylight/probes/action_view.rb:29:in `render_with_layout'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/template_renderer.rb:46:in `render_template'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/template_renderer.rb:18:in `render'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/renderer.rb:43:in `render_template'
    from gems/actionpack-3.2.22.5/lib/action_view/renderer/renderer.rb:24:in `render'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb:111:in `_render_template'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/streaming.rb:225:in `_render_template'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb:104:in `render_to_body'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/rendering.rb:89:in `render'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/rendering.rb:16:in `render'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
    from gems/activesupport-3.2.22.5/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
    from /home/openfoodweb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
    from gems/activesupport-3.2.22.5/lib/active_support/core_ext/benchmark.rb:5:in `ms'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
```

**Comment by luisramos0** [comment]
yeah...
I have put the split2 thing back in application.rb preconpile list.
If we do something with it, we can do it in PR #2637 
I think we should go forward with this PR without it.

**Comment by luisramos0** [comment]
This needs to be staged again.

**Comment by luisramos0** [comment]
Back to staging, this time on https://staging.openfoodfrance.org/

**Comment by RachL** [comment]
Front office looks as usual on both desktop and mobile. Guest and login checkout worked good as well.
Testing notes:
https://docs.google.com/document/d/1_tMLQZ2DHIlmbkU-tWlSgAo_bhbDAEYGRn94JBxXeIk/edit#

**Pull request merged**
