### PR TITLE
add producer and product tax category tax status to the OCSTs report

### LINKED ISSUE #9962: Get Producer and Product tax status in Order Cycle Supplier Totals Report
## Description

**- As a:** Enterprise (Hub)
**- On page:** Reports: Order Cycle Supplier Totals
**- I want to be able to:** easily identify the correct tax that needs to be reported in payments to Producers. 

In the OC Supplier Totals report I want to know if the Producer is registered for tax, and if the product is taxable. This information is contained in the Producer profile (in Aus 'Charges GST - Yes or No' in Enterprise Settings) and the Tax Category connected with the Product. 

## Acceptance Criteria & Tests
1. Add two new columns to the Order Cycle Supplier Totals reports For each line item we wish to display. These will be translatable fields: 'GST/VAT Registered' and 'Product Tax Category'.
2. Columns to be added to the end of each row.
3. 'GST/VAT Registered' will display true if the producer has 'Charges GST/VAT' enabled.
4. 'Product Tax Category' will display the tax category of the product. Consistent to other areas of the UI if no tax category is preset, 'None' is rendered.
5. For testing we wish to test each permutation (at least 4, though you  might want to test for multiple tax categories too).
6. These columns to be hidden by default in UI. API will return all data 'columns'.
7. All fields translatable
8. Unit test to cover this functionality.

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #9962 

#### What should we test?

- Described on #9962

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by abdellani** [comment]
For tests, am I supposed only to update the existing tests on `spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb`? Or to write new requests (/system) tests?

**Comment by jibees** [comment]
I think adding spec in `spec/lib/reports/*` is ok. 
If you're block on something or it's no that easy to test something in here, feel free to also create/update any spec in `spec/system/*`

**Comment by abdellani** [comment]
Hi 

I think that `spec/lib` will be enough, but I'm facing some issues with factories.
I'm planning to change the tests to make them organized as follows  
```ruby
context `with a VAT/GST-free distributor` do
 # create 2 orders
 # one with a product that has a tax category
 # the other will not have a tax category
end
context `with a VAT/GST enabled distributor` do
 # same as in the previous context
end
```

Now, when I do
```ruby
          let!(:distributor) { create(:distributor_enterprise) }
  
          let!(:order) do
            create(:completed_order_with_totals, line_items_count: 1, distributor: distributor)
          end
```
1. the product supplier will be different from the distributor. 
2. the product will automatically belong to a tax category.

Now, I don't see how I can provide parameters to the create function in order to decide to
1. enable/disable vat on the product supplier
2. select the tax category for the product.

Is it ok if  I update the database directly before running the tests?
For example, to disable the VAT in the supplier
```ruby
    it "..." do
        order.line_items.first.variant.product.supplier.update(charges_sales_tax:false)
    end
```

**Comment by jibees** [comment]
> Is it ok if I update the database directly before running the tests?

I don't see any reason to not do this. But maybe @filipefurtad0 will have a different opinion on it!

**Comment by filipefurtad0** [comment]
> Is it ok if I update the database directly before running the tests?

I think his is ok.

We could also consider updating the factories to generate the data required for that specific scenario - but I'm not sure it would be better (more clear, better performing) actually. So, I see no reason to update the DB on the test.

**Comment by abdellani** [comment]
I think that the failing test is not related to the changes that I introduced.

**Comment by sigmundpetersen** [comment]
>I think that the failing test is not related to the changes that I introduced.

Yes, it's a flaky spec (#9817)
I started a re-run of the build

**Review by jibees — COMMENTED** [review]
I think the two last commits should be squashed with their associated commit ; i don't think having `revert` in git history for the same PR makes sens. 
Also, I'm tend to think that some commits are maybe too atomic, and should probably be merged with previous or next, in order to be consistent. What do you think?

**Comment by abdellani** [comment]
Hi @jibees 
I agree.
I split the changes into two parts: 
- one that contains the report updates
- one that contains the tests

Is that better?

**Comment by jibees** [comment]
Yes, should do the work!

**Review by jibees — APPROVED** [review]
Thanks!!! 🙏 🤩

**Comment by drummer83** [comment]
Hi @abdellani, 
Thanks for working on this!

I can confirm the following changes:
- Add two new columns to the Order Cycle Supplier Totals reports for each line item we wish to display. :heavy_check_mark: 
- These will be translatable fields: 'GST/VAT Registered' and 'Product Tax Category'. :heavy_check_mark: 
- Columns to be added to the end of each row. :heavy_check_mark: 
- These columns to be hidden by default in UI. :heavy_check_mark: 

Needs adjustment (in my opinion):
- @openfoodfoundation/train-drivers-product-owners: Consistent to other areas of the UI if no tax category is preset, 'None' is rendered. :question: :arrow_right: It currently displays 'N/A' and I believe this string can't be changed/translated. My proposal would be to use the same string as on page /admin/products/new which is translated.

The following things need clarification:
- @openfoodfoundation/train-drivers-product-owners: 'GST/VAT Registered' will display 'true' if the producer has 'Charges GST/VAT' enabled. :question: :arrow_right: It currently displays 'Yes' or 'No'. Are we ok with that :question:
- @openfoodfoundation/train-drivers-product-owners: If an instance has set a default tax category, then its name will be displayed in the report if the product's tax category is set to 'None'. This could be irritating for users who are not charging GST/VAT and selected tax category 'None' intentionally. I think the behavior is ok, but I wonder if it would be less confusing if we displayed tax category 'None' in this case :question: 
- @openfoodfoundation/train-drivers-product-owners: If a product's tax category or the instance's default tax category or the enterprise's setting of 'charges GST/VAT' was changed during the time span of the report, this can't be seen. The line items will be all grouped together according to the current settings. Assume that an enterprise started to charge GST after they already made some sales without charging GST, the report will be incorrect, because all sales will be displayed as 'charges GST/VAT = yes'. How should we handle this :question: 
- @abdellani: All fields are translatable. :question: :arrow_right: Can you please confirm that both the strings in the columns select dropdown as well as the column headers are using the same translations :question: 

Not (fully) tested yet:
- For testing we wish to test each permutation (at least 4, though you might want to test for multiple tax categories too).
- API will return all data 'columns'.
- csv, xlsx and pdf are updated accordingly.
- Other order and fulfillment reports remain unchanged.

Out of scope for manual testing:
- Unit test to cover this functionality.

### :exclamation: Notes :exclamation: 
I suspect that there could be an underlying issue here with tax calculations, because I saw some other strange behavior not only in the reports. :arrow_right: #10059

I will move this back to In dev for now.

**Comment by lin-d-hop** [comment]
> https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: Consistent to other areas of the UI if no tax category is preset, 'None' is rendered. question arrow_right It currently displays 'N/A' and I believe this string can't be changed/translated. My proposal would be to use the same string as on page /admin/products/new which is translated.

I would suggest that in the CSV and json versions we render nothing - leave blank.
In the spreadsheet, pdf and screen versions we render human readable versions we render 'none'

> https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: 'GST/VAT Registered' will display 'true' if the producer has 'Charges GST/VAT' enabled. question arrow_right It currently displays 'Yes' or 'No'. Are we ok with that question

In the CSV and json versions we render: true/false
In the spreadsheet and screen versions we render human readable versions: yes/no

> https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: If an instance has set a default tax category, then its name will be displayed in the report if the product's tax category is set to 'None'. This could be irritating for users who are not charging GST/VAT and selected tax category 'None' intentionally. I think the behavior is ok, but I wonder if it would be less confusing if we displayed tax category 'None' in this case question

I would suggest that in the CSV and json versions we render nothing - leave blank.
In the spreadsheet, pdf and screen versions we render human readable versions we render 'none'

> https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: If a product's tax category or the instance's default tax category or the enterprise's setting of 'charges GST/VAT' was changed during the time span of the report, this can't be seen. The line items will be all grouped together according to the current settings. Assume that an enterprise started to charge GST after they already made some sales without charging GST, the report will be incorrect, because all sales will be displayed as 'charges GST/VAT = yes'. How should we handle this question

This is a known and existing problem within OFN. Genuinely solving it is out of scope for this issue - realistically we are years from fully facing this issue. Not a great answer but fully fixing this is a huge challenge, most enterprises face this challenge once, if ever, and there are (tedious) workarounds.

**Comment by abdellani** [comment]
>@abdellani: All fields are translatable. question arrow_right Can you please confirm that both the strings in the columns select dropdown as well as the column headers are using the same translations?

@drummer83, Yes I confirm

**Comment by abdellani** [comment]
> > https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: Consistent to other areas of the UI if no tax category is preset, 'None' is rendered. question arrow_right It currently displays 'N/A' and I believe this string can't be changed/translated. My proposal would be to use the same string as on page /admin/products/new which is translated.
> 
> I would suggest that in the CSV and json versions we render nothing - leave blank. In the spreadsheet, pdf and screen versions we render human readable versions we render 'none'

When We render the report in one of the following versions : [CSV, JSON ], the values from the table are rendered without formatting.

In the remaining formats : [spreadsheet, pdf and screen ]. The values are formatted using `RreportRowBuilder#ormat_cell`.
For example `true`/`false` will be changed to the translation of `Yes` or `No`

The `nil` value [is mapped to  "" (empty) ](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/reporting/report_row_builder.rb#L77).
```ruby
    def format_cell(value, column = nil)
      return "" if value.nil?
...
    end
``` 

In other words, if we render nothing in CSJ/JSON, we'll render nothing ("") in the other formats.

We can't change that without affecting the other reports.
 
> > https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: 'GST/VAT Registered' will display 'true' if the producer has 'Charges GST/VAT' enabled. question arrow_right It currently displays 'Yes' or 'No'. Are we ok with that question
> 
> In the CSV and json versions we render: true/false In the spreadsheet and screen versions we render human readable versions: yes/no

It works like that now.
```ruby
    def format_boolean(value)
      value ? I18n.t(:yes) : I18n.t(:no)
    end
```

> > https://github.com/orgs/openfoodfoundation/teams/train-drivers-product-owners: If an instance has set a default tax category, then its name will be displayed in the report if the product's tax category is set to 'None'. This could be irritating for users who are not charging GST/VAT and selected tax category 'None' intentionally. I think the behavior is ok, but I wonder if it would be less confusing if we displayed tax category 'None' in this case question
> 
> I would suggest that in the CSV and json versions we render nothing - leave blank. In the spreadsheet, pdf and screen versions we render human readable versions we render 'none'

Same as in the first comment.

**Comment by lin-d-hop** [comment]
Hi @abdellani 
Can you tell me what the options are for the blank/none fields?

Can we render 'none' in all versions? If so let's do that.

**Comment by abdellani** [comment]
> Hi @abdellani 
>Can you tell me what the options are for the blank/none fields?
> 
> Can we render 'none' in all versions? If so let's do that.

Hi @lin-d-hop 

Now, "" in CSV/JSON is mapped to "" in the other formats.

I'll map it to "none".

**Comment by abdellani** [comment]
In the failing test, we are expecting the CSV report to have a summary row.
This is not consistent with the UI where when the user selects the CSV format, the summary row is disabled automatically.

**Comment by abdellani** [comment]
@kirstenalarsen Sorry, for being late.
I fixed the test now.

I want to precise that before calling `report.render_as(:csv)`, the report needs to have `report_format: 'csv'` in the params.

To fix the test, I wrapped the test inside a new context where I updated the report params.
I also updated the csv file.

**Review by jibees — APPROVED** [review]
LGTM!

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

I'll split the testing notes in separate comments.

**API**

The request:
`https://staging.openfoodnetwork.org.uk/api/v0/reports/orders_and_fulfillment/order_cycle_supplier_totals?token=db4e79475fd7c47979b60eaabf793d6dd053728122b42067&reports_subtype=order_cycle_supplier_totals&q[completed_at_gt]=2022-11-15+00:00&q[completed_at_lt]=2022-12-15+00:00`

**Before this PR** returns:
(left, browser+console; right, Postman with the API request, after enabling the feature  `api_reports` on Flipper)

image

**After this PR** returns:
image

- We can see that the columns  'GST/VAT Registered' and 'Product Tax Category' are deactivated by default, but are visible on the API response.

From [these acceptance criteria](https://github.com/openfoodfoundation/openfoodnetwork/pull/9990#issuecomment-1331304874):
- no tax category: UI/PDF/Spreadsheet - `none`;  CSV - empty; json - `null`  - OK
- attributed tax category: UI/PDF/Spreadsheet - CSV and json - `product_tax_category` is displayed - OK
- GST/VAT Registered: UI/PDF/Spreadsheet - `Yes`; CSV and json - `true` - OK
- GST/VAT not-registered: UI/PDF/Spreadsheet - `No`; CSV and json - `false` - OK

This looks great and ready to ship :rocket: 
Thanks Mohamed! Merging.

**Comment by kirstenalarsen** [comment]
Yippee! Great work @abdellani and @filipe - really appreciate you getting
this through!

**Comment by filipefurtad0** [comment]
Updating the syntax to get the columns via API request (we need to overwrite `fields_to_hide`):
`
https://staging.openfoodnetwork.org.uk/api/v0/reports/orders_and_fulfillment/order_cycle_supplier_totals?token=db4e79475fd7c47979b60eaabf793d6dd053728122b42067&reports_subtype=order_cycle_supplier_totals&q[completed_at_gt]=2022-11-15+00:00&q[completed_at_lt]=2022-12-15+00:00&fields_to_hide[]`

**Pull request merged**
