### PR TITLE
Fix a few rubocop warnings manually and run rubocop autocorrect

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I improved Rubocop situation a little manually and then realized rubocop auto-correct exists!

Updated rubocop auto generated todo list by running [the command in the top of the file](https://github.com/openfoodfoundation/openfoodnetwork/blob/59d4e3d9e2192524d807b8dbc4271b427adea1ac/.rubocop_todo.yml#L2).

Also updated rubocop manual todo list following the process described in the file.

#### What should we test?
We can run a sanity check.

#### Release notes
Changelog Category: Changed
Improved code readability.

### CODE REVIEW

**Comment by luisramos0** [comment]
ready for review.

**Comment by luisramos0** [comment]
thanks @kristinalim I just rebased.

**Comment by sauloperez** [comment]
And another one :trollface:

**Comment by sauloperez** [comment]
Do we agree on approving it in Code Climate and fix the issues in other PRs? I'm afraid it'll take too long to fix them here.

**Comment by luisramos0** [comment]
yeah, these 119 issues are existing issues on files where we fix issues in this PR, this PR fixes hundreds of them but not all.

so, I rebased, and moved to test ready.

**Comment by sigmundpetersen** [comment]
Build failed after rebase, looks related to #3828?

**Comment by lin-d-hop** [comment]
Successfully passed sanity check on UK staging:
1) Log in
2) Create product
3) Add to OC
4) Order product and checkout
5) See order in back office

**Comment by luisramos0** [comment]
fixed conflict in users_and_enterprises_report.rb (I kept what is in master to avoid the need to test this again).
build is green.
merging.

**Pull request merged**
