### PR TITLE
Test mdbootstrap

### LINKED ISSUE #7500: Test to build a component with MDBootstrap
As discussed from [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/7198#issuecomment-805790718), it's time to choose a CSS framework to build robust, clean, usable components thanks to our StyleGuide, view_components and soon ReactiveRails.

There was a discussion about the choice between CSS utility framework _Tailwind_ and _MDBootstrap_.

Since we do not come to a conclusion, we purpose to test the two solutions. 

This PR is for MDBoostrap.

The component can be chosed from the issues listed in this epic : #7198

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
 1. I try to use MD components as much as possible to create the FilterField component: I failed. Then I used the utilities classes.
 2. ~I try to customize a component created by MDBootstrap~ to customize a component, you have to import MDBootstrap as a sass file (and not with a CDN like this is done in this PR) which suppose to integrate it into the build of the assets. As the first step was very deceptive, I did not go any further

Closes #7500

#### Screenshots
Capture d’écran 2021-06-30 à 11 01 01

Capture d’écran 2021-06-30 à 11 01 06

Capture d’écran 2021-06-30 à 11 01 11

#### PROS
Probably useful when you use the component _as it_.

##### Components are often paid
This one was near the global one:  https://mdbootstrap.com/docs/standard/forms/select/ but paying, which is very frustrating.

Pricing is here: https://mdbootstrap.com/docs/standard/pro/#section-pricing 

I can't see any prices for OpenSource projects.

##### All rules are written with `!important`
Which has some advantages (bootstrap take the lead on each existing CSS rules) but you can't override it manually with some styles over the elements (which is not a great rule but can be sometimes a good idea).

#### Conclusion
When components is not available (and the list of available components that are free are not as long), you simply use MDBoostrap as an utility CSS framework which is a little lower in terms of functionality than tailwind : 
 - Documentation is  not as clear and filled than tailwind
 - There's a lot of lack in term of utility classes (cursor, transition, transform, sizing, pseudo-classes ...) : I had to add some inline styling which is very frustrating (`cursor: pointer;`, `max-width: max-content;`, ...). Therefore functionality is clearly not at the same scale.
 - CSS is not compiled, so it seems that you provide an entire CSS file even if you use only 2 rules in your project (as far as I understood)
 
_**My conclusion**: For me, it is clearly a no-go, MDBoostrap is not at the same level as tailwind and it's lack of already done components (that are in terms of numbers, very poor)  doesn't compensate the huge gap that exists in term of utility classes._

@openfoodfoundation/core-devs I'd be happy to hear from you.

### CODE REVIEW

**Comment by andrewpbrett** [comment]
Looks like a pretty strong vote for Tailwind. Are we ready to make a decision on this?

**Review by mkllnk — COMMENTED** [review]
Some pretty convincing findings. Are you also doing an implementation with Tailwind as a comparison?

**Comment by jibees** [comment]
> Some pretty convincing findings. Are you also doing an implementation with Tailwind as a comparison?

Sure, already done : https://github.com/openfoodfoundation/openfoodnetwork/pull/7543 ;)

**Comment by mkllnk** [comment]
Ah, sorry, it has been such a long time that I didn't see the connection between the two PRs.

Comparing the two PRs, Tailwind seems to need more code. Or is that just the level of details you went into? Some examples:

```diff
-%div
+%div.max-w-max

-%div.border.position-relative{style: "max-width: max-content;"}
+%div.bg-white.border.border-gray-300.py-2.px-5.relative.max-w-max.rounded-sm

- %div.position-absolute.top-0.start-0.translate-middle.d-inline-bloc.px-2.ms-5.bg-white= @title
+%div.text-gray-500.absolute.-top-2.px-3.-ml-3.bg-white.text-xs= @title
```

The result in the screenshots is very similar but I find that the Tailwind screenshots look better. You were able to introduce some nice shades of grey. Is that what you struggled with in mdbootstrap?

I reckon that the difficulty customising is a really big downside and a pro for Tailwind. Frameworks that don't integrate well become a real pain later on.

**Comment by jibees** [comment]
> The result in the screenshots is very similar but I find that the Tailwind screenshots look better.

Yes, I managed easily to go further with tailwind. I quickly gave up with MDBoostrap.

> You were able to introduce some nice shades of grey. Is that what you struggled with in mdbootstrap?

Yes. And by default, there's a lot of shades in Tailwind (that don't need any customization)


Regarding the quantity of code, (even if I don't think it's a relevant standalone metric), both of the files are 30 lines long, 2055 characters long for MDBoostrap vs. 2190 for Tailwind, but with best customization as you saw.

**Comment by Matt-Yorkley** [comment]
I suspect the journey OFN will go on with Tailwind might end up looking a lot like OFN's journey with AngularJS (with everything that entails, including the initial excitement). I could be wrong though, and I don't have the bandwidth or the energy to argue, so I guess we can go with Tailwind and see what happens :ok_hand:

**Comment by jibees** [comment]
> I suspect the journey OFN will go on with Tailwind might end up looking a lot like OFN's journey with AngularJS (with everything that entails, including the initial excitement).

I hope tailwind will give us the opportunity to separate from it in the way that is more efficient than AngularJS does.

>  I could be wrong though, 

I could be wrong too, I just think (and I tested) that, at this time, this is the best solution for us. Of course, I'd be happy to change my judgment later on (or now btw!). 

> and I don't have the bandwidth or the energy to argue, 

Sorry to hear that. I thought we had severals opportunities to discuss about (github conversations, slack conversations, call meetings), and I don't want that someone from the team feels frustrated by such a decision. 
Proposals: 
 - Re-questionning the problem: we're focused on tailwind vs. MDBoostrap. Why not changing our point of view by changing the question?
 - Take the decision later on, maybe after the summer, so everyone (including you) could review and make their own PR by creating a component with Tailwind and/or MDBootrap?
 - Maybe we can say that if we go with tailwind, this should be a _not final_ decision that should be answered some months later.

> so I guess we can go with Tailwind and see what happens

Can we also schedule a meeting, such like "Tailwind, N months after : pros and cons"? I think this could be a good idea to always re-questionning our choices as we go along.

**Comment by andrewpbrett** [comment]
Thanks for the work on this @jibees. At [Delivery Train](https://community.openfoodnetwork.org/t/delivery-notes-july-6th/2348) we landed on option 3, going with Tailwind but making sure to revisit in 3 months. I think we can close these now.

**Pull request closed without merging**
