### PR TITLE
Merge 2-0-stable to master

### PR DESCRIPTION
**Pull request by luisramos0**
Are we merging 2-0-stable with a PR like this?
Or do we force push 2-0-stable into master?

@sauloperez @mkllnk @Matt-Yorkley @kristinalim

### CODE REVIEW

**Comment by mkllnk** [comment]
Yes, exactly like this. :rocket:

**Comment by sauloperez** [comment]
YES! :muscle:

**Comment by sauloperez** [comment]
If merge already we will make it much harder to have any other releases between now and the 1st v2 deploy. What if just leave this until the very moment we are ready to deploy? I left a comment related to it in https://github.com/openfoodfoundation/openfoodnetwork/pull/3697.

**Comment by luisramos0** [comment]
yeah, this is more a visualization exercise :-D
let's merge this a bit later and allow for a easy v1 release if needed.

also, before we merge we should create a branch with v1 right? 1-30-stable

**Comment by sauloperez** [comment]
> also, before we merge we should create a branch with v1 right? 1-30-stable

that would another solution. Then any needed patch releases should come from that branch. But then of course, we will need to merge them into `master`.

**Comment by luisramos0** [comment]
all right, lets do that then.

One thing we can do is to plan for a v1 release on the 30th as well :-)
What about this plan:
Somewhere before the April 30th:
       - prepare v1.31.0 from master
       - create branch 1-31-stable from master
       - merge 2-0 into master
       - double check it's all good with new master
       - prepare v2.0.0 from master

April 30th:
      - release v1.31.0 to all instance except Katuma and CAN that get v2.0.0.

**Comment by mkllnk** [comment]
Sounds good. I guess we want another v1 release with bugfixes for the current S2 bugs.

**Comment by luisramos0** [comment]
v1.31.0 is prepared
new branch: https://github.com/openfoodfoundation/openfoodnetwork/tree/1-31-stable

this PR can be merged now! ready for review :-D

**Pull request merged**
