### PR TITLE
 Fixes minor styling issues of admin and admin v3 in the dashboard

### LINKED ISSUE #11843: [BUU] Dashboard: Thin blue border around the Order Cycles section
## Description

On the multi-enterprise dashboard there is a thin blue border around the order cycles section if no active order cycles are available.

## Expected Behavior

It should look like the products section, which means a red border should be used instead.

## Actual Behaviour

There is a thin blue border.

## Steps to Reproduce

1. As an enterprise user with more than one enterprise, make sure you have no active order cycle available.
2. Visit the dashboard.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #11865: [BUU] Dashboard: Text ‘You have x active …’ is black for products, while it’s blue for order cycles (for multi-enterprise user)
## Description

The text ‘You have x active …’ is black for products, while it’s blue for order cycles.

## Expected Behavior

The colours should be identical.
Both should be very dark gray (almost black) like the text for products.

## Actual Behaviour

The text for order cycles is blue.

## Steps to Reproduce

1. As admin make sure you have more than one enterprise.
2. Make sure you have at least one product and one open order cycle.
3. Visit /admin/dashboard.
4. Check the colours.

## Animated Gif/Screenshot

image5

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by drummer83**
#### What? Why?

- Closes #11843
- Closes #11865

**Before:**
image

image

**After:**
image

image

#### What should we test?

- Activate admin style v3
- Make sure you have multiple enterprises but no order cycle open and no products.
- Visit the overview page /admin.
- Check that there is no thin blue border around the 'Manage order cycles field'.
- Check that the products section looks identical.
- Create a product.
- Open an order cycle.
- Check that the text 'You have x active ...' has the same color for products and order cycles.
- Check that the other pages remain unchanged and everything is working.

Additional changes which could be tested:
- With admin style v3 deactivated:
  - With products and order cycles active
    - Check that clickable areas turn into green when hovering
    - Check that clickable areas have no line when focusing them via TAB key
  - With NO products and NO order cycles active
    - Same as above.
  - With less than 6 enterprises available 
    - Check that the enterprise list does not have a scroll bar (allowing to scroll only few px)
  - With 7 or more enterprises available
    - Check that the enterprise list has no border when focusing via TAB key

- With admin style v3 activated:
  - With products and order cycles active
    - Check that clickable areas turn into darker blue when hovering
    - Check that clickable areas have a thin dark blue line when focusing them via TAB key
  - With NO products and NO order cycles active
    - Same as above.
  - With less than 6 enterprises available 
    - Check that the enterprise list does not have a scroll bar (allowing to scroll only few px)
  - With 7 or more enterprises available
    - Check that the enterprise list has a thin dotted border when focusing via TAB key (Firefox only?)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by drummer83** [comment]
A questions for @mariocarabotta:
Should we make the 'focused' pseudo-class identical with 'hover'? The focus is very difficult to see currently when using the TAB key (just a 1px line).

A question for @dacook and @mariocarabotta:
Should we get rid of the spree color definitions in admin style v3? We still have these in use in the dashboard:
```
$spree-blue = $color-btn-bg
$spree-green = ?
$spree-light-blue = ?
```

**Comment by mariocarabotta** [comment]
> A questions for @mariocarabotta: Should we make the 'focused' pseudo-class identical with 'hover'? The focus is very difficult to see currently when using the TAB key (just a 1px line).
> 

I agree it's actually quite difficult to see. @dacook had [re-enabled the outline default](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1701826434392259) a few weeks ago. 
I am not 100% sure what this means "Should we make the 'focused' pseudo-class identical with 'hover'?" - apologies if i'm misunderstanding it!
I had a look at a few websites and it seems like they increase the default line thickness (and style too..), but don't use the hover style when focused.
maybe we could increase the thickness of the dotted line? some examples from google and nngroup below.
Screenshot 2023-12-26 at 14 54 35
Screenshot 2023-12-26 at 14 53 27

> A question for @dacook and @mariocarabotta: Should we get rid of the spree color definitions in admin style v3? We still have these in use in the dashboard:
> 
> ```
> $spree-blue = $color-btn-bg
> $spree-green = ?
> $spree-light-blue = ?
> ```

mmm this one I'm definitely not familiar with - will leave it to @dacook, sorry

**Comment by dacook** [comment]
> Should we get rid of the spree color definitions in admin style v3?

They definitely need cleaning up, yes. But it will be hard to do that until we remove the old design, so for now we will keep them to enable easy switching between old/new design.

**Comment by dacook** [comment]
> Should we make the 'focused' pseudo-class identical with 'hover'? The focus is very difficult to see currently when using the TAB key (just a 1px line).

There's three main states to consider here:
* "Current" (the tab that's currently loaded)
* Focus (keyboard navigation with tab)
* Hover (mouse hover)

Here's a couple of examples (in that order)

Screen Shot 2023-12-28 at 3 31 39 pm
Screen Shot 2023-12-28 at 3 31 21 pm
Screen Shot 2023-12-28 at 3 34 09 pm

(there's a couple other states but these seem to be ignored in the above examples so I've also ignored them).

I like the blue outline for focus (this is browser default anyway) which is nice and clear, and I think the darkened background on hover is a good convention too. 

I would consider these changes as lower priority (the current design doesn't inhibit use of the system) but would love to see it improved one day..

**Review by dacook — APPROVED** [review]
Great!

**Review by mkllnk — APPROVED** [review]
Great!

**Comment by RachL** [comment]
Looking good, thanks @drummer83 !!! Merging :)

**Pull request merged**
