### PR TITLE
PI: landing page

### LINKED ISSUE #2455: Product import: review page layout and UX for product import landing page
## Description
We have review the UX of product import to avoid confusion, reduce the number of clics, and try to find some consistency.

## Acceptance criteria
capture du 2018-07-12 09-01-49

- **there is not anymore any "guideline page" within the backoffice so the button is gone**. We have integrated in the PO landing page a "helper" box with the possibility to download templates and the values that should be in those templates for columns that require fixe values. Those values are extracted from the instance configuration so for consistency it is better to put them here than in the user guide. Also today there is no user guide per instance and values change from each instance.
- templates for product listings and inventories are accurate. Especially, the template for inventory only has the necessary columns, some existing columns can be delete. Some column headers have been renamed for more clarity. See https://docs.google.com/document/d/1QDtKQe64enO5ZLnht9PxQ8bOlaMHCueJBMWSyW4zCng/edit# for headers in each template.

EDIT FROM RACHEL : The template part will be deal with in this new issue : https://github.com/openfoodfoundation/openfoodnetwork/issues/2481

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2455

Removes Product Import guide and adds a sidebar to the initial product import page. Mostly superficial changes to views and CSS, and removal of an old route.

#### What should we test?

Guide is gone. New sidebar with info is on Product Import page.

#### Release notes

Product Import: Updated landing page for Product Import and removed guide.

Changelog Category: Changed

### CODE REVIEW

**Comment by mkllnk** [comment]
Staged on https://staging1.openfood.com.au/.

**Comment by RachL** [comment]
@Matt-Yorkley the connected issue has 2 acceptances criteria : 
- the button and the help box (which are in this PR)
- the csv templates that should match the template in google docs
Are you working on another PR for the second point ? As I don't see the match.
Here are my testing notes : 
https://docs.google.com/document/d/16oSgekVOjGHq2IayaqWt6tkzJqVjRD8r935fMtDemSU/edit#

**Comment by Matt-Yorkley** [comment]
There's a couple of things missing from that google template, for example the `sku` field can be set on variants. It was proposed to rename the way inventories templates use the fields "producer" and "supplier", but I think I'll do that in another PR because it will be a bit messy if it's included here.

**Comment by RachL** [comment]
Ok @Matt-Yorkley then I will create another issue. Does the last change you made requier review or can we moved it to test again ?

**Comment by Matt-Yorkley** [comment]
I think back to testing is OK if the specs are green, it was just some minor changes to some specs to remove unnecessary code and a change to the CSV template.

**Comment by RachL** [comment]
Ok moving forward with this one. The new issue is here : https://github.com/openfoodfoundation/openfoodnetwork/issues/2481

**Pull request merged**
