### PR TITLE
Admin, Enterprise Details: Fix country selection on business address panel

### LINKED ISSUE #9777: Admin, Enterprise Settings, Business Details Panel, Business Address : First country of the available ones is selected
## Description
Regarding several hub in `fr-prod`, it appears that all of them have Afghanistan selected as their country on page, although it seems very unlikely.

`/admin/enterprises/[HUB_PERMALINK]/edit#!#business_details_panel` :

Capture d’écran 2022-10-13 à 12 22 51

\+ it seems that when we change country selector value, the state selector options do not change at all. 

*Important drawback*: when saving anything is this page (ie. `/admin/enterprises/[HUB_PERMALINK]`), I guess that the country will be effectively changed to Afghanistan (instead of France in case of `fr-prod`)

## Expected Behavior
Right country is selected. Ie. should be France in most of case.

## Actual Behaviour
Although France is the country saved in DB, it appears that Afghanistan is selected since it's the first one on the list.

## Steps to Reproduce

1. As an admin, go to `/admin/enterprises/[HUB_PERMALINK]/edit#!#business_details_panel`
2. Change country to a country that is not the first in the list
3. See that state options did changed
4. Select a state that is not the first on the list
5. Save
6. And then refresh the page, and see that country/state are well saved and are selected in the components.

## Workaround
I don't see any workaround. Each time will save anything on the page, first country of the selector will be saved.

## Severity

bug-s2: a non-critical feature is broken, no workaround

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9777

+ Actually should also solves many bugs on dependEnt-select also
+ correct some CSS alignment

Capture d’écran 2022-10-13 à 14 30 44

This probably needs some automatic specs since we didn't spot anything...

#### What should we test?

1. As an admin, go to `/admin/enterprises/[HUB_PERMALINK]/edit#!#business_details_panel`
2. Change country to a country that is not the first in the list
3. See that state options did changed
4. Select a state that is not the first on the list
5. Save
6. And then refresh the page, and see that country/state are well saved and are selected in the components.

Also
Test everywhere the double selector country/state is present on admin section that when changing country, the options state also change

Also
Business address could be different as address: (France/Haute-Garonne vs. France/Gers)

Capture d’écran 2022-10-13 à 15 14 53
Capture d’écran 2022-10-13 à 15 14 58

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by binarygit — APPROVED** [review]
Looks good to me @jibees :)

**Review by mkllnk — APPROVED** [review]
Great! :muscle:

**Comment by drummer83** [comment]
Hi @jibees,
Thanks for this PR!

**Before this PR**
- Layout issue of 'legal address' on page 'business details'
- Layout issue of 'country' and 'state' selectors on page 'business details
- Available states of business address depend on the selected country on page 'address'
- Country and state of business details always jump to the first available option after saving
image

**After this PR**
- Layout issue of 'legal address' on page 'business details' --> FIXED :heavy_check_mark: 
- Layout issue of 'country' and 'state' selectors on page 'business details --> FIXED :heavy_check_mark: 
image
- Available states of business address depend on the selected country on page 'address' --> FIXED :heavy_check_mark: 
- Country and state of business details always jump to the first available option after saving --> STILL OPEN :x:
Peek 2022-10-17 21-49

**Summary**
Most of the issues are fixed, but the saving of state and country of the business address still isn't working properly. It still jumps back to 'Afghanistan' and 'empty'.
Moving back to In Dev to have another look.

**Comment by jibees** [comment]
@drummer83 
Ok, I see. It's a different-but-related issue.
Actually, when you only change the country/state of a non-existing business address (ie. every fields are empty), the business address is not saved anymore. Then, there is no feedback that tells you "hey, you're trying to save an non complete business address".
To test this issue around the country/state behavior, you need to fill all the needed form for a business address.

**Pull request merged**
