### PR TITLE
Setup simplecov

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

This enables code coverage analysis when running specs in your dev
environment. Simply run them as usual and you'll see a line like the
following at the end of the output:

```
Coverage report generated for RSpec to /home/pau/dev/openfoodnetwork/coverage
```

Simply browse to coverage/index.html and the results in a web UI.

This is a useful tool that helps you decide if the tests you added are
enough or not.

##### Screenshots

screenshot from 2018-09-27 15-58-40
screenshot from 2018-09-27 15-58-30

#### What should we test?

Nothing. This is for development only.

#### Release notes

Add SimpleCov to enable code coverage analysis.

Changelog Category: Added

### CODE REVIEW

**Comment by sauloperez** [comment]
What do you mean? To get these screenshots I just did `bundle exec rspec ...`

**Comment by luisramos0** [comment]
it was a joke, I meant: is there a plugin to make rspec itself faster? I think it is rather slow...

**Comment by sauloperez** [comment]
What's slow is booting Rails and using ActiveRecord. You should use zeus which is stated somewhere in the docs. It is critical for my TDD cycles.

**Comment by luisramos0** [comment]
OMG, I missed that one (it's not on macos sieera setup guide). I need to install that.

**Comment by sauloperez** [comment]
It'd be great to share our setups. I'm sure there are lots of tips we're missing from each other.

**Comment by Tengoot** [comment]
[Deep-cover](https://github.com/deep-cover/deep-cover) may be also a nice addition to this project. I usually use both Simplecov and DeepCover, I think it's worth consideration. So far I am happy with that setup for my own usage and DeepCover makes difference.

**Comment by sauloperez** [comment]
Interesting @Tengoot!

**Comment by daniellemoorhead** [comment]
@sauloperez #dotheadminplease
screen shot 2018-10-01 at 1 37 02 pm

**Comment by sauloperez** [comment]
sorrryyyy

**Pull request merged**
