### PR TITLE
Test building component through our styleguide with tailwind

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

The aim of this PR is only to demonstrate and show a _real_ example of how we can customize our next components thanks to tailwind css framework.
There is no build and so this is not usable at all inside the app, only in storybook. 
The component view is here : `app/components/filter_field_component/filter_field_component.html.haml` 
Please, @openfoodfoundation/core-devs we need our inputs. 🙏 

_**Must not be merged. Only here for reviews.**_

##### Closed
Capture d’écran 2021-05-04 à 17 29 44

##### Opened
Capture d’écran 2021-05-04 à 17 28 28

##### Closed with one selected option
Capture d’écran 2021-05-04 à 17 28 41

##### Opened with one selected option
Capture d’écran 2021-05-04 à 17 30 08

References #7501, #7199

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Just putting this out there: I don't think we can reasonably use the CDN option. It's designed for quick examples and not meant to be used in production. It's almost 3 Megabytes of CSS that needs to be parsed during rendering, and doesn't work with half of Tailwind's features, as detailed here: https://tailwindcss.com/docs/installation#using-tailwind-via-cdn

**Comment by jibees** [comment]
@Matt-Yorkley Totally agree, this PR is just here as a test, to see how we can create components with tailwind and compare with the solution like MDBootstrap. This PR shouldn't be merged for the reason you explained. 

I thought it was clear as we discuss here: #7539 // Take the CDN approach just to test and compare with MDBootstrap and then, once CSS framework has been chosen, fully and properly integrate with webpacker.

**Comment by jibees** [comment]
@Matt-Yorkley would take in charge this linked issue concerning MDBootstrap: #7500 ?
Or I can take, but maybe it's more fair if it's you.
What do you think?

**Review by mkllnk — COMMENTED** [review]
I personally find this way of styling difficult to read. But I haven't worked with it yet and I don't know what all the classes mean. The result looks nice.

I'm not sure if I can give a valid opinion here. Creating our own classes which re-use Tailwind declarations could make it more legible.

**Comment by jibees** [comment]
> I personally find this way of styling difficult to read. But I haven't worked with it yet and I don't know what all the classes mean. 

The documentation is well filled, and you can easily find what you're looking for. 

> The result looks nice.

Yes, I agree: very close to the requirements and without customize anything, which looks like promising. This was very fast to code also.

> Creating our own classes which re-use Tailwind declarations could make it more legible.

I think we probably should prefix the tailwind classes since we're working with an existing codebase / css framework: https://tailwindcss.com/docs/configuration#prefix

For creating (ie renaming?) our own classes, I must admit that I'm skeptical and I don't see the value that we could bring (I mean, better than the tailwind team, which work on it since years)

**Comment by Matt-Yorkley** [comment]
So the other technical issue is that using Tailwind properly requires PostCSS 8, which requires Webpacker 6, and Webpacker 6 is not even released yet and is still in beta (and is not recommended for production). We need to introduce Webpacker for use with StimulusReflex, but Webpacker 5.3 is the latest stable version (which I think we'll have to use), which means we can't use PostCSS 8...

**Comment by jibees** [comment]
AFAIK, it seems possible to install tailwind with PostCSS 7:
https://tailwindcss.com/docs/installation#post-css-7-compatibility-build (which seems to be frictionless)

**Comment by mkllnk** [comment]
> For creating (ie renaming?) our own classes, I must admit that I'm skeptical

That's not what I meant. I was thinking of creating new classes for components. For example we could create a class "search-select-area" which contains `.bg-white.border.border-gray-300.py-2.px-5.relative.max-w-max.rounded-sm`.

**Comment by Matt-Yorkley** [comment]
> For example we could create a class "search-select-area" which contains `.bg-white.border.border-gray-300.py-2.px-5.relative.max-w-max.rounded-sm`

I think the idea is that _you don't do that_ with Tailwind :man_shrugging:

**Comment by jibees** [comment]
A great article about tailwind, and **recurring criticism of utility-first**. Worth a read: 
https://frontstuff.io/in-defense-of-utility-first-css

**Comment by Matt-Yorkley** [comment]
> A great article about tailwind, and **recurring criticism of utility-first**. Worth a read:
> https://frontstuff.io/in-defense-of-utility-first-css

Moving towards more of a focus on utility classes and composition is definitely a good thing! :100:

You can do that without Tailwind though (and without completely ditching the Cascade), and for example lean on the newer parts of the CSS/HTML spec like CSS Custom Properties (which Tailwind ignores) and the new things introduced by the Web Components stack.

Jared White has a pretty good take based on a lot of experience on Tailwind and non-Tailwind projects: https://dev.to/jaredcwhite/why-tailwind-isn-t-for-me-5c90

**Comment by mkllnk** [comment]
Nice articles.

I agree with a lot of points of In Defense of Utiltiy-First CSS. I've definitely seen "too much abstraction, too early" with people applying BEM. There's one point about avoiding repetition with components. It's not about "utility-only", it's

> “utility-first, then component”

> the whole point of utility-first is that you start composing with utility classes, and then create components when you start identifying repetitive patterns.

Tailwind gives us a first level of abstraction and we can build further abstraction on top of that.

There's also a recommendation to use the long class names instead of the abbreviations. I think that it would help everyone to get familiar with it quicker. We can't expect every developer to be a Tailwind pro.

When reading the Why Tailwind Isn't for Me article, I also agree with some points. Having lots of Tailwind classes in HTML is ugly. But I'm sure that you can get around that by bundling some in good components.

Is it true that Tailwind relies on Javascript? I'm sure that there are better solutions nowadays.

In the end, both articles are a bit opinionated. One claims that using high abstraction is just moving the ugliness from HTML to the CSS files but it's still there. It's maybe the same ugliness for a front-end dev, but for a back-end dev, it makes a big difference to have clean HTML because we need to fit the Ruby logic in there as well.

I'm also wondering if we can adopt a utility-first approach without Tailwind. Or maybe it doesn't matter what's first. We can also start with components and then break them down into smaller chunks when needed. I think that the key is to refactor your CSS from a big picture view to create a coherent and flexible library instead of patching little things locally and overriding overrides which becomes more complex over time. Native browser support is also evolving quickly and has the advantage of being a proven best practice compared to frameworks which are first the pioneers of a new way (cool at the time) and then getting clunky and outdated as browsers move on.

My personal conclusion is that Tailwind can be useful as an initial library but that we still need components as well. While Tailwind can be useful, I don't think that it's a must-have. We can also build on pure CSS and leverage all the new browser features. It's much more important that we design carefully than which framework we use.

Maybe we just need some guidelines like:

- Utility classes are allowed.
- Component classes are allowed.
- Combine these when needed.
- Split them when needed.
- Don't let a framework or naming scheme rule everything, apply with skilful care.

*Not that those guidelines really define anything.* :smile:

**Comment by jibees** [comment]
> My personal conclusion is that Tailwind can be useful as an initial library but that we still need components as well.

@mkllnk I can't agree more about what you're saying: thanks for explain it clearly, it makes a lot of sense. 🙏 

I see Tailwind as useful tool, that shouldn't be only seen as a overly constrained framework (that's why I do prefer it)

Components (when needed) FTW! ;)

**Comment by mkllnk** [comment]
We need a decision on this, right? I guess that the options are:

- Writing our own utility classes and use the latest CSS features.
- Using Tailwind and build our own abstractions and utility classes.

It appears to me that @jibees is pro Tailwind and @Matt-Yorkley is pro writing our own.

I need more information for a decision. How much complexity does Tailwind add? Will we need additional Javascript for Tailwind? Are we in a position to use Tailwind now?

**Comment by jibees** [comment]
> How much complexity does Tailwind add?

I don't know what you mean by _complexity_ but it's just about having a look to their documentation when you want to customize an html element to use the right classes. 


> Will we need additional Javascript for Tailwind?

As far as I understood, we should use https://github.com/rails/webpacker to use Tailwind. It also be a good idea to use such a project to build our js/css/assets, ... (whatever we do, choosing Tailwind or not)

> Are we in a position to use Tailwind now?

We should add webpacker, configure it, configure tailwind (as we use already a lot of classes in our code base, it should be safe to add a prefix like `ofn-` to all classes generated by Tailwind, see https://tailwindcss.com/docs/configuration#prefix) and check that everything goes right.

On the other hand, 
>  @Matt-Yorkley is pro writing our own.

not sure to understand what this means exactly. I thought it was more about using an already well defined CSS framework, that handles "components" classes (like `button`, `dropdown`, ...) directly (such as https://mdbootstrap.com/). Did I miss something? What's our plus-value of writing our own utility-first CSS framework (compared to using an opensource one, that has already been tested and approved a lot...)?

**Review by luisramos0 — APPROVED** [review]
This looks good to me, it's a valid way of going forward.

Going forward by just building our own classes doesnt seem right, tailwind will help us acelerate.
I think the alternative is to adopt something like https://material.angular.io/ I'd also support that if you prefer.

**Comment by andrewpbrett** [comment]
Closing, see https://github.com/openfoodfoundation/openfoodnetwork/pull/7852#issuecomment-875034777

**Pull request closed without merging**
