### PR TITLE
Update 'Bulk Coop Supplier Report'

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes openfoodfoundation/wishlist#409

#### What should we test?

- described on openfoodfoundation/wishlist#409

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
Thanks @abdellani !

I'd love to have better commit message. I don't think "update" adds much value. Maybe we should write something like "Add `producer_id` column" or "Rename supplier column by producer" (same for the commit of the spec, I'd love to have a commit message such as "Update tests to take into account the new column `producer_id`" ; should probably be into the same commit as well....)

**Comment by jibees** [comment]
Furthermore, I think it's important to contextualize a bit the PR by adding a comment, a screenshot, a _why I've done what I've done_ in the PR's description. It's easier then to review. What do you think?

**Comment by lin-d-hop** [comment]
PLease don't merge these changes. The issue is not ready for delivery and thus we can't release these changes. Thanks.

**Comment by abdellani** [comment]
Sorry @lin-d-hop, I didn't notice that.
I'll convert this PR to a draft.

**Pull request closed without merging**
