### PR TITLE
Fix untranslated buttons at image step of registration modal

### PR DESCRIPTION
**Pull request by haseleyi**
#### What? Why?

Closes [#3161](https://github.com/openfoodfoundation/openfoodnetwork/issues/3161)

This change fixes missing translations on the "back" and "continue" buttons for the Images step of enterprise registration and transitions the form's translations to lazy-loading.

#### What should we test?

In the Images step of an enterprise registration, look to the "back" and "continue" buttons at the bottom of the view.

#### Release notes

Fixed untranslated buttons at image step of registration modal.
Transitioned the translations in this form to lazy-loading.

Changelog Category: Fixed

### CODE REVIEW

**Comment by haseleyi** [comment]
Thank you both! How does that look?

**Comment by daniellemoorhead** [comment]
OK, so this has been sitting waiting for testing over a week ago. Let's get to it, @sauloperez or @luisramos0 or @Matt-Yorkley @mkllnk can you get it onto the next available staging server (currently AU and UK are in use) and get it ready for testing? 

#toottoot

**Comment by RachL** [comment]
deploying au Aus staging

**Comment by RachL** [comment]
image

This looks good!

**Pull request merged**
