### PR TITLE
Rails 5 2 update Rspec controller syntax

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

starts 7090

#### What should we test?
Less deprecation warnings and a green build.

#### Release notes

Changelog Category: Technical changes

Adapts code to rails 5.2

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Looking good. I'll rebase to hopefully trigger a successful build.

**Comment by luisramos0** [comment]
I think I need to have a look.

**Comment by luisramos0** [comment]
ok, 3 of the changes were not necessary, I removed them. Should be green now.

**Comment by luisramos0** [comment]
green build in GH.

**Review by andrewpbrett — APPROVED** [review]

**Pull request merged**
