### PR TITLE
Set retry count to 2 on system tests in CI

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Discussed in a previous meeting; sets retry count to 2 so we can avoid a few flaky specs and save some time.

#### What should we test?

-

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — COMMENTED** [review]
I don't like this. It makes it very unlikely that we detect new flaky specs before they are merged. We will just accumulate flaky specs over time again.

**Review by dacook — COMMENTED** [review]
Hmm, tricky one.

If we accumulate flaky specs, but they don't bother us, does it matter? 
* It increases runtime, which is not really a problem because it's already quick, but does waste resources (which are no cost to us, but still contribute CO2 emissions and take away from other OSS projects).
* It perhaps delays the inevitable: if specs become more flaky, they still impact on us and we need to fix them anyway. 

So it results in increased tech debt, but the "interest" (to use the debt metaphor) is virtually nil.

Even though it's probably a reasonable practical compromise, my gut feeling says it's better not to hide problems. The OFN codebase can be overwhelming, and allowing this might make it moreso in the long run.

**Comment by rioug** [comment]
I don't like it either, as @mkllnk said it will most likely hide new flaky specs. I think it's better to stick to adding a `retry` on per test basis, it also add context when looking at a spec file.

**Comment by dacook** [comment]
@Matt-Yorkley thanks for following up on the original discussion. But based on the comments here it looks like we don't want to proceed. Should we discuss further or are you happy to close it?

**Comment by mkllnk** [comment]
No movement for weeks. I'm closing this but happy to discuss if you think that we haven't considered everything properly.

**Comment by filipefurtad0** [comment]
Thanks @Matt-Yorkley for following up on this - I must admit I've lost it from sight - and everyone for chipping in on the discussion :heart: 

It's great to have gathered your thoughts around this.

I agree that it's good to keep the awareness on what's flaky. On my side, I feel it can be a bit overwhelming - quantity and complexity: the solution I think goes through better time management (maybe even 1hr time-boxing, each time I pick up such an issue).

Thanks again :pray:

**Pull request closed without merging**
