### PR TITLE
Various enterprise management adjustments

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Reordered the Enterprises edit page submenu for #390.

Changed the way text displays in the editor on the About Us tab to be visually consistent with the spacing of paragraphs on the front-end, to resolve issue #375.

Created a dropdown in Enterprise edit page for switching between enterprises for #421, including a popup warning if attempting to switch whilst there is unsaved data in the current page form.

### CODE REVIEW

**Comment by kirstenalarsen** [comment]
Awesome :)

**Comment by Matt-Yorkley** [comment]
Now also addresses #420, by displaying a confirmation popup if the user tries to navigate away from the page by other methods (not just the dropdown) whilst the form contains unsaved changes. Refactored a bit and added some comments for clarity.

**Comment by kirstenalarsen** [comment]
It's really exciting to see these annoying things getting sorted out :)

**Comment by Matt-Yorkley** [comment]
That key value was a funny one. I used `'data-url'` instead of `:data-url` as the key because I was getting an error saying that dashes are not allowed in symbols. Just looked it up and the alternatives are `:'data-url'`, or HAML now converts `:data_url` to `'data-url'` when rendering. I'll keep it in mind.

As for pulling the second function out into a separate file, I thought it might be problematic as the first function interacts with the second. May be it's not an issue. Looking at it now though, maybe it would be a good idea to use jquery's event namespacing on the `beforeunload` event so that bind and unbind could be called on the specific handler without interfering with other potential bindings...

Also it needs a translation on the message string...

**Comment by Matt-Yorkley** [comment]
@stveep Am I right in thinking if I pull the function out into a file and re-include it via the Rails asset pipeline, it'll be included site-wide?

**Comment by mkllnk** [comment]
@Matt-Yorkley 

> I used 'data-url' instead of :data-url as the key because I was getting an error saying that dashes are not allowed in symbols.

There is another solution to that: `data: { url: 'value' }`
Thats good if you have multiple `data-*` attributes. Otherwise `"data-url" => "value"` is okay I think. I didn't know that HAML converts underscores. Does our version support it? Do we use that anywhere?

> Am I right in thinking if I pull the function out into a file and re-include it via the Rails asset pipeline, it'll be included site-wide?

Yes, that is correct. All JS assets are bundles into one big file `all.js`.

**Comment by Matt-Yorkley** [comment]
As an angular training excercise, I've dropped the jquery completely and rewritten it as an angular directive and a service. I found an existing angular NavigationCheck factory that only runs on the enterprise page but didn't seem to be working, and fixed it (the callback was passing a function that checked the form's $dirty state, but it was getting run in a separate file that didn't have access to the same scope). That and the new service can now be used on other parts of the site where they're needed.

**Comment by stveep** [comment]
Nice one! Think it's good to do these things in Angular where possible - good practice and makes the project a bit more consistent.

Not sure why the spec is failing, it passes for me locally. Probably just needs to be rebased on master?

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Are all the commits in here from Rohan the result of you updating your branch but not rebasing?
Can you cherry-pick out the relevant commits so that we can test this more easily? And when you do, can you put them in a branch of the pattern uk/* so that they can be tested more easily by oliver?
Thanks!

**Comment by Matt-Yorkley** [comment]
Rebased the branch as suggested, tests passing.

**Comment by lin-d-hop** [comment]
@Matt-Yorkley This PR still shows 86 commits and 148 files changed. Can you clean it up please? This might mean cherry picking onto a new branch (in which case use uk/* pattern so it can be tested easily).

We then need to test it. This would be much easier if there was one issue per PR to test so we can document the testing.

It's really great you've been so helpful with all the little fixes here @Matt-Yorkley... but now we need to test it and demonstrate the fixes in a clear way to the international community this clump of fixes becomes confusing. If you could help us out be splitting out and clarifying what is fixed where that would make the whole process much more manageable.

**Comment by Matt-Yorkley** [comment]
Closing to tidy up and resubmit as multiple smaller PRs that are simpler for uk testing.

**Pull request closed without merging**
