### PR TITLE
Move taxons and taxonomies from spree_backend to OFN 

### PR DESCRIPTION
**Pull request by luisramos0**
### What? Why?
Part of #4050

This moves all things related to taxonomies and taxons from spree_backend to OFN. No change in functionality.

### What should we test?
The pages must work correctly as before.
Taxonomies: create taxonomy, sort taxonomies. Edit taxonomy: (use right click) add, rename, remove and edit Taxons.
Existing issues:
- cannot delete taxonomy even if newly created if more than one level of taxons.
- cannot sort taxons inside taxonomy #2944

### Release notes
Changelog Category: Changed

Imported views from spree_backend to make OFN more independent of Spree.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
There's quite a few Codeclimate issues. Do you want to handle them separately?

**Comment by luisramos0** [comment]
this is spree code, these are the not easy ones (complexity, etc). I dont want to fix all of them, a lot of work...

**Comment by luisramos0** [comment]
moving to test ready.

**Comment by RachL** [comment]
@luisramos0 code climate is complaining. Can I still test it?

**Comment by luisramos0** [comment]
yes @RachL I dont think we need to fix all issues in the spree code.

**Comment by RachL** [comment]
@luisramos0 I wonder : how can I actually create a taxonomy? I would need to drag it above "products" which is our main taxonomy, right?

**Comment by luisramos0** [comment]
you use the button "new taxonomy"

**Comment by RachL** [comment]
@luisramos0 :woman_facepalming: I was looking at the edit taxonomy page, so sorry.

Taxonomies:CRUD is working. Sorting is working in the UI, but not in the product category list
Taxons : add and edit is working.

I believe we will need another issue for sorting taxonomies. But this is pre-existing so it is ready to go!

**Comment by luisramos0** [comment]
thank you!
there's an issue already for the sorting problem: #2944

**Comment by RachL** [comment]
@luisramos0 this issues covers the sorting within a taxonomy so the sorting of taxons. But I tested as well the sorting of taxonomies. And nothing happened on the categories dropdown when creating a product for example. But I guess for now sorting taxonomies is less prioritary.

**Comment by luisramos0** [comment]
yeah, and is the order of taxonomies used anywhere now? I mean, the product categories are not taxonomies, they are taxons inside the Product Categories taxonomy.

**Comment by luisramos0** [comment]
I dont think I understand what is weird. We have a taxonomies system and we use one of the taxonomies as product categories. What's the confusion?

**Comment by sigmundpetersen** [comment]
In 'New Product' you can choose the taxonomy as on of the categories, e.g. 'Products', 'Others'. I guess that's the weird thing you mention, no @RachL ? They're sorted alphabetically among the other taxons/categories

**Comment by luisramos0** [comment]
ah, my mistake, all taxonomies and all taxons are shown on the product categories list. I think only taxons inside the Products taxonomy should be shown. But that's not the case now.

**Pull request merged**
