### PR TITLE
[Spree 2 Upgrade] - Added adapted order.shipping_method

### LINKED ISSUE #2009: [Spree 2 Upgrade] Replace Order#shipping_method with Order#shipments
`Order#shipping_method` is gone in Spree 2.0, so any line of code that uses it in OFN will fail. We can provide the same behaviour but being spree-2.0 compatible without having to wait for a specific spree-2.0 branch :metal:

The work has already been started in: https://github.com/openfoodfoundation/openfoodnetwork/pull/1651

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2009 

WIP: This is the quick fix, it still needs cleaning up, docs and tests.

#### What should we test?
More specs fixed.

#### Release notes
Changelog Category: Fixed
Adapted to spree 2 multi shipments by adding adapted shipping method to order.

#### How is this related to the Spree upgrade?
This is part fo the spree upgrade.

### CODE REVIEW

**Comment by luisramos0** [comment]
hey @sauloperez @mkllnk @HugsDaniel 
Before I proceed here I'd like to confirm the approach with you guys.
Would you agree I should use the same approach here as in #2638 VariantStock?
I'd create something like a OrderShippingMethodConcern with this (see the commit in this PR) adapted version of shipping_method and shipping_method= (see commit on PR #2669 for shipping_method=).

I think that would be the best approach. If you guys agree, I can create that class and write some unit tests and docs for it.
Thanks!

**Comment by luisramos0** [comment]
Moving to "Code Review" to get feedback. Will move back to "In Dev" once feedback is gathered and decisions taken.

**Comment by mkllnk** [comment]
I like the separation in a concern. The decorator is too big anyway and I don't see any downside.

**Comment by luisramos0** [comment]
This is ready for review with new concern, unit tests, docs and db constraint.

**Comment by luisramos0** [comment]
I have copied the approach from #2638 See this comment:
https://github.com/openfoodfoundation/openfoodnetwork/pull/2638#issuecomment-419987397

**Comment by sauloperez** [comment]
I couldn't stop myself @luisramos0 :trollface: . I hope there was nothing missing.

**Comment by luisramos0** [comment]
ahaha, awesome, lets do this 🎉

**Comment by luisramos0** [comment]
I have changed my mind. I am closing #2009.
I have opened #2685 to fix the order_spec.

**Pull request merged**
