### PR TITLE
Bring spree_backend payments controller to OFN

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Related to #4050

We bring payments_controller from spree_Backend and merge the decorator in OFN.

We fix some rubocop issues but leave abc size and method length on create and fire for later. These are reflected in the new todo_manual file.

#### What should we test?
We need to verify the page to capture payments in the order.
Create payment, capture payment, cancel payment.
We should test these things above with several order states as well as several payment methods.

There's this edge case where we delete the payment method and the list of payments of a past order with that payment method still shows the name of that deleted payment method correctly. I wonder if this is working in the current version. I havent tested this.

#### Release notes
Changelog Category: Changed
Brought the backoffice page that captures payments from spree to make OFN independent of Spree.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Needs a rebase @luisramos0

**Comment by sigmundpetersen** [comment]
Also needs a rebase

**Comment by luisramos0** [comment]
:+1: done

**Comment by RachL** [comment]
@luisramos0 when I click on a payment method of an order, I get an error 500 and I don't see this in production. Could it be linked to this PR?

Example link: https://staging.katuma.org/admin/orders/R064445101/payments/174

image


image

**Comment by luisramos0** [comment]
It was a bug in my migration of the code, I didn't see there was a show action. This link on the "payment method" column goes to a page that shows the payment...
It's now working. I just staged it to ES.

**Comment by luisramos0** [comment]
ready for testing in katuma.

**Comment by RachL** [comment]
Great I think this is ready to go!

I've tested creating, capturing and cancelling on all 3 payments methods.

Also

>There's this edge case where we delete the payment method and the list of payments of a past order with that payment method still shows the name of that deleted payment method correctly. I wonder if this is working in the current version. I havent tested this.

This is working as well :tada:

**Pull request merged**
