### PR TITLE
Uk/order cycle report

### PR DESCRIPTION
**Pull request by stveep**
Updates to OC report email

### CODE REVIEW

**Comment by stveep** [comment]
OK I am done with adding stuff now! (waits for build to fail...)

**Comment by sstead** [comment]
image

**Comment by oeoeaio** [comment]
@stveep, see @sstead's comment above showing a continuing issue with the way tax is calculated for the producer emails. I haven't had a look at the code myself yet. but we are keen to get this through asap, so if you'd like me to have a go at a fix, just say the word.

**Comment by stveep** [comment]
Hi @oeoeaio ,
Sorry I've had a look but having trouble reproducing the error; I can't figure out how to get tax adjustments applied to line items in the factories.
If you want to fix it go ahead - or alternatively just remove the tax column for now (tax breakdown wasn't in the previous email so no one will miss it I guess) and I will try again when I have more time later in the week.

**Pull request merged**
