### PR TITLE
Scope variant to take overrides into account in packer

### LINKED ISSUE #7337: Backoffice order blocked at 'Address' stage
## Description

Create order in back office for enterprise 201078 using OC 207544 (also tested for OC 207889)
Unable to complete the order placement.
Can not access 'Payments' tab
Order remains with status = 'Address'

Product stock is overridden in inventory but inventory settings do not necessitate products being in the inventory for them to be added to an order cycle.
No tag rules
Products added to backoffice orders are in the corresponding OC and are in stock in inventory.
Enterprise has delivery shipping methods set up.

Tested another enterprise and back office order placement works as predicted.

## Expected Behavior

Create order in back office for enterprise 201078 using OC 207544 (also tested for OC 207889)
Add product in 'Order Details'
Visit 'Customer Details' and add address
Visit 'Payments' and add a payment
complete the order

## Actual Behaviour

Create order in back office for enterprise 201078 using OC 207544 (also tested for OC 207889)
Add product in 'Order Details'
Visit 'Customer details' and add address
click update
click on 'payments' to finalise order placement. 
Taken back to 'customer details'

Revisit incomplete order and edit.
Products removed from 'Order Details' section. Fees remain only.

## Steps to Reproduce

1. Create order in back office for enterprise 201078 using OC 207544 (also tested for OC 207889)
2. Add product in 'Order Details'
3. Visit 'Customer details' and add address
4. click update
5. click on 'payments' to finalise order placement. 
6. Taken back to 'customer details'

1. Revisit incomplete order and edit.
2. Products removed from 'Order Details' section. 
3. Observe Fees remain only.

## Severity

bug s2
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #7337

See comments on the issue for an extended discussion, but it appears that backoffice orders weren't accounting for inventory variant overrides ... ever?

#### What should we test?

Set a product (Tomatoes) to have 0 on hand and "on demand?" unchecked in the product list
Add Tomatoes to Inventory and set On Hand to 10 and On Demand to No
Add Tomatoes to a back office order
Enter customer details
Before this PR:
Get stuck at "Address" state
After this PR: 
Moves to "Payment" state

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
LGTM.

It'll need tests though :wink:

**Comment by andrewpbrett** [comment]
Yeah I'm doing battle with one right now 🙄😆

**Comment by sauloperez** [comment]
can we help you @andrewpbrett ?

**Comment by Matt-Yorkley** [comment]
Awesome :100:

I'm wondering if we should add a quick feature test as well, covering this flow:
1. Create a new order via admin
2. Add a product that has zero stock but has an override with plenty of stock
3. Hit the save/next button
4. Check that section of the order edit UI that's been occasionally vanishing is actually there, and the line item is shown as we expect

What do you think?

**Comment by andrewpbrett** [comment]
I like it, good catch @Matt-Yorkley. Added a feature spec.

**Comment by Matt-Yorkley** [comment]
I had a look at the feature spec and it seems like it passes in master (without the bugfix). I tried writing another test and that _also_ passed. So... I tried writing an even longer test that went through the whole flow, and finally managed to replicate the bug in a test. Also confirmed it's fixed by the `Stock::Packer` change here :+1:

I'm not sure if it's worth adding it, but it looks like this: https://github.com/openfoodfoundation/openfoodnetwork/commit/a8daa725a2f317665a98c3bece53ef13216b0439

**Comment by andrewpbrett** [comment]
That looks a lot better, thanks @Matt-Yorkley 👍

**Review by sauloperez — APPROVED** [review]
awesome! this could be merged right away IMO. That feature spec gives me enough confidence. What do you say?

**Comment by andrewpbrett** [comment]
> this could be merged right away

SGTM 👍

**Comment by sauloperez** [comment]
decreed then!

**Pull request merged**
