### PR TITLE
removes mini_portile2

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

This gem is not used.

#### What should we test?

- Check if the deployment works without any issues.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
For reference, this gem was added based on this thread https://openfoodnetwork.slack.com/archives/CEBMTRCNS/p1668439152992899
It was reported as a missing dependency in ofn-install build.

Maybe we can run the ofn-install build on this branch and see if it fails?

**Comment by dacook** [comment]
📚 🧙‍♂️

**Comment by dacook** [comment]
Thanks for finding that info Sigmund! It sounds like the issue is specifically when installing with Vagrant, which doesn't happen in the ofn-install CI, we would need to manually test this on a dev machine. 

I'll see if I can properly test it now..

If not, I think it would be better to simply add a comment to the Gemfile to document _why_ we have the gem, so that Sigmund doesn't have to go searching again next time.

**Review by dacook — COMMENTED** [review]
.. My Vagrant VM failed to boot for some reason 😞 

@abdellani are you able to try it? 

Otherwise, I'd be happy if we just added a comment in the Gemfile for now.

**Comment by abdellani** [comment]
@dacook  Vargant is not installed on my environment :( 
I'll just add the comment to the Gemfile.

**Review by dacook — APPROVED** [review]

**Comment by dacook** [comment]
Thankyou

**Comment by dacook** [comment]
(oops I should have updated the PR title before merging!)

**Pull request merged**
