### PR TITLE
Added orderBy 'name' to the list of shipping methods offered

### PR DESCRIPTION
**Pull request by Duende13**
Hi @lin-d-hop! Solved issue #1626 ordering the methods by name.

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@oeoeaio should we get @sstead to test this now?

**Comment by oeoeaio** [comment]
@daniellemoorhead yep, I've approved it, so its good to go

**Comment by lin-d-hop** [comment]
@Duende13 Would you take a look at @enricostano s requested changes so we can try get this tested in time for the august release? Thanks! :-D

**Comment by Duende13** [comment]
Hi @enricostano  , I hope that this test is enough and thank you once more for your guidance and help. :) Let me know if you want me to add /change something else.

**Comment by daniellemoorhead** [comment]
@lin-d-hop will leave this to you guys to test in the UK, let us know when you think it's good to go :)

**Comment by lin-d-hop** [comment]
@OliverUK would you be happy to test this one for us?

**Comment by OliverUK** [comment]
Is there a build for it @lin-d-hop Lynne?

**Pull request merged**
