### PR TITLE
Modify default hash tabs controller to redirect users to shopping panel when an OC is selected.

### LINKED ISSUE #12076: Selecting OC redirects to shop's home page
## Description

Regression from  #5748 / #5072.
Reported [here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1706002650311759).

If a shop has a home page set, then selecting an OC from a shop redirects redirected to the home page instead of the shop page. This happens each time an order cycle is selected.

## Expected Behavior

Selecting an OC from a shop redirects redirected to the home page instead of the shop.

## Steps to Reproduce

As hub/admin:
1. Set an enterprise with a homepage (on `admin/edit#/shop_preferences_panel`, type some text in the Shopfront Message and save changes )

As a customer:
2. Visit the shopfront.
3. Select any tab (other than the Homepage tab)
4. Select an order cycle
5. Notice you're being redirected to the Homepage and not the Shop tab

## Animated Gif/Screenshot

Taken from [here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1706002650311759):

https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/0840f5c6-73b9-4269-96a2-97f233faa7ec

## Workaround

The current workaround is deleting the home page, which is not really a good workaround.

## Severity

priority bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.26
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Ideally, the PR closing this issue should improve the test case in the [relevant spec](https://github.com/openfoodfoundation/openfoodnetwork/blob/25a4e45171f426168b5cb42b792af64c31758e3e/spec/system/consumer/shopping/shopping_spec.rb#L141), since it the enterprise has no homepage set.

### PR DESCRIPTION
**Pull request by basilawwad**
#### What? Why?

- Closes #12076  

The activateDefaultPanel function takes the user to the default page, when a home_panel is added, it is set as the default page instead of the shop_panel.

#### What should we test?
see #12076

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Thank you!

**Review by rioug — APPROVED** [review]
Thanks for your help ! looks good :+1:

**Comment by mkllnk** [comment]
@rioug I'm moving this to Test Ready on the Github board as well. New process! Good bye Zenhub.

**Comment by drummer83** [comment]
Hi @basilawwad,
Thanks for working on this one!

I have tested it on our staging server and it's looking good!

I can confirm that
- when changing the shop through the /shops page, the user is still redirected to the home page. :heavy_check_mark: 
- as soon as the user selects an order cycle, they get redirected to the shop page. :heavy_check_mark: 
- when selecting a different order cycle, the user gets redirected to the shop page as well. :heavy_check_mark: 
- also when visiting other tabs - like 'Contact' - the user gets redirected to the shop page when changing the order cycle. :heavy_check_mark: 

I can't think of much more to test here, actually.

We're good to go!
Merging! :rocket: :tada: 

Thanks again!

**Pull request merged**
