### PR TITLE
Disable RSpec cops by default

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

There was just too much. Some of them seem over the top, while others look like they could be really helpful.
But we don't have time to evaluate them all right now.

Also a couple of other random spec fixes.

- Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/11253, at least for now

#### What should we test?
Green specs 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by dacook** [comment]
Need to wait for reviewdog rate limit to reset.

Also check again if RSpec/DescribeClass is still raising error. It looks like the default config should be covering it fine:
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#configurable-attributes-6

**Review by rioug — APPROVED** [review]
Good one ! We should track updating the rspec cops somewhere

**Comment by dacook** [comment]
Good point. I had added it to the list on https://github.com/openfoodfoundation/openfoodnetwork/issues/6055.

I think I'll leave it there, so that we evaluate it _after_ first cleaning up other cops.

**Comment by dacook** [comment]
FYI @mkllnk I merged this to avoid havoc with over-the-top cops.

**Comment by dacook** [comment]
[tumblr_msoajmw16q1shtqlxo1_1280](http://40.media.tumblr.com/6397dd93cc15929f3e54aa8a3d0f4def/tumblr_msoajmw16q1shtqlxo1_1280.jpg)

**Pull request merged**
