### PR TITLE
Add convenience script to install Ruby

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

We updated Ruby a few times recently and I find it very convenient to just call this script instead of typing the Ruby version.

#### What should we test?

Dev test:

```sh
./script/rbenv-install.sh
```

It shouldn't raise any error. I've used this in another project and it has been great so far. :smile: 

#### Release notes

Changelog Category: Technical changes

Add convenience script to install Ruby

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
Have you tried the docker setup? I strongly recommend it.

**Review by andrewpbrett — APPROVED** [review]

**Comment by mkllnk** [comment]
> Have you tried the docker setup?

Not really. I found the additional overhead a bit annoying in the past.

**Comment by sauloperez** [comment]
> I found the additional overhead a bit annoying in the past.

in terms of slowliness? To me, that I work on multiple projects, is a life saver.

**Comment by mkllnk** [comment]
> in terms of slowliness?

A bit of slowness, yes, but also entering a container each time I want to run a command. You probably find ways to make it convenient but it's not necessary for me.

**Comment by jibees** [comment]
I've tested.

Ruby 2.7.3 was already installed on my side, so when I launched the command, I got:
```
➜  openfoodnetwork git:(rbenv-install) ✗ ./script/rbenv-install.sh
Ruby is installed.
```

Then, I uninstalled the ruby version 2.7.3 with rbenv: `rbenv uninstall 2.7.3`

And I retriggered the command:
```
➜  openfoodnetwork git:(rbenv-install) ✗ ./script/rbenv-install.sh                                                  
Downloading ruby-2.7.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.3.tar.bz2
Installing ruby-2.7.3...
ruby-build: using readline from homebrew
Installed ruby-2.7.3 to /Users/jibees/.rbenv/versions/2.7.3

Ruby is installed.
```

Then I wanted to start the server:
```
➜  openfoodnetwork git:(rbenv-install) ✗ rails s
rbenv: rails: command not found

The `rails' command exists in these Ruby versions:
  2.4.4
  2.5.8
  2.5.9
  2.7.2
```

So, I tested to ruby version:
```
➜  openfoodnetwork git:(rbenv-install) ✗ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20]
```

From what I saw on the internet, I had to run the command: `gem install rails` ; lots of download and installing process (`Parsing documentation for railties-6.1.4 / Installing ri documentation for railties-6.1.4`), but then it works (after a  needed `bundle install`)

**_Conclusion:_**
👉 Not sure if this is the canonical way of doing, but I'm wondering if this `gem install rails` is a mandatory consequence.


I'd say `Ready to go`, but let me know.

**Review by sauloperez — APPROVED** [review]
Both branches seem to be working :+1:

**Comment by sauloperez** [comment]
Weird, I totally missed your comment @jibees I just saw it now.

**Comment by mkllnk** [comment]
@jibees Maybe you just needed run `bundle` after installing the new Ruby version?

**Comment by jibees** [comment]
> @jibees Maybe you just needed run `bundle` after installing the new Ruby version?

Yes, I re-tested, and that's exactly what I should have done. Thanks! 🙏

**Pull request merged**
