### PR TITLE
Uk Business model enhancements

### PR DESCRIPTION
**Pull request by lin-d-hop**
New PR for #814 

The commit history is a little messy, there were a number of conflicts in getting this branch back in line with master.

This includes changes to allow variable length trial periods (including no trial) and setting a minimum billable turnover (shops not charged fees under x turnover)

### CODE REVIEW

**Comment by lin-d-hop** [comment]
@oeoeaio @mkllnk 
It would be really great to get this merged for 1.7. There are two code climate checks that are my fault as my changes took the complexity out of the bounds of acceptable.

I can dig that really I should put the time into refactoring... on the other hand I'm really pushed for time this month and it would be really great to get these enhancement out for our soft release mid May.

Can you confirm if 
a) you are happy for the ugly code to go in and run the risk of refactoring being a low priority for a while? or 
b) these changes can't go in until I clean up my act and hence I need to make sure I reprioritise a few hours on this?

**Comment by mkllnk** [comment]
I got rid of the rubocop complaints, but I had to add a few more lines as well. What you think about https://github.com/mkllnk/openfoodnetwork/commit/d0db3da837799f66d9fa599aeef6ea202adada4f?

**Comment by daniellemoorhead** [comment]
@lin-d-hop we're going to include this in the 1.7 dot point release which includes all the leftovers from 1.7 and will come out in mid May. @oeoeaio will be completing the code review and then @sstead will test it all. Cheers!

**Comment by oeoeaio** [comment]
@lin-d-hop: see PR #934

**Pull request merged**
