### PR TITLE
Fix Rubocop violations in Stripe connect tests

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Stems from https://github.com/openfoodfoundation/openfoodnetwork/issues/4127

It only fixes existing Rubocop violations of the Stripe Connect tests which makes them a bit more readable now that we're reviewing them.

#### What should we test?

Nothing, enough with the automated tests passing.

#### Release notes

Fixed Rubocop style violations from Stripe Connect tests
Category: Changed

### CODE REVIEW

**Comment by luisramos0** [comment]
the specs are broken in semaphore.

**Comment by daniellemoorhead** [comment]
Moving this back to Dev Backlog, the broken spec isn't going to be fixed before @sauloperez gets back so it can be moved back to Code Review when it's ready to go again.

**Comment by luisramos0** [comment]
this should be in code review right Pau?

**Comment by sigmundpetersen** [comment]
yeah there was a flaky build error. rebuild was green

**Comment by sauloperez** [comment]
Yes, sorry

**Pull request merged**
