### PR TITLE
use js-big-decimal to calculate unit_value_with_description in products page

### LINKED ISSUE #9494: [Product import] Some products are duplicated instead of updated
## Description
In the admin dashboard, if you import a file to update products, it can create duplicates for some products. Weirdly it seems to only apply to products which unit type is **ml (or mL)** and **quantity is between 688 and 703**. It's the same behavior whether you first create the product from the dashboard or from an import file.

It impacts hubs using csv imports to update their products database: they don't understand why certain products are created again, and they have to manually delete the duplicates and manually update the original products. 

> The investigation case was about two 700mL cachaça bottles. tchin tchin 🍹

## Expected Behavior
If you import a file to update products, the original products must be updated, not created again.

## Actual Behaviour
If you import a file to update products, it will create duplicates for some products (or variants): the ones between 688 and 704ml. In the Products tab, the exact same product (or variant) appears twice.

It doesn't seem to apply when using other unit types or other unit values.

## Steps to Reproduce
1. Connect to admin > Products tab > [Import tab](https://coopcircuits.fr/admin/product_import)
2. Click on "Browse"
3. Select a file with at least one of the product with  : 
703 ⩾ units ⩾ 688
unit_type = ml (or mL)
Ex. of test file : [test-weirdo.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9222271/test-weirdo.csv)

5. Just after the import, in the "Import validation overview", you see that all your products have been created. Save.
6. Click "Upload another file". Choose the same file. You will see that the products between 688 and 703mL will be created again, the other ones being updated.

### First import
Screen Shot 2022-07-29 at 19 58 27

### Second import

Screen Shot 2022-07-29 at 19 59 27

### Example of the dashboard product list with same products twice

Screen Shot 2022-07-30 at 03 09 27

## Workaround
Each time you import a file to update your products database, you have to manually delete the duplicates and manually update the product if needed.

## Severity
bug-s3: a feature is broken but there is a workaround

## Possible Fix
When creating a 700mL product, the POST /admin/products request sends 
`name="product[unit_value]"
0.700000000000001` 

instead of 0.700

When importing the file to update the product, unit_value is not the same and the product is considered as new.

See difference in number formatting between requests for 687mL and 688mL: 
[whyohwhy.txt](https://github.com/openfoodfoundation/openfoodnetwork/files/9224067/whyohwhy.txt)

This probably has more consequences, as all products created between 688 and 703mL will have a wrong unit_value in database...For example an export of the product database would have to be manually corrected.

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

Closes #9494 (need to confirm with the author)

#### What should we test?

- Described on: https://github.com/openfoodfoundation/openfoodnetwork/issues/9494#issuecomment-1288911515

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Looks good to me! 
Thanks! 💪

**Comment by jibees** [comment]
@abdellani This issue is now ready to test right? 
(I'm asking because I think that its state in the board isn't reflecting its actual state ; it's now marked as in "In Dev", but I think it is actually "Code Review")

**Comment by abdellani** [comment]
Hi @jibees 
Yes, this is ready to test.
Thank you.

**Comment by drummer83** [comment]
Hi @abdellani ans @audez,

I am not sure what I am missing. On staging UK I still see this issue before and after staging this PR. Also I was able to see the the issue through importing the test-weirdo.csv twice as well as creating products manually and then importing test-weirdo4.csv.

How come I still see this?
Any ideas from your side?

**Comment by abdellani** [comment]
Hi @drummer83 

This PR solves part of the problem which I described here: https://github.com/openfoodfoundation/openfoodnetwork/issues/9494#issuecomment-1288881814

There is another problem that I noticed after your comment:  https://github.com/openfoodfoundation/openfoodnetwork/issues/9494#issuecomment-1301827465 

Should I handle that problem in this PR?  or in another PR (I'll have to remove close #9494 from the description )?

**Comment by abdellani** [comment]
I fixed the [second problem](https://github.com/openfoodfoundation/openfoodnetwork/issues/9494#issuecomment-1306893946) which was in the unit converter in the Product importer

**Review by jibees — APPROVED** [review]
💪 🙏

**Comment by drummer83** [comment]
Hi @abdellani,
ouuuffffff, this conversation was tricky to follow and understand what was solved where! 😅 
But in the end you came up with a great PR to fix it all! Thanks a lot! 💪 

To have an overview I listed the issues reported in #9494 again and noted their state before and after your changes:
- some products are duplicated instead of updated when importing (29.07.22)
  - if products were initially created manually; Before: ❌ After: ✔️ 
  - if products were initially created through import; Before: ✔️ (probably fixed by #9497) After: ✔️ 
- long decimals in product list after import (e.g. 693.0000000000001) (21.10.22); Before: ✔️ (probably fixed by #9827) After: ✔️ 
- some products are duplicated instead of updated when importing (21.10.22)
  - if products were initially created manually; Before: ❌ After: ✔️ 
- creating an invalid product with the unit_value = 700, converts the value to 699.9999999999999 at the view level (24.10.22); Before: ❌ After: ✔️ 

This one ready to go! 🚀 
Thanks again!

The only open issue left around weird decimals I could find is #9720 now.

**Comment by drummer83** [comment]
And maybe #9974 is related as well...

**Pull request merged**
