### PR TITLE
Option allow change orders

### PR DESCRIPTION
**Pull request by mkllnk**
This is a follow-up of #1141. Hopefully solving:

- #1083 Display products bought in an order cycle in the shop cart dropdown
- #1084 Display products bought in an order cycle in the edit cart page
- #1085 Allow for bought products to be removed from an order on edit cart page
- #1161 Opt-in option for enterprises to allow their customers to make changes to their current order

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
To be code reviewed by @oeoeaio

**Comment by sstead** [comment]
Looks good mostly. See specific comments on individual issues.
General issue...
- Cancelled orders or items removed from orders are still showing in 'items already ordered' of both the cart dropdown and the edit cart page.
- If a customer removes all items from a past order, the order still exists in admin orders interface...
image

**Comment by mkllnk** [comment]
> Cancelled orders or items removed from orders are still showing in 'items already ordered' of both the cart dropdown and the edit cart page.

True. I haven't done that.

> If a customer removes all items from a past order, the order still exists in admin orders interface...

That could actually be good so that you still have a record that an order was placed. The order could have been paid as well. We need to keep that record for accounting.

**Comment by mkllnk** [comment]
One more idea: We give CI it's own repository to build stuff. That would also mean more resources and our main repository is free from `merged-pull/*` branches.

**Comment by sstead** [comment]
image

**Comment by daniellemoorhead** [comment]
---Doing a PR Cleanup---

@mkllnk @oeoeaio is this still needed for the standing orders work? Is it still in testing or is it ready to go?

**Comment by oeoeaio** [comment]
Superseded by #1536

**Comment by sstead** [comment]
@oeoeaio This order cycle only has one enterprise fee and it's getting applied twice...
image

**Pull request closed without merging**
