### PR TITLE
Mobile: update layout for producers and groups tabs

### LINKED ISSUE #4570: [mobile ux] Style the 'Producer' tab
## Description

**- As a:** enterprise
**- On page:** Producers tab in shopfront
**- I want to be able to do:** have my content look like the new design

## Acceptance Criteria & Tests

**HOW IT LOOKS NOW**
Mobile

Tablet

Desktop
Screen Shot 2019-12-13 at 3 46 44 pm

**HOW IT NEEDS TO LOOK**
Mobile
Screen Shot 2019-12-13 at 3 50 43 pm

Tablet
- Same as current version, 2 rows
Desktop
- Same as current version, 3 rows

**NOTE: PLEASE KEEP THE TRACTORS AS THE BULLET IMAGE. THEY SHOULD BE SVG FORMAT SO SETTING THE COLOUR SHOULD MAKE THEM THE REQUIRED ORANGE.**

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS

### LINKED ISSUE #4579: [mobile ux] Style the 'Groups' tab
## Description

**- As a:** enterprise
**- On page:** Contact tab in shopfront
**- I want to be able to do:** have my content look like the new design

## Acceptance Criteria & Tests

**HOW IT LOOKS NOW**
Mobile

Tablet

Desktop

**HOW IT NEEDS TO LOOK**
Mobile
- use the same layout as on the producers page, no need for the copy saying "...part of:"

Tablet
- Same layout as existing version (single column)
Desktop
- Same layout as existing version (3 columns)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

--> CSS

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Part of #4579
Part of #4570

Adjusts the layout on "producers" and "groups" tabs.

#### What should we test?

Layout looks good on producers and groups in mobile, tablet, and desktop.

#### Release notes

Updated layout of producers and groups tabs for mobile and tablet.

Changelog Category: Changed

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
Hey Danielle, es-staging has been used for other stuff after you deployed this. Please redeploy when you are ready to test 👍

**Comment by daniellemoorhead** [comment]
**Testing notes - Producers tab:** no change that I can see. Links still incorrect colour, as are tractors, and the first line of copy should not be bold.

Screen Shot 2020-01-26 at 5 10 10 pm

**Testing notes - Groups tab:** 
- [ ] Bullet points are not correct - should be full black, not have a white middle.
- [ ] Layout is correct in mobile and tablet form, however it breaks in desktop (see screenshots below)

 Screen Shot 2020-01-26 at 5 11 55 pm

Screen Shot 2020-01-26 at 5 11 43 pm

**Comment by Matt-Yorkley** [comment]
I've updated the groups tab layout. 

This PR is only changing the layout and not any of the link styling etc, which will be done separately.

**Comment by RachL** [comment]
@Matt-Yorkley @daniellemoorhead Currently in production, the hub is also showing up in their producer list, even if they don't produce themselves, which is a bug. It looks from your screenshots that this might be fixed. Can you confirm?

Otherwise I will open a new issue.

**Comment by daniellemoorhead** [comment]
There aren’t any functional changes to the producer tab, only style changes, so this bug won’t be fixed as part of it as far as I am aware.

**Pull request merged**
