### PR TITLE
Notify user about errors raised in reports

### LINKED ISSUE #11304: Disable retries of background reports
* Background reports were introduced in: #10240

If a report fails, it's currently run again and again. That's especially bad if a report crashes after a long time computing. We waste server resources and block other processes.

After a certain time, the user doesn't actually expect a result any more and the report could be out of date. 

We can simply tell Sidekiq to not repeat this type of job. There are two scenarios to distinguish though:

1. *An error is raised in the report processing.* This is easy to handle. The error can be rescued and Sidekiq can be configured to not retry.
2. _The Sidekiq worker is killed while processing._ I'm not sure what happens in this case and I don't know if there's a configuration for this. We need to find out. If Sidekiq is just restarted during a deployment then we would like to resume the calculation. But if Sidekiq is killed by the OOM killer then it's a sign that the report used too much memory and we shouldn't retry. I'm not sure if we can distinguish these two cases.

Another related task:

- [ ] #11305

Further improvements of the background reports:

- [ ] #11306
- [ ] #9692

And useful before we try background reports in production:

- [x] https://github.com/openfoodfoundation/openfoodnetwork/issues/10997

After we the background reports are accepted in production:

- [ ] https://github.com/openfoodfoundation/ofn-install/issues/859

### LINKED ISSUE #11305: Provide error feedback to the user when a background report fails
* Related to #11304

When a background report fails the app doesn't tell the user and it looks like it still running. We should let the user know so that they can try again.

Further improvements of the background reports:

- [ ] #11306
- [ ] #9692

And useful before we try background reports in production:

- [x] #10997

After we the background reports are accepted in production:

- [ ] https://github.com/openfoodfoundation/ofn-install/issues/859

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #11304
- Closes #11305

We rescue standard errors during report generation.

#### What should we test?

- Activate the background reports feature toggle.
- Visit /admin/reports.
- Generate a report.
- It should succeed as usual.
- Replicate: #11530
- An error message should be displayed.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — APPROVED** [review]
Great!

**Comment by dacook** [comment]
FYI @RachL this implements a new error message, for handling unknown errors (essentially the same effect as the 500 error message):

      This report failed. It may be too big to process.
      We will look into it but please let us know if the problem persists.

**Comment by dacook** [comment]
As this is a small change under feature toggle, I'm going to suggest we skip second code review.

**Comment by drummer83** [comment]
Hi @mkllnk,
Thanks for this PR and the test instructions. 

I followed your steps and I can confirm that instead of the error 500 there is now an error message:
image

Other reports seem to work normal.

However there are two bugsnags which occurred with this PR staged:
- https://app.bugsnag.com/open-food-france/coopcircuits/errors/6529a85feedd3c0008fe92b6?filters[error.status]=open&filters[event.since]=30d&filters[app.release_stage]=staging
- https://app.bugsnag.com/open-food-france/coopcircuits/errors/6529a5986af3bf00077ae11c?filters[error.status]=open&filters[event.since]=30d&filters[app.release_stage]=staging

Even though it seems to work I am adding the 'feedback needed' label to see what you think about these errors.

Thanks!

**Comment by mkllnk** [comment]
Thank you, @drummer83. Very thorough testing again. The first Bugsnag report is about the failing report that was tested. It's the same as issue  #11530, unrelated to this PR. The other report came up because this PR has been staged and then unstaged. So it wouldn't be an ongoing problem. All good. I'm merging this.

**Pull request merged**
