### PR TITLE
Activate `split_checkout` feature by default

### LINKED ISSUE #10658: Move all managed instances to "Fully Enabled" split_checkout toggle
## Description
**- As a:** shopper
**- On page:** /checkout
**- I want to be able to do:** Only split checkout if I purchase an order on an instance managed by OFN global

## Acceptance Criteria & Tests

Split_checkout must be fully enabled or targeting 100% of actors on:

- NZ
- ES
- IE
- HU
- BE
- DE
- FR
- UK
- US
- AU
- CA

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10658 

#### What should we test?

- As admin, visit `/admin/feature-toggle/features` deactivate or delete `split_checkout` feature
- Deploy PR
- Check that after deployment, feature split_checkout exists and is activate

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice, very simple.

Long-term, I was wondering if we should expand our current list of features with two more lists. We could have:

1. current features with descriptions
2. active features
3. retired features

Then we always enable the active features and delete the retired features. Devs can then just move those feature names around. But the big downside would be that we enable the feature whenever the server is restarted even if we deactivated it again because there was a problem.

Another idea would be to have a rake task which can be triggered with ofn-install for all instances. That seems much better to me to control the timing or repeat it if necessary. Anyway, migrations are an easy way as well and don't require any additional work for now.

**Review by rioug — COMMENTED** [review]
Shouldn't you be updating this file as well  https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/feature_toggle.rb ?

**Comment by jibees** [comment]
> Shouldn't you be updating this file as well https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/feature_toggle.rb ?

You mean, by changing the description of the feature for example? Or anything else?

**Comment by rioug** [comment]
I meant by moving it to RETIRED_FEATURE, but I realize now that I am jumping the gun, ignore me.

**Review by rioug — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @jibees,
As proposed by you I disabled split checkout in the feature toggles and verified that it is switched off:
image

After staging the PR the flipper is activated automatically again and I see the split checkout:
image

I can still disable the feature manually and use the legacy checkout.

I have also tried deleting the flipper and re-staged the PR. This still showed the legacy checkout:
image

So I switched from UK to AU and immediately deleted the flipper (while split checkout was active). This brought back the legacy checkout:
image

Then I staged the PR and this brought split checkout back and activated automatically.
image

I think this is ready to go but leaving for you to decide and merge.
Thanks!

**Comment by jibees** [comment]
> I have also tried deleting the flipper and re-staged the PR. This still showed the legacy checkout:


Yes, because migration has already been executed: that's why when you switch to AU (instead of UK) the migration can run, and then the split_checkout feature is activated.
So, to me, it's good.

**Pull request merged**
