### PR TITLE
Bring powertip from spree_backend, including js and css

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Continues #4595 

We make extensive use of powertip. This brings the dependency code from spree_backend to ofn.

#### What should we test?
Make sure tooltips are working correctly in the backoffice.

#### Release notes
Changelog Category: Changed
Brought the tooltip dependency from spree_backend to make ofn independent of spree.

### CODE REVIEW

**Comment by luisramos0** [comment]
:+1: fixed

**Comment by mkllnk** [comment]
I think we have some intermittently failing tests here. There is a PR for this already. Should we move this to test ready as soon as Semaphore passes?

**Comment by filipefurtad0** [comment]
Deployment failed:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/katuma-staging/deploys/214

Somehow related to 212 / 209?

**Comment by luisramos0** [comment]
same as 4607

I fixed the file path on the new import statements. it's looking good now 👍
ready for testing

**Comment by lin-d-hop** [comment]
Checked all the tooltips I could find in the backoffice.
All good.
Ready to go

**Pull request merged**
