### PR TITLE
#477: Welcome emails

### PR DESCRIPTION
**Pull request by pmackay**
For #477. 

@RohanM could you please check and say if this is on the right track? There are other places where it would make sense to change the hardcoded emails.

### CODE REVIEW

**Comment by RohanM** [comment]
Hi Paul,

This is a really good start. I'm not sure about using `Spree::MailMethod.current.preferred_mails_from` for this purpose, though. This is the address that order confirmation emails are sent as, and in Australia we have these coming from a different email address (orders@openfoodnetwork.org). This allows us to deal with order support separately to inquiries (which come to hello@openfoodnetwork.org).

To keep this distinction, would you be able to add a separate config variable for the contact email address? I imagine this would take the form of adding an additional preference to `Spree::MailMethod`.

**Comment by lin-d-hop** [comment]
@pmackay just found this PR, quite dated now. Are you able to update/close/assign milestone to give some clarity?

**Comment by oeoeaio** [comment]
@pmackay, given that #477 is now closed, am I ok to also close this PR?

**Comment by pmackay** [comment]
Yes I presume it fell by the wayside...

**Pull request closed without merging**
