### PR TITLE
Overwrites spree_i18n translations for calculator's options

### LINKED ISSUE #2002: Calculator's options can't be translated (unrelevant automatic translations)
## Description
Hub managers don't all understand English, and are confused when they see English strings (here only in back office so doesn't affect customers)

## Expected Behavior
All text is translated in local language

## Actual Behavior
Amonf the calculator options:
- 2 can be translated in transifex ("weight (per kg)" and "flat percent") > ok
- 3 are badly automatically translated by Spree (ex: "flat rate (per order)", "flat rate (per item)", "flexible rate") so we need the strings to be able to translate them properly in transifex
- 1 is not translated ("price sack")

## Steps to Reproduce
1. In menu "entreprise", choose one entreprise and clic on "entreprise fees"
2. One one line clic on the calculator list options
3. This is valid also in other places where calculators are used: shipping methods & payment methods.

## Gif or screenshot
screenshot from 2017-12-20 14-57-23

## Severity
3 (as very confusing for most users) 

## Your Environment
*Version used: 1.10.1
*Browser name and version: Chrome 53.0.2785.116 (64-bit)
*Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by HugsDaniel**
#### What? Why?

Closes #2002 
It overwrites spree_i18n default translations for 4 calculator's options in order to translate them through Transifex.

#### What should we test?

In English, it displays normally the calculator's type.
In French (and other languages), translations for these calculators suit the suggestions made in #2002.

#### How is this related to the Spree upgrade?

This overwriting may be obsolete with future version of spree and spree_i18n, though v3.x doesn't seem to fix the issue.

### CODE REVIEW

**Comment by myriamboure** [comment]
Seems there is an issue also here with Semaphore...

**Comment by sauloperez** [comment]
For now only @oeoeaio can restart the failing CI job.

**Comment by pacodelaluna** [comment]
Deployed on french stage server (https://staging.openfoodfrance.fr/) right now.

**Comment by myriamboure** [comment]
I don't know how to test that... @pacodelaluna deployed the branch on French staging but with French locales so French translations. English strings have been made translatable (was before auto translations from Spree), so this is strange they should appear as "translation missing" no when deploying this with French locales? But not sure as Transifex process is a bit strange...
I don't know how to test that, the calculators are still displayed as before in this test, I see not change, but the process is that until it is merged I can't translate them in Transifex... so why do I still see the old spree automatic translations here? Is it normal?
Or do we need to deploy that with some other method to be able to test?
How can I check that is has not broken anything in the orginal english strings and made it possible to translate?
@mkllnk @sauloperez @HugsDaniel please give me some advise...
Testing notes only with screenprints but same as previous French translations: https://docs.google.com/document/d/10Lfag6q6hcKRdLhLajdP3pxK_IANmCd7c_wyIlZb_Nk/edit#

**Comment by mkllnk** [comment]
Staged on https://staging1.openfood.com.au/. @myriamboure You can test that it doesn't break English. Translations can't be tested yet. :-(

**Comment by sauloperez** [comment]
New translation keys have to be tested using the `en` locale. If that one works chances are that added translations will work too.

**Comment by HugsDaniel** [comment]
Quick tests seem to reveal that the overwriting only works when keys are found in locales. Otherwise, default spree_i18n translation is used.

**Comment by myriamboure** [comment]
Testing notes: https://docs.google.com/document/d/10Lfag6q6hcKRdLhLajdP3pxK_IANmCd7c_wyIlZb_Nk/edit# (3 screenshare showing nothing has changed) > good to go!

**Pull request merged**
