### PR TITLE
Remove duplicate footer links

### PR DESCRIPTION
**Pull request by tomekr**
#### What? Why?

Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/4623

https://github.com/openfoodfoundation/openfoodnetwork/commit/b948312de7776b23f3d4636e5445b21ef0c8e1ea removes the footer links from the view.
https://github.com/openfoodfoundation/openfoodnetwork/commit/43a3ac0a7b1a15de8206fd0366660a36051a65d8 removes the locales that were being used by the view as this appears to be the only place that it was being used. 

Before the change the view looked like:

Screen Shot 2020-01-06 at 1 24 24 PM

After the change the view looks like:

Screen Shot 2020-01-06 at 1 46 44 PM

#### What should we test?

You can load the application and confirm that the footers are no longer available.

#### Release notes

Duplicate footer links removed per https://github.com/openfoodfoundation/openfoodnetwork/issues/4623

Changelog Category: Removed

#### How is this related to the Spree upgrade?

Not related

#### Dependencies

No

#### Documentation updates

None

### CODE REVIEW

**Comment by tomekr** [comment]
@luisramos0 fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/4649/commits/1327d8044613a67d2289fb98a3eab4a6df4131c9

**Comment by tomekr** [comment]
Is the tag rules spec flaky?

**Comment by luisramos0** [comment]
yes, it is the most flaky one, we should probably comment it out.

**Comment by RachL** [comment]
@tomekr thank you and welcome :-) 

this is working as expected in staging. Moving to ready to go!

**Pull request merged**
