### PR TITLE
Fix snail issue for all enterprise fees

### LINKED ISSUE #8250: Snail when editing non-numeric characters on enterprise fees
## Description

In all things similar to #6942 and #8249, but concerning enterprise fees.

Updating an enterprise fee can cause a server error when entering invalid values.

## Expected Behavior

Invalid values should not be allowed or there should be a proper error message.

## Actual Behaviour

It shows the snail.

## Steps to Reproduce

1. Edit an enterprise fee.
2. Select the "per item" calculator.
2. Enter `'20.0'` with the single quotes as fee amount.
3. Click Update.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

* Version used: v4.1.2
* Browser name and version: Firefox 92
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

The only figures that should be allowed are:
- numbers 0123456789
- decimal point .
- negative sign -

The error message should read:
Invalid input. Please use only numbers. For example: 10, 5.5, -20

See [PR which introduces a fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/8204) for a similar issue, regarding transaction fees.

### PR DESCRIPTION
**Pull request by vsmay98**
#### What? Why?

Closes #8250 

#### What should we test?

This is the current status of the calculators:

- flat percent --> OK
- flat rate (per order) --> snail
- flexible rate --> snail
- flat rate (per item) --> snail
- price sack --> snail
- weight (per kg or lb) --> snail

Steps to Reproduce
As an Admin:

- edit an enterprise fee
- choose one of the calculators marked with "snail" above
- click update
- type in an invalid value (e.g. some text or numbers with comma as separator)
- click update --> snail

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by vsmay98** [comment]
Hello @drummer83 
This PR is ready for review.

**Comment by drummer83** [comment]
Thanks @vsmay98!
Your pull request is now in Code Review and we will let you know how it goes.
Thanks for your contribution!

**Review by mkllnk — APPROVED** [review]
That looks good, thank you.

**Comment by mkllnk** [comment]
A spec to reproduce the error first would be ideal.

**Review by jibees — COMMENTED** [review]
I think having a system spec that reproduce this specific case and ensure that the case is solved would be a good idea!

**Comment by mkllnk** [comment]
@vsmay98 Would you be happy to add a spec?

**Comment by vsmay98** [comment]
Sure @mkllnk 
I'm not well aware of system spec but will give it a try.

**Comment by vsmay98** [comment]
Hello @mkllnk @jibees 
I have added the specs, but now some other specs are failing due to this. Could you please take a look?

**Comment by sigmundpetersen** [comment]
@vsmay98 I think this is a "flaky" spec. I'm re-running the build, let's see if it passes.

**Comment by vsmay98** [comment]
Thanks @sigmundpetersen 🤝  The build is green now.

**Review by mkllnk — APPROVED** [review]
Thank you!

**Comment by drummer83** [comment]
Hi @vsmay98,
Thanks for this pull request!

I have first made sure that I can still reproduce the issue on our staging server. 
**Before** your PR the situation was like this:

Peek 2022-10-24 21-16

- flat percent --> OK
- flat rate (per order) --> snail
- flexible rate --> snail
- flat rate (per item) --> snail
- price sack --> snail
- weight (per kg or lb) --> snail

**After** your PR I tested again:

Peek 2022-10-24 21-30

In the screen capture I mostly used the string 'invalid' as input but I have also tested:
- numbers with comma separator :heavy_check_mark: 
- numbers with two '-' signs :heavy_check_mark: 
- numbers with leading spaces, trailing spaces or spaces in between :heavy_check_mark: 
- quotes ' and " :heavy_check_mark: 

For the different calculators we now have:
- flat percent --> OK
- flat rate (per order) --> OK
- flexible rate --> OK
- flat rate (per item) --> OK
- price sack --> OK
- weight (per kg or lb) --> OK

Worth mentioning:
- For 'Flexible rate' the 'max items' field is not validated as other fields, but it is set to '0' for invalid input while for 'Price sack' the amount values are validated as other fields and the error message is displayed for invalid input. Flexible rate should do the same.
- Invalid input field(s) should be highlighted (red border of input field) and all other updated information on the page should be kept (including changes on other existing enterprise fees)
- Flat rate (per order), Flexible rate, Flat rate (per item), Price sack: remove currency setting (the amount is considered the instance's currency anyway) :arrow_right: [wishlist #306](https://github.com/openfoodfoundation/wishlist/issues/306)

This is looking really great and it's removing quite a few snails at one shot. :boom: 

We are ready to go here and I will create a follow-up issue for the topics of 'worth mentioning' (probably later today). :arrow_right: #

Thanks again! :partying_face:

**Pull request merged**
