### PR TITLE
Move to master all en.yml entries added so far to v2 and add more missing v2 translations

### LINKED ISSUE #3140: [Spree upgrade] Move Spree translations into the Spree namespace
This is complementary to https://github.com/openfoodfoundation/openfoodnetwork/issues/3119 and https://github.com/openfoodfoundation/openfoodnetwork/issues/2187.

Spree 2 moved all i18n translation keys from the root namespace into the Spree namespace. For example `I18n.t("back_to_payments_list")` becomes `Spree.t("back_to_payments_list")` which is equivalent to `I18n.t("spree.back_to_payments_list")`.

We will find a lot of these broken translations during testing, but we can't possibly find all. This issue is to collect all translations we come across and don't want to forget. Please edit this description or post below if you are aware of any more translations we need to deal with.

This should be part of phase 2 in the Spree upgrade.

```
back_to_payments_list
```

### LINKED ISSUE #3452: [i18n] missing translations orders, bulk orders and subscriptions
Some translations missing in current BE instance (and thus some others too I guess?)

orders:
dashboard-orders-missing-translations

bulk orders:
dashboard-bulkorders-missing-translations

create new subscription step 3:
dashboard-new-subscription-step3-missing-translations

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Putting all v2 missing translations in master en.yml is harmless to master and will enable us to start translating things in transifex using the normal process. All these translations can then be merged back to 2-0-stable. One commit here is just moving things from 2-0-stable to master, the other one is adding new ones.

In the end, en.yml file in the 2-0-stable branch should be the same as master only with entry removals (there's only one entry deleted so far).

Closes #3140

#### What should we test?
v2 is now translated, we need to find if there are any other missing entries.
I have verified each of these entries locally (very boring task!!!)
It's important we use a language that is not translated in spree base translations so we test #3452 is fixed in v2. I have used fr_BE for tests.

#### Release notes
Changelog Category: Added
Added translation entries that will be used for OFN v2, so that translators can start the translation work.

#### How is this related to the Spree upgrade?
It's part of the spree upgrade.

#### Dependencies
This fixes #3452 but only in v2.

### CODE REVIEW

**Comment by luisramos0** [comment]
sorry to add stuff after your review @sauloperez  I just added one more commit with more things needed for v2 translations, it's just more en.yml entries.

**Comment by mkllnk** [comment]
Should we do a sanity check for the merge to master? Not that we accidentally override another translation... Having a browse through the admin interface and trying to spot weird text would be good.

**Comment by RachL** [comment]
@mkllnk @luisramos0 can you confirm that staging UK is enough? I don't need multilingual to test this, but I need a staging with English as a language option?

**Comment by luisramos0** [comment]
yes, for now this can only be validated in English

**Comment by RachL** [comment]
thank you @luisramos0 I navigated through (I think) all backoffice pages in both producer and super admin. I think we are good :) Moving this to ready to go

**Comment by sauloperez** [comment]
Would you mind fixing the conflict first @luisramos0 ?

**Comment by luisramos0** [comment]
thanks! done.

**Pull request merged**
