### PR TITLE
Remove :available_on attribute from Product

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Removes the `:available_on` attribute from `Product` as discussed in https://github.com/openfoodfoundation/openfoodnetwork/issues/9069

#### What should we test?

Not sure what to test here. The `available_on` column is not present in tables any more, it mostly affects admin products pages.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice cleanup. :heart_eyes:

**Review by rioug — APPROVED** [review]
:+1:  yeah ! less code :smile:

**Comment by rioug** [comment]
CI is green so we could probably merge as is. Leaving it to testers to decide if they want to do any testing.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley  - couple of conflicts came up in the meantime.

**Comment by filipefurtad0** [comment]
I've checked the feature on spree documentation:

`
available_on: The first date the product becomes available for sale online in your shop. If you don't set the available_on attribute, the product will not appear among your store's products for sale.`

I can't recall ever having seen this in the UI... did we ever use it?

**Comment by Matt-Yorkley** [comment]
> I can't recall ever having seen this in the UI

It doesn't really work as a feature, so we're removing it for now. You can set the date but doesn't hide products from the shopfront!

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Ok, I've found it now, it seems we could set this in the products page - never noticed it before, I must admit:

image

After this PR, this option is gone (from the dropdown) and the products page works as before:

image

Good to go :ok_hand:

**Pull request merged**
