### PR TITLE
Improve checkout panels UX

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Removes the "Next" buttons on checkout panels and the jumping around caused by closing the current panel. Going back to good old-fashioned scrolling. It also means the only big primary button on the page is the place order button :ok_hand: 

#### What should we test?

Checkout panel "Next" buttons are removed.

#### Release notes

Removed "Next" buttons in checkout panels.

#### Animated GIF

Checkout

Nothing jumps around or scrolls or moves unexpectedly :tada:

### CODE REVIEW

**Comment by mkllnk** [comment]
@Matt-Yorkley Is this ready for review?

**Comment by Matt-Yorkley** [comment]
Yes, but theres some controversy over whether or not we want to use the PR...

**Comment by sigmundpetersen** [comment]
Product discussion going on in https://github.com/openfoodfoundation/inception-pipe/issues/21

**Comment by RachL** [comment]
@Matt-Yorkley are you ok if we close this PR? Providing that the new checkout split will change this behavior?

**Pull request closed without merging**
