### PR TITLE
2931 Refactor and prepare weight calculator for spree 2

### LINKED ISSUE #2931: [Spree Upgrade] Fix Weight calculator
In Spree 2, what gets sent to the calculator is a Package and the weight calculator needs to calculate based on that type of object.

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2931 

Make weight calculator respond to any object with the order attribute.
Move calculator::weight from models/open_food_network/calculator to models/calculator and remove models/open_food_network :tada:
Clean up rubocop warnings on weight and weight spec and transpec weight spec.

#### What should we test?
We can validate the weight calculator is still working correctly. No functional change.

#### Release notes
Changelog Category: Changed
Refactored Weight calculator code to prepare for Spree 2.

#### How is this related to the Spree upgrade?
This is preparation step for spree 2 and directly fixes #2931

### CODE REVIEW

**Comment by luisramos0** [comment]
This PR together with #2880 and #2888 make the checkout process on the Spree Upgrade branch work!

**Comment by luisramos0** [comment]
LOL the gif

**Comment by myriamboure** [comment]
Testing notes: https://docs.google.com/document/d/1W5rFNBYZb6VJo7Aiwpc3thMMIIQiuyv7nC4hfTGRO7U/edit?usp=sharing
Issue with "g" products, in cart weight calculator is showing result and shouldn't. Also crashes when I try to reach shipping method edit page on enterprise 2.

**Comment by luisramos0** [comment]
I have rebased and added the migration commit: b7ffde795a6c7b8acd5c7df85c6834d156e0ab86

**Comment by luisramos0** [comment]
Bug fixed, reviewed and staged.

I believe I managed to deploy it in Katuma correctly.
I also deployed it in staging FR just in case katuma is not behaving correctly.

Ready for testing.

**Comment by myriamboure** [comment]
Ok @luisramos0 now it is working ! 
I tested entreprise fees on products in kg and g (to make sure g were not impacted), test the VAT on weight calculator was correctly calculated, and tested that shipping method with price on weight was behaving correctly.
https://docs.google.com/document/d/1W5rFNBYZb6VJo7Aiwpc3thMMIIQiuyv7nC4hfTGRO7U/edit?usp=sharing
I don't see other calculator using weight ... so we should be fine now !
Ready to go.

**Pull request merged**
