### PR TITLE
Fix deployments

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes https://github.com/openfoodfoundation/ofn-install/issues/662

- Moves `states.yml` back to it's old filepath where ofn-install expects it to be
- Fixes `default_country_id` problem
- Fixes some conflicts and makes `db:seed` task idempotent

#### What should we test?

- Loading seed data works in dev
- Deploying this branch works with ofn-install

#### Release notes

Improve loading of seed data

### CODE REVIEW

**Comment by luisramos0** [comment]
ah, thanks Matt for fixing this.
My assumption was that the scripts in spree were already being exectuted. but clearly that was not the case...

This looks good to me :+1:

**Comment by Matt-Yorkley** [comment]
I tested deployment and it's all good. I haven't tested running `rake db:seed` in a fresh dev database yet.

**Comment by Matt-Yorkley** [comment]
There was a minor error with `rake db:seed`. It's fixed now, and the `db:seed` task is now idempotent :+1:

**Review by luisramos0 — APPROVED** [review]
nice, thanks again!

**Comment by luisramos0** [comment]
Moving to Dev Test Ready as it is quite important to have this fixed asap.

I can run db:reset on my local env.
I can deploy this with ofn-install master to es-staging :+1: the data looks good in staging es :+1: 
I am merging now.

**Pull request merged**
