### PR TITLE
Update translations with current Transifex version

### PR DESCRIPTION
**Pull request by mkllnk**
Since our Transifex integration has a few flaws, there are many
translations that are not in the code yet. This imports everything, even
translation files that are not at 100%.

See https://github.com/openfoodfoundation/openfoodnetwork/issues/2167.

#### What should we test?

This can only be tested with a language different to `en`. See #2167 of an issue to test.

### CODE REVIEW

**Comment by sauloperez** [comment]
> Since our Transifex integration has a few flaws

Are these known? Or is this just that people updated their languages after the release?

**Comment by myriamboure** [comment]
@sauloperez see #2167 there are problems yes.

**Comment by sauloperez** [comment]
I thought @mkllnk meant something different.

**Comment by mkllnk** [comment]
@sauloperez I know only the flaws mention in the wiki: https://github.com/openfoodfoundation/openfoodnetwork/wiki/i18n

**Comment by sauloperez** [comment]
Pretty good wiki page @mkllnk . That's what we're aiming for :ok_hand:

**Pull request merged**
