### PR TITLE
Fit/remove user registrations controller

### LINKED ISSUE #6531: Removal of app/controllers/spree/user_registrations_controller.rb
### What we should change and why (this is tech debt)

This is a followup of issue #6418

### Context

This came up in the code review of #6454, see https://github.com/openfoodfoundation/openfoodnetwork/issues/6454#issuecomment-742464086

### PR DESCRIPTION
**Pull request by psychoslave**
#### What? Why?

Closes #6531

#### What should we test?

As @arku raised: 
>is it fine to inherit from Devise::RegistrationsController in UserRegistrationsController?

#### Release notes

Remove Spree::UserRegistrationsController

Changelog Category: Technical changes

### CODE REVIEW

**Comment by jibees** [comment]
Thanks for your contribution!
Build is broken and I don't think that this is flaky specs. Moving to "In Dev" then.

**Comment by psychoslave** [comment]
Hey @jibees thanks for the feedback. 

As said in https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1622207417066200 I would appreciate some guidance with what I should do, as is, should the specs be adapted or is there a real issue introduced by these changes?

**Comment by jibees** [comment]
Regarding the specs that failed, that real issue which must be handled and your code must be adapted ;)
See for exemple: 

````
1) UserRegistrationsController via ajax returns 200 when registration succeeds
     Failure/Error: expect(response.status).to eq(200)
     
       expected: 200
            got: 401
     
       (compared using ==)
     # ./spec/controllers/user_registrations_controller_spec.rb:47:in `block (3 levels) in <top (required)>'

**Comment by RachL** [comment]
Hello @psychoslave :) Are you still working on this one?

**Comment by psychoslave** [comment]
Yes, but with other things to deal with lately, I didn't have time to progress on it yet.

**Comment by RachL** [comment]
Closing as no recent activity on this :+1:

**Comment by psychoslave** [comment]
Ok, when I'll have time to contribute to OFN again, I'll start with a new ticket. Hope everything is fine for you.

**Pull request closed without merging**
