### PR TITLE
Adding i18n keys on JS templates

### PR DESCRIPTION
**Pull request by pacodelaluna**

### CODE REVIEW

**Comment by pacodelaluna** [comment]
I couldn't test manually all the JS part as I don't know how to trigger it form the Admin side ... I guess most of it is covered by tests.
Tell me if any issue.

**Comment by myriamboure** [comment]
Ping @daniellemoorhead for next release :-)

**Comment by mkllnk** [comment]
@sstead This PR shouldn't change anything visible. It's mainly modals and notifications. You can have a look at https://github.com/openfoodfoundation/openfoodnetwork/pull/1474/files#diff-37c9b835927e3c363588f172de9bb6fa. On the right in green you can see all the text that was replaced. If you know where to find these text bits, then you can test if they are still displaying correctly.

**Comment by sstead** [comment]
@mkllnk tested and text appears to be displaying correctly.

**Pull request merged**
