### PR TITLE
Add Ruby version to engines for Rubocop

### LINKED ISSUE #11245: [Rubocop] Gemspec/RequiredRubyVersion

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #11245 

> This ensures that RuboCop is using the same Ruby version as the gem.

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Gemspec/RequiredRubyVersion

#### What should we test?

No test.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
Lots of specs are actually failing. Moving into `In Dev`.

**Comment by mkllnk** [comment]
> Lots of specs are actually failing.

Oh, sorry for that. I fixed it now.

**Review by rioug — APPROVED** [review]
Nice quick win :+1:

**Review by dacook — APPROVED** [review]

**Comment by dacook** [comment]
Failing spec is flaky `rspec ./spec/system/consumer/caching/shops_caching_spec.rb:22`

Ready to merge!

**Pull request merged**
