### PR TITLE
[Vouchers] Fix order with voucher redirect to homepage after cart edit

### LINKED ISSUE #10865: [Vouchers] Redirection to HOME after updating the cart including a voucher
## Description

If after applying a voucher you go back to edit your basket and the order total is 0 $ after updating the cart, you then click checkout, enter your details and then click 'next - payment method', then you are redirected to the main page without notification, but the order is placed (email confirmation is sent).

## Expected Behavior

After updating the cart and returning to checkout, the checkout process should be as always. Clicking on 'Next - Payment Details' should take you to step 2 of the checkout.

## Actual Behaviour

After updating the cart and returning to checkout, clicking on 'Next - Payment Details' redirects to the home page. The order is placed without clicking the 'Complete order' button on step 3.

## Steps to Reproduce

1. Put items in your cart and proceed to checkout.
2. Enter your details and click 'Next - Payment method'.
3. Apply a voucher with an amount below the order total.
4. Select a payment method and click 'Next - Order summary'.
5. Click 'Edit' next to the order details.
6. Adjust the items in such way that the order total now is exactly the voucher amount (Total = 0.00 $).
7. Click 'Checkout'.
8. Click 'Next - Payment method'.
9. See that you are redirected to HOME, but you are receiving an email confirmation for the order.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/24ef1331-0351-4f22-80b9-505dbe48d33b

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #10865

After applying a voucher to an order and editing the order so that the total ends up being 0, when one goes through checkout again, the order was automatically confirmed when clicking on 'Next - Payment method'. This happened because the order was now considered a "free order" and payment was skipped. This is in place to allow unpaid subscription order to be completed.
So to avoid this issue, we make sure that payment is required for any order with a voucher applied.

#### What should we test?
- Put items in your cart and proceed to checkout.
- Enter your details and click 'Next - Payment method'.
- Apply a voucher with an amount below the order total.
- Select a payment method and click 'Next - Order summary'.
- Click 'Edit' next to the order details.
- Adjust the items in such way that the order total now is exactly the voucher amount (Total = 0.00 $).
- Click 'Checkout'.
- Click 'Next - Payment method'
    -> The payment step should load and the voucher should still be applied to the order (Note the voucher might be missing due to #10857)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Seems a bit hacky but good to solve for now. I guess that we still have a problem with zero-price products and no vouchers in the cart.

**Comment by Matt-Yorkley** [comment]
Hey @rioug I ended up doing some work on Vouchers while you were away and I've already got quite a substantial branch that addresses this issue around the order having zero total and a few other things as well, like:

- Improving some underlying things in the checkout generally
- Refactoring the checkout form and vouchers form so they're separated into two forms that can be submitted separately
- Extracting all the voucher-creating logic out of the checkout controller and into a `create` action in the  `VoucherAdjustmentsController` (which the voucher form now submits to)
- Implementing changes across the order and order states workflow to ensure the order can still be processed nicely if it's total drops to zero
- Adding some improvements to the way payment method selection works when the order doesn't require payment

I haven't pushed it yet because it's effectively blocked waiting for PR #10913 to resolve issues around removing the split checkout feature toggle and updating the related checkout specs...

**Comment by mkllnk** [comment]
@Matt-Yorkley, that's really cool. It's just a shame that we are doubling up on work here. Let's coordinate a bit better. @rioug has been tasked with the Vouchers work for most part of this year now. Can you maybe outline the tasks that are still ahead (in budget) and then you two can agree on who's doing what?

In the meantime, while we wait for pull requests to be merged and rebased, maybe @rioug could pick up some other little tasks. Fixing some flaky specs is always worthwhile in the long term.

**Comment by rioug** [comment]
Thanks @Matt-Yorkley , I would have been good to know you were working on this. 

> * Handling cases where an existing voucher amount gets recalculated after it's changed

I have been doing something similar while looking at #10857, I'll create a PR with what I have so far and we can look at it once we are unblocked by #10913 and you have pushed your work.

**Comment by Matt-Yorkley** [comment]
> It's just a shame that we are doubling up on work here.

Yeah, sorry. I got assigned to the Vouchers epic while @rioug was away and started looking at addressing the open issues, then I realised there was a lot of overlap with open checkout issues and vouchers issues, and I realised it was all kind of blocked until https://github.com/openfoodfoundation/openfoodnetwork/pull/10913 was resolved, so I had to pivot to helping Mohamed finish that off as the top priority and I ran out of time towards the end of the week.

I've been focussing on the behaviour around applying vouchers during checkout but the issues related to the admin vouchers UI (#10870 and #10871) are available to be worked on and shouldn't overlap.

**Comment by rioug** [comment]
> got assigned to the Vouchers epic while @rioug was away

I missed that sorry, I should have checked with you. I am assuming you'll look at this one as well #10855 ?

> the issues related to the admin vouchers UI (https://github.com/openfoodfoundation/openfoodnetwork/issues/10870 and https://github.com/openfoodfoundation/openfoodnetwork/issues/10871) are available to be worked on and shouldn't overlap.

I'll leave these for now, I am not sure we have the budget for it.

**Comment by rioug** [comment]
Will be superseded by https://github.com/openfoodfoundation/openfoodnetwork/pull/11003

**Comment by sigmundpetersen** [comment]
Should we close here then?

**Comment by rioug** [comment]
Yes we should, closing.

**Pull request closed without merging**
