### PR TITLE
Bring some JS and CSS code from spree_backend related to orders admin

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Continues #4595 

#### What should we test?
- Verify the edit product page has the usual style and positioning of elements.
- Verify you can add, edit and remove images from a product
- Verify the orders search page and the order edit page have the usual style and positioning of elements.
- In the list of payments of an order, make sure the outstanding balance tag is in the correct place with correct style

#### Release notes
Changelog Category: Changed
Bring javascript code related to orders from spree_backend so we can make OFN independent of Spree.

### CODE REVIEW

**Comment by luisramos0** [comment]
I rebased and added a dependency needed (admin/globals/variables.scss which is already added on another PR)  to make the precompilation process work here.
Ready for testing.

**Comment by lin-d-hop** [comment]
This is looking good.
Tested all steps and compared to UK production. Everything is exactly as it should be.
Ready to go!

**Comment by lin-d-hop** [comment]
@luisramos0 except now there is a conflict

**Comment by luisramos0** [comment]
it's a tiny conflict in the all css file, I dont think this can create problems, I will merge now.

**Pull request merged**
