### PR TITLE
Show distance matches for #1453

### PR DESCRIPTION
**Pull request by jeronimo**

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@oeoeaio I think you and Sally were testing this last week - is it right to get merged now that you've approved it?

**Comment by oeoeaio** [comment]
We had a look at this, and it actually breaks existing functionality. I'm not 100% that the existing functionality is something that we want, but if it is not then we need to clean up the code.

When the user searches for something, the logic matches on name and sends a query to the Geocoder API to see if a match can be found there. If a name match is found locally, the UI calculates distance relative to the matching hub (based on its address). If no name matches are found locally, the UI shows results based on proximity to whatever match is returned by the maps API (though the actual identity of this match is not transparently displayed to the user).

This PR breaks the part of the UI where the user can opt-in to seeing shops proximal to the first shop matched on name. As @sstead pointed out, this option is pretty weird. Surely what we really want is the ability to search on shop name and location simultaneously and to allow users to opt-in to show results based on a transparently displayed location (returned by the API), regardless of whether a name match is found.

I have done a bit of work to refactor the logic for this section, and have switched to using the Places API instead of the Geocoder, because it allows restriction of results to `locality`. The geocoder just matches anything and doesn't allow much filtering, so the results can be quite unpredictable. This allows us to display the name of a town that matches the query entered by the user, and to allow them to see results for that town if they which to.

My work needs a lot of tidying up, it's just a spike at the moment, but the functionality is close. Progress is here: https://github.com/oeoeaio/openfoodnetwork/tree/uk/1453_enterprice-search-logic

**Comment by daniellemoorhead** [comment]
Where are we going with this one @oeoeaio / @jeronimo? Next steps?

**Comment by oeoeaio** [comment]
My last comment is the current status as far as I am concerned. I am happy to work on it if I can have some time (probably another hour or two). IMHO the improvement in usability is significant and worthwhile.

**Comment by lin-d-hop** [comment]
I would agree that it is worthwhile making this improvement. I also think it is worthwhile having @oeoeaios head on the task and ideally UK would pay for this out of our general support bucket. Obviously this is lower priority than SO/Stripe etc but maybe we can add it to the list upon his return?
Ping @daniellemoorhead 
Thanks :-)

**Comment by daniellemoorhead** [comment]
@oeoeaio this is all yours to sort out once you've got all the stripe and standing orders sorted (or as a procrastination tool if you need one in between 😁  )

**Comment by lin-d-hop** [comment]
Closing. Captured a link to Robs spike for reference here:

**Pull request closed without merging**
