### PR TITLE
Fix the default logos

### PR DESCRIPTION
**Pull request by bingxie**
Add default logos and home_hero image. A fix for #748 .

### CODE REVIEW

**Comment by bingxie** [comment]
@sstead For testing: 
After a new installation, user can have the default logos on the header and footer(including mobile view) and the home_hero (the big background picture).

Or if the admin can remove the uploaded logos from admin console, user will see the default logo.

**Comment by mkllnk** [comment]
@sstead We have to check four images:

- the logo in the menu
- the logo in the menu on a small screen (window)
- the logo in the footer
- the background hero picture

Have a look at them before we stage the new code. The first two logos are configured on staging2 and are displaying. The other two got lost at some point.

After I pushed the new code to staging2, the first two should be the same as before and the last two should magically appear. :-) You can upload other versions of the images and see that it's still working.

That's all, I think.

**Comment by sstead** [comment]
the logo in the menu - 
image

the logo in the menu on a small screen (window)- 
image

the logo in the footer- 
image

the background hero picture- grey

**Comment by sstead** [comment]
After staging2 was loaded with new fix...
The logo in the menu- image
the logo in the menu on a small screen (window) - 
image
the logo in the footer- defaults to... 
image
the background hero picture- defaults to... 
image

Can I change each image in config? Yes.

**Pull request merged**
