### PR TITLE
Switch help modals from angular templates to use ViewComponent and StimulusJs

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

Partially addresses #8700

> We need to get to a place where we can remove the unsafe_eval directive from our CSP configuration in config/initializers/content_security_policy.rb. In order to do that we need to remove/replace a few things in the codebase (otherwise the app will be broken). The main one is our use of Angular Templates.

_Before:_

help-modals-before

_After:_ 

help-modals-after

I'm not sure the best way to do the CSS for this so I copied #8996 and moved it into the component folder and reused the login modal .reveal-modal classes.

#### What should we test?

The following modals have been updated to use StimulusJS instead of angular templates.

1. Enterprise settings > Business details > Terms & Conditions
2. Enterprise settings > Business details > Legal company name
3. Enterprise settings > Business details > Legal name
4. Enterprise settings > Business details > Legal phone number
5. Enterprise settings > Payment methods > Stripe connect 
6. Enterprise settings > Tag rules
7. Enterprise settings > Users > Add an unregistered user
8. Account > Credit cards > Saved cards (As logged-in customer)

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Wow, thank you!

**Review by jibees — APPROVED** [review]
Thanks a lot!

**Comment by filipefurtad0** [comment]
Hey @cillian ,
Some conflicts arose in the meantime - could you have a quick re-base on this one? Thank you :pray:

**Comment by cillian** [comment]
Hi @filipefurtad0 

I forced pushed to fix that conflict now, it was...

```
<<<<<<< HEAD
.row
  %fieldset.alpha.no-border-bottom
    %legend= t('.Invoice_item_sorting')
  .three.columns.alpha
    %label= t('.sort_items_by_supplier?')
    %div{'ofn-with-tip' => t('.sort_items_by_supplier_tip')}
      %a= t 'admin.whats_this'
  .three.columns
    = f.radio_button :preferred_invoice_order_by_supplier, true, 'ng-model' => 'Enterprise.preferred_invoice_order_by_supplier', 'ng-value' => 'true'
    = f.label :preffered_invoice_order_by_supplier, t('.enabled'), value: :true
  .five.columns.omega
    = f.radio_button :preferred_invoice_order_by_supplier, false, 'ng-model' => 'Enterprise.preferred_invoice_order_by_supplier', 'ng-value' => 'false'
    = f.label :preferred_invoice_order_by_name, t('.disabled'), value: :false
=======
= render HelpModalComponent.new(id: "terms_and_conditions_info_modal") do
  .margin-bottom-30.text-center
    .text-big
      = t('js.admin.modals.terms_and_conditions_info.title')
  .margin-bottom-30
    %p
      = t('js.admin.modals.terms_and_conditions_info.message_1')
  .margin-bottom-30
    %p
      = t('js.admin.modals.terms_and_conditions_info.message_2')
>>>>>>> 78d13912e (Switch help modals from angular templates to use ViewComponent and StimulusJs)
```

There is one new Rubocop error [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9040/files#diff-e738390304d4832c857ba16201ab6264ad5d1a4db358a6f10361a2d9f38655caR4) which says to add a call to `super`. I didn't fix that if that's okay with you because I don't think it is needed in ViewComponent classes, see the example [here](https://viewcomponent.org/#whats-a-viewcomponent)?

**Comment by jibees** [comment]
> There is one new Rubocop error [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9040/files#diff-e738390304d4832c857ba16201ab6264ad5d1a4db358a6f10361a2d9f38655caR4) which says to add a call to `super`. I didn't fix that if that's okay with you because I don't think it is needed in ViewComponent classes, see the example [here](https://viewcomponent.org/#whats-a-viewcomponent)?

Yep, this is not needed I guess. We probably should get rid of this warning. Will address this in a PR.

**Comment by filipefurtad0** [comment]
Hey @cillian ,

For some reason, I was unable to stage this with Semaphore... And while trying to figure out why, other merge conflicts came up.
So I tried to fix these, without force pushing into your branch, and the result was that all those other commits got added to this PR...

...but, the merge conflicts were solved :smile: and we could deploy this manually (ansiable) without recurring to semaphore. This allowed to test the PR - notes on the next message :+1: 

All tests are green, but I'm 100% sure if it is ok to merge in this state, so a quick reply with your agreement or from another dev would be reassuring.

Below, the testing notes. Thanks again for this PR :tada:

**Comment by filipefurtad0** [comment]
Following your detailed "What to test" section - the following modals have been tested:

- Enterprise settings > Business details > Terms & Conditions
- Enterprise settings > Business details > Legal company name
- Enterprise settings > Business details > Legal name
- Enterprise settings > Business details > Legal phone number

Peek 2022-04-19 17-54


- Enterprise settings > Tag rules
image

- Enterprise settings > Users > Add an unregistered user
image

- Account > Credit cards > Saved cards (As logged-in customer)
image

-     Enterprise settings > Payment methods > Stripe connect

Peek 2022-04-19 17-51

**Pull request merged**
