### PR TITLE
Rails52commits

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Brings changes from rails-5-2 branch. I think all these should work in rails 5.0. This way we can keep the rails-5-2 very small :+1:

#### What should we test?
Green build.

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by andrewpbrett** [comment]
Thanks @luisramos0! The failures are expected, right? These are changes that should work once we address the broken specs, that's what you mean?

**Comment by Matt-Yorkley** [comment]
Lots of build failures. It might be worth bringing these bits across in smaller pieces? I think if we drop the commits that change how the helpers are loaded we might get a green build here.

**Comment by luisramos0** [comment]
ok, I removed the helpers and also the around_destroy on product both not working for some reason, we can give these a try on another PR.

**Comment by Matt-Yorkley** [comment]
Ah, I started splitting this into separate PRs, but I guess we could do it in one...

**Comment by luisramos0** [comment]
yeah, I saw your PRs after cleaning up this one :-)
As you wish, I think this is all pr-no-test.

**Comment by luisramos0** [comment]
ok, I have removed from this one what's now in #7147

I think we can merge this as is.

**Comment by mkllnk** [comment]
Builds are still failing. I'm moving this back to in-dev for now.

**Comment by luisramos0** [comment]
ok, I think this is good to go now.

**Review by andrewpbrett — APPROVED** [review]

**Pull request merged**
