### PR TITLE
Silently fail when tax_category has been deleted

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?
* OFN CA have raised [an issue](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1705527604203799) where the new bulk edit products screen crashes on products that have a deleted tax category.
* Discussed in [#product-circle](https://openfoodnetwork.slack.com/archives/C018S101R4J/p1705531338497929)
* https://github.com/openfoodfoundation/openfoodnetwork/issues/12356

I guess all existing product screens handle this gracefully, though to be honest I'm not sure how. Apparently the new bulk edit products screen, and some old reports can't handle it.
Instead of investigating further, I decided it could be fixed in the model. This fixes the bulk edit products screen, and might fix the old reports that were mentioned.

https://openfoodnetwork.slack.com/archives/C018S101R4J/p1705531338497929

- Closes # 

#### What should we test?

With `admin_style_v3` enabled,

- Create a new tax category
- Create a new product with this tax category
- Delete the tax category
- Visit `/admin/products/` and view the product.
  - No errors
  - Tax category column should say "deleted".

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
The next fix would be to add to the TaxCategory:
```rb
  has_many :variants, dependent: :nullify
```

Then we wouldn't need to override the getter.

**Comment by dacook** [comment]
Oops, I missed an existing getter method (which sadly isn't covered by specs). This PR requires changes.

One concern I had is if we want to report on historic data. Clearly we don't currently handle that. And we probably don't need to; I think orders have all the tax information stored in adjustments. So the product doesn't need the old tax category. Instead, it would inherit the default tax category.

So yes, let's nullify on delete, that's probably what we do elsewhere. I'm assuming it will occur on soft-delete.
Hmm, so why do we need to keep a soft-deleted record anyway? Ah, we have a lot of records that `belongs_to :tax_category`.

So, @mkllnk confirming that  I should replace this commit, and go ahead to add `dependent: :nullify`, and a migration to set the data?

**Comment by mkllnk** [comment]
> I'm assuming it will occur on soft-delete.

Oh, I didn't know the tax categories were soft-deleted. In that case, we can use the soft-deleted categories, right? When categories are replaced, it's still good to be able to run reports including the old category for a few years.

Are we dealing with two problems? One could be that soft-deleted records are not found and the other could be that categories have been completely deleted? I don't know.

**Comment by dacook** [comment]
Closing until the solution is decided upon, but will keep the branch for reference.

**Pull request closed without merging**
