### PR TITLE
Solved problem 1416 with icons and maps on ie11.

### PR DESCRIPTION
**Pull request by Duende13**
It's a new branch with just the files needed for the solution, please check for previous comments on the PR #1528

### CODE REVIEW

**Comment by mkllnk** [comment]
Nice. This is a really clear pull request. I'm on Linux and will try VirtualBox images to test this: https://github.com/magnetikonline/linuxmicrosoftievirtualmachines

It's a shame that all the other approaches didn't work out.

**Comment by daniellemoorhead** [comment]
We'll get this tested by @sstead once @mkllnk is back online next week @Duende13 :)

**Comment by sstead** [comment]
@Duende13 
**Testing Notes**
No icons showing in IE unfortunately.
image

**Comment by daniellemoorhead** [comment]
@Duende13 @sineadfenton I'm removing this from the august dot point release as there are bugs stopping it from going through to done. Ping us when you're ready for another review via the aus review label and we'll get back onto it :)

**Comment by myriamboure** [comment]
@lin-d-hop what should we do with that issue? Can @Duende13 finish this ? The bug is kind of preventing the use of the discovery feature to some users, s3 or s2...

**Comment by lin-d-hop** [comment]
Closing. This was picked up as a learner issue for Susana and the fix is not working.

**Pull request closed without merging**
