### PR TITLE
Fix fatal error in reports helper for orders without payments

### LINKED ISSUE #5572: 500 Error on Payment Methods Report
## Description

The Order Cycle Management -> Payments Methods report loads all orders before even loading the filter/search page.

To find Payments Methods it uses a line:
`pm = o.payments.first.payment_method` -> payment.first is nil

If ONE order that is available to the user from ANY of their enterprises fails to find a payment method then the whole page crashes - 500Error:
`undefined method `payment_method' for nil:NilClass`

Bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5ea17c7622a1830018e1f834?filters[event.since][0]=30d&filters[error.status][0]=open

Since the system allows an order without a payment (?) we need this report to run regardless.

## Expected Behavior

The report, ya know, works.

## Actual Behaviour

SLUG

## Steps to Reproduce

I have not been able to track down the enterprise that this order is associated with yet - but ther user noreply@openfoodnetwork.org.uk is associated with it. This user is the one I use for all reports integrations.

1. Logged in as a user associated with an order without a payment 
2. Go to Payment Methods report
3. Slug! (500 error)

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.10.0
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

From @luisramos0 on Slack:
Should be very easy to address (like this o.payments.first&.payment_method)

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #5572

A form helper was trying to write create options for a dropdown of payment methods on orders, but the orders did not necessarily have payments (or payment methods), resulting in a slug.

#### What should we test?

The payment methods report page loads correctly if the hub has orders without payments

#### Release notes

Fixed an issue in payments report for orders without payments.

### CODE REVIEW

**Comment by sauloperez** [comment]
I managed to reproduce it and fix it on my machine. Could you take another look @filipefurtad0 ?

**Comment by Matt-Yorkley** [comment]
@sauloperez it looks like we jumped on this at the same time...

**Comment by sauloperez** [comment]
and my change is now gone :sweat_smile: 

I don't see what you changed. Mine was 

```diff
commit f322bac7668d91658c4a0c3c8c4a1f3be5428a2d
Author: Pau Perez <saulopefa@gmail.com>
Date:   Thu Jun 11 11:17:25 2020 +0200

    Defend from an order w/o payments building table

diff --git a/lib/open_food_network/order_cycle_management_report.rb b/lib/open_food_network/order_cycle_management_report.rb
index 49fb2e736..73a0ea34d 100644
--- a/lib/open_food_network/order_cycle_management_report.rb
+++ b/lib/open_food_network/order_cycle_management_report.rb
@@ -77,7 +77,7 @@ module OpenFoodNetwork
        ba.phone,
        order.shipping_method.andand.name,
        order.payments.first.andand.payment_method.andand.name,
-       order.payments.first.amount,
+       order.payments.first.andand.amount,
        OpenFoodNetwork::UserBalanceCalculator.new(order.email, order.distributor).balance]
     end
 
@@ -92,7 +92,7 @@ module OpenFoodNetwork
        sa.phone,
        order.shipping_method.andand.name,
        order.payments.first.andand.payment_method.andand.name,
-       order.payments.first.amount,
+       order.payments.first.andand.amount,
        OpenFoodNetwork::UserBalanceCalculator.new(order.email, order.distributor).balance,
        has_temperature_controlled_items?(order),
        order.special_instructions]
```

Would you mind applying it?

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley and @sauloperez,

The report still is broken, after staging:
error_500

Moving back to dev.

**Comment by sauloperez** [comment]
@filipefurtad0 this time we encountered another issue that is being discussed in https://github.com/openfoodfoundation/openfoodnetwork/pull/5561. Some orders didn't have billing address and that's something we assumed existed.

**Comment by sauloperez** [comment]
Something else I just spot is that I can do a `order.payments.first.destroy` while `order.state = 'complete'`.

IMO, we shouldn't let this happen in that state. I believe that from an accounting perspective this is a red flag although it removes some flexibility that may come in handy when "fixing" some edge cases as a hub manager.

**Comment by filipefurtad0** [comment]
Hi @sauloperez and @Matt-Yorkley,

This PR is working as expected and preventing the report to break.

This was tested after manually corrupting orders both via psql (removing payments - thanks @sauloperez :+1: ), in FR (R805323111, now deleted) and ES-staging (R620504317, id=1979) - see below note empty shipment_state as well:

```
  id  |   number   | item_total | total |  state   | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |                 email                  | special_instructions | distributor_id | order_cycle_id | currency | last_ip_address | customer_id | created_by_id 
------+------------+------------+-------+----------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+----------------------------------------+----------------------+----------------+----------------+----------+-----------------+-------------+---------------
 1979 | R620504317 |       0.00 |  0.00 | complete |             0.00 |      41 | 2020-06-11 15:55:52.315506 | 2020-06-11 16:07:31.662329 | 2020-06-11 16:07:31.662329 |            1413 |            1414 |         10.00 |                | balance_due   | filipefurtado+funchocustomer@gmail.com | 
```

image


Before the PR the Payment Methods Report was breaking - after staging it isn't. As agreed in Slack, the remaining issues concerning this will be tackled in other PRs.
Ready to go.

**Pull request merged**
