### PR TITLE
Use lazy lookup for translations

### PR DESCRIPTION
**Pull request by dacook**
This helps enforce the conventions to make the translations easier to navigate. As per our guide: https://github.com/openfoodfoundation/openfoodnetwork/wiki//Internationalisation-(i18n)#development

### CODE REVIEW

**Review by abdellani — APPROVED** [review]
Looks good to me.
All the failing specs seem flaky.

**Review by mkllnk — APPROVED** [review]
Nice, this will make the transition easier later.

**Comment by mkllnk** [comment]
Usually, I would have still added testing notes and so on but because this is behind a feature toggle, I'll just merge it.

**Comment by dacook** [comment]
Thanks all. I didn't mean for that to go in the Code review column though, sorry! It was just a small update for our dev branch, but it's great to have your feedback.

**Pull request merged**
