### PR TITLE
moved reroute code from controller to routes.rb and removed format.ht…

### LINKED ISSUE #6943: Manually navigating to an order cycle causes server error
## Error in OpenFoodNetwork

**ActionView::MissingTemplate** in **admin/order_cycles#show**
Missing template admin/order_cycles/show, admin/resource/show, spree/admin/base/show, application/show with {:locale=>[:en_AU, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml]}. Searched in:
  * "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2021-02-02-143326/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.4.0/gems/foundation-rails-5.5.2.1/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.4.0/gems/kaminari-core-1.2.1/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.4.0/gems/devise-4.7.3/app/views"
  * "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2021-02-02-143326/engines/web/app/views"
  * "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2021-02-02-143326/engines/order_management/app/views"

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60246cf6423eaa0017fa9c53?event_id=60246cf60069b127c1c90000&i=gh&m=ci)

## Stacktrace

    app/controllers/admin/order_cycles_controller.rb:26 - show

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60246cf6423eaa0017fa9c53?event_id=60246cf60069b127c1c90000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by ghost**
What? Why?
Closes #6943

When you copy and paste part of a URL to go to an order cycle, you may see a server error. Per the issue, there is no view for show so if a URL is entered as https://openfoodnetwork.org.au/admin/order_cycles/6791 (without /edit), user will likely get an error. Added redirect route to routes.rb file

What should we test?
Navigate to edit an order cycle.
Delete the /edit from the URL so that it looks like this: https://openfoodnetwork.org.au/admin/order_cycles/6791
Enter and you should get either the 'not found' error or get redirected to the order cycle edit page.

### CODE REVIEW

**Comment by rmklaus12** [comment]
@andrewpbrett All good! Do we have a preference for where this reroute line would go? AS of now, I popped it in after the order_cyles resource (at line 21). If that sounds good, I shall push again :-)

**Comment by andrewpbrett** [comment]
@rmklaus12 Yeah that looks like a sensible place to me :)

**Comment by andrewpbrett** [comment]
It also looks like there's some test failures - maybe that `format.html` line is necessary after all.

**Comment by rmklaus12** [comment]
@andrewpbrett That's what I'm discovering :-)

**Comment by rmklaus12** [comment]
As well, I cannot get the redirect to work from the routes/admin.rb file. Thinking it is related to this:
https://guides.rubyonrails.org/routing.html#breaking-up-very-large-route-file-into-multiple-small-ones
However, trying the suggested draw(:admin) in routes.rb gave an undefined error.

**Comment by RachL** [comment]
Hi @rmklaus12 lovely to see you again around here! I'm just checking: do you need any help?

**Pull request closed without merging**
