### PR TITLE
Adding the russian language to github

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Russian has been added to the javascript side but it's not on the server side list of languages.
I believe @romale must be updating the file manually on the Russian instance.
We should follow the same process for all languages, in this case, that means having this file in GH and let transifex update it like the other languages.

There are relatively few translations in transifex:
image

I am now wondering if @romale is translating directly on the file! If this is the case @romale can you please upload the file to transifex? If you dont know how to do this please send us the ru.yml file you are using and we can do that for you.

#### What should we test?
A green build is enough here. The next deploy to the russian server no one will need to update translations.

#### Release notes
Changelog Category: Added
Added russian language.

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]

**Review by sauloperez — APPROVED** [review]

**Comment by romale** [comment]
Hello Luis. Uploaded the current snapshot of the Russian translation to transifex

**Comment by luisramos0** [comment]
nice, thanks @romale 
Looking good :ok_hand: 
image

We don't recommend you change the language file directly on the server because we cannot support a process without version control.
We recommend you use transifex to make your changes so that the language file is versioned in github.

**Comment by romale** [comment]
Understand. Now I will translate through transifex, since the main translation work (in a form convenient for me) has been done

**Comment by luisramos0** [comment]
Great! And thanks a lot for your contribution!

**Pull request merged**
