### PR TITLE
Corrects setup for setup in credit card cloner spec

### PR DESCRIPTION
**Pull request by filipefurtad0**
We should not need additional hard coded keys other than the API key and the CLIENT_ID;

#### What? Why?

A PR has been merged with additional hard coded `STRIPE_CUSTOMER` and `STRIPE_ACCOUNT`, which seem incorrect to me:
- customers should be created per demand; if customer are deleted at some point, then re-recording the spec will fail, as the `customer_id` will be invalid
- we don't need to state `stripe_account` in this test; connected accounts should be as well created by demand.

#### What should we test?

- green build

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — CHANGES_REQUESTED** [review]
Great, but you are missing the api key now. I needed this to get it working:
```
  before {
    Stripe.api_key = ENV.fetch('STRIPE_SECRET_TEST_API_KEY', nil)
  }
```

**Comment by filipefurtad0** [comment]
> Great, but you are missing the api key now. I needed this to get it working:

Yes, absolutely. I've mixed it up with another PR (#12104, which is not yet merged and might make stating `Stripe.api_key` on each spec obsolete; we're not there just yet).

**Review by mkllnk — APPROVED** [review]
Great. That works for me now.

**Review by dacook — APPROVED** [review]
Great, so the test is more self-contained now 👍

**Pull request merged**
