### PR TITLE
Bring js code to make taxonomies admin work without spree_backend

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Continues to #4595

We need to bring jstree from spree_backend so that the taxonomies admin page works in the backoffice. We remove one usage of jConfirm to avoid having to bring jquery.alert as well.

We create a folder admin/spree where we will put the not angularized JS legacy code coming from spree_backend. It's not much code but I think it's better if we keep it isolated under admin/spree/.

#### What should we test?
The taxons admin page in the backoffice is working correctly, particularly setting up hierarchies and renaming and deleting elements.

#### Release notes
Changelog Category: Changed
Brought from spree_backend code to make taxons admin page work without spree code so that we make ofn independent of spree.

### CODE REVIEW

**Comment by luisramos0** [comment]
I rebased and tested deploying. All good. Ready for testing.

**Comment by lin-d-hop** [comment]
ping @luisramos0 #conflicts

**Comment by luisramos0** [comment]
rebased :+1:

**Comment by lin-d-hop** [comment]
Tested creating a taxon and associating with a product. 
Taxons can be deleted when not associated with a product and cannot be deleted afterwards.
Taxons in different hierarchies are squashed into a flat list.
Renaming works.
All changes flow correctly into shopfront and descriptions.
All behaviour is as the current taxonomy system on production.

Ready to go :-)

**Pull request merged**
