### PR TITLE
Handle soft deleted variants in order edit

### LINKED ISSUE #3903: When deleting a product, all orders dealing with that product show an error 500
## Description
When I delete a product, I cannot see orders that were dealing with this product anymore. Even if those orders contained other products as well 

## Steps to Reproduce

1. Check an order that has a particular product
2. Delete the product
3. If you try to edit the order again you will have an error 500

Bugsnag details on Katuma staging (the order contain only this product):

https://app.bugsnag.com/katuma/katuma/errors/5cf942f2d45903001a72f17f?event_id=5cf942f20041e9c719f30000&i=sk&m=nw

On Katuma production (the order contained other products):

https://app.bugsnag.com/katuma/katuma/errors/5cf8e37a020d19001a50ffda?event_id=5cf8e37a0041e1a0a46c0000&i=sk&m=nw

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.0.2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #3903 

This allows us to test https://github.com/openfoodfoundation/spree/pull/41. If it passes testing I will then revert it back to the `2-0-4-stable` branch but updating the target commit in the Gemfile.lock.

#### What should we test?

1. Delete a product that it's been purchased in an existing order
2. Go edit said order from /admin

You should see the page, including the deleted product, without any problem.

#### Release notes

Orders listing products that got deleted after the purchase can still be edited from the admin section

Changelog Category: Fixed

### CODE REVIEW

**Comment by sauloperez** [comment]
Moving to test ready as the underlying https://github.com/openfoodfoundation/spree/pull/41 got 2 approvals and this is only meant for testing now.

**Comment by Matt-Yorkley** [comment]
@sauloperez This has failed with a fatal error multiple times when being staged...

Relevant error lines:
```
bundle exec rake assets:precompile:primary RAILS_GROUPS=assets RAILS_ENV=staging"]
...
"rake aborted!", "Sass::SyntaxError: Invalid CSS after \"﻿\": expected selector, was \"@-webkit-keyfra...\"
in /home/openfoodnetwork/apps/openfoodnetwork/current/app/assets/stylesheets/application.css.scss"

```

**Comment by Matt-Yorkley** [comment]
This PR is not testable as it seems to break asset recompile and can't be staged. Moving back to `in dev` as Pau is away.

**Comment by RachL** [comment]
Deployment failed. As discussed with Pau on Slack, moving back to in dev

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/katuma-staging/deploys/90

**Comment by luisramos0** [comment]
I removed the accidental sass upgrade.

all good now in staging katuma, back to test ready ;-)

**Comment by sauloperez** [comment]
Thanks @luisramos0 ! I removed sass from the change.

**Comment by RachL** [comment]
Staging worked and now when I delete a product I still can access the previous orders, both as super admin and manager.

Two examples:

https://staging.katuma.org/admin/orders/R742456565/edit

https://staging.katuma.org/admin/orders/R622102456/edit

Ready to go!

**Comment by luisramos0** [comment]
I was too quick to merge, this was not supposed to be merged... I reverted it in #4061  sorry!

**Comment by sauloperez** [comment]
I'm a bit lost @luisramos0 . Since #4061 also got merged we restored `master`'s status but we haven't opened a PR that enables testing https://github.com/openfoodfoundation/spree/pull/41, did you?

**Comment by sauloperez** [comment]
Yes, sorry this PR and its Spree counterpart are a bit confusing. I knew this would happen

**Comment by luisramos0** [comment]
I just merged this PR and reverted it immediately. Nothing else.

**Pull request merged**
