### PR TITLE
Bump stimulus_reflex to 3.5.1 and cable_ready to 5.0.5

### PR DESCRIPTION
**Pull request by dacook**
* Bumps [stimulus_reflex](https://github.com/stimulusreflex/stimulus_reflex/releases/) **ruby gem and JS package** from 3.5.0-rc3 to 3.5.1
* Bumps [cable_ready](https://github.com/stimulusreflex/cable_ready/releases/)  **ruby gem and JS package**  from 5.0.1 to 5.0.5
* Bumps [stimulus_reflex_testing](https://github.com/podia/stimulus_reflex_testing) to `main` (because latest fixes haven't been released yet).

As of 20 May 2024, there's only one unsolved [new issue](https://github.com/stimulusreflex/stimulus_reflex/issues), but it doesn't seem to affect this codebase.

I'd recommend just viewing the overall diff, which shows just the upgrades as described above.

### What should we test?
These are underlying frameworks used for the dynamic functionality on the below pages. Simply checking that they work as usual, with no errors in the dev console should be sufficient.
* BUU Bulk Edit Products - Delete (`/admin/products` with `admin_style_v3`)
* A report, eg `/admin/reports/packing/customer` (old or new design, doesn't matter)
* Admin Enterprise > Connected app
* Admin Orders > Any bulk action

### Dependencies
- Depends on, or supersedes https://github.com/openfoodfoundation/openfoodnetwork/pull/12260

### CODE REVIEW

**Comment by dacook** [comment]
Doesn't matter how many times I stop spring, clear cache or restart the dev server, it refuses to acknowledge the cable_ready version.

Screenshot 2024-05-14 at 3 30 52 pm

See `yarn.lock`
```
cable_ready@5.0.4, cable_ready@^5.0.4:
  version "5.0.4"
  resolved "https://registry.yarnpkg.com/cable_ready/-/cable_ready-5.0.4.tgz#88b5bff27871be402f6ea049d65126bb1995d147"
  integrity sha512-HZLj3SjgEDB4H2GqtKHmg2lOu8YCti0hsPR9XC2mMfz6WOkHK4FWt1/NJ0OIKAcQAEnxEJEtlIgBv6tP1m958g==
```

**Comment by sigmundpetersen** [comment]
Yes, looks like v5.0.5 will fix this https://github.com/stimulusreflex/cable_ready/compare/v5.0.4...v5.0.5 👍

**Comment by dacook** [comment]
🙄 Groan, why couldn't they have released it a day earlier and saved my time!!!!

**Review by mkllnk — APPROVED** [review]
Sometimes it really doesn't seem worth it to work with bleeding-edge tools. These updates have been painful.

**Comment by dacook** [comment]
I agree. I actually delayed updating these gems, but decided we should keep them relatively up to date while we still use them. 
Hopefully we can avoid touching them for a while now..

**Comment by dacook** [comment]
Moving to test ready as its quite similar to the previously approved PR.

**Comment by filipefurtad0** [comment]
Hey @dacook ,

Tested what you've suggested - thanks so much for that:

- BUU Bulk Edit Products - Delete (/admin/products with admin_style_v3) -> deleted several products, all good. No console errors.
 - A report, eg /admin/reports/packing/customer (old or new design, doesn't matter) -> all good, report generated for the indicated dates
 - Admin Enterprise > Connected app -> app connects to Discovery Regenerative as expected
 - Admin Orders > Any bulk action -> bulk printed invoices for two complete, paid orders. All as before.

Merging.

**Pull request merged**
