### PR TITLE
Update js library (textAngular)

### LINKED ISSUE #1860: [mobile ux] Copy-paste in shopfront message display strange white strips
## In a feature branch or master?
This can be merged straight to master 🎉 

## Description
When copy-pasting from another shopfront or any text file, into the "message when shopfront open/close" (in menu enterprise setting > shop preferences), here is what happens. Some shops have done that apparently and then their shopfront is not looking good.

bug

### PR DESCRIPTION
**Pull request by mjal**
#### What? Why?

Closes #1860 
The issue is fixed just by updating the dependencies

#### What should we test?

We can copy paste welcome messages from /admin/enterprises/*/edit#/about without formatting issues

Because this can be sensible security-wise, everyone can verify that the file are indeed the latests from github.com/textAngular/textAngular

```
# This should be the same
curl https://raw.githubusercontent.com/textAngular/textAngular/master/dist/textAngular.min.js | sha256sum
curl https://raw.githubusercontent.com/mjal/openfoodnetwork/e0c8b20afa9ac3ea27f2dfaa65e405e3cf89d2d7/vendor/assets/javascripts/textAngular.min.js | sha256sum
# Same for textAngular-sanitize.min.js
curl https://raw.githubusercontent.com/textAngular/textAngular/master/dist/textAngular-sanitize.min.js | sha256sum
curl https://raw.githubusercontent.com/mjal/openfoodnetwork/e0c8b20afa9ac3ea27f2dfaa65e405e3cf89d2d7/vendor/assets/javascripts/textAngular-sanitize.min.js | sha256sum
```

### CODE REVIEW

**Comment by myriamboure** [comment]
Thanks @mjal for your first contribution and welcome to the OFN ! I am sure some dev will review soon your contributions, feel free to ask any question you have on Slack (I know you are there already ;-)).  Cheers!

**Comment by daniellemoorhead** [comment]
Moved back to 'In Dev', @mjal have a chat with @sauloperez if you need help finding an asset pipeline gem. If you don't have time to dedicate at the moment to doing this (which we would completely understand!) then let us know and we can add it to the backlog.

Cheers 😄

**Comment by mjal** [comment]
@sauloperez [I just found a gem](https://rubygems.org/gems/text-angular-rails) but unfortunately I don't think that it's still maintained.
It doesn't surprise me that there is no up-to-date gem available because it's javascript stuff

**Comment by sauloperez** [comment]
Thanks for taking the time to search @mjal! I have trouble deciding. If you add it to vendor it'll never be upgraded and if we do, we'll have to play the role of bundler ourselves; and we know we're bad at that.

On the other hand, we know that gem is not maintained and if we want to upgrade we depend on them. Could it simply be that the js lib hasn't been upgraded either?

And, what about `package.json`? Does it exist as npm package we could depend on? I haven't done this in a Rails project before though.

Thoughts? Cc @enricostano @mkllnk

**Comment by mkllnk** [comment]
Just looking at this pull request, it's just updating an asset we already have in the repository. So it's not making anything worse. And it sounds like the only way to improve the situation would be to contribute to maintaining a package.

**Comment by sauloperez** [comment]
> And it sounds like the only way to improve the situation would be to contribute to maintaining a package.

that's exactly what I think, then it depends on how responsive they would be if we open a PR on their repo.

> Just looking at this pull request, it's just updating an asset we already have in the repository. So it's not making anything worse.

Since it's not an easy decision, let's just move on. As @mkllnk says, it's not making things worse.

**Comment by mjal** [comment]
I sent a PR to update the gem and it was merged in the next 5 minutes :).
Unfortunately I kinda misnamed the assets (I realized it when I tried to use it) so I just sent another PR 🤕.
I'll update this PR when it's ready so we can use the gem.

**Comment by sauloperez** [comment]
Cool @mjal ! that's even better!

**Comment by sstead** [comment]
**Testing notes**

- There is a bug with this PR preventing shopfront messages from being saved and displayed. Therefore I can't test this specific issue until the bug is fixed.

https://docs.google.com/document/d/1maMDmulAGfM1cpC10TJd_yHos4r6SxmFtQEcS0595ao/edit#

**Comment by mkllnk** [comment]
True, I can't see any saved text in in WYSIWYG editor fields. Back to you @mjal.

**Comment by myriamboure** [comment]
@mjal any progress on that? Would be great to move it forward :)

**Comment by myriamboure** [comment]
Closing that PR for now, @mjal please feel free to open again if you have time in the coming days/weeks :-)

**Pull request closed without merging**
