### PR TITLE
Dont show 'closing in' message when oc closes in more than 3 months

### LINKED ISSUE #5305: Change Ready for message for Long term (continuously open) Order Cycles
## Description

As a shopper I visit the home page of a hub/shop which has an order cycle which is open all the time.
In the blue order cycle notice box in the top right corner the text 'Next Order Cycle Closing in ....' is displayed.  This is confusing.  I might think I won't be able to collect my food for another year/month.
withtext

Proposed improvement
If order cycle end date is more than 3 months ahead of current date then the text 'Next Order Cycle closing in...' is not displayed.
withouttext

## Acceptance Criteria & Tests

1. Set up an order cycle with end date more than 3 months in advance.
2. View shop page as a customer
3. The text 'New Order Cycle Closing in...' is not present  (see above mock up screen shots)
4.

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5305

#### What should we test?
We need to verify the message disappears if OC closes in more than 75 days from now and shows "closing in 2 months" up to that date.

#### Release notes
Changelog Category: User facing changes
Order Cycle "closing in" message is not shown now if the Order Cycle closses in more than 3 months.

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Comment by andrewpbrett** [comment]
I was going to review this, but it looks like we're going to make some changes based on the comments in the issue. I moved it back to In Dev until then 👍

**Comment by RachL** [comment]
hello @luisramos0 are you planning to make the changes or should this be assign to someone else?

**Comment by luisramos0** [comment]
I am sorry. I cant take it now. Better looked at by someone else.

**Comment by Matt-Yorkley** [comment]
Updated :+1:

**Review by andrewpbrett — APPROVED** [review]
🎉

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley and Luis,

The change introduced by this PR is effective.

**More** than 75 days till closing of the OC - now displays "Orders are currently open":
image

**Less** than 75 days till closing of the OC - behavior as before:

- displays "2 months..."
image

- "1 month"
image

- counts days for less than 1 month till OC closure
image

The key introduced by this PR seems to work well - the page renders correctly:
image

Good to go :tada:

**Pull request merged**
