### PR TITLE
Add style guide to the source locale

### PR DESCRIPTION
**Pull request by mkllnk**
There has been a lack of rules how to structure our locale en.yml. This
is a start to document some guidelines which can evolve over time.

Rules can be discussed in the community forum or in pull requests. Once
there is a strong agreement, we should add it to this guide.

@jeronimo @enricostano @oeoeaio What do you think about the rules? What do you think about documenting them this way?

### CODE REVIEW

**Comment by enricostano** [comment]
Good initiative @mkllnk 👏 

I agree on each point you are proposing. I'm not sure about location of the documentation, maybe a wiki page on GitHub and a link to it and the discussion thread?

We can even give it a try in `en.yml` and then decide if people read it and what to do.

**Comment by mkllnk** [comment]
Yes, I thought about other locations. But I wasn't sure where it should go. It needs one place that holds the document with the agreed wisdom and we need places to discuss about new proposals. That could be en.yml and pull requests. Or on Discourse. Or wiki plus Discourse. ???

**Comment by pacodelaluna** [comment]
Well, I was thinking of keeping the documentation into the Wiki, and we could add links to it inside the code. I think it is good to have a central place to deal with the project documentation, it can help newcomers to have a quick overview on how people are working on the project.
We could use Discourse to share opinions on a subject, and then Wiki to formalize them in order to keep the documentation updated.

**Comment by pacodelaluna** [comment]
Actually, imho, this discussion should happen on Discourse :)

**Comment by kirstenalarsen** [comment]
i agree, discussion on discourse, agreed position ‘latest knowledge’ on the wiki . .?

**Pull request merged**
