### PR TITLE
Remove SR from clear search button [OFN-12551]

### LINKED ISSUE #12551: [BUU] Remove SR from clear search button
On the new Bulk Edit Products screen (`/admin/products` with [feature toggle](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggles) `admin_style_v3`):
We want to remove the StimulusReflex action from the "Clear Search" button that appears when there are no search results.

- See https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/products_v3/_no_products.html.haml#L3
- Also remove now-unused [ProductsReflex](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/reflexes/products_reflex.rb) 

This is the last task which allows us to 
- Close https://github.com/openfoodfoundation/openfoodnetwork/issues/12331

Screenshot 2024-06-05 at 9 27 29 am

### PR DESCRIPTION
**Pull request by wandji20**
#### What? Why?

- Closes #12551

Remove Stimulus Reflex from the clear search button and delete unused products reflex class

#### What should we test?
Check that products clear search button is handled by turbo

- Visit ... page.
http://localhost:3000/admin/products

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] Technical changes only

Remove SR from clear search button

#### Dependencies
<!-- Does this PR depend on another one?
N/A

#### Documentation updates
<!-- Are there any wiki pages that need updating after merging this PR?
N/A

### CODE REVIEW

**Review by chahmedejaz — CHANGES_REQUESTED** [review]
That's great 🎉 Good to see Reflex being removed from the Products page finally! Thanks 🙌

Right now we don't have a spec to validate the **Clear Search** button click functionality, are you willing to add one please? Thanks.

**Review by chahmedejaz — APPROVED** [review]
Perfect. Thanks 🙌

**Comment by chahmedejaz** [comment]
Hi @wandji20 - Sorry I missed it before in review, we needed to replace Reflex actions with Turbo as well. I've pushed that respective change.
ref: https://github.com/openfoodfoundation/openfoodnetwork/issues/12551#issuecomment-2148576250

**Comment by wandji20** [comment]
Thanks @chahmedejaz

**Review by rioug — COMMENTED** [review]
Nice one :+1:  thanks :pray:

**Review by rioug — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @wandji20,
Thank you for yet another PR.

I have verified that the user experience is the same before and after your PR. Here are the screenshots.

Before:
image

After:
image

I have noticed an error in the browser console. However this is shown at page load already and it's indepent from the 'Clear search' button. It's shown in current master as well.
image

## Conclusion
No issues found, all good. :+1: 
Thanks again! Merging! :partying_face:

**Pull request merged**
