### PR TITLE
White Label: Make it possible to activate white label feature for one actor

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Previously, via PR #10567, the `white_label` feature could be configured only globally, not via actor. This PR basically change:
 - we (ie. super admin) could enable `white_label` for a specific actor, ie. a shop manager
 - we do not check for `white_label` feature enabled or not when displaying a shop banner. This means that, if a shop has been configured to not show OFN navigation, and, after, the `white_label` is removed from the shop owner, the feature (ie. not showing the OFN navigation on shop) will be still activated

That's why I think it can be a good idea to activate the feature to the super admin user once you want to give access to at least one shop manager. 

This also leads to a question : feature toggle is not meant for being used as a definitive thing, but only during development, to merge/ship PR without being blocked. That is to say, I don't encourage feature toggling to be used as a "can give a feature to a specific user". 

#### What should we test?
- As an admin, on `/admin/feature-toggle/features` activate `white_label` feature for a specific shop distributor, via `Spree::User;USER_ID`:
Capture d’écran 2023-04-14 à 09 56 09

- Check that, connected with that user you do have access to the white label panel under enterprise settings edit page.
- Once configured and activated, check that it works as expected (ie. not showing OFN navigation) for a not-connected + connected + shop owner + super admin user

#### Release notes

Changelog Category: Under feature toggle

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good :+1: 

I am little bit confused, Is this to allow a specific shop owner to use white label ? or is to give a Super Admin the ability to allow a shop owner to use white label ?

**Comment by dacook** [comment]
What I understand is that before, an instance manager will enable this feature toggle for all users. Now, they can enable it for individual users.
When the user has the option, they will see the new enterprise admin tab "white label", and can turn the white label preference on or off for any enterprises they add. 
So turning off the feature toggle won't change the white label preferences, it will just change who can access it.

JB has identified that feature toggling has been used as more permanent permission control. Feature toggles should only be temporary, so we should use some other kind of permission control for this.
Currently we have the ability for enterprise owners to grant permissions to other users. But we don't want to give all enterprises the white-label ability; I think we only want instance managers to allow white-label for certain enterprises. 

What if we hard-coded the enterprise admin "white label" tab to simply show only for super-admin users? Then a super-admin can enable-disable it anytime.

**Comment by jibees** [comment]
> @jibees, what if we hard-coded the enterprise admin "white label" tab to simply show only for super-admin users?
Then a super-admin can enable-disable it anytime.

Yes, it can be a good idea. The drawback is that shop managers could not manage their own white label preference (with the coming PRs, we will implement the possibility to upload an image to be used instead of the OFN default one for shop). 

So, I think it's still an open question. 

@kirstenalarsen What do you think?

**Comment by jibees** [comment]
As [discussed in delivery circle this morning](https://community.openfoodnetwork.org/t/delivery-circle-18-april/2815), let's close this PR as we want to activate this feature to everyone. 
Next, after some testing, we will open an issue to delete the white_label feature and then activate panel and configuration for each users on each instances.

**Pull request closed without merging**
