### PR TITLE
Solved #1416 

### PR DESCRIPTION
**Pull request by Duende13**
ie11 and svg images as markers generate javascript errors and icons don't show. png images have not such problems and for the size and the utility given, this solution solves the problem and it's not generating further problems in other browsers. 
Please, @lin-d-hop could you or someone have a look? Thank you!

### CODE REVIEW

**Comment by lin-d-hop** [comment]
@jeronimo would you take a look at reviewing this please?

**Comment by Duende13** [comment]
Hi Julius (@jeronimo)!
Thank you for the tip about the meta tag, this one I hadn't try it before. I just did it and nothing happened, just a little bit worst, still markers are not showing, javascript errors are coming back and the cherry on top of the cake, the map freezes when one tries to zoom in, below a screenshot. 
iexplorer

I already tried before the width, height changes, and the scaledSize and optimized solution with not luck, which was my best shot as almost everybody agreed on this. 
I know that png are not the best in comparison with the benefits of svg, but being icons, which are not going to be resized or edited, the file size is smaller, they show in all browsers and OS, and javascript errors vanished from IE11, I just saw on png images the best solution that I could find and not new issues raised.

**Comment by Duende13** [comment]
Sure, Julius. 
I'll keep an eye in case something new come, I've read that with Edge loads of problems are not happening for this reason they stop working in problems from ie11 so I don't think we'll see that coming soon, but I'll keep an eye for any updates. :)

**Comment by Duende13** [comment]
I forgot to mention that I tried another solution without success either. It was to put the path of the svg, which in our case is not a solution, due our svgs are composed of several paths
(path as a list of coordinates and other attributes needed to draw the image), our svgs are several
images one on top of each other, each of them with a path, I tried to combine, group and merge them to obtain a single path but the final image had nothing to be with our current icons.

**Comment by daniellemoorhead** [comment]
@mkllnk if you're happy with this fix then it's good to go to @sstead for testing. Cheers!

**Comment by enricostano** [comment]
I tried to open one of our SVG with https://jakearchibald.github.io/svgomg/ and I get an error related to the format. Could be that the SVG files have some issues?

Here you can find more info about SVG format and compatibility https://css-tricks.com/using-svg/

**Comment by daniellemoorhead** [comment]
@lin-d-hop @Duende13 given @enricostano's error noted above does this need to be resolved before it goes through to @sstead?

**Comment by Duende13** [comment]
@enricostano , what you are saying is that the svg images have problems of compatibility and that's the reason that are not showing on the maps? because my approach was to get these icons with as png images, and I don't thing these give any issue. If you think that the problem with svg on the maps is because of the compatibility I'll have a look but I'm not a designer at all (limited skills there). Just confirm this, please.  Thank you!!!

**Comment by enricostano** [comment]
Yep, I would give a look at the SVG format. It seems a bit broken to me.

**Comment by Duende13** [comment]
Nothing, @enricostano  I changed the svgs, I'm able to open them without errors with the online tool you sent, but I've just tested and the same, all browsers ok except ie11, which doesn't show anything at all.

**Pull request closed without merging**
