### PR TITLE
Update Rubocop config and replace deprecated TimeWithZone#to_s with argument

### LINKED ISSUE #10625: [Deprecation] TimeWithZone#to_s(:short) is deprecated
### What we should change and why (this is tech debt)

`DEPRECATION WARNING: TimeWithZone#to_s(:short) is deprecated. Please use TimeWithZone#to_fs(:short) instead. (called from block in report_order_cycle_options at <home>/openfoodnetwork/app/helpers/reports_helper.rb:6)`

### Context

I believe this was introduced after upgrading to Rails 7; noticed while working on #10507

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #10625 
- Fixes other style offenses.

It would have been very easy to fix the issue manually but I took the longer route to unlock many more auto-correction cops. Let's use them.

#### What should we test?

- Specs only.

I used some unsafe auto-correction cops but the affected files are very low risk and should be covered by specs.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Nice cleaning, thanks a lot! 🧼 

I guess we should address those todos along the way?

**Comment by mkllnk** [comment]
> I guess we should address those todos along the way?

What do you mean? Within this PR or just soon while we are working on similar code?

I think that it's too big for this PR but I could create issues for all new rules. Hm, maybe it would be useful to create issues for each violation in the todo file. That may motivate the community to pick them up. What do you think?

**Comment by rioug** [comment]
> I think that it's too big for this PR but I could create issues for all new rules. Hm, maybe it would be useful to create issues for each violation in the todo file. That may motivate the community to pick them up. What do you think?

I think that's a great idea ! Personally, I tend to forget the todo file. Is there a way to be reminded to check the todo file when working on file included in the todo ? It would be great if Rubocop could tell us that.

**Review by rioug — APPROVED** [review]

**Comment by jibees** [comment]
>What do you mean? Within this PR or just soon while we are working on similar code?

I'm meant while we are working on similar code, not this PR! Sorry for the confusion.

> I think that it's too big for this PR but I could create issues for all new rules. Hm, maybe it would be useful to create issues for each violation in the todo file. That may motivate the community to pick them up. What do you think?

I think it's a great idea! 💡 👍

**Comment by mkllnk** [comment]
I created a task list in this pre-existing epic:

* https://github.com/openfoodfoundation/openfoodnetwork/issues/6055

We can use the Github UI to create issues for each of them.

**Pull request merged**
