### PR TITLE
7872 remove stripe connect

### LINKED ISSUE #7869: Remove Stripe Connect
## What is the problem we are solving 

Now that we have moved to Stripe SCA we wish to remove Stripe Connect from the codebase to simplify and clean up our code.

## Success factors = expected outcome 

All code related to Stripe Connect is removed
No payment methods will reference this old payment method.
Any reports that reference this old payment method (Enterprise Fees report?) will now reference StripeSCA

## Useful information for inception

While all users have been moved from Stripe Connect it is still possible for users to have chosen this payment method and be using it. Therefore we need to ensure we do a migration of any Stripe Connect payment methods to Stripe SCA. All users have been warned and switched over so this does not need any more support input.

Another payment method was removed recently so this might be useful background:
https://github.com/openfoodfoundation/openfoodnetwork/issues/6231
and this resulting (and still unsolved) error is a mistake we should not repeat:
https://github.com/openfoodfoundation/openfoodnetwork/issues/7799

### LINKED ISSUE #7872: Remove Stripe Connect
### What we should change and why (this is tech debt)

Now that we have moved to Stripe SCA we wish to remove Stripe Connect from the codebase to simplify and clean up our code.

All Stripe Connect code is be removed
No existing payment methods should reference this old payment method.
Any reports that reference this old payment method (Enterprise Fees report?) will now reference StripeSCA

### Context

All Stripe Support teams have handled the roll out of Stripe SCA so we can boldly make code changes and migrations here.

Another payment method was removed recently so this might be useful background:
#6231
and this resulting (and still unsolved) error is a mistake we should not repeat:
#7799

### Impact and timeline

While all users have been moved from Stripe Connect it is still possible for users to have chosen this payment method and be using it. Therefore we need to ensure we do a migration of any Stripe Connect payment methods to Stripe SCA.

### LINKED ISSUE #8169: Migrated StripeConnect payment methods have empty "Account Owner"
## Description

Follow-up from  #8064.
When killing stripe Connect, we were left with one missing bit, after the migration:  **Account owner** is left empty, which breaks payments, namely in Subscriptions.

## Expected Behavior

No StripeSCA payment methods should have `Account owner` empty

## Actual Behaviour

Some StripeSCA payment methods have `Account owner` left empty

## Steps to Reproduce

Find the payment methods which have no `Account owner` attributed -> I guess this should be possible through the console

## Animated Gif/Screenshot

image

## Severity

Breaks subscriptions and potentially shopfront in backoffice payments.

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

Closes #7872
Closes #8169

Removes Stripe connect from codebase with necessary migrations.

#### What should we test?

- It should not be possible to select StripeConnect to create new payment method.
- All StripeConnect payment methods type should be changed to StripeSCA
- All migrated StripeConnect payments should retain account owner.

#### Release notes

- Removed Stripe Connect payment method.

Changelog Category: User facing changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Looking good!

I added a few suggestions but they don't block this pull request. Just a bit of nice-to-have cleanup work.

**Review by andrewpbrett — APPROVED** [review]
👏

**Comment by andrewpbrett** [comment]
@apricot12 this will need a quick rebase for the db schema file but looks great!

**Comment by filipefurtad0** [comment]
This time, I've deleted the migrations:
```
delete from schema_migrations where version = '20210817100257';
delete from schema_migrations where version = '20210928121506';
```
and tried again, but got the same outcome:

image

Should we pair on this tomorrow at some point?

**Comment by mkllnk** [comment]
Hey @apricot12, I'm sorry that it took me so long to look at this again. It's not obvious what's going wrong on staging.

Can we divide this pull request? That may make it easier to find the issue. I would suggest this structure:

1. Remove all uses of Stripe Connect but leave the payment gateway class in the code. This requires to modify the commit "Remove Stripe Connect gateway and related code" and restore app/models/spree/gateway/stripe_connect.rb. There are also some detours in the commit history which can be squashed at the same time, for example "Fix response for payment_profile_id in profile_storer.rb".
2. A following pull request contains the migrations. We should add a spec here as well.

What do you think?

**Comment by apricot12** [comment]
> Hey @apricot12, I'm sorry that it took me so long to look at this again. It's not obvious what's going wrong on staging.
> 
> Can we divide this pull request? That may make it easier to find the issue. I would suggest this structure:
> 
> 1. Remove all uses of Stripe Connect but leave the payment gateway class in the code. This requires to modify the commit "Remove Stripe Connect gateway and related code" and restore app/models/spree/gateway/stripe_connect.rb. There are also some detours in the commit history which can be squashed at the same time, for example "Fix response for payment_profile_id in profile_storer.rb".
> 2. A following pull request contains the migrations. We should add a spec here as well.
> 
> What do you think?

I think this is the best option we have for now. Since the migration for account owner just doesnt seem to be going or way.

**Comment by mkllnk** [comment]
Any progress on this? Or shall I do this?

**Comment by apricot12** [comment]
> Any progress on this? Or shall I do this?

So I've tried on my side to find a solution for the stripe account owner problem, but no luck so far. I'm going to put up a PR for #1 today.

**Comment by mkllnk** [comment]
Great, this is a good next step. Reviewing it now, I'm wondering though if we are still breaking things. For example, if an enterprise still has a StripeConnect payment method and tries to edit it after this pull request, it won't be in the list of available payment methods any more and that could fail.

I'm not familiar enough with this code to direct you exactly what to change. So I think that I will attempt a start by myself and then maybe I can guide you better. Sorry for the confusion. It's a very tricky task to remove a feature gracefully and I don't know this code very well.

So I'm planning to create a pull request with minimal changes so that you can't create a new StripeConnect payment method any more. That's the biggest problem at the moment. People still choose StripeConnect because they don't know better and don't read the warnings. But I will try to keep existing StripeConnect payment methods alive for now so that we don't trigger any errors. Then we can look at migrating those payment methods and lastly, remove all the code.

**Comment by filipefurtad0** [comment]
I think this PR was replaced by #8779, right @apricot12 ?
Closing.

**Pull request closed without merging**
