### PR TITLE
Updates Paypal system spec to consider new checkout flow

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

- contributes to https://github.com/openfoodfoundation/openfoodnetwork/issues/10958

Updates Paypal system spec to consider new checkout flow

#### What should we test?

- green build

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
I'm surprised about this build fail, as the PR does not touch any of this code...
Only reference I've found is this PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/5935

**Comment by sigmundpetersen** [comment]
Seems there's a fix in #12490 , don't know why it started failing though 🤷

**Comment by filipefurtad0** [comment]
> Seems there's a fix in https://github.com/openfoodfoundation/openfoodnetwork/pull/12490 , don't know why it started failing though 🤷

Thank you for pointing it out @sigmundpetersen :pray: I've added the blocked label here.

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Review by mkllnk — APPROVED** [review]

**Pull request merged**
