### PR TITLE
Use OFN logo in admin area

### LINKED ISSUE #3733: Admin logo
## Description

The logo in the admin area is set to the Spree logo by default. Some instances have manually hacked this to show the OFN logo instead of Spree, and it's much better! 

There's a Spree::Config preference called: `Spree::Config[:admin_interface_logo]` which has a default value of `admin/bg/spree_50.png`. We can set it by default to the OFN logo, and we could optionally allow instances to set or upload a custom logo.

## Expected Behavior

Effective branding!

## Actual Behavior

Promoting Spree instead of OFN?

## Steps to Reproduce

You can take a look at the admin area on UK production and French production to compare. Alternatively if you'd like to hack _your_ instance's admin logo, the process looks like this (if you have SSH access):

1. `sudo su openfoodnetwork`
2. `cd /home/openfoodnetwork/apps/openfoodnetwork/current`
3. `bash -lc "bundle exec rails c"`
4. `Spree::Config[:admin_interface_logo] = 'ofn-logo.png'`

I'm not sure how the routing works for this exactly, but the above will use the logo found under: `app/assets/images/ofn-logo.png`.

## Severity

s5?

## Possible Fix

There's lots of options. We could just set in an initializer, or make a fancy custom image upload thing in the content config UI like we have with other custom logos.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3733

Uses OFN logo in admin area instead of Spree logo.

admin-logo

#### What should we test?

Admin area logo has changed.

#### Release notes

Changed the logo in admin area.

Changelog Category: Changed

### CODE REVIEW

**Comment by luisramos0** [comment]
we need to test that this plays well with existing custom (a manually injected spree preference?) setup in aus and uk:
aus:
Screenshot 2019-05-27 at 13 11 14
uk:
Screenshot 2019-05-27 at 13 12 19

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Any thoughts on how this will interplay with the existing hacks to override the logo in the UK and Aus? Not sure how to test that this will play well with the existing production overrides.

**Comment by Matt-Yorkley** [comment]
> @Matt-Yorkley Any thoughts on how this will interplay with the existing hacks to override the logo in the UK and Aus? Not sure how to test that this will play well with the existing production overrides.

It'll override whatever has been added with manual hacks to this new value, which works fine. It's just a db entry with the path to the logo file.

**Comment by sauloperez** [comment]
ping @kirstenalarsen

**Comment by RachL** [comment]
@Matt-Yorkley it is working well in UK staging, but before there was the spree logo. Do you want to set up the manual hack and restage or do you think it is good to go?

**Comment by Matt-Yorkley** [comment]
I think it's good to go :+1:

**Pull request merged**
