### PR TITLE
7891 tailwind v2

### LINKED ISSUE #7891: Add tailwind into our build process
### What we should change and why (this is tech debt)

As discussed in delivery circle, we decide to start with Tailwind and review in 3 months if this was the right way to go.

This issue is here to integrate tailwind into our build.

### Sources
 - https://dev.to/andrewmcodes/webpacker-6-tailwind-css-2-0-integration-3oe6
 - https://gorails.com/episodes/tailwind-css-framework-with-rails
 - https://dev.to/davidteren/getting-started-with-rails-6-1-tailwindcss-jit-webpacker-postcss-8-25g7
 - https://evilmartians.com/chronicles/set-up-tailwind-css-jit-in-a-rails-project-to-compile-styles-20x-faster

### Context
 - #7543
 - #7539
 - #7524
 - https://community.openfoodnetwork.org/t/choosing-our-css-framework/2328
 - https://community.openfoodnetwork.org/t/delivery-circle-meeting-notes-july-6th/2348

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #7891 

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I'm taking a look now :+1:

I tried doing yarn install and it complained my local version of `nodejs` is too low! Updating...

**Comment by Matt-Yorkley** [comment]
@jibees give this a try :eyes:

**Comment by Matt-Yorkley** [comment]
I'm not sure about the all the PurgeCSS configuration, but I'm pretty confident this custom regex is the one we want to be using for matching: 
```rb
/[^%#<>"{\.'`\s]*[^%#<>"{}\.'`\s:]/g
```
It's customised to work with `HAML` specifically :+1:

**Comment by jibees** [comment]
> @jibees give this a try 👀
> 
> I'm pretty sure everything is working (Tailwind, PurgeCSS, JIT mode)...

Yes! We are almost here. I've tested, and seems to be ok, in certain conditions ...

What I've found (but needs more investigations) : 
 - `%div.text-green-50.text-sm` is not not rightly "parsed" by tailwind: only one class is handled. But `%div{class: "text-green-50 text-sm"}` is. Maybe worth having a look at tailwind class parsing for haml. 
 - Modification done aren't take into account. ex. from `%div.text-green-50.text-sm` to `%div.text-blue-50.text-sm`: text is not blue (but by default). Seems not to be the "jit" mode because even disabled, it's not functional.

**Comment by jibees** [comment]
_For the first point;_ I've opened an issue https://github.com/tailwindlabs/tailwindcss/issues/5408 (and a reproductible repo: https://github.com/jibees/tailwind-example) Not a a big deal for us since it seems to concern only when haml class is following by a variable with `=` like 
```haml
%h3= @name
``` 
(see `app/components/distributor_title_component/distributor_title_component.html.haml`)

**Comment by jibees** [comment]
_For the third one;_
Not much. The main point here is to merge the webpack configuration used by the rails app and the storybook one. This has to be done inside the `.storybook/main.js file`.

 I've tested for example:

```js
const railsWebpackEnv = require("../config/webpack/development");
const { merge } = require("webpack-merge");

module.exports = {
  stories: ["../spec/components/stories/**/*.stories.json"],
  addons: [
    "@storybook/addon-docs",
    "@storybook/addon-controls",
    {
      name: "@storybook/addon-postcss",
      options: {
        postcssLoaderOptions: {
          implementation: require("postcss"),
        },
      },
    },
  ],
  webpackFinal: async (config) => {
    return merge(config, railsWebpackEnv);
  },
};
```

But seems to be invalid for now.

(source: https://storybook.js.org/docs/react/configure/webpack/#extending-storybooks-webpack-config)

**Comment by Matt-Yorkley** [comment]
Ah okay, we just need to update the regex to this:
```rb
/[^%#=<>"{\.'`\s]*[^%#=<>"{}\.'`\s:]/g
```
:boom:

**Comment by Matt-Yorkley** [comment]
On the second point, I think Tailwind is doing some heavy caching for performance reasons. I think we'll have to look at setting it up to recompile when certain files change... https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

**Comment by jibees** [comment]
Even if I remove the `jit` mode, and, at the same time, adding the `NODE_ENV=development TAILWIND_MODE=watch` to the `webpack-dev-server`, it needs to restart the server to see the changes applies....

```diff
diff --git a/Procfile b/Procfile
index ba11bc27a..fd7705485 100644
--- a/Procfile
+++ b/Procfile
@@ -1,5 +1,5 @@
 # Foreman Procfile. Start all dev server processes with: `foreman start`
 
 rails:      bundle exec rails s -p 3000
-webpack:    ./bin/webpack-dev-server
+webpack:    NODE_ENV=development TAILWIND_MODE=watch ./bin/webpack-dev-server
 sidekiq:    bundle exec sidekiq -q mailers -q default
(END)
```

I don't have any idea to go further...

**Comment by Matt-Yorkley** [comment]
- What exactly are you trying to do?
- How are you changing the styles? 
- Where are you defining them? 
- Are you doing this in Storybook or the browser?

I can edit Tailwind styles applied to elements on a page (even using Tailwind's `@apply` function) with the current settings and I get a hot-reload that recompiles really fast and reloads the page automatically with the styles updated.

**Comment by Matt-Yorkley** [comment]
As a test, I'm putting this in `app/webpacker/packs/application.scss`:
```css
.pulsing-text {
  @apply animate-pulse font-bold text-gray-200;
}
```

And on line 4 of `app/views/home/_brandstory.html.haml` I'm adding the `.pulsing-text` class to the `h2`, running it in the browser (with `foreman start`) and then editing that style.

I'm not sure about Storybook though, I think it might be more complex to work with.

**Comment by jibees** [comment]
Ok I'll try an explanation as it wasn't clear enough before, sorry.

1. I start the server: `foreman start`
2. I modify the `app/views/home/_brandstory.html.haml` as it:
```diff

diff --git a/app/views/home/_brandstory.html.haml b/app/views/home/_brandstory.html.haml
index 25b868774..4a471d850 100644
--- a/app/views/home/_brandstory.html.haml
+++ b/app/views/home/_brandstory.html.haml
@@ -1,7 +1,7 @@
 #brand-story.pane
   .row
     .small-12.medium-8.medium-offset-2.columns.text-center
-      %h2
+      %h2.line-through
         = t :brandstory_headline
       %p
         = t :brandstory_intro
```
3. I can't see any changes ...
4. If I restart the server, it now works as expected...
Capture d’écran 2021-09-10 à 10 26 56

... ok, it's more complex than I thought...

Same process, but with `underline` instead of `line-through`
1. I start the server
2. I modify the same file, but with `underline`
```diff
diff --git a/app/views/home/_brandstory.html.haml b/app/views/home/_brandstory.html.haml
index 25b868774..6f43e7e38 100644
--- a/app/views/home/_brandstory.html.haml
+++ b/app/views/home/_brandstory.html.haml
@@ -1,7 +1,7 @@
 #brand-story.pane
   .row
     .small-12.medium-8.medium-offset-2.columns.text-center
-      %h2
+      %h2.underline
         = t :brandstory_headline
       %p
         = t :brandstory_intro
```
3. It works as expected...Nice I could say!
Capture d’écran 2021-09-10 à 10 32 49
4. But then, if I change from `underline` to `line-through`

5. `underline` is well remove, but no trace of `line-through` style:
Capture d’écran 2021-09-10 à 10 33 50

6. So, I restart the server (with the `line-through` modification then) ... and then it works...
Capture d’écran 2021-09-10 à 10 35 16


I'd say ... WTF? Is it only _on my machine_?

**Comment by jibees** [comment]
(for Storybook, I'd vote to create another PR once this one is merged ; seems to be difficult, and needs some custom webpack configs ... 😢 )

**Comment by Matt-Yorkley** [comment]
Ah, so I think if the SCSS files change it will trigger a recompile, but it won't do it if only the view files have changed. Does that make sense?

I've added a commit which should trigger a recompile via `webpack-dev-server` when view files change :point_up:

**Comment by jibees** [comment]
I've retested the process, with your commit (thanks 🙏 ). Nothing changed. The process is:

1. Start the server
2. Modify the file `app/views/home/_brandstory.html.haml`: add `underline` to the first `%h2`
3. Works as expected
4. Change `underline` to `line-through` (to the first `%h2`)
5. See that nothing changed. 
6. Restart the server
7. Then, modification works as expected.

This needs a review on how `chokidar` works.

**Comment by RachL** [comment]
@jibees can we close the PR and the issue?

**Comment by jibees** [comment]
@RachL 
Discussion open: https://community.openfoodnetwork.org/t/tailwind-5-months-after-review-pros-and-cons-what-should-we-do/2478
Think we can close this one, and open a new if needed

**Pull request closed without merging**
