### PR TITLE
DFC API return SuppliedProduct after creation

### PR DESCRIPTION
**Pull request by mkllnk**
:information_source: This is a funded feature. Please use the Clockify project with the following name when working on this, including review and test: `#9170 OFN DFC Products`

#### What? Why?

- Part of #10826 

When you create a new product via the DFC API you need to know its id to refer to it later. The API endpoint used to respond without any content but now it returns the SuppliedProduct.

Screen Shot 2023-06-30 at 15 00 48

#### What should we test?

- You need a user managing or owning an enterprise.
- Retrieve the API key of that user.
- Visit `/api-docs` and select the DFC API.
- Authenticate with your API token.
- Go to Create SuppliedProduct.
- Execute the example with test data similar to the example.
- The response should be successful and the product should be created.
- The response should contain the DFC id of the new SuppliedProduct (based on a Spree::Variant).

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

#### Dependencies

- #11133

### CODE REVIEW

**Review by rioug — APPROVED** [review]
There is an empty commit here : 01cdb894f9672a1bc0bac14d7fc0888edfcedc51, can that be cleaned up ? 
Otherwise looks good :+1:

**Comment by mkllnk** [comment]
> There is an empty commit here : https://github.com/openfoodfoundation/openfoodnetwork/commit/01cdb894f9672a1bc0bac14d7fc0888edfcedc51, can that be cleaned up ?

It's not empty, it's a merge commit. Once the other PR is merged and this one is rebased, the merge commit will disappear.

**Review by rioug — APPROVED** [review]
A little bit hacky as you mentioned but I think it's fine given the circumstances.

**Review by dacook — APPROVED** [review]
Great work, an improvement and it's now more robust to handle the ever-changing DFC.

**Pull request merged**
