### PR TITLE
Fixes minor styling issues of admin v3 in the multi-enterprise dashboard

### LINKED ISSUE #11843: [BUU] Dashboard: Thin blue border around the Order Cycles section
## Description

On the multi-enterprise dashboard there is a thin blue border around the order cycles section if no active order cycles are available.

## Expected Behavior

It should look like the products section, which means a red border should be used instead.

## Actual Behaviour

There is a thin blue border.

## Steps to Reproduce

1. As an enterprise user with more than one enterprise, make sure you have no active order cycle available.
2. Visit the dashboard.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #11865: [BUU] Dashboard: Text ‘You have x active …’ is black for products, while it’s blue for order cycles (for multi-enterprise user)
## Description

The text ‘You have x active …’ is black for products, while it’s blue for order cycles.

## Expected Behavior

The colours should be identical.
Both should be very dark gray (almost black) like the text for products.

## Actual Behaviour

The text for order cycles is blue.

## Steps to Reproduce

1. As admin make sure you have more than one enterprise.
2. Make sure you have at least one product and one open order cycle.
3. Visit /admin/dashboard.
4. Check the colours.

## Animated Gif/Screenshot

image5

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by drummer83**
#### What? Why?

- Closes #11843
- Closes #11865

**Before:**
image

image

**After:**
image

image

#### What should we test?

- Make sure you have multiple enterprises but no order cycle open.
- Visit the overview page /admin.
- Check that there is no thin blue border around the 'Manage order cycles field'.
- Open an order cycle.
- Make sure you at least one product.
- Check that the text 'You have x active ...' has the same colour for products and order cycles.
- Check that the legacy admin design remains unchanged and everything is working.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — COMMENTED** [review]
Thanks for diving in to sort these out.

I think we could achieve with much less code by setting up a couple of CSS classes to style it accordingly. How comfortable would you be with trying that? I'd be happy to create a commit to get you started if you'd like to try.

**Comment by drummer83** [comment]
Sure, @dacook!
Looking forward to learning. :green_heart: 
Thank you, David!

**Comment by dacook** [comment]
Apologies I didn't get back to this today, will do it in the morning.

**Comment by drummer83** [comment]
Work continued in #11977. Closing here.

**Pull request closed without merging**
