### PR TITLE
3.0 updates

### PR DESCRIPTION
**Pull request by Matt-Yorkley**

### CODE REVIEW

**Comment by luisramos0** [comment]
nice! I guess the question is: what are the things from this PR that we can bring to master?

for example: Is this a valid fix? can we bring to master?
Screenshot 2019-12-22 at 16 49 56

**Comment by Matt-Yorkley** [comment]
> Is this a valid fix? can we bring to master?

Nope, that one's `Rails 4` only...

**Comment by Matt-Yorkley** [comment]
Okay! Out of 3204 tests, 584 are currently failing. That's ~18%!

**Comment by Matt-Yorkley** [comment]
On the `strong parameters` issue, Spree has it's own implementation:

https://github.com/spree/spree/blob/4cc2c2967352d3fe7652bd873e492c074ffcc3da/core/lib/spree/core/controller_helpers/strong_parameters.rb
https://github.com/spree/spree/blob/4cc2c2967352d3fe7652bd873e492c074ffcc3da/core/lib/spree/permitted_attributes.rb
https://github.com/spree/spree/blob/4cc2c2967352d3fe7652bd873e492c074ffcc3da/core/spec/lib/spree/core/controller_helpers/strong_parameters_spec.rb

**Comment by Matt-Yorkley** [comment]
Closing as tidied up and split into 3 new cleaner and smaller PRs.

**Pull request closed without merging**
