### PR TITLE
Add used feature toggles to appear in the admin UI

### LINKED ISSUE #9125: List available feature toggles in the UI
### What we should change and why (this is tech debt)

When you want to activate a new feature, you have to know it's key like `api_v1`. It would be nice if we added these to Flipper when booting the application so that you see an overview of all current feature in the feature toggle UI.

With that list of currently active feature, we can also remove old features from the database to keep it clean. That has the advantage that we can re-use feature names. This may happen accidentally, for example if someone uses `api_next` as key and two years later there's a new API and we use it again, forgetting that it has been used already. If we then had pre-existing toggles in the database, we may get random behaviour. So cleaning those up avoids that.

### Context

Non-devs want to activate feature toggles like the API and have to ask devs about the name.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #9125 

The admin UI shows only features which were added to the database. We always had to look up a feature's name add it manually before we could enable it. Now it will appear in the UI after some code asked if it was enabled.

This only adds a database query once when the feature doesn't exist yet. The `feature.exist?` call only performs an in-memory lookup in the memoizer.

This implementation is slightly different to what I suggested in the issue. I thought we had to maintain a list of features and add them add boot time. But I think that it's better to avoid maintaining that list and to avoid the work during boot time. One day we still want to remove old features from the database but I checked current production servers and I couldn't see any unused features. Lets do that when it actually becomes a problem.

#### What should we test?

- Visit `/admin/feature-toggle/`.
- Delete all features.
- Go to `/admin/reports/orders_and_distributors`
- Then reload the feature toggle page and assert `report_inverse_columns_logic` being there.
- Visit `https://staging.openfoodnetwork.org.au/api/v1/customers`.
- Assert that `api_v1` is in the feature toggle list.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Thanks for this one!

Specs failed, I think we probably should do something like that (as it should be I guess): 

```diff

diff --git a/spec/system/consumer/shopping/checkout_auth_spec.rb b/spec/system/consumer/shopping/checkout_auth_spec.rb
index 747a6d2413..389c5a4eaf 100644
--- a/spec/system/consumer/shopping/checkout_auth_spec.rb
+++ b/spec/system/consumer/shopping/checkout_auth_spec.rb
@@ -83,8 +83,8 @@ describe "As a consumer I want to check out my cart", js: true do
 
       context "split checkout" do
         before do
-          allow(Flipper).to receive(:enabled?).with(:split_checkout) { true }
-          allow(Flipper).to receive(:enabled?).with(:split_checkout, anything) { true }
+          allow(OpenFoodNetwork::FeatureToggle).to receive(:enabled?).with(:split_checkout) { true }
+          allow(OpenFoodNetwork::FeatureToggle).to receive(:enabled?).with(:split_checkout, anything) { true }
         end
         include_examples "with different checkout types", "split_checkout"
       end
```

**Review by jibees — APPROVED** [review]
Nice! 
Way much better now thanks to you!

**Comment by drummer83** [comment]
Hi @mkllnk,
Thanks for the great test instructions again!

I tested this one on staging UK. These are the features **before** staging this PR:
image

I then deleted all features and visited the pages you mentioned:
Peek 2022-10-08 16-46

As you can see, the features are back on the list. I have also visited /checkout to get Split Checkout back in the list. 
image

We just don't have 'a_feature_which_does_not_exist' anymore... According to the name I am not worried about that! :smiley: 

As far as I can tell we are ready to go here! :+1:

**Comment by mkllnk** [comment]
Great testing! Thanks.

**Pull request merged**
