### PR TITLE
Fix product duplication

### LINKED ISSUE #660: Product duplication has errors or not working at all
In production, when I'm duplicating products, the price, quantity and units fields aren't always duplicating accurately. I can't see much of a pattern in regards to why some products duplicate accurately, and others have strange, inconsistent errors.
I was logged in as sstead@student, and sallystead2@gmail...

Examples:
image
image
image
image

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

Closes #660

The product duplicator is not cloning the variants of the original product.
=> I updated the logic to make it clone the variants.

#### What should we test?

- check #660

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by abdellani** [comment]
@mkllnk 

I fixed variants cloning.
Now, when a variant is cloned, the `after_create` hook is called to create the stock items.

I'm not sure about the best approach to copy data from the original `stock items` to the new ones.

Is it better to let the hook does its job, then search for the copies and update them?
Or to create the stock item manually and skip the `after_create` hook?

**Comment by abdellani** [comment]
@mkllnk 
I updated the product duplication test, but it's still failing because of the following [condition](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/spree/core/product_duplicator.rb#L16) 
```ruby
        # don't dup the actual variants, just the characterizing types
        new_product.option_types = product.option_types if product.variants?
```
Is this condition still valid? do we copy the option_types only when the product has variants?

**Comment by mkllnk** [comment]
> Is this condition still valid? do we copy the option_types only when the product has variants?

Good question. To be honest, I never came across the option types code before and I have been working with this code base for many years. :open_mouth: 

1. This concept comes from Spree and our code is a bit different. We always have variants.
2. Because we always have variants, we just [simplified the duplicator code](https://github.com/openfoodfoundation/openfoodnetwork/commit/c0ee72319fb2705fcd686c699a9fc18153f29e0f). Please rebase on master.
3. The comment "don't dup the actual variants" is not valid any more because we are now doing it. :smile: 
4. I think that we want to copy the option_types and you can alter the spec for this.

Does that answer your question?

**Comment by abdellani** [comment]
Yes, I understand now  : )

I rebased on the master branch, and the tests are passing locally now.

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for looking at this reeeeeally old issue. It has been around for more than 7 years now! :eyes: 
I have cloned products with all kinds of settings and properties and with multiple variants before and after your pull request.

In the product list I have split testing into two steps to see all available columns and compare them.
**Part 1:**
image
**Part 2:**
image

You can see:
- before your PR a lot of information was not cloned properly and most important the second variant was not cloned at all
- after your PR both variants are cloned and almost all information is cloned correctly. The only information missing on the clones is SKU, the on hand amount and the on demand setting. 

I have also checked every single page of the product details and compared the original product/variant to the cloned ones after your PR.
**Product details:**
image
**Variants:**
image
**Edit variant:**
image

Here also SKU, the on hand amount and the on demand setting are the only things which are not included in the clone.

## Conclusion
This is a great improvement and I am sure our users will love it.
Regarding SKU: It is not cloned but that's ok, because SKU will never be the same as for the original product and we have no information what the new SKU would be.
Regarding on hand amount and on demand setting: The way we do it now the cloned product will never be shown in the shopfront  because stock is 0 and on demand is deactivated. This is probably ok. One could think about cloning these two settings as well, but especially stock levels are unlikely to be the same as for the original product. @openfoodfoundation/train-drivers-product-owners If you think that any of this information should be included in cloning as well, let me know and I will create an issue for this.

Thanks again @abdellani, this is great to see and I think we are ready to merge here. :muscle:

**Comment by RachL** [comment]
@drummer83 thanks! think we are good this way. We can go back to this once back-office UI uplift is done and network part 2 is kicking in.
This is super great improvement already!

**Comment by tschumilas** [comment]
I missed this issue before being merged -  and I"m SO SO happy to see it fixed.  I'm a user that does a lot of cloning.  Most typically, as a support person,  I clone when I am also re-assigning a product to a new enterprise (which saves a lot of new product creation).  So the choice to set on demand and stock = 0 for the clone is absolutely the right one (IMHO).    I look forward to cloning now!!  Thanks all.

**Pull request merged**
