### PR TITLE
Quick css fix in main menu

### LINKED ISSUE #5671: Styling in main menu (Superadmin)
## Description

While testing translation PR #5589 I noticed the item "More" on the main menu is slightly misplaced. This appears only to affect  Superadmin in Language dashboard.

## Expected Behavior

Menu should look like this ("More" should appear translated, in production):
image

## Actual Behaviour

image

## Steps to Reproduce

1. Log in as Superadmin and check how the main menu looks like in French language.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Worth checking how does it look like in production, with the due translation key.

### PR DESCRIPTION
**Pull request by renanbona**
#### What? Why?

Closes #5671 

BEFORE the changes:
before_the_changes_french

AFTER the changes:
new_menu_french
new_menu_english

#### What should we test?

Access the `/admin` page and the main menu should be ok with both langues (English and French)

#### Release notes

Fix css in main menu (Superadmin) 

Changelog Category: Fixed

### CODE REVIEW

**Comment by luisramos0** [comment]
Thanks for your PR!

I am not sure about reducing the fontsize. I thought we were using a plugin that adds entries to MORE if they dont fit. So the solution here would be to make one extra entry like customers go into the MORE submenu.

**Comment by renanbona** [comment]
OK, I will check this plugin and see if I cant make the customers option go to the MORE submenu.

**Comment by luisramos0** [comment]
I remember now, it's vendor/assets/javascripts/jquery.adaptivemenu.js

**Comment by renanbona** [comment]
I've been doing some tests in the master branch, and apparently this bug has already been fixed. So I'm thinking about closing this PR. Can you have a quick look and see if you can reproduce this bug? @luisramos0

**Comment by luisramos0** [comment]
I think the problem is still there but only in some circumstances? I know you have to be super admin and maybe it's only in French. And if it works in French superadmin I think there will be another condition that is causing this sometimes...

**Comment by RachL** [comment]
heya @renanbona are still working on this issue or should we close your PR for someone else to pick it up?

**Comment by renanbona** [comment]
Hey @RachL I'll work on this again this Friday.

**Comment by renanbona** [comment]
Actually this bug is already fixed in this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/5658/files#diff-e35182d90157bf50b09e78cb6a31defaR2808. The translation of word "More" was added in `fr.yml`. So I'm closing this PR because I've tested in both browsers Google Chrome and Mozilla in different monitors and the bug is already fixed. 

main_menu_fixed

**Pull request closed without merging**
