### PR TITLE
update swagger.yaml based on current docs

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/6040 - this adds the most recent file downloaded from Swagger.

#### Release notes

Updated documentation

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Okay, I'm not sure how to verify this. How did you generate it?

**Comment by luisramos0** [comment]
hey, maybe you will need to verify details but swagger.yaml on our code repo is the golden data source for this, not what's in swagger.io. I believe what's in swagger.io is an older version.
I think you can close this PR and keep what's on our side. You can just upload on our side an put it in the ofn account in swagger.io.

**Comment by andrewpbrett** [comment]
Well the one on Swagger says version 0.2 and the one in the repo says 0.1... 😁 :trollface:

**Comment by mkllnk** [comment]
Simply copied and pasted our swagger.yml to Swaggerhub now and they should be in sync.

**Pull request closed without merging**
