### PR TITLE
Checkout address handling

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Related to Stripe problems previously explored in https://github.com/openfoodfoundation/openfoodnetwork/issues/7952#issuecomment-883545593 and https://github.com/openfoodfoundation/openfoodnetwork/pull/8233

I'm pretty sure this is responsible for at least some (but maybe not all) of the problems reported in #8296 

Should fix some edge cases with failing Stripe payments, where the errors shown in Bugsnag refer to address fields being blank (when they actually were filled out correctly at the checkout), and the backtrace shows the checkout was being loaded after a Stripe redirect (referencing `#handle_redirect_from_stripe`). Here's an example from French Production: https://app.bugsnag.com/open-food-france/coopcircuits/errors/60f11496903af700075b686d?filters[event.since]=7d&filters[error.status]=open&event_id=618a7041008972185a600000

Review note: see further details in the second commit message. 

Side note: ultimately we should move all this Stripe-response-processing into it's own controller, and have Stripe redirect back to _that_, instead of just throwing all these requests at the `checkout#edit` action.

Soundtrack: [Oh My Gosh!](https://www.youtube.com/watch?v=gOEHefkds2w) :musical_note: 

#### What should we test?

I think these issues can sometimes occur when using Stripe at the checkout in cases where either:
- the user is a guest
- the user is registered but hasn't previously placed an order
- the user is registered but hasn't previously saved an address

If a previously saved address isn't found (not including the billing and shipping addresses on the current order), the addresses on the order can get partially _cleared_, which means the order doesn't get completed because the addresses become invalid.

#### Release notes

Fixed address issue in checkout with Stripe payment processing

Changelog Category: Technical changes

### CODE REVIEW

**Review by jibees — APPROVED** [review]
We should have this in mind for the split checkout too ;)

**Comment by Matt-Yorkley** [comment]
> We should have this in mind for the split checkout too ;)

Luckily the split checkout doesn't have this problem yet :smile:

**Review by mkllnk — APPROVED** [review]
That makes sense, thank you!

I agree that a separate controller would be better.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

I've went through the scenarios you mentioned (before staging) but could not reproduce this one, for some reason.

After staging, tested Stripe SCA payments on shopfront, backoffice and subscriptions. Tried some edge cases around new customers, for example, placing backoffice orders for unregistered customers.

It all looks good!
Let's keep our eyes out on this one :eyes: :crossed_fingers:

**Comment by RachL** [comment]
Love the soundtrack :) 

I'm closing the linked issue : let's reopen as soon as we have new examples.

**Pull request merged**
