### PR TITLE
Align items on shipping and payment methods forms

### LINKED ISSUE #6784: Wrong alignment on shipping and payment methods
## Description

When creating or updating a new shipping method and payment method, some fields are not correctly aligned

## Steps to Reproduce

1. Go to `admin/enterprises/NAME/edit#/shipping_methods`
2. Edit an existing shipping methods and see the fields are not aligned
3. If you create a shipping method, alignment problems are starting after saving
4. Same on payment methods BUT creation form has already alignment problem on the calculator

## Animated Gif/Screenshot

image

image

image

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.5.6
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Closes #6784 
Align forms (on both creating and editing) for shipping methods and payment methods.

#### What should we test?
1. As an enterprise manager, test both shipping methods and payments methods forms: items must be aligned.
2. Test forms on creation and editing: items must be aligned.
Capture d’écran 2021-02-01 à 15 20 43
Capture d’écran 2021-02-01 à 15 20 15
3. Don't forget to test each state of form. For example, on the Payments methods form, don't forget to test when "Provider" field is Stripe, Paypal, ... : 
Capture d’écran 2021-02-01 à 15 51 06

#### Release notes
Fix alignment issues on payment methods and shipping methods

Changelog Category: User facing changes

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
I think this one should be a falky spec:
./spec/features/admin/payment_method_spec.rb:55 # 

So I moving on with staging/testing :+1:

**Comment by jibees** [comment]
> I think this one should be a falky spec:
> ./spec/features/admin/payment_method_spec.rb:55 #
> 
> So I moving on with staging/testing 👍

Not sure, I need to investigate...

**Comment by filipefurtad0** [comment]
Ok, @jibees - I'm having a look already at the PR in staging-UK, but I'll await for your feedback, in case you conclude this is not flaky spec.

**Comment by jibees** [comment]
> Ok, @jibees - I'm having a look already at the PR in staging-UK, but I'll await for your feedback, in case you conclude this is not flaky spec.

Thanks to the tests, I can notice that this field (Stripe Account Owner) was hidden. It should be now visible.

Capture d’écran 2021-02-01 à 17 57 37

**Comment by filipefurtad0** [comment]
Thanks you for investigating this. I'll stage this again after the green build.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Thank you for the detailed test proposals.
 
This looks good now. As a comparison, we can see a server without this PR (left side) and a server with this PR staged (the right): 
  
image

image

image

I had a look on mobile (iPhone below) as well:

image

image


All good, moving to ready to go.

**Pull request merged**
