### PR TITLE
Product import: consider `display_name` with `null` or `empty` as value as equal

### LINKED ISSUE #9868: [Product Import] Empty variant names recorded differently leads to variant duplication
## Description
When importing a file, some variants are duplicated instead of updated: it's the ones whose variant names have been deleted. As they have a `display_name=""` instead of `null`, they are considered new variants.

## Expected Behavior
Variants should be updated and not duplicated if the same variant already exists.

## Actual Behaviour
Some variants are duplicated instead.

In OFN, each variant has a name -or no name-, as well as a parent product defined by its own name. 
When you import a csv file, if a product and a variant name is the same -or has no name- as an existing one , the initial variant of this product should be updated.

But when you create a variant and you let the variant name field (`display_name`) empty, the name has no value and `display_name=null`.
Now if you edit this variant and give it a name, `display_name=“whatever”`is saved in memory. Then if you delete the variant name, `display_name=""`.

Now if you import a csv file to update your products, a duplicate will be created for these variants, as display_name=null is different from  display_name="".

That's why some variants are duplicated instead of updated, it's the ones that had a name one day and lost it. 

## Steps to Reproduce

1. Import a csv file from the product import page (admin/product_import) with 2 products having the diplay_name field empty (it also works if you create 2 products from the dashboard (admin/products/new), with the variant name empty)
ex file: 
[PEPITES.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9864874/PEPITES.csv)

2. Import the same file again, see that both products are updated
3. In the Product page, edit one of these products (admin/products/xxx/edit) and give the variant a name and ave. Then delete the variant name and save.
4. From the product import page, import the csv file again (admin/product_import), see that the variant you've edited is created again instead of updated 

To check the request:
5. On the product page, open developer tools, search for the edited product and look at the request
https://coopcircuits.fr/api/v0/products/bulk_products.json
6. In the response, under the variant sections, see that
-  in the “variants” section, which displays the latest updated data of a variant, “display_name”: “”
-  and in “master” section, which is an image of the initial variant data, “display_name”: null
7. Search for the other product and look at the request: display_name is null

## Workaround
Re-creating products from scratch.
Edit the products manually and remove them from the import file.

## Severity
bug-s3: a feature is broken but there is a workaround

It's not so rare, i looked at the 15 first products of 8 enterprises randomly, and 
- shop 1963: 10 products with "display_name"=""
- shop 2723 : 10 products with "display_name"=""
- shop 2633 : 2 products with "display_name"=""
- shop 1985 : 3 products with "display_name"=""
- shop 4071 : 0 products with "display_name"=""
- shop 3902 : 0 products with "display_name"=""
- shop 2719 : 1 products (out of 4) with "display_name"=""
- shop 3570 : 3 products with "display_name"=""
So 6 out of 8 of these shops will have duplicates if they import a file to update their products. Fortunately nobody ou presque does that.

## Possible Fix
Variants names should be considered the same if display_name is null OR empty.

And probably assign null value to display_name when a variant is saved with no name. (it would be logical but this alone will not fix the issue for all already existing products)

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #9868 

#### What should we test?

Can't explain more than the linked issue

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — COMMENTED** [review]
@jibees shouldn't we have a spec to test this scenario ?

**Review by mkllnk — CHANGES_REQUESTED** [review]
Good, this should work. But I agree on having a spec.

**Comment by jibees** [comment]
Yep, you're right. 
See commit d9b534b829 (should be squashed)

**Review by rioug — APPROVED** [review]
Looks good now :+1:

**Review by mkllnk — APPROVED** [review]

**Pull request merged**
