### PR TITLE
Sass deprecations

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?
Those deprecation warnings have been bugging me for ages. They're gone now!

#### What should a dev test?
`bin/webpack`

No deprecation warnings should appear like this 
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($total-colspace, 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
10 │ $col-width: ($total-colspace / 16) * 0.01;
   │              ^^^^^^^^^^^^^^^^^^^^
   ╵
    app/webpacker/css/admin/grid.scss 10:14       @import
    app/webpacker/css/admin/all.scss 91:9         @import
    app/webpacker/packs/admin-styles-v2.scss 4:9  root stylesheet

```

#### Release notes

<
Changelog Category:  Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Nice one, thanks a lot!

I think I will test and merge it ;)

**Comment by jibees** [comment]
I've tested, and still have some:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(strip-unit($value), strip-unit($base-value))

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
93 │   $value: strip-unit($value) / strip-unit($base-value) * 1rem;
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/foundation-sites/scss/foundation/_functions.scss 93:11           convert-to-rem()
    node_modules/foundation-sites/scss/foundation/_functions.scss 128:27          rem-calc()
    node_modules/foundation-sites/scss/foundation/components/_global.scss 297:17  @import
    app/webpacker/css/darkswarm/variables.scss 1:9                                @import
    app/webpacker/css/darkswarm/all.scss 4:9                                      @import
    app/webpacker/packs/darkswarm.scss 1:9                                        root stylesheet
```
+

```
WARNING: 27 repetitive deprecation warnings omitted.
```

All warnings I've seen are in `node_modules/foundation-sites/scss/foundation/`

Then, I wanted to deactivate warning from deps then, by using the [quietDeps option](https://sass-lang.com/documentation/js-api/interfaces/Options#quietDeps) which reduce the number of warnings, but still don't entirely remove them. Probably because sass loader doesn't recognize them as deps. 

I've made a commit then: 6bf21d2abd

Please, delete if you feel this is not an improvement.

**Review by rioug — APPROVED** [review]
Nice one, I tested with and without JB's change and as he noted the warnings are coming from something we don't control. The `quietDeps` option is definitively an improvement though .

**Comment by dacook** [comment]
Thanks for the improvement, I'll go ahead and merge!

**Pull request merged**
