### PR TITLE
Remove Angular from Primary Details Tab

### LINKED ISSUE #9479: [Bye Bye Angular] Enterprise Settings -> 'Primary Details'
Implement Stimulus in the "Primary Details" section:

Task One - Should have a stimulus controller that react on some input changes (ex do not show the field "permalinkCtrl" until sells == 'own' or 'any', ...). Should be generic as possible since will probably widely used in others sections
Estimate - 4hrs

Task Two - Implements the `permalink_controller` as a Stimulus controller 
(see `app/assets/javascripts/admin/enterprises/controllers/permalink_controller.js.coffee`)
Estimate - 6hrs

### PR DESCRIPTION
**Pull request by binarygit**
#### What? Why?

Closes #9479

#### What should we test?

- Visit page `/admin/enterprises/<shop-name>/edit#!/primary_details`
- Ascertain the Groups selector works as it did previously
- Ascertain that you can select/deselect (multiple) Groups
group

- Ascertain that when you enter an available permalink, user is notified that it's `available` .
- Ascertain that when you enter an unavailable permalink, user is notified that it's `unavailable`.
- Ascertain that any unaccepted chars in the permalink such as `/` `$` etc are turned into `-` automatically. Eg: you input 'fr$d', the permalink input should automatically update with 'fr-d'

- Ascertain that the various `what's this` info floats display/hide as they did

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice, thank you!

I was wondering if the permalink controller could be replaced with more general code. It's very common to submit a form and replace some HTML. Are we doing more than that? I thought that there were some default tools in StimulusJS to do that.

**Comment by binarygit** [comment]
I don't think it's as general a workflow. We are displaying/hiding `spinners, availability` in a very `life-cyclic` way. And these are pretty much very specific to the permalink. But you are right, in the end it is actually just replacing certain content after making a response but it is only just one line of JS `this.permalinkFieldTarget.value = result;` as I see it.

And no Stimulus doesn't have anything default for something like this :sweat_smile:

**Comment by drummer83** [comment]
Quick question @binarygit: 
- By 'Groups selector' in the 'What should we test?' section you mean the radio buttons? 
- And the permalink workflow means that the link opens correctly? Or is there more?



Thanks!

**Comment by binarygit** [comment]
Hey @drummer83 I updated my `What's should we test?` section, I think I answer your questions completely there...let me know if that's not the case :slightly_smiling_face:

**Comment by drummer83** [comment]
Note to myself: Most of this applies to super-admin only. ☝️

**Comment by drummer83** [comment]
Hi @binarygit,
Thanks for this one! I have tested the following as super-admin user as well as enterprise owner (where possible):

#### "Whats this?" popups
- They all show nicely, well aligned and with the correct content. **--> OK**
- On smaller screens the popups may be partially covered by the "Groups" input field. This was introduced by this PR. --> **new issue #9636**
- Left before PR, right after PR:
Peek 2022-09-05 23-56

#### Groups selector
- Groups can be selected **--> OK**
- Groups can be removed **--> OK**
- Groups can be searched for **--> OK**
- Selected groups will be applied to the enterprise **--> OK**
image

#### Permalink
- Permalink input shown for 'sells == own' or 'sells == any' **--> OK**
- Invalid characters are deleted while typing slowly (because the appear at the end) while they are replaced by '-' when typed very fast or pasted **--> OK**
- Permalink works well for accessing the shopfront (also after changing the permalink) **--> OK**
- New version is really slow (1 s delay) compared to previous version (almost instantly) **--> Can we improve this? Separate issue #9637**
- Left before PR, right after PR:
Peek 2022-09-06 00-15

There are two minor thing which we could look into. I have created new issues for them. None of them should prevent us from going ahead and merging, I think.

Moving to ready to go!

Thanks again for this great contribution! :muscle:

**Pull request merged**
