### PR TITLE
Change default enterprise limit in Spree::User from 1 to 5

### PR DESCRIPTION
**Pull request by ltrls**
PR for #683 
As it's enforced in database I made a migration to change it.

### CODE REVIEW

**Comment by sauloperez** [comment]
There seem to be a bunch of specs that rely on this limit to be 1.

**Comment by daniellemoorhead** [comment]
There are still conflicts on this branch, so removing the aus review label till it's green.

**Comment by myriamboure** [comment]
? @ltrls can you look at that ? it seems to me that all tests have passed... Not sure I understand :-o let me know Pierre when I can put again the aus review label.

**Comment by ltrls** [comment]
> ? @ltrls can you look at that ? it seems to me that all tests have passed... Not sure I understand :-o let me know Pierre when I can put again the aus review label.

I rebased it just after @daniellemoorhead comment ^.^

**Comment by ltrls** [comment]
I'd like to add an error modal as requested [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/683#issuecomment-327875389) but I'm pretty bad at Angular (and not sure if should use Angular stuff at all).
I can do something like this:
```diff
diff --git a/app/views/admin/enterprises/index.html.haml b/app/views/admin/enterprises/index.html.haml
index a233bc314..c539536ce 100644
--- a/app/views/admin/enterprises/index.html.haml
+++ b/app/views/admin/enterprises/index.html.haml
@@ -4,9 +4,8 @@
 - content_for :page_actions do
   = render 'admin/shared/user_guide_link'
 
-  - if spree_current_user.can_own_more_enterprises?
-    %li#new_product_link
-      = button_link_to t('.new_enterprise'), main_app.new_admin_enterprise_path, icon: 'icon-plus', id: 'admin_new_enterprise_link'
+  %li#new_product_link
+    = button_link_to t('.new_enterprise'), main_app.new_admin_enterprise_path, icon: 'icon-plus', id: 'admin_new_enterprise_link', onclick: ("event.preventDefault(); alert('something')" unless spree_current_user.can_own_more_enterprises?)
 
 = admin_inject_monthly_bill_description
 = admin_inject_column_preferences module: 'admin.enterprises', action: "enterprises_index"

```
but I'm not sure if I'm in the right direction not using Angular directives, where I should insert the modal content... should I use the [ofn-modal](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/darkswarm/directives/modal.js.coffee) directive? (I'm not sure how ><)

**Comment by myriamboure** [comment]
Ping @mkllnk or @oeoeaio if you have an advice for @ltrls on his new question ?

**Comment by sauloperez** [comment]
I don't know Angular either @ltrls but `"event.preventDefault(); alert('something')" unless spree_current_user.can_own_more_enterprises?` should go into a function in the controller and then call it using `ng-click` like you can see in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/customers/index.html.haml#L62

**Comment by myriamboure** [comment]
@daniellemoorhead in the Aus support context, do you think someone who knows well Angular in the Aus team can spend 10-15 min with @ltrls so that he doesn't spend a day searching by himself ? Let us know who can and let's connect them on Slack :-)

**Comment by daniellemoorhead** [comment]
Hi @myriamboure, I think that @oeoeaio would be the best person for this request. I would suggest that either yourself or @ltrls get in touch with him on slack and organise a time to chat about it :)

**Comment by myriamboure** [comment]
Ok awesome ! it seems @augnustin knows Angular so I think he might be able to support @ltrls, guys feel free to chat with @oeoeaio on Slack if you don't find quickly your way through :-)

**Comment by oeoeaio** [comment]
Sorry for the slow response team. @myriamboure @augnustin @ltrls where are you at with this?

`ofnModal` is a darkswarm (frontend) directive, which is designed to be used in conjunction with Foundation Zurb, so it cannot be easily used in the backend. 

I would suggest using the `InfoDialog` directive (`javascript/admin/utils/services`), example usage [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/4dd71c12404554053da2d78b3a3a7e0cba6335fe/app/assets/javascripts/admin/resources/services/customers.js.coffee#L27)

**Comment by daniellemoorhead** [comment]
@myriamboure this PR says it's WIP but it's in the test ready column. Did work finish on this and it's actually ready for testing? If yes then take the WIP label off :)

**Comment by myriamboure** [comment]
I guess we can @daniellemoorhead I was not sure, if a PR is superseeded by another one, can the previous one be closed? Not sure how superseeding works :-o Can you check with the team if you are in the same room?

**Comment by daniellemoorhead** [comment]
Closing this as superseded by #2053. Feel free to reopen if still needed.

**Pull request closed without merging**
