### PR TITLE
BUU: Fix question mark icon for tooltip

### LINKED ISSUE #11524: Enlarged unit price tooltip image, on variant edit page
## Description

Maybe introduced by [angular removal](https://github.com/openfoodfoundation/openfoodnetwork/pull/10833) from the admin pages?

The tool-tip image found on the variant-edit page appears enlarged and with incorrect shape. Function is not affected: if we click on it, the box is still displayed, as usual. It just affects readability and usability.

## Expected Behavior

Tooltip should appear with the correct size and shape:

image

## Actual Behaviour

The question mark / tooltip image appears enlarged and partially hidden. There are also errors in the console, not sure if related:

image

## Steps to Reproduce

1. Visit the variant-edit page for a given variant, /admin/products/<product_id>/variants/<variant_id>/edit`
2. Notice the poor readability on the unit price tooltip image

## Animated Gif/Screenshot

See Expected and current behavior.

## Workaround

-

## Severity

Only backoffice users impacted. Function not compromised. Regression. Proposing:
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: tested on v4.4.10, but around for a while now I think«
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Fixed in legacy backoffice, so this one closes #11524 as well.
Capture d’écran 2023-09-11 à 15 35 20

Capture d’écran 2023-09-11 à 15 35 15

#### What should we test?

- As an admin, visit product creation/edition page, and check that question mark for tooltip renders well.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1 or DFC)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
@filipefurtad0 ,@jibees, 
Did this close https://github.com/openfoodfoundation/openfoodnetwork/issues/11388 as well?

**Comment by jibees** [comment]
Oh yes, was a duplicate. Thanks @drummer83 !

**Comment by RachL** [comment]
thanks @drummer83 I knew I had seen an issue before, but I failed to find it doing searches in the repo. YAY to one less issue 💪

**Comment by filipefurtad0** [comment]
Thank you for raising it @drummer83 - indeed the issue I opened was double from #11388, which considers the **product creation page** (mine does not!).

In any case, and to answer your question, yes the PR fixes that page too:

image
image

**Pull request merged**
