### PR TITLE
Orders page spec update

### LINKED ISSUE #8216: [release test automation] Orders page
### What we should change and why (this is tech debt)

We need to check and update the test cases on `/orders` page. This should be covered by the file:

`spec/system/admin/orders_spec.rb`

```

As an administrator
    I want to manage orders
  with a complete order
    order cycles appear in descending order by close date on orders page
    filter by multiple order cycles
    filter by distributors
    filter by complete date
    select/unselect all orders
      by clicking on the checkbox in the table header
    with a capturable order
      capture payment
      ship order from the orders index page
  with incomplete order
    can edit order
  test the 'Only show the complete orders' checkbox
    display or not incomplete order
  save the filter params
    when reloading the page
    and clear filters

```

~~While we are at it, we should update it to system spec too -> **done** in https://github.com/openfoodfoundation/openfoodnetwork/issues/8217~~

### Context

Release test automation and updating feature into system specs.

### Impact and timeline

An up-to-date, resilient build.

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #8216.

- updates orders spec into a system spec
- adds test cases

#### What should we test?

Green build.

#### Release notes

Adds automatic test coverage to `/orders` page

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice! :smile:

**Comment by filipefurtad0** [comment]
Thanks for moving to code review and the positive feedback! :-)

I was still going to address the second part (adding test cases). Should I have signaled this PR as draft instead @sigmundpetersen ? Anyway maybe we should merge after the second review, and I can work on top of that.

**Comment by sigmundpetersen** [comment]
> Should I have signaled this PR as draft instead @sigmundpetersen ? 

Yes, that could have been an option.
We have an issue right now in that the default column for new PR's has changed from Code Review to In Dev.
Previously the PR submitter could move it manually to In Dev if it wasn't quite ready yet.
The default column should be changed back to Code Review, this can be done next time someone submits a PR,
see discussion for reference here https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1629796117038500


> Anyway maybe we should merge after the second review, and I can work on top of that -> that's probably the best approach, as these get conflicts frequently 👍

Let's see what the reviewers think on this 👍

**Review by andrewpbrett — APPROVED** [review]
Merging this and working on top makes the most sense to me @filipefurtad0

**Pull request merged**
