### PR TITLE
Remove DFC Provider engine

### PR DESCRIPTION
**Pull request by pacodelaluna**
#### What? Why?

This code was merged by mistake by me initially.
My suggestion is to remove this code from master for now and we could add it later if necessary.

#### What should we test?

Nothing to test, the engine was not used.

#### Release notes
- Remove DFC Provider engine

Changelog Category: Technical changes

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]

**Comment by pacodelaluna** [comment]
@andrewpbrett I rebased to fix the conflict on `config/routes` file but I still have a failing check on codecov side, I removed tests but I also removed the related logic, not getting the issue yet.

**Comment by andrewpbrett** [comment]
@pacodelaluna I wouldn't worry about the failing codecov check, we're still not sure what it compares branches to a lot of the time.

**Comment by andrewpbrett** [comment]
@pacodelaluna I'm now thinking we should leave it in, since the auth issue has been addressed and we want to improve upon the DFC engine soon. Do you mind if we close this PR?

**Comment by sauloperez** [comment]
Unless there's any obvious drawback, having this engine although incomplete, may aid in making the discussions not so abstract. There'll be something concrete we can look at.

**Comment by andrewpbrett** [comment]
I'm going to close (partially to get it out of Code Review 😉) but feel to reopen if you feel differently @pacodelaluna.

**Pull request closed without merging**
