### PR TITLE
[BOM] Covers for the use of local default time on datepicker pre-selection

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

This came up on this build run https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3387236736/jobs/5627703970 - in this PR #https://github.com/openfoodfoundation/openfoodnetwork/pull/9924 - but I could observe it in my local system as well

On the BOM page, the datepicker pre-defines a data range which uses the local system time as a reference. This causes the spec to fail due to discrepancies in time zones.

This PR adds a workaround, defining the system time, to account for this behavior.

#### What should we test?

Green build.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
We'll have a rubocop offense due to the use of `Date.today`. Perhaps there is a better way to address this issue.

**Comment by jibees** [comment]
Oh thanks @filipefurtad0 !
Actually, I think that `prev_day(1)` in my code on PR https://github.com/openfoodfoundation/openfoodnetwork/pull/9924 is wrong. I'll correct this.
Using a date without a timezone is not a good idea as well. 
To me, the right solution is to synchronize the timezone for both capybara and cuprite in order to use the same.

**Review by mkllnk — COMMENTED** [review]
Is this now obsolete with JB's other PR?

**Comment by filipefurtad0** [comment]
> Is this now obsolete with JB's other PR?

Agree, this one is obsolete. Closing, thank you!

PS: I could not solve my "challenge" though, which was to make sure the pre-filled in date on the date picker is the zone date, and not the system date... But I can dwell on this elsewhere :sweat_smile:

**Pull request closed without merging**
