### PR TITLE
Show invoice number on invoices

### LINKED ISSUE #11052: [Invoices] Invoice number not visible on the invoice
## Description

Follow up of #10532.

The invoice number is not visible on the invoice.

## Expected Behavior

The invoice number should be visible in the header of the invoice.

## Actual Behaviour

It's not visible.

## Steps to Reproduce

1. Create an invoice.
2. Look at it.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #11052

#### What should we test?

- described on #11052
- 

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by mkllnk** [comment]
This seems to be a draft, not ready for review. Moving.

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Review by jibees — COMMENTED** [review]
Shouldn't we add some specs to check if invoice number is well displayed?

**Review by mkllnk — APPROVED** [review]

**Comment by RachL** [comment]
@abdellani I think we can remove the "TAX INVOICE" + order number as we already have the info above.

image

Also linking this conversation to understand how we want to deal with issue numbers on first release: https://openfoodnetwork.slack.com/archives/C04MR8R7078/p1689689936299919

Moving back to in dev in he meantime.

**Review by rioug — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @abdellani 

Invoice number is now being displayed on invoices:

Regular invoice
image

Alternative invoice
image

Disabling the feature displays invoices as before:

Regular invoice
image

Alternative invoice
image

Thank you!! :muscle: 
Merging.

**Pull request merged**
