### PR TITLE
#715: Add missing strings for en-GB locale.

### PR DESCRIPTION
**Pull request by pmackay**
Fix for #715. Tests passed here: https://buildkite.com/open-food-foundation/uk-branches/builds/25.

### CODE REVIEW

**Comment by pmackay** [comment]
@RohanM @oeoeaio please could you check and merge if OK?

**Comment by pmackay** [comment]
Also is the travis-ci stuff being maintained still?

**Comment by oeoeaio** [comment]
pinging @mkllnk

**Comment by mkllnk** [comment]
Cool. Thanks for the PR. But we should fix the underlying problem as well. Javascript doesn't use a fallback language file yet.

**Comment by pmackay** [comment]
So would it be better to have the `en-GB` file only contain overrides? Does Rails find strings in a fallback file already?

Is there any way to know what strings are used in JS and which in Rails?

**Comment by mkllnk** [comment]
> So would it be better to have the `en-GB` file only contain overrides?

I'm not sure. From a developer view, I would think so, yes. But Transifex would always display that the translation is not complete. If you are using that trigger to commit translations automatically, the incomplete translations get never committed.

Rails has several settings to judge missing translations as an error or not.

> Does Rails find strings in a fallback file already?

Yes, it does. It is possible to deactivate that behaviour. But we included only one language file in Javascript so far. It should be easy to add a default language. I planned that at some point, but I don't think that it has a separate issue. You are welcome to open one.

> Is there any way to know what strings are used in JS and which in Rails?

Not that I know of. Of course you could use grep to look for calls of the `t` alias `translate` function or in Javascript the `t` filter (angular).

**Comment by pmackay** [comment]
@mkllnk could you describe a bit more how the translation strings are fed into JS? I've updated UK staging with this merge (https://buildkite.com/open-food-foundation/uk-deployment/builds/40#a4129347-766f-40e1-a0ff-ff4d7fb0548c) but https://staging.openfoodnetwork.org.uk/#/ is still showing `label_login`. Is there something missing that it isnt picking up the `en-GB` strings? 

>But we included only one language file in Javascript so far.
Could it relate to this? What does this mean?

**Comment by mkllnk** [comment]
Interesting. You can follow the [instructions to change the language](https://github.com/openfoodfoundation/ofn_deployment/wiki/Setup#languages). But in your case, I thought the asset pre-compilation during deployment should pick the newer file up. The locale is included as asset `app/assets/javascripts/darkswarm/i18n.js.erb`.

**Comment by pmackay** [comment]
@mkllnk those instructions worked, which is great! However is the file deletion step not in the deploy scripts that Buildkite runs? It would be much better if deployment could handle this reliably.

**Comment by mkllnk** [comment]
> However is the file deletion step not in the deploy scripts that Buildkite runs?

No, it isn't. And the deletion is just a workaround. If you do that during the deploy-step, the site won't have Javascript available for the time of the asset compilation. The pre-compilation should pick-up the language change. But I don't know why it doesn't.

**Comment by pmackay** [comment]
Those instructions delete the JS files and then do asset compilation - what's the difference?

**Comment by mkllnk** [comment]
@pmackay You can customise your deployment script. That is `.git/hooks/post-receive` in your app folder. Just add the line for deletion if you like. We should solve the more general problem with the pre-compilation, but I don't know how long that will take.

> Those instructions delete the JS files and then do asset compilation - what's the difference?

The difference of deleting the file first? That the deleted files are in use by a production instance. We are working in the same folder unlike the Ansible deploy scripts. And the compilation can take some minutes if there is a lot to do. I'm not sure if I got your question right.

**Pull request merged**
