### PR TITLE
prevent loading the reporting module if already loaded [dev environment]

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

This PR is created after the [discussion](https://github.com/openfoodfoundation/openfoodnetwork/pull/10145)
I described the details on this [comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/10145#issuecomment-1361045969)

#### What should we test?

- edit the code
- refresh the browser
- -> error
- refresh a second time.

Screencast: https://user-images.githubusercontent.com/16113997/208862989-08b20c10-6b08-4127-94ab-838db8c1ce82.mp4
The link used in the screencast: http://localhost:3000/admin
The edited file: `app/constraints/feature_toggle_constraint.rb`
 

#### Release notes

Changelog Category:  Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
Unfortunately, specs are failing... 😭

**Comment by jibees** [comment]
And I still have the error with that fix (editing a controller)

**Comment by abdellani** [comment]
@jibees 
I updated my fix,  and the tests passed successfully now.
I  only added another condition `&& defined?(::Reporting::Errors)`, but to be honest I don't know exactly why this fixed the issue.

Can you please confirm on your end?

**Comment by jibees** [comment]
> Can you please confirm on your end?

Much better, for sure. Will review it and merge it. Thanks! 🙏 ☺️

**Review by jibees — APPROVED** [review]
This should do the trick. Very helpful thanks. 

We still don't know the original issue (why this appear recently), but let's be pragmatic: merging!

**Pull request merged**
