### PR TITLE
Move map icons to /public

### LINKED ISSUE #6829: Group map only showing "+1" map pointer
## Description

Group maps are not displaying pointers when there is only 1 hub per address anymore. As a result, a lot of maps are empty.

## Steps to Reproduce

Empty group maps: https://www.coopcircuits.fr/groups/fleuve-de-liens#/map or https://openfoodnetwork.org.uk/groups/monlocalfood#/map

Map with only "+1" : https://openfoodnetwork.org.uk/groups/biodynamic-association-licensees#/map or https://openfoodnetwork.ca/groups/orillia-fairgrounds-farmers-market#/map

## Workaround
None ? The main map can be used though

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.5.6
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6829 

This moves the map icons to `/public` for the [reasons](https://github.com/openfoodfoundation/openfoodnetwork/pull/6885#pullrequestreview-591202296) that Matt points out.

After deploying, we will need to run `Rails.cache.clear` on all managed instances, and include a note that non-managed instances should do the same. 

#### What should we test?

AU staging has a [group](https://staging.openfoodnetwork.org.au/groups/new-group-222#/map) that should display one of the missing icons. With `master` deployed (and, probably, after running `Rails.cache.clear` since AU currently has the fix deployed to it and therefore has the new URL), the icon does not appear and there should be an error in the console for the 404 looking for it. 

After deploying this PR, and again running `Rails.cache.clear`, the icon should appear and there should be no error in the console.

It would be even better if we found/made a group on a staging server that had multiple different icons displayed.

#### Release notes

Fixed a bug where map icons were not displaying on the Groups map (it would only show the "+1" icons).
 

Changelog Category: User facing changes

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Review by Matt-Yorkley — COMMENTED** [review]
Hmmm... we might need to think about this cached serializer and how it's actually working.

So there are two ways we can serve images; one is to keep them under `assets/`, in which case they will be precompiled and will have fingerprints added to the filenames. The other is to move them somewhere under `public/`, in which case they can be accessed normally and will not have fingerprints.

In this case we're serving these image links over the API, and we're now rendering those URLS with fingerprints added. But... if the timing of the cache-invalidation is not in sync with changes to the images we could end up with broken links again. Do you see what I mean? A change in an image's fingerprint would not trigger a cache-reset on those enterprise objects, so the cached values could remain after they've become stale.

I wonder if this would be a problem or not? The solution in that case would be to move the icons to something like `public/map_icons/*` and update the URLS to make sure we _don't_ use fingerprints. What do you reckon? Am I overthinking this?

**Comment by andrewpbrett** [comment]
@sauloperez sorry I should have marked this as a draft; I wanted to be able to deploy it to a staging server but it wasn't quite ready. 

@Matt-Yorkley I think you're right, even if it is a little overcautious, since it seems like it will be rare that these images change. My only concern is a vague sense that we're losing out on asset pipeline goodness and standardization, especially as we upgrade Rails. 

I'll try moving them to a `public` folder and if that works on UK staging, I think we go with that for now, since this is an S2  after all.

**Comment by andrewpbrett** [comment]
I deployed to AU staging after moving the images to `/public` but still don't see them showing up. I just realized that it's probably because the enterprise serializer is cacheing the image URL (duh) - so we'll have to invalidate the cache for this test to work.

**Comment by andrewpbrett** [comment]
Okay, with that last commit, I confirmed that a group that was previously not finding the assets is now showing the icons, on staging-UK. However, the test on AU staging still doesn't show the icons. I don't have access to that staging server to test if doing a `Rails.cache.clear` will get them to appear, though.

**Comment by andrewpbrett** [comment]
@mkllnk did `Rails.cache.clear` on AU staging and the icons appeared correctly after that. So I think that the easiest thing is to just mark this as a prod-test where for all managed instances, we run that command in the console, and include a release note that non-managed instances will have to do the same.

**Review by Matt-Yorkley — APPROVED** [review]
Great. We can remove those icons from the /assets path as well, right?

**Comment by andrewpbrett** [comment]
> We can remove those icons from the /assets path as well, right?

Good catch, just squashed a commit to do that.

**Review by sauloperez — APPROVED** [review]

**Pull request merged**
