### PR TITLE
Fix/text overlay with long unit name

### LINKED ISSUE #11967: Long item unit names can clash with added quantity in shop
## Description

Text can become unreadable when two labels are overlapping. See Screenshot.

## Expected Behavior

We could limit the length of the item description displayed or introduce line breaks.

## Actual Behaviour

The text overlays and becomes unreadable.

## Steps to Reproduce

1. Set up a product with items as unit.
2. Enter a very long unit name like in the screenshot.
3. Visit the shop with a small screen, like mobile.

## Animated Gif/Screenshot

IMG_3644

## Workaround

Shorten the unit name.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by Isaac-alencar**
#### What? Why?

- Closes #11967 

Long item unit names was overlaying with added quantity in shop making both labels illegible. I fixed this with CSS by hiding part of the long text with ellipsis so it does not clash with added quantity in shop label.

#### What should we test?

(Same as to reproduce the initial bug)
- Set up a product with items as unit.
- Enter a very long unit name like in the screenshot.
- Visit the shop with a small screen, like mobile.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes

Long unit name no longer overlays added quantity in shop

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Thank you!

**Review by rioug — APPROVED** [review]
Nice, thanks for your help !

**Comment by drummer83** [comment]
Hi @Isaac-alencar,
Thank you so much for working on this! :pray: 

I staged this PR to two of our staging servers to test it. However, I can't really see a difference - to me it looks like somehow the <span> you added to the code is not being generated? I added a screenshot to show what I mean.

Could you have a look at what's happening here?

image

Thanks again! :smile:

**Comment by Isaac-alencar** [comment]
> Hi @Isaac-alencar, Thank you so much for working on this! 🙏
> 
> I staged this PR to two of our staging servers to test it. However, I can't really see a difference - to me it looks like somehow the you added to the code is not being generated? I added a screenshot to show what I mean.
> 
> Could you have a look at what's happening here?
> 
> image
> 
> Thanks again! 😄

I'm not quite sure, but it seems that my changes were not applied. The text you highlighted on the screen shot should have be into a span according the changes I've made

**Comment by mkllnk** [comment]
I staged this again to test and I couldn't see the change in HTML structure to start with. The span tag wasn't there. Then I remembered that we cache parts of the shopfront and ran `Rails.cache.clear` in the console. After reloading the page it looked good.

### Before

Screenshot from 2024-01-19 09-33-00

### After

Screenshot from 2024-01-19 09-36-12

This is an improvement but I think that it cuts off a little bit too much. It could go past the price column and just needs to stop before the add button. Do you think that you can adjust that?

**Comment by Isaac-alencar** [comment]
I'm not sure if its is possible (at least with CSS), but I'll do my best. I'll keep you posted! Sounds good?

**Comment by drummer83** [comment]
If you're comfortable with it, it's no problem changing more than CSS, I think.

**Comment by Isaac-alencar** [comment]
> If you're comfortable with it, it's no problem changing more than CSS, I think.

Hi!

Sorry for delaying on this answer. I was not able to make the last adjusts neither with CSS nor chunking the text with Ruby 😢.

**Comment by mkllnk** [comment]
That's okay. I'm moving this to Test Ready.

**Comment by drummer83** [comment]
Hi @Isaac-alencar,
Thanks again for working on this!
And thanks @mkllnk for providing the hint regarding the cache. :+1: 

Below you can see two videos of the behavior for very long unit names before and after your PR.

Before:

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/8d3ec0e9-a081-44d5-b41d-8a9badca3b2a

After:

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/5799232b-44a8-44a0-811f-9c4394efe46b

And here you can see two examples (both AFTER your PR) for normal/typical unit names. 480 px is a common screen width on old devices.

Wider screen and short unit name with no danger of overlap:
image

Narrow screen (480 px) and short unit name, also no danger of overlap, but unit is heavily cut off.
image

## Conclusion
On the one hand we have great improvement here for very long unit names. There is no overlapping anymore. :+1: 
On the other hand the space for the unit name gets really narrow on very small screens, this also affects short unit names which didn't cause any overlap before.

I am hesitant to merge this one, because we should have very little very long unit names only. For those it a clear improvement. But we have a vast majority of short unit names. And for those we see a regression because the space is confined even though it's not required.
It's more tricky than we thought! :thinking: 

What do you think @openfoodfoundation/train-drivers-product-owners, @mariocarabotta?

**Comment by sigmundpetersen** [comment]
@RachL @kirstenalarsen @mariocarabotta any feedback on the above? ☝️

**Comment by mariocarabotta** [comment]
> @RachL @kirstenalarsen @mariocarabotta any feedback on the above? ☝️

any chance we can make use of that white space? seems like the container is shrinking too much as the width scales down. Would it be possible to tweak the column itself to always use as much white space as possible?

301479281-f3d191e3-74c6-4fca-ac11-6d68d41f23a6

**Comment by sigmundpetersen** [comment]
Ok, moving back to In Dev.
@Isaac-alencar would you be up for looking at that whitespace on smaller screens?

**Comment by Isaac-alencar** [comment]
> Ok, moving back to In Dev. @Isaac-alencar would you be up for looking at that whitespace on smaller screens?

Sure! I can do that

**Comment by RachL** [comment]
Hi @Isaac-alencar it's been a long time without any update here. I'm sorry I'm only finding out about this PR today. Are you still able to do the change requested?

**Comment by RachL** [comment]
Closing here, we can reopen if needed :+1:

**Pull request closed without merging**
