### PR TITLE
Do not fetch VOs with deleted variant

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

This came up while finding the root cause of https://github.com/openfoodfoundation/openfoodnetwork/issues/6727 and can be shipped as a separate improvement.

Right after we fetch the variant overrides we filter out in Ruby the ones with a deleted variant so it's a waste of resources. The fundamental difference is that `#includes` and
`#references` results in LEFT JOINs, whereas `#joins` results in INNER JOIN, and because there's a default scope on `deleted_at IS NULL`, these are not included in the result set.

Before:

```sql
SELECT *
  FROM "variant_overrides"
  LEFT OUTER
  JOIN "spree_variants"
    ON "spree_variants"."id"              =  "variant_overrides"."variant_id"
   AND "spree_variants"."deleted_at" IS NULL
  LEFT OUTER
  JOIN "spree_products"
    ON "spree_products"."id"              =  "spree_variants"."product_id"
   AND "spree_products"."deleted_at" IS NULL
 WHERE "variant_overrides"."permission_revoked_at" IS NULL
   AND "variant_overrides"."hub_id" IN (
    SELECT "enterprises"."id"
      FROM "enterprises"
    INNER
      JOIN "enterprise_roles"
        ON "enterprise_roles"."enterprise_id" =  "enterprises"."id"
    WHERE (enterprise_roles.user_id          =  ?)
      AND (sells                             != 'none')
 ORDER BY name)
```

After:

```sql
SELECT "variant_overrides".*
  FROM "variant_overrides"
 INNER
  JOIN "spree_variants"
    ON "spree_variants"."id"              =  "variant_overrides"."variant_id"
   AND "spree_variants"."deleted_at" IS NULL
 INNER
  JOIN "spree_products"
    ON "spree_products"."id"              =  "spree_variants"."product_id"
   AND "spree_products"."deleted_at" IS NULL
 WHERE "variant_overrides"."permission_revoked_at" IS NULL
   AND "variant_overrides"."hub_id" IN (
    SELECT "enterprises"."id"
      FROM "enterprises"
    INNER
      JOIN "enterprise_roles"
        ON "enterprise_roles"."enterprise_id" =  "enterprises"."id"
    WHERE (enterprise_roles.user_id          =  ?)
      AND (sells                             != 'none')
 ORDER BY name)
```

#### What should we test?

This is covered in the test suite by spec/controllers/admin/variant_overrides_controller_spec.rb:72. It keeps
passing so we're good to go. Green build :green_apple: .

#### Release notes

Don't fetch variant overrides with deleted variants
Changelog Category: Technical changes

### CODE REVIEW

**Review by Matt-Yorkley — COMMENTED** [review]
Looks great :+1:

There's a couple of Variant Override specs that are failing, and I haven't seen them fail before..

**Review by luisramos0 — APPROVED** [review]

**Comment by sauloperez** [comment]
I think I managed to tame the beast now :sweat: There's room for improvement in terms of N+1s but I got to stop now or it'll scope-creep too much. Besides, VOs will be removed in the future and this is not among our performance hotspots anyway.

**Review by Matt-Yorkley — APPROVED** [review]
TBH, I hope some day we can move to a simpler and more granular bulk-update strategy that doesn't try to process lots of creates/updates/deletes all at the same time, and :fire: all these ModelSet classes.

Buuuuuut.... not today.

LGTM :+1:

**Comment by sauloperez** [comment]
yes, we are aligned on both: :fire: but not today :laughing:

**Comment by sauloperez** [comment]
I'm merging because this will be tested as part of #6789 anyway.

**Pull request merged**
