### PR TITLE
Bump Nokogiri

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I think I just fixed our only critical severity security issue :tada:
https://github.com/openfoodfoundation/openfoodnetwork/network/alert/Gemfile.lock/nokogiri/closed

We can remove deface from spree_core now that we dont use spree_backend and spree_i18n and better_spree_paypal dont use deface. This is done in https://github.com/openfoodfoundation/spree/pull/42 for current spree 2-0-4 and in https://github.com/openfoodfoundation/spree/pull/42 for the next spree 2-1-0.

After removing deface from spree we can just remove nokogiri from our concerns and let it upgrade through the other gems that depend on it :tada: 

The paperclip requirement in spree_core changed but our version 3.4.2 is good for it, no paper_clip upgrade in this PR.

#### What should we test?
Maybe a sanity check? I think this is a fundamental piece of software so we would see problem in the build if there were any.

#### Release notes
Changelog Category: Fixed
Fixed long standing critical security issue in OFN related to a dependency with security problems :tada:

### CODE REVIEW

**Comment by luisramos0** [comment]
This can only go after the spree PRs are merged.

**Comment by luisramos0** [comment]
ready for review.

**Comment by luisramos0** [comment]
if you have reviewed this PR you can probably quickly review this one https://github.com/openfoodfoundation/openfoodnetwork/pull/5194 that updates the spree revision on the 3-0-stable version.

**Comment by luisramos0** [comment]
It just my mistake!!! the require in spree_core changed but our version remains the same :see_no_evil: 
No paper_clip change here.
image

**Comment by filipefurtad0** [comment]
Hi @luisramos0,

I performed a basic sanity check:
- Creating hub/customer
- Setting a product/OC/payment and delivery method
- Making a cash-purchase
- Getting all the right emails during the process.

All good - moving to ready to go.

**Pull request merged**
