### PR TITLE
Adjust user creation syntax

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Related to https://github.com/openfoodfoundation/openfoodnetwork/pull/4153 which was supposed to fix 2 bugs, but only fixed one of them.

`#skip_confirmation!` can't be chained... :see_no_evil: 

#### What should we test?

Dev test only. It'll need to be checked when deploying during a fresh install.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Ok, I just tested and readjusted this to fix another error caused by validation callbacks calling `downcase!` on the email ENV var, where it hadn't been used with `#dup`, so failed with a "can't modify frozen string" error. It looks like it's all working now... :roll_eyes:

**Comment by sauloperez** [comment]
aha! that's exactly the error the Travis CI for ofn-install was reporting

**Comment by sigmundpetersen** [comment]
This is ready right? 

Is this something we need to keep a note of somewhere:
> It'll need to be checked when deploying during a fresh install.

**Comment by Matt-Yorkley** [comment]
I tested it in Vagrant this morning. Ready to go :+1:

**Pull request merged**
