### PR TITLE
Ensure dynamic modals always use selected locale

### PR DESCRIPTION
**Pull request by dacook**
### What? Why?

- Raised in https://github.com/openfoodfoundation/openfoodnetwork/pull/11565#issuecomment-1746814011

Some reflexes were displaying content in the _**instance default**_ language, rather than the _**user-selected**_ language. I've added a general solution for this (similar to what we do for normal web requests), which now ensures _all_ reflexes are in the selected language.

### What should we test?
* Log in to an instance with multiple languages.
* Select a non-default language
* It doesn't matter if `admin_style_v3` enabled or not.

Note: I found that `es` didn't have translations for some parts, which caused some text to show in English. So it might be helpful to test in another language that has better translations. If at least part of the updated area is in the right language, then it should be ok.

- [x] products_v3: load products and inspect column headers
- [x] admin/enterprise: add unregistered enterprise manager
- [ ] admin/enterprise: delete whitelabel logo. There was an unrelated error on dev (`WhiteLabel#remove_logo: undefined method 'capture_haml'`), but it seems to be fine in staging. 🤷 let's see how it goes in staging.
- [ ] admin/orders: these were correct before, but have been updated with general solution so it's worth checking)
    - capture
    - ship
    - resend_confirmation_emails 
    - send_invoices
 - admin/orders: these didn't have correct language before
    - [x] bulk_invoice
    - [ ] cancel_orders

#### Screenshots example
With system default of `en`, and user-selected `es`.
Before, the dynamic modals were in English:
Screen Shot 2023-10-11 at 10 54 57 am
Screen Shot 2023-10-11 at 10 53 08 am
Screen Shot 2023-10-11 at 10 54 00 am

Now they are in Spanish as expected:
Screen Shot 2023-10-11 at 10 55 04 am
Screen Shot 2023-10-11 at 10 55 22 am

### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
So much better than the old approach. And obviously a common practice. Thank you!

**Comment by drummer83** [comment]
Hi @dacook,
Thanks for this one.  I've come along some issues and I'm not sure I am testing the right thing here. Could you please have a look and provide a bit more information about what and how to test? Thanks! :pray: 

I've tested on staging AU, default language in staging is en_AU, I selected FR for testing - some screen shots of the 'before' state are taken from German production server.

## Reflex errors
### Error 1
First of all I had an error when trying to open the product v3 page (before and after staging):
image

I switched off admin v3 and continued.

### Error 2
Even with admin v3 switched off completely I got the error when deleting the white label logo:
image

In fact, after refreshing the page I could see that the image got removed but I didn't get to see the flash message.

## Test cases

| | Before | After |
| - | - | - |
| admin/products: Columns selector | `Columns` & `Save as default` not using locale :x: image | not fixed :x: |
| admin/enterprise: Add unregistered enterprise manager | no issues found :heavy_check_mark: | still ok :heavy_check_mark: |
| admin/enterprise: Delete white label logo | :question: Reflex error | :question: Reflex error |
| admin/orders: Capture payment, ship order | Order state, payment state & shipping state not using locale :x: image | Fixed! :heavy_check_mark: image |
| admin/orders: Resend confirmation emails, send invoices | no issues found :heavy_check_mark: | still ok :heavy_check_mark: |
| admin/orders: Bulk print invoices | Modals not using locale :x: image | fixed :heavy_check_mark: image |
| admin/orders: Bulk cancel invoices | Order state, payment state & shipping state not using locale :x: image | fixed :heavy_check_mark: image |
| admin/orders: Flash error messages for capturing payment, shipping order | :question: How to make the tasks fail? :question: | :question: |

## Summary
- Some things got fixed! :muscle: 
- Some things I couldn't reproduce! :no_good_man: 
- Some things are still not fixed! :sob: 
- Some things I couldn't test due to Reflex error! :fog: 
- Some things I don't know how to create (flash errors)! :question: 

I'll move this back to In Dev, hoping that you can understand my notes. Please let me know how to proceed and get in touch if anything is unclear.
Thanks! :pray:

**Comment by dacook** [comment]
Great job, thanks Konrad for all these details!

> **Error 1**
> First of all I had an error when trying to open the product v3 page (before and after staging):

Thanks for reporting that, I haven't seen that happen before. I wasn't able to find any errors logged in bugsnag at that time. If you see that message happen again, you can open the devtools console, and there should an error message there that you can copy (that will be really helpful for debugging).

> admin/products: Columns selector (covered in #9509)

This might be unrelated. I've not given much attention to this screen because we are going to replace it with products_v3. Let's leave it with that issue.

> 3. admin/enterprise: Delete white label logo
>   ❓ Reflex error

Hmm that's annoying. It's probably fine to assume all is working (based on other test results), and deal with this in a separate issue..

> 8. admin/orders: Flash error messages for capturing payment, shipping order
>    ❓ How to make the tasks fail? ❓

I looked into the code and found:
* **Payment** fails for order if:
    * payment not required, 
    * there is no "pending_payment" (I guess that means it has reached the payment step of checkout), or 
    * there is a payment gateway error
* **Shipping**... hmm actually it looks like there's a bug, I don't think the message will show if shipping fails 😞 . 
    In fact there doesn't seem to be any error handling around the shipping state, so I suspect that it never fails.


----
So I think we're nearly good to go, but do you think you'd be able to have a go at replicating a payment failure with the bulk actions menu? I couldn't find a spec for this 😞

**Comment by drummer83** [comment]
Hi @dacook,
here is the log of the Reflex error:
grafik

**Comment by drummer83** [comment]
> So I think we're nearly good to go, but do you think you'd be able to have a go at replicating a payment failure with the bulk actions menu? I couldn't find a spec for this 😞

Hmm, no success here.

There is no bulk action for capturing payments. Only cash payments can be captured on the /admin/orders page. And this is on a one-by-one basis using the :heavy_check_mark: button next to the order. I have no idea how to make this fail.

I also tried a failing Stripe payment on the /payments page. But due to https://github.com/openfoodfoundation/openfoodnetwork/issues/9048 there is no flash message for failing Stripe payments in the back office.

Paypal payments are not possible in the OFN back end.

Sorry - I'm running out of options. :laughing:

**Comment by dacook** [comment]
Thanks Konrad.

> Error 1

Thanks for this info. I tried to replicate this by creating a non-admin user, but wasn't able to. I suspect it's due to corrupt data on staging, so have added a commit to gracefully handle this. Could you please try again, and if it's still a problem can you share the specific username and instance you're testing with?

> Error 2

Would you be able to create a new issue for fixing this?

> capturing payments. I have no idea how to make this fail.

Sorry, I don't know either. The code change here was minimal and it's using the same general method that has been tested elsewhere, so do you think it would be ok if we just proceed as-is?

**Comment by drummer83** [comment]
Hi David @dacook,
Thanks for following up!

> > Error 1
> 
> Thanks for this info. I tried to replicate this by creating a non-admin user, but wasn't able to. I suspect it's due to corrupt data on staging, so have added a commit to gracefully handle this. Could you please try again, and if it's still a problem can you share the specific username and instance you're testing with?

Is it possible that this issue got fixed when I merged #11647? Even without staging your latest changes it is now working. 
After staging it's working as well. So this one is solved. :heavy_check_mark: 

> > Error 2
> 
> Would you be able to create a new issue for fixing this?

Sure. :+1: 
 
> > capturing payments. I have no idea how to make this fail.
> 
> Sorry, I don't know either. The code change here was minimal and it's using the same general method that has been tested elsewhere, so do you think it would be ok if we just proceed as-is?

Yeah, let's proceed. :+1:

**Comment by drummer83** [comment]
Update: Issue for Error 2 created here: #11665.

**Comment by drummer83** [comment]
Moving to Ready To Go and waiting for your final confirmation to merge. Please go ahead, if you agree.

**Comment by dacook** [comment]
> Error 1
> this one is solved. ✔️

Hooray!

> Update: Issue for Error 2 created here: https://github.com/openfoodfoundation/openfoodnetwork/issues/11665.

Thank you!

> Moving to Ready To Go and waiting for your final confirmation to merge. Please go ahead, if you agree.

Merging!

**Pull request merged**
