### PR TITLE
6942 fix payment method fee bug

### LINKED ISSUE #6942: Entering "'20.0%'" as payment method fee causes server error
## Description

Updating a payment method can cause a server error when entering invalid values.

It looks like someone tried to give a 20% discount by entering that value.

## Expected Behavior

Invalid values should not be allowed or there should be a proper error message.

## Actual Behaviour

It shows the snail.

## Steps to Reproduce

1. Edit a cash payment method.
2. Select the "per item" calculator.
2. Enter `'20.0'` with the single quotes as fee amount.
3. Save.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

The only figures that should be allowed are:
- numbers 0123456789
- decimal point .
- negative sign -

The error message should read:
Invalid input. Please use only numbers. For example: 10, 5.5, -20

## Error in OpenFoodNetwork

**ArgumentError** in **spree/admin/payment_methods#update**
invalid value for BigDecimal(): "'-20'"

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/601f42015495cb001730e02f?event_id=601f428a0069977abd1b0000&i=gh&m=ci)

## Stacktrace

    app/models/spree/preferences/preferable.rb:119 - BigDecimal
    app/models/spree/preferences/preferable.rb:119 - convert_preference_value
    app/models/spree/preferences/preferable_class_methods.rb:26 - block in preference
    lib/spree/localized_number.rb:29 - call
    lib/spree/localized_number.rb:29 - block (2 levels) in localize_number
    app/controllers/spree/admin/payment_methods_controller.rb:43 - update

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/601f42015495cb001730e02f?event_id=601f428a0069977abd1b0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by meronokbay**
#### What? Why?

Related to #6942

This validates the payment method fee and shows a flash message to the user if they input a value that isn't a number.

#### What should we test?

Edit a cash payment method and set the payment method fee to be a non-number value like 'hello' and try to submit the form.

#### Release notes

Validate payment method  fee input

Changelog Category: User facing changes

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]
This looks like a good approach. What was the original cause of the 500 error? Would it work instead to use something like `validates_numericality_of` on the model instead of handling it in the controller?

**Comment by meronokbay** [comment]
> This looks like a good approach. What was the original cause of the 500 error? Would it work instead to use something like `validates_numericality_of` on the model instead of handling it in the controller?

The error is caused by this line `BigDecimal(value.to_s).round(2, BigDecimal::ROUND_HALF_UP)` in `preferable.rb`. Providing a non-number value as payment method fee causes an exception here. I tried adding `validates :amount, numericality: true` in the model and it was still causing the same error because the code in preferable.rb is being called before hitting the model validations, so I think that approach won't work.

**Comment by andrewpbrett** [comment]
> the code in preferable.rb is being called before hitting the model validations, so I think that approach won't work.

Got it, thanks @meronokbay! This just needs a second review and then it can go to test ready.

**Review by mkllnk — APPROVED** [review]
Nice!

**Comment by filipefurtad0** [comment]
Hey @meronokbay ,

Thank you for addressing this issue!

I've reproduced this bug before staging your PR on the staging server. After staging I've tested:

1) a `cash/check` payment method, in combination with a flat rate calculator (per order or per item)

Peek 2021-09-09 13-25

Using the percentage symbol (for example) now does not break the page - the banner is displayed as expected :+1: 

2) other payment methods as well, like StripeSCA and Paypal in combination with a flat rate calculator (per order or per item). These seem to break the page as well -> Error 500

Peek 2021-09-09 13-26


3) Tested other calculators, other then flat-rate calculators  - like Flexible Rate, for example - with a cash payment method -> Error 500
Invalid characters break the page in these cases, when invalid characters are introduced in the fields of other calculators

4) This issue reminded me to test `shipping methods` as well. When editing shipping methods we can see that the issue is reproducible too.

**Summary**

This PR fixes the issue for the combination in test case 1) -> so we should merge it :+1: 
However, the issue #6942 remains open, as the the test cases 2) 3) concern payment methods as well.

I'll open an additional issue for shipping methods (I don't think we have it, test case 4).

Thank you so much for this contribution :tada:

**Comment by meronokbay** [comment]
@filipefurtad0 thanks for pointing these out. I will work on them in the weekend.

**Pull request merged**
