### PR TITLE
add Mayhem for API as a github workflow

### PR DESCRIPTION
**Pull request by dlowe**
#### What? Why?

Added a github action to run [Mayhem for API](https://mayhem4api.forallsecure.com/) (which is a free automated testing tool for http APIs) against the v0 api: given the openapi spec and api server, it generates and runs random test payloads, looking for exceptional behavior.

Disclosure: working on this tool is my day job!

I also added a second path to the v0 spec, just so there would be a little bit more meat to the testing. I don't know how much this project cares about maintaining the API spec, but automating a Mayhem for API workflow also makes it much easier to keep the spec in sync with reality.

#### What should we test?

As with any github workflow, test results can be consumed through github. Alternatively, Mayhem for API also has a dashboard, over here: https://mayhem4api.forallsecure.com/mayhemheroes/openfoodnetwork.

To make it work in the upstream repo, there's a bit of out-of-PR effort to integrate:

 * sign up for a free mapi account, creating an openfoodnetwork organization
 * create a mapi service account within the openfoodnetwork organization
 * modify the mapi.yaml action in this PR to point at your mapi organization
 * add the service account's API token to github as a repository secret named MAPI_TOKEN

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — COMMENTED** [review]
Thanks for working on this.

So we need to create an account at https://mayhem4api.forallsecure.com, right?

Did the test pass on your fork?

I noticed that you added to the swagger.yml. Was that necessary to make it pass? That file is generated automatically and the changes would be reverted unless we change the code from which it's generated.

And have you seen the API v1? We are still working on it but it would make more sense for us to apply this action for v1.

**Comment by dlowe** [comment]
> So we need to create an account at https://mayhem4api.forallsecure.com, right?

Correct, to get the workflow to work 

> Did the test pass on your fork?

Yep! Here's an example run: https://github.com/mayhemheroes/openfoodnetwork/runs/6183235363?check_suite_focus=true

> I noticed that you added to the swagger.yml. Was that necessary to make it pass? That file is generated automatically and the changes would be reverted unless we change the code from which it's generated.

Oh, I missed that! Can you tell me how to generate the spec?

> And have you seen the API v1? We are still working on it but it would make more sense for us to apply this action for v1.

I did see it, but the v1/swagger.yaml file doesn't currently parse as openapi. Is that one also generated? If so, I think the generator needs some work to produce a valid spec. If you can point me at the generator, I'd be happy to take a crack at it (and get the mayhem integration pointed at v1).

Thanks!

**Comment by mkllnk** [comment]
I created the organisation `openfoodfoundation` and added a token to the repository secrets.

The specs are generated by running `bundle exec rswag`. You may need to set up the application first though. Let me know how you go.

**Comment by dlowe** [comment]
> I created the organisation `openfoodfoundation` and added a token to the repository secrets.

Hmm, the latest run is still not seeing a MAPI_TOKEN secret. Did you call it by a different name?

**Comment by mkllnk** [comment]
Strange, I added that as a repository secret:
Screenshot from 2022-04-29 15-13-48

I just generated a new token and updated Github. Could it be that Github is hiding it from your code? What does the last line here mean?

> Set up job
> Operating System
> Virtual Environment
> Virtual Environment Provisioner
> GITHUB_TOKEN Permissions
> Secret source: None

**Comment by mkllnk** [comment]
Let's see:
* #9149

**Review by mkllnk — APPROVED** [review]
Brilliant! Thank you for fixing our spec! Results are now public:

https://mayhem4api.forallsecure.com/openfoodfoundation/openfoodnetwork

**Pull request merged**
