### PR TITLE
Call matomo manually on asynchronous page visits

### LINKED ISSUE #10881: [Checkout] Metrics: 99% of users "exit" on the `/details` step
## Description

Sort of a duplicate of [this issue](https://github.com/openfoodfoundation/Analytics/issues/3). Bringing this over to this repo as a bug as discussed in delivery circle today.

Maybe related to https://github.com/openfoodfoundation/openfoodnetwork/issues/11599.

To a large extent, we're currently we're only able to track users on split-checkout till the `/details` step; after this, we observer exits to the order confirmation page.

For some reason, both customer support and myself are able to trigger the goal, and leave tracks through all the pages

## Expected Behavior

We expect to see this in the goals/funnels for UK-prod:

`/details` -> `/payment` -> `/summary` -> `/order_confirmation_page_URL` (GOAL trigger)

image

## Actual Behaviour

`/details` -> `/order_confirmation_page_URL` (no GOAL trigger)

image

## Steps to Reproduce

1. Log into https://openfoodnetwork.innocraft.cloud/
2. Visit the UK-prod dashboard (site=2)
3. Check the goal and funnel from `SC_complete_order_w_funnel_URL`
4. Visit UK-prod site and checkout
5. Were you able to trigger a conversion with your visit? (you might need to wait 24hrs) If yes, then why? If no, then why?
6. Notice the current metrics: 99% of users exit from `/details` to order confirmation

## Animated Gif/Screenshot

image

## Your Environment

* Version used: v4.3.9
* Browser name and version: Not clear
* Operating System and version (desktop or mobile): Not clear

## Possible Fix

No idea: just using this space to post the latest data from the month of May (till today):

image

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #10881

#### What should we test?

Matomo should register navigation events between checkout pages on form submissions.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley,

I've rebased the branch before staging. I can't say my testing is conclusive:

image

After checking out a few times I can state that:
- the app works as before (looks safe to merge)
- some visits are tracked (this was the case before, especially when running Matomo in preview mode)
- others are not; I've placed 5 orders but I see that only 2 got fully converted

It's difficult to really debug this asynchronously. Therefore I'd be in favor of:
- moving this PR to code review
- if all is good, merge and release 

Then compare results with the visits from prod.

What do you think?

**Review by mkllnk — APPROVED** [review]

**Comment by mkllnk** [comment]
Rebased for conflict resolution. Ready for testing.

**Review by filipefurtad0 — APPROVED** [review]
Adding a review to test the branch protection option :+1:

**Comment by filipefurtad0** [comment]
Hi @Matt-Yorkley ,

Seems the order placing did not really trigger the goals I'd expect:

image

Other data seems to flow in as before, so I don't see any risk of regression.

I'd still be up for putting this into prod, and see how data collection works with different setups... I'll move it to ready to go.

**Comment by Matt-Yorkley** [comment]
The change I made should send the standard `PageView` data for page navigations(?). What's the trigger for these custom events like `SC_complete_order_EVENT`?

**Comment by filipefurtad0** [comment]
If we exclude the funnel configuration, the goal should be triggered when:

image

If we check this on `preview mode`, it works fine; [here for example](https://github.com/openfoodfoundation/openfoodnetwork/pull/11022#issuecomment-1597183383), we see some conversions.

If don't use the preview mode, no conversions.

On the funnel: it basically adds additional conditions, so that the events are triggered, these are the conditions:

image

These events basically correspond to the `Next` button clicking, on each respective page.

EDIT to the previous testing notes:

image

Seems these events are now tracked... So it seems there is an improvement.

**Comment by filipefurtad0** [comment]
Ok, this change is now in production for about two weeks. I think it's safe to say that it introduced no regression:

image

image

But also, I can't spot an improvement, so I'll detach the issue and move it to all the things.

**Pull request merged**
