### PR TITLE
Remove spree_i18n dependency

### LINKED ISSUE #6426: Removespree_i18n
### What we should change and why (this is tech debt)
We should bring what's needed from https://github.com/openfoodfoundation/spree_i18n/tree/1-3-stable
I am not sure if these translations are even used but if they are, this may introduce some missing translations in OFN, must be tested. Anyway, this needs to be removed and cleaned up so we dont depend on translations on spree_i18n but only on entries coming from transifex.

### Context

Bye bye spree, left overs.

### Impact and timeline
I wonder if this dependency is even needed! Trying it out in a new PR.

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #6426 

#### What should we test?
We need to verify translations are available and that there are no missing translations in the app.

#### Release notes
Changelog Category: Technical changes
Removed dependency spree_i18n, it's not used.

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]
:tada:

**Comment by Matt-Yorkley** [comment]
I'm somewhat surprised we can just cut this without any negative effects...

**Comment by luisramos0** [comment]
Me too :-) i think we need to look for missing translations and also test
that toggling languages worka correctly.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
I'll have a go a this tomorrow :+1:  But I wonder if this PR would be a good opportunity to update/improve the automated testing of missing translations, see #2626. I mention this in the context of a recent S2 introduced by a missing translation.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley and Luis,

Checked the app throughout and found no new/unknown missing translations... I tried to cover both Ruby `t` method (the more common ones?) and JavaScript translations (date-pickers, for example).

This looks good to go.

**Pull request merged**
