### PR TITLE
Adding inverse_of

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Brings in some improvements to the definitions on associations from Spree `2-2-stable`. Explicitly defining the `inverse_of` on associations helps `ActiveRecord` figure out what it's supposed to be doing, especially across join tables.

See commit messages for links to the original Spree commits (with links to issues they fix and related discussions).

#### What should we test?

Green build.

#### Release notes

Changelog Category: Technical changes

Added missing `inverse_of` declarations on various associations.

### CODE REVIEW

**Review by sauloperez — COMMENTED** [review]
Have you checked this `inverse_of` aren't automatically handled by Rails? See https://github.com/rails/rails/pull/10886/files

**Comment by Matt-Yorkley** [comment]
Ah, interesting. It looks like it was added just before Spree moved to Rails 4.1. The docs say it tries to guess and isn't always right? Should we add it anyway, or close the PR?

**Comment by sauloperez** [comment]
I'd carefully the specifics cases Rails can't infer automatically and add only those.

**Comment by Matt-Yorkley** [comment]
Apparently it can fail in various cases: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Setting+Inverses

- `belongs_to` in join models
- associations with `:foreign_key` or `:through` options
- associations with custom scopes
- anywhere the class name isn't obviously the same as the association name (where `:class_name` option is used)

**Comment by Matt-Yorkley** [comment]
Yeah, the inverses are definitely missing in lots of cases and should be manually defined:
```
Loading development environment (Rails 4.2.11.3)
irb(main):001:0> Spree::TaxRate.reflect_on_association(:zone).has_inverse?
=> false
irb(main):002:0> Spree::TaxRate.reflect_on_association(:tax_category).has_inverse?
=> false
```
If these were being guessed correctly by Rails, they would return something like `:tax_rate` :point_up: eg:
```
irb(main):004:0> Spree::Zone.reflect_on_association(:tax_rates).has_inverse?
=> :zone
```

**Review by sauloperez — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
:sunglasses:

**Pull request merged**
