### PR TITLE
Bugfix/6558 validate social links

### LINKED ISSUE #6558: Social links are not validated
## Description

In the **enterprise settings>social** the links for social media are not validated. The user can add the link in different formats and it cause problems when the link is generated in the ui.

## Expected Behavior

The user can add the link in any format (depending on the social network) and the system process it and save just the username for each social.

**Facebook**
 https://www.facebook.com/username -> username

**LinkedIn**
https://www.linkedin.com/in/username -> username

**Twitter**
 https://twitter.com/username -> username

## Actual Behaviour

If the user add https://www.facebook.com/username to the facebook field, it will ve converted into https://www.facebook.com/https://www.facebook.com/username on the frontend

## Steps to Reproduce

1. Go to _enterprise settings_ and click on _social_ tab
2. Add a link in the incorrect format to a social field
3. Open the enterprise front end
4. Click on _contact_ tab and click on the social icon you want to test

## Workaround

The user can just add the link how it is supposed to, but there is no validation for that.

## Severity

**bug-s4**
It could cause a problem if the social link is added in a wrong way, but if the user add it in a correct way, it works. To solve this issue can improve the user experience.

## Your Environment

* Browser name and version: Chrome 87
* Operating System and version (desktop or mobile): macOS 11.0.1

## Possible Fix

The same issue happened with instagram, but there is already an issue https://github.com/openfoodfoundation/openfoodnetwork/issues/1760 opened for that and there is this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6544 that solves it.
I'd suggest to take the same approach as this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6544, use regex to convert the link introduced and store just the user name, also use a migration to update the current social link on the db.

### PR DESCRIPTION
**Pull request by marthaerm**
#### What? Why?

Closes #6558

This PR fix the issue with facebook, twitter and linkedin links incorporating the same approach as this [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/6544), it validates the facebook, twitter and linkedin links added for the user, so it stores just the username.
The `app/views/admin/enterprises/form/_social.html.haml` also was modified to concatenates the social base url to the username stored on the database.
#### What should we test?

I added some tests to validate the pattern for each social link (facebook, twitter, linkedin)

#### Release notes

Social links validated to store just the username of eachone

Changelog Category: Technical changes

### CODE REVIEW

**Review by andrewpbrett — CHANGES_REQUESTED** [review]
Thanks for this PR @marthaerm, it's looking good! I see there are two tests that are failing:

./spec/features/consumer/registration_spec.rb:122
./spec/models/enterprise_spec.rb:720

They probably just need to be updated to reflect the new behavior. 

Also Rubocop is suggesting that we call `.freeze` on those Regex's, I believe.

**Comment by RachL** [comment]
hello @marthaerm hope this message finds you well. Are you still available to make the changes requested here?

**Comment by marthaerm** [comment]
> hello @marthaerm hope this message finds you well. Are you still available to make the changes requested here?

Hi! I'm sorry, I got a bit busy, I'd like to help with the changes, but I'm not available to do them right now, so if someone else can join, would be great.

**Comment by andrewpbrett** [comment]
I took another look at this and it would also require a migration, similar to #6544. Those can get tricky, so this isn't as close as I thought to being complete. I'm going to close this PR and move the issue into All the Things, similar to what we did for #1760, for it to get prioritized and picked up.

**Pull request closed without merging**
