### PR TITLE
Delivery/Order email updates

### PR DESCRIPTION
**Pull request by lin-d-hop**
Incorporating more of the configurable content into the order emails for producer, no longer AU hardcoded.
Plus a typo in the shipping info. 
en-GB locale update just some minor formatting.

All minor stuff. 
Would someone take a look and merge to master? @mkllnk @oeoeaio 
Thanks!

### CODE REVIEW

**Comment by mkllnk** [comment]
Hi Lynne, thanks for that. All changes look good to me. I will try to get this through next week.

**Comment by pmackay** [comment]
@lin-d-hop is there anything from #569 that could be included in this PR?

**Comment by lin-d-hop** [comment]
@pmackay as per Rohans comments should we change Spree::MailMethod.current.preferred_mails_from
to perhaps..
ContentConfig.footer_email
??

**Comment by daniellemoorhead** [comment]
Hi all :)
Where's this at? Still requiring some assistance from @mkllnk with this or has the PR been done and this can be closed?

**Comment by lin-d-hop** [comment]
Just merged this and based on @mkllnk's code review and removed the aus review label. Thanks peeps.

**Comment by mkllnk** [comment]
Hi @lin-d-hop, I'm sorry that I didn't have time to merge this the last two weeks. Did you check with Rohan or Rob about merging? Because we normally don't merge directly, we go through our build pipeline on Buildkite to merge and deploy to our production server at the same time.

**Comment by lin-d-hop** [comment]
Hi @mkllnk 
I didn't check. Apologies. Since it was a small change I was just trying to clear it off the queue. I know for future not to do that. Hope it hasn't broken anything with the pipeline etc. :-( Sorry for getting ahead of myself.

So, nothing is merged until it is being deployed to production. I assume production deploys happen on a schedule? Is there a page or list or something for merges that are going in to each production deployment? I guess from my perspective it might make it easier to to know where things are at, and hence not wonder whether I need to chase things or just let them sit. I know you guys are really busy so trying to bug you as little as possible...

Sorry again for messing up the procedure.

**Comment by mkllnk** [comment]
No worries. I'm not aware of anything broken.

At the moment, we use Buildkite to push the most urgent branch to our staging server. Sally tests that the desired features are there and nothing is broken. We then merge to master and deploy master to our production server in one go.

That means that the current bottle neck is Sally's office time, Wednesday and Friday. We could have more testers, but it should never be the developer and it needs to be a person who knows the system quite well as a user.

**Pull request merged**
