### PR TITLE
Admin, BOM: can bulk delete line items of an order

### LINKED ISSUE #9148: No bulk delete possible on BOM when orders have multiple items
## Description
It is not possible to select and bulk delete items from orders on the BOM page,  when there are multiple items on the order.  It IS possible to select and bulk delete items IF these are the only/last items in an order.   It IS possible to delete items singularly.

## Actual Behaviour
Should be able to filter, select and bulk delete items.

## Steps to Reproduce

1.create an order with multiple items
2.select multiple items on the BOM page
3.go to actions -  delete.  
4.

## Workaround
Work around is to delete items one by one but for a large hub with 1000 items in their shop and on orders,  this is very time consuming.

## Severity
S2?  

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version: Chrome - latest
* Operating System and version (desktop or mobile): Windows -  desktop

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Previously, we could only bulk delete line items if those deletions lead to an order cancellation (basically, all items of an order)
With this PR we can bulk delete line items event if deletion does not lead to an order cancellation.

- Closes #9148

#### What should we test?

As an admin, on BOM page:
- delete **all** line items of an order: this should show a modal about modal cancellation
- delete **not all** line items of an order: this should delete those previously selected line items

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by RachL** [comment]
🙈 🙈 🙈 
 
 I'm not sure how to check: can we (if not already done) add a spec on this one to avoid it in the future? 💦

**Comment by jibees** [comment]
Should be done via: https://github.com/openfoodfoundation/openfoodnetwork/pull/10447/commits/e5ca8b0ee1009c49d69edc0fb670b563b6c51521

**Review by dacook — COMMENTED** [review]
It looks like we now go ahead and delete without any confirmation. Are you sure? That seems dangerous. (or is it easy to undo and doesn't require confirmation?)

**Comment by RachL** [comment]
@dacook @jibees nice catch, we need a confirmation modal, this action cannot be undone 👍 I thought we already had one.

**Comment by jibees** [comment]
Sorry, I missed that. 
Back to "Code Review". 

Thanks for your deep review 💪

**Review by dacook — APPROVED** [review]
Looks good to me!

**Comment by dacook** [comment]
A random aside: it looks like `variant_autocomplete.js.erb` is unnecessarily parsed for embedded ruby. Do you know if it needs the `.erb` in the filename?

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Review by mkllnk — APPROVED** [review]

**Comment by RachL** [comment]
Ok I think I went through all tests possible: 

- single delete with the bin or dropdown that leads or leads not to cancellation
- same with bulk delete: there I tested also bulk delete on 1 order and bulk delete on several order (massively destroying my test shop :D )

I'm merging :muscle:

@drummer83 if you can take a quick look during release testing, a second pair of eyes would not hurt I think.

That being said, I guess that if I've missed something, we still have a PR that improves the current situation. So good to have reach the bottom of this one!!

Also the "are you sure" modal is now well design and not the ugly browser notification we had before. thanks @jibees 😗 

image

**Comment by drummer83** [comment]
I have checked this in release testing as well.
Looking good. :+1:

**Pull request merged**
