### PR TITLE
Add Google map region parameter

### LINKED ISSUE #11394: Google map region parameter
## Description

We are launching OFN (Open Food Network) in India, and the way the country borders are displayed differs.

We have realized that https://www.google.com/maps uses visitors IP address to determine the region that will be shown.

More info on this post
https://www.washingtonpost.com/technology/2020/02/14/google-maps-political-borders/

## Expected Behavior

We should have the capability to set up the region so that users, e.g., from India, see the same map as when they are visiting https://www.google.com/maps

## Actual Behaviour

Currently, there is no option to define a region that will be used for Google Maps, and the map is displayed the same for all instances and users.

## Steps to Reproduce

1. Navigate to the /map path.
1. Zoom in on India.

## Animated Gif/Screenshot

The current display looks like this (the red dashed borders should be solid):

Screenshot 2023-08-12 at 08 34 03

And this is correct for users from India:

Screenshot 2023-08-12 at 08 39 38

## Workaround

I am not aware of any workarounds for this issue.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: any
* Browser name and version: any
* Operating System and version (desktop or mobile): any

## Possible Fix

Adding a `GOOGLE_MAP_REGION` parameter when [loading](https://github.com/openfoodfoundation/openfoodnetwork/blob/613802f477bb6c6536fd78e59b1ea204426b5b63/app/views/shared/_google_maps_js.html.haml#L2) will resolve this issue.

### PR DESCRIPTION
**Pull request by duleorlovic**
#### What? Why?

- Closes #11394

#### What should we test?

- set env variable `export GOOGLE_MAPS_REGION=IN`
- Visit /map path.
- Zoom in on India
- Borders should be solid as on https://github.com/openfoodfoundation/openfoodnetwork/issues/11394

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
That's a nice addition. Thank you.

**Review by jibees — APPROVED** [review]
Thanks! 🙏

**Comment by drummer83** [comment]
Hi @openfoodfoundation/core-devs,
I have been playing with this, trying to find a way to make it work, but I failed. :disappointed: 
Could someone please let me know how to test this?
How do I set the env variable?
Thanks for your support!

**Comment by duleorlovic** [comment]
When you follow https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md eg
```
foreman start
```
and navigate to http://localhost:3000/map you can notice alert "This page can't load Google Maps correctly" which means you have not provided valid google map api key.
You need to enable Maps Javascript API in your Google project and copy Keys & Credentials > API Key

You can set env variable in two ways. First is to edit `.env.development` file (you can find all keys https://github.com/openfoodfoundation/openfoodnetwork/blob/master/.env#L54) so lets say we add those two env variables
```
# .env.development
GOOGLE_MAPS_API_KEY=asd123.....
GOOGLE_MAPS_REGION=IN
```
and when you run again `foreman start` you should see the map on  http://localhost:3000/map 

Another way is to run `export GOOGLE_MAPS_API_KEY=asd123..... GOOGLE_MAPS_REGION=IN` and than `foreman start` in the same shell.

**Comment by mkllnk** [comment]
> Could someone please let me know how to test this?

After deployment, you have to edit `~/apps/openfoodnetwork/current/.env.staging` on the server. Add this line:
```
GOOGLE_MAPS_REGION=IN
```

Then restart puma:

```
sudo systemctl reload puma.service
```

The borders of India should then look different on that staging server compared to others which are not set to India.

**Comment by drummer83** [comment]
Ok, cool! Thank you both for the support! :+1: 

I was close:
- I wasn't aware of the required puma restart
- I wasn't aware of the .env.**staging** file

Now that I knew that, I was able to test the PR.

### Before staging (or without a GOOGLE_MAPS_REGION set)
image

### After staging and with the GOOGLE_MAPS_REGION set to IN
image

I think this one is good to go! Thank you @duleorlovic for this contribution!
Merging! :partying_face: :rocket:

**Comment by RachL** [comment]
@mkllnk @duleorlovic maybe a stupid question, but currently when navigating to the map, Australia is briefly shown for a few seconds before the instance's country is loaded. Will this PR fix this problem too?

**Comment by mkllnk** [comment]
> when navigating to the map, Australia is briefly shown for a few seconds before the instance's country is loaded. Will this PR fix this problem too?

No, that's hard-coded:

https://github.com/openfoodfoundation/openfoodnetwork/blob/3aca33b8a607a8cbcd1d9c96524c8871b7f83b16/app/assets/javascripts/darkswarm/services/map_configuration.js.erb.coffee#L2-L6

**Pull request merged**
