### PR TITLE
Bring base helper from spree_backend

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Relates to #4050

In this PR we bring the base_helper from spree with a number of generic helper methods used in different parts of the application. See testing notes below for details.

#### What should we test?
There are couple of different things that need to be validated here.

1. Editing an order, in Customer Details, the placeholder should look like this translated:
Screenshot 2019-12-16 at 18 14 51

2. field_container - product edit page looks good and works.

3. error_message_on - editing a product, removing name and saving it will show an error on the top of the page as well as below the name field (can be tested in english):
Screenshot 2019-12-16 at 18 19 16

4. preference_field_tag - make sure you can edit preferences in the general settings, for example, verify the footer_tos_url field is working correctly.

5. zones - make sure you can add and remove countries and states from a zone: this needs to be tested for both country based zones and state based zones.

Screenshot 2019-12-17 at 09 49 37

6. preference_fields - make sure you can configure calculators correctly on shipping_methods, payment methods and enterprise fees. everythin shouldd be fine. a quick test of the form is enough.

7. product properties - make sure you can add properties to a product - test the link on the top right to add more lines to the form

8. producer properties - make sure we can add and remove properties from a producer enterprise - this page is currently a bit weird because you can only add more properties by saving the form (it will add one if all are used) but there should be a button on the top "add properties" like in the product properties above. I think we can open a bug for this. Probably S4.

#### Release notes
Changelog Category: Changed
Brought base_helper with generic helper methods to build the admin pages from spree to make ofn independent of spree.

### CODE REVIEW

**Comment by lin-d-hop** [comment]
Ping @luisramos0 conflicts

**Comment by luisramos0** [comment]
rebased to resolve conflicts. ready for testing.

**Comment by luisramos0** [comment]
rebased to resolved conflict on rubocop file.

**Comment by RachL** [comment]
This is looking good!

My notes: https://docs.google.com/document/d/1vsU8Yqo9XmUVGIJQ_dm7dpdxmdroEMhcsYgH_gI9Mr8/edit#

@luisramos0 I didn't find what you've meant by the footer_tos_url field . So I've tested the shopping preferences entirely. Hope this was the right place :+1:

**Comment by luisramos0** [comment]
hmm, I meant "preferences in the general settings" but you say "shopping preferences".
I mean /admin/general_settings 
tos = terms of service - "Conditions d'utilisation URL"
Let me know if you think you have verified this page.
thanks!

**Comment by RachL** [comment]
@luisramos0 not at all! I didn't know this was called preferences as well. I just tested this page. Looking good!

**Comment by luisramos0** [comment]
sorry about that, I got taken by the names of the variables. they are all preferences in the code...
thanks!

**Pull request merged**
