### PR TITLE
[Spree Upgrade] Merging master into 2-0-stable (1st run in Mar2019)

### PR DESCRIPTION
**Pull request by luisramos0**
Merging master into 2-0-stable.
Same as previous #3524
  This is the result of:   

git checkout master    
git pull upstream master    
git checkout 2-0-stable
    git pull upstream 2-0-stable
    git checkout -b 2-0-stable-Mar6
git merge master  

Conflicts:
CONFLICT (content): Merge conflict in spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
	keep on_demand
	git add spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee

CONFLICT (content): Merge conflict in lib/open_food_network/scope_variant_to_hub.rb
	delete in_stock?
	keep count_on_hand as total_on_hand
	git add lib/open_food_network/scope_variant_to_hub.rb

CONFLICT (content): Merge conflict in config/locales/en.yml
	keep master

CONFLICT (content): Merge conflict in app/models/variant_override.rb
	keep HEAD just add new method use_producer_stock_settings? from master
	git add app/models/variant_override.rb

CONFLICT (content): Merge conflict in app/assets/javascripts/admin/all.js
	keep master
	git add app/assets/javascripts/admin/all.js

CONFLICT (content): Merge conflict in Gemfile.lock
	keep stringex
	upgrade stripe
	git add Gemfile.lock

CONFLICT (content): Merge conflict in Gemfile
	keep spree_paypal_express from HEAD
	upgrade stripe
	git add Gemfile

git commit
git push origin 2-0-stable-Mar6

### CODE REVIEW

**Comment by luisramos0** [comment]
the build is totally broken, I need to have a look.

**Comment by luisramos0** [comment]
super flaky build with #3520, #3576 and #3582 at the same time...

**Comment by sauloperez** [comment]
Yes... we should go back to fixing these tests asap. I'll try it this week.

**Comment by sigmundpetersen** [comment]
#3582 has failed on all builds of this PR (>10 builds) so it has gone from slaky to consistent I would say

**Comment by sauloperez** [comment]
then that is great news! it is easier to fix things that break always. We should check if it has something to do with this particular PR though.

**Comment by luisramos0** [comment]
I dont see how this PR could be making specs more flaky, but it could be...
I think we should merge anyway and fix the flaky specs in separate PRs. what do you think?

**Comment by sauloperez** [comment]
Agree

**Comment by luisramos0** [comment]
sorry, it was my distraction. the error with shipping_methods_spec was not the flaky #3582 but rather a missing translation. I added that translation in this last commit and, although, still flaky, the build is green.
I am preparing a follow up PR to move all admin/shipping_methods translations to lazy lookups.

**Comment by mkllnk** [comment]
Now I'm wondering if we changed something in master during that time that made the spec flaky... I'll merge as you suggested though.

**Pull request merged**
