### PR TITLE
In the shopfront, display fee name in the tooltip of a price product breakdown

### LINKED ISSUE #8899: Admin Fee display in shopfront: displaying fee name instead of the type
## Description
**- As a:** (enterprise user, super admin, user...) Shopper
**- On page:** (provide url of the page you want to modify. If not provide where will be created the new url and the name we want to give it) Shopfront
**- I want to be able to:** (specify the desired behavior) ee the name of enterprise fees specified by enterpise

Enterprise fees have 'types' associated with them:  - admin, sales, transport, packing, fundraising
This is a Spree legacy and doesn't have a reflection on taxes or functionality. It simply creates a point of confusion for users.

This issue is part of a 3part epic to remove these fee types.

Part 1. Removing them from the shopfront.
Currently the fee type is displayed in the shopfront within the 'pie chart' feature
Screenshot from 2022-02-16 14-10-16

Instead of the **fee types** these should have the **fee names** that have been entered here:
Screenshot from 2022-02-16 14-15-49

So from the image above the Pie Chart should now say '100% special' instead of 'Fundraising Fee' as it would say now.

## Acceptance Criteria & Tests

1. All types of fees should now display in the pie chart with the Fee Name instead.
2. Front end developer should take into consideration how the Fee Name length will render on different devices. If the name is too long it should be truncated with a ... to ensure it renders well. Any max should be noted in the issue fro additional testing.
3. 
4.

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8899

I've created a new attribute inside the variant serializer (`fees_name`) instead of breaking the existing API 

#### What should we test?

- Add multiple fees to an enterprise: `/admin/enterprise_fees?enterprise_id=4`
Capture d’écran 2022-06-21 à 14 23 16

- Assign all fees to an order cycle managed by previously edited enterprise: `/admin/order_cycles/2/edit`
Capture d’écran 2022-06-21 à 14 25 09

 - Check that on each product of the order cycle, the tooltip around price breakdown presents the fee name instead of the fee type:
Capture d’écran 2022-06-21 à 14 26 12
if name is long
Capture d’écran 2022-06-21 à 14 27 18

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Before this PR, the enterprise fees names were being displayed:
image

After staging the PR, the names are displayed instead:
image

However, we can see that a long name does not get "cut"... This was tested in both Firefox and Chrome (Ubuntu 20.04, above) and on mobile (Android/Chrome below):

image
 
Maybe best to address this usability detail before merging?
Moving back to In Dev.

**Comment by jibees** [comment]
Long name, without any space ;)

**Comment by filipefurtad0** [comment]
Riiight!! My bad... I don't think (without any spaces) is a relevant test...
I'll repeat with a regular text.

**Comment by filipefurtad0** [comment]
Yeah, this looks great:
(before I was actually surprised it didn't... :see_no_evil: )

Thank you for commenting :+1: 

Desktop Chrome/Firefox:
image

Android Samsung 21, Chrome
image

iPhone 11, Safari
image

Merging!

**Pull request merged**
