### PR TITLE
Run rubocop with reviewdog

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Run Rubocop with GH Actions on each `push` and `pull_request`

Capture d’écran 2021-11-24 à 09 35 31

#### Release notes
Add an automatic run of a Ruby linter

Changelog Category: Technical changes

### CODE REVIEW

**Comment by achauve** [comment]
Seems great! What's suprising me is even without automatic checking since a few weeks/months(?) there was no error at the first rubocop run?
Or is it just running on diffs introduced in the branch/PR?

**Comment by jibees** [comment]
> Or is it just running on diffs introduced in the branch/PR?

Yes, I understand that (and it's quite normal actually ;))

**Comment by achauve** [comment]
> Yes, I understand that (and it's quite normal actually ;))
Yes ok, it's only style/formatting/naming checks. Seems to be hard to detect unused variables, dead code and other problems in ruby like in python or js (like pyflakes/pylint/eslint do).

**Review by achauve — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]
:+1:

**Pull request merged**
