### PR TITLE
i18n for admin/orders

### PR DESCRIPTION
**Pull request by mjal**
#### What? Why?

Partially address #2001

This provides all the i18n as noted in #2001, except for the "Please enter 3 characters" string (it come from the select2 library, idk how to localize that yet)

#### What should we test?

The english version remains unchanged.
After translation are provided on transifex, there is more translation in "order management".

### CODE REVIEW

**Comment by myriamboure** [comment]
Thank you @mjal ! Feel free to as @ltrls or @pacodelaluna I think they have dealt with Spree repo translations issue before, they can probably guide you. Would be great to try to put it all in that PR to avoid too many staging deployment for minor translation tests I think :-)

**Comment by daniellemoorhead** [comment]
Branch conflicts

giphy

**Comment by sauloperez** [comment]
I just checked the difference between the `1-3-stable` and `2-0-stable` branches for `spree_i18n` and looks like a nightmare bringing this changes in now. Check by yourself: https://github.com/openfoodfoundation/spree_i18n/compare/1-3-stable...openfoodfoundation:2-0-stable.

I also see a branch named `spree-upgrade-intermediate` that's identic to `2-0-stable`. Does it ring a bell to anyone? cc @oeoeaio @enricostano @mkllnk @Matt-Yorkley 

I suggest bringing in these missing keys in our `config/locales/` and move forward. Upgrading `spree_i18n` will take us some time we don't have now.

**Comment by mjal** [comment]
I just added them to `config/locales` then, it worked, thanks @sauloperez for the advice.

I didn't knew that there was a fork of spree_i18n for OFN, I'm a little confused because there is some changes but the Gemfile still link to spree/spree_i18n 1.3-stable :o.

**Comment by sauloperez** [comment]
Yes. Exactly what I told you, a mess :trollface: there's nothing worse than having unmanaged dependencies.

**Comment by myriamboure** [comment]
@sauloperez do you approve the last addition of @mjal ?
@mjal can you confirm it then covers the whole issue (and update the intro post then so that we know what to test). Thanks ;-)

**Comment by mjal** [comment]
@myriamboure first post updated

**Comment by myriamboure** [comment]
Staged on https://staging.openfoodnetwork.org.uk/ testing now

**Comment by myriamboure** [comment]
All right, nothing broken in the English version, can be merged and we'll test if translations are good in other languages once we are able to translate in transifex :-)
Testing notes (just screenshots showing all is good on order edit pages): https://docs.google.com/document/d/1B2PAUn283AHu9VGvpo7TRmBxoiIJNJ7INN0yM7rxJWM/edit#

**Pull request merged**
