### PR TITLE
Drop unused Spree Promotion Tables

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

We found some tables that aren't in use. We don't have models for these, and probably never used them.

I took a look at the au-prod database and found a small handful of records in a couple of tables, that don't seem to amount to anything (they weren't linked to any products). The timestamp was from 2013.

#### What should we test?
No application code has changed so I don't think we need to test anything.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]
:+1:

**Review by rioug — APPROVED** [review]
Yeah! less code :broom:

**Comment by rioug** [comment]
@dacook or @Matt-Yorkley I can't merge this as I was the one who rebased the branch, could one of you take car of it ?

**Comment by dacook** [comment]
I can merge once someone approves it, but I can't approve it because I'm the creator of the PR 😆 

But I _can_ bypass branch protections 🔨

**Pull request merged**
