### PR TITLE
Raisl 5 - Render plain and render head

### LINKED ISSUE #7077: [Rails 5.2] Render deprecations
From the upgrade guide:

> Removed deprecated support to :text and :nothing in render
If your views are using render :text, they will no longer work. The new method of rendering text with MIME type of text/plain is to use render :plain.
Similarly, render :nothing is also removed and you should use the head method to send responses that contain only headers. For example, head :ok sends a 200 response with no body to render.

Related error:
```
Tag Rules deleting deletes both default and customer rules from the database
       Failure/Error: render(text: params[:permalink], status: :conflict) && return
       
       ActionView::MissingTemplate:
         Missing template enterprises/check_permalink, base/check_permalink, application/check_permalink with {:locale=>[:en], :formats=>[:js, :html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :haml]}. Searched in:
           * "/home/runner/openfoodnetwork/app/views"
           * "/home/runner/openfoodnetwork/vendor/bundle/ruby/2.4.0/gems/foundation-rails-5.5.2.1/app/views"
           * "/home/runner/openfoodnetwork/vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.2.1/app/views"
           * "/home/runner/openfoodnetwork/vendor/bundle/ruby/2.4.0/gems/devise-4.7.3/app/views"
           * "/home/runner/openfoodnetwork/engines/web/app/views"
           * "/home/runner/openfoodnetwork/engines/order_management/app/views"
       # ./app/controllers/enterprises_controller.rb:42:in `check_permalink'
       # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
       # ------------------
       # --- Caused by: ---
       # Capybara::ExpectationNotMet:
       #   expected not to find visible css "#tr_1", found 1 match: "Inventory variants tagged\nare:\nVISIBLE"
       #   ./spec/features/admin/tag_rules_spec.rb:230:in `block (4 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #7077

I wonder if these things work in rails 5.0.

#### What should we test?
Green build is enough I think.

#### Release notes

Changelog Category: User facing changes | Technical changes

Adapt controllers code to rails 5.2

### CODE REVIEW

**Comment by luisramos0** [comment]
I wonder if the build is just very flaky these days or if I have to fix something....

**Comment by sigmundpetersen** [comment]
Same failures are in master right now, so I guess this build is good.

**Review by mkllnk — APPROVED** [review]
Great! :+1:

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by andrewpbrett** [comment]
@luisramos0 do you mind rebasing this? I'll have time a little later too.

**Comment by andrewpbrett** [comment]
@luisramos0 nevermind, it was simple enough to do in the GitHub web UI. 👍

**Comment by luisramos0** [comment]
nice, thanks!

**Pull request merged**
