### PR TITLE
Admin, `/orders`: adds translation for order in `confirmation` state

### LINKED ISSUE #10718: Missing translation: confirmation (order state)
## Description

The admin orders page displays a missing JS translation error for orders in the `confirmation` state

## Expected Behavior

Confirmation state should be translated

## Actual Behaviour

JS error is displayed

## Steps to Reproduce

1. Create an order in the confirmation state (summary step of split checkout, via UI)
2. Visit the orders page and untick the option to display only complete orders
3. See the JS translation error

## Animated Gif/Screenshot

image

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.3.3
* Browser name and version: Firefox 111
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10718 
Capture d’écran 2023-04-20 à 09 42 04

#### What should we test?
Well explained in the linked issue: 
 - Create an order in the confirmation state (summary step of split checkout, via UI)
 - Visit the orders page and untick the option to display only complete orders
 - See that order in `confirmation` state have the word translated and little red circle 

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
@filipefurtad0 Did manage to create a simple/efficient spec for that actually ;) It's not that easy to make difference between a state untranslated and a state translated. We can eventually look at `[MISSING` content in the whole page to check any translation errors in the whole specs. But I don't know if it is relevant.

**Comment by filipefurtad0** [comment]
No, I don't have a good suggestion. However, we should have this
https://github.com/openfoodfoundation/openfoodnetwork/pull/3006/files
in place, which in principle should catch it. I wonder why it is not. I'll investigate.
Thanks @jibees !

**Comment by jibees** [comment]
> in place, which in principle should catch it. I wonder why it is not. I'll investigate.

Maybe because we don't set `CHECK_TRANSLATIONS` env. variable when running spec on CI?

**Comment by filipefurtad0** [comment]
> Maybe because we don't set CHECK_TRANSLATIONS env. variable when running spec on CI?

Right - indeed our build is not catching this.

I've tried to make it work locally, by setting that ENV to true, if I set it to true, but I don't get a warning for this missing translation. I think this could be because it is under the `js` name space, and not under the `spree.` name space.

So I guess we would need to change that missing translation checker to include js. Would you agree?
I guess this is out of scope for this PR.

**Comment by jibees** [comment]
> So I guess we would need to change that missing translation checker to include js. Would you agree?
I guess this is out of scope for this PR.

Yes, probably!

**Comment by mkllnk** [comment]
That translation checker is an old artifact from Spree and we never used it. I discovered it only recently and wanted to remove it, so many distractions. If we miss a translation in Ruby code including views then an error is raised. If this is in Javascript then I'm not sure where the problem is. Ideally it would raise a Javascript error in testing (not production) and we should fail tests when errors are present. We used to fail on Javascript errors but since then we introduced Cuprite and changed the code for translations in Javascript. So I'm not sure which or if both of these mechanisms to detect the error are broken.

**Review by mkllnk — APPROVED** [review]
Code looks good. :+1:

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Comment by drummer83** [comment]
Hi @jibees,
Thanks for this fix!

Before staging the PR I could see the missing translation:
image

After staging the PR the state is displayed correctly and the colored symbol is added as well:
image

There was no feedback regarding the color of the symbol and it seems that you changed your find from orange to red but I think that makes sense because we have 'address' and 'payment' in red as well. :+1: 

Merging! Thanks! :tada:

**Comment by filipefurtad0** [comment]
Opened this [PR here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10739) which could be a step towards signalling missing translations.

**Pull request merged**
