### PR TITLE
3283 [Enterprise Fee Summary] Receiver as "Fee Calc on Transfer Through" for incoming exchange fees

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

Relates to #3283 

As discussed in #3283, for enterprise fees added to an incoming exchange, "Fee Calc on Transfer Through" should be the name of the sender (the producer).

#### What should we test?

1. Set up an OC with different enterprises for producer, coordinator, and distributor.
2. Set up an incoming and outgoing exchange for a variant with stock.
3. Add one enterprise fee each for the producer, coordinator, and distributor to the incoming exchange and also to the outgoing exchange.
4. Create and complete an order for the variant.
5. Check the Enterprise Fee Summary. There should be 8 rows for the order. For all 3 rows marked "Incoming", "Fee Calc on Transfer Through" should be the name of the producer. For all 3 rows marked "Outgoing", it should be the name of the distributor.

#### Release notes

No release notes needed as this would be packaged with the rest of the initial changes for the Enterprise Fee Summary.

Changelog Category: -

#### Dependencies

This requires #3312 to be merged to the transitional branch first.

### CODE REVIEW

**Comment by kristinalim** [comment]
@mkllnk The exact definition (for some scenarios) is still being clarified in #3283, but:

1. For fees for incoming exchanges - If the data is available, it should be the sender in the exchange.
2. For fees for outgoing exchanges - If the data is available, it should be the receiver in the exchange.

**Comment by mkllnk** [comment]
Ah, now I get the problem. Does that mean that a producer can effectively charge for items of other producers that are sold in the same order cycle by applying a fee for the whole order?

Can we find the fee via `Spree::Adjustment#originator` and get the enterprise from there?

Could another name for this column be "Charged by"?

**Comment by kristinalim** [comment]
> Does that mean that a producer can effectively charge for items of other producers that are sold in the same order cycle by applying a fee for the whole order?

@mkllnk Yes this is currently the case.

> Can we find the fee via Spree::Adjustment#originator and get the enterprise from there?
> Could another name for this column be "Charged by"?

@mkllnk Were you thinking about the recipient of the fee? This data is already in "Enterprise Owner".

"Fee Calc on Transfer Through" I believe is to tell to which enterprise you'd want to attribute the fee... Still checking this in Issue #3319, and will address other scenarios in PR #3337.

**Comment by mkllnk** [comment]
@kristinalim I'm sorry, but I just stuffed up your branch for a bit. I tried to stage this pull request and it failed on merging master into it. I was surprised, because this pull request didn't indicate any merge conflicts. Anyway, I thought I should rebase it on master and I resolved the conflict. Now Github complained about a merge conflict and when I saw that I realised what I did. I forgot that this pull request is based on the feature branch. I think the feature branch has a merge conflict with master.

Luckily there is `git reflog` and I could restore the original version of this branch. But I think your feature branch needs rebasing or merging to resolve the conflict. You may need to rebase or merge all the other connected branches then as well.

**Comment by kristinalim** [comment]
@mkllnk I see. I don't have permission to force-push to a branch in this repository, unfortunately. Could you do it? I can take care of rebasing the open PRs upon this feature branch.

I rebased and pushed to my fork:

```sh
git remote add kristinalim git@github.com:kristinalim/openfoodnetwork.git
git fetch kristinalim
git checkout kristinalim/feature/enterprise_fee_summary
git push upstream +HEAD:feature/enterprise_fee_summary
```

**Comment by mkllnk** [comment]
Done. Slightly different commands:
```
git fetch git@github.com:kristinalim/openfoodnetwork.git feature/enterprise_fee_summary
git push upstream +FETCH_HEAD:feature/enterprise_fee_summary
```

**Comment by kristinalim** [comment]
This has been rebased already, @mkllnk. Thank you!

**Comment by RachL** [comment]
@kristinalim deployment failed on UK staging...

**Comment by kristinalim** [comment]
@kirstenalarsen This particular PR was not meant to fix the "Fee Calc on Transfer Through" issue. I pinged for a second review of #3337 which should fix this - hoping we can get merge that in the transitional branch before merging everything to master.

**Pull request merged**
