### PR TITLE
Fix: Add lastname, firstname and firstname, lastname search

### LINKED ISSUE #11585: [BOM] Allow to search with Lastname Firstname order and with a comma
Follow up on https://github.com/openfoodfoundation/openfoodnetwork/issues/10570

## Description

**- As a:** (enterprise user, super admin, user...)
**- On page:** `/admin/orders/bulk_management`
**- I want to be able to do:** some user copy/paste what they see on the page in the search. Yet the search returns no result if there is a comma. 

Also, searching with last name first gives no result yet. We want to add those 2 cases to this search.

## Acceptance Criteria & Tests

1. Log in as admin of a hub with some complete orders and visit `/admin/orders/bulk_management`
2. On the search field, copy paste the first name + last name of a customer as it appears on BOM (with comma)
3. Click "Filter Results"
4. See it's working
5. Now switch your search and put last name first: it should work as well

### PR DESCRIPTION
**Pull request by OsamaNabih**
#### What? Why?
Add `<firstname>, <lastname>` and `<lastname>, <firstname>` search

- Closes #11585 

Add 2 new runsacks, one for each case

#### What should we test?

- Visit `/admin/orders/bulk_management` page.
- Try searching with `Mistery, John` or `John, Mistery` (as displayed to the user) with built-in sample data
- No longer showing empty results

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes

### CODE REVIEW

**Comment by rioug** [comment]
Moving back to in Dev as it's still a draft PR.

**Review by mkllnk — COMMENTED** [review]
Nice approach. Thank you for this contribution. Would you be able to look at the failing specs and see what's happening?

**Comment by OsamaNabih** [comment]
> Nice approach. Thank you for this contribution. Would you be able to look at the failing specs and see what's happening?

Sure, I'll get to working on it!

**Comment by sigmundpetersen** [comment]
Still some failing specs here I'm afraid

**Comment by sigmundpetersen** [comment]
@openfoodfoundation/developers @openfoodfoundation/train-drivers-product-owners 

Is this something we should fix and get through the pipe?
Or should we close this one?

**Comment by RachL** [comment]
I guess our team is now too small to fix those? I would vote for closing.

**Comment by dacook** [comment]
I just spent 20 mins to dive in and see if I could easily complete it, but wasn't able to. 

It's very much a work-in-progress. We probably need the new ransack queries as have been created, but I think to implement them would some clever SQL hackery. Postgres doesn't seem to support a simple way of achieving it (that I could find easily).

So I vote to close also. I hope the issue can be picked up again because it sounds like a useful feature.

**Pull request closed without merging**
