### PR TITLE
Replace use of spree.root_path and root_url with main_app.root_path and main_app.root_url

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Continues #4595

This change will enable us to stop depending on spree_backend and some of the base spree routes that come with it.

Here I also adapt an unnecessary call to a devise method related to routes in after_sign_in_path_for. This was breaking the build without spree_backend.

#### What should we test?
I dont think we need to test all the changes to main_app.root_path.
I suggest we validate manually the change in after_sign_in_path_for by testing the redirection process after login:
1 - type __domain__/admin directly on the browser, like https://staging.openfoodnetwork.org.au/admin
2 - logout if you are logged in and repeat step 1
3 - after step 2 you will see the login box
4 - login
5 - expect to land in the backoffice at /admin

#### Release notes
Changelog Category: Changed
Switched some routes from spree base routes to ofn (main_app) routes to enable removing spree_backend dependency.

### CODE REVIEW

**Comment by luisramos0** [comment]
sorry, I forgot to check the build after pushing.
It's fixed now.

**Comment by lin-d-hop** [comment]
Ping @luisramos0 Fancy unpicking the code climate issue?

**Comment by luisramos0** [comment]
the codeclinate issue will be ignored. it's application_controller being too long... not easy at all.

this is ready for testing.

**Comment by lin-d-hop** [comment]
Tested:
Admin URL when not logged in - showed login panel
Logging in then checking the admin URL - works
Logging out and refreshing admin URL - shows login panel
Logging back in and refreshing the admin URL - works
Logging out then logging in to visit an unauthorised admin URL - shows 'unauthorised' message

All behaved as expected.
Ready to go :-)

**Pull request merged**
