### PR TITLE
Separate date format used for server communication from user-readable date

### LINKED ISSUE #6917: New date picker does not prefill correct end date in reports
## Description

Some reports have their date prefill with the last month range.

Since the introduction of the new date picker the date range is fixed at 20.01.2021 to 20.01.2021

List of reports impacted are all under:

`/admin/reports/orders_and_fulfillment`

## Steps to Reproduce

1. Log in as admin
2. Go to `/admin/reports/orders_and_fulfillment`
3. See the prefilled dates

## Workaround

Removes the dates

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.5.9
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Closes #6917

This aim of this PR is to separate date format used for communication between backend and frontend and date format visible in the input for the end user.
 - Date format used by both back and front end is fixed.
 - Date format visible by end user is i18nized (and named `altFormat` by flatpickr)

#### What should we test?
The issue has been found by using another language than english (a language that doesn't use the date format : `Y-m-d` or `Y-m-d H:i` for its date(time)picker) on pre-filled form. I do recommend to test all the date(time)picker of the platform with another language than english (such as `FR`), and have a special attention to whom pre-filled (as far as i know: `/admin/reports/orders_and_fulfillment` and `/admin/orders/bulk_management`).

##### List of date(time)picker: 

 - `/admin/order_cycles/`
 - `/admin/order_cycles/[ORDER_ID]/edit`
 - `/admin/reports` such as `/order_management/reports/bulk_coop/new` or `admin/reports/orders_and_fulfillment? report_type=order_cycle_customer_totals`
 - 
 - `/admin/orders/bulk_management`
 - `/admin/orders?q[s]=completed_at+desc#`
 - `/admin/order_cycles/new` (create new order cycle)
 
for reference, the PR which introduce the new datepicker: #6691

#### Release notes
Fix display issue from datepicker when language wasn't english.

Changelog Category: User facing changes

### CODE REVIEW

**Review by andrewpbrett — COMMENTED** [review]
I think this makes sense - could you add a better title for it? There's also a lot of commits that seem like they could probably be squashed together.

**Review by sauloperez — APPROVED** [review]
I also share @andrewpbrett 's points though

**Comment by filipefurtad0** [comment]
Thanks @jibees for this PR and for the testing details as well as the reminder of the pages to have a look :pray: 

I've added some pics of an account set to **English (left)** and another one set to **French (right),** on the pics below.

**Before staging** this PR:

- `/admin/reports/orders_and_fulfillment`, 

image

-  `/admin/orders/bulk_management`

image

We can see the default date, on the right side, as mentioned in the issue #6917.

**After staging** this PR:

- `/admin/reports/orders_and_fulfillment`, 

image

-  `/admin/orders/bulk_management`

image

So, this looks good now for the date fields which appear pre-filled, for both `Y-m-d` and `d-m-Y` types.



Also checked the pages (not pre-filled):

`    /admin/order_cycles/

`image

 `   /admin/order_cycles/[ORDER_CYCLE_ID]/edit`

image

`    /order_management/reports/bulk_coop/new` 

image

`    /admin/orders?q[s]=completed_at+desc#`

image

    /admin/order_cycles/new (create new order cycle)

image


This looks good to go, moving this forward. Pinging @RachL in case another look is needed here.

**Comment by RachL** [comment]
Totally trusting you @filipefurtad0 👍 Thanks for the detail testing notes, as usual ❤️

**Pull request merged**
