### PR TITLE
Add extra social media to order confirmation email

### LINKED ISSUE #3509: Add extra (Instagram) social media links to emails sent to customers and users
## Description

***Done***
There are only two social media links are in the footer of emails sent to OFN users: these are Facebook and Twitter.  It would be great to have Instagram added to this.

***To Do***
In the footer of order confirmation emails there are no social media links to OFN itself- just contact details of the hub/shop the customer ordered from.  It would be great to have the same 'Connect with us' footer on all emails.
 
## Expected Behavior

In the footer of emails sent to customers, below 'Cheers, Open Food Network (UK) team' to add the 'Connect with us:' box.
In the 'Connect with us:' box to add Instagram as a third option.

***Done***
Customer registration emails

***To Do***
Order confirmation emails

## Actual Behaviour

Footer of emails to OFN users has two social media links only: Facebook and Twitter.
Emails sent to customers have no social media footer.

## Steps to Reproduce

***Done***
1. Sign up to OFN
2. See footer links in Welcome email are missing Instagram links

***To Do***
1. Place an order in OFN
2. See footer links in Order Confirmation email are missing Instgram links

## Animated Gif/Screenshot

***Done***
welcome email footer/email to OFN users

image

***To Do***
Order confirmation email (sent to OFN customer)
image

## Context

Prevents effective social media communication and marketing.

## Severity

bug-s5

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

### PR DESCRIPTION
**Pull request by luchiago**
#### What? Why?

Closes #3509 

It's a feature to show to the customers our social media links

Here's a screenshot example:
image

#### What should we test?

Place an order and see the order confirmation for the customer

#### Release notes

Changelog Category: Added

### CODE REVIEW

**Comment by luchiago** [comment]
@luisramos0 These are my changes. I was unable to send a screenshot because the changes do not appear to have been applied. In fact, it shows that the new footer is in the email, but as I said, the Linkedin link doesn't change

**Comment by luisramos0** [comment]
Thanks for the PR Lucas! You are only changing the default values of the preferences, do you need to change the default values?
To change the preferences in your installation you need to load the BackOffice /admin and go to Confguration > Content

**Comment by luchiago** [comment]
@luisramos0 But how will the change in the local administrator be applied by my PR?

**Comment by luchiago** [comment]
@luisramos0 Now I can see the changes and send a screenshot, but my previous doubt persists

**Comment by luisramos0** [comment]
ok, I see.
you are asking how preferences get loaded into the DB.
you can look at the DB here:
select * from spree_preferences where key like '%content_conf%';

I dont know the answer to your question, we could have a look at the Configuration and Preference code in Spree. Maybe the next reviewer will know :+1:

**Comment by luchiago** [comment]
> nice, thanks for the PR Lucas!
> I wonder if the instagram red could be a bit darker, or less red, to get less visual attention on the email.
Something like this?
image

**Comment by luchiago** [comment]
> ok, I see.
> you are asking how preferences get loaded into the DB.
> you can look at the DB here:
> select * from spree_preferences where key like '%content_conf%';
> 
> I dont know the answer to your question, we could have a look at the Configuration and Preference code in Spree. Maybe the next reviewer will know

Alright

**Comment by luchiago** [comment]
@luisramos0 I think this PR is done. Just let me know your opinion about Instagram color.

**Comment by luisramos0** [comment]
hello, yeah, I think we go with your original color unless someone complaints during testing :-)
This PR will be tested soon.

**Comment by daniellemoorhead** [comment]
Hey @luisramos0 codeclimate failed for this PR - can I still test it or does it need to be resolved first?

**Comment by luisramos0** [comment]
it's complaining about the instagram color as well :-)

Anyway, eady for testing.

**Comment by filipefurtad0** [comment]
Hi @luchiago,

I staged, placed the order and had a look at the confirmations emails. There it is, Instagram red-tab:

image

I'm fine with the red-colour as well. 

One note though:
for the social media tabs to appear one needs to set a link for them, as superadmin on the page: /admin/contents/edit

Thanks for this improvement!
Ready to go.

PS: Thanks @daniellemoorhead for clarifying the codeclimate check issue :-)

**Comment by luisramos0** [comment]
@filipefurtad0 this PR adds the social buttons to the customer order confirmation, I wonder if you are not looking at the manager order confirmation email that already had the social links.

**Comment by filipefurtad0** [comment]
Yes, thanks @luisramos0 - indeed, in the case of Katuma, I was looking at the Enterprise. In the the customer's report this social-media info is indeed absent.

Thanks again and sorry for the false alarm. Ready to go.

**Comment by luchiago** [comment]
Thank you guys @filipefurtad0 @luisramos0 for reviewing

**Pull request merged**
