### PR TITLE
issue 3777 - Make all map icons green

### LINKED ISSUE #3777: Make all map icons green
## Description
Many new users to OFN ask why the map icons are two different colours and ask why so many shops on OFN are closed. They ask what is wrong with the software if there are a lot of users that don’t use the platform. And they ask why their own shops appear closed when they are open. This is an annoying question for administrators and onboarders to have to answer all the time.

The current colors are based on this diagram:
image

**- As a:** non logged in user (or any logged in user - so anyone basically)
**- On page:** /map
**- I want to be able to do:** see all icons in green

## Acceptance criteria

Visiting /map I should only see green icons. No more white or red.

### PR DESCRIPTION
**Pull request by eelcodevlieger**
Closes #3777 - Make all map icons green

#### What should we test?
Check that that the Map icons [producer, shop, hub] display OK and all show green.

Would be good to cross check against the map page before the change to check different icon states (outline icons and red icons) all have been successfully mapped to a green icon.

Confirm other icons on the site referring to shop/hub/producer remain unchanged.

#### Release notes
Make all map icons green

#### Changelog Category:
Changelog Category: Changed

#### Documentation updates
If there are any references to the old state model diagram (see issue details) in the documentation, this will need to be removed.

### CODE REVIEW

**Comment by luisramos0** [comment]
hello!!! Can you pls explain the approach? Are you replacing the icons? How did you generate the new icons? Are they all the same icon? (if so, maybe a single file would be better).
Thanks!

**Comment by eelcodevlieger** [comment]
Hi Luis,
Where there was no solid green icon available, I used Inkscape to edit the solid red icons and set it to fill colour rgba 0b8c61ff 

Replaced all existing icons for solid green equivalents.

It will indeed be more efficient to use a single icon for each type, but I am not able to test this locally (no Google Maps API key), so went for the safe option.

About to test this in staging to confirm it working.

If it works OK I can add a further commit to improve.

**Comment by Matt-Yorkley** [comment]
Staged on: https://staging.katuma.org

**Comment by RachL** [comment]
This is ready to go! thank you @eelcodevlieger :)

Testing notes:
https://docs.google.com/document/d/1ant2xnXTyCYZkiKNKJpYT9uKYjgHtusNsRMIkt300Rs/edit#

**Comment by sauloperez** [comment]
Congrats @eelcodevlieger :tada:!

**Pull request merged**
