### PR TITLE
Show commit in CI

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?
https://openfoodnetwork.slack.com/archives/GK2T38QPJ/p1681180450549159

> I’ve just found two instances where CI (linting and testing) appears to be running from a rebased version of the PR branch. That is, the PR branches off an old version of master, but when running in CI it appears to include the latest changes from master.

`actions/checkout@v3` actually creates a merge commit into master, to ensure you're testing the latest as close to master as possible. That's all well and good, but quite confusing when you see errors in CI that aren't present in the actual PR branch. Hopefully this will be a clue when such confusions arise.

#### What should we test?
When viewing the CI logs for linters or specs, we should be able to see the commit ID and name (which mentions the merge)

#### Release notes

Changelog Category: Technical changes > CI

#### Documentation updates
Have already added a section here: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Continuous-Integration

### CODE REVIEW

**Review by jibees — APPROVED** [review]
👌 
Thanks, this should probably makes things easier to understand!

**Comment by mkllnk** [comment]
> actions/checkout@v3 actually creates a merge commit into master

My understanding was that it checks out the merge commit which was created by Github. I'm not 100% sure how often that commit is updated. But I think that if you push to master and then trigger CI manually that it will pick up the new commits.

**Review by mkllnk — APPROVED** [review]
Excellent, thank you.

**Comment by dacook** [comment]
> My understanding was that it checks out the merge commit which was created by Github.

I later saw this in the logs:

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +f63835b5cf2c5bbe0f02143c75de8a2136ae65f2:refs/remotes/pull/10678/merge
```

Presumably `/merge` requests a merge commit for master, which perhaps Github creates on demand.

**Comment by mkllnk** [comment]
Yes, that's it.

**Pull request merged**
