### PR TITLE
Update the base Ubuntu Docker image from 18.04 to 20.04

### LINKED ISSUE #6152: Update the base Ubuntu Docker image from 18.04 to 20.04
Ubuntu 18.04 is out of date because version 20.04 was released 6 months ago.

### PR DESCRIPTION
**Pull request by ipalo**
#### What? Why?

Closes #6152 

Update the base Ubuntu Docker image to version 20.04

Changelog Category: Changed

#### what to test
This is a dev test, someone needs to try this locally and verify it works for them: the local server runs successfully as before.

### CODE REVIEW

**Review by Matt-Yorkley — COMMENTED** [review]
What's the motivation here? Our servers are not on Ubuntu 20 yet, so I'm not sure moving the dev environment to Ubuntu 20 is a great idea...

**Comment by ipalo** [comment]
Hey @Matt-Yorkley,
Ubuntu 20 is the current LTS and I followed the specs of [the issue #6152 ](https://github.com/openfoodfoundation/openfoodnetwork/issues/6152) as agreed with @luisramos0

Let me know if you prefer moving this PR to another base branch.

**Comment by luisramos0** [comment]
imo this will have to done anyway at some point. we will have v20 in prod at some point.
I am already on ubuntu 20 on my laptop. I dont see a problem having docker on 20 as well :+1:

**Review by Matt-Yorkley — APPROVED** [review]

**Review by luisramos0 — APPROVED** [review]

**Comment by sauloperez** [comment]
test and working! :tada: thanks for this contribution @ipalo !

**Pull request merged**
