### PR TITLE
🔧 Remove `new_products_page` and all associated controllers/components/...

### LINKED ISSUE #11273: [BUU] Remove new_products_page feature toggle
## Description

Let's remove this toggle which is not used anymore!

### PR DESCRIPTION
**Pull request by jibees**
👑 `new_products_page` is dead, long live `admin_style_v3` ! 👸
#### What? Why?

- Closes #11273 

#### What should we test?
- You should not be able to activate `new_products_page` feature toggle
- Automatic specs and release testing should be enough

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Good cleanup.

**Review by rioug — APPROVED** [review]
It's a bit sad to see code that hasn't made it to production being discarded, anyone nice cleaning !

**Comment by jibees** [comment]
Just added @dacook as a reviewer so he knows

**Comment by RachL** [comment]
Seems to work! merging

**Pull request merged**
