### PR TITLE
Vcr stripe accounts controller spec

### LINKED ISSUE #12201: [Integration/API tests] /spec/controllers/admin/stripe_accounts_controller_spec.rb
### What we should change and why (this is tech debt)

Replacing stubs with real VCR calls.

### Context

Contributing to #11890.

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

- Closes #12201.

Provides real Stripe data to controllers, even in cases in which these don't make real http calls. Not sure all changes are necessary/relevant - question to reviewers :-)

#### What should we test?

- green build.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , 

When I `rspec spec/controllers/admin/stripe_accounts_controller_spec.rb:60` to test `it "redirects to unauthorized" do`,
I get a `Stripe::AuthenticationError: Invalid API Key provided: bogus_key`.
Which seems ok since there is no config in the test, but I was wondering how did your tests passed ?

Regarding if controllers send real HTTP, I think the answer is yes. The File VCR wrote tells me an answer with a 401 (Unauthorized), a time, a server(nginx- which is not the local server I use).
The VCR files generated in the this draft-PR seem to me that real call have been made. Do you have a doubt on one of the call in particular ?

**Comment by filipefurtad0** [comment]
Hey @cyrillefr ,

> I get a Stripe::AuthenticationError: Invalid API Key provided: bogus_key.

It like the spec is fetching the API key from `.env.test`, which should only happen when running the tests CI. To prevent this from happening, the API key I've sent via DM should be set on `.env.test.local`, which then overrides the previous file. Did you do so already? I'd try this in the first place, and then see if we can further debug.

> Regarding if controllers send real HTTP, I think the answer is yes. 

Thank you for confirming! This is a bit tricky for me, as I'm not entirely sure how controllers work in Rails. So, I guess all `get(:status, params:)` should be real http calls, and as such, possible to catch with VCR, right?

> Do you have a doubt on one of the call in particular ?

Thanks again. Indeed, I was wondering for some cases in particular, like the very first test case:

` it "redirects to Stripe Authorization url constructed OAuth" do`

 in which I've provided a real client ID:

`"scope=read_write&client_id=#{client_id}&response_type=code")`

I'm not sure how valuable this test is, I think the stubbed version would be ok as well. But I'm not sure.

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , I have not yet full read your answers and fixed what I needed to fix.

But, to be more precise about what are genuine calls and what are not genuine calls.
In the specs, when you have `get`, or `spree_delete`, those are not real calls.

Those mock calls match some rails methods defined in controllers.
For example, the `get :connect` at line 18 in the `stripe_accounts_controller_spec.rb` file match the `connect` method in the controller. This method ends with a `redirect_to Stripe::OAuth.authorize_url(url_params)`.
But the Stripe::OAuth object is a real object and do a genuine call, this is no mock (though I am not certain it calls something or the url is in the api itself).
So, in a way, a real interaction with Stripe is done, but not directly with a get(which can only match internal controllers of the app), but the controller does some real stuff.

Some real call in specs can be mocked with webmock, those calls replace some genuine calls, some external calls.
You can see in webmock some real url, it is not for internal purpose.
I have looked at the generated yml files and the url seem to go the stripe website, so to me, it show that real calls have been made.

A thing I wonder though, is there are some real call made to create some Stripe account ( I don't know if those are deleted or if there are many that have been created). I would need to check with the api.

**Comment by filipefurtad0** [comment]
Hey @cyrillefr ,

Many thanks for your reply and contribution to this effort.

> In the specs, when you have get, or spree_delete, those are not real calls.

The example you've provided makes sense to me. Even if there would be a real http call from `get :connect` on line 18, VCR would not catch it, as I've set the tag `:vcr, :stripe_version ` only on the examples below (a bit off topic: this tag is set in our `base_spec_helper.rb` and is meant to facilitate the re-recording of cassetes)

So, I've rebased the PR, set the tag at the top of the spec file. So, if `redirect_to Stripe::OAuth.authorize_url(url_params)` is a real call, then VCR should capture it, but it does not seem to be the case. So, indeed, I'm not sure changing this specific test brings any added value (as opposed to keep it as it initially was, with "fake" client id)

 
> A thing I wonder though, is there are some real call made to create some Stripe account ( I don't know if those are deleted or if there are many that have been created).

I think this might be due to the let statements added on some commits, like the `let(:connected_account)`, in which a real Stripe call is made, by the code I've introduced. This is intended to provide the controller with real data.

In addition that, there is this block:

```
            it "returns with a status of 'access_revoked'" do
              expect {
                response = get(:status, params:)
              }.to raise_error Stripe::PermissionError, message
            end
```

Which I think also calls a real http request, as the cassette `returns_with_a_status_of_access_revoked_.yml` has indeed a `code: 403`... So this is a case in which I think the PR might bring some actual improvement.

Other than this case, I'm not very sure.

Somewhat mysteriously :eyes: (it's never great when things work but we don't know why, I guess) the build is now green, after rebasing and re-recording the cassettes. So, I'm marking this as ready for review.

Really appreciate you taking the time to reflect and contribute to my better understanding of this issue - many thanks @cyrillefr :pray: :bouquet:

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , I have a problem with the spec at line 55
`context "when I don't manage the enterprise linked to the stripe account" do`

Before the test, there is an object `Stripe::Account` that is created.
But at the end of the test, the object that is being destroyed is a `StripeAccount` (local object).
I do not understand very well why there is 2 objects and how they interact with each other.
(In `app/models/stripe_account.rb` method `deauthorize_and_destroy`)

But the thing is, every time, the spec is executed, the created object will not disappear afterwards.
I have checked with a `Stripe::Account.list`, and there is at least 60 of these objects created. 
I have got back in time only to 17th march. There are likely more.
By checking at the email properties of these objects, there are maybe other tests that may behave the same.
There are many `jumping.jack@example.com` as well as `lettuce.producer@example.com` and `carrot.producer@example.com`

**Comment by filipefurtad0** [comment]
Hey @cyrillefr ,

> Before the test, there is an object Stripe::Account that is created.
But at the end of the test, the object that is being destroyed is a StripeAccount (local object).

Thanks for raising this. I checked the Stripe documentation, and I think that, in this case, the reason why the OFN code destroys only the local object is that real Stripe accounts cannot be deleted (only test accounts), see:

https://docs.stripe.com/api/accounts/delete?lang=ruby

So, I'd say the logic is:

- create a "real" Stripe account (connected_account)
- incorporate this connected_account ID to create the local object
- destroy the local object (indeed, this is a local call! And not a real http call...)

One can argue, that it is not relevant whether we provide a "real" account id or a fake one... I'm not sure it is worth creating the real object. This is exactly the type of questions this PR raises to me - so again, thanks.

> I have checked with a Stripe::Account.list, and there is at least 60 of these objects created.

Indeed, we don't delete them - you are correct. They are piling up on the/(my) test developers account... I think this is harmless, but maybe I should do some manual cleaning... another option would be to add the something like 

```
after do
  Stripe::Account.delete(connected_account.id)
end
```
at the end of the spec. But, I'm thinking, whether this is the best option.

What do you think @cyrillefr ? I'll leave this in code review to have the feedback from other devs too.

**Comment by mkllnk** [comment]
> ```rb
> after do
>   Stripe::Account.delete(connected_account.id)
> end
> ```

That looks like a good solution to clean up the test account.

**Review by mkllnk — APPROVED** [review]
Good work.

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , I agree with @mkllnk.
Since the api_key allows to delete test account, it should be done.
Note that this is not allowed to do it with a production api key.

**Comment by filipefurtad0** [comment]
I've added a the necessary lines to remove the accounts created within this spec. We can see these are being deleted on the VCR cassettes. In a separate PR, I'll take the same approach for similar cases. Re-requesting review.

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Pull request merged**
