### PR TITLE
Update units when variant unit name is edited

### LINKED ISSUE #8495: Editing unit names is not correctly applied on shopfront
## Description

If you edit a unit name on a product sold by item, the shopfront does not display the unit name correctly everywhere. 

## Expected Behavior

Unit name is coherent

## Actual Behaviour

Only unit names on unit price is correctly edited.

## Steps to Reproduce

1. Change the unit name of a product already sold by item
2. See how the change is applied on the shopfront

## Animated Gif/Screenshot

An example in staging: 

In production (the user first save the product and made a mistake, now impossible to change it): 

## Workaround

I can't see one, hence s2.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v.4.1.7
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): Both

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

Closes #8495 

Made it so that when variant unit name is edited, units are updated. This makes it so that this change is reflected everywhere in the UI. 

variant_unit_name

#### What should we test?
- Changes to unit name for products sold by item should be reflected everywhere.

Changelog Category: Technical changes

### CODE REVIEW

**Comment by apricot12** [comment]
@Matt-Yorkley @filipefurtad0  I think this should fix the issue without messing with anything?

**Comment by Matt-Yorkley** [comment]
Nice, this is looking good :+1:

Just needs some specs now.

One thing I would look at (maybe in manual testing) is checking it with a product that has multiple variants (not just one).

**Review by Matt-Yorkley — APPROVED** [review]
Awesome :+1:

**Review by jibees — APPROVED** [review]
👌

**Comment by filipefurtad0** [comment]
Hey @apricot12 ,
I don't think this PR is an `easy-test`. Was this discussed somewhere?

**Comment by apricot12** [comment]
> Hey @apricot12 ,
> 
> I don't think this PR is an `easy-test`. Was this discussed somewhere?
> 
> 

Oh I thought it was rather easy to test. It wasn't discussed anywhere. My mistake.

**Comment by filipefurtad0** [comment]
No worries @apricot12 ,
The reason I've pointed this out is that we've [introduced a regression](https://github.com/openfoodfoundation/openfoodnetwork/issues/8553) last time we've tried to close #8495, as `Variant unit names` and `display as` appear in many places in the app - off the top of my head, on order confirmations (UI and Emails), reports, cart page...

**Comment by filipefurtad0** [comment]
For an Items product:

- Without `display_as` info, changing `Variant Unit Name` is now reflected coherently throughout the pages:

image

- Adding `display_as` info:
image

This seems **not to be correctly updated** in the:
- cart page (below) and order confirmation page
image

However, display as info is correctly updated on the reports section - OC Customer Totals Report:

image


This was verified to be coherently displayed throughout the app:

- Order Cycle (incoming/outcoming sections) 
image


I think this is good to go, as the missing test case seems not to be introduced by this PR. This can be seen on another staging server as well.

Merging and opening an issue for this last finding.

**Comment by Matt-Yorkley** [comment]
I'm guessing you added those items to the cart before changing the variant names? I think that's okay :ok_hand:

**Pull request merged**
