### PR TITLE
Remove unused spree route for products

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #[the issue number this PR is related to]

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by sauloperez** [comment]
Looks like we also need to update the calls to the path helpers

**Comment by RachL** [comment]
hello @luisramos0 I hope you are doing fine :) I'm wondering: shall we leave this PR open? Are you planing on taking it further?

**Comment by luisramos0** [comment]
Hello Rachel, sorry, I wont have time for this now.
This is a really good and simple clean up, would be good if someone could fix the build and ship it.

**Comment by RachL** [comment]
This PR is open since more one year now :( I will close it. We can reopen if needed.

**Pull request closed without merging**
