### PR TITLE
[draft] Adds turnip to the stack

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Adds [turnip](https://github.com/jnicklas/turnip) to the stack.

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
When adding the gem, getting:

```
Bundler could not find compatible versions for gem "json":
  In snapshot (Gemfile.lock):
    json (= 2.6.1)

  In Gemfile:
    json

    aws-sdk (= 1.67.0) was resolved to 1.67.0, which depends on
      aws-sdk-v1 (= 1.67.0) was resolved to 1.67.0, which depends on
        json (~> 1.4)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

Should be unblocked by #6347.

**Comment by jibees** [comment]
What I've done to install new gems:


- run `bundle update`
- `Gemfile.lock` is modified. Commit this file (this commit is `#1`)
- Add your gem in the `Gemfile`
- run `bundle`
- commit both `Gemfile` and `Gemfile.lock`: you're package is installed  (this commit is `#2`)
- drop commit `#1`

**Comment by filipefurtad0** [comment]
Alright, this is green now :+1: 
I'll play around with this to figure out if it brings us any value.

**Comment by filipefurtad0** [comment]
The benefit here would be to improve our communication between dev - product - test, but honestly, I think we communicate quite well, because we are a small team and because we have several people having "many hats". I might be wrong, but it sounds to me like this might make sense in bigger teams, in which the roles are very separated.

In conclusion, and from what I've gathered, it does not look like it is worth the overhead in learning this separate syntax.

Closing - till further notice or other opinions.

**Pull request closed without merging**
