### PR TITLE
removed translation or between buttons

### LINKED ISSUE #8457: Missing translation: "or" between buttons
## Description
On several pages there is "or" displayed between two buttons. The text cannot be translated in Transifex. So it should be added to Transifex or it could be removed completely, because it is not very common to have "or" between two buttons.

## Expected Behavior
The text "or" should be translated or removed.

## Actual Behaviour
The text "or" is present on some pages and can't be translated.

## Steps to Reproduce
1. Log in
2. Choose a language other than English
3. Go to /admin/order_cycles
4. Klick 'new schedule' ('neuer Zeitplan' in German)
5. In the opening modal you will see "or" between the two buttons

## Animated Gif/Screenshot
image

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.6
* Browser name and version: Chrome 95.0.4638.69 (Offizieller Build) (64-Bit)
* Operating System and version (desktop or mobile): Windows 10, Desktop

## Possible Fix
1. Make the string "or" translatable.
2. Remove (all appearances of) the string "or".
Decision by Product/Delivery circle required which way to go.

### PR DESCRIPTION
**Pull request by Dmoment**
#### What? Why?

Closes #8457

On several pages, there is "or" displayed between two buttons. This has to be removed as per issue #8457 

### Steps to Reproduce
- Log in
- Choose a language other than English
- Go to /admin/order_cycles
- Click 'new schedule' ('neuer Zeitplan' in German)
- In the opening modal you will see "or" between the two buttons

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Can we now remove it from the translations file?

https://github.com/openfoodfoundation/openfoodnetwork/blob/a5b0324f768016974796152af70688d7b4e316a1/config/locales/en.yml#L348

https://github.com/openfoodfoundation/openfoodnetwork/blob/a5b0324f768016974796152af70688d7b4e316a1/config/locales/en.yml#L3359

https://github.com/openfoodfoundation/openfoodnetwork/blob/a5b0324f768016974796152af70688d7b4e316a1/config/locales/en.yml#L3852

**Comment by Dmoment** [comment]
> 

Now we have to remove this from the transitions file of all the supported languages.

**Comment by mkllnk** [comment]
> Now we have to remove this from the transitions files of all the supported languages.

No, we just remove it from `en.yml` and the other files will get updates automatically through our Transifex process.
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

Will you do it in this pull request?

**Comment by Dmoment** [comment]
> > Now we have to remove this from the transitions files of all the supported languages.
> 
> No, we just remove it from `en.yml` and the other files will get updates automatically through our Transifex process. https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29
> 
> Will you do it in this pull request?
Removed it from `en.yml` here itself.

**Review by mkllnk — COMMENTED** [review]
Great!

I think I found a couple more places with `or`:

- app/assets/javascripts/templates/admin/show_more.html.haml
- app/views/split_checkout/_guest.html.haml

**Comment by Dmoment** [comment]
> Great!
> 
> I think I found a couple more places with `or`:
> 
> * app/assets/javascripts/templates/admin/show_more.html.haml
> * app/views/split_checkout/_guest.html.haml

Removed them as well.

**Review by mkllnk — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @Dmoment ,
Is this your first issue? Welcome! :tada: 

I've checked the pages in which you've introduced the code changes, the or string is gone now. On the images below, left (before this PR), right - after this PR:

- `admin/order_cycles` - adding a schedule

image

- `/order/<order_id>/edit`

image

- all pages under` /admin/products/<product_name>/`

**edit**, images, variants, **product properties**, group buy options, search (bold below):

image


image

There is a minor formatting glitch here, already per-existent. I'll open an issue for these pages.


- `admin/products/new`

image


Good to go! Thank you :rocket:

**Comment by Dmoment** [comment]
Thank you. It feels great to get my PR merged. I will be creating more.

**Pull request merged**
