### PR TITLE
Fix: Issue #8459 Missing translation: "Product" in product created confirmation message

### LINKED ISSUE #8459: Missing translation: "Product" in product created confirmation message
## Description
When creating a new product, the confirmation message at the top of the screen is not fully translated. It starts with untranslated "Product xy".

## Expected Behavior
"Product" in the confirmation message should be translated.

## Actual Behaviour
"Product" in the confirmation message is not translated.

## Steps to Reproduce
1. Choose a language other than English.
2. Log in.
3. Go to /admin/products
4. Klick 'new product' ('neues Produkt' in German)
5. Fill in all required field and select 'new'
6. Observe the confirmation message at the top of the screen

## Animated Gif/Screenshot
image

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.6
* Browser name and version: Chrome 95.0.4638.69 (Offizieller Build) (64-Bit)
* Operating System and version (desktop or mobile): Windows 10, Desktop

### PR DESCRIPTION
**Pull request by gjacob3000**
#### What? Why?

Closes #8459 

Added a new function to **base_controller.rb**, _flash_message_for_w_resource_ that looks at the resource name and applies the newly translated resource name to the resource_desc; this fix could be applied to numerous Missing Translation bugs in the issues page. I changed the function call for _create_ in **products_controller.rb** to implement this change and pass in the translated product (using t[:product]) to the resource name and continue the function as before. I added this function to base_controller to minimize the interference with other code items and isolate this issue. 

This change was necessary since the previous **base_controller** function, _flash_message_for_, did not apply the translated resource name and only applied the English version directly, so there had to be a t() included to the resource name to access the yaml translations.

#### What should we test?
Since we isolated this issue only to **products_controller.rb**, we made a new function in **base_controller.rb**; we just need to test if the function create is acting inappropriately.

#### Attachments
Video Replicating the error with fix:
https://user-images.githubusercontent.com/49418660/145761466-7f5403d4-156a-4f76-bccc-74468726e5b7.MOV

Image of Error Fix (Correctly translating "Product" to "Produkt"):
IMG_8280

### CODE REVIEW

**Review by jibees — CHANGES_REQUESTED** [review]
Thanks @gjacob3000 !
I'd squash all the three commits, to get a git history much more clean (and avoid commit about linter)

**Comment by gjacob3000** [comment]
> Thanks @gjacob3000 ! I'd squash all the three commits, to get a git history much more clean (and avoid commit about linter)

Hey I am had some issues squashing, please let me know if that worked!

**Comment by jibees** [comment]
> > Thanks @gjacob3000 ! I'd squash all the three commits, to get a git history much more clean (and avoid commit about linter)
> 
> Hey @jibees, I had some issues squashing, please let me know if that worked!

Actually, not. As you can see, there are 5 commits on your PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/8613/commits

Seeing only one is the goal to reach. You can recreate a branch and another PR if you're stuck ;)

**Comment by gjacob3000** [comment]
> > > Thanks @gjacob3000 ! I'd squash all the three commits, to get a git history much more clean (and avoid commit about linter)
> > 
> > 
> > Hey @jibees, I had some issues squashing, please let me know if that worked!
> 
> Actually, not. As you can see, there are 5 commits on your PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/8613/commits
> 
> Seeing only one is the goal to reach. You can recreate a branch and another PR if you're stuck ;)

Okay! I just created a new PR that encompasses it all in 1 commit!

**Pull request closed without merging**
