### PR TITLE
Bring some basic js functions and dependencies from spree_backend

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Continues #4595 

In this PR we bring from spree_backend the following code:
- admin.js.erb (becomes admin/spree/base.js in ofn now)
- we merge existing override show_flash_error with original from spree in admin.js
- require spree.js for some basic helper functions in spree_core like Spree.url
- to align checkboxes jquery.vAlign
- to make the main spinner work: spin, progress.coffee and progress css
- to make the main menu work: jquery.horizontalNav
- to make select2 work: admin/spree-select2 and plugins/select2.css
- to improve right side menu and the list of payment gateways in the edit order pages: equalize

#### What should we test?
We need to validate the following behaviors:
- producer properties are sortable, edit an enterprise that is a producer and edit/sort it's properties (known issue here: you have to press update to see a new empty input field appear to add a second property)
- date pickers still work - searching for orders for example
- tooltips are still working, for example, editing a enterprise group user, there should be a what's this tag with a tooltip.
- to align checkboxes jquery.vAlign, in the orders search page, checkbox "completed orders" is aligned with the top of the input box on its left, like this:
Screenshot 2019-12-29 at 10 51 42
- I am not sure what exactly jquery.horizontalNav is doing but lets keep it and make sure the main menu in the backoffice looks good in different browsers and windows sizes
- verify select2 inputs work in orders search page for example, verify filter status and distributors
- verify that the right side menu and the list of payment gateways in the edit order pages are aligned

#### Release notes
Changelog Category: Changed
Bring some basic js functions from spree_backend to make OFN independent of Spree.

### CODE REVIEW

**Comment by luisramos0** [comment]
There was a problem with the assets compilation and now with the build. I'll get this ready for testing tomorrow.

**Comment by luisramos0** [comment]
This is deploying correctly now. Ready for testing.

**Comment by lin-d-hop** [comment]
date pickers work - checked in searching orders and defining OCs.
tooltips are working - checked throughout enterprise settings.
orders search page checkbox - aligns as per description above
main menu in the backoffice - looks good in Chrome, Firefox and mobile
Spinner - not really sure how to test this.... seemed to work fine.
Filters in order search page work
All Edit Order pages align and appear correctly in Chrome and Firefox.

I think this is good to go.

However while testing the page has become conflicted ping @luisramos0 

Fingers crossed that I don't need to retest after these conflicts are fixed.

**Comment by luisramos0** [comment]
great, thanks a lot for testing.
conflicts are minor. I am merging.

**Pull request merged**
