### PR TITLE
Reimplement tabs on shopfront using our custom tab directive

### LINKED ISSUE #1171: Shopfront sections (about, producers...) not collapsing
## Description
As a user when I am on any shopfront, if I click on "about" or "producers" or "contact" or "groups" tab within the shopfront, the content expant, but when I click on the small arrow to collapse it, it doesn't work.
shop_sections

## Expected Behavior
When I click on the "collapse" arrow it collapses and I don't see the content anymore.

## Actual Behavior
It doesn't collapse.
On mobile, where a section contains a lot of content, the user must scroll past all of the section content to reach the products

## Steps to Reproduce
1. Go to any shopfront (for instance https://www.openfoodfrance.org/hub-demo-open-food-france/shop)
2. Click on any of the inner tabs.

## Severity
S3, this is pretty annoying when navigating a shopfront and affecting many users.

## Your Environment
PC, French production (all productions), Chrome

## Possible Fix
When in the product edit page, if I hit cancel, i should be directed to Bulk Product Edit page.

### PR DESCRIPTION
**Pull request by oeoeaio**
#### What? Why?

Closes #1171
Tabs in the shopfront were not able to be closed because they were using the directives from `angular-foundation` which do not have this functionality. I have reimplemented them using our own tab directive (which is already is use on the account page).

#### What should we test?

- [ ] Tabs on all shopfront/checkout pages should behave exactly as they did before, except they should be able to be closed again by clicking on tab once open.
- [ ] The look and feel of the tabs should also not have changed at all
- [ ] Should probably check behaviour on a mobile device

#### Release notes

Tabs is shopfront pages can be be closed again after they have been opened

### CODE REVIEW

**Comment by myriamboure** [comment]
Awesome @oeoeaio ! Thanks for taking the time to do that as you mentioned it in slack :-)

**Comment by daniellemoorhead** [comment]
Heya @Matt-Yorkley would be great if you could code review this at the start of the week so it can be tested and merged once @oeoeaio and Sally are back online.

**Comment by myriamboure** [comment]
Tests are not passing though @oeoeaio :-(

**Comment by myriamboure** [comment]
@oeoeaio you have merged this but it has not been teste, right? I had asked François to deploy yesterday night and he just did, should I test then?

**Comment by myriamboure** [comment]
screenshot from 2018-05-30 07-34-56
There is an issue @oeoeaio tabs are on two lines :-(

**Comment by mkllnk** [comment]
Oh no, that was my mistake. I pushed it to our staging server and also pushed it to production, because I thought it was tested already. Rob is displayed here, because I used our CI server.

**Comment by oeoeaio** [comment]
There is also an issue with styling, now that I look at it on production

**Pull request merged**
