### PR TITLE
Bump stimulus_reflex to 3.5.0-rc4 and cable_ready to 5.0.3

### PR DESCRIPTION
**Pull request by dacook**
* Bumps [stimulus_reflex](https://github.com/stimulusreflex/stimulus_reflex) **ruby gem and JS package** from 3.5.0-rc3 to [3.5.0-rc4](https://github.com/stimulusreflex/stimulus_reflex/releases/tag/v3.5.0.rc4).
* Bumps [cable_ready](https://github.com/stimulusreflex/cable_ready/releases/)  **ruby gem and JS package**  from 5.0.1 to [5.0.3](https://github.com/stimulusreflex/cable_ready/releases/tag/v5.0.3)
* Bumps [stimulus_reflex_testing](https://github.com/podia/stimulus_reflex_testing) to `main` (because latest fixes haven't been released yet).

### What should we test?
These are underlying frameworks used for the dynamic functionality on the below pages. Simply checking that they work as usual, with no errors in the dev console should be sufficient.
* BUU Bulk Edit Products - Delete (`/admin/products` with `admin_style_v3`)
* A report, eg `/admin/reports/packing/customer` (old or new design, doesn't matter)
* Admin Enterprise > Connected app
* Admin Orders > Any bulk action

### Dependencies
- Supersedes and closes https://github.com/openfoodfoundation/openfoodnetwork/pull/12260

### CODE REVIEW

**Comment by dacook** [comment]
😞 Yup, all Reflexes failed (evident in [failed-tests-screenshots](https://github.com/dacook/openfoodnetwork/actions/runs/8167360156/artifacts/1301036303))
Probably due to the version "mismatch"

**Comment by dacook** [comment]
It's very strange. Currently the Gemfiles say:
```
gem "cable_ready", "5.0.1"
  cable_ready (= 5.0.1)
```
And package.json / yarn.lock:
```
    "cable_ready": "5.0.2",

cable_ready@5.0.2, cable_ready@^5.0.0:
  version "5.0.2"
```
Yet there's no errors raised. 

On any attempt to upgrade, CableReady refuses to run, stating in the browser that the npm version is still 5.0.1:
```
CableReady failed to execute your reflex action due to a version mismatch between your gem and JavaScript version. Package versions must match exactly.

cable_ready gem: 5.0.3
cable_ready npm: 5.0.1
```

I checked, it's not:
```
grep 'version' node_modules/cable_ready/package.json
  "version": "5.0.3",
```

Even in the browser:
```
console.log(CableReady.version)
5.0.3
```

**Comment by dacook** [comment]
Yay, after upgrading stimulus_reflex, this now works!

**Review by rioug — APPROVED** [review]
:+1:

**Review by mkllnk — APPROVED** [review]
Great! :crossed_fingers:

**Comment by mkllnk** [comment]
Does this need testing? Maybe checking reports?

**Comment by dacook** [comment]
Yes, I think it should be treated the same as https://github.com/openfoodfoundation/openfoodnetwork/pull/12260 , which is awaiting testing, but also lacking test notes. 
I'll add some notes now.

**Comment by sigmundpetersen** [comment]
@dacook is this superseded by #12472 , same as #12260?

**Comment by dacook** [comment]
Oh, yes thanks. That's weird, I don't know how I missed this.

**Pull request closed without merging**
