### PR TITLE
Pre-compile all needed assets in CI environment

### LINKED ISSUE #11010: [Flaky] rspec ./spec/system/consumer/caching/shops_caching_spec.rb:17
### What we should change and why (this is tech debt)

`rspec ./spec/system/consumer/caching/shops_caching_spec.rb:17`

```
Failures:

  1) Shops caching caching enterprises AMS data caches data for all enterprises, with the provided options
     Failure/Error: expect(Rails.cache.exist?(key, options)).to be true
     
       expected true
            got false
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_shops_caching_caching_enterprises_ams_data_caches_data_for_all_enterprises__with_the_provided_options_155.png
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5263043188/jobs/9512817149
https://openfoodnetwork.slack.com/archives/C012LE8LLDS/p1686718490274599?thread_ts=1686601349.929099&cid=C012LE8LLDS

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #11010

We use Webpacker *and* Sprockets to compile assets. I hadn't realised
before that we were still compiling lots of JS with Sprockets. So even
after we pre-compiled assets with Webpacker, we still needed to compile
more assets on the first page visit in test environment. That made some
time-critical specs, like caching specs, fail.

This approach pre-compiles all assets but only in CI. Running the
compilation task adds 6.5 seconds even if there's nothing to compile
while the previous Webpacker call returned instantly. So I decided to
run the compilation only on CI and activated on-demand compilation to
the test environment.

Time-critical specs will still be flaky without pre-compilation locally
but I figured that a fair trade-off for faster specs in general. During
most development, we don't need all assets to be compiled and it's
faster to just compile what's needed. And running a time-critical spec
twice solves the flakiness.

**Do you agree with this approach?** Do you have a better idea?

#### What should we test?

- Specs only.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Good find !

**Comment by dacook** [comment]
Sorry I didn't get to have a good look at this yet. I don't like the idea of adding 6.5sec to most CI runs, but I'm not sure there's any better solutions. Maybe if we can isolate those specs that require sprockets we can run it only where needed. Will have a look next week.

**Comment by dacook** [comment]
Given that this adds time to compile all assets, which might not be used, I had a go at [Cache public assets in CI](https://github.com/openfoodfoundation/openfoodnetwork/pull/12580#top).
But I'm not sure it will work. @mkllnk do you might taking a look to see if it makes sense to you?

**Comment by mkllnk** [comment]
Oh, I had not realised that this is doubling CI run time, from 6 minutes to 12 minutes. That's not great, of course. The easiest quick fix in this case would be to put a `retry: 2` on the flaky spec. So in the second run the assets are compiled and the test should pass.

**Comment by dacook** [comment]
> this is doubling CI run time

Hmm that's weird, but certainly not good! 

Ideally, I'd like us to be able to cache the necessary parts to speed up the asset compilation, AND pre-compile as per this PR, because that replicates a prod instance.

But it doesn't seem practical, so  `retry` is an appropriate alternative.

**Pull request closed without merging**
