### PR TITLE
Move default versions of Paperclip-managed images to /public

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Related to #5643

Image paths for these files are handled by `Paperclip`, which (with our current version) does not handle fingerprints on assets. Therefore we need to make these default images available under /public. 

#### Release notes

Updated default paths for customisable images

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
In this specific case, it's only for default versions of images that are later overridden by new custom images uploaded via superadmin, in: https://github.com/openfoodfoundation/openfoodnetwork/pull/5682/files#diff-1245181b6af54c13d6edab80fd4e4f02

We don't need to do this for all the other images.

**Comment by Matt-Yorkley** [comment]
Brazil has just provisioned a new server, and immediately hit this issue...

**Comment by luisramos0** [comment]
ok :+1: 
did you find any other missing images in there?

**Comment by Matt-Yorkley** [comment]
> did you find any other missing images in there?

#5701

**Comment by filipefurtad0** [comment]
Hi @Matt-Yorkley ,

I verified the path was changed from /assets to /default_images/

I found these to appear on the homepage:

- /default_images/ofn-logo.png"
image

- /default_images/ofn-logo-mobile.svg
image

- /default_images/home.jpg
image

- /default_images/ofn-logo-footer.png
image

Checked several browsers with the Browserstack screenshot tool, the pics appear there as well, as seen in the results summary below (except for the non-compatible systems or timeouts):

image

Full results here:
[9aa41cea0e74c9b2f75fc9cfb63afee88f7cff1a.zip](https://github.com/openfoodfoundation/openfoodnetwork/files/4858637/9aa41cea0e74c9b2f75fc9cfb63afee88f7cff1a.zip)

Ofn-logo-mobile.svg seems to be broken, on Windows 10, IE11. This is seen by zooming in and out:
zoom_windows_ie11

This is not introduced by this PR nor v3, as it's also observed in staging-katuma. I'll open a separate PR for this.

I also checked that products with no picture display the ofn-logo.png - all good.

This looks ready to go.
Is there something else I should check @Matt-Yorkley?

**Comment by Matt-Yorkley** [comment]
That's fine :+1:

Thanks @filipefurtad0

**Pull request merged**
