### PR TITLE
Spree routes

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Quick test...

Closes #[the issue number this PR is related to]

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by luisramos0** [comment]
Is this working? I couldnt make devise work!!!

We can keep the spree namespace in a file like the api one.

You can just change the top line of the spree file to something like:
Openfoodnetwork::Application.routes.draw do

and remove the mount thing from the main routes file.

**Comment by Matt-Yorkley** [comment]
The devise stuff looks like there might be a couple of namespace issues, but I think they just need a bit of tweaking. The amount of code changes is a bit crazy. I think this change would be technically possible, but it would need more work. I'm not sure this is a good way to go, it was just a quick test...

**Comment by luisramos0** [comment]
I think it is a good change. Id leave the routes in the same file and go for it.

We can make it gradual by having the spree.rb file like this:

```ruby
Spree::Core::Engine.routes.draw do
  devise_for :spree_user,
  
  < start with everything here as is and then have individual PRs to move things below >
end

Openfoodnetwork::Application.routes.draw do
  namespace :spree do
     < gradual PRs that will move things from above into here >
   end
end
```

When all is migrated, remove the spree engine mount in the  main routes file.
what do you think about this approach?

**Comment by luisramos0** [comment]
What is the immediate benefit of this change? Is it necessary for rails 5?

Anyway we need to continue gradually with steps like #6723, right?

**Comment by luisramos0** [comment]
So we can continue with PRs like this: https://github.com/openfoodfoundation/openfoodnetwork/pull/6799/files

**Comment by Matt-Yorkley** [comment]
Yeah, I'll close it. this PR tries to change all of them at once, but there's some build errors that couldn't be resolved in relation to Ransack view helpers. Anyway, we can do this in small steps and I'm not sure it's blocking Rails 5.

**Pull request closed without merging**
