### PR TITLE
Convert specs to RSpec 3.7.0 syntax with Transpec

### LINKED ISSUE #2097: Disable `should` syntax in specs
## What? Why?

We are still using the very old RSpec should syntax. Chances are that this syntax won’t work in upcoming versions of RSpec and that may prevent us from upgrading RSpec in the future.

The problem is that we waste valuable time and energy reviewing the syntax used in a PR when this is better done by machines. We would be better off focusing on architecture and implementation.

This stems from https://github.com/openfoodfoundation/openfoodnetwork/pull/2084, which is a good example of this.

## Proposed solution

This needs to be disabled with RSpec itself. See https://relishapp.com/rspec/rspec-expectations/docs/syntax-configuration#disable-should-syntax.

## Dependencies

We tried doing it in https://github.com/openfoodfoundation/openfoodnetwork/pull/2180 but as explained in https://github.com/openfoodfoundation/openfoodnetwork/pull/2180#issuecomment-376897246, it can't be done until we reach Spree 3.0.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Partially addresses #2097 

This disables `should` syntax and converts all existing specs to `expect` syntax.

This conversion is done by [Transpec](http://yujinakayama.me/transpec/) 3.3.0 with the following command:
    transpec

* 1858 conversions
    from: obj.should
      to: expect(obj).to

* 888 conversions
    from: == expected
      to: eq(expected)

* 368 conversions
    from: obj.stub(:message)
      to: allow(obj).to receive(:message)

* 219 conversions
    from: obj.should_not
      to: expect(obj).not_to

* 111 conversions
    from: obj.should_receive(:message)
      to: expect(obj).to receive(:message)

* 89 conversions
    from: obj.stub(:message => value)
      to: allow(obj).to receive_messages(:message => value)

* 74 conversions
    from: it { should ... }
      to: it { is_expected.to ... }

* 24 conversions
    from: it { should_not ... }
      to: it { is_expected.not_to ... }

* 19 conversions
    from: obj.stub_chain(:message1, :message2)
      to: allow(obj).to receive_message_chain(:message1, :message2)

* 7 conversions
    from: Klass.any_instance.stub(:message)
      to: allow_any_instance_of(Klass).to receive(:message)

* 7 conversions
    from: lambda { }.should_not
      to: expect { }.not_to

* 6 conversions
    from: Klass.any_instance.should_receive(:message)
      to: expect_any_instance_of(Klass).to receive(:message)

* 5 conversions
    from: =~ /pattern/
      to: match(/pattern/)

* 4 conversions
    from: < expected
      to: be < expected

* 1 conversion
    from: === expected
      to: be === expected

* 1 conversion
    from: > expected
      to: be > expected

* 1 conversion
    from: Klass.any_instance.should_not_receive(:message)
      to: expect_any_instance_of(Klass).not_to receive(:message)

* 1 conversion
    from: obj.should_not_receive(:message)
      to: expect(obj).not_to receive(:message)

* 1 addition
      of: RSpec.configure { |c| c.infer_spec_type_from_file_location! }

For more details: https://github.com/yujinakayama/transpec#supported-conversions

#### What should we test?

No behavior change. With green tests is enough.

#### Release notes

Test suite converted from RSpec's `should` to `expect` syntax.

### CODE REVIEW

**Comment by sauloperez** [comment]
:scream: just a single spec failing! #science

**Comment by sauloperez** [comment]
For unknown reasons the CI status checks got lost. This is still failing https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-2180/builds/4 due to the latest commit.

**Comment by sauloperez** [comment]
Spree still uses `should` syntax in 2.0 and so makes it impossible to disable that syntax :see_no_evil: . See https://github.com/openfoodfoundation/spree/blob/fe0a1311abb097bf3ac8001a24246c6cff5ecdbb/api/lib/spree/api/testing_support/helpers.rb#L10.

**Comment by enricostano** [comment]
I would keep the changes, remove the syntax check and create an issue to do that once we get to 2.0. a.k.a. blocked by spree upgrade

**Comment by sauloperez** [comment]
Unfortunately, Spree **still** uses `should` in 2.0...

**Comment by enricostano** [comment]
Blocked by 3.x then

**Comment by myriamboure** [comment]
Shall we create an epic for Spree 3.x and attached the stories we find to be blocked by it so that we keep track of them?

**Comment by sauloperez** [comment]
As you wish @myriamboure

**Comment by sauloperez** [comment]
I updated the issue this PR was pointing to :point_right: https://github.com/openfoodfoundation/openfoodnetwork/issues/2097

**Comment by daniellemoorhead** [comment]
Heya, I'm moving this into the blocked column as it can't be worked on till it's unblocked.

**Comment by sauloperez** [comment]
Not worth keeping this being so out of date. We won't lose track of it since there's an issue.

**Pull request closed without merging**
