### PR TITLE
[Rails 5.2] Tap/map error on cart service

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?
Quite a few errors like this in the build:
```
  14) CartController adding a group buy product to the cart sets a variant attribute for the max quantity
      Failure/Error:
        (data[:variants] || []).map do |variant_id, quantity|
          if quantity.is_a?(Hash)
            { variant_id: variant_id, quantity: quantity[:quantity], max_quantity: quantity[:max_quantity] }
          else
            { variant_id: variant_id, quantity: quantity }
          end
      
      NoMethodError:
        undefined method `map' for <ActionController::Parameters {"1704"=>1} permitted: false>:ActionController::Parameters
        Did you mean?  tap
      # ./app/services/cart_service.rb:109:in `read_variants_hash'
      # ./app/services/cart_service.rb:105:in `read_variants'
      # ./app/services/cart_service.rb:20:in `block in populate'
      # ./app/services/cart_service.rb:19:in `populate'
      # ./app/controllers/cart_controller.rb:9:in `populate'
      # ./spec/support/controller_requests_helper.rb:49:in `process_action_with_route'
      # ./spec/support/controller_requests_helper.rb:27:in `spree_post'
      # ./spec/controllers/cart_controller_spec.rb:117:in `block (4 levels) in <top (required)>'
      # ./spec/controllers/cart_controller_spec.rb:116:in `block (3 levels) in <top (required)>'
```

This is caused by the fact the params passed are no longer an hash but ActionController::Parameters that does not have the method map. Here we use each and build an array from it.

#### What should we test?
No errors with tap/map in the build.
 
#### Release notes

Changelog Category: Technical changes
Adapt code to rails 5.2

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]
🙏

**Review by sauloperez — COMMENTED** [review]
Nice! Codecov is telling us that line 112 is no covered by any test. Would you mind adding/changing a controller test to do so @luisramos0 ?

**Review by Matt-Yorkley — APPROVED** [review]
:muscle:

**Comment by luisramos0** [comment]
Actually the coverage was there but the spec was still sending an hash and not the Parameters object that is sent by the controller now :+1:

**Comment by andrewpbrett** [comment]
Hm it looks like something in this PR is causing the test-consumer-features job to hang indefinitely. I tried running the changed spec locally and it passes immediately.

**Pull request merged**
