### PR TITLE
Updates build environment to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Relates to https://github.com/openfoodfoundation/openfoodnetwork/pull/9557
and to https://github.com/openfoodfoundation/openfoodnetwork/pull/10618

This is a bit of a test, to check if our build breaks when we run our test suite under Ubuntu 22.04

#### What should we test?

- green build

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
Maybe we could create an [env. variable](https://docs.github.com/en/actions/learn-github-actions/variables#using-the-env-context-to-access-environment-variable-values)?

```yaml
env:
  RUNS_ON: ubuntu-22.04
```

and use it like:
```yaml
runs-on: env.RUNS_ONE
```

**Comment by filipefurtad0** [comment]
> Maybe we could create an [env. variable](https://docs.github.com/en/actions/learn-github-actions/variables#using-the-env-context-to-access-environment-variable-values)?

Thanks @jibees - now committed and squashed :+1

**Comment by dacook** [comment]
Good idea!

The actions seemed to queue indefinitely (more than 4 hours) so I cancelled and retried. Looks like the environment variable isn't right.
```
Requested labels: env.RUNS_ON
Job defined at: openfoodfoundation/openfoodnetwork/.github/workflows/build.yml@refs/pull/10683/merge
Waiting for a runner to pick up this job...
```

According to the [docs](https://docs.github.com/en/actions/learn-github-actions/variables), I think this should work:

```yml
runs-on: $RUNS_ON
```

**Comment by dacook** [comment]
I checked if we should update the brakeman and linter workflows. 
We already use `runs-on: ubuntu-latest`, which seems fine.

**Comment by dacook** [comment]
Question: should we proceed with this now, or wait until we have a server environment on this OS before making this change?

**Comment by jibees** [comment]
I've force-pushed a commit to change that, thanks @dacook. 
CI is green now.

**Comment by jibees** [comment]
> Question: should we proceed with this now, or wait until we have a server environment on this OS before making this change?

With ubutun-22.04 on CI:
 - we can spot errors that occurs with ubutun-22.04
 - but we cannot see errors for others (ie. the ones used in prod env) ubuntu.

But as we want to upgrade to ubuntu-22.04, I think it's a good move to have CI on ubuntu-22.04

**Comment by sigmundpetersen** [comment]
Moving this to Code Review.
Would be good to have @mkllnk's opinion on if we should move forward with this

**Review by mkllnk — APPROVED** [review]
Great! Thank you!

**Review by rioug — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
Thank you for trying all that out, @rioug. Tedious work but important. :pray:

**Pull request merged**
