### PR TITLE
Fix display issue in product image edit page

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Fixes a minor display regression with new image sizes in admin product edit page.

#### What should we test?

In admin product edit, when uploading an image the thumbnail isn't so big it breaks the layout.

#### Release notes

Changelog Category: User facing changes

Fixed image layout regression in product edit image page.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Before and after:

Screenshot from 2020-11-03 18-45-06
Screenshot from 2020-11-03 18-45-17

**Review by luisramos0 — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Before:

image

After:

image

Looking good now :+1: 

PS: reducing the broadness of the window allows a slight "under-lap" of the pic:

image

This is backoffice here, so I think this is fine... do you feel this needs an issue? Ping @RachL

**Comment by RachL** [comment]
@filipefurtad0 I'm not sure. Let's see if we found a bigger problem? Here it's not perfect but it's readable. With the product catalog getting an uplift I'm guessing we will soon redo these kind of pages.

Nice eggs by the way!

**Comment by Matt-Yorkley** [comment]
That's large tablet kind of size, right? I think we can go ahead with this for now :+1:

**Comment by filipefurtad0** [comment]
That was a somewhat smaller window, but on my laptop screen, using Firefox 82/Ubuntu 20.04 (sorry, I should have mentioned it before), see:

zeamays

This is on laptop as well, Chrome 86:

zeamays_chrome

Perhaps could be improved, but this PR is already a major fix :+1:

**Comment by Matt-Yorkley** [comment]
If anyone tries to use admin with a screen that size, that tiny bit of overlap will be the least of their problems :sweat_smile:

**Pull request merged**
