### PR TITLE
[Spree 2.1] Paypal gem test

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Related to #4645 

This uses the (new) `2-1-0-stable` branch of the paypal gem. It's the `2-1-stable` branch plus a couple of old OFN modifications (from 2-0-stable) cherry-picked on top, plus a minor modification to the gemspec to allow it to be used with spree_core `2.1.0`.

Rebased on top of `luisramos0/3-0-latest` for better spec visibility.

The new paypal gem branch is here: https://github.com/openfoodfoundation/better_spree_paypal_express/commits/2-1-0-stable

### CODE REVIEW

**Comment by luisramos0** [comment]
we are doing the same thing :see_no_evil: 
https://github.com/openfoodfoundation/openfoodnetwork/pull/4825/commits/ef47527dfac69aad40a08e622c66d3a3e024c6fd

**Comment by Matt-Yorkley** [comment]
Okay... all but one of the Paypal-related specs are now passing with the new adapted gem. :tada:

The final one is a feature spec that tests for a flash (error) message during checkout. The flash message is expected to contain: `PayPal failed`, but the error message being shown seems to be a generic one that was added in a recent commit which altered checkout failure messages: `The checkout failed. Please let us know so that we can process your order.`

I'm not sure if this is caused by the Paypal gem not working, or by the recent change in checkout error responses...

**Comment by Matt-Yorkley** [comment]
Aha! It looks like there was a sneaky `ActiveModel::ForbiddenAttributesError` hiding somewhere deep in the checkout process. The unrecognised error got caught by the new rescue block in #4699, which interrupted the regular error response in the test...

I'll do some more investigating.

**Comment by Matt-Yorkley** [comment]
All passing after a rebase on `luisramos/3-0-latest` and an extra commit for updating a broken spree_routes helper. I think it's ready :tada:

I'll submit a new PR when we've merged all the open ones, there's some messy conflicts at the moment.

**Comment by Matt-Yorkley** [comment]
This PR was for testing only. Already merged in: #4862

**Pull request closed without merging**
