### PR TITLE
Add final weight to occt report 

### LINKED ISSUE #10036: Add Final Weight to Order Cycle Customer Totals report
## Description

In the 'Bulk Order Management' page (BOM) you can change the weight of a sold product. Currently there is no way to see this information in the reports.

Let's add an additional column to the OC Customer Totals report on each line item that has a Final Weight for that line item.

In the case that the weight has not been changed in BOM this column should give the variant weight
In the case that the weight has been changed in BOM and qty = 1 this column should give the change weight
In the case that the weight has been changed in BOM and qty > 1 this column should give the sum of changed weights eg if 2x salad were 145g and 160g then the value should be 305g

## Acceptance Criteria & Tests

1. Add new column to the 'Order Cycle Customer Totals' report - 'Final Weight'
2. Column to be added to the end of each row.
3. Ensure that the 3 cases outlined above are all met. Test with qty of 1, 2 and something >2 at least.
4. These columns to be hidden by default in UI. API will return all data 'columns'.
5. All fields translatable
6. Unit test to cover this functionality.

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #10036 

#### What should we test?

- Described on: #10036 

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by abdellani** [comment]
I think there's a problem in the [test](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/lib/reports/orders_and_fulfillment/order_cycle_customer_totals_report_spec.rb#L47)

When I selected "CSV" format in the UI, the `Summary Row` checkbox is disabled automatically. 
image

But in the test, we're [generating ](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/lib/reports/orders_and_fulfillment/order_cycle_customer_totals_report_spec.rb#L10) a CSV with `Summary row`

**Comment by RachL** [comment]
@abdellani apologies for late answer here: you are right - the test is wrong. Are you able to update it within this PR or do we need another issue?

**Comment by abdellani** [comment]
Hi @RachL 

I suggested a fix on https://github.com/openfoodfoundation/openfoodnetwork/pull/9990

What should I do next? wait for https://github.com/openfoodfoundation/openfoodnetwork/pull/9990 to be merged, or copy the fix here too?

**Review by jibees — APPROVED** [review]
Looks good to me! 💪

**Comment by RachL** [comment]
@abdellani I'm not sure what's the best practice here. @jibees what would you do?

**Comment by jibees** [comment]
Maybe cherry pick the commit?

**Comment by sigmundpetersen** [comment]
... and then rebase the other PR after the first one is merged (whichever one is tested/merged first)

**Comment by sigmundpetersen** [comment]
So #9990 is now merged. This would need a rebase then

**Comment by abdellani** [comment]
> So #9990 is now merged. This would need a rebase then

done

**Comment by filipefurtad0** [comment]
For some reason, the build was not triggered here - hitting the Rebase button :+1:

**Comment by sigmundpetersen** [comment]
This needs a rebase to get the updates from #10199 .
There may still be a relevant failure however, as Filipe pointed out.

**Comment by abdellani** [comment]
@filipefurtad0 
I solved the issue.
The csv report is expected to end with an empty line @ `spec/lib/reports/orders_and_fulfillment/order_cycle_customer_totals_report_spec.rb:50`

**Comment by filipefurtad0** [comment]
Thanks @abdellani ,
In that case, and since it is really a minor change, I think this is good to merge :+1:

**Pull request merged**
