### PR TITLE
Sort package.json to avoid conflicts

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
When adding a package via `yarn`, packages are sorted, which is a nice feature. 
This PR simply sort the file to avoid some bad commit diff like we have here: https://github.com/openfoodfoundation/openfoodnetwork/pull/8996/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

#### What should we test?
Only green build 🟢 

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — COMMENTED** [review]
6y6tl6

**Comment by jibees** [comment]
6y6ttn

**Comment by jibees** [comment]
6y6u0e

**Comment by RachL** [comment]
Everything ok @jibees 🤣 ?

**Pull request merged**
