### PR TITLE
Change "Enterprise Relationships" to "Enterprise Permissions"

### LINKED ISSUE #1384: Change 'enterprise relationships' to 'enterprise permissions'
I suggest we replace "relationships" with "permissions", which is a more accurate description of the tool. Explaining E2Es is quite tricky already. Removing one more confusing word from the mix would help. 

image

### PR DESCRIPTION
**Pull request by kristinalim**
This only updates ~`en*`~ `en` translations, and does not affect URLs and other back-end references.

#### What? Why?

Closes #1384 

From @sstead:

> I suggest we replace "relationships" with "permissions", which is a more accurate description of the tool. Explaining E2Es is quite tricky already. Removing one more confusing word from the mix would help.

#### What should we test?

From the admin dashboard:

1. Click on "Enterprises".
2. Check the secondary menu. Beside "Enterprises", you should see "Enterprise Permissions" instead of "Enterprise Relationships".
3. Click on "Enterprise Permissions".
4. Check the page heading. You should see "Enterprise Permissions" instead of "Enterprise Relationships".

#### Release notes

* Change ~`en*`~ `en` translations for enterprise relationships (back-end) from "Enterprise Relationships" to "Enterprise Permissions".

### CODE REVIEW

**Comment by kristinalim** [comment]
Thanks, @sauloperez! Checking these out.

**Comment by kristinalim** [comment]
I'm new to Transifex.

I was concerned that translators might not see a translation task for this change, because this updates only the `en` translation strings not the translation keys. I set up a test Transifex project and was able to confirm that changing a translation string for the source language does prompt translation in other languages again.

**Comment by sauloperez** [comment]
And with the latest changes we did, when a language changes translations we get a Github PR :v:

**Comment by kristinalim** [comment]
Yes, the setup seems awesome. :slightly_smiling_face:

**Comment by mkllnk** [comment]
Staged on https://staging1.openfood.com.au/.

**Comment by RachL** [comment]
This is ready to go!

@kristinalim Welcome and thank you for the detailed testing process in the PR description :)

Here are my testing notes : 
https://docs.google.com/document/d/1ibjjFA85BYQLvvOd4vauvKEIy-iA8cysFJJOs4NlfoM/edit#

**Pull request merged**
