### PR TITLE
Uk/1315 hide empty filter properties

### PR DESCRIPTION
**Pull request by jeronimo**
Regarding #1315 issue.

This is the "best" solution I came up with which still doesn't feel "Angular way". Please guide me if you have better one.

### CODE REVIEW

**Comment by jeronimo** [comment]
I was hoping to implement in that way as well. But there are more than one `filter-selector` directive in the view and it is needed to hide parent html element of that directive so I saw it as a namespace conflict so that one would override all. Or `allSelectors` is `nil` because it is outside `filter-selector` scope.  I am not sure anymore, will have to check again :)

**Comment by jeronimo** [comment]
@Matt-Yorkley, @oeoeaio Maybe for suggestions how to make the code better?

**Comment by oeoeaio** [comment]
Hey @jeronimo, I would do this by assigning the result of the filter to a variable on the parent scope (using the `as` syntax), and then showing/hiding the whole block based on whether length is non-zero. Something like:

````ruby
  .filter-block{ ng: { show: "filteredTaxons.length > 0" } }
    // title,etc
    %filter-selector{ ...... objects: 'producers_to_filter | searchEnterprises:query | taxonsOf as filteredTaxons' }
````
That way you can avoid the use of jquery in the `filter-selector` directive.

Thoughts?

**Comment by jeronimo** [comment]
@oeoeaio, if I understand your suggestion correctly this is the same I have tried at the beginning and that is what @Matt-Yorkley suggested as well. But if you would read my comments maybe it will explain the problem. Unless I still do not understand Angular Services yet.

**Comment by oeoeaio** [comment]
@jeronimo ok, so the scoping this is pretty interesting here, I have worked with these directives before and they are pretty complex, I'll give you that. You are right in saying that `allSelectors` is not accessible because it is only present inside the `filter-selector` scope.

I am suggesting something different though, and I think it will work. Each `%filter-selector` element declares it's own `objects` using a filter, the result of which can be assigned to a unique variable on the parent scope. So filtered objects from the taxons filter-selector can be assigned to `filteredTaxons` and the filtered objects from the properties `filter-selector` can be assigned to `filteredProperties`. So there should be no conflict. You can then use the length of `filteredTaxons` or `filteredProperties` with an `ng-show` to show or hide the selectors. Does that make sense?

**Comment by daniellemoorhead** [comment]
Removing this from August dot point release, ping us with the aus review label when you're ready to go @jeronimo :)

**Comment by myriamboure** [comment]
@jeronimo any news on that PR ? @lin-d-hop do we move it forward or close it for now and open an icebox issue to improve mobile UX and bug the issue in it?

**Comment by myriamboure** [comment]
Closing as it's been open for ages and no move. Iceboxed the original issue for when we decide to prioritize mobile UX.

**Pull request closed without merging**
