### PR TITLE
Bring spree_backend overview controller to OFN

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Related to #4050

Here we basically move the overview decorator to the original controller from spree_backend because the original controller was basically empty.

#### What should we test?
We need to validate that the main admin dashboard works as usual. Probably better to validate it for the different scenarios:
- redirect to enterprises if first access and enterprise profile (profile, producer, hub) was not chosen yet
- single enterprise dashboard if user manages only 1 enterprise
- multiple enterprises dashboard if user manages more than 1 enterprise

#### Release notes
Changelog Category: Changed
Imported the controller related to the dashboard from spree_backend to make OFN more independent of Spree.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hi @luisramos0 :-)

Checked the test cases, all good.

Not related to this PR (tested before and after staging):
Noticed one gets an Snail/Error 500, when adding a new product (link below) if not specifying Unit Value:
https://openfoodnetwork.org.au/admin/products/new

There are several S3s at All The Things, but didn't find this one. Should I open a new S3?

In any case, I'll move this to Ready To Go :-)

**Comment by luisramos0** [comment]
@filipefurtad0 you posted a link to production, did you test in staging?

**Comment by filipefurtad0** [comment]
I see now I didn't. In AU-staging the confirmation email sends me back to production, and I didn't notice it - sorry for that.
Moving back to test ready.

**Comment by filipefurtad0** [comment]
Double checked the test cases, same result. I think everything is fine. So, moving back to Ready to Go.

I still get Error 500, now on the link below, and if one don't insert a value for unit size.
https://staging.openfoodnetwork.org.au/admin/products/new

I haven't tested much in AU-staging, and I realize now that this is a particular aspect of the email confirmation here. Will keep my eye open for this.

**Comment by luisramos0** [comment]
ah, tricky emails!

ok, thanks Filipe.

I think you are seeing this issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/3912

**Comment by filipefurtad0** [comment]
Yes! That's it Luis - issue: #3912
I'll be watching out for those tricky emails.
Thanks again.

**Comment by RachL** [comment]
@filipefurtad0 @luisramos0 that confirmation link can be fixed by super admin. But I don't have the login. Do you guys have it for staging AU?

**Comment by luisramos0** [comment]
ah, is it the site url in general config? I have just fixed it in staging AU :-)
thanks @RachL

**Comment by RachL** [comment]
@luisramos0 yes it is! But I don't know if this could be changed "permanently" in the way we build our test data. often, we end up with spree demo URL after we put fresh seed data for example. I guess in this case we've put some production data on AU and ended up with the production URL in the config?

**Comment by filipefurtad0** [comment]
Thank you to both! @luisramos0 @RachL This is a great discussion, especially since I am not so clear on how to test with seed- / test- / production-data. Should we move to Slack? Would definitivelly be grateful for some insigts. There recently was a discussion I had some difficulty following:
https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1575446899162200

**Pull request merged**
