### PR TITLE
added buttons to form and updated sanitizer to allow extra formatting

### PR DESCRIPTION
**Pull request by idanceinbetween**
#### What? Why?

Relates to #3757.

Added two formatting option buttons (underline and insert link) to two pages (new and edit product), but still need one more functionality (target=_blank) to prevent users leave OFN site to fully resolve the issue. @luisramos0 to help implement the directive from PR #2384

#### What should we test?
- As an enterprise manager, user can add external links in product descriptions.

#### Release notes
- Buttons were added.
- Function works on display page (product modals).

Changelog Category: Changed

#### How is this related to the Spree upgrade?
Not known 

#### Documentation updates
Not sure...

### CODE REVIEW

**Comment by luisramos0** [comment]
hello, can you try to fix your github config so that your commits appear with your github user?

I think you can fix the username using with git config...

**Comment by luisramos0** [comment]
thanks for your PR @idanceinbetween 

this is correct and working in the admin side, after saving the links the data in the db column is correct with target="_blank" by default. I think it must be the shopfront code that is removing the target="_blank" part of the link for some reason... I will investigate this further later today.

**Comment by idanceinbetween** [comment]
> hello, can you try to fix your github config so that your commits appear with your github user?
> 
> I think you can fix the username using with git config...

Whoops, didn't even realise, just fixed hope it's working properly for future PRs.

**Comment by luisramos0** [comment]
can you rebase this Pr and get the new user into this PR? if you do that you will get into the list of OFN github contributors with this PR. We are missing 3 to reach 100 contributors :-)

**Comment by sauloperez** [comment]
Awesome @idanceinbetween! You nailed it!

**Comment by idanceinbetween** [comment]
> can you rebase this Pr and get the new user into this PR? if you do that you will get into the list of OFN github contributors with this PR. We are missing 3 to reach 100 contributors :-)

is it working now? 😃

**Comment by luisramos0** [comment]
ah, your name now appears but it's still not linked to the gh account:
https://github.com/openfoodfoundation/openfoodnetwork/pull/3799/commits

**Comment by luisramos0** [comment]
@amers185 you had the same problem recently and your last PRs are connected to GH. can you explain what @idanceinbetween needs to do to get the commits with the GH user?

**Comment by amers185** [comment]
Hello! I had a similar issue. I solved it by following the instructions from this page: https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user You have to link your github account to an email of your own. Hope it helps.

**Comment by idanceinbetween** [comment]
> Hello! I had a similar issue. I solved it by following the instructions from this page: https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user You have to link your github account to an email of your own. Hope it helps.

Thanks @amers185. I think I just managed to fix it, fingers crossed!

**Comment by luisramos0** [comment]
ah, nice, thanks @amers185

**Comment by luisramos0** [comment]
yes @idanceinbetween the last commits look good :+1:

**Comment by luisramos0** [comment]
moving to in dev as I want to find out why targetblank is not rendering in the shopfromt

**Comment by luisramos0** [comment]
good point @kristinalim

**Comment by lin-d-hop** [comment]
Tested and this all looks great!
Thanks @idanceinbetween!! This is a really great addition much wanted by OFN users.

Testing notes here:
https://docs.google.com/document/d/1AgkNw9nsWVCL5KpDwTIFXAeo8idsH2fR19f5GoDbpEU/edit#

**Comment by luisramos0** [comment]
@lin-d-hop this is closing #3757 right?

**Comment by lin-d-hop** [comment]
Yeah :-) @luisramos0 is it the testers job to close a connected issue when moved to 'Ready to Go'? Or does a dev do that on merging?

**Comment by RachL** [comment]
@lin-d-hop I was under the impression that merging a PR was closing automatically the connected issue. However this also remove any link between the issue and the PR once it is merged.
But in this case however I think we just forgot to add 3757 as a connected issue

**Comment by lin-d-hop** [comment]
No. I checked. You had connected it 14 days ago @rachL. But when I closed it the connection was broken as you say. #confused

**Comment by luisramos0** [comment]
it's the description! 
"Relates to #3757." will not close issue.
"Closes #3757." will close the issue.

usually dev writes "closed #..." and GH closes the issue for us.

**Comment by lin-d-hop** [comment]
Aaaahhhhh Thanks @luisramos0! Clever github.

**Comment by RachL** [comment]
@lin-d-hop actually you did the right thing ;) The issue said "relates" and not "closes". Good to know!!

**Pull request merged**
