### PR TITLE
Remove the admin_style_v3 toggle from Production and Staging environments

### LINKED ISSUE #12911: Remove the admin_style_v3 toggle from production and staging environments
⚠️ **Please use clockify code #12476 Flower Farms**

## Description
**- As a:** (enterprise user, super admin, user...)
**- On page:** `/admin/feature-toggle/features`
**- I want to be able to do:** 

It shouldn't be possible to turn off the feature toggle anymore, in staging and production. Also the page `/admin/products_old` should stop being accessible

dev environment can still toggle off if needed

## Acceptance Criteria & Tests

1. Check that the toggle is not available anymore
2. check that `/admin/products_old` does not exist anymore and throws an error

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12911
- This PR removes the `admin_style_v3` feature toggle for staging and production envs
- Moreover, it ensures that you can see the toggle in development env.

#### What should we test?

- As described in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

### CODE REVIEW

**Comment by chahmedejaz** [comment]
We can remove old bulk update specs now as we won't be using it anymore.

**Review by dacook — APPROVED** [review]
I was wondering if this would be straightforward or not..
I guess not! Thanks for working this out.

It's a bit complicated, but hopefully we can remove it again soon anyway.

**Comment by rioug** [comment]
@chahmedejaz can you fix the conflict ?

**Comment by chahmedejaz** [comment]
Thanks @dacook and @rioug - Conflicts have been resolved.

**Review by dacook — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
Good quick solution. I hope that we can remove the old code completely soon.

**Comment by drummer83** [comment]
Looking good! Merging! Testing notes will follow...

**Comment by drummer83** [comment]
Hi @chahmedejaz,
Thanks for working on this. Here are my testing notes now.

## Before staging
- Feature toggle before staging:
ksnip_20241019-132133

- Page products_old can be loaded:
ksnip_20241019-132235

## After staging
- Feature toggle after staging:
ksnip_20241019-133347

- Page product_old cannot be loaded anymore.
- I couldn't find any broken links linking to the product_old page.
- I did not test anything regarding the toggle in the development environment, because I think it's not critical.

Thanks again! :pray:

**Pull request merged**
