### PR TITLE
Transifex update

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I am fixing a bug in the new en_ZA #3941, the main key has to be en_ZA, not en_GB. This was fixed in transifex.
This PR is the results of  "tx pull --force" (I dont think this was executed before the last 2.1.0 release).

#### What should we test?
No test required.

#### Release notes
Changelog Category: Added
Translations updated.

### CODE REVIEW

**Comment by sauloperez** [comment]
watch out because Transifex did correctly sync the changes https://github.com/openfoodfoundation/openfoodnetwork/pull/3944/files#diff-8269cc8275896e5ac1c230aefafbe095R1

**Comment by luisramos0** [comment]
ah, nice, thanks!
ok, so let's close the PR.
we need to refresh translations before the next release.

**Comment by luisramos0** [comment]
ah, nice, thanks!
ok, so let's close this PR.
we need to refresh translations before the next release.

**Comment by luisramos0** [comment]
ah, nice, thanks!
ok, so let's close this PR.
we need to refresh translations before the next release.

**Pull request closed without merging**
