### PR TITLE
Add CircleCI config

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

WIP test configuration for CircleCI

#### Release notes

Changelog Category: Added | Changed | Deprecated | Removed | Fixed | Security

### CODE REVIEW

**Comment by luisramos0** [comment]
is there a discourse post about this? are we planning to move from semaphore?

**Comment by Matt-Yorkley** [comment]
I thought I'd give it a quick try to see if it fixes our flaky spec problems...

**Comment by Matt-Yorkley** [comment]
And it looks like Semaphore are deprecating their old CI offering (which is what we're on).

**Comment by luisramos0** [comment]
ok :+1:

are we not on semaphore classic?
https://docs.semaphoreci.com/article/88-migration-guide-for-semaphore-classic-users
"We don't have any plans to sunset Semaphore Classic"

I cant find anything about this on discourse, maybe we talked about it on slack only...

**Comment by sigmundpetersen** [comment]
Yes, @sauloperez has talked about this several times, I guess mostly on slack. He has suggested the switch to CircleCI more than once. Semaphore was removing our open source offering, but I think we got extended credits or something.

**Comment by luisramos0** [comment]
ok, I dont see sempahore deprecating v1 or removing the open source offering...

Screenshot 2019-12-02 at 12 43 38

**Comment by sauloperez** [comment]
That's last weeks news. I got an email explaining that @luisramos0 . Do you mind if we move this conversation to Slack. I feel it's going to be easier there.

**Pull request closed without merging**
