### PR TITLE
Fix sorting of admin products by name

### LINKED ISSUE #6105: Alphabetical Sort of Admin Products broken
## Description

Unable to sort product list alphabetically in the admin interface (https://openfoodnetwork.org.uk/admin/products) .
Enables user to manage their products.
This was implemented in issue #4759 but is broken as a result of [this release](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.2.8).

## Expected Behavior

Visit https://openfoodnetwork.org.uk/admin/products
Click 'NAME' in Product table to sort products alphabetically by name from a-z or z-a 
productlistsort

## Actual Behaviour

Visit https://openfoodnetwork.org.uk/admin/products
Click 'NAME' in Product table.
Products ordering is unchanged (non-alphabetical)

## Steps to Reproduce

1. Create a list of products in non alphabetical order (Loaf of bread, Pork Chops, Whole chicken, Cake)
2. click on NAME in products table on this page https://openfoodnetwork.org.uk/admin/products
3. Observe order in which products appear is unchanged. (ie not reordered to Cake, Loaf of bread, Pork Chops, Whole Chicken)
4.

## Animated Gif/Screenshot

downsort
upsort

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 3.2.8
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

The API expects the `sorting` parameter to be nested inside the `q` paramter.

Closes #6105
#### What should we test?

See _Steps to Reproduce_ in #6105 

#### Release notes

Fix sorting of products by name in admin.

Changelog Category: Fixed

### CODE REVIEW

**Review by luisramos0 — CHANGES_REQUESTED** [review]
Thanks @cillian for one more!
This is a repeat regression. It was broken, then fixed, then broken. It's a true reminder of the old no-auto-tests world of software. The good news is that is past! We need to add a spec to test the sorting buttons... if you dont find the time maybe I can give help here, latest next week :+1:

**Comment by cillian** [comment]
No prob @luisramos0 I have added a test now, let me know if it needs any more changes.

**Review by luisramos0 — APPROVED** [review]
nice, thank you!

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @cillian ,

A brief checkup of the bug - **before this PR** - the direction of the arrow next to "Name" can be switched to up/down, but this has no effect on the product ordering:

image
image


**After this PR:**

Clicking on "Name" nor orders the products alphabetically:

image
image

Interestingly, the arrow next to "Name" is now missing...

image


This seems to be caused by this PR... I think this could be merged, since it does solve the underlying issue. I'll open an issue on the missing arrow :+1:

**Pull request merged**
