### PR TITLE
 Clean up unused enterprise fields

### LINKED ISSUE #11243: Clean up unused OFN Enterprise fields
During inception / analysis I am noting fields on the **_Enterprise_** table in OFN that I think are obsolete and unused (I don't even know where you could update them in the UI?). Noting here as potential papercut to remove
* Pickup Times
* Next Collection At
* Distributor Info

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #11243 

The less code the better. When talking about new APIs, we were trying to map all existing attributes but that's wasted effort on unused attributes. We better avoid that in the future.

#### What should we test?

- Test that the pickup time for an order cycle displays correctly.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Good cleanup :broom:

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,
there was a recent merge causing a conflict on this one.

**Comment by mkllnk** [comment]
Rebased, ready for testing again.

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

I've checked the usual places for the pick up time after staging this PR:


Shopfront:

image

On top of all three checkout steps:

image

Order confirmation screen:

image

Email confirmations (displaying one email):

image

Looking good!
Merging.

**Pull request merged**
