### PR TITLE
[Spree Upgrade] Fix order_with_totals_and_distribution factory by updating shipping fees

### LINKED ISSUE #3113: [Spree Upgrade] Fix admin orders edit - capture payment (1 broken test)
Fix:

```
  6) 
    As an administrator
    I want to manage orders
 capture payment from the orders index page
     Failure/Error: expect(page).to have_content "Payment Updated"
       expected to find text "Payment Updated" in "Logged In As : lynn_kuhlman@cormier.name Account Logout Store DASHBOARD ORDERS PRODUCTS REPORTS CONFIGURATION USERS ORDER CYCLES GROUPS ENTERPRISES CUSTOMERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Listing Orders NEW ORDER SEARCH DATE RANGE STATUS INVOICE NUMBER: EMAIL FIRST NAME BEGINS WITH LAST NAME BEGINS WITH ONLY SHOW COMPLETE ORDERS DISTRIBUTORS ORDER CYCLES FILTER RESULTS 15 per page 1 Results found. Viewing 1 to 1. DISTRIBUTOR ORDER DATE NUMBER STATE PAYMENT STATE SHIPMENT STATE CUSTOMER E-MAIL TOTAL Enterprise 31 November 20, 2018 R244243478 [MISSING \"EN.ORDER_STATE.COMPLETE\" TRANSLATION] [MISSING \"EN.PAYMENT_STATES.BALANCE_DUE\" TRANSLATION] [MISSING \"EN.SHIPMENT_STATES.PENDING\" TRANSLATION] anastasia.maggio@monahan.com $13.00 « FIRST PREVIOUS 1 NEXT LAST »"
     # ./spec/features/admin/orders_spec.rb:185:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?
Closes #3113 
By fixing the totals in the factory, the test sees an order with correct total of 13 (including the shipping fee of 3) and not just 10 (the line item total).
This makes the test payment amount move from 10 to 13 and, because it covers the final amount of 13, capturing the payment just works.
All credit to @mkllnk for finding out the source of the issue [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/3113#issuecomment-452599450).

#### What should we test?
spec in 3113 should be green (I have confirmed in the build).

### CODE REVIEW

**Comment by luisramos0** [comment]
ehehe, sorry about that!

Actually, I am not sure this PR is ready. We need this last commit to fix orders_spec and it's good looking (update_adjustments...).
These two factories need to be cleaned up...

**Comment by luisramos0** [comment]
The build is looking good. The lines added to the factories are not good but I believe this is related to #2685 (and PR #3250). @sauloperez what shall we do with this?
will we try to get rid of order.update_shipping_fees?

**Comment by sauloperez** [comment]
Moving back to in dev because I'll take a look at it now that I got the hang of adjustments (kind of...).

**Comment by sauloperez** [comment]
This is ready again. After doing quite deep spelunking I found out the actual problem was that the shipment adjustment were not created at the time they should. That is why manually triggering the logic from the factories fixed it.

**Comment by luisramos0** [comment]
ah, great, looks good!

bu there are lots of broken tests, you have fixed the shipment_with factory but I guess  order_with_totals_and_distribution also needs some fix to replace update_shipping_fees

**Comment by luisramos0** [comment]
tumblr_m8cr6cgxt21qeeqito4_250

**Comment by sauloperez** [comment]
Oops, I think this introduced a bunch of errors like

```
3) Spree::Adjustment recording included tax Shipment adjustments the shipping charge is the adjustment amount
     Failure/Error: adjustment.amount.should == 50
     
     NoMethodError:
       undefined method `amount' for nil:NilClass
     # ./spec/models/spree/adjustment_spec.rb:73:in `block (5 levels) in <module:Spree>'
```

The tests mentioned in #3113 got fixed though.

**Comment by luisramos0** [comment]
@sauloperez will you take care of this?

before your change in shipment_with:
```
(byebug) order.shipment.adjustment
#<Spree::Adjustment id: 127, source_id: 320, amount: #<BigDecimal:7fcdea54a4d8,'0.5E2',9(18)>, label: "Shipping", source_type: "Spree::Shipment", adjustable_id: 307, created_at: "2019-02-13 11:59:36", updated_at: "2019-02-13 11:59:36", mandatory: true, originator_id: 308, originator_type: "Spree::ShippingMethod", eligible: true, adjustable_type: "Spree::Order", included_tax: #<BigDecimal:7fcdf3a2afa8,'0.1E2',9(18)>, state: "open">
(byebug) order.adjustments
[#<Spree::Adjustment id: 127, source_id: 320, amount: #<BigDecimal:7fcdec18cab0,'0.5E2',9(18)>, label: "Shipping", source_type: "Spree::Shipment", adjustable_id: 307, created_at: "2019-02-13 11:59:36", updated_at: "2019-02-13 11:59:36", mandatory: true, originator_id: 308, originator_type: "Spree::ShippingMethod", eligible: true, adjustable_type: "Spree::Order", included_tax: #<BigDecimal:7fcdec185da0,'0.1E2',9(18)>, state: "open">]
```

after your change in shipment_with:
```
(byebug) order.shipment.adjustment
#<Spree::Adjustment id: 126, source_id: 319, amount: #<BigDecimal:7f9eac3a79e0,'0.5E2',9(18)>, label: "Shipping", source_type: "Spree::Shipment", adjustable_id: 304, created_at: "2019-02-13 11:56:26", updated_at: "2019-02-13 11:56:26", mandatory: true, originator_id: 307, originator_type: "Spree::ShippingMethod", eligible: true, adjustable_type: "Spree::Order", included_tax: #<BigDecimal:7f9eb822ed78,'0.1E2',9(18)>, state: "open">
(byebug) order.adjustments
[]/1 |>                                                                                                                                                                                                                                                      |  ETA: ??:??:??
(byebug) order.reload
#<Spree::Order id: 305, number: "R568266163", item_total: #<BigDecimal:7f9eb2493c18,'0.0',9(18)>, total: #<BigDecimal:7f9eb2493b78,'0.0',9(18)>, state: "cart", adjustment_total: #<BigDecimal:7f9eb24939c0,'0.0',9(18)>, user_id: 749, created_at: "2019-02-13 11:56:26", updated_at: "2019-02-13 11:56:26", completed_at: nil, bill_address_id: 1344, ship_address_id: nil, payment_total: #<BigDecimal:7f9eb2492bb0,'0.0',9(18)>, shipping_method_id: nil, shipment_state: "pending", payment_state: "balance_due", email: "kaleb_von@bergstromgrimes.info", special_instructions: nil, distributor_id: nil, order_cycle_id: nil, currency: "EUR", last_ip_address: nil, customer_id: nil, created_by_id: nil>
(byebug) order.adjustments
[]
```

I got this in spec/models/spree/order_spec.rb:238

**Comment by sauloperez** [comment]
Among the 3 failing specs I found two in `spec/features/admin/bulk_order_management_spec.rb` but they are passing on my machine. The other one is fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/3497.

**Comment by luisramos0** [comment]
yes, the build looks good.
bulk_order_management_spec is flaky flaky 🤣 
code review?

**Comment by luisramos0** [comment]
I have reviewed now. approved!

**Pull request merged**
