### PR TITLE
[WIP 🚧 ] `/admin/order_cycles` behind feature toggle `admin_style_v2`

### LINKED ISSUE #10125: Change OC page colors
## Description
**- As a:** enteprise and super admin using feature toggle
**- On page:** `/admin/order_cycles` and sub pages
**- I want to be able to do:** 

- [x] Base the work on previous PR 

- [x] Fix table : 

- [x] Turn "clear all" as secondary button

- [x] if not fixed by previous PR, placeholder need a darker grey: 

- [ ]  Change columns selector to introduce same component than in reports

- [x] Green yellow and grey need to cover whole line

- [x] Use white on blue when selected and white on grey when not? 

same as in but maybe we can use darker grey in both cases : 

- [x] Fix tag color

- [x]  Use correct `#017a9a` blue

image

## Acceptance Criteria & Tests

1. check the task are done
2. check old colors stay active without feature toggle

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10125

Capture d’écran 2022-12-09 à 10 32 27

#### What should we test?
 - As an admin, _with_ feature `admin_style_v2` activated, you should see the design
 - As an admin, _without_ feature `admin_style_v2`, nothing should change

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
#10080 is merged, I've rebased this one onto master, and I think it's ready to `Code Review` then

**Comment by RachL** [comment]
@jibees shall I stage this already or it's best I wait for code review first?

**Comment by jibees** [comment]
@RachL I'm not sure this one needs code review actually ;)

**Comment by RachL** [comment]
ok staging then :)

**Comment by jibees** [comment]
Done:

Capture d’écran 2023-01-06 à 10 47 45
Capture d’écran 2023-01-06 à 11 21 57

 - > Can we use the secondary (white) button for disabled button?

I'd say no: secondary button are for enabled button, not for disabled ones. Why you want this? Not sure to understand ;)


 - > Needs to be a white secondary button

Yes, we this button is enabled:
Capture d’écran 2023-01-06 à 11 26 49
Capture d’écran 2023-01-06 à 11 30 50

**Comment by RachL** [comment]
ok let's leave them on this model for now :+1: I was just wondering as they were not much readable, but I guess it's meant to be this way :)

**Comment by jibees** [comment]
> but I guess it's meant to be this way :)

Yes, a bit, but maybe we could improve a bit (I've no idea actually)

So I guess we are ready here!

**Comment by RachL** [comment]
@jibees a tiny glitch left in the 3 layer cake :) 

image

Let's not spend too much time on it but I wonder why sometimes the border stops - this is in incoming section (I even wonder if it was a scroll bar) :

image

Looks cool otherwise!! I don't want to switch to the old design for release testing haha

**Pull request merged**
