### PR TITLE
Add code coverage reporting to our CI build with Codecov

### LINKED ISSUE #4435: Report code coverage as part of CI
### What we should change and why (this is tech debt)

Currently, there's no way to have an up-to-date code coverage % both for the `master` branch and for each PR. This becomes essential to ensure we keep a healthy test coverage while trying to reduce the manual release testing the project needs.

The simplest solution IMO is to leverage Code Climage's coverage report. We just need to send the coverage report to it from each CI build. Some months ago I investigated this and realized Semaphore V1 does not support this. I don't know if Semaphore v2 supports it yet but as of this writing, they don't have a freemium model for open source yet (I begged and they just gave us 200$ credit while they implement it).

What I suggest is to migrate to Circle CI. It feels clear now to me that it got ahead in the CI's battle: much more documented, more features, freemium for OSS. Looks like Semaphore is trying to catch up. Besides, I got already acquainted with it on other projects and it won't be difficult to change to it.

The only blocker was the minimum Ruby version, 2.2, and that will next week be solved.

### Context

This is part of the ongoing https://community.openfoodnetwork.org/t/release-testing-next-steps/1741/4.

### Impact and timeline

This will enable us not to lower the bar and trust our test suite. We also need to keep in mind that code coverage it's not a guarantee that we're actually testing no regressions are introduced but it's something.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #4435

It analyzes the coverage of all CI build jobs and uploads the reports to our Codecov account that I previously set up. See https://app.codecov.io/gh/openfoodfoundation/openfoodnetwork/pulls?page=1&state=open&order=-pullid.

Codecov is free for open source so we're good :ok_hand: 

#### What should we test?

Green build.

#### Release notes

Added code coverage reporting to our CI build with Codecov
Changelog Category: Technical changes

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]
Really easy! Let's run it for a while and see how it works.

**Comment by sauloperez** [comment]
The only experience I have with it are those visual reports that show you the delta of a PR plus the dashboard which highlights coverae across the codebase. I'm sure it can offer more than that though.

**Review by Matt-Yorkley — APPROVED** [review]
Nice, lets give it a try :+1:

**Comment by Matt-Yorkley** [comment]
Browsing the coverage reports I notice there are some directories with zero coverage that are dragging down the total significantly, but they're not necessarily critical app code. `/lib/tasks/sample_data/` is one example.

**Comment by Matt-Yorkley** [comment]
Wow, `app/controllers/payments_controller.rb` has 0% coverage...?

**Comment by sauloperez** [comment]
We'll need to come up withelst indeed. I don't care that much about `lib/tasks/sampla_data` but that controller is concerning.

**Pull request merged**
