### PR TITLE
Translationfix

### LINKED ISSUE #6226: Missing translations on date picker (Orders pages - edit and bulk management)
## Description

Translation seems to be missing on the date picker, for both the Bulk order management and the Orders page. Observed while testing #5928.

## Expected Behavior

Different languages can be displayed on these date pickers, by choosing another languages other than English.

## Actual Behaviour

Only English is displayed on the date pickers in these pages, despite having selected other languages.

## Steps to Reproduce

1. Choose a language other than English ans log in as admin/hub manager
2. Visit `/admin/orders` or `/admin/orders/bulk_management`
3. Click on one of the date fields (see pics)
4. See missing translation

## Animated Gif/Screenshot

Bulk order management page:

Orders page:

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.2.11
* Browser name and version: Firefox 86 
* Operating System and version (desktop or mobile): Desktop/Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ankis17**
#### What? Why?

Closes #6226
We have included a way to translate the datepicker months and weeks within the Orders page when logged in as an administrator. This change was needed because when the language of the website was something other than English, the months and days in the datepicker would still appear to be in English.

We found our fix by browsing the Datepicker widget opensource Code in the JQuery UI documentation. From here, we were able to understand how to properly translate the Datepicker.

#### What should we test?

More rigorous tests for datepicker might be needed in order to ensure the functionality of the translation.

#### Release notes
Translation for Datepicker has been fixed to support languages other than English. 

Changelog Category: User facing changes

### CODE REVIEW

**Review by andrewpbrett — CHANGES_REQUESTED** [review]
Hi @ankis17 and @nikhilt99 - thanks for submitting this PR! I checked out this branch locally and confirmed that it does in fact fix #6226 🎉 

Before we merge it, could you squash the commits down to a single commit? We'd like to keep the history clean of adding and removing test files. It will also need a second approval before it goes to testing. [Here's some more info about the process](https://github.com/openfoodfoundation/openfoodnetwork/wiki/The-process-of-review%2C-test%2C-merge-and-deploy).

I also noticed that the issue mentions only two places (Orders page and Bulk Order Management) that the date pickers are not translated. On the Order Cycles screen, for example, date pickers already use the correct translations. It would be good to take a look at what we're doing on the Order Cycles screen, and determine if this new approach of putting the code in `base.js.erb` will allow us to improve how we translate the datepickers on that screen, or if we should use the same approach that we're already using there. 

Thanks again - this is a great fix! 🎉

**Comment by ankis17** [comment]
Hi, thank you! We tried to squash the commits by using rebase, but are not sure if it worked. Would it be okay to make another branch/ PR with just one commit and go from there. Or do you have any other recommendations?

**Comment by andrewpbrett** [comment]
Yeah, squashing can be tricky depending on what tools you're using. If you're more comfortable with a single commit on a new branch that's fine to close this PR.

**Comment by ankis17** [comment]
Great @andrewpbrett I just submitted another PR with all the changes (#6524)

Should I go ahead and close this one?

**Comment by andrewpbrett** [comment]
Thanks @ankis17! Much clearer what's happening and easier to merge that way. I'll close this one for you. I had one remaining question about the PR but will move discussion to that one now.

**Pull request closed without merging**
