### PR TITLE
Migrate from Paperclip to ActiveStorage

### PR DESCRIPTION
**Pull request by achauve**
#### What? Why?

Closes #[the issue number this PR is related to]

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
In terms of the configuration there's an extra detail as well: some instances store images on S3 and some don't (they store them directly on the server itself). We'll need to be able to use either option and apply it dynamically based on the ENV vars. I guess we'll need to test both cases separately.

**Review by mkllnk — COMMENTED** [review]
Sounds like a good plan. So the point of no return (can't roll back) is when we start storing images with ActiveStorage and use its random keys because Paperclip won't be able to point to them. Or is there a way to provide ActiveStorage with a method that creates keys following the same pattern as Paperclip? Then it's completely backwards-compatible. It would require a `down` method in the migration though that converts ActiveStorage data into Paperclip data. I'm not sure it's worth it. That code would be as experimental as the rest and we may just mess things up even more. It may be easier to fix ActiveStorage if we made a mistake than going back to Paperclip again and that point.

**Comment by achauve** [comment]
> Sounds like a good plan. So the point of no return (can't roll back) is when we start storing images with ActiveStorage and use its random keys because Paperclip won't be able to point to them. Or is there a way to provide ActiveStorage with a method that creates keys following the same pattern as Paperclip? Then it's completely backwards-compatible. It would require a `down` method in the migration though that converts ActiveStorage data into Paperclip data. I'm not sure it's worth it. That code would be as experimental as the rest and we may just mess things up even more. It may be easier to fix ActiveStorage if we made a mistake than going back to Paperclip again and that point.

The goal is ot use both paperclip and active storage after the first PR is deployed, so obviously using only one file in the storage with the current Paperclip naming scheme, but updating both Paperclip AND Active Storage metadata. At this point rollback should be easy with no down migration required, just deploying the old code.
And then after a while (one to two weeks), deploy the second PR that deletes every trace of Paperclip code and data (sql columns). After this one rollback will be much harder and need a db reload, but I thought we would keep the Paperclip naming scheme forward, to avoid another migration to move every file to a new destination.

**Comment by mkllnk** [comment]
Hey @achauve, I'm working my way through this issue at the moment and I didn't know how difficult it was. You were totally right that re-uploading all images is the best way to go because we need to download them for a checksum anyway.

**Pull request closed without merging**
