### PR TITLE
Replace beef with fungi in sample data :cow: 

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I hope no one is opposed to this. I'd just like to not have meat on sample shop by default. Fish and Meat can be added.

#### What should we test?
We need to load sample data into a fresh DB.

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]
:fist_raised: :sweat_smile:

**Comment by Matt-Yorkley** [comment]
Maybe we should add a comment too: `No animals were harmed in the making of this sample data.`

**Comment by luisramos0** [comment]
:-)

**Comment by luisramos0** [comment]
I just tested this myself. I think we can move on, very simple change.

**Pull request merged**
