### PR TITLE
Create a columns selector component and remove the angular directive one

### LINKED ISSUE #10133: Update column dropdown everywhere
## Description
**- As a:** enterprise or super admin
**- On page:** BOM, customers and OC
**- I want to be able to do:**

- [ ] BOM
- [ ] Customers
- [ ] OC

## Acceptance Criteria & Tests

**No feature toggle on this one!!!!**

1. Check columns selectors have same design than current reports
2.  Check selecting / unselecting columns works as usual
3.  Check saving columns as default work

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10133

Not that easy, because we need to reload the table once we save or we toggle one column. The trick is that we are outside of angularjs. 

- [ ] 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
I tried to reload angular app after reflex:

**`app/webpacker/controllers/columns_selector_controller.js`**

```diff
diff --git a/app/webpacker/controllers/columns_selector_controller.js b/app/webpacker/controllers/columns_selector_controller.js
index 3c42fa80f9..e5f781e076 100644
--- a/app/webpacker/controllers/columns_selector_controller.js
+++ b/app/webpacker/controllers/columns_selector_controller.js
@@ -6,4 +6,16 @@ export default class extends ApplicationController {
   }
 
   disconnect() {}
+
+  afterReflex(element, reflex, noop, reflexId) {
+    super.afterReflex(element, reflex, noop, reflexId);
+
+    angular
+      .element(document.querySelector("[ng-app]"))
+      .injector()
+      .invoke(function ($rootScope, $compile) {
+        // reload angular
+        $compile(document)($rootScope);
+      });
+  }
```

But without success, as I had an error in the console:
```
Uncaught Error: [$compile:ctreq] Controller 'ngModel', required by directive 'ofnSelect2', can't be found!
```

**Comment by mkllnk** [comment]
I looked at this for a while and I'm not sure how to proceed either. AngularJS doesn't pick up those DOM changes. But I was also wondering why you change the DOM? It has all the right code already. The AngularJS variable `columns.*.visible` needs to change and then AngularJS should update the table by itself. That doesn't actually need a server call.

The final solution will be to render the whole table server-side and then we don't need AngularJS to render the ng-repeat. So if we can't get the in-between solution to work then maybe we either need to change only AngularJS variables or we need to replace the whole rendering. Your current version of replacing the AngularJS-rendered DOM with the empty server-rendered template doesn't make much sense to me. Or was that just an interim step?

**Comment by jibees** [comment]
> Yes, will try that solution.

I tried. But to be honest I didn't find a good solution with that. I must admit that I'm a bit tired working with Stimulus (and/or StimulusReflex) and don't find any good solution, or be blocked by a lot of things. It's probably a passage, maybe I need a pause.

**Comment by mkllnk** [comment]
Are you tired of Stimulus or of keeping remaining AngularJS working?

It's good to listen to  your motivation. Let's discuss at the delivery circle about taking a break from these tasks. Maybe it needs some fresh input from another developer.

**Comment by RachL** [comment]
@mkllnk @jibees how are we moving forward here? CSS or someone else than JB tries it out with Stimulus?

**Comment by jibees** [comment]
I'd love to see someone else working on it with Stimulus, see how it goes, share the knowledge and the feelings about it.

**Comment by mkllnk** [comment]
Okay, I'll give it a go.

**Comment by jibees** [comment]
Closing this one then.

**Pull request closed without merging**
