### PR TITLE
Add image back into server for background

### LINKED ISSUE #2278: Unreadable welcome text (image missing)
The enterprise welcome screen where you choose your package (enterprise subscription) is missing the background image which makes the text invisible.

## Expected Behavior

image

## Actual Behavior

screenshot from 2018-05-11 14-37-59

## Steps to Reproduce

1. Log in as enterprise user
2. Edit an enterprise
3. Change the last part of the URL from `edit` to `welcome` and hit enter
4. Alternatively, you can sign up as a new enterprise. That's how people usually see it.

## Context

Sally was testing https://github.com/openfoodfoundation/openfoodnetwork/pull/2269, but couldn't see the changed text.

## Severity

It's affecting every new enterprise user. The interface is usable, but they may not understand everything. => s4

## Your Environment

Tested locally, on staging and production.

## Possible Fix

We can define a dark background colour for the case that the image isn't there. Additionally, we could restore the image to it's supposed position at `/assets/home/tagline-bg.jpg`. I found the image on our old server.

tagline-bg

### PR DESCRIPTION
**Pull request by robotscissors**
#### What? Why?
Image was missing from the server when a new enterprise account was created. Used the image that was provided and put it correctly in the folder. Great instructions.

Closes #2278 

It took me while to get everything installed, but shortly after that I was able to re-upload the image as was stated as a solution in the issue.

#### What should we test?
Test is for missing image.  Not sure how to test this. I have provided a screenshot.

screen shot 2018-05-30 at 8 41 26 pm

### CODE REVIEW

**Comment by myriamboure** [comment]
Thank you for this first PR @robotscissors ! I let the devs have a look at it and give you feedback :-) Cheers!

**Comment by robotscissors** [comment]
Thank you!!

**Comment by mkllnk** [comment]
It could be nice to make the background of that area dark, so that you can see the text while the image is loading (or if it can't be loaded). But that's just a bonus. :-)

**Comment by robotscissors** [comment]
@mkllnk Happy to oblige. Would you like me to test that?

**Comment by robotscissors** [comment]
@daniellemoorhead, I added a simple background color to the container that holds the image. Since CSS loads sequentially, the background will be turn black while the image loads. :) Therefore, the text should be readable even if image hasn't finished loading.

**Comment by RachL** [comment]
I've created a producer account and I can see the image and the sentence. So looks good to me : 
image
Is there a need to test with other type of accounts ? ping @myriamboure @sauloperez

**Comment by sauloperez** [comment]
I don't think so.

**Comment by myriamboure** [comment]
Good! I think it's fine as well, let's merge.

**Pull request merged**
