### PR TITLE
Use DEFAULT_COUNTRY_CODE instead of DEFAULT_COUNTRY in application.yml.

### LINKED ISSUE #441: DEFAULT_COUNTRY in application.yml is not consistent with ofn_deployment
In `application.yml.example` it is `DEFAULT_COUNTRY: "Australia"` but in ofn_deployment it is assumed to be a 2 letter country ISO code. 

Need to decide how to be consistent. The argument for using a 2 letter code is its always just short and simple and the `i10n_*` projects use the same country code to identify which country they are for.

### PR DESCRIPTION
**Pull request by pmackay**
Fixes #441.

### CODE REVIEW

**Comment by pmackay** [comment]
@mkllnk any idea when this could get merged?

**Comment by mkllnk** [comment]
As soon as Rohan has setup the new test system, he wants to run a test with this. It's on his agenda.
@RohanM maybe next week?

**Comment by kirstenalarsen** [comment]
this is building now, fingers crossed will be in aus staging shortly. will be included in v0.9 aiming for later this week. Just a ping for @datashaman to check whether it affects anything he's doing

**Comment by datashaman** [comment]
Thanks for the heads-up! I've added another line to my config so it will
work with either. This must still land in master for me to change to the
way only.

**Comment by kirstenalarsen** [comment]
looks all good. so will merge and into production in the morning (general rule - never push anything to production while Rohan is sleeping :)

**Pull request merged**
