### PR TITLE
Remov i18nt keys from automated tests#9499

### LINKED ISSUE #9499: Remove I18n.t(<key>) from automated tests
### What we should change and why (this is tech debt)

We should remove `I18n.t(<key>)` from assertions on automated test and replace them with the respective string.

### Context

This is a fairly old discussion; came up recently [here](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1658187213357489?thread_ts=1658137192.453269&cid=C02TZ6X00).

Discourse links:

https://community.openfoodnetwork.org/t/convention-decision-to-i18n-or-not-to-i18n-in-spec-assertions/1432

https://community.openfoodnetwork.org/t/ensure-correct-translations-are-maintained-and-comprehensive/1303

### Impact and timeline

Spec improvements.

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

- Closes #9499 

A few occurrences of I18n remain, due to their variable nature.

#### What should we test?
Since this PR is all about automated testing, the only test is to get every automated test passing.
There are also tests about the I18n lib itself.

### CODE REVIEW

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , I just pushed changes.
Though, I have a failed check, on an untouched part from me.
Furthermore, I did not touch any code, only specs.

Do you allow me to rebase to relaunch checks ?

**Comment by filipefurtad0** [comment]
Hi @cyrillefr ,
Thanks so much for this PR and your notice.

> Though, I have a failed check, on an untouched part from me.

I agree it looks like it could be a flaky spec. So, I don't think it should be necessary to rebase. I've re-triggered the build, let's see if we get green now.

**Review by jibees — COMMENTED** [review]
I would love to this last commit squashed with its _original_ commit (I guess 8e308b0b01b470012fc9e28d191df6cd8a2d1cbb ?) since it solves a bug introduced by the PR itself: therefor we do keep a clean history.

**Comment by cyrillefr** [comment]
Hello @jibees , I squashed the last commit in the mailer commit + the system commit (there were 2 bug fixes).

**Review by jibees — APPROVED** [review]
Thanks a lot!

waiting for @filipefurtad0 review as well.

**Review by filipefurtad0 — APPROVED** [review]
Awesome :clap: 
Thanks so much @cyrillefr !

Build is green - we're good to merge.

**Pull request merged**
