### PR TITLE
Independent 'update cart' label

### LINKED ISSUE #7229: Missing translation string: Independent update cart label
## Description
The string 'Update' (the cart) on the cart page is not independent from string 'Update' on several buttons.
Different translations may be needed (like 'update' vs. 'refresh').

## Steps to Reproduce
1. In Transifex try to change the string on the cart page without changing the string on the buttons. It's not possible.

## Animated Gif/Screenshot
grafik

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
- Version used: v3.6
- Browser name and version: Firefox 87
- Operating System and version (desktop or mobile): Desktop Windows 10

### PR DESCRIPTION
**Pull request by drummer83**
#### What? Why?

Closes #7229 

The string 'Update' (the cart) on the cart edit page is now independent from string 'Update' on several buttons in admin.
Different translations may be needed (like 'update' vs. 'save').

* New line no. 1300 in en.yml
* Other changes are just added quotes to make the file more beautiful according to [i18n](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29#development)

#### What should we test?
1. Put an item into the cart
2. Navigate to 'edit cart' page
3. Observe the label 'Update' when changing the translation of 'orders_form_update_cart'
--> The label should change accordingly
--> The label of buttons 'update' on admin pages remains unchanged, e.g.
* admin/contents/edit
* admin/enterprises

grafik

#### Release notes
Added independent translations for update cart labels

Changelog Category: User facing changes

#### Documentation updates
If translation is changed, screenshots might have to be updated.

### CODE REVIEW

**Comment by mkllnk** [comment]
@sauloperez Do you have any idea why Codecov says that this PR is decreasing coverage? It shouldn't affect it at all. It also lists classes that are not covered but that didn't change. Is that a bug or is something wrong with our setup?

**Comment by sauloperez** [comment]
Honestly, I have no idea. The report looks too red so I would try reprocessing the PR from Codecov's dashboard.

**Comment by sauloperez** [comment]
According to Codecov's warning

> The base reference contains commits not present in the head reference. Please merge the base reference into the head reference to see the most up to date coverage information.

I bet this is a matter of getting all PRs based on commits that are tracked by Codecov. Until we don't get to that I guess that'll keep happening. Could you try rebasing onto latest `master` @drummer83 to find out?

**Review by Matt-Yorkley — APPROVED** [review]

**Review by andrewpbrett — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Cool, thank you so much @drummer83 ,
for the PR and the your notes.

I added a key to fr.yml which worked fine in the UI, after re-starting the server:
image

Other "Update" strings remain untouched :+1: 
Good to go!

**Pull request merged**
