### PR TITLE
Add RSpec cops

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?
We [discussed](https://github.com/openfoodfoundation/openfoodnetwork/pull/11208#discussion_r1280049281) that this format is preferred:
- [x] `RSpec/ExpectChange EnforcedStyle: block` 

This required installing the rubocop-rspec plugin, which generates A LOT of new offences. 
So we [discussed](https://openfoodnetwork.slack.com/archives/GK2T38QPJ/p1708384144709289) relaxing these options:
- [x] `RSpec/MultipleExpectations Max` - increase to a more reasonable number like 5
- [x] `RSpec/MultipleMemoizedHelpers Max` - increase to 10

#### What should we test?
Only specs have changed, so no manual testing. 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1 or DFC)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Documentation updates

- [ ] Add remaining items to [epic ](https://github.com/openfoodfoundation/openfoodnetwork/issues/6055)..

### CODE REVIEW

**Comment by dacook** [comment]
Although in principle I'd like to do this, I think we should https://github.com/openfoodfoundation/openfoodnetwork/issues/6055 before embarking on this.

But even then, perhaps this adds more overhead than we really want...

**Comment by RachL** [comment]
@dacook are you still working on this one or shall we close it?

**Review by mkllnk — APPROVED** [review]
Wow, that's still a lot of additions. But I'm happy to have these additional guidelines. We can evolve our rules over time. This is the first step to bring it in and test it out.

**Review by rioug — APPROVED** [review]
Nice one ! now I really need to automate Rubocop in my workflow :D

**Comment by rioug** [comment]
@dacook are you taking care of updating the related epic ?

**Comment by dacook** [comment]
Yep, have updated it now 👍

**Pull request merged**
