### PR TITLE
Use config to get logo in mails

### PR DESCRIPTION
**Pull request by marito59**
Use ContentConfig.footer_logo to get localized logo file instead of
defaut AUS logo.

### CODE REVIEW

**Comment by marito59** [comment]
Not sure how I should proceed to get the pull request processed. Tagged Internatioonal and assigned Maikel. 

Let me know if I should proceed differently.

**Comment by mkllnk** [comment]
Your change looks fine. It can probably be tested next week.

The management of issues and pull requests is currently discussed. You saw the permissions discussion. @kirstenalarsen can probably give you the latest state of that.

**Comment by kirstenalarsen** [comment]
think tag ‘aus review’ is best, we check that regularly . .

**Comment by marito59** [comment]
Hi @mkllnk 

The change has not been included in the master and the i18n branch has been deleyed. Did I do something wrong ? Is there any reason ?

Just asking to be more accurate next time we want to publish something.

**Comment by mkllnk** [comment]
Hi @marito59 

Sorry, you did everything right. I deleted the i18n branch because it was completely merged into master. I didn't know that this would invalidate your pull request. I keep this pull request on my list even though it's closed.

Thank you for pointing this out.

**Comment by marito59** [comment]
OK, thanks.

**Comment by mkllnk** [comment]
Sorry, it took a while, but I had a look at your change and it looks all fine. I opened a new pull request #751. It can go to production when our build pipeline is free.

**Comment by marito59** [comment]
Thanks again Maikel.

**Pull request closed without merging**
