### PR TITLE
Add API endpoint to list open shops

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

This creates a new endpoint like https://openfoodnetwork.org.au/api/shops/open_shops.json

parallel to the existing one https://openfoodnetwork.org.au/api/shops/closed_shops.json

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I think we threw this "closed shops" endpoint in there because the specific UX of a specific page demanded a closed shops endpoint. But... maybe it's not that great? It's not very REST-like. Are there better ways we can represent this and organise the endpoints in this controller that would make more sense or be more standardised? Just thinking out loud.

For example, it could be one index action, and it could take an optional parameter to show only open or only closed shops...?

:thinking:

**Comment by luisramos0** [comment]
Yes. I agree. I just wanted to show how to quickly get list of enterprises.
This one list must be requested quite a lot.

Additionally i think this shop concept should be well defined and discussed
with product team. What is a shop? An enterprise with some conditions (like
ship and pay methods defined)? Or simply a representation of an enterprise
for the frontoffice?

**Comment by RachL** [comment]
If I understand correctly, the purpose of this PR is to demonstrate how easy it is to create endpoints, not actually proposing a new one, am I correct?

Otherwise I'm afraid we are not ready yet to have these discussion around the shop concept 🙈 we have a lot on our plates right now.

> This one must be requested a lot.

FYI in FR it is indeed asked for by external websites. But there is also a rising concerns among users and they would like to consent where their shops is being displayed. An example of the questions we need to ask ourselves when incepting new endpoints...

**Comment by luisramos0** [comment]
This is exactly what Romain (see slack #dev) needs and it's only adding an endpoint open_shops parallel and similar to the existing closed_shops. Any external developer can use this at least for development.

We could simply keep this shop endpoint with these lists of enterprises for the frontoffice kind of integration, I think Matt describes the ideal scenario. But this PR already fixes the problem. We could ship this and normalize later as part of the api initiative.

I think the consent requirement is quite simple: checkbox on the enterprise profile to allow enterprises to share their data (data that is otherwise already public on our frontoffice) with external patterns integrating with our API. This checkbox can be used in these queries. It's fairly easy to do.

**Comment by RachL** [comment]
> I think the consent requirement is quite simple: checkbox on the enterprise profile to allow enterprises to share their data (data that is otherwise already public on our frontoffice) with external patterns integrating with our API. This checkbox can be used in these queries. It's fairly easy to do.

Awesome :) May I ask how the endpoint works today? It list all shops or only visible ones?

**Comment by Matt-Yorkley** [comment]
> We could ship this and normalize later as part of the api initiative.

But in that case we'd be shipping an endpoint that _people would start using_, in the knowledge that we will probably make breaking changes to that endpoint in the short-term, right?

I think if we touch this controller at all we should put something in place that we think we are actually going to keep...

**Comment by lin-d-hop** [comment]
I have to say I'm a bit nervous about adding a new endpoint at this point when we are making big decisions about our API strategy.

It feels a bit like trying to just pack one more thing in a suitcase, but you don't know whether you're going to Portugal or Scotland. Maybe the thing you pack will be useful or maybe you'll just have to carry the thing around for your whole trip.

**Comment by luisramos0** [comment]
ok, I think I am rethinking my role here. As a external community member I'd like to feel I can add features to the product and iterate without exactly following the core team roadmap. This change is 0% disruptive (we already list all closed shops, and eventually all shops will be on the closed shops list at some point, here I add a equal open shops endpoint). I am seeing Romain actually using this endpoint to build his app and, later on, adapt it to the changes you will want to do to the endpoint. I mean, from the perspective of a client android app must be very easy to change the endpoint URL and adapt to some changes on the payload, specially if the mapping app is only using a few like name and address.

I understand where you are coming from. I wanted to make this comment, I think it's relevant.

I am closing this PR for now as Romain is already happy with working with the example json he has got.

**Pull request closed without merging**
