### PR TITLE
Change for xhr rquest to avoid csrf during testing

### LINKED ISSUE #5606: [Rails 4.1] CSRF protection from remote <script> tags (22 broken specs)
We have few errors in the build related to this change in rails 4.1:
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#csrf-protection-from-remote-script-tags

The build:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5611/builds/8

### PR DESCRIPTION
**Pull request by luchiago**
#### What? Why?

Closes #5606
A change necessary due to upgrade for rails 4.1 and to be able to test requests with js format

#### What should we test?

The spec files who has `format: :js` included in some `it` blocks

#### Release notes

Update testing with `format: :js` to avoid crsf problems

Changelog Category: Changed

### CODE REVIEW

**Comment by luisramos0** [comment]
Hey, its great to see you help with the upgrade! Thanks a lot!

I havent looked up anything about this problem.
Can you explain a bit better why do you think this is the solution?
does this mean we will not have to change the code outside specs?

**Comment by luchiago** [comment]
@luisramos0 Well, I looked at the issue and I understood the problem was with the specs with `format: :js` inside the examples. I made a search to see if Spree doesn't offer a helper to do the same in the specs, but it didn't have. I can investigate the code that is being tested with this format.

**Comment by luisramos0** [comment]
Thanks @luchiago I think it's fine for now. Let's do this for all the specs that are failing with this error and then later in the upgrade (with manual testing for example) we will be able to detect if there's anything else breaking because of this. Thanks!

**Comment by Matt-Yorkley** [comment]
The relevant `rspec-rails` issue is [here](https://github.com/rspec/rspec-rails/issues/950) and Rails upgrade documentation on this subject is [here](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#csrf-protection-from-remote-script-tags), for reference.

**Comment by luisramos0** [comment]
Changing the target branch is not a good approach. I cherry-picked this commit on top of master and created this:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5651
If the build is green there we should go with 5651 instead, ok?

**Comment by luchiago** [comment]
@luisramos0 I saw the log in both builds on semaphoreci and the problem is with a specific test
```ruby
Failures:

  1) Taxonomies show should display existing taxonomies
     Failure/Error: within_row(1) { expect(page).to have_content("Brand") }
       expected to find text "Brand" in "Categories"
     # ./spec/features/admin/configuration/taxonomies_spec.rb:17:in `block (4 levels) in <top (required)>'
     # ./spec/features/admin/configuration/taxonomies_spec.rb:17:in `block (3 levels) in <top (required)>'
```
It seems not related to the fix I made, but I can fix this too.

**Comment by sigmundpetersen** [comment]
Yes, that one is a flaky spec. I've seen it in master and other PR's

**Comment by luchiago** [comment]
Alright, @luisramos0.

**Comment by luisramos0** [comment]
#5651 looks good
Closing this one.
Thanks a lot for this @luchiago :clap: it's great to see contributions to the rails upgrade project!

**Pull request closed without merging**
