### PR TITLE
unlock the ofn-install installation process

### LINKED ISSUE #10001: missing dependency and insufficient privileges
## Description
The [ofn-install](github.com/openfoodfoundation/ofn-install) repository used to deploy openfoodnetwork application  currently fails because of 2 points in the openfoodnetwork code : 
- a missing dependency  in the Gemfile : mini_portile2-2.8.0
- insufficient privileges on postgresql are granted to the user ofn_user used with database openfoodnetwork to create extension pg_stat_statement, see. https://github.com/openfoodfoundation/openfoodnetwork/blob/master/db/schema.rb#L16

## Expected Behavior
- the execution of a `bundle install --deployment` launched by a [task during deployment](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/deploy/tasks/deploy.yml#L62) should be successful.
- the execution of `bundle exec rake db:schema:load` launched by another [task during deployment](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/deploy/tasks/deploy.yml#L94) should also be successful.

## Actual Behaviour

- the execution of a `bundle install --deployment` launched by a [task during deployment](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/deploy/tasks/deploy.yml#L62) fails with the following error message : 
```sh
"bundler: failed to load command: rake (/home/openfoodnetwork/.gem/ruby/3.0.0/bin/rake)",
"Bundler::GemNotFound: Could not find mini_portile2-2.8.0 in any of the sources",
```

- the execution of `bundle exec rake db:schema:load` launched by another [task during deployment](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/deploy/tasks/deploy.yml#L94) fails with the following error message : 
```sh
"rake aborted!",
"ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create extension \"pg_stat_statements\"",
"HINT:  Must be superuser to create this extension.",
```

## Steps to Reproduce

1. begin with a clean environment : gem folder empty and a brand new postgresql instance
2. run `bundle install --deployment`
3. the first error (missing dependency) appears
4. run  `bundle install` should solve (= work around) the problem
5. run then `bundle exec rake db:schema:load` 
6. the second error (unsufficient rights) should appear

## Severity

bug-s3: a brand new installation is currently not possible with the current ofn-install procedure, but it's not critical since we don't install new server currently

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by heroinedor**
#### What? Why?

- Closes #10001 

- missing dependency added to Gemfile
- pg_stat_statement extension creation taken off from the schema.rb file because this postgresql extension is in reality created by the datadog role in ofn-install ( see : https://github.com/openfoodfoundation/ofn-install/blob/master/roles/datadog/tasks/pg_stats.yml#L2 ). It can not be created by rake because it is executed with the ofn-user which does not have the SUPERUSER right requested to create the extension ( see : https://www.postgresql.org/docs/current/pgstatstatements.html ) 

#### What should we test?

As explained in the issue 
- begin with a clean environment : gem folder empty and a brand new postgresql instance
- run `bundle install --deployment` => it should now be successful
- run then `bundle exec rake db:schema:load`=> it should also be successful

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Thanks @heroinedor !
One comment: i'd squash commit b4e4be6b64f29ff22153e03923bba85ba405765f and 39125487b57d7ae7289c5a8f1c4c9eb573f1517d to have a great git history.

I'd love to have @mkllnk approval, but I guess he is currently not available

**Review by dacook — APPROVED** [review]
I'll admit I'm not aware of why this is needed yet; I hope to get up to speed next week.
But in the meantime this looks fine to me:

1. I don't understand why the new gem is needed, but I guess shouldn't break anything


2. It looks like the `enable_extension` line was accidentally brought back from a production instance recently, so it makes sense to remove it again. 
I can confirm when I `rake db:migrate` in my dev env, the line gets removed anyway

**Comment by jibees** [comment]
> I'm not sure if it's necessary for user testing of technical changes?

Yes, you're probably right. 

So let's merge once @heroinedor squash the two commits https://github.com/openfoodfoundation/openfoodnetwork/commit/b4e4be6b64f29ff22153e03923bba85ba405765f and https://github.com/openfoodfoundation/openfoodnetwork/commit/39125487b57d7ae7289c5a8f1c4c9eb573f1517d (if it makes sense to you)

**Comment by heroinedor** [comment]
Shall we simply merge the 3 commits together at the merge time (option : squash and merge) ?

**Comment by jibees** [comment]
> Shall we simply merge the 3 commits together at the merge time (option : squash and merge) ?

Then we'll lost the comments (useful) on commits (which aren't not exactly related). I can do the squash, let me 5min I'll force push your branch :p

**Comment by sigmundpetersen** [comment]
Build is green 🎉 💪 
https://github.com/openfoodfoundation/ofn-install/actions/runs/3496471866

**Pull request merged**
