### PR TITLE
Migrate StripeConnect to StripeSCA

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

Part of #7872 

This PR migrates StripeConnect to StripaSCA via Rails migration

Changelog Category: Technical changes

#### Dependencies
#7978

### CODE REVIEW

**Review by andrewpbrett — COMMENTED** [review]
Won't this result in many instances having two StripeSCA payment methods available? Would it be better to remove the Connect payment method entirely?

**Comment by apricot12** [comment]
> Won't this result in many instances having two StripeSCA payment methods available? Would it be better to remove the Connect payment method entirely?

@andrewpbrett Is it okay if we removed StripeConnect entirely? I thought we were migrating to preserve the old data? Or maybe we should make another dummy payment method to dump this into?

**Comment by andrewpbrett** [comment]
I think we actually do want to keep it, as you've done here. The scenario I wanted to avoid was having two identically named providers on the `admin/payment_methods/new` page; I think that we will avoid this as part of the changes in #7978. It might be better if this migration were a part of that PR, since I don't think we could/should merge this separately.

**Comment by andrewpbrett** [comment]
Closing in favor of #8064

**Pull request closed without merging**
