### PR TITLE
Webdrivers

### LINKED ISSUE #3450: Chrome and chromedriver version compatibility
## Description

We use headless Chrome and chromedriver to run our automated tests. The versions of the two need to be compatible. If you install both through your system's package manager they should be good. Semaphore provides compatible versions as well.

While most developers have Chrome installed, many new developers don't have chromedriver installed and need to do that extra step to set up. We started using the chromedriver-helper gem which installs the chromedriver automatically. That makes onboarding new developers or setting up a new computer much easier. Unfortunately, chromedriver-helper doesn't know which version it needs to install. It installs the latest by default which may not be compatible with the installed Chrome version.

Chromedriver-helper Installing the latest chromedriver version broke our Semaphore builds. If we want to have the convenience of chromedriver-helper, we need to find a configuration that will not break the build and is still convenient for developers.

## Expected Behavior

- Semaphore can run specs successfully.
- Developers don't have to manually install chromedriver.

## Actual Behavior

Semaphore fails.

## Severity

The Semaphore build was modified to install a newer Chrome version which fixes the build for now. But that may not be the ideal solution.

## Possible Fix

- Remove chromedriver-helper and not have the convenience of automated chromedriver installs.
- Install latest Chrome on Semaphore. This doesn't solve the problem for development environments with older Chrome, e.g. Debian stable.
- Configure chromedriver-helper to install specific version. This will need updating from time to time and we have to find a version that is compatible with all development environments and Semaphore.
- Can we configure chromedriver-helper to not install anything if the system provides chromedriver already?

### PR DESCRIPTION
**Pull request by eelcodevlieger**
#### What? Why?

Closes #3450

The 'chromedriver-helper' gem has been deprecated and replaced by the 'webdrivers' gem.
https://rubygems.org/gems/chromedriver-helper/versions/2.1.1
https://rubygems.org/gems/webdrivers/versions/3.8.1

This should allow for
 * better future support
 * the option to do version pinning
      - for example specifying Webdrivers::Chromedriver.version = '2.46'
      - see docs: https://www.rubydoc.info/gems/webdrivers/3.8.1

NOTE: only been able to partially test this due to local database issues

#### What should we test?
test that the automated test suite completes (including web/selenium tests)

#### Release notes
The 'chromedriver-helper' gem has been deprecated and replaced by the 'webdrivers' gem.

Changelog Category: Changed

#### Documentation updates
There might be a wiki testing page that references the old chromedriver-helper

### CODE REVIEW

**Comment by luisramos0** [comment]
I think we need to remove this line from the build in semaphore:
bundle exec ./vendor/bundle/ruby/2.1.0/bin/chromedriver-update 72.0.3626.69

but if we remove it we may break all other builds. so we may need to remove it temporarily to test this PR?

**Comment by sauloperez** [comment]
@eelcodevlieger could set up a sempahore CI for his own fork and run it there but that involves a lot of manual work. Might be easier to do as you suggest @luisramos0

**Comment by mkllnk** [comment]
I changed the Semaphore config to only run that script if it exists. We will see in half an hour if it works.

**Comment by luisramos0** [comment]
it works, green build.

shall we go forward with this? I am a bit out of context here so Ill leave the review for other devs.

**Comment by Matt-Yorkley** [comment]
Yes, I think `Webdrivers` is the defacto way to manage selenium/chrome drivers now, and everybody else has already switched. Our current chromedriver gem has big deprecation warnings on their repo page. 

Lets do it!

Thanks @eelcodevlieger ! :heart:

**Comment by mkllnk** [comment]
I would love to go ahead with this but it doesn't work on my computer. The spec helper raises the following error:
```
     Failure/Error: bridge = driver.browser.send(:bridge)
     
     NoMethodError:
       undefined method `strip' for nil:NilClass
     # ./spec/spec_helper.rb:59:in `block in <top (required)>'
```

Does anyone else have that problem? It may be chrome version specific as it seems fine on Semaphore.

@luisramos0 You contributed the code that fails for me. Do you have any idea what's happening here?

**Comment by luisramos0** [comment]
those lines were added to make file downloads work in specs with headless chrome... #3651

I am not able to run feature specs locally today (even with master) for some reason, I need to sort that out first :-)

**Comment by eelcodevlieger** [comment]
@luisramos0 Hi Luis, did you manage to run feature specs locally again with master?

**Comment by eelcodevlieger** [comment]
There is a StackOverflow answer to suggest this workaround is no longer needed and can be replaced by calling 'tap' on the selenium driver:

```
  driver = Capybara::Selenium::Driver.new(
  	app,
  	browser: :chrome,
  	options: options
  ).tap { |d| d.browser.download_path = DownloadsHelper.path.to_s }
```

https://stackoverflow.com/questions/52640691/chrome-headless-download-pdf-using-capybara-and-selenium

Do you have a specific spec that requires this headless file download function we can verify this with?

**Comment by luisramos0** [comment]
hello @eelcodevlieger sorry for the slow reply, we have been in France in the OFN gathering this past week.
I tried now and it's all good for me, I can run all specs in this branch including spec/features/admin/reports/enterprise_fee_summaries_spec.rb

@mkllnk will be on holidays one more week so we may need to wait....
or shall we go ahead if this works for @sauloperez and/or @Matt-Yorkley?

**Comment by luisramos0** [comment]
Really nice one that stackoverflow hint @eelcodevlieger 
It works for me locally.
I added it as one new commit to this branch, let's see if this works well in semaphore and also see if this works for other people locally 🤞

**Comment by luisramos0** [comment]
yeah, build green, looking good.

so, ping @sauloperez and/or @Matt-Yorkley. please let us know if this works for you locally:
spec/features/admin/reports/enterprise_fee_summaries_spec.rb

**Comment by Matt-Yorkley** [comment]
I'm getting this when I run it locally: 
```
rspec: No such file or directory - --product-version

NoMethodError: undefined method `strip' for nil:NilClass

  0) enterprise fee summaries navigation when accessing the report as an superadmin shows link and allows access to the report
     Failure/Error:
       Capybara::Selenium::Driver
         .new(app, browser: :chrome, options: options)
         .tap { |driver| driver.browser.download_path = DownloadsHelper.path }

     NoMethodError:
       undefined method `strip' for nil:NilClass
     # ./spec/spec_helper.rb:57:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:57:in `block in <top (required)>'
     # ./spec/features/admin/reports/enterprise_fee_summaries_spec.rb:25:in `block (4 levels) in <top (required)>'
     # -e:1:in `<main>'
```

**Comment by Matt-Yorkley** [comment]
Turns out I had some other versions of `chromedriver` installed elsewhere, and I needed to reinstall `chrome`.

It works now :+1:

**Comment by sauloperez** [comment]
I still need to figure out how to make it work with my dev container setup so happy to merge.

**Comment by luisramos0** [comment]
nice 🎉

**Pull request merged**
