### PR TITLE
Break up large spec files

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?
 Knapsack evenly distributes spec files to run in parallel, but can't break up spec files to run in parallel. 
I noticed that a couple of large spec files were much longer than others, and therefore causing a bottleneck.

Also, I think we can change one of the runners to run more system specs, because the models are nice and quick.

#### What should we test?
-  green specs
- quicker runtime
- review the 'Usage' list to see individual runtimes (scroll to bottom left of Actions summary).

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by dacook** [comment]
One system_admin spec was still 7m, but maybe after this is merged, Knapsack will have better data to more evenly distribute specs. 

-----

Excerpt from logs shows that spring is used for both rake and rspec commands. I couldn't see timestamps to prove the time saving.
```
Run bin/rake db:create db:schema:load

Heads up! 🔥

👉 StimulusReflex requires caching to be enabled. Caching allows the session to be modified during ActionCable requests.

To enable caching in development, run:

  rails dev:cache

Running via Spring preloader in process 2883
Database 'open_food_network_test' already exists

Run bin/rake knapsack_pro:queue:rspec
Running via Spring preloader in process 2891
```

**Review by mkllnk — APPROVED** [review]
Thank you! This is great.

**Comment by dacook** [comment]
Thanks, I just had a look at the latest master build, and it was done in 6m 19s. 
The longest runner was 6m 9s, executing only `spec/system/admin/order_spec.rb`.
Second longest was 5m 24s, for `spec/system/admin/subscriptions/crud_spec.rb`.

So those are the next bottlenecks to attack..

**Comment by dacook** [comment]
FYI @filipefurtad0 I made a few tweaks to CI here ^

**Pull request merged**
