### PR TITLE
Adding tweaks that have been missed from merges

### LINKED ISSUE #518: Customer account / payment methods report improvements
and question . .

This report takes ages to load in a system that has lots of info in it. I'd suggest putting an initial filter into it (like the other reports), that only loads the last week or month to start with, so that it doesn't take so long to come up

image

Also, I am getting some data in it that doesn't make much sense to me. I am trying to work out what's going on, but not quite sure what it's trying to do, so just putting in a bunch of potential issues below and you can separate them out as you see fit :)

Issue 1: 
Logged in as southeastfood hub. The coordinator of sefhub has quite a few orders under her name (Naomi Atkins) BUT some of these are on her personal email and others on the admin email  
It appears that the balance calculation is using her name rather than the login email. I'm pretty sure this is incorrect, should be using the User (distinct email address) not the customer name for this calculation
image

image

Issue 2:
when looking at the same user (e.g.     ), different entries have different balance values

image

image

Issue 3:
Assuming a +ve balance mean she is owed, and -ve balance means she owes, then the negative balance should add up to unpaid orders under that User (email)

This is showing (variously) the two values above, and one at -$5K (and a couple of others). 
image

I'm not sure where these values are coming from - can you tell me what it should be calculating (user, name, hub combo etc?) so I can then see if it is. The figures don't seem to be total outstanding against any of the above from my first estimates

### PR DESCRIPTION
**Pull request by lin-d-hop**
@kirstenalarsen @oeoeaio @NickWeir63 + others that I should be pinging...

Hi all,

Ok, so after doing some digging I have found that a lot of the report refactorring had already been merged into master... so that code has been there for a while  :-/ 

I'm not sure what happened. It looks like Rohan included the reports refactoring before he went away and it is still in master. If you look at lib/open_food_network/bulk_coop_report for example you can see that its history goes back to a cherry-picked refactorring commit. So the reports refactorring is in master and has been for a while and perhaps some of the world exploded?

Only specific cherry-picked commits of the work I was doing made it in. This is why the order_cycle_management report has been broken for a while. But thanks @RohanM being flexible around getting these reports merged when you did. Seems it was an awkward request so my apologies for that.

For these changes I created a branch on the main code base (rather than my fork, which isn't updating properly) to push my code for this PR. It actually seems simpler doing it this way instead of going via my fork so unless there are any objections I might continue doing that....

Soooo.... what all this means is:
a) It's not worth you doing the staging2 before and after testing @NickWeir63 because the code is not going to change significantly, the changes are already there.
b) This PR has the updates that have been missed that will fix #518, #265 and #264 all being well.

If this can go on to staging on Friday then @NickWeir63 could test the packing reports and order cycle management reports for the following Weds.

Thanks, let me know if any issues :-)

### CODE REVIEW

**Comment by lin-d-hop** [comment]
Hi all, @kirstenalarsen @oeoeaio @mkllnk 

Just wondering if there was a reason this didn't get merged on Friday? Would be good to get feedback to try get it in this week.

Cheers,
Lynne

**Comment by mkllnk** [comment]
@lin-d-hop This is staged at the moment (staging2). We can stage any of our branches as long as they pass the tests on the CI server. The master branch is equivalent to the deployed code on the production server.

**Comment by lin-d-hop** [comment]
thanks @mkllnk! 

I now have a few questions... Perhaps you can help?

I thought the tweaks in this branch would fix some of the bugs I've been seeing. And logging into staging2, they didnt. So to inspect wtf was going on I cloned a new repository, changed into the branch 'reports-tweaks' and ran local server. When I do this the changes aren't actually on the branch... the files are the same as before I committed this branch. This fits with the behaviour I see on staging2...

Why might the branch not actually show the changes on the fresh checkout? 
The changes are on the branch when I look at the code directly from the project in the browser.
I'm really confused... :-/

Thanks in advance for any insight.

**Comment by mkllnk** [comment]
I'm not sure. If I checkout this branch, I can see the changes as they appear on GitHub.
```sh
git fetch
git checkout origin/reports-tweaks
git grep listing_ocm # shows me three new lines that are in your commit
```

How do you know that your changes are not there?

If I log in as admin and visit https://staging2.openfood.com.au/admin/reports/order_cycle_management, I get a server error.

Bugsnag gives me the stacktrace:
```
NoMethodErrorundefined method `firstname' for nil:NilClass
lib/open_food_network/order_cycle_management_report.rb:60delivery_row
	Icon link out.5751c0fa
lib/open_food_network/order_cycle_management_report.rb:31block in table_items
	Icon link out.5751c0fa
lib/open_food_network/order_cycle_management_report.rb:31table_items
	Icon link out.5751c0fa
app/controllers/spree/admin/reports_controller_decorator.rb:97order_cycle_management
```

**Comment by lin-d-hop** [comment]
Thanks for looking into that @mkllnk . Getting the Bugsnag is really useful. Is there a way I can access the bugsnags myself? 

I checked again on the branch and you are right, my code was there. N00b error. Sorry :-)

So another question about the "NoMethodErrorundefined method `firstname' for nil:NilClass"....

This must be a change in the data itself as it is new and doesn't happen locally. Grumpy cat also occurs now in the Customers reports, that also use the same method to access order.billing_address.firstname.

@oeoeaio Might this be related to using the orders structure for billing? Is there now no firstname in some orders.billing_address? What other fields in order can now be null?

If this behaviour is what is wanted I will update the two reports to handle having null details in the order.

Cheers :-)

**Comment by mkllnk** [comment]
About the error: It is a bit confusing. It says that the method `firstname` is missing. But that is not the point. It also says " for nil:NilClass". That means that the address is missing. The address is nil and nil is an object itself that doesn't not have the method `firstname`. That means that we have objects (orders?) in our database without an address. Not sure if that is valid or a bug to be solved. I'm not familiar with that code.

**Comment by kirstenalarsen** [comment]
I’m guessing this could be something to do with the enterprise account orders - they maybe don’t have addresses. Will get @oeoeaio to check tomorrow . .

**Comment by kirstenalarsen** [comment]
@lin-d-hop @NickWeir63 - are you able to confirm that this is only a problem for superadmin e.g. if you are an enterprise admin, your reports shouldn't pull up these 'enterprise accounts' orders and so shouldn't have the address / grumpy cat problem? This relates to urgency of fix - if you are able to test and it does what you need as enterprise managers then is ok (if annoying) for immediate use because the problem only occurs as super-admin, which is good because it's in production here in Aus :)  

I am asking this in the full knowledge that when you get this question the branch will no longer be in staging . . but it will be back for your Friday . .

**Comment by kirstenalarsen** [comment]
ok, so we think this is probably us but haven't had a chance to look at it this week as @oeoeaio has been pulled into dealing with https://github.com/openfoodfoundation/openfoodnetwork/issues/673 as a matter of urgency, and it's turned out to be a bit tangly! So we haven't put your reports back in staging for the weekend - sorry. However, if you have some testing capacity, we would GREATLY appreciate you doing some checking of the reports to see if they are now reading correctly from the updated / variable weights values! We're putting that in staging now, but it's changing quite a lot of stuff so very reluctant to go live (despite user pressure) without some serious testing! @NickWeir63 - any chance?

**Comment by kirstenalarsen** [comment]
can that - tests failed so not in staging :(

**Comment by lin-d-hop** [comment]
@kirstenalarsen can you post that? I can only see it passing when I log into buildkite.

**Comment by kirstenalarsen** [comment]
no no, the branch that I was hoping you could test instead failed - see my comment a couple up. We haven’t looked into your one yet so haven’t rebuilt

how you coping with the explosion of activity? I feel like you’re being hit from every direction!!

**Comment by lin-d-hop** [comment]
oh got it :-) It's nice to see everything so lively ;-)

**Comment by lin-d-hop** [comment]
Hi @kirstenalarsen @RohanM 
Just wondering if this is still on the cards to merge? Any progress? Thanks!

**Comment by oeoeaio** [comment]
Sorry @lin-d-hop, my fault. Will try and get something moving tomorrow. Thanks for the reminder! :)

**Pull request merged**
