### PR TITLE
Display a warning when clicking the generate invoice button if an ABN is required but not present

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

- Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/11940

#### What should we test?

See #11940

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled (under `invoices`)

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good ! thanks for your help.

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @cillian,
Thanks for working on this improvement!

I can confirm, that the 'ABN required' note is now shown for the 'Create or Update Invoice' button as well. :+1: 
It's correctly blocking the user from performing this task, if no ABN is set. :heavy_check_mark: 
If the ABN is set, the 'ABN required' note is not shown and the user can perform the task. :heavy_check_mark: 
This is working for both current and new admin v3 design. :heavy_check_mark: 

image

One minor thing, when the created invoice is not shown immediately:
1. Remove the ABN from the enterprise.
2. In a different browser tab go to the /invoices page of an order which doesn't have an invoice yet.
3. In the first tab add the ABN and click 'Update'.
4. In the second tab refresh the page.
5. In the second tab click the 'Create or Update Invoice' button.
6. There is no 'ABN required' note, so refreshing the page made it aware, that the enterprise now has an ABN available. The invoice is being created, but it is not immediately shown in the list. Only after refreshing the page (or leaving and coming back) it is shown.
I don't understand why this is happening. Do you have an idea?
It's definitely an edge case and we don't need to invest much time, I was just surprised that refreshing the page BEFORE clicking the button is not enough. If the ABN was there all the time, then the invoice is listed immediately.

## Conclusion
The main issue here is fixed, we are left with an edge case. And this whole thing is still behind a feature toggle, so we are safe to merge this one! :muscle: 

## Questions
@RachL What do you think about the edge case. Does it need an issue?

Thanks again, Cillian! Merging now! :tada:

**Comment by RachL** [comment]
Thanks Konrad, I guess some people will want to do that when they have forgotten to add the ABN number. So not so edgy... but there is a workaround, perhaps it's an s4?

**Comment by cillian** [comment]
> The invoice is being created, but it is not immediately shown in the list. Only after refreshing the page (or leaving and coming back) it is shown.

@drummer83 thanks for investigating. I tried to recreate that issue but didn't have any luck yet unfortunately, the invoice appears immediately.

**Comment by drummer83** [comment]
Thanks for trying, @cillian! 

I can still reproduce it on both staging AU and UK, but my steps above were not complete. It seems like it has something to do with an added hash `#` at the end of the URL when the "ABN required message" is shown. Maybe this helps?

1. Remove the ABN from the enterprise.
2. In a different browser tab go to the /invoices page of an order which doesn't have an invoice yet.
3. NEW: Click 'Create or Update Invoice' button.
  - See the 'ABN required' warning.
  - See the added `#` at the end of the URL.
4. NEW: Confirm with 'OK'.
5. In the first tab add the ABN and click 'Update'.
6. In the second tab refresh the page.
7. In the second tab click the 'Create or Update Invoice' button.
8. There is no 'ABN required' note, so refreshing the page made it aware, that the enterprise now has an ABN available. The invoice is being created, but it is not immediately shown in the list. Only after refreshing the page (or leaving and coming back) it is shown.

**Comment by drummer83** [comment]
Issue is created here: #12157.

**Pull request merged**
