### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elf-pavlik** [comment]
how does it relate to #711 

do you use https://www.transifex.com/open-food-foundation/open-food-network/language/es/ ?

**Comment by elopio** [comment]
Ah, damn it. The en.yml didn't mention anything about transifex. That would have make things a lot more easy :)
I merged #711, added some translations from @kmoragas and uploaded the translations to transifex. The full spanish translation is now ready for review in there.

When uploading the file I polluted some of the suggestions with the source english strings, sorry about that.

Closing this one.

**Comment by mkllnk** [comment]
I added some instructions to `en.yml` (9f50b74680d5c4e27bb03dcdfa73fc9e43be8b0f).

**Comment by elopio** [comment]
Thank you for the added instructions.

**Pull request closed without merging**
