### PR TITLE
De-deface some admin configuration pages and the general admin layout and menu

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

There's no issue for this but this is part of #2807. In this PR I am de-defacing a few things in the backoffice:
- configurations - general settings
- configurations - image settings
- configurations - shipping categories
- main admin layout and admin/shared/head
- main admin menu

No functional changes done, just bringing code from spree, converting to haml and applying the defaces.

#### What should we test?
Make sure these pages show all fields and work as before:
- Configurations - General Settings page
- Configurations - Image Settings
- Configurations - Shipping Categories

The main admin menu has a new order of entries.

The main admin layout was de-defaced, in terms of testing I think a general test of menus, submenus and general page layouts should be enough. 

#### Release notes
Changelog Category: Changed
Removed deface from a few parts of the backoffice thus making OFN less entangled with Spree code.

### CODE REVIEW

**Comment by mkllnk** [comment]
@luisramos0 One failing spec.

**Comment by luisramos0** [comment]
and by that second line of thought, every spree module we remove from our list of dependencies represent thousands of lines of code we remove!

**Comment by RachL** [comment]
- Configurations - General Settings page

I change the configurations (cookies, title, terms and conditions...) all went well

- Configurations - Image Settings
A bit difficult to test, but adding / editing seems to work as usual.

- Configurations - Shipping Categories
Adding editing and deleting shipping categories is working good.

The main admin menu is working fine.
Menus, submenus and general page layouts are looking fine both on both latest Firefox and Chrome / Windows.

I tested super admin and manager's views. This is ready to go

**Comment by mkllnk** [comment]
I'm wondering why we didn't catch the breaking changes in here.

- Did the deploy not work properly?
- Or did we not test the pages that are broken?

@RachL Can you remember if you saw the affected parts when testing?

**Comment by RachL** [comment]
@mkllnk I had a quick look on the page layouts, but I didn't use ALL the pages except the ones listed above. So I may have miss these errors.
But I would like to be sure: what do you and @Matt-Yorkley think about when you say these are *broken* pages?
I'm noticing 2 things:
A. The table headers are bigger (which is ugly compared to the rest of the page but with my eyesight I'm actually for the first time reading them with no effort :) I'm looking forward to the day we change that and also that spree blue color for all text against a white background... but that's not the subject here :D )

B. On product, OC and subs pages, the icons are not centered

image

But these two things do not affect how the pages are working, or am I missing something?

**Pull request merged**
