### PR TITLE
Add Russian to list of momentJS locales

### PR DESCRIPTION
**Pull request by romale**
#### What? Why?

Closes #[the issue number this PR is related to]

image

#### What should we test?

Check that the OC selector in the front-office shows no English text. All in the one you selected. I still have you check where we use momentjs in the back-office.

#### Release notes

Show order cycle timing in Russian, Catalan, Arabic, and Turkish.
Changelog Category: Fixed

### CODE REVIEW

**Comment by sauloperez** [comment]
done! It did work this time.

Screenshot from 2020-07-29 12-52-50
Screenshot from 2020-07-29 12-53-11
Screenshot from 2020-07-29 12-53-23
I'll tweak that Catalan copy a but so it fits

**Comment by filipefurtad0** [comment]
Hey @romale ,

This is great... Order cycle timings are now shown in Russian, Catalan, Arabic, and Turkish! Pics below:

image

image

image

image


Thanks for putting this up in one PR!
Ready to go.

PS: @sauloperez, I noticed the Catalan message is not fitting the box right now. Should I open a separate PR for this?

**Comment by sauloperez** [comment]
Thanks @filipefurtad0 . I already fixed the translation and it'll look like

Screenshot from 2020-07-31 08-57-57

**Comment by RachL** [comment]
@sauloperez @luisramos0 what's the process to get it to work for other languages? I wanted to answer Theo's question here : https://openfoodnetwork.slack.com/archives/CFU9N7TGB/p1597936429001500 but I'm not sure what's the best next step.

**Comment by sauloperez** [comment]
Add the required momentjs locale file as done here but also have it listed in https://github.com/openfoodfoundation/ofn-install/blob/3031b9d682dc60d442fe1c28b11902b3bbd1b9a3/inventory/group_vars/be.yml#L8. I'm assuming [nl-be](https://github.com/derekprior/momentjs-rails/blob/master/vendor/assets/javascripts/moment/nl-be.js) is the one we want. If that's the case, we can do it right away.

**Pull request merged**
