### PR TITLE
Upgrade to Rails 7.0

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Using the latest version of Rails gives us the latest tools and best compatibility. It speeds up development and unblocks our transition of the asset pipeline.

#### What should we test?

- Log in before deploy and make sure that you are still logged in after.
- Test uploading images including error messages when uploading an unsupported image.
- Test checkout.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

#### Documentation updates

Follow-up issues to create:

- [ ] [2.12 New ActiveSupport::Cache serialization format](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format)
- [ ] [2.14 Active Storage default variant processor changed to :vips](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-storage-default-variant-processor-changed-to-vips)
- [ ] Apply Rails 7.0 config defaults (`./bin/rails app:update`)

### CODE REVIEW

**Comment by filipefurtad0** [comment]
I had a look at the failing system spec. It's on the sales tax by producers report:

`rspec ./spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb:344`

The filters `producer`, `order cycle` and `customer` seem not be appearing on the page - pic taken from the artifacts from GH Actions:
image

In master this appears correctly - pic taken from staging:

image

So, this one is not really spec related, perhaps a code change is needed. Any ideas @abdellani ? (pinging you as you were working on this recently)

**Comment by abdellani** [comment]
@filipefurtad0 
It seems to be related to the changes that I introduced on this [commit](https://github.com/openfoodfoundation/openfoodnetwork/pull/10175/commits/c87c8ed0df53176403567968759cd4107253e1e8#diff-fd897e65894a47a646cc5465887f9172a7db0327ca383459debc6da99382925f) to `app/views/admin/reports/show.html.haml`
 
I'm not able to reproduce the issue manually,  because the UI doesn't load properly on my local environment.
 
image

I switched to this branch and run `bundle` before running `rails s`.

@mkllnk  did I miss something?

**Comment by mkllnk** [comment]
> I switched to this branch and run bundle before running rails s.

It's always good to run `yarn` as well.

**Comment by abdellani** [comment]
>It's always good to run yarn as well.

@mkllnk I fixed the issue
I was running `./bin/webpack-dev-server` on another project.

**Review by abdellani — COMMENTED** [review]
The problem was on the "lookup_context.exists?".
I just needed to remove the last "/" from the partial path.

**Comment by mkllnk** [comment]
Legend, thanks @abdellani! Once the included PRs are merged I'll rebase this one and we can do some testing.

**Review by dacook — APPROVED** [review]
Yay, that seemed pretty painless!

**Review by jibees — APPROVED** [review]
Almost there!

**Comment by filipefurtad0** [comment]
Actually, this was tested and will be re-tested on release testing - so I see no reason to hold this back. Merging.

**Comment by mkllnk** [comment]
Wow, Rails has become a lot more mature. But I still have that "too easy" feeling as well. We'll see...

**Pull request merged**
