### PR TITLE
Remove dead code from OC edit page code

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Related to #4379

Delete dead code, see commit messages for details.

#### What should we test?
Create and edit OCs. Validate only variants are listed in the exchanges. Products can never be selected and master variants are also not displayed (master variants are never displayed in the system now).

#### Release notes
Changelog Category: Removed
Delete dead code, make Order cycle pages easier to maintain.

### CODE REVIEW

**Comment by luisramos0** [comment]
yes, thanks @mkllnk 💪

**Comment by luisramos0** [comment]
I messed up this branch by force pushing new stuff into it. I reverted and it's now as it was when approved :+1:

**Comment by filipefurtad0** [comment]
Hey @luisramos0,

Found no issues on creating and editing order cycles. Master variants are not shown for selection, so I think all is good here -> Moving to Ready to Go.

Perhaps a minor UX issue though:
I feel the "Select All" thick should disappear, after you unselect a variant. It should only be thicked, when all variants are selected, too - which does not happen on the pic below. Would this be something to open an issue on?

image

**Comment by luisramos0** [comment]
great, thanks Filipe!

That is a valid problem, you need to click twice on select all if you want to select all afterwards.
I am working on changing this list of products as a continuation of #4422, the select all button will be changed. So, you can create an issue or maybe just keep it in mind as we will need to test this in the next few weeks for sure.

**Comment by filipefurtad0** [comment]
Thanks for the feedback :-)
I will keep this in mind, untill the next test is due.

**Pull request merged**
