### PR TITLE
Merging master into 2-0-stable (one month of commits in master)

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Merging master into 2-0-stable.

This is the result of:
git checkout master
git pull upstream master
git checkout 2-0-stable
git pull upstream 2-0-stable

git checkout -b 2-0-stable-sept
git merge master

- resolved conflicts
git add spec/controllers/spree/orders_controller_spec.rb
git add Gemfile
git add Gemfile.lock

git commit
git push origin 2-0-stable-sept

The last commit of the last merge into 2-0-stable was on the 27th July, so this one looks good as it starts on the following commit on the 30th July and then goes up to the 4th of September.

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@luisramos0 

Please, please, #assignyourself, please! 🙏

**Comment by luisramos0** [comment]
one comment/question is: with local git log I see only one commit with the full merge, here in GH it shows all the 160 separate commits...

**Comment by sauloperez** [comment]
These are all the commits we're bringing in from `master`, those that weren't in `2-0-stable`, so I think it's all right.

**Comment by luisramos0** [comment]
I found a problem in the Gemfile, stripe should have been 3.3.2. It was a mistake in my conflict resolution.
SO, I went through every conflict resolution again in this PR. Much better now on the Gemfile.lock, I picked two more updates that Hugo had done on the 2-0- branch (climate_control and stringex). and also rabl 0.8.4. introduced by spree 2.

**Comment by luisramos0** [comment]
I was just waiting 2 approvals as a normal PR.

**Comment by sauloperez** [comment]
I thought we consider it one of those no-review PRs but it's fine.

**Pull request merged**
