### PR TITLE
Remove Migs payment gateway

### LINKED ISSUE #6232: Remove MIGS payment gateway
### What we should change and why (this is tech debt)

MIGS payment method is obsolete and should be removed from the OFN codebase (see discussion [here](https://openfoodnetwork.slack.com/archives/C4NDJT3FY/p1603291765051800?thread_ts=1603272008.051000&cid=C4NDJT3FY)).

### Context

This is related to #6231 .

This first came to light when rolling out v3, where it was spotted that only very few users were using this payment method. See [comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/5879#issuecomment-681125276).

### Impact and timeline

This should simplify the codebase and the upgrade from Rails 4.0 -> 4.1

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #6232

#### What should we test?
Harmless PR, almost pr-no-test.
A quick check on other payment  methods should be enough.

#### Release notes
Changelog Category: User facing changes
Removed MIGS payment gateway to avoid maintenance costs.

### CODE REVIEW

**Review by mkllnk — COMMENTED** [review]
Great!

I just checked on au-prod:
```
Spree::Payment.where(payment_method_id: Spree::PaymentMethod.where(type: "Spree::Gateway::Migs").select(:id)).maximum(:created_at)
=> 2018-07-13 04:02:24 UTC
```

It hasn't been used in over two years. @kirstenalarsen 

Just thinking: what happens if you try to look at an existing Migs payment method or payment? Are we gracefully dealing with this?

**Comment by luisramos0** [comment]
good point Maikel, we need a migration to maybe just rename them to Check.

**Comment by luisramos0** [comment]
ok, I have added the migration. I think this is good enough.

**Review by sauloperez — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by Matt-Yorkley** [comment]
I think a quick dev-test might be good, maybe: create a Migs payment method in staging, then deploy this PR and check it's been migrated.

**Comment by Matt-Yorkley** [comment]
Tested:
- Created a Payment Method using Migs, checked in the console
- Deployed
- Reloaded the created payment method page, it's updated and there were no errors
- Checked in the console, all good

Ready to go. Thanks @luisramos0 :heart:

**Pull request merged**
