### PR TITLE
Download report as attachment on Firefox

### LINKED ISSUE #9144: [Reports] Open PDF in new tab
This issue can only be worked on once https://github.com/openfoodfoundation/openfoodnetwork/pull/9032 is merged.

## Description
**- As a:** enterprise & super admin
**- On page:** ALL subpages of `admin/reports`
**- I want to be able to do:** When export in PDF, I want the PDF to open in a new tab instead of the same page I select all my filters. Currently it means the current page is lost.

## Acceptance Criteria & Tests

1. Log in as enterprise user
2. Go to `admin/reports`
3. Check all reports: if you download them as PDF, the PDF should open in a new tab

Repeat as super admin

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9144

#### What should we test?
- Export a report as a file (PDF, CSV, Spreedsheat) with both chrome and firefox
- File should be handled as an attachment, and therefore should be downloaded via the browser (and open in a new tab if firefox)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]

**Comment by RachL** [comment]
@jibees on Firefox it download AND opens in a new tab. Is that the desired behavior? I would say that if it opens in a new tab, the user can decide if they download or not?

**Comment by jibees** [comment]
Actually, it seems to be the default behavior of Firefox. 
Although Chrome only download the file, it seems that firefox download and open the file in a new tab (if it can be read by firefox)
This could be changed by firefox options itself: 
Capture d’écran 2022-05-18 à 11 03 07

**Comment by RachL** [comment]
@jibees it does open in a tab by default, but not download at the same time. But I will try out different aspects.

**Comment by RachL** [comment]
ok closing then :) Sorry for the trouble!

**Pull request closed without merging**
