### PR TITLE
Show product description in creation form after errors appeared

### LINKED ISSUE #6118: Product description is cleared if there are errors in the product form
## Description
This might be closer to feature request than bug... 

If I create a product, and type a really nice, long description with a lot of effort, but forget to do something else in the form (choose a Category for instance) and then I click Create, the form tells me about the error but wipes out all my wonderful work!

## Expected Behavior
The form should remember what I've entered in all the fields. 

## Actual Behaviour
The form remembers some fields (name, category, price) but not others (description, unit size, value, on hand)

## Steps to Reproduce

1. Go to https://openfoodnetwork.net/admin/products
2. Click New Product
3. Fill in description, unit size, value, on hand fields
4. Leave out one or more required fields
5. Click create

## Animated Gif/Screenshot
Screen Shot 2020-10-01 at 2 12 17 PM

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment
Safari

### PR DESCRIPTION
**Pull request by Snick555**
## What? Why?
Closes #6118

#### What should we test?
We need to verify the issue is fixed.

#### Release notes
Changelog Category: Fixed
Fixed a problem when creating a product, in case of errors the original entered product description will not be lost.

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]
Hello @Snick555 thanks for your PR.

**Review by sauloperez — APPROVED** [review]
Thanks a lot for this contribution @Snick555 !

**Comment by andrewpbrett** [comment]
I tried this out and it looks good to me! The description stays there after submitting the form with errors. Nice one @Snick555 🎉 

Do we think this should have a test to go with it? Given the tradeoff of a slower build?

**Comment by filipefurtad0** [comment]
Hey @Snick555 , Welcome!

Thanks @andrewpbrett for spotting and opening up this issue.

I checked the current behavior and indeed the most of the input fields are blanked out, on the current version. After this PR, the Product Description field is kept:

image

This is ready to go.
Thank you Ihor!! :tada: 


PS: 

I've spotted a couple of issues which are not introduced by this PR:

- it seems that the Price and In Stock are not really mandatory fields - this was however the case, till very recently. This looks like a recent regression, as after staging v.3.2.9 in Katuma staging, attempting to create a product without a price looks like this:

image

On the current master branch this is possible:

fields_not_mandatory

- filling out Unit Size but leaving Value empty leads to error 500/Snail (this seems to be "older" than the latest release), in fact these are known issues #3912 and #4959

**Comment by luisramos0** [comment]
I think that first one needs an issue.
I know the second issue very well, I got a call about it from my farmer when I was in the middle of nowhere :rofl:

**Pull request merged**
