### PR TITLE
Use the same Rubocop config on Code Climate as locally 

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

We configured Code Climate to be aware of all open issues instead of ignoring open issues via the rubocop todo lists. We were hoping that Code Climate could give us some nice stats like progress if it's aware of all our open issues. But the graphs don't tell us anything.

In addition, developers get confused about how our setup works because running rubocop locally would yield different results to the feedback Code Climate gave on pull requests. And new violations had to be added in two places. Adding it to a rubocop todo list made sure that the violation didn't come up when running rubocop locally. But Code Climate would still complain about it and we needed to accept it there, too.

So it's better to have one source of truth for our open style issues and that is our rubocop config in this repository. It contains two todo lists that document all violations we would like to fix in the future but it's okay to submit pull requests that don't fix those.

Instead of accepting new style issues in Code Climate, every pull request with new violations has to add them to the rubocop config. I hope that this will make rubocop more useful and encourage developers to reduce code style debt.

#### What should we test?

No test.

#### Release notes

Changelog Category: Technical changes

Simpler setup of code quality checks.

#### Context

Here are some screens of the Code Climate dashboard. I can't see anything useful in there.

Screenshot from 2021-03-31 15-17-38
Screenshot from 2021-03-31 15-21-16
Screenshot from 2021-03-31 15-20-44
Screenshot from 2021-03-31 15-19-37
Screenshot from 2021-03-31 15-18-17
Screenshot from 2021-03-31 15-18-07

### CODE REVIEW

**Review by sauloperez — COMMENTED** [review]
Thanks for taking this on @mkllnk . I agree Code Climate didn't provide us much value.

I see we won't be using the `accept changes` button from Code Climate anymore but I still don't understand why we need that second config file `.rubocop_styleguide.yml`. I may have missed something from your PR description.

**Comment by mkllnk** [comment]
> I still don't understand why we need that second config file .rubocop_styleguide.yml.

We don't need that file any more. I just did the smallest possible changes. I'll merge the configs so that it's easier to understand.

**Comment by mkllnk** [comment]
Actually, the order in which we load the config files is important. Currently we do this:

  - .rubocop_todo.yml
  - .rubocop_styleguide.yml
  - .rubocop_manual_todo.yml

If we copy the contents of `.rubocop_styleguide.yml` into `.rubocop.yml`, we have a lot of content and then another inherit. Or we need to copy the manual todo list into the config as well and it might be difficult to find. What do you think @sauloperez, should we leave it as is or copy it all (except .rubocop_todo.yml) into the normal config?

**Comment by sauloperez** [comment]
I personally prefer to have a single file for simplicity and because I'm used to Rubocop's standard (I don't need to find out anything specific) but it's fine as is.

**Review by sauloperez — APPROVED** [review]

**Review by jibees — APPROVED** [review]

**Pull request merged**
