### PR TITLE
BOM: Display confirm modal on date range change only one time

### LINKED ISSUE #9757: [Flaky] spec/system/admin/bulk_order_management_spec.rb
### What we should change and why (this is tech debt)

```
Failures:

  1) 
  As an Administrator
  I want to be able to manage orders in bulk
 using page controls using date restriction controls when the form is dirty shows a dialog and keeps changes when confirm dialog is rejected
     Failure/Error: expect(page).to have_selector "input[name=quantity].ng-dirty"
       expected to find css "input[name=quantity].ng-dirty" within #<Capybara::Node::Element tag="td" path="//HTML[1]/BODY[1]/DIV[1]/DIV[1]/DIV[4]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[5]/FORM[1]/TABLE[1]/TBODY[1]/TR[2]/TD[11]"> but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_be_able_to_manage_orders_in_bulk_using_page_controls_using_date_restriction_controls_when_the_form_is_dirty_shows_a_dialog_and_keeps_changes_when_co_694.png

     
     # ./spec/system/admin/bulk_order_management_spec.rb:619:in `block (6 levels) in <top (required)>'
     # ./spec/system/admin/bulk_order_management_spec.rb:618:in `block (5 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'
```

I ran this spec ten times and it failed eight times. Pretty bad.

### Context

This came up when trying to remove retries:

* https://github.com/openfoodfoundation/openfoodnetwork/pull/9635

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Previously, when changing the date range, we had several modals that opened. Now, the `confirmRefresh()` method should be open only one time.

Closes #9757

##### Updates after some testing
Actually this one introduce another issue: when clicking on dismiss for the modal, the date range values doesn't reset to the previous (ie. before dismissing) values. I can't make it work for now.

#### What should we test?

- As an admin, visit the Bulk Order management page `/admin/orders/bulk_management`
- Change something in one order (or more), like the "" value
- Change the date range via opening the daterange picker. You should see a modal that either you could accept or dismiss
- If accept: this should reload the orders with the current date range
- If dismiss: this should do nothing

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
Actually I spend many times on it. 
Currently, I don't know how to solve this issue (ie. the one that doesn't change the date range to previous value). Don't know if I should let this PR in draft mode (and work on it later) or _merge_ this one and open an ticket to solve the issue triggered here.
@filipefurtad0 any idea?

**Comment by filipefurtad0** [comment]
It's a hard call :-)
I personally don't like the repeating modal and have the "hope" it improves flakiness.

I'd say let's review/test?

**Comment by jibees** [comment]
@filipefurtad0 
Actually, it seems that I managed to handle that point and now the date range picker is reset to the previous dates

**Comment by filipefurtad0** [comment]
@jibees I've noticed the build failure on this PR and propose a solution here https://github.com/openfoodfoundation/openfoodnetwork/pull/9934.

**Comment by jibees** [comment]
> @jibees I've noticed the build failure on this PR and propose a solution here #9934.

That failing was actually quite normal since I added a `prev_day(1)` to make it pass on my local setup. 
Modified, and let see if it's green!

Thanks! 🙏

**Review by mkllnk — APPROVED** [review]
Nice! Thank you.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

I've now checked both scenarios after changing a quantity of a line item, and then changing the date range:

- accepting the modal does not trigger further modals -> the change is effective at "first try"
- not accepting the modal i) keeps the changes and ii) resets the date range

Perfect!! :tada: 
Merging.

**Pull request merged**
