### PR TITLE
[Spree Upgrade] Merging master into 2-0-stable (4th run in Mar2019)

### PR DESCRIPTION
**Pull request by luisramos0**
Merging master into 2-0-stable.
Same as previous #3640
 This is the result of: 
git checkout master

git pull upstream master

git checkout 2-0-stable
git pull upstream 2-0-stable git checkout -b 2-0-stable-Mar29
git merge master

####Conflicts:

CONFLICT (content): Merge conflict in spec/lib/open_food_network/orders_and_fulfillments_report_spec.rb
	   keep master and replace factory  line_item with line_item_with_shipment in a few places
	   git add spec/lib/open_food_network/orders_and_fulfillments_report_spec.rb
            **I am having trouble with the new specs from #3646**, @kristinalim @mkllnk could you please have a look?

CONFLICT (content): Merge conflict in app/controllers/spree/admin/variants_controller_decorator.rb
	keep HEAD
	git add app/controllers/spree/admin/variants_controller_decorator.rb
	remove delete_and_refresh_cache from variant_decorator
	git add app/models/spree/variant_decorator.rb
	remove delete_and_refresh_cache tests from variant spec
	git add spec/models/spree/variant_spec.rb
	thanks @sauloperez for directions [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/3639#issuecomment-477020099), it made the merge very easy. **I thought it was working but the build is broken here as well** in app/models/spree/variant_decorator.rb @sauloperez could you please have a look?

CONFLICT (content): Merge conflict in Gemfile.lock
	keep 2-0 but update stripe to 4.11
	git add Gemfile.lock

CONFLICT (content): Merge conflict in Gemfile
	keep 2-0 but update stripe to 4.11
	git add Gemfile

git commit
git push origin 2-0-stable-Mar29

#### What should we test?

On Zenhub, this PR is connected with _and_ blocks #3625.

According to PR #3647, #3625 needs to be solved already in this merge PR.

there are also these PRs that are now brought to v2 (I am not sure we need to retest): #3662, #3646 and #3644

### CODE REVIEW

**Comment by kristinalim** [comment]
@luisramos0 @mkllnk I've appended a commit fixing failing specs for the Customer Totals report.

@sauloperez Just let us know if you want us to help look into the failing specs for variant deletion.

**Comment by luisramos0** [comment]
thank you very much @kristinalim 🙏

**Comment by sauloperez** [comment]
Fixed! Sorry for my late notice and thanks for the offering @kristinalim

**Comment by luisramos0** [comment]
ah, awesome, thanks a lot team!!!

**Comment by luisramos0** [comment]
This was one week old already so I run another git merge master into this branch.
Conflicts and broken specs fixed in 3 additional commits, have a look.

**Comment by luisramos0** [comment]
yeah, I have added 3 more PRs that are brought to v2 with this.
Anyway, this is last big merge from master 🎉

**Comment by luisramos0** [comment]
apologies for bypassing the process, I decided to merge this now so we can test everything together (#3604 for example) now.
if there are problems with this we can create new issues.

**Pull request merged**
