### PR TITLE
[BUU] Activate admin_style_v3 for ~50% of users

### LINKED ISSUE #12707: [BUU] Activate admin_style_v3 for 50% of users
⚠ Please use clockify code https://github.com/openfoodfoundation/openfoodnetwork/issues/7198 Back Office Uplift (Product) while reviewing or working on this task.

**TO BE RELEASED On August 6th**

## Description
**- As a:** super admin
**- On page:** `/admin/feature-toggle/features`
**- I want to be able to do:**  See that on top of the admin and new users groups, the toggle is also activated for 50% of users

## Acceptance Criteria & Tests

1. Before the PR only admins + new user + 25% + dedicated actors eventually should have had access
2. After: same as 1 + 50% of users instead of 25

We will trust filpper to work on this one, we won't check if it is really 50%

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

- Closes #12707

#### What should we test?
See issue

#### Release notes

I'm not sure exactly  how many users are affected, but perhaps its time to start reporting as user-facing changes?

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by RachL** [comment]
@dacook I've tried the following test: 

- disabling the feature, deploying: the feature gets activated for 50%
- staged master then switched on to 2 groups (admins, new_...) + 25%. In that case deploying the PR didn't change the percentage. 

Is this a risk in production too?

**Comment by dacook** [comment]
Hi @RachL , I think that's ok. Rails migrations are designed to run once on the database, and so it remembers if it's been run before, and doesn't retry the second time. 
Just to be sure, I double-check on my machine to confirm that the 50% overwrites the 25%:

## Before
Screenshot 2024-08-01 at 9 21 05 am
```
== 20240731065321 ActivateAdminStyleV3For50PcUsers: migrating =================
== 20240731065321 ActivateAdminStyleV3For50PcUsers: migrated (0.0282s) ========
```
## After
Looks good ✅
Screenshot 2024-08-01 at 9 21 27 am

**Comment by dacook** [comment]
PS @RachL can you confirm if this should be listed as a user-facing change?

**Comment by RachL** [comment]
@dacook awesome! I guess BUU is entering the "user facing change" category you are right 🎉

**Pull request merged**
