### PR TITLE
Updated hash syntax to Ruby 1.9 symbol notation

### PR DESCRIPTION
**Pull request by askl56**

### CODE REVIEW

**Comment by oeoeaio** [comment]
Hi @askl56,

Thanks for this, hope you found a way to automate this and didn't have do to it manually! Just noticing there are still some spec failures, if you rebase this branch on the current master it will fix ``spec/features/admin/bulk_order_management_spec.rb:428`` for you, but I think the rest of the failures will need attention. Any chance you could have a look at those and push up some fixes?

**Comment by askl56** [comment]
Sure. I'll also implement Ruby style guide changes.

**Comment by askl56** [comment]
Hmm @oeoeaio I will take a look at this tomorrow. I'm keen to get on board with the team and help this project as much as I can.

**Comment by askl56** [comment]
im gonna reset to master, then start this again.

**Comment by oeoeaio** [comment]
@askl56 Sorry, I've been away. Back now. Let me know if you need anything to help out with this.

**Pull request closed without merging**
