### PR TITLE
Provide specific tab widths for shop tabs when screen width > medium

### LINKED ISSUE #2347: Enterprise tabs in shopfront display on two lines
https://github.com/openfoodfoundation/openfoodnetwork/pull/2331 made the shopfront tabs display in two lines. I accidentally merged that before it was tested.
## Expected Behavior

The tabs are on one line.

screenshot from 2018-05-30 16-39-03

## Actual Behavior

The tabs are on two lines.

## Steps to Reproduce

1. Go to any shopfront.

## Animated Gif/Screenshot

screenshot from 2018-05-30 07-34-56

## Severity

s4 every customer is affected, but it's only a layout issue.

### PR DESCRIPTION
**Pull request by oeoeaio**
#### What? Why?

Closes #2347

#### What should we test?

- [x] Shop tabs should be on one line

#### Release notes

#2347 has not been released, so we don't need separate release notes for this

### CODE REVIEW

**Comment by myriamboure** [comment]
@sauloperez can we quickly review, stage and test that for the release? Because @mkllnk accidentaly merged something that introduce a very strange display on the shopfront (the tabs appear on two lines) so this PR is supposed to fix it. I would like to avoid users disturbance/regression on their shop appearance... and it's quick to test. If you stage it to Katuma I can test tonight or this week-end.

**Comment by sauloperez** [comment]
staged on https://staging.katuma.org/

**Comment by myriamboure** [comment]
Ok tabs are back on one line on computer, and looks ok as well on mobiles actually:
screenshot from 2018-06-04 16-14-59
img_9044
Ready to go!

**Comment by myriamboure** [comment]
@sauloperez it seems you staged without approving on code side so check if code is ok before merging.

**Pull request merged**
