### PR TITLE
Remove duplicated keys in en yml

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

when I wanted to update some keys on en.yml, I noticed that there are some duplicated keys.
I tried to clean it on this PR

#### What should we test?

Not sure how to test it.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by abdellani** [comment]
the key `producers:` is also duplicated.
https://github.com/openfoodfoundation/openfoodnetwork/blob/967f94e15a81e4326d698d9d9deff20cf6ec5aa8/config/locales/en.yml#L400
https://github.com/openfoodfoundation/openfoodnetwork/blob/967f94e15a81e4326d698d9d9deff20cf6ec5aa8/config/locales/en.yml#L3611-L3614

I think that the first one should be removed.

**Review by mkllnk — APPROVED** [review]
Great effort. This is related to:

* #9500

The mentioned yaml-lint in the issue only verifies that the yaml file is correct but it doesn't recognise duplicate keys. There's a python tool called `yamllint` that does much more:

* https://github.com/Pryz/yaml-lint

It found another duplicate key:

```
  3611:3    error    duplication of key "producers" in mapping  (key-duplicates)
```

I'm wondering if we should address all found issues and use that tool on CI to verify that nobody accidentally adds a duplicate key again.

**Comment by mkllnk** [comment]
All tests pass and your edits align with the output of yamllint. So I'm pretty confident that this is all correct and I'll merge it.

**Comment by drummer83** [comment]
@abdellani @mkllnk
Just to be sure: Some languages use different translations of the same English word, depending on the context.
This PR is only removing duplicates which were used for the exact same position in the app, correct? So the translations depending on context are not changed, right?

**Comment by mkllnk** [comment]
That's right, The resulting translations won't change at all. And the other languages generated by Transifex won't change either because the duplicate keys have already been ignored by Transifex. The problem with those duplicates was that the first one would be ignored while the second one would win and override the first. So developers would think that some content was in the translation file but it never reached Transifex or the app.

**Pull request merged**
