### PR TITLE
[Rails 4.1] Merge Rails 4.1 branch into master

### LINKED ISSUE #5386: [Rails 4.1] Upgrade OFN to Rails 4.1
## What is the problem we are solving 
This issue represents the effort to upgrade rails to 4.1.

This is related to #4826 but not necessarily blocked by it as we can now upgrade rails without upgrading spree.

This discourse thread contains more info about this:
https://community.openfoodnetwork.org/t/bye-bye-spree-or-spree-v2-1-and-beyond/1598/30

I read the rails 4.1 upgrade guide and I estimated this as 3 weeks of dev time. I wonder if the dual boot is worth the effort if these upgrades without spree look so easy for an app like OFN.
Would be good to get a second dev to do this  estimate :-)

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5386 
This will merge the rails-4-1 branch into master. I think it's useful to have this open already so we can look at the code (look at how small this PR is!!) and discuss potential issues.

#### What should we test?
This will need careful testing already being discussed.

#### Release notes
Changelog Category: Technical changes
Upgraded to rails 4.1

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Am I right in thinking our Capybara and Selenium dependencies are pinned at an outdated version because of our Rails version? Maybe we can try some version bumps here...

**Comment by luisramos0** [comment]
capybara is waiting for raills 4.2 see Gemfile:
gem 'capybara', '>= 2.18.0' # 3.0 requires rack 1.6 that only works with Rails 4.2

but maybe selenium can already go up. I think dependabot will do some of that work when we merge rails 4.1 into master.

**Comment by Matt-Yorkley** [comment]
The build is green after merging those two small PRs :heavy_check_mark:

**Comment by luisramos0** [comment]
We have decided to block this and test this with rails 4.2.
So this PR will not be tested independently. This will be tested as part of #6301

**Comment by Matt-Yorkley** [comment]
FYI I just rebased this branch on `master`

**Comment by luisramos0** [comment]
Thanks!

**Pull request merged**
