### PR TITLE
Add review & edit sub keys

### LINKED ISSUE #3688: [Subs] Missing translation on edit a sub page
## Steps to Reproduce

1. Log in with a profile that can access to subscription
2. Click on "edit" a subscription
3. You will see two things untranslated: the title of the page and the review button

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v1.29
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Windows 10

### PR DESCRIPTION
**Pull request by HugsDaniel**
#### What? Why?

Closes #3688 and #3743

Added `admin.subscriptions.edit` I18n keys in en.yml.
Fix and move to js namespace some translations in new schedule modal and in new customer modal.

#### What should we test?
In subscriptions#edit page, the title should be `Edit Subscription`.
See #3743 for details about schedules and customers.

#### Release notes
Changelog Category: Fixed
Fixed missing translations.

### CODE REVIEW

**Comment by sauloperez** [comment]
you came back!

**Comment by sigmundpetersen** [comment]
@luisramos0 do you think this is not Test Ready then? Should we move it back?

**Comment by luisramos0** [comment]
yeah, sorry, I moved to test ready.
I think it's not test ready, it may just be waste of time doing it in v1 as the keys may be required in a diff location in v2.

**Comment by luisramos0** [comment]
I checked and 3255 was deployed in uk staging just now. I am using stg uk to take care of 3255.

**Comment by luisramos0** [comment]
The review key was already put in as part of this PR: #3720 so I removed it from this PR.
This PR will fix the Edit title in #3688 

I extended the scope of this PR to fix #3743 as well.
Ready for review.

Staging FR is actually good to test these translations because the default language is FR, if user changes to English everything should appear in English. This can be tested before transifex is involved.

**Comment by RachL** [comment]
Everything is looking good! Ready to go!

image

image

image

**Pull request merged**
