### PR TITLE
Switch to using the Spree GA tracker code

### PR DESCRIPTION
**Pull request by pmackay**
Fix for #938. Would be good to test this on a staging server and verify analytics are being tracked. Would require setting up a UA code for staging as well (but with Spree trackers, that can now be done!)

Copy created with `uk/` prefix.

### CODE REVIEW

**Comment by pmackay** [comment]
This has been tested on UK staging and works for basic page views.

**Comment by daniellemoorhead** [comment]
Hiya @pmackay I'm still a bit concerned about this solution - can you tell us what it will do to the way we access Analytics now? Will there be any change? Given it's the site admins that will be using GA I want to make sure that included in this issue/PR is a description of how it changes the current way we do things (if at all). Are you able to provide this?

**Comment by pmackay** [comment]
I believe it will work the same, tracking basic page views. Once this is merged, you will have to enter the Analytics `UA` number into the "Trackers" config in Spree admin. I did that for UK staging and could see realtime page views being recorded in GA. You can then have a different `UA` number for staging and production if that's of interest (not possible before).

Does that help? If Aus is ok for this to be merged, I'll update the deployment docs with some notes on configuring GA.

**Comment by pmackay** [comment]
Also note that it has a commerce analytics tracking support, feeding into the GA commerce support specifically as well. I've not tested that, but its Spree code so would assume is likely to be ok.

**Comment by daniellemoorhead** [comment]
So what will this mean for the existing data we have, will it change, will there be a blip in the recording? Will it reset?

**Comment by pmackay** [comment]
There would be a slight blip between when the code is updated to the time you add the setting in Spree admin. Existing data should not change I think. I havent tested this, but there is no reason any data should get lost. And it should continue adding data to the same profile if the same `UA` code is used.

**Comment by daniellemoorhead** [comment]
So, this means that we'll be able to look at data on a month on month or year on year basis, we won't have to restart from scratch with this kind of trending data view? If it doesn't impact on that, then go right ahead and merge it :)

**Comment by pmackay** [comment]
Isnt it usually Rohan, Maikel or Rob who merge stuff?

**Comment by daniellemoorhead** [comment]
All of them, but given @mkllnk has been across this it should probably be him.

**Comment by daniellemoorhead** [comment]
Have asked @RohanM to have a look at this in terms of solution, if all is well then we'll push it as part of release 1.8 next week.

**Pull request merged**
