### PR TITLE
Sync subscriptions on newly-cloned order cycles

### LINKED ISSUE #8890: Subscriptions orders are not reliably created when order cycles with schedules open
## Description

The hub manager for Southern Harvest Association Community Stall (#2565) reported a recurring issue with the subscriptions not activating when an order cycle is opened.

## Expected Behavior

This hub has multiple order cycles and each order cycle often has more than one schedule attached to it.

When the manager creates an order cycle with attached schedules, the opening of the order cycle should automatically trigger the creation of subscription orders linked to those schedules.

## Actual Behaviour

The manager created the following order cycles with [Tuesday bakery fortnightly 2 ]()and[ ]()[Tuesday bakery]() schedules attached. 

Subscribers for [Tuesday bakery fortnightly 2]()
[aliceandbentaylor@gmail.com](mailto:aliceandbentaylor@gmail.com)

Subscribers for [Tuesday bakery]()
[ccfoster0203@gmail.com](mailto:ccfoster0203@gmail.com)
[paulajsutton@gmail.com](mailto:paulajsutton@gmail.com)

This should have created triplicates of the same orders for the three subscribers above but instead:

- order cycle at 7.42am 14 Feb called 'Tuesday bakery orders, Summer week 12' **(Order cycle ID #11547) did not trigger** the automatic creation of orders
- order cycle at 4.07pm 14 Feb called 'COPY OF Tuesday bakery orders, Summer week 12' **(Order cycle ID #11554) did not trigger** the automatic creation of orders
- order cycle at 4.18pm 14 Feb called 'COPY OF COPY OF Tuesday bakery orders, Summer week 12' **(Order cycle ID #11555) triggered** the automatic creation of the orders below

Order [R512835542](https://openfoodnetwork.org.au/admin/orders/R512835542/edit) was created for [aliceandbentaylor@gmail.com](mailto:aliceandbentaylor@gmail.com) on February 14, 2022 4:21 PM matching the customer's subscription.

Order [R668563271](https://openfoodnetwork.org.au/admin/orders/R668563271/edit) was created for [ccfoster0203@gmail.com](mailto:ccfoster0203@gmail.com) on February 14, 2022 4:21 PM matching the customer's subscription.

Order [R707406134](https://openfoodnetwork.org.au/admin/orders/R707406134/edit) was created for [paulajsutton@gmail.com](mailto:paulajsutton@gmail.com) on February 14, 2022 4:21 PM matching the customer's subscription.

All the products selected in incoming and outgoing products were the same for all three order cycles.

The same scenario happened the previous week for the same schedules where the creation of the orders were finally triggered by the 3rd/triplicate order cycle  **'COPY OF COPY OF Tuesday bakery orders, Summer week 11' (Order cycle ID #11492)**.

During the previous week the manager also created an order cycle that opened at 6.48am and closed at 4pm Thu 9 Feb called **'Thursday bakery orders, Summer week 11' (Order cycle ID #11510)** with [Thursday bakery, ]()[Thursday bakery fortnightly]() schedules attached.

Subscribers for [Thursday bakery]()
[andypbray@gmail.com](mailto:andypbray@gmail.com)
[adencotterill@gmail.com](mailto:adencotterill@gmail.com)

Subscribers for [Thursday bakery fortnightly]()
[philippa.may.thomson@gmail.com](mailto:philippa.may.thomson@gmail.com)

No subscription orders were created for this order cycle

Pattern that is emerging:
Subscription orders for

- [Tuesday bakery]() and [Tuesday bakery fortnightly 2]() schedules only seem to get placed when the 3rd copy of the order cycle is created (as indicated in the name 'COPY OF COPY OF...'
- [Tuesday bakery fortnightly]() schedules - no subscriptions for this schedule yet
- [Thursday bakery ]()and[ ]()[Thursday bakery fortnightly]() schedules are not being created after one order cycle was created - consecutive order cycles were not created to see if the next ones would trigger the automation

## Workaround

The customer's workaround has been to duplicate and triplicate the order cycles with the relevant schedules until the orders are created. But this workaround is untenable even now.

## Severity

bug-s1: a critical feature is broken: subscription orders are not being created which impacts the hub's income and creates a messy workload for the hub of duplicating order cycles and checking orders.

## Your Environment

I will have to ask the hub manager about these and get back to you.

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #8890 (hopefully)

Syncs subscriptions after cloning an order cycle with schedules.

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley , thanks for the heads-up for the early test.

Something to note: staging this PR will include #8828, so the tests below will not exactly recreate #8890 (from production, without #8828), in which the users manually added the schedule to the OC, at some point. However, the issue also mentions cloning... so there is some focus on cloning below.

I've tried to break this into peaces.

**Test case 1)** Creating an OC / schedule / subscription **from scratch** - our happy path

The steps were - on this order:
i) creating an OC, to open on a future time
ii) creating a schedule / adding it to the OC
iii) creating a subscription
iv) running the subscription job
 
Peek 2022-02-16 11-29

The takeaway: We can see that although the OC is not open yet, **a proxy order is created** - displayed as `pending` state in the UI and seen on proxy_orders table in the DB. Running the subscription job creates the "real" order (an order_id is added in the `proxy_orders` table), and the state changes to `cart` :+1: 

v) running the confirmation job
Peek 2022-02-16 11-31

Take away: The proxy order UI-table for that subscription becomes empty, as the order was processed. Emails get sent, the "real" order gets confirmed and completed :+1: 

**Test case 2)** Cloning an OC (from the OC above)

i) cloning the OC, we can see that the schedule was carried (this can be verified in the DBs, not show below)

Peek 2022-02-16 11-33

ii) we can see that the UI-table is empty; also the DB table proxy_orders does not display any order as in the previous test case.
iii) running the subscription jobs does not change this, no order is placed:

Peek 2022-02-16 11-34

The takeaway: it seems to me, that the breaking point is the creation of the proxy order in the moment in which the schedule tag is added:
-> cloning is not creating a proxy order
-> manually creating order cycles is (on the order in step 1)

To be tested:
Test case 3) Repeating test case 1), in a different order, for example:
i) creating a subscription
ii) creating the order cycle
iii) adding the schedule to the order cycle

**Comment by filipefurtad0** [comment]
Ha! I think I've got it. Some additional and relevant test cases:

Test cases 3.a and 3.b)
i) creating a subscription
ii) creating the order cycle - to open in a future time
iii.a) adding the schedule to the order cycle - when editing the OC
iii.b) adding the schedule to the order cycle - when editing schedules (i.e., on the `/order_cycles` page)

Both variations created the proxy order correctly; running the subs jobs was then fine :+1: 

However....
Test cases 4)
i) creating a subscription
ii) creating a **closed** order cycle - open times are in the past
iii) adding the schedule to the order cycle
iv) setting the order cycle to open in a future time

This will fail to create a proxy order!

**Comment by Matt-Yorkley** [comment]
Awesome investigating :pray:

Okay, so when it comes to cloning OCs, I'm guessing in most cases users will be cloning an OC after it's finished, so it'll be closed when they clone it? And then they'll set the dates they want _after_ cloning?

**Comment by filipefurtad0** [comment]
> when it comes to cloning OCs, I'm guessing in most cases users will be cloning an OC after it's finished, so it'll be closed when they clone it? And then they'll set the dates they want after cloning?

That's my understanding as well :100: 

I _think_ it might relate to cloning as well, as cloned OCs are always created **with empty dates**... I guess the proxy orders are  created correctly **only** when the order cycle is set to open in the future. This would explain why #8828 creates OCs which never run the subscriptions: it does passe the schedule correctly, but at the moment of creation the dates are empty...

**Comment by Matt-Yorkley** [comment]
Okay I've pushed some updates to the draft. I'll take a look at writing some test coverage. Could you try re-testing those failing edge cases with the updated version @filipefurtad0? :pray:

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley , I've re-staged and re-tested:

**Test-case 4**
i) creating a subscription
ii) creating a closed order cycle (marked gray) - open times are in the past / or with empty dates (no color marking)
iii) adding the schedule to the order cycle
iv) setting the order cycle to open in a future time

Creating the order and running the subscription is still failing, in this case (below we see no order is created):
Peek 2022-02-16 16-07



**Test-case 5**
i) creating a subscription
ii) creating an order cycle to open in a future time (marked yellow)
iii) adding the schedule to the order cycle
iv) setting the order cycle to open in a future time

This creates the order and allows running the subscription.

Also relevant:
**Test-case 6**
i) creating a subscription
ii) creating an open order cycle (marked green)
iii) adding the schedule to the order cycle
iv) setting the order cycle to open in a future time

This creates the order and allows running the subscription :+1: 

Peek 2022-02-16 16-01

Thinking out loud:
I think the tricky bit is that this actually is the correct behavior -> Proxy orders should not be created in the moment schedules are added to closed order cycles. However, they should be created as soon as the dates are updated, either to be open in a future time or open in the present (test case 4).

**Comment by Matt-Yorkley** [comment]
Hmmm... but in that **test case 4** did you hit save after setting the dates and before checking the DB? I couldn't see that in the gif.

**Comment by filipefurtad0** [comment]
Alright! Major improvement :muscle: 

Taking test case (4) above:

i) creating a subscription
ii) creating a closed order cycle (marked gray) - open times are in the past / or with empty dates (no color marking)
iii) adding the schedule to the order cycle
iv) setting the order cycle to open in a future time

We can consider some variations on the transition between steps, ii) and iv). These are working:

starting with a **closed OC**
i) schedule + OC closed (gray) `-> change to ->` schedule + OC open (green) = order is created :tada: 
ii) schedule + OC closed (gray) `-> change to ->` schedule + OC opening in the future (yellow) = order is created :tada: 

These transitions are not working yet:

starting with an **OC with no values on dates** -> these relate to cloning
iii) schedule + OC w/ no dates (white) `-> change to ->` schedule + OC open (green) = order is not created 
iv) schedule + OC w/ no dates (white) `-> change to ->` schedule + OC opening in the future (yellow) = order is not created

However, if you turn iii) or iv) into a closed order cycle (cases i or ii) and then open them it creates the order consistently. This sums it up - hopefully it's understandable:
Peek 2022-02-16 20-11

**Comment by Matt-Yorkley** [comment]
This code is not nice. I'm getting strong Augean Stables vibes here. 

Aaaanyway... I've added more test coverage for that last case and fixed it.

**Review by jibees — APPROVED** [review]
This looks like complicated. 
But looks good to me... 👌

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley 

I can confirm this fixes the two missing test cases :+1:
(repeating here for clarity)

So, after this PR (and adding to the test cases i) and ii) on the previous comment):

- starting with an OC with no values on dates -> these relate to **cloning**

iii) schedule + OC w/ no dates (white) -> change to -> schedule + OC open (green) = order is now created :tada: 
Peek 2022-02-17 12-11

iv) schedule + OC w/ no dates (white) -> change to -> schedule + OC opening in the future (yellow) = order is now created :tada: 
Peek 2022-02-17 12-12

So I'd say with this new code there is no need to revert #8828, as this makes subscriptions work as well, on cloned OCs :+1: 


Something which became apparent from all this testing and fixing:

Let's say:
- a subscription is created with items from order cycle A
- time goes by and in the meantime OC A closes
- user does not clones OC A but creates OC B
- while setting up OC B the user does not add items in the incoming / outgoing sections
- user adds the schedule to OC B

In this case, and despite the fact that there are no items on OC B the subscription _will_ run, and create orders.

I'm pretty sure this is not introduced here, I'll need to double check.

**Comment by Matt-Yorkley** [comment]
Yeah this stuff around schedules and subscriptions could do with a serious tidy-up at some point.

**Pull request merged**
