### PR TITLE
[BUU] Handle corrupt data and troubleshooting

### PR DESCRIPTION
**Pull request by dacook**
### What? Why?
A couple of similar errors have come up this week
- Hopefully this will help with https://github.com/openfoodfoundation/openfoodnetwork/issues/12682

1. A small code change that _might_ help avoid the error on **hu_prod**.
2. On **fr_prod**, I found some corrupt data was causing an error. This is now handled gracefully. Well, more gracefully than before. It will appear as below with the first option in the list selected:

Screenshot 2024-07-18 at 12 01 35 pm

#### Staging
- Updating units on any product
#### fr_prod
- Updating units for producer 5658: https://coopcircuits.fr/admin/products?producer_id=5658 (this page currently is error 500)

### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by dacook** [comment]
Discovered a flaky (unrelated) spec:
https://github.com/dacook/openfoodnetwork/actions/runs/9984099251/job/27592766383

Should be an easy fix 

 1) As an enterprise user, I can manage my products listing with several variants displays an on hand count in a span for each product

     **Failure/Error:** expect(page).not_to have_content "20" # does not display the total stock
       expected not to find text "**20**" 
       in "Logged in as : olen@harveydenesik.biz Account Logout Store Dashboard Products Reports Enterprises Products Inventory Import Bulk Edit Products New Product Categories All categories Brand Ruby on Rails All categories Search 2 products found for your search criteria. Showing 1 to 2. Show 25 per page 50 per page 100 per page 15 per page 15 per page Columns Name ▲ SKU Unit scale Unit Price On Hand Producer Category Tax Category Inherits Properties? Actions Weight (kg) Weight (T) Volume (mL) Volume (L) Volume (kL) Items Weight (g) Weight (g) YES 1g On demand Enterprise **20**3 Enterprise **20**3 Brand Ruby on Rails Ruby on Rails None TaxCategory - 5 None New variant Weight (kg) Weight (T) Volume (mL) Volume (L) Volume (kL) Items Weight (g) Weight (g) YES 1g 16 Enterprise **20**3 Enterprise **20**3 Ruby on Rails Brand Brand None TaxCategory - 5 None 1g 4 Enterprise **20**3 Enterprise **20**3 Ruby on Rails Brand Brand None TaxCategory - 5 None New variant"
     
 `./spec/system/admin/products_v3/index_spec.rb:80:in `block (4 levels) in <top (required)>'`

**Review by chahmedejaz — APPROVED** [review]
Looks Good to me. I think it's worth trying it out, 🤞

**Comment by filipefurtad0** [comment]
Hey @dacook,

This is a though one to test, as I could not reproduce it either. So, I've created a list of products and changed their unit from:
- Kg to g
- g to kg
- kg to L
- Item to Kg
- Kg to Item

Spotted no issues. So I'd say we're good to merge and, as you point out, await for feedback from production (FR and HU).

**Comment by filipefurtad0** [comment]
Releasing this one as feature-toggled, as it seems to relate only to BUU (as described on [the issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/12682#issue-2412930534)).

**Comment by dacook** [comment]
## fr_prod
I just checked on fr_prod, and it loads without error now ✅. The  Unit Scale field is not marked as changed, so I guess the hub have since updated it anyway.

https://coopcircuits.fr/admin/products?producer_id=5658

## hu_prod
The full fix for this is included in next week's release.

**Pull request merged**
