### PR TITLE
Remove js specs

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

This removes the Javascript specs from the Github build. We will keep them in the Semaphore build and remove everything else from the Semaphore build. 

#### What should we test?

Fast green build

#### Release notes

Updated build configuration

Changelog Category: Technical changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]

**Comment by sauloperez** [comment]
And why is that?

**Comment by Matt-Yorkley** [comment]
> Didn't we want to stick to a single CI service?

Yeah I think it makes more sense to run all the specs with Github CI, and just use Semaphore for deploying to staging...

**Comment by andrewpbrett** [comment]
That works for me, I'll close this and then just... update Semaphore to have a completely empty task?

**Comment by andrewpbrett** [comment]
Okay, Semaphore is now updated to just run `echo "deploy away!"`, taking about 20 seconds.

**Pull request closed without merging**
