### PR TITLE
Don't show credit owed when = 0 in order confirmation

### PR DESCRIPTION
**Pull request by drummer83**
#### What? Why?

- This relates to #11114.

If an order is paid with the exact amount, then there is no credit owed and no balance due. In this case it is not required to show the credit owed = 0.

#### What should we test?

- Visit /orders/ORDER_NUMBER page from the user account.
- If the order has a balance due, this should be indicated in red (as before).
- If the order has a credit owed, this should be indicated in black (as before).
- If the order has neither, this should not be indicated at all (this is new).

Before:
image

After:
image

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Very good, thank you. I added a little simplification to keep the code easier to read.

**Review by dacook — APPROVED** [review]
Go team!

**Comment by filipefurtad0** [comment]
Hey @drummer83,

Thanks for this improvement, and for documenting the issue nicely :muscle: 

Following your proposed testing steps:

i) If the order has a balance due, this should be indicated in red (as before):

image

ii) If the order has a credit owed, this should be indicated in black (as before):

image

iii) If the order has neither, this should not be indicated at all (this is new).

image

Awesome - good to go, merging :tada: 

PS: It should be fairly straightforward to add some some assertions to check for these and the changes introduced on https://github.com/openfoodfoundation/openfoodnetwork/pull/11114, within our test suite, I'll look for the relevant file and do so.

**Comment by filipefurtad0** [comment]
Another note, for some reason, this last build run took unusually long :eyes: 

image

Let's see what happens after merging...

**Pull request merged**
