### PR TITLE
Uncomment flaky spec on variant_overrides_spec.rb

### LINKED ISSUE #4957: [Flaky spec] Fix features/admin/variant_overrides_specs currently commented out (2 specs)
spec/features/admin/variant_overrides_spec.rb:193
spec/features/admin/variant_overrides_spec.rb:210

This spec is not failing all the time #flaky

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #4957

#### What should we test?
Green build 🟢 

#### Release notes
Add tests around variant overrides.

Changelog Category: Technical changes

### CODE REVIEW

**Comment by sauloperez** [comment]
I just re-run the build to make sure they are not flaky anymore.

**Comment by jibees** [comment]
> I just re-run the build to make sure they are not flaky anymore.

@sauloperez And it's all green ;)

**Comment by sauloperez** [comment]
let's see once more :joy:

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by sauloperez** [comment]
```
Finished in 12 minutes 25 seconds (files took 10.12 seconds to load)
162 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/features/admin/variant_overrides_spec.rb:431 
```

sorry :sweat: as expected no magic happened and we need to work on its reliability.

**Comment by jibees** [comment]
@sauloperez 
I think if it's line #431 that failed it's more about #6192

Here modified lines are: 195 & 212

**Review by sauloperez — APPROVED** [review]

**Pull request merged**
