### PR TITLE
[Bye bye spree] Bring classes related to users to OFN

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?
Continues #4826
Here we move the following files to OFN:
- core/app/models/spree/legacy_user.rb NO COPY - we need to replace usages by Spree::User
- core/app/models/spree/role.rb COPY
- core/config/initializers/user_class_extensions.rb  COPY and remove reference to dead Spree::Core::UserBanners

No code changes were made, here we only move the code from spree, adapt the specs if needed and improve the code a little with rubocop and transpec.

#### What should we test?
TODO

#### Release notes
Changelog Category: Changed
Brought code needed in OFN from Spree so that we can make OFN independent of Spree.

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
This one is pretty simple so I'm moving it to Test Ready.

**Comment by filipefurtad0** [comment]
Hi @luisramos0 ,

Maybe here it would be necessary to manually check that the rights from different roles work as before? I checked that:

- superadmin can edit/has access to all enterprises - OK
- enterprise owners can only access own entnerprise - OK
- enterprise owners don't have superadmin rights, for example, can't access /admin/users - "Authorisation Failure" is shown - OK
- customers cannot edit enterprises - "Authorisation Failure" is shown - OK 

I smoke tested around the examples on `user_spec.rb`. For example:

- for a given user, I've set the enterprise ownership limit to 1, and attempted to make him own another enterprise, other than the previously own. This failed, as expected, with the error: 

image

- created a new user. Verified confirmation and welcome emails.

I'm moving to ready to go, as all seems good here. Is there anything particular you feel that should be tested for this PR?

**Comment by luisramos0** [comment]
Hi Filipe, I am sorry I forgot to get that TODO done!
Thanks for being proactive. I think we are good here with the tests you have decided to do, well done!

**Comment by filipefurtad0** [comment]
No worries Luis!
I'm happy the tests seemed appropriate :+1:

**Comment by filipefurtad0** [comment]
Hey @luisramos0 ,
I've spotted this today #6038 and I think this relates to this PR.

**Pull request merged**
