### PR TITLE
Allow docker-compose configuration customization

### PR DESCRIPTION
**Pull request by santakadev**
#### What? Why?

Allow developers to customize *docker-compose* configuration by using an unversioned `docker-compose.override.yml` file.

That way, we can expose for example the DB port without changing the configuration in the versioned `docker-compose.yml` file.

```yaml
# docker-compose.override.yml

version: '3'

services:
  db:
    ports:
    - 5432:5432
```

### CODE REVIEW

**Comment by jhsu802701** [comment]
Is there a reason that PostgreSQL does not have an exposed port?

**Review by luisramos0 — COMMENTED** [review]
I dont think we should encorage that unless there's a good reason to do so.
What config do you want to use that should not go to the default config file? I would prefer a PR to change the standard config file.

**Comment by santakadev** [comment]
Normally I add `docker-compose.override.yml` to .gitignore to allow customization, like adapting the port numbers to avoid collisions, but being honest my current need is to open PostgreSQL port. :sweat_smile:

I created https://github.com/openfoodfoundation/openfoodnetwork/pull/6200 to solve that need.

About this PR, I don't have a strong opinion, so we can wait to see if there is a need for customization in the future.

**Comment by Matt-Yorkley** [comment]
Hi @santakadev, I don't use the Docker setup myself, but the ability to work around port collisions locally without changing the repo's contents seems pretty reasonable. Do you still need #6217 if #6200 is merged? Or do you want both? What's the use-case for opening port 5432 in dev?

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by jhsu802701** [comment]
> 
> Out of interest, what's the use-case for opening port 5432 in dev? You can't just use `psql`?

Opening up a port for PostgreSQL makes it easy to use Pgweb or something similar to view the database.  I never got the hang of psql.  That said, people who prefer the psql way will still be free to use it.

**Comment by sauloperez** [comment]
After #6217 being merged, I don't see the need for this one. Do you mind if we close it @santakadev ?

**Pull request closed without merging**
