### PR TITLE
[Breaking] Replace Paperclip with Active Storage

### LINKED ISSUE #6347: Migrate Paperclip to ActiveStorage
### What we should change and why (this is tech debt)
Our file attachments manager gem Paperclip (upload files to S3 for example) is deprecated in favor of ActiveStorage. ActiveStorage comes with rails 5. After we are on rails 5, we can migrate to ActiveStorage.

We think this will be an easy task.

### Context
Paperclip upgrades and rails upgrades

### Impact and timeline
This will move us away from deprecated dependencies.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #6347. This completes the migration from Paperclip to Active Storage.

#### What should we test?

- All images that displayed before should still display.
- Upload new images and they should still display.
- Also check logos in emails.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

:warning: This will break images if you haven't run the migration tasks beforehand:
```
bundle exec rake from_paperclip_to_active_storage:copy_content_config  # Associate ContentConfig to ActiveStorage blobs
bundle exec rake from_paperclip_to_active_storage:migrate              # Copy data to Active Storage tables referencing Paperclip files
```

We should increase the minor version number in this release.

#### Dependencies

Before merging and deploying this PR, we need to migrate all images on all servers. I think that @filipefurtad0 ran the migration scripts on all staging servers already. Let's do the production servers. I'm logging in via SSH and then run:

```
cd ~/apps/openfoodnetwork/current &&\
 bundle exec rake from_paperclip_to_active_storage:copy_content_config &&\
 screen -d -m time bundle exec rake from_paperclip_to_active_storage:migrate
```

The `screen` commands starts the long-running task in a separate terminal which runs in the background and we can call up at any time. I started that on all servers and will check later if they completed and what the output is.

- [x] au
- [x] ca
- [x] ie
- [x] uk
- [x] us
- [x] es
- [x] fr
- [x] de
- [x] be
- [x] hu

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

After the migration task was re-ran and finished in staging-AU, [as mentioned here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9119#issuecomment-1113160398), I've staged #9126 the PR in both staging servers.

It seems that:
- all images break in staging-UK (left)
- some images break in staging-AU (I think those which were uploaded quite a while ago)

image

On staging-UK, the `/products` page is not loading for this particular hub:

image

The page does load for more recent hubs, but still with broken images:

image

Image upload seems to work fine, on both servers:

image

So, I think we need a second look on this one... Do let me know if you need any additional or specific feedback.

**Comment by mkllnk** [comment]
> all images break in staging-UK

That may actually be because the config on file says it's using cloud but the config in the database uses the local disk. If we want to test the local storage properly, we should remove the S3 config from `.env.staging`. I'll look into this.

**Comment by mkllnk** [comment]
I moved this back to In Dev and will investigate those errors.

**Comment by mkllnk** [comment]
> That may actually be because the config on file says it's using cloud but the config in the database uses the local disk. If we want to test the local storage properly, we should remove the S3 config from .env.staging. I'll look into this.

It looks like the config has been changed on the server already. The secrets define s3-bucket but the server doesn't have it. :shrug:

**Comment by mkllnk** [comment]
I had a look why some images are not displaying in uk-staging and au-staging. I found that the checksum wasn't computed correctly in the migration task for cloud storage. And local storage was tripped up by our deployment scripts. We create a new app folder for each release and then link to persisting files like file uploads. Active Storage uses a new directory and we were not linking to that. Instead, a new deployment would come with an empty storage folder again and all images were missing on uk-staging. I'm glad that we found that now. I will need to update ofn-install for that.

**Review by jibees — APPROVED** [review]
Very clear, nice _git history documentation_: congrats! 🎊 💪

**Comment by mkllnk** [comment]
Hm, I'm just doing some more testing and it looks like there are still some issues.

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,
Just to confirm on what/how to test this PR:

1) upload an image file larger that 20MB
2) run the migration tasks for the staging servers
3) stage this PR and check the image is still there

Is this a valid test?
Thanks :pray:

**Comment by mkllnk** [comment]
@filipefurtad0 Sorry for not adding any more detail. We don't need to test for these huge files because they are rare, should maybe not be supported anyway and we would need to deploy an old version of OFN before any of the Active Storage work got merged to upload such a big image. If you uploaded a big image now, it's already duplicated in Active Storage and the checksum should already be correct.

Hm, that said, the migration would still run and re-calculate the checksum. So maybe yes, doing your test won't hurt. :wink: 

The main part of the test is though to make sure that all images are still displaying everywhere because the code to display the images changed. So rendering an image in an email is different to rendering an image in the shop and hopefully they all work.

**Comment by filipefurtad0** [comment]
Alright! I think we're good.

As usual, two staging-servers were used for this, -UK and -AU.

**1) Before staging**
- I've uploaded the "staring dog" pic, a BMP image over 50MB. It loaded well, displayed correctly in the product list and in the shopfront
- checked other images, like logos, other product images
- placed orders and checked the logo image on emails

2) Then, the **PR was staged**, and
- verified the large image still displays correctly:
image
- checked other images
- placed orders and checked Emails are still displaying the shop logos
- uploaded new images, to check if the upload function still works -> all good :+1: 

I think we're ready to go for production :muscle:

**Comment by mkllnk** [comment]
Deployed to all managed instances! Looking good so far.

**Pull request merged**
