### PR TITLE
[Rails 6.1] Upgrade thor

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

select2-rails upgrade is blocking the upgrade to rails 6.1.
I tried relaxing the requirement for thor ≳ 14 in select2-rails so we could move thor to v1 and that would enable railities 6.1.
Looks like its workign as the green is build.

I dont have permissions to create the select2-rails repo in ofn, we can then push the branch 349_nothor to it and use it. That will enable the rails 6.1 upgrade.
EDIT: done. Now using modified select2-rails that works with thor v1. 

#### What should we test?
green build.

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
> I dont have permissions to create the select2-rails repo in ofn

Shall I re-add you as an admin? :slightly_smiling_face:

**Comment by luisramos0** [comment]
We need someone to do this "create the select2-rails repo in ofn, we can then push the branch 349_nothor to it and use it."
or make me admin of the repo again :-)

**Comment by Matt-Yorkley** [comment]
You're an admin on the repo again. Welcome back :smile:

**Comment by luisramos0** [comment]
thanks but I am not able to fork this repo https://github.com/argerim/select2-rails into ofn.
can you pls make the fork, should be a single click, maybe I'll be able to move the branch over afterwards.

**Comment by andrewpbrett** [comment]
It looks like I also don't have permissions to create a fork in the OFF organization - could you add me or Luis @Matt-Yorkley?

**Comment by mkllnk** [comment]
The repo is forked.

**Comment by luisramos0** [comment]
Hi Maikel, thanks for forking the repo.
I dont have permissions to add the branch to the repo.
https://github.com/openfoodfoundation/select2-rails/compare/v3.4.9...luisramos0:v349_with_thor_v1

Basically we need to move/push
https://github.com/luisramos0/select2-rails/tree/v349_with_thor_v1
to
https://github.com/openfoodfoundation/select2-rails

**Comment by mkllnk** [comment]
It looks like someone made you admin now.

**Comment by luisramos0** [comment]
yes, it worked now :-)

**Review by Matt-Yorkley — APPROVED** [review]

**Review by andrewpbrett — APPROVED** [review]

**Pull request merged**
