### PR TITLE
Introduce a filter results button on the BOM page

### LINKED ISSUE #10017: Introduce a "Filter results" button on the BOM page
## Description

**- As a:** enterprise user or super admin
**- On page:** `admin/orders/bulk_management`
**- I want to be able to do:** 

Currently each time you change a filter, the content of the page reloads. This can generate a lot of uneccessary request and is not consistent on what we have on the other pages.

The proposal is to mimic the behavior of the order list : 

Current BOM page : 

image

What we want to do: 

image

For now, let's keep current behavior of showing the past week by default. We only change how we get results : we need to press the button instead of just using filters.

## Acceptance Criteria & Tests

1. Log in as enterprise manager
2. Go to BOM
3. See that you need to use the filter button to get different result than the past week
4.Check the clear filters button is still working

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #10017, #8998

Capture d’écran 2022-12-14 à 10 15 10

For the BO, this PR introduce two buttons "Filters Results" and "Clear Filters" and change a bit the behavior:
 - The orders are still loaded on first page load (with the same date range, ie. 1 week)
 - When changing any input (date range, Producers, ...) it _does not_ reload the orders automatically
 - Clicking on "Filter Results" will refresh the orders list, filtered by the previously modified filters
 - Clicking on "Clear Filters" will reset all the filters with their default values (as it was on first page load)

_tl;dr_: same behavior as `/admin/orders` for the two buttons

**At the same time**, this PR will solve inconsistency between date range selector and order cycle selector. Finally, the proposed solution is to:
 - Put the date range selector _after_ the order cycle selector
 - When changing order cycle value, automatically change the date range selector with the order cycle dates values
 - User can re-change the date range values _after_ choosing an OC.

#### What should we test?
- As an admin, go to `/admin/orders/bulk_management`
- Check that orders are first loaded, according to filters
- Change any filter: check that orders did not change
- Click "Filter Result": orders should change
- Click "Clear Filters": filters should be reset to default values 

_tl;dr_: same behavior as `/admin/orders` ;)

- As an admin, go to `/admin/orders/bulk_management`
- Check that changing an OC modifies the date selector _but_ you can change the date range afterward

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by RachL** [comment]
@jibees would this work prevent/fix bugs like this one? https://github.com/openfoodfoundation/openfoodnetwork/issues/8998

**Comment by jibees** [comment]
> @jibees would this work prevent/fix bugs like this one? #8998

Nop, I don't think so (i've [commented](https://github.com/openfoodfoundation/openfoodnetwork/issues/8998#issuecomment-1346545360) the original issue). Seems not related.

**Comment by jibees** [comment]
@filipefurtad0 @RachL 

I would like this PR solve also the issue #8998. I've made a proposal (and fix, this PR is ready to test) into the PR description, but I copy/paste here:

> - Put the date range selector after the order cycle selector
> - When changing order cycle value, automatically change the date range selector with the order cycle dates values
> - User can re-change the date range values after choosing an OC.


What do you think?

**Comment by RachL** [comment]
Let's try it out :+1:

If it doesn't fix the bug, we can consider removing all links between dates and dropdown? I'm not sure it provides that much value, but perhaps I'm wrong.

**Comment by jibees** [comment]
Should we test before preview? 
Maybe it worth an automatic test as well (wasn't tested actually)? @filipefurtad0 what do you think?

**Comment by filipefurtad0** [comment]
Hey @jibees ,

I had a very quick test on this PR:

> When changing any input (date range, Producers, ...) it does not reload the orders automatically

From my perspective, I think this is a good idea :clap: Perhaps more clicks are required, but I find the results are more concise.

> User can re-change the date range values after choosing an OC.

A quick test showed that it is now possible to cross the OC selector with a date range differing from the opening/closing of the OC: i.e., it closes #8998.

Two minor remarks on usability, no strong opinion:

- it is perhaps "new" not to have the date-range selector in the upper-left corner, like several other pages - but I still think this change makes sense :+1: 
- I wonder if we should have `Shop > Producer > Order Cycle > Date Range` instead. Again, not sure.

> Maybe it worth an automatic test as well (wasn't tested actually)? @filipefurtad0 what do you think?

We do have some coverage [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/d801b6e9700d993881edc36cb75759267cb14d70/spec/system/admin/bulk_order_management_spec.rb#L320), but indeed I'd expect something here to break, after your changes in the UI :eyes: 

In any case, I think we should updated this spec, at least to include the click on the search button.

**Comment by jibees** [comment]
@filipefurtad0 
> We do have some coverage [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/d801b6e9700d993881edc36cb75759267cb14d70/spec/system/admin/bulk_order_management_spec.rb#L320),

Sorry, I wasn't not clear: I was only talking about the _trick_ that link OC selector and date range.

**Comment by RachL** [comment]
@filipefurtad0 can you describe your thinking? 

Spontaneously, a filter on the left seems more accessible to me. And I could be wrong, but perhaps there are a lot of users using BOM with only 1 shop, so they would have a super accessible button, but that they never use...

I'm happy to be wrong about this, but if it's ok for you I'm moving the PR in code review as it is blocking other work and I can always open a new issue as part of Admin v2 to change the order again.

**Comment by filipefurtad0** [comment]
Let's move to code review :+1: 

My thinking was rather about the fact that a hub can have many producers and, for that reason, it could make sense to have this choice made first - and hence, swap positions between the Producer- and Hub dropdowns. But again, really just thinking out loud.

**Comment by filipefurtad0** [comment]
> the trick that link OC selector and date range.

@jibees I've committed a spec update [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10168/files), to cover this feature, separate from this PR - in case it is helpful.

If green and all is good I'll move it to code review or it can be cherry picked.

**Comment by jibees** [comment]
Oh thanks! Maybe I'll cherry pick your commit on top of this branch and see how it goes! thanks a lot!

**Comment by jibees** [comment]
@filipefurtad0 
oopsi. This failed. Back into `In Dev`

**Comment by filipefurtad0** [comment]
This looks strange :eyes: 

If that PR did not help, then I'd suggest to do it the other way around: to remove that last cherry-pick (and move back to code review) and I'll add the spec on top of this, after testing. What do you think @jibees ?

**Comment by jibees** [comment]
> to remove that last cherry-pick (and move back to code review)

yes. Will do that. Thanks @filipefurtad0 !!

**Comment by abdellani** [comment]
@jibees 
The code looks good to me, but I think there is a small problem:
when I select a different OC, the end_date will change to `date of today + 31 days`, is that normal?

https://user-images.githubusercontent.com/16113997/209640092-ed5bdc87-24e1-49de-bea5-5c399c39b649.mp4

**Comment by jibees** [comment]
> when I select a different OC, the end_date will change to date of today + 31 days, is that normal?

When selecting an OC, the date range should change to the OC date range itself. In your case, Multi Shop OC should start on 2022-12-26 and ends on 2023-01-27. 
Capture d’écran 2022-12-27 à 10 04 21

If not this is an issue that we should address.

**Comment by abdellani** [comment]
@jibees 
You're right. So, I guess we don't have any problem now.

**Review by abdellani — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees 

I'm having a second more detailed look at this. Let's compare current (master, left) and future (this PR, right) behaviors:

image

The only minor inconsistency I spot here is the color of the "clear filters" button; was red, now is blue. This might make up for a good contribution to first timers on OFN - I'll make an issue for it.

Going through the test cases again:

- Check that orders are first loaded, according to filters :heavy_check_mark: 
- Change any filter: check that orders did not change :heavy_check_mark: 
- Click "Filter Result": orders should change :heavy_check_mark: 
- Click "Clear Filters": filters should be reset to default values :heavy_check_mark: 

I've checked again if it is possible to combine the different filters, for example, order cycle, and a custom date range (differing from the order cycle start/close dates) :heavy_check_mark: 

This looks great! :muscle:

**Comment by jibees** [comment]
> I spot here is the color of the "clear filters" button; was red, now is blue. 

Yes, I used the same design than `/admin/orders`

Capture d’écran 2022-12-28 à 17 57 53

**Comment by filipefurtad0** [comment]
Ahh - right, so maybe we don't need https://github.com/openfoodfoundation/openfoodnetwork/issues/10212. Ok, closing :+1:

**Comment by RachL** [comment]
@filipefurtad0 yes and with new admin v2 style, secondary button will be white, so this one will transition soon to white FYI

**Comment by jibees** [comment]
(_this is a spoil_)


Capture d’écran 2022-12-29 à 09 49 24

**Comment by filipefurtad0** [comment]
Niiicceee :star_struck:

**Pull request merged**
