### PR TITLE
Use standard ApplicationRecord in task class

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

I accidentally introduced a style violation in 286dade66ff9a22c048416aab9725f09370ffd8d. Well, my additional config meant that we weren't ignoring an old violation any more. I'm resolving that violation here so that `rubocop` runs successfully.

It's best practice to use the ApplicationRecord. But when Rake is loaded, our application is not loaded yet and the ApplicationRecord class wasn't available yet. Requiring within the task solves the problem because Rake loads the Rails environment before executing this task.

I also removed the unused highline loading.

#### What should we test?

- Just deploy. The affected task cleans the database but that's too hard to wait for in staging. If it fails in production we only keep some old data and nothing bad should happen. We should also get notified to rectify it.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
🆗 🙏

**Comment by drummer83** [comment]
Hi @mkllnk,
I staged this PR on staging UK. Staging worked just fine and the page is loading as normal. Is this all to test?

**Note:** I accidentally clicked 'Update with merge commit' instead of 'Update with rebase'. Is this a problem? Is there a way to undo or correct this in case it happens again?

If there is really nothing else to test, this one is ready to go! 🚀

**Comment by mkllnk** [comment]
> Is this all to test?

Yes, all good.

> I accidentally clicked 'Update with merge commit' instead of 'Update with rebase'. Is this a problem? Is there a way to undo or correct this in case it happens again?

Github doesn't show the update button while the branch is in sync with master. But once we merged something else to master, the button should appear again and if you do a rebase then, it should skip the merge commit because it won't be needed any more. Then everything is resolved.

**Comment by mkllnk** [comment]
But I'll merge now anyway to save time. The one additional merge commit is not big deal.

**Pull request merged**
