### PR TITLE
Replace toggle_controller with method inside generic controller

### PR DESCRIPTION
**Pull request by cyrillefr**
- move toggle method from toggle_controller inside toggle_control ctrller
  - change corresponding html attributes in view
  - move corresponding spec in toggle_controller ctrller spec
  - delete now unused toggle controller + spec

#### What? Why?
See #11928 
Does not close the issue, as this is a replacement for the second of the three old/tailored/legacy controllers.

The replaced controller was used only to toggle 2 check boxes that may or may not appear in the details checkout page.

#### What should we test?
- Connect as a customer(ie jane.customer)
- Buy some items
- Go to checkout
- At checkout, under the "Details" tab -> scroll down to the `shipping info` part.
- There are various radio buttons like `Home delivery Fredo's Farm Hub` or `Pickup Fredo's Farm Hub`. By picking one of these options, you should see 2 more options `Shipping address same as billing address?`and `Save as default shipping address`. Clicking on the 1st radio button should toggle these 2 options visible. Clicking on 2nd radio button should toggle these 2 options not visible.

There is a unit test: `app/webpacker/controllers/toggle_control_controller.js` that now tests what was old toggle_controller used to test.

To see it in action via testing:
Toggle `headless` value to `true` in `cuprite_setup.rb`
Insert a `binding.pry` under line: `click_button "Next - Payment method"` (line 92)
`rspec spec/system/consumer/checkout/details_spec.rb:91`
When page is displayed, clicking radio buttons like `A Free Shipping with required address` should toggle 2 check boxes related to the shipping address.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [X] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — CHANGES_REQUESTED** [review]
Nice one.

The testing notes should be for a user point of view. We don't expect our tester to go fiddling with code. 
Could you update the "What should we test?" section to describe which page the tester should be looking at ? We want to make sure we are not introducing any regression !

**Comment by cyrillefr** [comment]
Hello @rioug, I have updated the testing part.

**Review by rioug — APPROVED** [review]
Awesome , thanks !

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @cyrillefr,
Thanks for continuing your work on this!

I staged the PR to our server and here are the test results:

Selecting a pickup method, the checkboxes for delivery address are not shown: :heavy_check_mark: 
image

Selecting a delivery method, the checkboxes are both shown: :heavy_check_mark: 
Activating the 'Shipping address same a billing address' option hides the address input fields: :heavy_check_mark: 
image

Deactivating the 'Shipping address same a billing address' option displays the address input fields: :heavy_check_mark: 
image

Activating the 'Save as default shipping address' option saves the shipping address as default and shows it during next checkout: :heavy_check_mark: 

To my understanding there isn't more to test here. Everything is looking good/as before.

Merging! :partying_face: :rocket: 
Thanks again!

**Pull request merged**
