### PR TITLE
Add translation keys for password messages

### LINKED ISSUE #7182: Missing translation in user account
## Description

When changing email or password, and not typing correctly the password twice, the error message shown is only partially translated

## Steps to Reproduce

1. Login as a shopper, manager, whatever!
2. Go to Profile > Account > Setting
3. Change the email address and hit save
4. See the error message

## Workaround
Learn english

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.6
* Browser name and version: All
* Operating System and version (desktop or mobile): both

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #7182
Replaces #7453 

#### What should we test?

That the new strings appear in the password confirmation dialog.

#### Release notes

Added translations for password confirmation messages

Changelog Category: User facing changes

### CODE REVIEW

**Comment by andrewpbrett** [comment]
I'm going to move this to test ready.

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

Before it was not possible to translate the these strings:
image

After your PR and editing the respective locale file (fr_CA.yml in this case) and tagged these strings with <FR> for visibility):

image

Works! Good to go.

**Comment by drummer83** [comment]
I came across this PR because it is part of the latest release and the strings appear in Transifex as "untranslated".
Now I wonder:
- The words "doesn't match" are still not translatable, are they? I couldn't find them.
- What about the error, if the password is too short (< 6 chars)? It is also not in Transifex.

BUT: The instances managed to translate them both in the screenshots of [#7453](https://github.com/openfoodfoundation/openfoodnetwork/pull/7453) and [#7182](https://github.com/openfoodfoundation/openfoodnetwork/issues/7182). How did they do that?

What am I missing here? Any advice @andrewpbrett, @filipefurtad0?

**Comment by andrewpbrett** [comment]
These error messages are generated by Rails, so I believe things like "doesn't match" and "too short" are already included without having to be translated in Transifex.

**Comment by drummer83** [comment]
Sounds good, but it's not working for Germany. :-)
grafik

Should I open an issue for this?

**Comment by andrewpbrett** [comment]
Ah got it. Yes, let's open an issue please so we can investigate further.

**Pull request merged**
