### PR TITLE
Fix Update button sizing

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

This was broken when [upgrading Foundation](https://github.com/openfoodfoundation/openfoodnetwork/pull/11349). 

I think a single review is fine, then it can be tested and merged sooner.

#### What should we test?
As pictured on above PR^

1. Visit cart edit page
2. Observe the "Update" button appears as expected

- It would be good to check how this appears in another language, if the word is longer.

#### Release notes

It's not worth noting this to instance managers, especially if the fix can be merged before the above PR is released.

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1 or DFC)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @dacook,
Thanks for this quick fix! :zap: 

### Production
image - image - image - image

### Master before the  fix
image - image

### Staging the fix
image - image

## Results
It's definitely better than without the fix, but still not exactly the same as before.
Maybe we should disable line breaks?
Asking @RachL for her opinion on this.

**Comment by dacook** [comment]
Thanks for the testing Konrad. I considered disabling wrapping, but was concerned about the effect it might have for long descriptions. Ultimately I think it depends on what real translations will show. It would be great to have a French opinion :)

**Comment by drummer83** [comment]
@RachL Pinging for your opinion.

Without wrapping and a long text the whole column expands and nothing gets broken. The longest translation we currently have in our code is actually 13 or 14 characters only, so pretty short. I think it's a good solution:
image

**Comment by RachL** [comment]
Yes I agree with @drummer83 let's try it without wrapping then (a bit sad, but we need to be pragmatic).

**Comment by dacook** [comment]
Thanks for confirming Konrad and Rachel. I've updated this, and here are some sample screenshots. I'll merge this for today's draft release, as it's a very small change. I'll add a note  to check it in the release testing.

### Tablet
Screen Shot 2023-09-14 at 9 33 36 am
Screen Shot 2023-09-14 at 9 35 08 am
Screen Shot 2023-09-14 at 9 34 07 am

### Mobile
Well we have work to do here anyway...
Screen Shot 2023-09-14 at 9 32 03 am

**Pull request merged**
