### PR TITLE
Replace remote_toggle with method inside generic controller

### PR DESCRIPTION
**Pull request by cyrillefr**
- put former remote toggle ctrller `toggle` method in new `toggleAdvancedSettings` in more generic toggle ctrller
 - modified acordingly the 2 associated views
 - put former test code in more generic ctrller test file
 - deleted now useless ctrller + test files

#### What? Why?
See #11928 
Does not close the issue, as this is a replacement for the third of the three old/tailored/legacy controllers.

The replaced controller was used only to toggle advanced settings in a visible/not visible div

#### What should we test?

- Connect as shop admin and go to `admin/order_cycles`
- Chose an order to edit (url should be of the like: `http://localhost:3000/admin/order_cycles/6/edit`
- Click the `Advanced Settings` button (up right under the main menu bar)
- Advanced Settings should be appearing underneath the button.
-  `Close` button should be working and closing the div. 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [X] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice. I'm just wondering if we actually need Javascript for this or could have used the native HTML `<details>` tag.

**Comment by cyrillefr** [comment]
Hello @mkllnk , I did not know about that HTML tag.

I agree with you, at first sight, it could do the job.
There a `close` button and a `save and reload` button in the toggable area to check.

Could it be a future issue/PR ?

**Review by dacook — APPROVED** [review]
Perfect, thank you!

Maikel makes a great point, I wish I thought of that earlier. Oh well, this still reduces the code we have to maintain which is a good move forward.

**Comment by drummer83** [comment]
Hi @cyrillefr,
Thanks for continuing your work on this!

I have tested before and after staging and couldn't see any difference - which is good in this case. :wink: 

I couldn't see any problems in the browser console or in Bugsnag as well, so we're ready to go!
Merging! :tada:

**Pull request merged**
