### PR TITLE
[Spree 2.1] Fix specs in Api::EnterprisesController and Api::ShopsController

### LINKED ISSUE #4957: [Flaky spec] Fix features/admin/variant_overrides_specs currently commented out (2 specs)
spec/features/admin/variant_overrides_spec.rb:193
spec/features/admin/variant_overrides_spec.rb:210

This spec is not failing all the time #flaky

### LINKED ISSUE #5533: [Spree 2.1] Broken spec - EnterprisesController missing routes
Errors:

```
  1) EnterprisesController as an enterprise owner creating an enterprise creates as sells=any when it is not a producer
     Failure/Error: spree_post :create, { enterprise: new_enterprise_params }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:33:in `block (4 levels) in <module:Api>'

  2) EnterprisesController as an enterprise owner creating an enterprise saves all user ids submitted
     Failure/Error:
       spree_post :create, {
         enterprise: new_enterprise_params.
           merge({ user_ids: [enterprise_owner.id, manager1.id, manager2.id] })
       }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:43:in `block (4 levels) in <module:Api>'

  3) EnterprisesController as an enterprise manager submitting a valid image I can update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:71:in `block (4 levels) in <module:Api>'

  4) EnterprisesController as an non-managing user submitting a valid image I can't update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:90:in `block (4 levels) in <module:Api>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5533 and #5504 
Tricky one but this should be it. Some discussion about this can be found in the issues.
Basically this is the fix:
image

#### What should we test?
green specs.
EDIT: the build looks good, these api specs are green.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
It's red...

**Comment by luisramos0** [comment]
yes, it doesnt fix it. But it will be something like this I think. The authorization change is not going in.

**Comment by luisramos0** [comment]
apparently a sleep fixes the problem:
image

**Comment by luisramos0** [comment]
well, actually, the sleep only makes it a bit less flaky, it still fails sometimes. Failed 1 in 3 builds since I added the sleep.

**Comment by luisramos0** [comment]
I have re-used this branch to fix 5533 and 5504, I have hidden previous comments about 4957.

**Pull request merged**
