### PR TITLE
Make "on demand" columns visible by default on "bulk product edit" and "inventory" (variant overrides) tables

### PR DESCRIPTION
**Pull request by ltrls**
This is the PR for #1118, it should be quick to review!

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
@enricostano @sauloperez @pacodelaluna feel free to also code review this if you have time :)

**Comment by sauloperez** [comment]
If I understood correctly the issue this PR is related to, what we want is to add `on demand` column on the bulk edit table with its default value to `true`. In that case, we're missing the change on the template to actually add the column.

**Comment by oeoeaio** [comment]
Was there a discussion about this? I think enabling it be default will make the interface too cluttered. Individual users can make it appear by default for both of these interfaces by setting their column preferences. My vote would be against this as a blanket rule.

**Comment by myriamboure** [comment]
Yes @oeoeaio we have discussed it and agreed with @sstead basically all our users look for it and make mistakes and but stock to 9999 because they don't see the column, so it's important in term of UX to make it visible by default, the table is still  very readable and not heavier... thanks :-)

**Comment by sstead** [comment]
Testing looks good!
On demand shows by default, and the user can then set their column preferences in both Products and Inventory.
image

**Pull request merged**
