### PR TITLE
Update deprecated WickedPdf config syntax

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

While developing, I noticed a deprecation warning.

> WickedPdf.config= is deprecated and will be removed in future versions. Use WickedPdf.configure instead.

So I followed the instructions and simplified it a bit.

#### What should we test?

- Print an invoice.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Nice !

**Review by dacook — APPROVED** [review]
💯 
Thanks for documenting the reason for the page_size!

**Review by filipefurtad0 — APPROVED** [review]
Thanks for pinging me on this one @mkllnk :pray:

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

Checked bulk printing on the orders page, and individually, on the order edit page. Also, I figured it could not hurt to check a report printing to PDF and sending the invoice in that format, as well.

All good, merging.
Thanks!

**Pull request merged**
