### PR TITLE
Require login

### PR DESCRIPTION
**Pull request by mkllnk**
Solving #849.

### CODE REVIEW

**Comment by sstead** [comment]
The 'shopfront requires login' setting is working :) potential rephrase of info tab...
image

If a shopfront requires login, this is the landing message... I think it could be made a bit more friendly (and not red, red is a angry colour :P)? But I assume this is just a placeholder text, and eventually the message will be customisable by the enterprise? In which case this message is fine for now.
image

The only issue I'm seeing is that ANY user can login to see a shopfront currently. It's not yet limited to customers on the enterprise's customer list. I can be a user that's never shopped at that shop before. Or I can be a new user and register with any email and then see the shop (that email isn't confirmed at any point).

**Comment by mkllnk** [comment]
The text can be changed very easily. We can also change the style of the message. But it should be very obvious that it is something new and that you have to read it. If it would look like the normal hub message, people might not read it, because they have read it before and know that there is just some extra information. And then they might wonder why there are no products.

Should people be able to change the message text or layout?

> The only issue I'm seeing is that ANY user can login to see a shopfront currently.

Yes. That was the description. And verifying emails should be on the agenda soon.
Or should we change that to customers of that enterprise only? @oeoeaio Was was the original idea?

**Comment by mkllnk** [comment]
A new version is ready, but not staged yet.

**Comment by mkllnk** [comment]
I found something else. Not only customers should be allowed to see the shopfront. Admins, owners and managers of that enterprise should see it as well.

**Comment by daniellemoorhead** [comment]
@mkllnk so admins, owners and managers of the enterprise can't see the shopfront at the moment, only the customers with correct permissions can?

**Comment by mkllnk** [comment]
That is correct for the deployed version. But I added the rest to the branch already.

**Pull request merged**
