### PR TITLE
[Invoices] Actions dropdown menu disappears after creating the first invoice

### LINKED ISSUE #11049: [Invoices] 'Actions' dropdown menu disappears after creating the first invoice
## Description

Follow up of #10532.

After creating the first invoice the button for the 'Actions' dropdown menu disappears. Leaving and coming back to the invoice page brings it back.

## Expected Behavior

As soon as there is an invoice the actions dropdown menu should be available.

## Actual Behaviour

The menu disappears after the first invoice is created.

## Steps to Reproduce

1. Go to the invoices page.
2. Create a first invoice.
3. Observe the action dropdown menu.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #11049

##### Test the feature
- As a shop manager, go to an order and its invoice panel 
- Click on the `New Invoice` button
Capture d’écran 2023-06-21 à 10 26 07
- Check that an invoice has been generated and the dropdown `Actions` is still functional. 
Capture d’écran 2023-06-21 à 10 26 15

##### Check there is no regression
As a shop manager, check that, in different context, the dropdown `Actions` for an order has no regression.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by abdellani — APPROVED** [review]
LGTM
Thank you @jibees

**Comment by jibees** [comment]
Lots of failing specs, don't know why as:
 - they seems to be unrelated to the changes,
 - they are green locally

**Comment by sigmundpetersen** [comment]
Yeah, that's #11016

**Review by mkllnk — APPROVED** [review]
Great!

**Pull request merged**
