### PR TITLE
3.0 Strong Parameters

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Related to #4641

Starts addressing #4644 

Starts the move towards strong parameters in OFN, and fixes various tests in the `3.0` build. 

Adds some temporary methods to print a list of the related parameters in Semaphore when a test fails due to forbidden params, to help with debugging.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I thought it might be useful to keep the attributes visible in each model until the strong params work is finished. 5ffc5fc and 265afdf should both be tidied up at the end.

**Comment by luisramos0** [comment]
ah, I completely agree with Maikel. I had that exact same comment going through my mind but I ignored it :-)

**Comment by Matt-Yorkley** [comment]
I thought that at first, but after digging in to it I think strong params is the way to go. Partly because Spree is already using it, and partly because the protected_attributes gem actually introduces other issues (and spec failures) that at would need to be fixed in order to _not_ use strong params.

**Comment by luisramos0** [comment]
I am ok with that if you have an idea of the size of the tasks:
A - use protected_attributes gem and fix the problems
B - implement strong parameters in all of OFN 

is A not just a couple of hours and B quite a few days of dev?
I am afraid that implementing (and testing) B could take a while.

**Comment by mkllnk** [comment]
Is there a way in between? Can we keep protected attributes and move to strong parameters where the protected attributes cause trouble?

I agree that strong parameters are the way to go. I just hoped that we can deal with it later.

**Comment by mkllnk** [comment]
Or here is another idea, we could add strong parameters to master to prepare for the upgrade: https://stackoverflow.com/questions/13852534/strong-parameters-in-rails-3-2-8

**Comment by Matt-Yorkley** [comment]
> we could add strong parameters to master to prepare for the upgrade

It's a nice idea, but we would hit the issue that Spree 2.1 has it's strong parameters implementation included and fully integrated into all it's controllers, so to do it in master we would probably have to include some kind of hacky backport into our current Spree version...

**Comment by mkllnk** [comment]
But didn't we import most of Spree's controllers so that the upgrade doesn't help us here and we still have to do it ourselves?

I'm not sure if it's a good idea to have this discussion in asynchronous text. Maybe let's organise a dev call.

**Comment by Matt-Yorkley** [comment]
Yeah, I think we need to merge all the spree back end work into master, merge the other bits in 3-0-stable, then merge master into 3-0-stable, then take a look and come up with a solid plan.

**Comment by luisramos0** [comment]
We need to rebase 30 and create issues for each temp fix that is there.

**Pull request closed without merging**
