### PR TITLE
Creates Stripe spec for split-checkout

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Draft.

Contributes to https://github.com/openfoodfoundation/openfoodnetwork/issues/8667 by adding Stripe coverage for split-checkout.

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
A note to self:

Currently, Stripe UI behaves differently than in staging and allows proceeding to the following steps even with no or incomplete card info:

Peek 2022-02-23 19-46

**Comment by filipefurtad0** [comment]
I'm a bit stuck on this one. For some reason, the UI behaves inconsistently on the test environment.

I'm trying to get a consistent happy-path test, but:

- on `/payment` the UI behaves strangely, and allows to proceed to /summary despite incomplete or incorrect card data.

Peek 2022-02-23 19-46

- on the order confirmation page, we can see that the order is created/confirmed but the payment is not taken:

image

This happens even if we submit complete/valid card info...


What am I missing here? Is there a specific helper for stripe/split-checkout which needs to be called?
Thanks for your help!

PS: I've pushed the files/settings only to allow to make this to be reproducible on other systems, it's not really ready for review.

**Comment by mkllnk** [comment]
The test environment is probably mocking some behaviour which allows the checkout to happen even though the payment isn't taken.

Is the order amount positive?

**Comment by filipefurtad0** [comment]
By running `bundle exec rspec spec/system/consumer/shopping/split_checkout_stripe_spec.rb`; the `byebug`'s are already on the file) and inspecting the order we can see:

i) On step 2 - Payment method

`#<Spree::Order id: 529, number: "R514735230", item_total: 0.1e2, total: 0.1e2, state: "cart", adjustment_total: 0.0, user_id: 1842, created_at: "2022-02-28 22:24:44.528555000 +1100", updated_at: "2022-02-28 22:24:44.854050146 +1100", completed_at: nil, bill_address_id: nil, ship_address_id: nil, payment_total: 0.0, shipment_state: nil, payment_state: nil, email: "ela@skiles.ca", special_instructions: nil, distributor_id: 1215, order_cycle_id: 469, currency: "AUD", last_ip_address: nil, customer_id: nil, created_by_id: nil, included_tax_total: 0.0, additional_tax_total: 0.0>`

ii) On confirmation screen

`#<Spree::Order id: 529, number: "R514735230", item_total: 0.1e2, total: 0.1e2, state: "cart", adjustment_total: 0.0, user_id: 1842, created_at: "2022-02-28 22:24:44.528555000 +1100", updated_at: "2022-02-28 22:24:44.854050146 +1100", completed_at: nil, bill_address_id: nil, ship_address_id: nil, payment_total: 0.0, shipment_state: nil, payment_state: nil, email: "ela@skiles.ca", special_instructions: nil, distributor_id: 1215, order_cycle_id: 469, currency: "AUD", last_ip_address: nil, customer_id: nil, created_by_id: nil, included_tax_total: 0.0, additional_tax_total: 0.0>`

So the order does not advance from cart, and all the details like bill, ship address, even customer, are empty. I'll create a complete order and see if issues i) and ii) still occur with Stripe.

**Comment by RachL** [comment]
hello @filipefurtad0 are you still working on this one?

**Comment by filipefurtad0** [comment]
Thanks @RachL and sorry for the delay in the reply - lost it out of sight :see_no_evil: 

We can close this. It remains a challenge (Stripe testing on split checkout) but this PR brings no improvement so far, which will hopefully come after #9034 works. So I think we can close one for now.

**Pull request closed without merging**
